### ISSUE TITLE
Octree 

### ISSUE THREAD

**Issue by fotsing365** [CloudCompare/CloudCompare#1002]
Hi,
I would like to know if  it is  possible in the code  to recover the portion of point cloud  in a cell of an octree? For example after computing `cloud->getOctree();` I apologize for my bad english.
thanks.

**Comment by dgirardeau** [comment]
Yes, definitely. See the DgmOctree::getPointsInCell method:
https://github.com/CloudCompare/CloudCompare/blob/03342f56a36f1bd4521cbce1d894a722f1d73e97/CC/include/DgmOctree.h#L563

(To get the cell code - that you have to give to the getPointsInCell method), you have to use the GenerateTruncatedCellCode method)
