### ISSUE TITLE
Command Line Compute Normals guessing the Octree radius

### ISSUE THREAD

**Issue by petrasvestartas** [CloudCompare/CloudCompare#1006]
Hi,

I am using cloudcompare compute normals function via command line.
Each time I need to write Octree radius, if it is really off the application crashes.

Is there any way to call the compute normals method in such a way that the Octree radius is chosen automatically? Just like in the cloudcompare software?

I want to get this value automatically:
![Normals](https://user-images.githubusercontent.com/18013985/69361488-407fd000-0c95-11ea-834b-ad7d274ccc7c.png)

Now I am filling these values manually:
 Arguments = "-SILENT -COMPUTE_NORMALS -O " + filepath_ + " -NO_TIMESTAMP -C_EXPORT_FMT " + exportFormat + " -MERGE_CLOUDS -OCTREE_NORMALS "+ **OctreeNormals**  +" -ORIENT_NORMS_MST " + OrientNormals,

**Comment by dgirardeau** [comment]
That's currently not possible.

**Comment by petrasvestartas** [comment]
Is there any way to approximately know this number? 

It makes then this function hardly usable if the number is not known before running actual software. 

It would help that by default this number is computed if the user does not give any input.

**Comment by dgirardeau** [comment]
This value should mostly depend on the scale of the cloud (and features represented by the cloud). And secondarily on the cloud density.

**Comment by petrasvestartas** [comment]
How does it work on structured grids? Is ot possinle to share a code? I have a grid of million points from  faro scanner

**Comment by dgirardeau** [comment]
Ah you are lucky (regarding your first question). A new addition to CC allows you to set 'auto' instead of the radius ;)

Otherwise for using scan 'grids', just look at the code directly:
https://github.com/CloudCompare/CloudCompare/blob/d37af7907bbbbd0c34193eec4334ece53323c5d5/libs/qCC_db/ccPointCloud.cpp#L5096

**Comment by petrasvestartas** [comment]
Is it possible to show the example for auto radius in command line?

Do I need to download new cloudcompare?

**Comment by dgirardeau** [comment]
Yes you have to download the latest one. And you just have to type '-OCTREE_RADIUS auto' (see wiki for more options, etc.)

**Comment by petrasvestartas** [comment]
Thank you so much for building this option for me:) It works perfectly.

I hope I can attend the workshop for CloudCompare in France, I see that the developer workshop is fully booked. I tried to send organizers if there would be a possibility to attend it.

**Comment by dgirardeau** [comment]
Oh this option was not developed for you. This is why you are lucky ;).

**Comment by petrasvestartas** [comment]
Ech, it does compute the normals, but the result in Poisson reconstruction is totally different than using cloudcompare auto radius. Any idea how to get result as on the image on the left with correct radius?

![Result](https://user-images.githubusercontent.com/18013985/69535419-8d5cf280-0f84-11ea-8f2d-597d28e14f24.png)

**Comment by dgirardeau** [comment]
You also have to set the orientation correctly...

**Comment by petrasvestartas** [comment]
I was doing the ORIENT_NORMS_MST with 6 neighbors, it does help but it seems that the compute pointcloud normals change a little bit from previous CC versions.

There is another issue is when running Cloud compare via command line in 2.11. 
Before I could write proc.WaitForExit() and the command line waits until CC is done with computing.
Now the software hangs.
The only solution is to make the thread sleep for approximately the computation time.
proc.WaitForExit(someseconds)

**Comment by dgirardeau** [comment]
ORIENT_NORMS_MST will (try to) make all normals with the same orientation, but it doesn't know if they are all in the right direction or all in the opposite direction (you may have to call 'invert normals' afterwards, even in the GUI version).

And regarding the fact that the processus doesn't finish, it is apparently due to a warning message issued by PDAL (3rd party library used to load LAS files). Not sure exactly where it comes from.

**Comment by petrasvestartas** [comment]
Sorry for spamming too much. I give up with auto mode.

I do not know what is happening but the auto mode produces different results each time for the same cloud and the process is hanging as you mentioned. 

![Question](https://user-images.githubusercontent.com/18013985/69571482-d33ca980-0fca-11ea-801b-dd92583e903e.png)

**Comment by dgirardeau** [comment]
Auto mode is random ;) (we randomly select 100 points and we look at their neighborhood).
