### ISSUE TITLE
Identify flat areas of cylindrical scan

### ISSUE THREAD

**Issue by petrasvestartas** [CloudCompare/CloudCompare#1011]
This is not a bug, but asking for an advice.

I have a kind of cylindrical object scan whose end parts are flat.
What would the best way to identify those flat parts?
I was thinking about computing pointclouds normals and clustering them according to direction, but I have a feeling that something like this is already existing.

The scan is literally a tree branch that was cut with a saw.

![question](https://user-images.githubusercontent.com/18013985/69668423-86270900-1098-11ea-8195-94cdaec2f34c.png)

**Comment by WargodHernandez** [comment]
There are a number of possible ways to work this, including ransac for planes & cylinders.
If you want a bit more control I did something similar by using the PCA alignment and then taking the first and last inch or so with cropping tool. Then iterativly fitting planes to those capped regions.
Some of those steps are available in CC today, the iterative plane fitting routine isn't yet there, I plan on adding it within the next week or so. 
But either way it would be a fairly manual process in comparison to finding decent ransac parameters

**Comment by petrasvestartas** [comment]
I am actually searching for the library that I could run in .NET environment.
Yesterday I managed to run RANSAC from Accord.NET C# library, but it only works when there more than 50 % inliners that outliners.

I see there are PCL segmentation methods for finding planes in plointcloud, but it is quite hard for me to comprehend the full C++ world as a .NET user.

**Comment by GreKro** [comment]
Hi, 
If you have small amount of data you can use RANSAC Shape Detection Plugin by hand in CloudCompare (Plugins - RANSAC Shape Detection), this functionality unfortunately is not avalible via Comand Line Mode yet.  
If you want to automate this process you can  try python-pcl (https://github.com/strawlab/python-pcl).
For me it is the easiest way to configure  PCL environment on Windows.  RANSAC shape detection is avalible in this python implementation. If you have exprience with programming in .NET, Im pretty sure that you will be able to write simple python tool to use RANSAC plane detection.   
look at these example use of ransac plane detection:

import pcl
import numpy as np
p = pcl.PointCloud(np.array([[1, 2, 3], [3, 4, 5]], dtype=np.float32))
seg = p.make_segmenter()
seg.set_model_type(pcl.SACMODEL_PLANE)
seg.set_method_type(pcl.SAC_RANSAC)
indices, model = seg.segment()
