### ISSUE TITLE
CloudCompare cannot load files specified via relative paths

### ISSUE THREAD

**Issue by oleg-alexandrov** [CloudCompare/CloudCompare#1013]
I have a point cloud in the current directory, on Linux, which I try to open as:

ccViewer mycloud.ply

and it fails to load it.

Yet, if I specify the full path to it, like /path/to/mycloud.ply, then it works.

It is pretty standard for any Linux and Mac tool to understand relative paths. Is there are reason why ccViewer cannot handle it? Thanks.

**Your environment**
 - CC Version (or git hash/tag):  1.38, latest from GitHub
 - OS & Version: Ubuntu Linux 16.04
 - Graphics card: 
 - Qt Version (if compiling):  5.6

**Comment by dgirardeau** [comment]
I believe ccViewer uses its executable path as the 'default' path (not the one you are calling it from).

**Comment by oleg-alexandrov** [comment]
Thank you. Then ccViewer is inconsistent with both CloudCompare and also any other tool I ever used for any purpose.  I don't see why a user would want to store clouds in the directory where the tool itself is stored, in fact any other design decision, as to make the default path point to Desktop, or user home folder would make a lot more sense than what it does now.
