### ISSUE TITLE
What's the principle of GuessBestRadius and how to cite CloudCompare in paper?

### ISSUE THREAD

**Issue by Crocs512** [CloudCompare/CloudCompare#1016]
Hi!

If it is possible, I want to know how to compute an automatic radius for each point.

And I want to know if there is a BibTeX to cite CloudCompare. 

Looking forward to your help. Thanks!!!

**Comment by dgirardeau** [comment]
Automatic radius for each point would be super expensive (but there might be some articles about that). Anyway it will depend a lot on the application (depending on what you are targeting, etc.). In CC we use a fixed radius in most of the cases.

And regarding citations, no BibTeX is available on our side, just this forum topic: https://www.cloudcompare.org/forum/viewtopic.php?f=2&t=146
