### ISSUE TITLE
Point Cloud  Display Error

### ISSUE THREAD

**Issue by xq198109** [CloudCompare/CloudCompare#1017]
**Describe the bug**

**How to reproduce**

 
**Additional context**

**Your environment**
 - CC Version (or git hash/tag):cc 2.10.2
 - OS & Version: Win 10
 - Graphics card: rtx2080
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
Can you describe the issue a little bit more? ;)

**Comment by xq198109** [comment]
**How to reproduce**
1. Go to Open LAS File
2. Click on 'No'  in Gloable Shift and Scale Dialog
3. Change View port
4. See error

 
**Additional context**
 
![image](https://user-images.githubusercontent.com/48425847/71576072-49807e80-2b2a-11ea-90bb-1b2ef30b9d9f.png)

**Comment by xq198109** [comment]
if Click on 'Yes' in Global Shift and Scale Dialog,the error will disappear

**Comment by dgirardeau** [comment]
That's not a bug... that's the whole purpose of the 'Global Shift' mechanism.

You can get the full explanation by clicking on the 'question mark' next to the warning **'Coordinates are too big! (original precision might be lost)!'**

![image](https://user-images.githubusercontent.com/2735509/71577000-c5f76b00-2af2-11ea-8009-3c3e8ab01c8c.png)
