### ISSUE TITLE
Support for cgal 5.x

### ISSUE THREAD

**Issue by alexmyczko** [CloudCompare/CloudCompare#1018]
The bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947474

The build logs: https://buildd.debian.org/status/package.php?p=cloudcompare&suite=sid

**Comment by dgirardeau** [comment]
Not sure to understand (I'm not the Linux expert here): how would a new release help here?

**Comment by alexmyczko** [comment]
not at all :) it is actually one issue and one wish absolutely unrelated to eachother

**Comment by WargodHernandez** [comment]
So looking at the logs a bit, it looks like (At least for Arm64, the other failures appear similar) the builds had been successful for versions up to 2.10.3-3+b1, and failing started at 2.10.3-3+b2.

Looking at the errors showing up it appears CGal isn't working on the newer b2 version as the first failures in the actual build show up after 

```
In file included from /usr/include/CGAL/Kernel/global_functions.h:25,
                 from /usr/include/CGAL/Cartesian/Cartesian_base.h:22,
                 from /usr/include/CGAL/Simple_cartesian.h:20,
                 from /usr/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20,
                 from /<<PKGBUILDDIR>>/CC/src/Delaunay2dMesh.cpp:28:
/usr/include/CGAL/Kernel/hash_functions.h:25:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type; did you mean ‘enable_if’?
   25 | inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
      |             ^~~~~~~~~~~
      |             enable_if
```
Not all of the errors are listed here just the first ones that are new for b2.

Looking at the cgal version listed in the build toolchain for b1 and b2
b1 (Success)
```
libcgal-dev_4.14-5
libcgal-qt5-14_4.14-5
libcgal-qt5-dev_4.14-5
libcgal13_4.14-5
```

b2 (Failure)
```
libcgal-dev_5.0-3 
libcgal-qt5-dev_5.0-3
```

CC source is unchanged between these different builds only the build environments appear to change.

is this what you are trying to report as an error?

**Comment by alexmyczko** [comment]
Thanks for pointing that, I just didn't see it.

**Comment by WargodHernandez** [comment]
Cgal 5.x looks like a pretty major change https://www.cgal.org/2019/11/08/cgal50/
It's c++14 minimum and it also has a few breaking changes that I believe we are possibly affected by (there are breaking changes in point set processing, 2d triangulation and 3d triangulation)

**Comment by dgirardeau** [comment]
I believe @rjanvier was the first to integrate CGAL (4.x I presume). Romain, any thought about moving to CGAL 5.x?

**Comment by WargodHernandez** [comment]
Until support is added can we limit the version in CGALSupport.cmake to versions 4.3 to 4.14.2(The latest 4.x release). I'm not a CMake expert at all but it seems like Find_package can target versions

actually after looking for version ranges I can't seem to find if we at least specify the Major version 4 in the search it shouldn't crash with a 5.x lib

`FIND_PACKAGE( CGAL [VERSION 4] QUIET COMPONENTS Core )`

**Comment by dgirardeau** [comment]
Yes good idea. We would at least detect the issue before hand.

**Comment by alexmyczko** [comment]
thanks
