### ISSUE TITLE
[snap] Could not initialize GLX

### ISSUE THREAD

**Issue by hermannsblum** [CloudCompare/CloudCompare#1026]
**Describe the bug**
Same bug as #916, but I cannot reopen that issue.

**How to reproduce**
```
snap install cloudcompare
cloudcompare.CloudCompare
```

**Expected behaviour**
cloudcompare opens

**Additional context**
```
> cloudcompare.CloudCompare       

(process:19505): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Could not initialize GLX
[1]    19505 abort (core dumped)  cloudcompare.CloudCompare
```

I tried all the things suggested in #916. I installed `qt5-default` and also have the `core` snap installed. All is on newest versions.

**Your environment**
```
> snap --version        
snap    2.42.5
snapd   2.42.5
series  16
ubuntu  18.04
kernel  5.3.0-26-generic
```

**Comment by dgirardeau** [comment]
Are you using a remote desktop connection maybe? This generally doesn't work.

**Comment by nachovizzo** [comment]
I'm having the same erros here:
```
snap    2.42.5
snapd   2.42.5
series  16
ubuntu  18.04
kernel  4.15.0-76-generic
```
And then
```sh
cloudcompare.CloudCompare                                                              

(process:21406): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Could not initialize GLX
[1]    21406 abort (core dumped)  cloudcompare.CloudCompare
```

No remote connection.

**Comment by hermannsblum** [comment]
I am also not using a remote connection.

**Comment by nachovizzo** [comment]
@dgirardeau Is there any way I can help?

I think that the issue might be related to NVIDIA drivers

**Comment by dgirardeau** [comment]
Sorry I can't personally help you on this one (I don't use Linux ;)

**Comment by hermannsblum** [comment]
> I think that the issue might be related to NVIDIA drivers

Seeing this comment, I tried again to install the snap. I recently had some other troubles with my nvidia driver and re-installed the driver.  
After re-installing the nvidia driver, cloudcompare launches without problems.

**Comment by rjanvier** [comment]
thanks. Are you using drivers from Ubuntu repositories?

**Comment by hermannsblum** [comment]
Yes, all drivers were nvidia drivers installed with the ubuntu driver tool. However, I don't remember the exact version that I had before and where the error occured.
