### ISSUE TITLE
C2C_DIST not saving output

### ISSUE THREAD

**Issue by benrazor** [CloudCompare/CloudCompare#1029]
**Describe the bug**
When running the `-c2c_dist` command from the command line in Windows, the command seems to be executed as expected, but CC log window exists without saving the output cloud (the SAVE operation doesn't appear in the log and isn't executed)

**How to reproduce**
From Windows CMD run: 
  `CloudCompare.exe -o cloud1.las -o cloud2.las -c2c_dist`
or:
  `CloudCompare.exe -o cloud1.las -o cloud2.las -c2c_dist -save_clouds FILE out.bin`

**Expected behaviour**
The output distance cloud should be saved after execution

**Additional context**
Other commands (e.g. `-m3c2`) save the output cloud as expected (even without using `-save_clouds`)
Simply opening and saving a cloud works as well (`-o cloud.las -save_clouds FILE out.bin`)

**Your environment**
 - CC Version (or git hash/tag): 2.11 alpha (Anoia) [Windows 64-bit]
 - OS & Version: Windows 10 Home, 64-bit
 - Graphics card: NVIDIA GeForce GTX 1060 6GB

**Comment by dgirardeau** [comment]
Hum, the only reason why this would happen is that something goes wrong (either the C2C distance algorithms declares an error, or the process crashes!).

**Comment by benrazor** [comment]
> 
> 
> Hum, the only reason why this would happen is that something goes wrong (either the C2C distance algorithms declares an error, or the process crashes!).

I didn't see any errors in the log. The algorithm works and produces an output when I apply it from within the GUI, where I'm able to save it manually.
Also, I tried running it from the command line on different Windows computers with different clouds - the output was never saved. When I tried doing the same with the same clouds in Ubuntu, it worked flawlessly and saved the output file as expected.

**Comment by dgirardeau** [comment]
Have you seen the warning about the large coordinates? With the command line mode, you have to explicitly indicate how the clouds should be shifted (with -GLOBAL_SHIFT ...). Otherwise, you'll lose accuracy, and maybe the clouds won't end close to each other. In which case it may make the distance computation result weird.

Of course, here you don't even have a result ;).

Can you maybe share the clouds with me (and the exact command line arguments in case they are slightly more complicated than your example): admin [at] cloudcompare.org

**Comment by benrazor** [comment]
I sent you a link to a google drive folder containing two clouds. I tried them with the following **exact** command line arguments:

`CloudCompare.exe -o -global_shift auto C:\Users\User\clouds\cloud1.las -o -global_shift auto C:\Users\User\clouds\cloud2.las -c2c_dist`

The log this time:
![image](https://user-images.githubusercontent.com/46484840/73741294-9b807980-4752-11ea-9c51-d3dedb48f01f.png)

**Comment by dgirardeau** [comment]
Thanks. Can you share the google drive link with my personal email address? (daniel.girardeau @ gmail.com). I can't retrieve them with the 'admin' version.

**Comment by benrazor** [comment]
sure, 
just did.

**Comment by dgirardeau** [comment]
Thanks I'll look at that asap.

**Comment by dgirardeau** [comment]
Ok, so in the end, it was a bug (due to a recent change). The process was internally causing an error and was silently exiting before finishing the work.

Here is the fix: 61f128d95218a12d565186da6fb982c0e4bc9f57

And I updated the online version (2.11.alpha, **non stereo** version)

**Comment by dgirardeau** [comment]
And thanks for the feedback ;)

**Comment by benrazor** [comment]
Great, works perfectly!
Thanks for the quick response! 🥇👍
