### ISSUE TITLE
qPCL plugin crash on exit

### ISSUE THREAD

**Issue by WargodHernandez** [CloudCompare/CloudCompare#1051]
CC crashes while closing the program after using either MLSSmoothingUpsampling or NormalEstimation from the qPCL plugin. This happens in the respective destructors calling delete on the associated dialog. The intent of the if guards, should have prevented the delete as the parent shouldn't be == 0. 
![image](https://user-images.githubusercontent.com/7495752/75300243-1d147600-57ec-11ea-98e2-698d4f860dbc.png)
![image](https://user-images.githubusercontent.com/7495752/75300305-4f25d800-57ec-11ea-8442-67e586680eb5.png)

I suspect the parent pointer is already invalidated by this point.

**Your environment**
 - CC Version 2.11
 - OS & Version: Win 10.0.17763 
 - Graphics card: Nvidia Quadro M2200
 - Qt Version (if compiling): 5.11.2

**Comment by dgirardeau** [comment]
Actually the issue was that Qt had already deleted the dialogs when the destructors of the tools were called. Therefore the pointer was not valid anymore. Commit 8bf76eaa49eb5f87d6ce05a97909e6f4c2a24857 should fix this.
