### ISSUE TITLE
-silent flag in ubuntu seems to have no effect in -c2c_dist

### ISSUE THREAD

**Issue by benrazor** [CloudCompare/CloudCompare#1055]
**Describe the bug**
Running the `-c2c_dist` command from the terminal in Ubuntu pops up the CloudCompare console regardless of whether the `-silent` flag is used or not.
(In Windows the flag has the desired effect)

**How to reproduce**
Run:
`/snap/bin/cloudcompare.CloudCompare -silent -auto_save off -O '/path/cloud_1.las' -O 'path/cloud_2.las' -C2C_DIST`

**Expected behaviour**
The algorithm should run silently (solely in the terminal, without any windows popping up)

**Your environment**
 - CC Version (or git hash/tag): 2.10.1
 - OS & Version: Ubuntu 18.04.4
 - Graphics card: GeForce GTX 1060

**Comment by rjanvier** [comment]
hey thanks for the report. Could you try the last snap package (into the edge channel) it should be fixed. thank you.

**Comment by rjanvier** [comment]
I close this do to inactivity and it seems to be fixed. Please do not hesitate to reopen it
