### ISSUE TITLE
Shapefiles behave differently between version 2.9 and 2.10

### ISSUE THREAD

**Issue by CraigGIS** [CloudCompare/CloudCompare#1058]
**Describe the bug**
I have a script that runs in ArcCatalog v10.4.1 which runs on shapefiles saved from cloudcompare containing multi-point objects.  If I save the shapefile out of version 2.9, the script runs fine.  If I save the same shapefile containing the same data out of version 2.10, the script in Arc crashes.  I can convert identical data by opening it and saving it in the other version, but I would like to upgrade and leave 2.9 behind but can't do that until this is resolved.

**How to reproduce**
Save a shapefile out of CC Version 2.10 containing a small multi-point object (a point cloud).  In Arc Catalog, run the 'Buffer' Tool on that shapefile.  

**Expected behaviour**
I expect shapefiles to behave exactly the same between versions.

**Additional context**
The arc crash message is as follows, although I'm not sure this will help you.

Traceback (most recent call last):
  File "F:\6601 4Front VA National Cemetery\GIS\Tools\ArcpyScripts\PointCloudToCSV.py", line 47, in <module>
    arcpy.Buffer_analysis(inFilePath, bufferUnited, bufferDist, "FULL", "ROUND", "ALL", "#", "PLANAR")
  File "c:\program files (x86)\arcgis\desktop10.4\arcpy\arcpy\analysis.py", line 692, in Buffer
    raise e
ExecuteError: ERROR 999999: Error executing function.
An error occurred during the buffer operation
Failed to execute (Buffer).

Failed to execute (PointCloudtoCSV).

**Your environment**
 CC Version 2.10
 Windows 7 Pro
 - Graphics card: Nvidia Quadro 4000
 - Qt Version (if compiling):  NA

**Comment by dgirardeau** [comment]
Can you try with the latest 2.11.beta version? I remember there was a bug in the 2.10 version with SHP files indeed.

**Comment by CraigGIS** [comment]
Daniel, The latest 2.11 beta version worked perfectly, thanks a bunch!
