### ISSUE TITLE
Hierarchy export type support in CommandLine

### ISSUE THREAD

**Issue by WargodHernandez** [CloudCompare/CloudCompare#1075]
I propose adding `
-H_EXPORT_FMT {format}`
and properly support exporting `CLGroupDesc : CLEntityDesc`
to support exporting Hierarchies properly in command line mode.

currently if you call `ccCommandLineParser::exportEntity(	CLEntityDesc& entityDesc,` with a `CLGroupDesc` object the logic only correctly handles cloud or mesh

```C++
bool isCloud = entity->isA(CC_TYPES::POINT_CLOUD);
isCloud |= forceIsCloud;
QString extension = isCloud ? m_cloudExportExt : m_meshExportExt;
```
a group object passed through this will incorrectly be labeled as a mesh.

with the default bin filter this still all works but if a user changes `-M_EXPORT_FMT  PLY` before a hierarchy is passed to cmd.exportEntity the group object will be passed to the PLY filter which does not support HIERARCHY_OBJECT or multiples.

I export hierarchy groups in QRansac command line, and I realized we may have issues because of it.

**Comment by WargodHernandez** [comment]
It looks like we currently take advantage of this logic for the allAtOnce parameter used in saveClouds and saveMeshes.
I modified exportEntity to work with the H_EXPORT_FMT command and for my purposes it all worked. But using allAtOnce for meshes or clouds would then use the hierarchy format which wouldn't be correct.

@asmaloney @dgirardeau @rjanvier 
What are the opinions on either adding a exportEntityGroup function or modifying exportEntity parameter list to add an optional bool forceIsHierarchy similar to the existing forceIsCloud, I just don't like having a long string of bools for a parameter list in a public interface.

**Comment by asmaloney** [comment]
My vote would be to not add more methods, and not add a new bool param, but instead define and use [flags](https://doc.qt.io/qt-5/qflags.html).

Cleans it up and leaves room for easy expansion in the future (and it's not limited to `force*` options - could be anything else).

**Comment by WargodHernandez** [comment]
I'm fine with that.
Are you voting for replacing
```C++
QString ccCommandLineParser::exportEntity(	CLEntityDesc& entityDesc,
											QString suffix/*=QString()*/,
											QString* baseOutputFilename/*=0*/,
											bool forceIsCloud/*=false*/,
											bool forceNoTimestamp/*=false*/)
```
with 

```C++
QString ccCommandLineParser::exportEntity(	CLEntityDesc& entityDesc,
											QString suffix/*=QString()*/,
											QString* baseOutputFilename/*=0*/,
											SOMENEWFLAGTYPE exportFlags/*=defaultflag*/)
```

or

```C++
QString ccCommandLineParser::exportEntity(	CLEntityDesc& entityDesc,
											QString suffix/*=QString()*/,
											QString* baseOutputFilename/*=0*/,
											bool forceIsCloud/*=false*/,
											bool forceNoTimestamp/*=false*/,
											SOMENEWFLAGTYPE exportFlags/*=defaultflag*/)
```
??

**Comment by asmaloney** [comment]
I would do the first & just clean it up.

So in **ccCommandLineInterface**, declare something like:

```cpp
    enum ExportOption {
        NoOptions = 0x0,
        ForceCloud = 0x1,
        ForceHierarchy = 0x2
        ForceNoTimestamp = 0x4
    };
    Q_DECLARE_FLAGS(ExportOptions, ExportOption)
 ```

Then the interface is:

```cpp
CLEntityDesc& entityDesc,
			const QString &suffix,
			QString* baseOutputFilename,
			ccCommandLineInterface::ExportOptions options);
```

(I also made _suffix_ a const ref assuming it should be...)

**Comment by WargodHernandez** [comment]
Yeah looks good, I'll get that started.

**Comment by WargodHernandez** [comment]
Any reason you chose enum vs enum class?
I made it an enum class out of habit

**Comment by asmaloney** [comment]
Nope - I was just following the example from [QFlags](https://doc.qt.io/qt-5/qflags.html). I'm not sure if I've tried using QFlags with an enum class.

**Comment by WargodHernandez** [comment]
It appears to work, this is my first time messing with QFlags so I wasn't sure
