### ISSUE TITLE
GitHub actions not building Linux

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#1080]
**Describe the bug**

GitHub actions should also build on Linux.

**Comment by rjanvier** [comment]
Why?

**Comment by WargodHernandez** [comment]
Its because for some reason we aren't seeing the Travis results anymore (they still are being run though)
if you look at the last PR merged the checks that were run are reported like this
![image](https://user-images.githubusercontent.com/7495752/77800001-33a02e00-7033-11ea-83c2-1e42b55716ac.png)
All Travis results are gone

but you can see them in Travis
![image](https://user-images.githubusercontent.com/7495752/77800136-621e0900-7033-11ea-9772-3c1a4187e055.png)


So I think the issue should be to resolve whatever is preventing the Travis results from showing or add Linux to Github Actions

**Comment by rjanvier** [comment]
...Or use Travis for windows and macOS builds, because it’s also possible...

**Comment by WargodHernandez** [comment]
Yeah I don't think we care too much as long as all three platforms are tested, and results easy to see.
Also at reasonable speed for free. :)

**Comment by WargodHernandez** [comment]
Looking at our build minutes for the last week of Travis we should probably stick with Travis if 3000 mins is the Github limit.

We used ~33 minutes processing time per build, and had 30 builds in the last 7 days
30 * 33 = 990 minutes per week
4 weeks per month = 3960 minutes per month processing.

rough numbers but yeah I think we will need more than 3000 on a semi regular basis

**Comment by asmaloney** [comment]
I'm sure GitHub actions will handle Linux if it's configured properly.

I think we should pick one or the other, not both. I don't have a strong opinion about which one. I have experience with Travis in several projects and zero experience with GitHub's stuff.

**Comment by rjanvier** [comment]
seems ok on last @asmaloney PR
![Capture](https://user-images.githubusercontent.com/1537100/77820386-34dc6400-70e2-11ea-832a-9f1172751c05.JPG)

**Comment by asmaloney** [comment]
Again:

>  I think we should pick one or the other, not both.

**Comment by rjanvier** [comment]
I saw no problem using two CI systems if they do the job (and according to the last snapshot they do). I really do not see the issue here. The only issue I see right now is maybe the pricing policy of GA. If you want to homogenize CI systems then please change the title of the issue accordingly.

**Comment by tmontaigu** [comment]
> Looking at our build minutes for the last week of Travis we should probably stick with Travis if 3000 mins is the Github limit.
> 

From what I understand Github actions are free (unlimited time) for public repos, but for private repos you have x minutes depending on your plan
[About billing for github actions](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions#about-billing-for-github-actions)

**Comment by asmaloney** [comment]
Why should we maintain two CI systems? Ultimately they do the same thing. So we get no benefit and some extra support burden.

**Comment by rjanvier** [comment]
Do whatever you think is right, but my opinion the support burden here is OS dependant and not CI dependant. 
If you move to GA, the only thing I want to keep on LInux CI is the use of base package from Ubuntu (apt) and not from a third party package manager (conda) like it's done for other OSes.
