### ISSUE TITLE
GitHub actions should use multiple jobs (if available)

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#1081]
**Describe the feature you would like**

When compiling it looks like it's doing one file at a time which is quite slow. It takes 15 minutes (macOS) to 27 minutes (Windows) to do a build.

Travis took between 3 and 13 minutes (for Linux).

Maybe there's a way to use multiple jobs like you can in Travis? (i.e. compiler options like -jN for clang where N is the number of processors)

**Comment by tmontaigu** [comment]
Windows Builds should also use Ninja as it might help reducing build time

**Comment by asmaloney** [comment]
What needs to be done to make Windows use ninja?

I don't use ninja, or Windows (much), or GitHub Actions, so I have no clue here.

On the Travis side, the time differences are actually gcc vs. clang, not based on SCALAR_DOUBLE. The gcc builds have always been faster than the clang ones for this project. 

I _think_ part of it is templates and part is the number of includes (& amount of code included), but without profiling, it's just a guess. I haven't done much profiling of compile times...

**Comment by tmontaigu** [comment]
it should be as easy a installing ninja  during the conda step (and remove the brew install ninja for macos) and changing the generator used on windows to Ninja

**Comment by asmaloney** [comment]
@tmontaigu would you mind switching Windows to ninja? It would be nice to have the Windows build times more in line with the rest.

Thanks!

**Comment by asmaloney** [comment]
Should be addressed by #1112 (using the Visual Studio generator which can do parallel builds).

Thank you @tmontaigu.
