### ISSUE TITLE
Discussion: cmake structure & TBB

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#1090]
I want to discuss how we set up and use TBB in the cmake files. I think it's handled in the wrong place and in the wrong way.

I think some of the complication comes down to the issue of [CCLib](https://github.com/CloudCompare/CloudCompare/issues/897) and trying to keep it usable/buildable without building all of CC.

1) We have a cmake option `COMPILE_CC_CORE_LIB_WITH_TBB`. This is checked in _CmakeExternalLibs_ which is included in the top level of the CC repo (for CC & viewer), and in the CCLib cmake files.

2) TBB is used in CCLib and CloudCompare/viewer, so this option name is not great.

3) It should be using cmake targets properly which means moving things around a bit.

4) _CmakeExternalLibs_ is now sort of a common "bridge" between building CCLib and CC/viewer - i.e. it's used in both.

The question is where do we put this option so that it can be used in CCLib (if built on its own) and in CC/viewer?

1) We can leave it where it is and change the option name. Then we should probably rename this cmake file and put it somewhere so it's clear it's an "interface" between CCLib and CC/viewer - i.e. changes here effect both.

2) Move the option to CCLib and then add `COMPILE_WITH_TBB` to the top level.  This top-level one would control the CCLib one. This keeps things cleaner and would help when we try to separate CCLib into its own repo later on.

Then CCLib can be compiled on its own, and CC/viewer controls whether TBB is used or not.

3) Other suggestions?

I'm leaning towards (2) because I don't like trying to factor out common CCLib & CC/viewer things. CCLib needs to live on its own.

(Incidentally this has come up because I'm trying to solve the OpenMP problem on macOS, but I don't want to muddy the waters here.)

**Comment by WargodHernandez** [comment]
I would vote for Option 2.

**Comment by asmaloney** [comment]
@WargodHernandez I see you add "CC NextGen" - the reason I'm bringing it up now is that I need to do something similar with OpenMP in order to get it to work. (The other suggestion in that thread you mentioned that I mentioned ;-) does not work in our case. I need to move to the target version.) TBB is just an easier example at the moment since it's clearer.

An alternative is for me to just disable OpenMP for macOS and deal with this after release - which I'm fine with. The Mac version has never compiled with OpenMP on anyways.

**Comment by WargodHernandez** [comment]
@asmaloney it doesn't matter to me much, I just think it would make sense to leave stuff as tested as much as possible if we are calling it a release vs another beta.

**Comment by dgirardeau** [comment]
I personally don't use TBB, so I'll let you handle it the way you prefer :D

**Comment by rjanvier** [comment]
I'm in favor of (2) but we already came to the consensus (elsewhere, in c++14 thread) that this kind change should target "CC Next" and not 2.11.
Maybe (3) is having the option only available for CCLib but it should "propagate/indicate" the use of TBB to other binaries (qCC/viewer) by the mean of a cmake [configuration file](https://cmake.org/cmake/help/v3.4/module/CMakePackageConfigHelpers.html). It's just a proposal here, I really don't know what would be the most convenient.

**Comment by asmaloney** [comment]
Now that CCCoreLib has been separated, this is implemented as follows:

- CCCoreLib has a setting `CCCORELIB_USE_TBB` which controls whether or not to use TBB
- when this is set, it adds `CC_CORE_LIB_USES_TBB` to the library's _target_compile_definitions_
- when CCCoreLib is linked to using _target_link_libraries_, the compiler definitions come along with it, so `CC_CORE_LIB_USES_TBB` is available in the main application
