### ISSUE TITLE
qFacets plugin crashes during program exit

### ISSUE THREAD

**Issue by WargodHernandez** [CloudCompare/CloudCompare#1091]
Open stereogram from the qFacets plugin.
Close CloudCompare
crash

**Your environment**
 - CC Version (or git hash/tag): 2.11.beta
 - OS & Version: Window 10 
 - Graphics card: NVIDIA Quadro M2200
 - Qt Version : 5.11.2

![image](https://user-images.githubusercontent.com/7495752/78058950-edeaaa80-733d-11ea-9895-a4a3cac30db1.png)

**Comment by asmaloney** [comment]
Reproduced on macOS.

The correct solution is probably to use [Q_GLOBAL_STATIC](https://doc.qt.io/qt-5/qglobalstatic.html#Q_GLOBAL_STATIC), but this will require some changes to `StereogramDialog` since the constructor cannot be called with arguments.

I'm happy to tackle this if you're busy on other things.

**Comment by WargodHernandez** [comment]
Thanks @asmaloney , I'm looking into some RANSAC stuff currently, so I'd appreciate that

**Comment by asmaloney** [comment]
I've fixed the crash (no reason to use globals at all here).

But what should I be seeing when I select a cloud and choose "show stereogram" and use the default params? I've tried it on several things and I don't see anything happening.

**Comment by WargodHernandez** [comment]
It's not obvious but your cloud has to have normals.
I had to play around with it to figure that out, the first time I used it was with normals so I saw the expected behavior before the nothing happens behavior

**Comment by asmaloney** [comment]
Ah thanks!

I'll file another issue then :-) It should complain if the selected cloud doesn't have normals.

**Comment by dgirardeau** [comment]
Actually this tool can also be used with a group of 'facets'. This makes the activation/deactivation of the option a little bit tricky.

But I guess you could definitely display an error message if you realize that you only have a cloud and it has no normals...

**Comment by asmaloney** [comment]
Yes - I wasn't talking about activation because then the user has even less information (why is it deactivated for _this_ cloud, but not this other one?)
