### ISSUE TITLE
ccColorFromScalarDlg adjustment arrows not doing anything

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#1107]
**Describe the bug**

The arrows for adjusting _minimum_ and _maximum_ don't seem to do anything.

**How to reproduce**

I'm using the **pumpACartesian.e57** file from the test data. (If you don't have it I can get it to you.)

I bring up the ccColorFromScalarDlg, and when I click the arrows next to _minimum_ for red, it just flips between 0.38 and 0.70.

When I do that, it does not adjust the sliders in the histogram.

The _maximum_ arrows do nothing.

**Expected behaviour**

I should be able to increment the numbers using the arrows and the change should be reflected in the histogram sliders.

If the number can't be adjusted, then the entry widget and arrows should be deactivated.

**Your environment**
 - CC Version (or git hash/tag): 2.11.x
 - OS & Version: macOS
 - Qt Version (if compiling): 5.12.7

**Comment by WargodHernandez** [comment]
Sorry about that incorrect commit comment, c1e7cf4 does not address this issue

**Comment by WargodHernandez** [comment]
@asmaloney 
When you say the arrows are you referring to the dialog box up/down spinners? 
![image](https://user-images.githubusercontent.com/7495752/78953271-2b151200-7a8d-11ea-9c7f-7645cbd913bb.png)
if so I wasn't able to replicate on windows with QT 5.11.2
I verified those are adjusting and in the proper direction for all 4 channels on both toRGB and toHSV mappings

**Comment by asmaloney** [comment]
Yes - it's the double spin boxes.

It might be something specific with that file I test with... I sent it to Sam and it's in the CloudCompare test repo if you have access to that.

It might be a precision/stepping issue?

**Comment by WargodHernandez** [comment]
yep, that explains it, I see the same thing with that file
