### ISSUE TITLE
On Quaternion Math

### ISSUE THREAD

**Issue by vishnukumarts** [CloudCompare/CloudCompare#1142]
Hi,
My question is not about a bug.  What to understand the concept better on Quaternion.

On File RegistrationTools.cpp, RegistrationProcedure().  
I am not sure what the below line is doing?
double s = sqrt((1 + cos_t) * 2);

Information or comments on the above line would be useful.  

Thanks

**Comment by dgirardeau** [comment]
Well, I guess the original intent was simply to create the quaternion corresponding to the rotation of a quantity 't' (see how cos_t is computed) about the axis 'a': see https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation

Basically q = [cos(t/2), sin(t/2) * a)

To compute cos(t/2) we apparently used the half-angle formula... But for sin(t/2) I'm a bit confused here. Either it's serious trigonometric 'golf' or a bug!

**Comment by vishnukumarts** [comment]
yeah, I hope its a bug.  For now I will directly detect the quaternion from the angle.  Thanks a lot @dgirardeau

**Comment by vishnukumarts** [comment]
double cos_t = Np.dot(Nx); //a.b = a*b*cos(theta)
assert(cos_t > -1.0 && cos_t < 1.0); //see above

double actualangle = acos(cos_t);  //Added
//double s = sqrt((1 + cos_t) * 2); //Removed
//double q[4] = { s / 2, a.x / s, a.y / s, a.z / s }; //Removed
double q[4] = { cos(actualangle/2), a.x * sin(actualangle /2) , a.y * sin(actualangle/2), a.z * sin(actualangle/2) };//Added

For information of the fix.  Closing it.

**Comment by dgirardeau** [comment]
Let's keep this open, waiting for the patch to be applied!

**Comment by dgirardeau** [comment]
Ok I patched the code: 508ed91e040e9ac0e0764e6ba8ebbec666848b5c (and the equivalent in the new CCCoreLib repo).
