### ISSUE TITLE
Classification scalar manipulation with aritmetic functions leads to type problems when exporting to laz

### ISSUE THREAD

**Issue by Buzz0m** [CloudCompare/CloudCompare#1144]
**Describe the bug**
Case: I want to manipulate the classification with a function (eg. "x 10" or "x (-1)") to illustrate something (in my case that "these trees are to be cut down"). When doing addition there is no problem, but multiplication at least causes problems when later on exporting to laz. There seems to be some kind of type problem -> PDAL exception: Unable to fetch data and convert as requested: Classification: double(300) -> unsigned char 
When multiplying the classification scalar the SF is no longer "Classification" but is somehow also downgraded to another scalar. Maybe because classification need to be integer and not double which the SF is turned into after the multiplication?

**How to reproduce**
1. Import laz with classifications
2. Edit scalar field -> arithmetic -> multiply scalar field : classifications with constant, eg. -1. Also check to directly update SF1.
3. Save cloud as laz and additional fields
4. Get error dialogue.

**Expected behaviour**
A. Classification SF values are parsed to integers when exporting to laz
B. Classification -field is not downgraded when applying SF manipulations to it 

**Additional context**

**Your environment**
 - 2.11 Aplha (anoia):
 - win10, 10.0.16299, build 16299:
 - Graphics card: NVIDIA Quadro M2200
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
The LAS classification field has some very tight specifications:
![image](https://user-images.githubusercontent.com/2735509/79549207-fa3d6a00-8096-11ea-9c6c-817b5f1936fe.png)

Basically it's between 0 and 18 in the general case (and between 64 and 255 in your case in a way).

So any value above 255 or non integer would indeed be considered as an error.

**Comment by Buzz0m** [comment]
Thanks for the quick "close" and taking the time to explain!
