### ISSUE TITLE
wavefront object export bug

### ISSUE THREAD

**Issue by d99000706** [CloudCompare/CloudCompare#115]
After trimming geometry from an imported .obj in CloudCompare and exporting a .obj and then opening this in another software, we noticed that the exported file had faces whose normal index was greater than the number of normals in the file.

File can be found at:
https://drive.google.com/file/d/0B3AWOegU14LyRFMxV1drZVM0NFk/edit?usp=sharing

**Comment by dgirardeau** [comment]
I never managed to reproduce this issue. If someone encounter this problem again, please et me know and re-open this issue.
