### ISSUE TITLE
{ci} Add qLASFWFIO plugin on Windows

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#1170]
**Describe the feature you would like**

Right now the Windows CI does not build the **qLASFWFIO** plugin.

It requires a library ([LASlib](https://github.com/LAStools/LAStools/tree/master/LASlib)) that is not available through [conda](https://anaconda.org/anaconda/repo) (which is the package manager the CI is using).

Possible solutions:
- figure out how to download it to the right place and add it to the Windows CI
- find someone to add it to conda!

**Comment by tmontaigu** [comment]
Maybe another solution _could be_ to use [LASzip](https://github.com/LASzip/LASzip) which LASlib is built upon, the API is not the same, so a few changes to the plugin would be needed, but we should be able to keep the same features (reading / writing) and laszip is available on conda (maintained by the PDAL team, as LASzip is one of the supported LAZ backend for PDAL)

**Comment by asmaloney** [comment]
Here I was thinking Daniel was the only person who could keep the various LAS libraries straight :-)

I was under the impression that there was something in that particular library that the other libs couldn't do?

**Comment by dgirardeau** [comment]
Can LASzip do the same things as LASlib?!

**Comment by dgirardeau** [comment]
(oops, clicked no the wrong button ;) )

**Comment by tmontaigu** [comment]
I think yes, at least for the things this plugins care about, which is (if I'm not wrong) reading and writing LAS with supports for the waveform thingy

I looked up quickly LASlib and the LASReaderLas it exposes (and this plugin uses) seems to in fact use the struct defined in LASzip

**Comment by dgirardeau** [comment]
Interesting!

**Comment by asmaloney** [comment]
So would that mean we could simplify - back to one LAS plugin without the PDAL dependency? That would help because then we're all building the same plugin for LAS :-)

**Comment by tmontaigu** [comment]
that can be a good idea, and the pdal plugin could be reworked to not be LAS specific but handle all formats that PDAL supports (and not be bundled by default?)

**Comment by tmontaigu** [comment]
As the qLASFWFIO is deprecated, i'm closing (5507e592631039a9b02e80d897dc55e7e268bb50)
