### ISSUE TITLE
On Evaluating Rotation matrix

### ISSUE THREAD

**Issue by vishnukumarts** [CloudCompare/CloudCompare#1177]
It's not about a bug,
On File RegistrationTools.cpp, RegistrationProcedure(),
I am seeing Rotation matrix is identified twice for three-point case,
1. Using quaternion 
2. followed by an arbitrary rotation.

I doubt we need to do both or only quaternion is fine enough.

Note: From the master branch, you guys removed the CC folder itself?

**Comment by asmaloney** [comment]
> From the master branch, you guys removed the CC folder itself?

Yes - that has become its own, separate library called [CCCoreLib](https://github.com/CloudCompare/CCCoreLib).

**Comment by vishnukumarts** [comment]
Ok moving the issue to CCCorelib.  Closing it here.
