### ISSUE TITLE
.las unknown file format on fedora compile

### ISSUE THREAD

**Issue by soble** [CloudCompare/CloudCompare#1238]
on fedora 32
dnf/rpm install qt, make, cmake gdal, pdal

cmake options added were gdal and pdal
gdal works
pdal, ie .las and .laz doesn't
the .las option isn't in the file open types
when I toggle to all and try it says "can't guess file format"

 - CC Version (2.12 alpha
 - OS & Version: Fedora 32
 - Graphics card: 1070
 - Qt Version (if compiling): 5.13.2

I used a set of fedora32 pdal rpms linked from pdal.io

rpm -qa |grep PDAL laszip
PDAL-2.1.0-2.fc32.x86_64
PDAL-vdatums-2.1.0-2.fc32.x86_64
PDAL-libs-2.1.0-2.fc32.x86_64
PDAL-devel-2.1.0-2.fc32.x86_64
laszip-3.4.3-1.fc32.x86_64
laszip-devel-3.4.3-1.fc32.x86_64

#pdal info TGJungDEM.laz --summary
{
  "file_size": 374754,
  "filename": "TGJungDEM.laz",
  "now": "2020-05-22T03:21:54+1000",
  "pdal_version": "2.1.0 (git-version: Release)",
  "reader": "readers.las",
  "summary":
  {
    "bounds":
    {
      "maxx": 506362.5,
      "maxy": 6649981.5,
      "maxz": 202.8000031,

Very likely this is my issue, It's my first try at compiling, 
I gave up on windows

cmake gave an error until I edited PDALConfig.make
line 47 PDALConfig.make
old  foreach(_dir /usr//usr/lib64)
new foreach(_dir /usr/lib64)

**Comment by asmaloney** [comment]
I'm afraid I won't be much help since I don't use PDAL or Linux. The PDALIO plugin is likely not being built or installed properly.

One thing to check would be the CloudCompare console output (at the bottom of the window). When built and installed properly, you should see something like this (but for PDAL):
```
...
[17:29:53] 	Plugin found: E57 (libQE57_IO_PLUGINd.dylib)
...
[17:29:53] [Plugin][E57] New file extensions registered: E57
```

If not, are there any errors in the CloudCompare console?

**Comment by soble** [comment]
Thanks for the pointer
I wasn't loading any plugins
make install put the plugins in lib64 but cc was looking in lib
