### ISSUE TITLE
Cannot compile with -DCCCORELIB_USE_CGAL=ON

### ISSUE THREAD

**Issue by PE1NUT** [CloudCompare/CloudCompare#1258]
CC does not compile with CGAL enabled. I'm trying to run Delaunay2.5 as I have a point cloud that I would like to turn into a mesh. However, compilation fails on a seemingly trivial constexpr for RAD_TO_DEG and DEG_TO_RAD in libs/qCC_db/extern/CCCoreLib/include/CCConst.h

**How to reproduce**
Platofm: Ubuntu 20.20
git clone --recursive https://github.com/cloudcompare/CloudCompare.git
cd CloudCompare; mkdir buid; cd build
cmake -DCCCORELIB_USE_CGAL=ON -DCMAKE_BUILD_TYPE=Release ..
make

Error message:
[  1%] Building CXX object libs/qCC_db/extern/CCCoreLib/CMakeFiles/CCCoreLib.dir/src/AutoSegmentationTools.cpp.o
In file included from /home/paul/CloudCompare/libs/qCC_db/extern/CCCoreLib/include/FastMarching.h:7,
                 from /home/paul/CloudCompare/libs/qCC_db/extern/CCCoreLib/include/FastMarchingForPropagation.h:8,
                 from /home/paul/CloudCompare/libs/qCC_db/extern/CCCoreLib/src/AutoSegmentationTools.cpp:7:
/home/paul/CloudCompare/libs/qCC_db/extern/CCCoreLib/include/CCConst.h:29:38: error: ‘(1.8e+2 / 3.1415926535897931e+0)’ is not a constant expression
   29 |  constexpr double RAD_TO_DEG = (180.0/M_PI);
      |                                ~~~~~~^~~~~~
/home/paul/CloudCompare/libs/qCC_db/extern/CCCoreLib/include/CCConst.h:33:37: error: ‘(3.1415926535897931e+0 / 1.8e+2)’ is not a constant expression
   33 |  constexpr double DEG_TO_RAD = (M_PI/180.0);

**Additional context**
The reason I'm building it myself is because on Ubuntu 20.20 (using the Debian package, not the snap), the Delaunay2.5 doesn't work. but returns '[ccMesh::Triangulate] Failed to construct Delaunay mesh (Triangle lib error: CGAL library not supported)'

**Your environment**
 - CC Version (or git hash/tag): f2cdc5eeab3c2923b690bab8c0d9a093faeead67
 - OS & Version: Ubuntu 20.20 LTS
 - Qt Version (if compiling): 5.12.8 (as shipped with Ubuntu 20.20 LTS)

**Comment by asmaloney** [comment]
Thanks @PE1NUT 

This is a duplicate of #835. It is a [CGAL bug](https://github.com/CGAL/cgal/issues/3180).

Since `DEG_TO_RAD` and `RAD_TO_DEG` are deprecated and I think all uses have been removed, you can try removing the declarations.

**Comment by PE1NUT** [comment]
Thanks for your quick reply.

Commenting out the two 'const expr' allows the compilation to proceed, but it then fails later on with the definition of some static colors in libs/qCC_db/include/ccColorTypes.h

In #935 there is a suggestion to build with clang++ instead, which is what I ended up doing. This resulted in a compile without errors or warnings, and a working Delaunay.

**Comment by kbae01** [comment]
Hi, there I have also the same issue with create mesh out of point clouds in CC 2.11.3 in Ubuntu. To resolve this, do I need to install clang++ as C/C++ compliers and run cmake with the following options. Am I correct, guys?

cmake -DCCCORELIB_USE_CGAL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ ..

I tried with only with  -DCCCORELIB_USE_CGAL=ON with g++ and it was complied alright but I got the same error with creating meshes as shown in the attached. Well, I couldn't find not much explanation on this in the build instruction unfornately. 

![CC_mesh_errors_Linux_1](https://user-images.githubusercontent.com/70741795/153715130-908a4313-1f4f-4f8b-a51b-593630ef0ac1.jpg)
![CC_mesh_errors_Linux_2](https://user-images.githubusercontent.com/70741795/153715131-43607af5-45f3-4365-b202-e28d2638a807.jpg)

**Comment by dgirardeau** [comment]
If enabling the CCCORELIB_USE_CGAL option was effective (on CMake side), then you should have the CC_CORE_LIB_USES_CGAL_LIB preprocessor defined (on the C++ side).

You can try to write anything (if possible, rubish) in any `#if defined(CC_CORE_LIB_USES_CGAL_LIB)` block (in Delaunay2dMesh.cpp for instance) and see if this prevents compilation, and if you get an error message?

**Comment by AsimJalwana** [comment]
> If enabling the CCCORELIB_USE_CGAL option was effective (on CMake side), then you should have the CC_CORE_LIB_USES_CGAL_LIB preprocessor defined (on the C++ side).
> 
> You can try to write anything (if possible, rubish) in any `#if defined(CC_CORE_LIB_USES_CGAL_LIB) ... #endif` block (in Delaunay2dMesh.cpp for instance) and see if this prevents compilation, and if you get an error message?

To help in investigation, Delaunay2dMesh.cpp was updated by including (on L:34)
#if defined(CC_CORE_LIB_USES_CGAL_LIB)
a complete silly statement
why is it happening?
TGIF
#endif

The code compiled well and the binaries were generated as usual. This implies that there is something missing from CMAKE?

Can you share more suggestions to solve the issue?

**Comment by dgirardeau** [comment]
So I looked at the 2.11.3 branch and I see that you need to define COMPILE_CC_CORE_LIB_WITH_CGAL and not CCCORELIB_USE_CGAL!

**Comment by kbae01** [comment]
Thanks, Daniel and Asim. After turn on COMPILE_CC_CORE_LIB_WITH_CGAL in CMAKELists.txt, now I can compile and build successfully with clang++. However, CC becomes frozen while making a mesh from a point cloud, which I could successfully make a mesh in the window version of CC 2.11.3 (stable). I will try with a smaller point cloud or check CGAL version installed in a Linux VM to ratify the issue.

**Comment by dgirardeau** [comment]
Aer you maybe compiling in Debug mode? (which is super slow)

**Comment by dgirardeau** [comment]
Are you maybe compiling in Debug mode? (which is super slow)

**Comment by kbae01** [comment]
After I turned on CGAL option in CMAKEList.txt, I used "cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ ..", which I believe a release mode? Am I right?

**Comment by dgirardeau** [comment]
Ah yes it should be...

**Comment by kbae01** [comment]
I can make a mesh with a smaller point cloud and will try again with a VM with more memory or a better cpu.

**Comment by kbae01** [comment]
It works now after adding more memory and CPU cores to VMs. But we are still testing with using more than one core at a time.
