### ISSUE TITLE
BUG - procedure entry point gdal300.dll

### ISSUE THREAD

**Issue by freesuer** [CloudCompare/CloudCompare#1259]
Hi, 

My cloudcompare was working fine last week but now everytime I start, I have this error. 
<img width="319" alt="Annotation 2020-05-30 215215" src="https://user-images.githubusercontent.com/57350772/83338826-37b52a00-a2c8-11ea-80ca-575836cf039c.png">
I've already uninstalled and reinstalled CC but the problem is persistent.

Any troubleshoot ?

And thank you for such a great tool !!

Best, 

Max

**Comment by freesuer** [comment]
PS: the gdal300.dll file is present in the CC folder

**Comment by dgirardeau** [comment]
I believe this is related to the issue we currently have with the Faro LS SDK. Can you try to uninstall CC, and re-install it without the Faro plugin?

**Comment by freesuer** [comment]
indeed, it works now ! Thanks

**Comment by freesuer** [comment]
Truly appreciate your commitment !

**Comment by dgirardeau** [comment]
I hope we will be able to find a solution to this conflict between GDAL and the Faro LS SDK...
