### ISSUE TITLE
How to add labels on an already labeled dataset

### ISSUE THREAD

**Issue by dev741** [CloudCompare/CloudCompare#1265]
Hi, 
I need to add sub classes on an existing point cloud dataset, Is there  any one can help me with detailed steps?
Thank you all

**Comment by dgirardeau** [comment]
Can you describe your need a little bit more? Are you referring to 'labels' as "2D labels" (that you can get via point picking) or scalar values obtained by classification?

And do you want to do this pro grammatically or manually?

**Comment by dev741** [comment]
Hi, 
 the data set have classes: in my case, i need to add sub classes under the Class building : like doors and i need to add them manually is that possible?
Thank you so much

**Comment by dgirardeau** [comment]
Then you should add a new scalar field. But it's not super easy to do it manually: you can use the 'scissors' tool to segment the cloud (or any other method), then create a new scalar field ('Edit > Scalar fields > Add constant SF') **always with the same name**, and a different value each time (= your sub-class). Then once this is finished, you can merge all the subsets together and CC will also merge the scalar fields based on their names.

**Comment by dev741** [comment]
thank you , it seems that this will take too much time, so how about the grammatically method?

**Comment by dgirardeau** [comment]
Well, if you refer to the programmatic way of doing this, then you'll have to find first how to segment the cloud (and that's not going to be easy ;). And then creating a scalar field and populating it is easy (just look at how ccScalarField objects are created and then the 'reserve' and 'addElement' methods are your friends).
