### ISSUE TITLE
.laz not recognized when files filtered by All (*.*)

### ISSUE THREAD

**Issue by ddoubleprime** [CloudCompare/CloudCompare#1273]
**Describe the bug**

On macOS, 2.11rc1 Anoia, selecting a .laz to open from the recent files menu or the open dialog with (\*.\*) set as type results in :

[Load] Can't guess file format: unhandled file extension 'laz'

Setting the selector in the Open dialog explicitly (to .las/.laz) allows the file to be opened normally.

(have not been able to test whether this affects opening other file types).

**How to reproduce**

1. Go to 'File'->'Open'
2. With file type filter set to 'All (\*.\*)', choose a .laz file, and click open
3. See error
4. Repeat 1, set selector to LAS cloud (.las .laz) -> file opens fine.

**Expected behaviour**

Expected would be for it to recognize the file extension and process the correct file type automatically.

**Your environment**
 - CC Version (or git hash/tag): 2.11rc1 Anoia, package from Andy Maloney
 - OS & Version: macOS, 10.15.5 Catalina
 - Graphics card: AMD Radeon R9 M395X 4 GB
 - Qt Version (if compiling): n/a

**Comment by asmaloney** [comment]
Thank you for the report @ddoubleprime.

This is an issue with the LASIO plugin (fixed in current version, needs to be backported), so I'm going to close this issue and open one over there as a reminder:

https://github.com/asmaloney/LASIO/issues/1
