### ISSUE TITLE
E57Format: incorrect linking

### ISSUE THREAD

**Issue by fbosche** [CloudCompare/CloudCompare#1278]
![Capture](https://user-images.githubusercontent.com/17482201/84597149-b7f79580-ae59-11ea-8a0b-e091e2ff8dbd.JPG)
When I compile with the E57 plugin on Windows, I get an error when loading the E57 plugin in the Release mode. Going through the dependencies (see attachmnt), I noticed that the E57Format.dll is expecting the Debug version of the Xerces shared library. When I use that one instead of the Release version, the plugin loads. (note that the issue didn't occur with the Debug compilation, as E57Format.dll correctly links to the Debug library in that case).
Maybe that issue doesn't occur when Xerces is linked statically (I haven't checked). I'm not sure where the error occurs (maybe some CMakeLists somewhere. Also, I'm not sure if the issue relates to CC or it should in fact be reported on the E57 library GitHub page instead.

My environment:
 - CC 2.12
- Win10 x64 / MS 15 2017
 - Qt V5.12.2

**Comment by WargodHernandez** [comment]
when you are compiling are you prompted to use the CMake variable XercesC_LIBRARY_RELEASE? or just XercesC_LIBRARY & XercesC_INCLUDE_DIR ?

**Comment by fbosche** [comment]
When Configuring in CMake, I'm asked to provide the paths to both the DEBUG and the RELEASE libraries (along with the INCLUDE_DIR).

**Comment by fbosche** [comment]
OK. I've redone some compilations from scratch (with erasing absolutely everything everywhere), and it now seems to work. So, maybe there was some residual stuff from when I had incorrectly given the path to the Debug library to the RELEASE request a while back. Hmmm. I thought I had done some full cleanups since, but maybe not.

**Comment by WargodHernandez** [comment]
Ok, I'll close this for now, feel free to reopen if you don't feel this is resolved
