### ISSUE TITLE
QE57_IO_PLUGIN.dll does not seem to be a valid plugin

### ISSUE THREAD

**Issue by fbosche** [CloudCompare/CloudCompare#1279]
I have compiled CC 2.12 with the E57 plugin along with some private plugins. The Core IO, the E57 plugin and the private plugins all load when running the executable in the Install folder of the build machine. But, when I deploy on another machine, the E57 plugin fails to load (while the others ones load fine). I get the log error message:

`QE57_IO_PLUGIN.dll does not seem to be a valid plugin    (Cannot load library C:\.....\QE57_IO_PLUGIN.dll: The specified module could not be found.)`

I have noted in a different bug report a bug related to the linking with Xerces, but I don't think this is the problem.

I believe the problem is related to missing libraries. But, I have added E57Format.dll and the Xerces dll in the executable folder. What am I missing?

My environment:
 - CC 2.12
- Win10 x64 / MS 15 2017
 - Qt V5.12.2

**Comment by WargodHernandez** [comment]
can you do a dependency walker on the machine that isn't working on the QE57_IO_PLUGIN.dll from the plugin folder and also on the Xerces dll in the CloudCompare folder and send back screenshots like these
  
![image](https://user-images.githubusercontent.com/7495752/84834390-15b8e880-afe6-11ea-9028-3c44b6a50cba.png)

![image](https://user-images.githubusercontent.com/7495752/84834362-0a65bd00-afe6-11ea-9ee1-ff8e00350d86.png)

**Comment by fbosche** [comment]
First, I should point that I had the problem when linking the E57Format library dynamically. But, when I linked it statically, then the plugin loaded fine. 
I'll have to recompile the lot with dynamic linking of E57Format before I can give you the dependcy walker output. Who knows. Maybe it'll work this time......

**Comment by fbosche** [comment]
OK. I've now done the recompilation and it now works fine. I suspect this may have been linked to the same problem as my other submitted issue, i.e. somehow I may not have done a proper cleanup of my folders when I did it, and there may have been some inappropriate residual files there. I'm really confused about this, but it seems to work now.
Thank you,

**Comment by WargodHernandez** [comment]
Ok, I'll close this for now, feel free to reopen if you don't feel this is resolved
