### ISSUE TITLE
Icon for CSF Plugin is not licensed for use

### ISSUE THREAD

**Issue by irowebbn** [CloudCompare/CloudCompare#1285]
Here's a weird one for you:

The icon used in the CloudCompare menu to denote the cloth simulation filter (CSF) plugin is actually the logo of a [religious organization for university students](https://en.wikipedia.org/wiki/Christian_Student_Fellowship) (Christian Student Fellowship). The image, as far as I can tell, is the original creation of this organization and the use of this image by this organization predates the use in this application (it was introduced in Mar 2019, by  @asmaloney in 069c945).

Since this project does not have a license to use the image, it should be replaced with something more generic.

Full disclosure: I have attended events organized by and have relationships with many people currently or previously employed by CSF. I am filing this issue because I am probably the only person in the world who knows about this group and also has used this software, and I believe this use of copyrighted imagery to be a simple oversight that should be fixed. I do not speak on behalf of the organization.

**Comment by WargodHernandez** [comment]
Not that it changes much but the plugin is actually from 2016 introduced in  [#76ed607 New plugin: qCSF](https://github.com/CloudCompare/CloudCompare/commit/76ed607c2898799c940105fc237aac424f31ea44#diff-07c07f842348829196ccbe5a3511fd89)

> Provided by the Qi Jianbo and Wan Peng (School of Geography, Beijing Normal University, China)

Not sure if it can be removed from historical releases? I'm sure one of us can throw together a qCSF logo instead of a CSF logo.

**Comment by asmaloney** [comment]
@WargodHernandez is correct - that's what we were given with the plugin. I didn't add it.

The interface will use a default icon if it's not included, so that's easy to do for any future releases. For past releases... I know I can't re-create them all.

**Comment by WargodHernandez** [comment]
Are there any existing tools for Github to remove a single file from all history?

**Comment by asmaloney** [comment]
Never had to do it, but:

https://stackoverflow.com/questions/43762338/how-to-remove-file-from-git-history

**Comment by WargodHernandez** [comment]
https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history

It appears there is

**Comment by asmaloney** [comment]
Not sure what the commits looks like after that, but just removing the file will mean anyone trying to build an older version will fail. So if there's a way to add a note/warning to point at the change I just submitted, that would be helpful.

**Comment by WargodHernandez** [comment]
if we use the [bfg-repo-cleaner](https://rtyley.github.io/bfg-repo-cleaner/) and replace the icon with an equivalent sized PNG that isn't infringing then everything should just continue to work

**Comment by asmaloney** [comment]
For reference, it's used in the plugin manager UI, the CSF's window icon, and the included docs in the CSF dialog.

My suggestion would be to remove it for the future with my commit, and replace it in the history with a blank icon.

**Comment by asmaloney** [comment]
I have removed the CSF plugin from all the historical macOS downloads.
