### ISSUE TITLE
CC 2.11 crash out when loading LAS file which was read with a previous release of CC

### ISSUE THREAD

**Issue by Roumagnifique** [CloudCompare/CloudCompare#1289]
I was using a previous version of CC, I updated it and:
When I am loading LAS file in the CC gui, thGUI directy end up with a windows message saying that CC "a cessé de fonctionner".
I was able to read these files with a previous version of CC (I don't have anymore the version number!).

The las files are comming from a tile export of Metashape (previously photoscan).

When I try to make a subsampling by command line (already done with success with a previous version of CC), I have an error message related to the projection system, the messages are copy/paste below:

[1] "\"C:\\Program Files\\CloudCompare\\CloudCompare.exe\" -SILENT -AUTO_SAVE OFF -O E:\\Seb\\iDROP\\test\\Congo1_v1_UTM33N-0-5.las -SS SPATIAL 0.1 -NO_TIMESTAMP -C_EXPORT_FMT LAZ -SAVE_CLOUDS "
[Global Shift] Max abs. coord = 1e+4 / max abs. diag = 1e+6
[ccColorScalesManager] Found 0 custom scale(s) in persistent settings
[Plugin] Searching: C:/Program Files/CLOUDC~1/plugins
	Plugin found: Additional I/O (QADDITIONAL_IO_PLUGIN.dll)
	Plugin found: Animation (QANIMATION_PLUGIN.dll)
	Plugin found: CEA Virtual Broom (QBROOM_PLUGIN.dll)
	Plugin found: CANUPO (QCANUPO_PLUGIN.dll)
	Plugin found: Compass (QCOMPASS_PLUGIN.dll)
	Plugin found: Core I/O (QCORE_IO_PLUGIN.dll)
	Plugin found: Cork (QCORK_PLUGIN.dll)
	Plugin found: CSF Filter (QCSF_PLUGIN.dll)
	Plugin found: CSV Matrix I/O (QCSV_MATRIX_IO_PLUGIN.dll)
	Plugin found: DP (QDOT_PRODUCT_IO_PLUGIN.dll)
	Plugin found: E57 (QE57_IO_PLUGIN.dll)
	Plugin found: EDL Shader (QEDL_GL_PLUGIN.dll)
	Plugin found: ELlipser (QELLIPSER_PLUGIN.dll)
	Plugin found: Facet/fracture detection (QFACETS_PLUGIN.dll)
	Plugin found: FBX (QFBX_IO_PLUGIN.dll)
	Plugin found: Hough Normals Computation (QHOUGH_NORMALS_PLUGIN.dll)
	Plugin found: Hidden Point Removal (QHPR_PLUGIN.dll)
	Plugin found: LAS FWF file I/O (QLAS_FWF_IO_PLUGIN.dll)
	Plugin found: M3C2 Distance (QM3C2_PLUGIN.dll)
	Plugin found: PCD file I/O (QPCL_IO_PLUGIN.dll)
	Plugin found: PCL wrapper (QPCL_PLUGIN.dll)
	Plugin found: PCV / ShadeVis (QPCV_PLUGIN.dll)
	Plugin found: PDAL (QPDAL_IO_PLUGIN.dll)
	Plugin found: Photoscan I/O (QPHOTOSCAN_IO_PLUGIN.dll)
	Plugin found: PoissonRecon (QPOISSON_RECON_PLUGIN.dll)
	Plugin found: RANSAC Shape Detection (QRANSAC_SD_PLUGIN.dll)
	Plugin found: RDB2 (I/O Plugin) (QRDB_IO_PLUGIN.dll)
	Plugin found: Riegl RDB I/O (QRIEGL_IO_PLUGIN.dll)
	Plugin found: Surface of Revolution Analysis (QSRA_PLUGIN.dll)
	Plugin found: SSAO Shader (QSSAO_GL_PLUGIN.dll)
[Plugin] Searching: C:/Users/gef/AppData/Roaming/CCCorp/CLOUDC~1/plugins
[Plugin] Searching: C:/ProgramData/CCCorp/CLOUDC~1/plugins
[Plugin] Searching: C:/Program Files/CLOUDC~1/data/plugins
[Plugin][Additional I/O] New file extensions registered: ICM OUT PN POLY POV PV SOI SX
[Plugin][Core I/O] New file extensions registered:  GEOREF MA OBJ OFF PDMS PTX SBF STL VTK
[Plugin][CSV Matrix I/O] New file extensions registered: CSV
[Plugin][DP] New file extensions registered: DP
[Plugin][E57] New file extensions registered: E57
[Plugin][FBX] New file extensions registered: FBX
[Plugin][LAS FWF file I/O] New file extensions registered: LAS
[Plugin][PCD file I/O] New file extensions registered: PCD
[Plugin][PDAL] New file extensions registered: LAS
[Plugin][Photoscan I/O] New file extensions registered: PSZ
[Plugin][RDB2 (I/O Plugin)] New file extensions registered: RDB2
[Plugin][Riegl RDB I/O] New file extensions registered: RDS
Auto-save is disabled
[LOADING]
Opening file: 'E:\Seb\iDROP\test\Congo1_v1_UTM33N-0-5.las'
(readers.las Error) GDAL failure (1) PROJ: proj_as_wkt: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date
(readers.las Error) GDAL failure (1) PROJ: proj_as_wkt: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date
(readers.las Error) GDAL failure (1) PROJ: proj_create_from_database: cannot build geodeticCRS 4326: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date
(readers.las Error) GDAL failure (1) PROJ: proj_as_wkt: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date
(readers.las Error) GDAL failure (1) PROJ: proj_as_wkt: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date

**Your environment**
 - CC Version (or git hash/tag): 2.11
 - OS & Version: Windows 7
 - Graphics card: NVIDIA GeForce GT 730

**Comment by dgirardeau** [comment]
For some time now we have switched from LibLAS to PDAL to load LAS files by default.

Can you test with the other LAS filter (use the File Open dialog and look for the 'LAS 1.3 or 1.4' filter). Then can you report if it works or not?

And can you maybe share the file that makes CC crash with us? (admin [at] cloudcompare.org)
