### ISSUE TITLE
cloudcompare can not open an .obj file which can be  opened by Meshlab

### ISSUE THREAD

**Issue by wangfudong** [CloudCompare/CloudCompare#1291]
**Describe the bug**
I get an obj file that can not be opened by cloudcompare. However, it can be opened by Meshlab.

It looks just like a usual  obj file with 3 fields v, vt, f:
v 0.179777 -0.297089 -0.028758
v 0.187788 -0.297154 0.003566
v 0.194296 -0.318587 0.001624
...
vt 0.646294 0.644335
vt 0.645856 0.638017
vt 0.652067 0.642382
...
f 1183/1/1183 3/2/3  1182/3/1182
f 1182/3/1182 1/4/1  1181/5/1181
f 1181/5/1181 2/6/2  1183/1/1183
f 1183/1/1183 1182/3/1182  1181/5/1181
...
However, this file lacks of the field vn.

When I use cloudcompare to open it, the coudcompare will be killed. I guess this is due to the fact that cloudcompare does not well-check whether the field vn is matched with the field f.

The original obj file is attached in the following objfile.zip (102kb).
[objfile.zip](https://github.com/CloudCompare/CloudCompare/files/4855411/objfile.zip)

**Environment**
 - Cloudcompare Version: 2.10.2
 - Win10 64-bit:

**Comment by dgirardeau** [comment]
Have you tried with the 2.11 version? With this version I could successfully load the file.

However there are a few interesting warnings:
_[20:38:11] [OBJ] Malformed file: indexes go higher than the number of elements! (v=2709/tc=-1/n=2709)_

**Comment by dgirardeau** [comment]
And this is because the file has normal indexes (the index in the middle of each 'f' sub groups such as 'f 789/**152**/789 61/**153**/61  786/**154**/786'') while there are no normals defined in the file (with the 'vn' key at the beginning)?

**Comment by wangfudong** [comment]
Thank you! The latest version 2.11 can open the obj file successfully. I think in this version the developers have debuged the io process such that the fields like "v, vt, vn, f, mtl" of obj file are checked more carefully.
