### ISSUE TITLE
can't build 2.11.0/2.11.1/2.11.2/2.11.3 on debian sid

### ISSUE THREAD

**Issue by alexmyczko** [CloudCompare/CloudCompare#1299]
Here's a build log:

http://phd-sid.ethz.ch/debian/cloudcompare/2020/cloudcompare_2.11.0-1_amd64.build

and with 2.11.1

http://phd-sid.ethz.ch/debian/cloudcompare/2020/cloudcompare_2.11.1-1_amd64.build

and with 2.11.2

http://phd-sid.ethz.ch/debian/cloudcompare/2020/cloudcompare_2.11.2-1_amd64.build

would be great to get this solved for https://release.debian.org/bullseye/freeze_policy.html

according to
https://repology.org/project/cloudcompare/versions all others are also still stuck with 2.10.x except:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/cloudcompare/default.nix#L76

**Comment by tmontaigu** [comment]
How could we try to reproduce this ? 
I downloaded & installed debian sid (bullseye?) in a VirtualBox and CloudCompare compiled fine.

**Comment by alexmyczko** [comment]
I will check... could you post your buildlog?

**Comment by tmontaigu** [comment]
I don't know if this is gonna help: [buildlog.txt](https://github.com/CloudCompare/CloudCompare/files/5573538/buildlog.txt)

btw most of the options you are passing to cmake to build optional features of CC are obsolete

**Comment by alexmyczko** [comment]
i'm not sure if you're on testing or sid, but it always ends at the same place:

```
                 from /var/www/debian/cloudcompare/2121/CloudCompare-2.11.3/libs/qCC_db/ccBBox.h:22,
                 from /var/www/debian/cloudcompare/2121/CloudCompare-2.11.3/libs/qCC_db/ccHObject.h:23,
                 from /var/www/debian/cloudcompare/2121/CloudCompare-2.11.3/libs/qCC_db/ccArray.h:22,
                 from /var/www/debian/cloudcompare/2121/CloudCompare-2.11.3/libs/qCC_db/ccAdvancedTypes.h:22,
                 from /var/www/debian/cloudcompare/2121/CloudCompare-2.11.3/libs/qCC_db/ccGenericMesh.h:25,
                 from /var/www/debian/cloudcompare/2121/CloudCompare-2.11.3/libs/qCC_db/ccMesh.h:26,
                 from /var/www/debian/cloudcompare/2121/CloudCompare-2.11.3/qCC/ccEntityAction.h:20,
                 from /var/www/debian/cloudcompare/2121/CloudCompare-2.11.3/qCC/mainwindow.h:25,
                 from /var/www/debian/cloudcompare/2121/CloudCompare-2.11.3/qCC/mainwindow.cpp:18:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h:293:75: note: declared here
  293 | Q_CORE_EXPORT QT_DEPRECATED_VERSION_X(5, 15, "Use Qt::endl") QTextStream &endl(QTextStream &s);
      |                                                                           ^~~~
make[3]: Leaving directory '/var/www/debian/cloudcompare/2121/CloudCompare-2.11.3/obj-x86_64-linux-gnu'
make[2]: *** [CMakeFiles/Makefile2:1565: qCC/CMakeFiles/CloudCompare.dir/all] Error 2
make[2]: Leaving directory '/var/www/debian/cloudcompare/2121/CloudCompare-2.11.3/obj-x86_64-linux-gnu'
make[1]: *** [Makefile:152: all] Error 2
make[1]: Leaving directory '/var/www/debian/cloudcompare/2121/CloudCompare-2.11.3/obj-x86_64-linux-gnu'
dh_auto_build: error: cd obj-x86_64-linux-gnu && make -j16 "INSTALL=install --strip-program=true" returned exit code 2
make: *** [debian/rules:8: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
```

**Comment by tmontaigu** [comment]
tried again after properly changing the apt sources.list to sid as they were still pointing to testing, however It still compiles.

I took a look around and saw a patch here 'http://phd-sid.ethz.ch/debian/cloudcompare/2020/cloudcompare-2.11.3/debian/patches/changes', is that patch applied ?

If yes, I think it is the cause of the problem

**Comment by alexmyczko** [comment]
even worse, a patch applied via cp in debian/rules :( hahah but your hint did help, thank you
