### ISSUE TITLE
CLI bug - silent mode with shapefiles 

### ISSUE THREAD

**Issue by GreKro** [CloudCompare/CloudCompare#1303]
Hi @dgirardeau 

I would like to report a bug in Command Line Interface related to syntax with shapefile layers and silent mode.
When I used the following syntax:

CloudCompare -SILENT -NO_TIMESTAMP -C_EXPORT_FMT SHP -EXT shp -O shape1.shp -O shape2.shp -MATCH_CENTERS 

CC asks me about "altitude field" and I have to manually select the ignore option.

I think in silent mode it should ignore 'altitude field' as a default.

 I'm using  CC v. 2.11.1 on Windows 8.

Best regards,
GK

**Comment by dgirardeau** [comment]
I agree, it's not what's supposed to happen in 'SILENT' mode.

I fixed this (d033a7a3a0f71bb8134df83f6b5167fd4faa7d00). It will be available in the next release (should normally be 2.11.2, and it should be released soon).
