### ISSUE TITLE
[LAS 1.3 or 1.4 filter] Extended classification IDs are not handled correctly

### ISSUE THREAD

**Issue by tpwrules** [CloudCompare/CloudCompare#1304]
**Describe the bug**
LAS versions before 1.4 and point data formats below 6 restrict classification IDs from 0 to 31. Version 1.4 files and point data formats 6 and above allow "extended" classification IDs from 0 to 255.

When saving a cloud with a scalar field named Classification, the "LAS 1.3 or 1.4" filter writes numbers greater than 31 as 31 even when saving to a compatible version of LAS. When loading a LAS file containing extended classification IDs, numbers greater than 31 are read as 0.

I've attached [some_points.bin.zip](https://github.com/CloudCompare/CloudCompare/files/5017319/some_points.bin.zip) with a cloud that contains 256 points. Each has an RGB color, a Classification from 0 to 255 (each point has a unique number) and a similarly set Intensity. 

**How to reproduce**
1. Unzip and load the provided some_points.bin.zip file
2. Save the cloud using the LAS 1.3 or 1.4 filter with "Optimal resolution" (for consistency).
3. Load the LAS file using the same filter. Click 'No' when asked to apply global shift and scale (for consistency).
4. Observe that the loaded Classification is set to 31 for all points with Classification originally above 31. (you may have to turn off the original cloud to see)
5. Load the LAS file again with the "LAS cloud" filter. Just click 'Apply' in the "Open LAS File" dialog, don't change any settings. Click 'No' when asked to apply global shift and scale (for consistency). 
6. Observe the same problem as step 4, thus showing that the problem is during saving.
7. Observe that the "LAS.version.major", "LAS.version.minor", and "LAS.point_format" fields in the Meta data under the cloud Properties are 1, 4, and 7 respectively, thus showing that the data was saved in a format that supports extended classification IDs.

**Expected behaviour**
I expect that the loaded values match the saved values.

**Your environment**
 - CC Version (or git hash/tag): 2.11.1
 - OS & Version: Windows 10 Pro 1809
 - Graphics card: NVIDIA Quadro P2000
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
Ok, this should now be fixed (the PR is on its way: https://github.com/CloudCompare/CloudCompare/pull/1318)

**Comment by dgirardeau** [comment]
The 2.12.2 version is now online (with the above fix)
