### ISSUE TITLE
[LAS cloud filter] Point data format selection doesn't check for extended classification IDs

### ISSUE THREAD

**Issue by tpwrules** [CloudCompare/CloudCompare#1305]
**Describe the bug**
LAS versions before 1.4 and point data formats below 6 restrict classification IDs from 0 to 31. Version 1.4 files and point data formats 6 and above allow "extended" classification IDs from 0 to 255.

When saving a cloud with a scalar field named Classification, the "LAS cloud" filter writes numbers greater than 31 to the classification flags fields and does not use a format that supports extended classification IDs. If the cloud has metadata that indicates the file was loaded from a format supporting extended IDs, then the cloud is correctly saved to that format and the IDs are preserved.

I've attached [more_points.bin.zip](https://github.com/CloudCompare/CloudCompare/files/5017519/more_points.bin.zip) with a cloud 'regular_points' that contains 256 points. Each has an RGB color, a Classification from 0 to 255 (each point has a unique number) and a similarly set intensity. It additionally contains 'las_meta_points' which has identical data to 'regular_points', but also has metadata indicating that it was loaded from a LAS 1.4 + point data format 7 file.

**How to reproduce**
1. Unzip and load the provided more_points.bin.zip file
2. Save 'regular_points' using the LAS cloud filter with "Optimal resolution" (for consistency).
3. Load the 'regular_points.las' file using the same filter. Check 'Classification', 'decompose', and 'Value' in the 'Open LAS file' dialog. Uncheck 'Synthetic flag', 'Key-point', and 'Withheld' then click 'Apply'. Click 'No' when asked to apply global shift and scale (for consistency).
4. Observe that the loaded '[Classif] Value' scalar field is the original Classification values modulo 32. (you may have to turn off the original cloud to see)
5. Observe that the "LAS.version.major", "LAS.version.minor", and "LAS.point_format" fields in the Meta data under the cloud Properties are 1, 2, and 2 respectively, thus showing that the cloud was NOT saved in a format that supports extended classification IDs.
6. Repeat steps 2 and 3 with 'las_meta_points'.
7. Observe that the loaded '[Classif] Value' scalar field matches the original Classification values. (you may have to turn off the original cloud to see)
8. Observe that the "LAS.version.major", "LAS.version.minor", and "LAS.point_format" fields in the Meta data under the cloud Properties are 1, 4, and 7 respectively, thus showing that the cloud was saved in a format that DOES support extended classification IDs (the format the metadata indicates the cloud was ostensibly loaded from).

**Expected behaviour**
I would expect that the appropriate format is selected for clouds with classification IDs greater than 31 so that the loaded values match the saved values. If it is desirable to preserve the loaded = saved behavior with un-decomposed LAS files, I would expect a way to indicate that I wish to save in a format that supports extended classification IDs or a way to directly specify the format.

The only ways I know of to attach the necessary metadata to select the right format are to merge the cloud with one that already has the metadata or to hex edit the .bin file to write out the correct metadata. Neither is a good approach in my opinion.

**Your environment**
 - CC Version (or git hash/tag): 2.11.1
 - OS & Version: Windows 10 Pro 1809
 - Graphics card: NVIDIA Quadro P2000
 - Qt Version (if compiling):

**Comment by tmontaigu** [comment]
Closing as the new plugin merged in #1688 detects when classification is > 31 and also allows to manually  select the version & point format
