### ISSUE TITLE
Plugin make Program no responding

### ISSUE THREAD

**Issue by ArtEdur** [CloudCompare/CloudCompare#1306]
Hello

I am trying to develop a plugin for extracting indoor plane based on point cloud.Now i have complete the plugin,however when i use the plugin in the program,the program will always become no responding.

If possible,please tell me the reason

Thank 
Authur

Here is my code
[qIndoorExtraction.zip](https://github.com/CloudCompare/CloudCompare/files/5027364/qIndoorExtraction.zip)

**Comment by WargodHernandez** [comment]
You will need to post relevant code here and more information, not as a zip file. What version of cloud compare are you starting from? 

Can you get the example plugin or any of the included plugins to run? If so can you distill your plugin down to the smallest reproducible problem so we can point you in the right direction. 

I'm sure there are people here who are willing to help if you follow the GitHub issues template and guidance.

**Comment by ArtEdur** [comment]
I am sorry for that!This is my firts time i reported a issue here.Now i will report my issues flow the GitHub template.

**Describe the bug**
I develop a plugin for extracting indoor plane based on point cloud using PCL，when i run this plugin in the cloudcompare.exe(release),the program no responding,and the plugin even cant deal with the point cloud with about 2 milion points.However the algorithm i use can easily deal with the same point cloud in the console application.

**How to reproduce**
I develop the plugin based on the Example Plugin.
1.modify the code as the ExamplePlugin suggest
2.add my own algorithm in the doAction() 
{my algorithm based on the pcl so i transform the ccPointCloud to the pclPointCloud as the following code}
`
	const ccHObject::Container& selectedEntities = m_app->getSelectedEntities();
	
	size_t selNum = selectedEntities.size();
	if (selNum != 1)
	{
		m_app->dispToConsole("Select only one cloud", ccMainAppInterface::ERR_CONSOLE_MESSAGE);
		return;
	}
	ccHObject* ent = selectedEntities[0];
	ccPointCloud* pc = static_cast<ccPointCloud*>(ent);
	boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB>> cloud(new pcl::PointCloud<pcl::PointXYZRGB>);//点云
	int i, count = pc->size();
	cloud->width = count;
	cloud->height = 1;
	cloud->points.resize(cloud->width*cloud->height);
	if (!cloud)
	{
		m_app->dispToConsole("Not enough memory!", ccMainAppInterface::ERR_CONSOLE_MESSAGE);
		return;
	}
	for (i = 0; i < count; ++i)
	{
		pcl::PointXYZRGB point;
		const CCVector3* p;
		p = pc->getPoint(i);
		point.x = (float)p->x;
		point.y = (float)p->y;
		point.z = (float)p->z;
		cloud->push_back(point);
	}`
3.then run the project to generatr the cloudcompare and the plugin
4.install the plugin into the folder "plugins"
5. run the cloudcompare.exe
6.import my point cloud data {about 2 milion points  file format:ply}
7.selected the point clouds and run the plugin
8.the program no responding and cant compute a result

**Expected behaviour**
the plugin can use successfully with a massive point cloud,and dont make the program no responding

**Additional context**
i didnt use the camke to link the pcl libraries.


**My environment**
cloudcompare 2.11
win7
GTX1080
Qt 5.14.2
pcl 1.9.2




here is my algorithm code:
`pcl::ExtractIndices<pcl::PointXYZRGB> extract;
	pcl::ExtractIndices<pcl::Normal> extract_normals;
	boost::shared_ptr<pcl::ModelCoefficients> coefficients_plane(new pcl::ModelCoefficients);
	pcl::PointIndices::Ptr inliers(new pcl::PointIndices);
	pcl::search::Search<pcl::PointXYZRGB>::Ptr tree;
	boost::shared_ptr<pcl::NormalEstimation<pcl::PointXYZRGB, pcl::Normal>> normal_estimator(new pcl::NormalEstimation<pcl::PointXYZRGB, pcl::Normal>);


	boost::shared_ptr<pcl::PointCloud<pcl::Normal>> cloud_normals(new pcl::PointCloud<pcl::Normal>);
	std::vector<std::vector<float>> planeparas;
	pcl::console::TicToc tt;
	boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB>> cloud_plane(new pcl::PointCloud<pcl::PointXYZRGB>);

	pcl::PLYWriter writer;

	pcl::PointXYZRGB minpt1, maxpt1;
	pcl::getMinMax3D(*cloud, minpt1, maxpt1);


	boost::shared_ptr<pcl::PointCloud<pcl::Normal>> normals(new pcl::PointCloud<pcl::Normal>);
	normal_estimator->setSearchMethod(tree);
	normal_estimator->setInputCloud(cloud);
	normal_estimator->setKSearch(50);
	normal_estimator->compute(*normals);
	m_app->dispToConsole("normal compution over");

	pcl::RegionGrowing<pcl::PointXYZRGB, pcl::Normal> reg;
	reg.setInputCloud(cloud);
	reg.setMinClusterSize(1000);
	reg.setMaxClusterSize(1000000);
	reg.setSearchMethod(tree);
	reg.setNumberOfNeighbours(5);
	reg.setInputNormals(normals);
	reg.setSmoothnessThreshold(3.0 / 180.0*M_PI);
	reg.setCurvatureThreshold(1.0);
	std::vector<pcl::PointIndices> clusters;
	reg.extract(clusters);
	m_app->dispToConsole("v over");

	std::stringstream SaveFilePath1, SavePcdFilePath1;
	

	std::stringstream SaveFilePath2, SavePcdFilePath2;



	int j = 0;
	for (std::vector<pcl::PointIndices>::const_iterator it = clusters.begin(); it != clusters.end(); ++it)
	{
		boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB>> cloud_cluster(new pcl::PointCloud<pcl::PointXYZRGB>);
		for (std::vector<int>::const_iterator pit = it->indices.begin(); pit != it->indices.end(); ++pit)
		{
			cloud_cluster->points.push_back(cloud->points[*pit]);
		}
		cloud_cluster->width = cloud_cluster->points.size();
		cloud_cluster->height = 1;
		cloud_cluster->is_dense = true;

		normal_estimator->setSearchMethod(tree);
		normal_estimator->setInputCloud(cloud_cluster);
		normal_estimator->setKSearch(100);
		normal_estimator->compute(*cloud_normals);


		pcl::SACSegmentationFromNormals<pcl::PointXYZRGB, pcl::Normal> seg;
		seg.setOptimizeCoefficients(true);
		seg.setModelType(pcl::SACMODEL_NORMAL_PLANE);
		seg.setNormalDistanceWeight(0.1);
		seg.setMethodType(pcl::SAC_RANSAC);
		seg.setMaxIterations(100);
		seg.setDistanceThreshold(0.05);



		int i = 0, nr_points = (int)cloud_cluster->points.size();
		while (cloud_cluster->points.size() > 0.01*nr_points)
		{
		
			seg.setInputCloud(cloud_cluster);
			seg.setInputNormals(cloud_normals);
			seg.segment(*inliers, *coefficients_plane);
		
			extract.setInputCloud(cloud_cluster);
			extract.setIndices(inliers);
			extract.setNegative(false);
			extract.filter(*cloud_plane);
			std::stringstream SaveFilePath, SavePcdFilePath;
			pcl::getMinMax3D(*cloud_plane, minpt1, maxpt1);

			if (cloud_plane->points.size() < 500)
				break;
			pcl::PointXYZRGB maxpt, minpt;
			pcl::getMinMax3D(*cloud_plane, minpt, maxpt);

			double x = coefficients_plane->values[0];
			double y = coefficients_plane->values[1];
			double z = coefficients_plane->values[2];


			if (maxpt.z - minpt.z<0.42 && maxpt.z - minpt.z>0.38)
			{
				break;
			}

			else if (maxpt.z - minpt.z<2.2 && maxpt.z - minpt.z>1.9)
			{
				if (maxpt.y - minpt.y < 0.7)
				{

					for (int m = 0; m < cloud_plane->size(); m++)
					{
						cloud_plane->points[m].r = 255;
						cloud_plane->points[m].g = 0;
						cloud_plane->points[m].b = 0;
					}
					SavePcdFilePath << "D:\\CCProject\\output" << j << "cloud" << i << ".ply";
					//writer.write(SavePcdFilePath.str(), *cloud_plane, false);
					writer.write(SavePcdFilePath.str(), *cloud_plane, false);
				}
			}
			else if (x > 0.95 && y > 0.25)
			{
				if (maxpt.z - minpt.z < 0.4 || maxpt.z < 0.8)
					break;
			
				for (int m = 0; m < cloud_plane->size(); m++)
				{
					cloud_plane->points[m].r = 0;
					cloud_plane->points[m].g = 255;
					cloud_plane->points[m].b = 0;
				}

			
				SavePcdFilePath << "D:\\CCProject\\output" << j << "cloud" << i << ".ply";
		
				writer.write(SavePcdFilePath.str(), *cloud_plane, false);
			
			}
			else if (x > 0.25 && y < -0.95)
			{
				if (maxpt.z - minpt.z < 0.42 || maxpt.z < 0.8)
					break;
	
				for (int m = 0; m < cloud_plane->size(); m++)
				{
					cloud_plane->points[m].r = 0;
					cloud_plane->points[m].g = 255;
					cloud_plane->points[m].b = 255;
				}
		
				SavePcdFilePath << "D:\\CCProject\\output" << j << "cloud" << i << ".ply";
				//writer.write(SavePcdFilePath.str(), *cloud_plane, false);
				writer.write(SavePcdFilePath.str(), *cloud_plane, false);
				
				/*writer.write(SavePcdFilePath.str(), *cloud_sor, false);*/
			
			}
			else if (z > 0.95 || z < -0.95)
			{
				/*for (int m = 0; m < cloud_sor->size(); m++)
				{
					cloud_sor->points[m].r = 255;
					cloud_sor->points[m].g = 255;
					cloud_sor->points[m].b = 255;
				}*/
				for (int m = 0; m < cloud_plane->size(); m++)
				{
					cloud_plane->points[m].r = 255;
					cloud_plane->points[m].g = 255;
					cloud_plane->points[m].b = 0;
				}
				
				SavePcdFilePath << "D:\\CCProject\\output" << j << "cloud" << i << ".ply";
				writer.write(SavePcdFilePath.str(), *cloud_plane, false);
		
			}


			std::vector<float> tempplaneparas;
			tempplaneparas.push_back(coefficients_plane->values[0]);
			tempplaneparas.push_back(coefficients_plane->values[1]);
			tempplaneparas.push_back(coefficients_plane->values[2]);
			tempplaneparas.push_back(coefficients_plane->values[3]);
			planeparas.push_back(tempplaneparas);
			srand((unsigned)time(NULL));


			extract.setNegative(true);
			extract.filter(*cloud_cluster);
			extract.setIndices(inliers);
			extract_normals.setNegative(true);
			extract_normals.setInputCloud(cloud_normals);
			extract_normals.setIndices(inliers);
			extract_normals.filter(*cloud_normals);

			

			i++;

		}


		j++;
	}




`

**Comment by ArtEdur** [comment]
After today's debug,i found that,it spend a lot of time at the normal estimation and the extract(cluster),however it didn't spend a lot of time ,if i run the code in a console application.

**Comment by WargodHernandez** [comment]
Are you running CC in debug mode or release?

**Comment by ArtEdur** [comment]
Yeah I run the cc in the release Mode,I think there may be another way to realize the plugin based on the PCL library,the Example Standard may be not suitable for it.

**Comment by theadib** [comment]
Hello ArtEdur,
does your problem still exists? I developed the qJsonRPC plugin.
My problem for debugging was, that CC only starts plugins from dedicated (hardcoded) locations.
I put a symbolic link in one of those directories to my current plugin build folder in order to debug the current version which is under development and not the distributed version.

HTH, Adib.
