### ISSUE TITLE
Issue when creating Contour lines (missing iso-lines)

### ISSUE THREAD

**Issue by oebviliesenfeld** [CloudCompare/CloudCompare#1313]
Hello,

when creating contour lines from a point cloud, some contour lines are "forgotten" in the current version (2.11.1) of Cloudcompare. 
In the older version 2.10 it works without any problems (and the same settings). See the screenshots:

CC v2.11
https://ibb.co/g60T6dp

CC v2.10
https://ibb.co/cCLb8rX

This is the Pointcloud i was using:
https://workupload.com/file/aEyVhKTmgyw

Best regards
Thomas

**Comment by oebviliesenfeld** [comment]
Ok, thank you very much!

**Comment by dgirardeau** [comment]
Here is the preview version: https://www.cloudcompare.org/release/Cl ... up_x64.exe

Hope this helps.

**Comment by oebviliesenfeld** [comment]
I've just tested the new build and it works perfect again. Thank you very much!
