### ISSUE TITLE
VTK writer makes 'malformed file'

### ISSUE THREAD

**Issue by xroynard** [CloudCompare/CloudCompare#1316]
**The Bug:**

When loading a VTK file saved from a mesh with several Scalar Fields, I get error : 

> An error occured while loading 'Filename': malformed file

**My environment:**

CC Version (or git hash/tag): Version v2.11 (Anoia) 64-bit
OS & Version: Windows 10 64bit
Graphics card: Intel HD

**Comment by WargodHernandez** [comment]
I was able to reproduce the error on my side taking a mesh without scalar fields then exporting point coordinates to scalar fields (x, y, z) and then saving as a .VTK when reloading file cloud compare will load the mesh successfully and 1 scalar field before producing this error 
![image](https://user-images.githubusercontent.com/7495752/91482772-71f87e00-e85b-11ea-9670-fcb53c4e0bdf.png)

Tested on v2.10.0(Installed from cloudcompare website) - 2.12(Compiled source)

**Comment by dgirardeau** [comment]
Considering how old this code is, and how complex the VTK format can be, I wouldn't be surprised that this bug has been here forever ;)

**Comment by WargodHernandez** [comment]
not sure if it is the writer or the reader at fault the VTK spec I looked at wasn't super clear and the example files only ever contained one scalar for points and/or for cells.

Either we need to repeat the `POINT_DATA pointCount` before each scalar field when writing or we need to stop consuming `lastDataSize` after scalar fields while reading

**Comment by xroynard** [comment]
Repeat "POINT_DATA pointCount" before each scalar field works for me. So I think it's the writer that should be fixed.

Thanks,
Xavier

________________________________
De : Chris Brown <notifications@github.com>
Envoyé : jeudi 27 août 2020 à 21:50
À : CloudCompare/CloudCompare
Cc : xroynard; Author
Objet : Re: [CloudCompare/CloudCompare] VTK writer makes 'malformed file' (#1316)


not sure if it is the writer or the reader at fault the VTK spec I looked at wasn't super clear and the example files only ever contained one scalar for points and/or for cells.

Either we need to repeat the POINT_DATA pointCount before each scalar field when writing or we need to stop consuming lastDataSize after scalar fields while reading

**Comment by WargodHernandez** [comment]
I just found the VTK writer https://gitlab.kitware.com/vtk/vtk/-/blob/master/IO/Legacy/vtkDataWriter.cxx#L441 and it only does the `POINT_DATA pointcount` once before outputting all scalars, normals, etc...
So I believe the proper answer is to not consume lastDataSize after scalar fields while reading, I have tested and it works for me.

I don't have any other software to test our files against, but we should try to conform to whatever is out in the world currently

**Comment by WargodHernandez** [comment]
Going through the VTK legacy reader it looks like it wouldn't handle finding POINT_DATA multiple times unless there was a CELL_DATA in-between. 
When in the readPoint data function it tests against `CELL_DATA `but not `POINT_DATA `so it would cause an 

> "Unsupported point attribute type: "

 error in any software using the official VTK lib if we repeat the `POINT_DATA` line.

**Comment by WargodHernandez** [comment]
So unless anyone has a reason not to do it this way my plan is to follow the VTK implementation and use POINT_DATA once before all point normals, colors & scalars  (how the writer works currently) and then just modify the reader.

**Comment by dgirardeau** [comment]
Works with me!
