### ISSUE TITLE
Reading invalid LAS file, CloudCompare grabs all RAM and is killed

### ISSUE THREAD

**Issue by phma** [CloudCompare/CloudCompare#1317]
**Describe the bug**

I'm writing a program that writes LAS files. It produced the attached file, which has garbage in the nVariableLength field. I loaded it into CloudCompare to see what it looks like, but the computer froze for several minutes, then CloudCompare disappeared.
**How to reproduce**
1. Hit the open button or File|Open
2. Select this file

**Expected behaviour**

It should pop up an error saying that it reached end of file while reading variable-length records, or just say that the file is invalid.

**Additional context**

**Your environment**
 - CC Version (or git hash/tag): 2.10.3
 - OS & Version: Ubuntu Focal
 - Graphics card: Beignet
 - Qt Version (if compiling): Compiled with 5.12.5, running with 5.12.8
[719.las.gz](https://github.com/CloudCompare/CloudCompare/files/5144397/719.las.gz)

**Comment by dgirardeau** [comment]
What a tasty graphic card ;)

CC is relying on various 3rd party libraries to load LAS files (depending on the OS). We basically use PDAL, libLAS and LASlib... I checked on Windows and the issue only occurs with PDAL (LASlib opens the file fine, and I can't test with libLAS which is only used on macOS).

The issue happens in the method ```ILeStream& operator>>(ILeStream& in, LasHeader& h)``` in the LasHeader.cpp file. It reads as many elements in ```h.m_vlrCount``` without checking that the input stream (_in_) is in error state or not (I don't even know if that's possible with this ILeStream structure anyway).

Therefore I would suggest you to report this as an 'issue' to the PDAL project directly.

**Comment by dgirardeau** [comment]
Digging a little bit more, one would 'just' have to add the following test inside the 'Read regular VLRs.' loop:
```
if (!in.good())
{
	throw LasHeader::error("End of file reached (file seems corrupted)");
}
```

I've fixed it on my side but since I'm not using the latest version of PDAL (for various reasons), I'll let you report the issue and the (potential) fix to them.
