### ISSUE TITLE
command line: the 'LAST' keyword was not properly managed after -SF_OP

### ISSUE THREAD

**Issue by zdr3zdr** [CloudCompare/CloudCompare#1320]
**Describe the bug**
command line: the 'LAST' keyword was not properly managed after -SF_OP

**How to reproduce**
[0015.txt](https://github.com/CloudCompare/CloudCompare/files/5156241/0015.txt)
file "0015.txt":
953.044 1058.770 -8.883
953.064 1058.750 -8.893
953.094 1058.730 -8.893
953.114 1058.720 -8.893
953.144 1058.700 -8.903
953.174 1058.690 -8.903
953.194 1058.670 -8.903

command line:
"C:\Program Files\CloudCompare\CloudCompare.exe" -AUTO_SAVE OFF -NO_TIMESTAMP -O "0015.txt" -COORD_TO_SF Z -SF_OP LAST add -0.5 -C_EXPORT_FMT BIN -SAVE_CLOUDS FILE "0015_Add_(-0.5).bin" -CLEAR

**Expected behaviour**
Error:
"Invalid SF index! (after SF_OP)"

**Additional context**
It was work in version CC 2.10

**Your environment**
 - CC Version (or git hash/tag): 2.11.1
 - OS & Version: Win 10
 - Graphics card: GTX 1060
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
Have you tried with the 2.11.2? It was one of the remaining bugs that was fixed in this version normally.

**Comment by zdr3zdr** [comment]
-SF_OP LAST work in version 2.11.2.
Thanks.
