### ISSUE TITLE
M3C2 via CLI

### ISSUE THREAD

**Issue by danielfeldman** [CloudCompare/CloudCompare#1325]
**Describe the bug**
When I run M3C2 in the CLI and set the parameters file to use the pre-calculated normals of the first cloud it fails and recalculates the normals instead.
In the UI, using the same point clouds, it works fine.

**How to reproduce**
1. Take 2 clouds: the first one should contain normals in it, and the second may or may not have normals (I used ply files). 

2. Ran the following command:
CloudCompare -O cloud_1_with_nomals.ply -O cloud_2.ply -M3C2 m3c2_params_normals-cloud1.txt

3. The job will be completed successfully but you will see this error log: "Can't restore the previous normal computation method (cloud#1 or core points has no normals)"
![cli-window_can-not-restore-normals](https://user-images.githubusercontent.com/39147140/93189638-082d0f00-f74b-11ea-8959-9c0d60c137ab.png)

You can find the parameters file here:
[m3c2_params_normals-cloud1.txt](https://github.com/CloudCompare/CloudCompare/files/5223009/m3c2_params_normals-cloud1.txt). 
It was created using the "save" option in the UI. 

**Expected behavior**
The CLI should behave the same as the UI and use the pre-calculated normals.

**Your environment**
 - CC Version (or git hash/tag): v2.10.2 and v2.11.3
 - OS & Version: Windows 10

 - Experienced the same issue with CC v2.10.2 on Linux 18.04

**Comment by dgirardeau** [comment]
I guess we will need to look at this in depth, but that may take some time!

**Comment by danielfeldman** [comment]
Thanks for the response.
Do you think it is a matter of days/weeks?

**Comment by dgirardeau** [comment]
At least a week I would say... I don't have a lot of time right now, and debugging the Command Line (and especially big plugins like M3C2) is always tedious...

**Comment by dgirardeau** [comment]
Okay I think I found the issue. I fixed the code (deab9fac267da3fc7985df643777452c5213494e)

**Comment by dgirardeau** [comment]
I uploaded the latest 2.12.alpha version online (for Windows). I'll wait for your feedback.

**Comment by dgirardeau** [comment]
Ok it's now online

**Comment by danielfeldman** [comment]
Thank you! It works fine now! I compared the UI and the CLI result and it seems to be the same. 
* A small issue that still exists is that the error message still appears: "Can't restore the previous normal computation method (cloud#1 or core points has no normals)" - it does not really bother me (because it works) but I wanted to bring it to your attention. 

In addition, I have a follow-up question, If I want to use this latest version in a docker with ubuntu image - do you suggest just to pull the master version and move to your commit (with the fix)? or do you plan to create a tag for that 2.12.alpha version?
(right now I have been working with v2.10.2 tag - which was built in the docker).
I am open to other suggestions of course =] 

Thanks again.

**Comment by dgirardeau** [comment]
Sorry I didn't see your last question. We generally don't create tags for alpha or beta versions... So I guess the only way would be to pull the master branch indeed.
