### ISSUE TITLE
How could I get the xyz coordinates of label points through the cloudcompare API

### ISSUE THREAD

**Issue by XieJinLiang** [CloudCompare/CloudCompare#1326]
I opened a pcd point cloud file through cloudcompare, and marked some 2D label points and saved them as cc entities bin files.
The question is : How should I get the xyz coordinates of these label points through the API of cloudcompare? I read the codes of cc2DLabel.cpp and BinFilter.cpp, but did not find the relevant method.

**Comment by dgirardeau** [comment]
Something like cc2DLabel::PickedPoint::getPointPosition()?
https://github.com/CloudCompare/CloudCompare/blob/master/libs/qCC_db/src/cc2DLabel.cpp#L83

And since you can have up to 3 points associated to a label, you'll have to request the right point with cc2DLabel::PickedPoint& getPickedPoint.
