### ISSUE TITLE
How to understand DgmOctree?

### ISSUE THREAD

**Issue by Micalson** [CloudCompare/CloudCompare#1328]
In CC_Core, DgmOctree is a effective data structure for point cloud, and I want to use it in my own data. So, How to understand it. 
Could anyone explain it? Thank you.

Regards,

**Comment by dgirardeau** [comment]
Well, you have a short explanation of the Octree "philosophy" here: [https://www.danielgm.net/phd/isprs_laserscanning_2005_dgm.pdf]()

But then most of the information will be via the code documentation and usage example through out the code base of CloudCompare...

**Comment by Micalson** [comment]
Sorry, The link you provided is wrong. It points to this page.
