### ISSUE TITLE
'the third-party library has failed to perform the operation' when loading a ply file

### ISSUE THREAD

**Issue by epoc88** [CloudCompare/CloudCompare#1329]
**Describe the bug**

did not load the ply file
https://drive.google.com/file/d/1u15avxt5JRCSqQWPMJE_XbZeDKhbsoXJ/view?usp=sharing

**How to reproduce**
unable to load ply file. and  it reproduce everytime

**Expected behaviour**
load the ply file, it will show the error from both ccViewer and Cloud Compare version.

**Additional context**

**Your environment**
 - CC Version (or git hash/tag):
 - OS & Version: Ubuntu 16.04
 - Graphics card:  Nvidia Quadro P5000
 - Qt Version (if compiling): QT5.2

**Comment by dgirardeau** [comment]
On the Windows 2.12 version (= master branch), the file opens well...Which version are you using?

**Comment by epoc88** [comment]
latest Ubuntu version, 1.39 64bit. Will there be a fix to linux version?

**Comment by theadib** [comment]
I tested the file using Ubuntu 20.10 an snapcraft CloudCompare 2.11. loading without crash on default parameters.
The recent development version 2.12 loads this file also fine.

Adib.

**Comment by ferreram** [comment]
@epoc88 This might be due to the fact that you are trying to load a ply file which is stored on an external media, try storing the ply file directly on your computer's hard-drive.

**Comment by juliangaal** [comment]
@ferreram suggestions fixed my issue, thanks!

**Comment by YuanwenFu** [comment]
Another possible reason is that there is Chinese in the path!
