### ISSUE TITLE
how to convert pointclod RGB field to scale field from command line

### ISSUE THREAD

**Issue by zhixiongzuo** [CloudCompare/CloudCompare#1330]
Thanks for your excellent work, I want to use cloudcompare on my remote server, just find there is no way to convert RGB field to SF from command line . Is there a command line to convert RGB field to SF that I just don't know , or any tips ?

**Comment by HeadLessHUN** [comment]
I think it is already done, since then. #1539

-RGB_CONVERT_TO_SF
