### ISSUE TITLE
Command Line access for Noise filter

### ISSUE THREAD

**Issue by jfmonod** [CloudCompare/CloudCompare#1333]
Hi, 
I'd like to request exposing the Noise filter to the command line just like the SOR filter is. 

Thanks,

Jean-Frederic Monod

**Comment by prasadvagdargi** [comment]
Any hints on how the SOR filter is exposed? I couldn't quite find it in the code.

**Comment by dgirardeau** [comment]
See https://github.com/CloudCompare/CloudCompare/blob/master/qCC/ccCommandLineCommands.cpp#L2644

**Comment by Oyla-Inc** [comment]
Following up on this.. is there a plan to add Noise filter to command line interface. It will be very useful. Great Work

**Comment by jambus1986** [comment]
you do really good work, guys,

it would help me too, plllsss add noise to commandline, thx

**Comment by dgirardeau** [comment]
Ok, I've added it!

- new option '-NOISE (KNN/RADIUS {value 1} REL/ABS {value 2} -RIP':
	- To apply the Noise filter to the loaded point clouds
	- value 1: number of neighbors if KNN, radius if RADIUS
	- value 2: relative error (standard deviation multiplier) if REL, absolute error if ABS
	- -RIP: remove isolated points (optional)

You'll have to use the latest 2.12.alpha version (online)

**Comment by dgirardeau** [comment]
I'll let you test the new version ;)
