### ISSUE TITLE
ccViewer cannot open non-english filenames from cmd

### ISSUE THREAD

**Issue by gregkotsaftis** [CloudCompare/CloudCompare#1335]
I use a cmd console to execute ccViewer and pass along a filename that contains non-english characters e.g. Greek

If the filename contains non-english characters then this happens
![image](https://user-images.githubusercontent.com/3630283/96099711-35044b80-0edc-11eb-8857-6273f72b65dd.png)

If i use e.g. Photoshop to open the same file from cmd, it opens without errors.
![image](https://user-images.githubusercontent.com/3630283/96100726-5dd91080-0edd-11eb-9a41-6d7cd0763282.png)

OS: Windows 10 Pro v2004
Display language: English
Locale: Greek

**Comment by dgirardeau** [comment]
Ok that should be fixed now (db6745f5c1529615aa3bfdf1aae49f4822dc6403).

I've uploaded the latest version of ccViewer on the official website (and here's the shortcut: https://www.cloudcompare.org/release/ccViewer_v1.40.alpha_bin_x64.7z)

**Comment by gregkotsaftis** [comment]
Yes I can verify that the problem if fixed in v1.40.alpha.
Thnx and keep up the good work!
