### ISSUE TITLE
CMD line: add option to "use sensors" when using COMPUTE_NORMALS  and OCTREE_NORMALS

### ISSUE THREAD

**Issue by onitreb** [CloudCompare/CloudCompare#1339]
This is actually 2 requests, but either solution would be welcome:
1) Automatically compute normals with sensors with the "compute_normals" command (with e57 files)
2) Add option to 'use sensors' when using the octree_normals command.

This would be helpful when computing normals of e57 files using the command line.

The GUI has the option to "use sensors when possible", but currently is is not possible compute e57 normals correctly, based on the sensor position, at the command line.

PTX and FARO files work correctly. The issue is PTX (exported from FARO Scene) are enormous files and take forever to export.

**Comment by jambus1986** [comment]
he is right,
i have the same problem too, 
greets

**Comment by jambus1986** [comment]
the original issue is from october, but its still
actual to me,....is there already any news about
CMD line: add option to "use sensors" when using COMPUTE_NORMALS?

it would be the last brick in my project, that
CC could do everything itself...

thx for your answer,
Unfortunately i am no real programmer, who could solve
this problem on his own :\

**Comment by dgirardeau** [comment]
Hi.

Since the COMPUTE_NORMALS is used to compute normals of structured scans (PTX, FARO, DP) and it's already using the sensor (origin), I assumed you were referring to the OCTREE_NORMALS method?

I added a '-ORIENT SENSOR_ORIGIN' option to allow using the associated sensor origin as orientation point.

**Comment by dgirardeau** [comment]
I'll update the 2.12.alpha version (for Windows) later today.

**Comment by dgirardeau** [comment]
Ok, the latest 2.12.alpha version is now up to date.

**Comment by jambus1986** [comment]
hi, i testet it with e57 files,  in CC Program there are sensor-Data for each node,
but in Commandline with -ORIENT SENOR_ORIGIN 
it says that there is none :(

i used latest alpha version

commandline output:

[E57] 'formatName' - ASTM E57 3D Imaging Data File
[E57] 'guid' - {E40A3B57-4B74-49EB-AB3F-8739BC817137}
[E57] 'versionMajor' - 1 (INTEGER)
[E57] 'versionMinor' - 0 (INTEGER)
[E57] Reading new scan node (0) - strohhacker001
[E57] Internal description: this file is generated by Autodesk ReCap
[E57] Reading new scan node (1) - strohhacker002
[E57] Internal description: this file is generated by Autodesk ReCap
[E57] Reading new scan node (2) - strohhacker003
[E57] Internal description: this file is generated by Autodesk ReCap
[E57] Reading new scan node (3) - strohhacker004
[E57] Internal description: this file is generated by Autodesk ReCap
[E57] Reading new scan node (4) - strohhacker005
[E57] Internal description: this file is generated by Autodesk ReCap
[E57] Reading new scan node (5) - strohhacker007
[E57] Internal description: this file is generated by Autodesk ReCap
[E57] Reading new scan node (6) - strohhacker009
[E57] Internal description: this file is generated by Autodesk ReCap
[E57] Reading new scan node (7) - strohhacker010
[E57] Internal description: this file is generated by Autodesk ReCap
[E57] Reading new scan node (8) - strohhacker011
[E57] Internal description: this file is generated by Autodesk ReCap
[E57] Reading new scan node (9) - strohhacker012
[E57] Internal description: this file is generated by Autodesk ReCap
[E57] Reading new scan node (10) - strohhacker013
[E57] Internal description: this file is generated by Autodesk ReCap
[E57] Reading new scan node (11) - strohhacker014
[E57] Internal description: this file is generated by Autodesk ReCap
[I/O] File 'D:\Punktwolken\HankeStrohhacker3\Strohhacker.e57' loaded successfully
Found one cloud with 5683280 points
Found one cloud with 4546411 points
Found one cloud with 3768101 points
Found one cloud with 3824038 points
Found one cloud with 2219694 points
Found one cloud with 2953949 points
Found one cloud with 2620423 points
Found one cloud with 2894978 points
Found one cloud with 2307236 points
Found one cloud with 1270659 points
Found one cloud with 2254771 points
Found one cloud with 2293816 points
[OCTREE NORMALS CALCULATION]
        Radius: 0.015
computeNormalsWithOctree started...
[UpdateNormalOrientations] Could not found a valid sensor child
[ComputeCloudNormals] Timing: 70.54 s.
computeNormalsWithOctree success
cloud->hasNormals: 1
computeNormalsWithOctree started...
[UpdateNormalOrientations] Could not found a valid sensor child
[ComputeCloudNormals] Timing: 69.61 s.
computeNormalsWithOctree success
cloud->hasNormals: 1
....
![Snap 2021-07-20 at 22 57 10](https://user-images.githubusercontent.com/83144510/126394466-4cc8daba-5a93-4969-b6b6-e96e98f38299.png)

**Comment by dgirardeau** [comment]
Sorry for the long wait: I finally fixed the bug! I fixed it: a517fedaadfe0250b0258f5d4526015c6c3fdaf1

An updated version of CC 2.12.alpha will soon be online.
