### ISSUE TITLE
qJSonRCPPlugin fails to build on Linux because inconsistent naming scheme.

### ISSUE THREAD

**Issue by bartoszek** [CloudCompare/CloudCompare#1340]
There's a problem when building on Linux host.
Because `cloudcompare` capitalize `s` in `qJSonRPCPlugin` cmake fails to locate `qJSonRPCPlugin.qrc` file.
_Error introduced in:_ fc3792df536ad72d594d5f7cd81abb8c045d73f2
_Build log:_ https://travis-ci.org/github/CloudCompare/CloudCompare/jobs/740290471#L2705
```
-- Found submodule plugin: /build/cloudcompare-git/src/cloudcompare/plugins/core/Standard/qJSonRPCPlugin
CMake Error at plugins/cmake/Plugins.cmake:82 (message):
  Missing qrc file:
  /build/cloudcompare-git/src/cloudcompare/plugins/core/Standard/qJSonRPCPlugin/qJSonRPCPlugin.qrc
Call Stack (most recent call first):
  plugins/core/Standard/qJSonRPCPlugin/CMakeLists.txt:9 (AddPlugin)
```
The file is named `qJson...` not `qJSon...` 🚧 
https://gitlab.com/theadib/JSonRPCPlugin/-/blob/master/JsonRPCPlugin.qrc

**Comment by dgirardeau** [comment]
b31125553205963fe3fd990f724ef85abf959369 should fix this issue.

**Comment by dgirardeau** [comment]
Ok, not yet :D. I'm working on it.

**Comment by dgirardeau** [comment]
Ok, that's fixed now.
