### ISSUE TITLE
CloudCompare: error while loading shared libraries: libCCAppCommon.so: cannot open shared object file

### ISSUE THREAD

**Issue by theadib** [CloudCompare/CloudCompare#1345]
**Describe the bug**
after fresh make and install CloudCompare does not start. as of: 2020-11-03
```
make
sudo make install
CloudCompare
CloudCompare: error while loading shared libraries: libCCAppCommon.so: cannot open shared object file: No such file or directory
```

The distributed executable does not find the dynamic libraries:
```
adib@vega:~/Projekte/mycc/CloudCompare/build$ ldd /usr/local/bin/CloudCompare 
	linux-vdso.so.1 (0x00007ffc243f5000)
	libCCAppCommon.so => not found
	libQt5PrintSupport.so.5 => /lib/x86_64-linux-gnu/libQt5PrintSupport.so.5 (0x00007f168c94e000)
	libCCPluginAPI.so => not found
	libQCC_GL_LIB.so => not found
	libQCC_IO_LIB.so => not found
	libQCC_DB_LIB.so => not found
	libCCCoreLib.so => not found
```
The dynamic library was pushed to 
-- Installing: /usr/local/bin/libCCAppCommon.so
And the application is in:
/usr/local/bin/CloudCompare

There is no RPATH information in the binary.
https://stackoverflow.com/questions/58997230/cmake-project-fails-to-find-shared-library
```
readelf -d /usr/local/bin/CloudCompare

Dynamic section at offset 0x5d2670 contains 43 entries:
  Tag       Typ                          Name/Wert
 0x0000000000000001 (NEEDED)             Gemeinsame Bibliothek [libCCAppCommon.so]
 0x0000000000000001 (NEEDED)             Gemeinsame Bibliothek [libQt5PrintSupport.so.5]
 0x0000000000000001 (NEEDED)             Gemeinsame Bibliothek [libCCPluginAPI.so]
```

**Root of the problem**
the dynamic libraries MUST go to /usr/local/lib instead /usr/local/bin

**Workaround**
https://blog.andrewbeacock.com/2007/10/how-to-add-shared-libraries-to-linuxs.html
This can only be a temparary workaround until dynamic libraries goes to /usr/local/lib path
```
echo "/usr/local/bin" > cloudcompare.conf
sudo mv cloudcompare.conf /etc/ld.so.conf.d
sudo ldconfig
```
**Environment**
I am using Ubuntu 20.10

**Comment by theadib** [comment]
I see this is a duplicate to https://github.com/CloudCompare/CloudCompare/issues/1298

But I do not know how to link to the other ticket.

Adib.
--
Duplicate of #1298

**Comment by theadib** [comment]
PS: my cmake version is 3.16.3

I see all the magic happens in file cmake/Cmake.install

BUt I don't know cmake to figure out if this is a bug or intended behaviour.

???

Adib.

**Comment by theadib** [comment]
same problem as #1294

**Comment by theadib** [comment]
**workaround 2**

```
export LD_LIBRARY_PATH=/usr/local/bin
CloudCompare
```

**Comment by theadib** [comment]
**workaround 3**

```
sudo mv /usr/local/bin/libCC*.so /usr/local/lib
sudo mv /usr/local/bin/libQCC*.so /usr/local/lib
```

**Comment by rjanvier** [comment]
yes, it should work but should be done (and used to be done) by the cmake script... And I fear you have to do the same with shaders and plugins.

**Comment by theadib** [comment]
at least plugins are loaded from the CloudCompare. The program looks into the preprogrammed fixed path.

**Comment by theadib** [comment]
Issu has been solved with this commit 
https://github.com/CloudCompare/CloudCompare/commit/e65258c064fcd28c034801166ba10bc0b05aa3a9
see above
