### ISSUE TITLE
Fails to load textures

### ISSUE THREAD

**Issue by schmohlo** [CloudCompare/CloudCompare#1347]
CC suddently stopped loading textures from .obj or .fbx.
It works fine for CCs .bin files, though.

I've tried reinstalling v2.10.1 and 2.11.3. The only difference is, in 2.10 the object is black, in 2.11 it is invisible.

[console.txt](https://github.com/CloudCompare/CloudCompare/files/5518248/console.txt)

Edit: 
The untextured mesh is also only shown after changing the default point size or line width. It disappears again after moving the camera.

**Comment by dgirardeau** [comment]
Can you try with the 2.12.beta version?

For OBJ, it can be due to badly shaped MTL files (the parameters 'Alpha' - 0 for transprent - and 'Transparency' - 1 for transparent - are sometimes mixed).

But for FBX, this should normally be managed properly...

**Comment by schmohlo** [comment]
Thanks for the quick reply.

I only found 2.12.alpha. The problem persists. It's definitely not the file, because they work just fine on other computers.

I suspect there is something seriously wrong in the background of my installations. There are also some icons missing (see image).
![grafik](https://user-images.githubusercontent.com/35264015/98697565-5b02fb80-2375-11eb-90f7-1fd8618ffa18.png)

**Comment by dgirardeau** [comment]
Hum, as if Qt's "image plugins" are missing. They should be in a folder named "imageformats" just next to CloudCompare.exe. And you should have a bunch of them (gif, svg, etc.)

**Comment by dgirardeau** [comment]
Otherwise it means they are not properly loaded by your system (for an unknown reason...)

**Comment by schmohlo** [comment]
That was it, thank you very much!

I had recently installed QT3 to recompile some older projects. After uninstalling QT3, everything works fine again. It probably tried to use those old qt dlls.
