### ISSUE TITLE
Incorrect segmentation when using existing polyline contour

### ISSUE THREAD

**Issue by vik748** [CloudCompare/CloudCompare#1350]
**Describe the bug**

When using an existing polyline contour to segment a planar pointcloud, if the whole scene is not in the view, CC incorrectly segments with a line where the view ends on screen

**How to reproduce**

1. Create a plane 
2. Sample the plane to a point cloud
3. Import the attached [polyline contour](https://github.com/CloudCompare/CloudCompare/files/5528226/Morgan_2_contour.zip)
4. Start segmentation and use the polyline for segmenting
5. Zoom in so that only a part of the cloud is in view
6. Finish segmentation

You will notice that the resulting segmented cloud ends where the view ends.

**Expected behaviour**

Irrespective of the view, CC should correctly segment based on the polyline

**Additional context**

See attached images highlighting the issue
![cc_bug](https://user-images.githubusercontent.com/23345159/98895168-743ea180-2474-11eb-959e-362adf629de9.png)
![cc_bu_2](https://user-images.githubusercontent.com/23345159/98895167-73a60b00-2474-11eb-8e68-82a6c6ed3202.png)

[Morgan_2_contour.zip](https://github.com/CloudCompare/CloudCompare/files/5528226/Morgan_2_contour.zip)

**Your environment**
 - CC Version (or git hash/tag): 2.11.1
 - OS & Version: Ubuntu 16.04
 - Graphics card: RTX 2080
 - Qt Version (if compiling): N/A

**Comment by dgirardeau** [comment]
Have you tried with the 2.11.3 or the 2.12.alpha? I believe there's a related bug which has been fixed in the 2.12.alpha at least.

**Comment by vik748** [comment]
Unfortunately I don't have the setup to compile and install different versions so am using the pre-compiled binaries available for Ubuntu 16.04.

**Comment by dgirardeau** [comment]
Ok that's fixed on the master branch. Just in case, I've updated the Windowse 2.12.alpha version online (I can't help for the Linux version)
