### ISSUE TITLE
Sequentially toggles the visibility

### ISSUE THREAD

**Issue by traum100** [CloudCompare/CloudCompare#1351]
Can I make a plugin or script that sequentially toggles the visibility property of loaded files?

The desired behavior is as follows:

1. Load consecutive point cloud files. 
(Sort by file name, map0, map1, map2...)

2. Make all files unvisible.

3. Turn on visible the files at time intervals.
(show map0 -> wait 1sec -> show map1 -> wait 1sec -> show map2 -> ... )

This will look like an animation of growing point clouds.
This will be especially useful when displaying 3D mapping results.

**Comment by dgirardeau** [comment]
Yes, I think it's definitely possible. Basically if the user where to select a group/folder in the DB tree, you could easily add an action to your plugin that:
- retrieve the children entities under the select group (in a vector)
- sort them by name or whatever
- and then start a loop (or a background process with QTimer if you want the application to stay responsive) and change their visibility one by one (with 'setEnable' typically, which is common to all CC entities).

**Comment by traum100** [comment]
As you said, the example plugin was modified to implement the function. Works well thanks.

`// Example of a plugin action

#include "ccMainAppInterface.h"
#include <thread>

namespace Example
{
	// This is an example of an action's method called when the corresponding action
	// is triggered (i.e. the corresponding icon or menu entry is clicked in CC's
	// main interface). You can access most of CC's components (database,
	// 3D views, console, etc.) via the 'appInterface' variable.

	std::thread* aThread;
	void loop(ccMainAppInterface* appInterface)
	{
		const ccHObject::Container& selectedEntities = appInterface->getSelectedEntities();
		int num = selectedEntities.size();
		
		QString numStr;
		numStr.sprintf("%d cloud selected", num);
		appInterface->dispToConsole(numStr, ccMainAppInterface::STD_CONSOLE_MESSAGE);

		ccHObject::Container clouds;
		for (int p = 0; p < num; p++)
		{
			ccHObject* ent = selectedEntities[p];
			if (ent->isA(CC_TYPES::POINT_CLOUD))
			{
				ent->setVisible(false);
				clouds.push_back(ent);
			}
		}

		std::sort(clouds.begin(), clouds.end(), [](ccHObject* a, ccHObject* b)
		{
			QString name_a = a->getName();
			QString name_b = b->getName();

			int num_a = name_a.remove("submap_").toInt();
			int num_b = name_b.remove("submap_").toInt();

			return num_a < num_b; 
		});

		for (int p = 0; p < 10; p++)
		{
			QString str;
			str.sprintf("wait %d", p + 1);
			appInterface->dispToConsole(str, ccMainAppInterface::STD_CONSOLE_MESSAGE);
			Sleep(1000);
		}
		
		for (int p = 0; p < clouds.size(); p++)
		{
			ccHObject* ent = clouds[p];
			if (ent->isA(CC_TYPES::POINT_CLOUD))
			{
				ent->setVisible(true);
				appInterface->redrawAll();

				QString name = ent->getName();
				QString str;
				str.sprintf(" show %d/%d", p + 1, clouds.size());
				appInterface->dispToConsole(name + str, ccMainAppInterface::STD_CONSOLE_MESSAGE);
				Sleep(100);
			}
		}
	}

	void performActionA( ccMainAppInterface *appInterface )
	{
		if ( appInterface == nullptr )
		{
			// The application interface should have already been initialized when the plugin is loaded
			Q_ASSERT( false );
			
			return;
		}
		
		/*** HERE STARTS THE ACTION ***/
	
		// Put your code here
		// --> you may want to start by asking for parameters (with a custom dialog, etc.)
		aThread = new std::thread(loop, appInterface);

		// This is how you can output messages
		// Display a standard message in the console
		appInterface->dispToConsole( "[ExamplePlugin] Hello world!", ccMainAppInterface::STD_CONSOLE_MESSAGE );
		
		// Display a warning message in the console
		appInterface->dispToConsole( "[ExamplePlugin] Warning: example plugin shouldn't be used as is", ccMainAppInterface::WRN_CONSOLE_MESSAGE );
		
		// Display an error message in the console AND pop-up an error box
		//appInterface->dispToConsole( "Example plugin shouldn't be used - it doesn't do anything!", ccMainAppInterface::ERR_CONSOLE_MESSAGE );
	
		/*** HERE ENDS THE ACTION ***/
	}
}
`

**Comment by dgirardeau** [comment]
Don't you have someting on your side? If yes, you can simply add the plugin files to a github repository (simply the files of your plugin) and we can then add a submodule to this repository under our 'plugins' folder.
