### ISSUE TITLE
Where can I see the code for Compute geometric features?

### ISSUE THREAD

**Issue by liupeng625** [CloudCompare/CloudCompare#1354]
I want to see the algorithm principle of calculating geometric features. How can I check?

**Comment by dgirardeau** [comment]
See https://github.com/CloudCompare/CCCoreLib/blob/master/src/GeometricalAnalysisTools.cpp#L24 and https://github.com/CloudCompare/CCCoreLib/blob/master/src/Neighbourhood.cpp#L805 (and also: https://www.cloudcompare.org/doc/wiki/index.php?title=Compute_geometric_features - you'll find the article where most of the features are described)
