### ISSUE TITLE
Inconsistent usage of arrays.isInvalidIntData (L556, L1832 of E57Filter.cpp).

### ISSUE THREAD

**Issue by SebWouters** [CloudCompare/CloudCompare#1355]
On https://github.com/CloudCompare/CloudCompare/blob/master/plugins/core/IO/qE57IO/src/E57Filter.cpp#L556 the convention 0 for valid and 1 for invalid is used for arrays.isInvalidIntData, thereby answering the question posed in the variable name.

However, on https://github.com/CloudCompare/CloudCompare/blob/master/plugins/core/IO/qE57IO/src/E57Filter.cpp#L1832 intensity data is used when arrays.isInvalidIntData[i] is 1.

**Comment by dgirardeau** [comment]
Good catch!

4df5bcee3db616f46dc70cc28a33834f803cbf3e should fix it.
