### ISSUE TITLE
Improve/Clean LAS file support

### ISSUE THREAD

**Issue by tmontaigu** [CloudCompare/CloudCompare#1356]
We have a problem with LAS file handling:

There are 2 plugins that can read/write LAS files:
 1. `qPDALIO`  which uses PDAL
 2. `qLASFWFIO` which uses LASlib

Both PDAL and LASLib handle the compressed LAZ format, both supports the LAS 1.4 version,
The difference is that LASLib supports waveform data while PDAL does not.

Also on macOs, a different plugin is shipped with CC to provide LAS support([asmaloney/LASIO](https://github.com/asmaloney/LASIO) it is the old plugin that was the main one until qPDALIO was introduced) which uses `libLAS`.
`libLAS`  does not support the newer 1.4 format or waveform data, and we sometimes get issues about 1.4 files
 (https://github.com/CloudCompare/CloudCompare/issues/1308, https://github.com/CloudCompare/CloudCompare/issues/550)

Ideally there should be only one LAS plugin that supports all LAS features, that is easy to compile and ship on
the 3 main platform (Linux, Windows, macOs).

**Describe alternatives you've considered**

I think we should deprecate/remove the qPDALIO plugin as the main LAS Filter and use either the `qLASFWFIO` (and improve it)
or create a new one based based on [Laszip](https://github.com/LASzip/LASzip) (laszip support the needed features as LASlib, 
it essentially is the same codebase as LAStools/LASlib and may be easier to compile / integrate on the 3 platforms).

Using a LAS specific lib (which PDAL is not as it support a lot more format other than LAS) would also give us more control
and probably resolve some other LAS related issues (https://github.com/CloudCompare/CloudCompare/issues/915, https://github.com/CloudCompare/CloudCompare/issues/1008, https://github.com/CloudCompare/CloudCompare/issues/1305)

qPDALIO could then be reworked to handle all formats that PDAL support, and being a filter with less priority.

**Comment by dgirardeau** [comment]
I approve! I believe we just need to find a solution that works on the 3 OSes? Can Laszip really be used alone? Or does it require a lot of work to complement it?

**Comment by tmontaigu** [comment]
Yes the main thing we need a solution that works on the 3 platforms.

I think Laszip should be usable alone to do the processing we do.

**Comment by tpwrules** [comment]
Has there been any progress on this? The issue of mine you linked is still a problem for me.

**Comment by tmontaigu** [comment]
I worked on a doing a different [plugin](https://github.com/tmontaigu/LAS-IO) but stopped when it was time to do full waveform support.

**Comment by tmontaigu** [comment]
So I got the plugin to successfully read LAS files with waveforms which was the main blocking thing to go further.

**Comment by tmontaigu** [comment]
I think the plugin now has the the functionnalities, it now mostly needs polishing and testing.

- It tries to pick the 'best' LAS version when saving a cloud which does not come from a LAS file which should fix #1305.
- It allows user to select the version & point format they want to save a cloud in
- It keeps and restores all VLRs wich should fix #1008 and partially fix #915
- It handles waveforms (there is still a small quirck)
- It uses LASzip which is easy to build(and LASzip doesn't require dependencies) so it should be easy to deploy on the 3 platforms we target.

**Comment by reppiZ** [comment]
@tmontaigu Whats the progress on this? I'm in dire need of this functionality and would be happy to be a test bunny for you. I currently can not get .las files to even open on CloudCompare and desperately need to do this.

**Comment by tmontaigu** [comment]
If you cant get any las file to open that means your CloudCompare was not compiled with the qPDALIO plugin enabled

**Comment by reppiZ** [comment]
I know and I have been trying for a day now to get it compiled with that plug-in. PDAL was compiled and installed from source just fine. When I generate the build files with PDAL plugin, I get no errors. However when I try to build them, I always get stopped at PDAL plug-in. I can't figure it out and could really use some help.

**Comment by reppiZ** [comment]
I finally got it to work with PDAL plugin. I think what was going on was that I built PDAL from source instead of using apt-get from the Ubuntu repositories. 

After using apt-get and following the CI workflow on GitHub for Ubuntu, everything seems to work.

**Comment by tmontaigu** [comment]
Closing as the new 'unified' plugin has been merged

**Comment by jbminster** [comment]
Well, the most current version of ccviewer for MacOS Sonoma (14.6.1) does not recognize .las nor .laz file name extensions.  ({Load]: Can't guess file format: unhandled file extension ,las) I am trying to view a property cloud file generated using "3d Scanner.app" on iPad iOS 17.x.

**Comment by rjanvier** [comment]
Please open a dedicated issue, thanks.
