### ISSUE TITLE
Failed cmake cloudcompare

### ISSUE THREAD

**Issue by Shen001** [CloudCompare/CloudCompare#1359]
when i cmake cc ，cmake get a error information 
"CMake Error at libs/qCC_db/CMakeLists.txt:9 (add_subdirectory):The source directory D:/code/cpp/CloudCompare/libs/qCC_db/extern/CCCoreLib does not contain a CMakeLists.txt file."

so, what should i do to fix this? thanks~

cmake(3.15.1)
visual studio 2017 community

**Your environment**
 - CC Version (or git hash/tag): current 
 - OS & Version: windows 10
 - Graphics card: NVidia 1050
 - Qt Version (if compiling): 5.10

**Comment by dgirardeau** [comment]
You probably forgot to initialize and pull the submodule (libs/qCC_db/extern/CCCoreLib)

**Comment by weixi234** [comment]
Yes, after adding the file(https://github.com/CloudCompare/CCCoreLib), it compiles successfully.

**Comment by Shen001** [comment]
yeah~i try it，that‘s’ awsome~~

**Comment by githubwys** [comment]
yeah~,so cool, it works
