### ISSUE TITLE
Coordinate system changed after editing and saving PCD file

### ISSUE THREAD

**Issue by JimmyPesto** [CloudCompare/CloudCompare#1360]
**Describe the bug**

As already mentioned in the Forum:
https://www.danielgm.net/cc/forum/viewtopic.php?f=9&t=3969&p=18285&hilit=PCD+rotated+by+90&sid=bea04ce7a93b52c784935e397126b620#p18285

When you import a PCD cloud for editing like segmentation and output the cloud back into the PCD file it will be rotated.
I can reproduce this on two different PCs. Its independent of the used PCD cloud file.

**How to reproduce**
Steps to reproduce the behaviour:
1. Drag and drop a PCD cloud file ("original.pcd") into CloudCompare.
2. Use the scissors segmentation tool and cut some parts of the cloud (not needed to reproduce the error, but it helps to see visual differences).
3. File -> Save -> PCD -> Filename: "segmented.pcd".
4. Run `pcl_viewer original.pcd segmented.pcd` to visualize both clouds in the same coordinate system.

**Expected behaviour**

The two clouds should still be aligned perfectly. There should only be one cloud visible. The full cloud "original.pcd" which is partly overlain by "segmented.pcd".

But you will see that the two clouds are 90° apart.

The behaviour can not be reproduced when importing "original.pcd" and "segmented.pcd" back into CloudCompare. Both Clouds share the same orientation in CloudCompare. Only visualizing the PCD exported files in PCL viewer makes the error visible.
When you import the "original.pcd" to CloudCompare and save it to a new file without editing "original_CCexport.pcd" this cloud will also be rotated the same way as "segmented.pcd". Visualizing `pcl_viewer original_CCexport.pcd segmented.pcd` both clouds will be aligned but not in their original position as they came from a depth cam or what ever.

**Workaround**

Save the segmented cloud as PLY format (either binary or ascii) and convert the PLY file to PCD with `pcl_ply2pcd` tool.
When visualizing clouds exported as PLY from CloudCompare in PCL the error is not happening.

**Your environment**
 - CC Version (or git hash/tag): 2.11.1 (Anoia) [Linux 64-bit]
 - OS & Version: Ubuntu 18.04.5 & 20.04
 - Graphics card: not used
 - Qt Version (if compiling): Compiled with Qt 5.9.5

**Comment by mbe19** [comment]
I encountered the same issue on Ubuntu 18.04, Cloud Compare v 2.11.1 (Anoia) compiled with QT 5.9.5

**Comment by dgirardeau** [comment]
Where can I find PCL viewer?

And do you have the problem with any PCD file, or just some? (I wonder if some PCD files have an associated position matrix or something like that that wouldn't be kept by CC, etc.).

**Comment by luca-penasa** [comment]
might be the viewport entry in the header? https://pointclouds.org/documentation/tutorials/pcd_file_format.html#
```
VIEWPOINT - specifies an acquisition viewpoint for the points in the dataset. This could potentially be later on used for building transforms between different coordinate systems, or for aiding with features such as surface normals, that need a consistent orientation.

The viewpoint information is specified as a translation (tx ty tz) + quaternion (qw qx qy qz). The default value is:

VIEWPOINT 0 0 0 1 0 0 0
```

I'd check whether in the offending pcds there is a non-identity viewpoint (?)

**Comment by JimmyPesto** [comment]
> Where can I find PCL viewer?
> 
> And do you have the problem with any PCD file, or just some? (I wonder if some PCD files have an associated position matrix or something like that that wouldn't be kept by CC, etc.).

Until now it was the same with every PCD file tested. This includes PCDs from different cams too.

I can post the header before and after CC import & export if you like.

**Comment by dgirardeau** [comment]
Yes good idea

**Comment by JimmyPesto** [comment]
Imported PCD in CC:
![grafik](https://user-images.githubusercontent.com/26494580/100234369-4739c680-2f2b-11eb-834d-54d846add3c9.png)

Header before:
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z normal_x normal_y normal_z curvature
SIZE 4 4 4 4 4 4 4
TYPE F F F F F F F
COUNT 1 1 1 1 1 1 1
WIDTH 229075
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 229075
DATA ascii
-2.3543241 -1.8079878 3.9958804 nan nan nan nan
-2.3442359 -1.8062618 3.9920657 nan nan nan nan
-2.3360384 -1.8059855 3.9914551 nan nan nan nan
-2.32811 -1.8059164 3.9913025 nan nan nan nan
-2.3200936 -1.8057784 3.9909973 nan nan nan nan
-2.3109293 -1.8047428 3.9887085 nan nan nan nan
```

Header after:
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS curvature _ normal_x normal_y normal_z _ x y z _
SIZE 4 1 4 4 4 1 4 4 4 1
TYPE F U F F F U F F F U
COUNT 1 12 1 1 1 4 1 1 1 4
WIDTH 32785
HEIGHT 1
VIEWPOINT 0 0 0 0.707107 -0.707107 0 0
POINTS 32785
DATA binary
```

CC when dropping in the previously saved PCD again:
![grafik](https://user-images.githubusercontent.com/26494580/100234806-e5c62780-2f2b-11eb-887e-694f06198c99.png)
This TGL/GBL thing looks like the visualization of the coordinate axis in PCL. Or is this sth. CC related?
You can see that the two TGL/GBL things are definitly messed up, not having the same directions.
But the clouds (original and the segmented) still match only in the CC view.

@dgirardeau the viewer is part of the standard pcl tools. If you installed pcl via `apt` you should find it in your path as `pcl_viewer`.
When you compile PCL yourself make sure you tell cmake to compile the tools too.

Running the `pcl_viewer`:
```
pcl_viewer path/to/ID-38-blabla.pcd
The viewer window provides interactive commands; for help, press 'h' or 'H' from within the window.
> Loading path/to/ID-38-blabla.pcd [PCLVisualizer::setUseVbos] Has no effect when OpenGL version is ≥ 2
[done, 127.576 ms : 32785 points]
Available dimensions: curvature _ normal_x normal_y normal_z _ x y z _

```

**Comment by dgirardeau** [comment]
Thanks.

The coordinates should not be changed/transformed (and CC only uses the coordinates, this is probably why the clouds are properly aligned when re-loaded in CC).

However I see that the "VIEWPOINT" definition changes. And that's probably why it's not displayed properly in pcl_viewer?

I personally don't know how the PCL I/O filter works in detail (I just remember it relies on the PCL library). But I guess something is not set properly at saving time?

**Comment by dgirardeau** [comment]
Can you restore the "VIEWPOINT" line to its original state and see what's the effect?

**Comment by JimmyPesto** [comment]
Does CC always export binary PCD or was it my choice somewhere?

When editing the `VIEWPOINT 0 0 0 1 0 0 0` in the output PCD the pcl_viewer does show nothing. Maybe because its binary format? Maybe I mess sth. up while editing idk. There is not even an error, just no cloud shown:
```
The viewer window provides interactive commands; for help, press 'h' or 'H' from within the window.
> Loading path/to/ID-38-blabla-VIEWPOINT-TEST.pcd [PCLVisualizer::setUseVbos] Has no effect when OpenGL version is ≥ 2
[done, 123.37 ms : 32785 points]
Available dimensions: curvature _ normal_x normal_y normal_z _ x y z _
```

**Comment by WargodHernandez** [comment]
This is really weird the transformation matrix for the TLS/GBL is different depending on how I select the object to look at it.
![image](https://user-images.githubusercontent.com/7495752/100263848-e1394900-2f02-11eb-9f7b-e17191286973.png)

This second image was taken after clicking off of the sensor but not on another item, and then selecting the sensor again

![image](https://user-images.githubusercontent.com/7495752/100264134-44c37680-2f03-11eb-98b1-7adc6d2b5c52.png)

if I apply this inverted to the TLS/GBL then CC will save with VIEWPOINT 0 0 0 1 -0 0 0

**Comment by WargodHernandez** [comment]
Also if I click on another item after this and scroll the properties window to the matrix, and then go back to the TLS/GBL it will look like the identity matrix again, but when saving the TLS/GBL acts as if it is internally stored as 
![image](https://user-images.githubusercontent.com/7495752/100264584-df23ba00-2f03-11eb-9e78-4ba2e18c1509.png)

**Comment by WargodHernandez** [comment]
If you load the pcd twice and then transform one TLS/GBL by the inverse of 
![image](https://user-images.githubusercontent.com/7495752/100264904-4f324000-2f04-11eb-94b3-e3c2ee48baa8.png) 
then you can see that internally the something is going on with our transforms for TLS/GBL
![image](https://user-images.githubusercontent.com/7495752/100265048-843e9280-2f04-11eb-9523-2f0e172c7dac.png)

**Comment by WargodHernandez** [comment]
When loading the PCD we are applying this to the sensor for the default viewpoint
![image](https://user-images.githubusercontent.com/7495752/100265461-25c5e400-2f05-11eb-971a-1c911b87af4b.png)
which seems to stem from 
![image](https://user-images.githubusercontent.com/7495752/100265616-60c81780-2f05-11eb-9956-c4e98b709f8c.png)

**Comment by WargodHernandez** [comment]
Everything works as expected when I change the above code to 

![image](https://user-images.githubusercontent.com/7495752/100267194-e8168a80-2f07-11eb-8998-d3b7a61c3371.png)

After that I can translate/rotate the TLS/GBL freely and save/load and get the expected results each time.

**Comment by dgirardeau** [comment]
Nice!

**Comment by dgirardeau** [comment]
Time for a PR? 😋

**Comment by PerceptMD** [comment]
Thanks! ;)

**Comment by JimmyPesto** [comment]
Thanks! ;)
