### ISSUE TITLE
CloudCompare ignores global shift when exporting shapes as DXF.

### ISSUE THREAD

**Issue by oebviliesenfeld** [CloudCompare/CloudCompare#1363]
If i import a point cloud and choose "Preserve global shift on save", CC says, that "shift/scale information is stored and used to restore the original coordinates at export time".
But it seems to fail when exporting shapes as a DXF, created with the plugin "RANSAC shape detection".
After opening the DXF in a CAD, all exported items have local coordinates. I have to apply the global shift manually to bring them back to the original coordinate system.

Here is a video that shows the issue: [https://youtu.be/d-KJAX0cuLA](https://youtu.be/d-KJAX0cuLA)

 - CC Version: 2.11.3
 - OS & Version: Windows 10, 20H2 (build 19042.630)
 - Graphics card: NVIDIA Geforce GTX 1080 Ti

Best regards
Thomas

**Comment by dgirardeau** [comment]
Actually the DXF filter does export coordinates in the 'global' coordinate system. Therefore I think the issue is more with the RansacSD plugin. I guess the Global Shift information is not transferred to the primitives this plugin creates.

**Comment by WargodHernandez** [comment]
I'd suggest manually segmenting the cloud and fitting a plane to edit, then export that to DXF and see if you have an issue with the global shift. 

I believe the newer ransac version uses the original points and just uses the fitting methods in CC. The older versions created new points and lost any extra info that was baked in to the cloud, but I changed that, I think the 2.11 version should respect the shift. 
I'll try to get a chance to look at it later today

**Comment by dgirardeau** [comment]
Actually the primitives didn't have any 'global shift & scale' information. And you can't set the vertices cloud (as with meshes). Therefore I generalized the concept of 'global shift & scale' information for meshes, so that it's easier and more explicit to set these pieces of information with meshes or primitives.

See https://github.com/CloudCompare/CloudCompare/pull/1364

I made a PR to enable that.

**Comment by oebviliesenfeld** [comment]
Thank you very much for all your answers. It's great to hear that it should work now. But where can i download an updated Windows version? If i go to [https://github.com/CloudCompare/CloudCompare/actions/runs/386077110/workflow](https://github.com/CloudCompare/CloudCompare/actions/runs/386077110/workflow), i can see two Windows builds and two macOS builds. But where is the download link? I'm relatively new to github, sorry. :-(

**Comment by dgirardeau** [comment]
I've just updated the 2.12.alpha version online. Let me know if it works (or not ;) ).

**Comment by oebviliesenfeld** [comment]
Thank you so much! I've just tested it and now it works fine.
