### ISSUE TITLE
Adding local coordinate system objects

### ISSUE THREAD

**Issue by WargodHernandez** [CloudCompare/CloudCompare#1365]
See http://cloudcompare.org/forum/viewtopic.php?p=22356#p22356

Here is an example of the local system models I use, 3 planes & 3 polylines which I always move together so they act like a local coordinate system reference. 
This lets me move objects in their local reference system which makes it really easy to adjust multiple objects together, it also allows me to measure clouds easily in their own coordinate system. 
![image](https://user-images.githubusercontent.com/7495752/100398448-73287b00-3003-11eb-83bb-a3941d1170b2.png)

I didn't really want to add it to the primitive factory as they pollute the DB tree and you need to keep all 6 objects grouped together for them to make sense. I thought a new primitive would make more sense and could allow you to create the primitive as an automatic child to be turned on/off through the properties window. But still allow them to be select-able for the  Advanced mode translate/rotate form and the measuring modes.

**Comment by dgirardeau** [comment]
Yes, adding a specific primitive would be perfect. Maybe with an option to show or hide the planes / axes maybe. And a scale of course.

**Comment by WargodHernandez** [comment]
Any thoughts on primitive name for a component like this? 

Here are a few possibilities but I am open to whatever:

- ccLocalReferenceSystem

- ccCoordinateSystem

**Comment by dgirardeau** [comment]
Ah, the options are good. The second is simpler?

**Comment by WargodHernandez** [comment]
Thinking about it, should there be 2 coordinate systems, 2D & 3D?
Or just a configuration option on a generic coordinate system?

**Comment by dgirardeau** [comment]
Which use case do you imagine for the 2D one? Isn't the 3D one always suitable?

**Comment by WargodHernandez** [comment]
Well yeah 3D is always suitable, I was just thinking about some other software I've used previously which would allow 2D coordinate systems. It seemed primarily to simplify some reporting options, like omitting the z coordinates when measuring point to point on a plane.

But for a first attempt at this primitive where almost none of those extras would exist, maybe I should just keep it simple

**Comment by WargodHernandez** [comment]
I think I like coloring the planes and having them offset rather than centered what do you think of this look?
![image](https://user-images.githubusercontent.com/7495752/100658876-98b7cc00-3304-11eb-951e-6f927c50f32b.png)

**Comment by dgirardeau** [comment]
Yes!
I also prefer the offset planes.

**Comment by WargodHernandez** [comment]
I ended up needing to modify ccGenericPrimitive to allow copying colors when using += operator, but you could use it for some other uses like possibly coloring faces on cubes with different colors

**Comment by WargodHernandez** [comment]
I've got the following properties setup and working now
![image](https://user-images.githubusercontent.com/7495752/100697864-fa4f5900-334b-11eb-999d-4f434e5edb4b.png)

- The coordinate system origin

- Planes visibility

- Planes Stippled

- Axis Lines visibility

- Axis width (same as normal line width but acts independent)

- Display Scale (modifies the size of the planes and axis drawn)

I'm thinking I'll have a PR tomorrow. mostly need to clean up the primitive factory additions. I think I'll do a another PR to add more useful interactions with the primitive and a few of the dialogs (Cloud to primitive distance measurements and advanced translate/rotate screen)

**Comment by dgirardeau** [comment]
Very good
