### ISSUE TITLE
Normal Orientation

### ISSUE THREAD

**Issue by petrasvestartas** [CloudCompare/CloudCompare#1366]
Hello,

I am using PCL for computing pointCloud normals using Visual Studio 2019.
Since I know that there would be no help on PCL github forum I would like to ask your help.

In CloudCompare normal orientation is performed using Minimal Spanning Tree.

Is there any possibility to explain me how can I orient already computed normals?
I would like to somehow implement such method using PCL for educational purpose.

I do not have a correct view point and the current pointcloud normals looks like this:

![image](https://user-images.githubusercontent.com/18013985/100456611-fc51b780-30c0-11eb-9019-9f2b78b32564.png)

**Comment by dgirardeau** [comment]
Do you mean that you want to do something equivalent to the Minimal Spanning Tree in PCL? They probably have it (or an equivalent) but I'm definitely not a PCL expert...

**Comment by petrasvestartas** [comment]
Yes. Apparently, there is no implementation to what cloud compare can do with normal orientation, just estimation while orienting normals based on a single point.

**Comment by petrasvestartas** [comment]
Open3D is probably now easiest way to do this:
![image](https://user-images.githubusercontent.com/18013985/100626992-beee6380-3326-11eb-996a-19ab08f29cdc.png)

**Comment by dgirardeau** [comment]
Ah, never heard about it. Thanks for the pointer.
