### ISSUE TITLE
Cork plugin build issue on linux.

### ISSUE THREAD

**Issue by bartoszek** [CloudCompare/CloudCompare#1368]
I've got a few issues when trying to build `qcork` plugin on Linux host. ( `env:{os:Linux,distro:Arch,clang:11.0.0}` )
Here's a PR that fixes those issues: https://github.com/CloudCompare/cork/pull/2
Last one involves masking streaming operators for `TopoCache` behind [`#define SUPPORT_TOPO_STREAM_OPERATORS`](https://github.com/CloudCompare/cork/blob/c914dbabfd2e31d82da3a32c47106ae58bd8c13e/src/mesh/mesh.topoCache.tpp#L456) 
This requires including `-DSUPPORT_TOPO_STREAM_OPERATORS` in `cxxflags` for both `cork` and `cloudcompare` build.

**Comment by christian-rauch** [comment]
https://github.com/CloudCompare/cork/pull/2 has been merged.

@bartoszek @dgirardeau This issue can be closed now.
