### ISSUE TITLE
Ask about file saving feature

### ISSUE THREAD

**Issue by Jane-Tran** [CloudCompare/CloudCompare#1369]
This is the great app and thanks for creating it. The application has helped me a lot in my work, visualization is very fast and convenient.
But I have a question is how quickly you can save file.I have a related problem when saving 5 million points as ply ASCII file but very long read and save time (20 seconds - 30 seconds). I wonder how you guys do them so quickly. I use a buffer to write data but the speed is still not improving, much of the time is spent converting data to string.
Thank you very much for your feedback ! @mardy @mankoff @renatoGarcia @eile @asmaloney

**Comment by dgirardeau** [comment]
Have you looked at the code maybe? (https://github.com/CloudCompare/CloudCompare/blob/master/libs/qCC_io/src/AsciiFilter.cpp). We simply use Qt for reading and splitting lines to individual tokens and then to numbers.

By the way, are you compiling in release mode? (debug is much slower).

**Comment by Jane-Tran** [comment]
Thank so much ❤️
