### ISSUE TITLE
plugin disappear after putting some codes in doAction

### ISSUE THREAD

**Issue by Hooooozier** [CloudCompare/CloudCompare#1372]
**Describe the bug**

the plugin i've made disappear when i insert some codes in doAction() function, my other plugins still works fine.
the codes was 
`       

    auto fileStream = std::make_shared<concurrency::streams::ostream>();
	concurrency::streams::ostream outFile = concurrency::streams::fstream::open_ostream(U("E:\\rest_data\\restful01.pts")).get();
	*fileStream = outFile; 
	std::string url("http://localhost:8080");
	http_client client(web::uri(conversions::to_string_t(url)));
	http_response response = client.request(methods::GET).get();
	response.body().read_to_end(fileStream->streambuf()).get();
	fileStream->close().get();
`

after i put these codes in my Plugin's doAction(), the icon of this plugin vanish from the plugin bar, and after i delete these codes, the icon come back again.

**Comment by dgirardeau** [comment]
Hum, do you have a warning in the Console about the plugin failing to load?

The only reason I would see why adding code would prevent the plugin to load would be that it requires a dependency that is not found.

**Comment by Hooooozier** [comment]
There is no warnings in the Console.
I install cpprestsdk via the NuGet in Microsoft Visual Studio, and it generate two dll in the plugin folder, one is my testplugin.dll and the other one is cpprest141_2_10.dll, i think the cpprest141_2_10.dll may be the dependency of my plugin.
It's my first time to write a plugin in a project, and i really hope you can help me to get through this. 
Thank you!

**Comment by WargodHernandez** [comment]
You'll actually need the cpprest141_2_10.dll in the parent folder not in the plugins folder.
The same folder as the cloudcompare.exe

**Comment by Hooooozier** [comment]
Thank you very much for helping me solve this problem.

**Comment by tmontaigu** [comment]
I'm closing as it seems resolved.
