### ISSUE TITLE
Add "Don't ask me again" check box to "Are you sure you want to quit?" dialog

### ISSUE THREAD

**Issue by alex-feldman** [CloudCompare/CloudCompare#1376]
**Describe the feature you would like**

Add "Don't ask me again" check box to "Are you sure you want to quit?" dialog

**Is your feature request related to a problem? Please describe.**

I tend to have many instances of CC open and occasionally want to close many of them at once. I have to click OK on every "Are you sure?" dialog and it is time consuming. (Admittedly less so, now that I've discovered Ctrl-clicking on the Windows taskbar icon...) 
I understand that dialog is there to protect the user from accidentally closing and losing work, but it would be nice to have a way to turn it off. Maybe it could be hidden in Preferences or something to not make it too easy for the user to turn the confirmation dialog off. Or, re-enable the dialog once per day.

Thanks for your time and for the great software.

**Comment by yd-yin** [comment]
Yes! I also request this feature for the similar reason
