### ISSUE TITLE
Can't import float-based .PLY files

### ISSUE THREAD

**Issue by roncapat** [CloudCompare/CloudCompare#1377]
**Describe the bug**
When a .PLY file (written with plyfile python library in my case, but also crafted by hand in text mode) is opened in CC, the following messages are displayed:

[PLY] Unable to open file
An error occurred while loading 'cloud_0': the third-party library in charge of saving/loading the file has failed to perform the operation.

I can read XYZ double pointclouds saved as PLY, but not XYZ floats.

**How to reproduce**
Create an ASCII file with the following content:
```
ply
format ascii 1.0
element vertex 4
property float x
property float y
property float z
end_header
0 0 0
0 0 0
0 0 0
0 0 0
```
and try to open it.

**Expected behaviour**
The program should handle different formats for fields x,y and z of PLY pointclouds

**Your environment**
 - CC Version (or git hash/tag): 2.11.1
 - OS & Version: Ubuntu 20.04

**Comment by dgirardeau** [comment]
On the Windows version, I can load this file without any issue.

Isn't there another issue? Such as a read access issue? Can you try with another file type? (such as a plain ASCII file)

**Comment by roncapat** [comment]
No difference of permissions between the readable and unreadable versions

**Comment by dgirardeau** [comment]
I was not speaking of the file read permission. But about the CloudCompare executable permission. I remember the snap version - or maybe the flatpak one - has sometimes not the right to access files outside of a specific folder (but I can't remember the details).

And what about the ASCII file?

**Comment by roncapat** [comment]
Sorry, you are right. 
I checked in terminal the path to CC exec. It was under /snap/bin. I copied the file on my main disk (it was on a secondary hard drive) and CC worked well with my generated PLY files. 

So this issue can be closed.

But I have a question now: how to allow access from Snap installations to certain paths?

**Comment by dgirardeau** [comment]
I think there's already issues opened about that. And sadly I'm not the Linux expert here...

**Comment by roncapat** [comment]
Found it:

```
sudo snap connect cloudcompare:removable-media
```
