### ISSUE TITLE
Plugin load file with the wrong addToDB() function

### ISSUE THREAD

**Issue by Hooooozier** [CloudCompare/CloudCompare#1378]
**Describe the bug**
I want to make a plugin that can load files from a folder without selecting them, so I just copied the doActionLoadFile() function in mainwindow.cpp and modified it.
The original file choosing process is 

`StringList selectedFiles = QFileDialog::getOpenFileNames(this, "Open files(s)", currentPath,      fileFilters.join(s_fileFileterSeparator), &currentOpenDlgFilterm CCFileDialogOptions());`

because I don't want to choose the file, so I changed it to 

`String tempFile = String::fromStdString("E:\\000001.pts");
QStringList selectedFiles;
selectedFiles.append(tempFile);`

And at the end of the plugin's doAction() function , I use addToDB() to load it
`m_app->addToDB(selectedFiles, currentOpenDlgFilter);`

There is an error, it seems `m_app->addToDB()` needs a ccHobject as its first parameter(line 9056 in mainwindow.cpp), but the addToDB function I want to use with a QStringList as its first parameter(line 9185 in mainwindow.cpp). So what should I do to use the right function.

**Comment by WargodHernandez** [comment]
It (addToDB function for loading files) can be added to the plugin interface, I have added the same function there beforeand used it for a plugin I developed, and just never got around to purpose adding it to the official interface.
What do you think @dgirardeau?

**Comment by Hooooozier** [comment]
Did you mean that I should write another function to load files instead of putting these code in the doAction() function?
I am not familiar with C and visual studio, so I may ask some dumb questions.
Thank you a lot for your help.

**Comment by WargodHernandez** [comment]
I mean to add the addToDB function that loads files based on QStringList to the plugin interface (remove it from mainwindow class and put it in the interface) so any plugin could use it from that point. 
Whenever we notice replication especially across multiple plugins, we should attempt to share code if possible by exposing it to the plugins.

**Comment by dgirardeau** [comment]
I think that in this particular case, if you already know the name and type of the file, then you just need to use the right I/O filter (AsciiFilter::loadFile). Or FileIOFilter::LoadFromFile if you want more flexibility. These methods will return a ccHObject*, that you can simply pass to addToDB.

**Comment by Hooooozier** [comment]
I solved it, thank you!
