### ISSUE TITLE
Incorrect Angle in Point Picking

### ISSUE THREAD

**Issue by neobis001** [CloudCompare/CloudCompare#1380]
**Describe the bug**
Angle C below should be 180 - 76 - 28 = ~76, not 104. Maybe it's adding A and B?

![angle-bug](https://user-images.githubusercontent.com/10540174/103941182-580d5880-50e3-11eb-8890-65e38a38661a.png)

**Your environment**
 - CC Version (or git hash/tag): 2.11.1 (Anoia)
 - OS & Version: Windows 10

**Comment by WargodHernandez** [comment]
@neobis001 thanks for pointing out this error I've submitted a PR with a fix for this, surprising this went unnoticed for so long
