### ISSUE TITLE
InitOpenGL does not take place with translations

### ISSUE THREAD

**Issue by WargodHernandez** [CloudCompare/CloudCompare#1387]
in main.cpp we determine if we are in command line mode and if not we setup openGL which must be done before initializing ccApllication 
```C++
bool commandLine = (argc > 1) && (argv[1][0] == '-');
#endif
   
	if ( !commandLine )
	{
		ccApplication::initOpenGL();

#ifdef CC_GAMEPAD_SUPPORT
		QGamepadManager::instance(); //potential workaround to bug https://bugreports.qt.io/browse/QTBUG-61553
#endif
	}

	ccApplication app(argc, argv, commandLine);

```

Later we check if the -LANG argument was passed and if so just set command line to false

```C++
//specific commands
	int lastArgumentIndex = 1;
	QTranslator translator;
	if (commandLine)
	{
		//translation file selection
		if (QString(argv[lastArgumentIndex]).toUpper() == "-LANG")
		{
			QString langFilename = QString::fromLocal8Bit(argv[2]);

			//Load translation file
			if (translator.load(langFilename, QCoreApplication::applicationDirPath()))
			{
				qApp->installTranslator(&translator);
			}
			else
			{
				QMessageBox::warning(nullptr, QObject::tr("Translation"), QObject::tr("Failed to load language file '%1'").arg(langFilename));
			}
			commandLine = false;
			lastArgumentIndex += 2;
		}
	}
```

In this case the `ccApplication::initOpenGL();` call is skipped completely, looking into that function it seems that macOSx will possibly have issues when using translations

```C++
void ccApplicationBase::initOpenGL()
{
	//See http://doc.qt.io/qt-5/qopenglwidget.html#opengl-function-calls-headers-and-qopenglfunctions
	/** Calling QSurfaceFormat::setDefaultFormat() before constructing the QApplication instance is mandatory
		on some platforms (for example, OS X) when an OpenGL core profile context is requested. This is to
		ensure that resource sharing between contexts stays functional as all internal contexts are created
		using the correct version and profile.
	**/
```

Not sure if anyone who can test this on OS X (maybe @asmaloney ?)

**Comment by WargodHernandez** [comment]
It looks like full screen mode on windows would also be affected
```C++
// The 'AA_ShareOpenGLContexts' attribute must be defined BEFORE the creation of the Q(Gui)Application
	// DGM: this is mandatory to enable exclusive full screen for ccGLWidget (at least on Windows)
	QCoreApplication::setAttribute(Qt::AA_ShareOpenGLContexts);
```

**Comment by WargodHernandez** [comment]
Confirmed application hard crashes switching to `full screen (3D View)` if you load a translation on windows

**Comment by WargodHernandez** [comment]
@dgirardeau is there any reason to avoid calling `ccApplicationBase::initOpenGL()` or `QGamepadManager::instance()` when in command line mode?
It seems the easiest fix would be to just remove the check for command line.

**Comment by dgirardeau** [comment]
If I remember well, the aim was not initialize anything related to OpenGL, so that systems without a graphic card (server, etc.) could use the command line mode at least.

But now, with the new Qt OpengGLWidget mechanism, and the fact that Qt will refuse to run on systems with old graphic cards for instance, I'm not sure it still make sense?
