### ISSUE TITLE
ccPlugin->getName().isEmpty():"Plugin %1 has a blank name"

### ISSUE THREAD

**Issue by wangzhiqiangwq** [CloudCompare/CloudCompare#1391]
**Describe the bug**

I compiled the plugins projects, each .dll of plugins were built correctly. I placed them in plugins folder and the cloudcompare function well and the plugins displayed in menu correctly. Howerver, the second day, I went  wrong.  This function ccPlugin->getName().isEmpty() have errors:all the plugin has a blank name". I think I do nothing with this, so confused. 

![微信截图_20210130122337](https://user-images.githubusercontent.com/18256621/106347003-09279d00-62f6-11eb-9e0a-5eb92688e86b.png)

**Your environment**
 - CC Version 2.12 Alpha (or git hash/tag):
 - OS & Version: win 10 x64
 - Graphics card: 
 - Qt Version (if compiling): QT5.14.2

**Comment by dgirardeau** [comment]
I haven't tried to compile with Qt 5.14 yet. Can you maybe retry with Qt 5.12?

**Comment by wangzhiqiangwq** [comment]
I just find the problem. I changed the filed 'description' of m_data->field(QString("description") )  in ccDefaultPluginInterface.cpp by accident. So it was not in correspondence with info.json  file.
Thank you very much

**Comment by wangzhiqiangwq** [comment]
@dgirardeau I just find the problem. I changed the filed 'description' of m_data->field(QString("description") ) in ccDefaultPluginInterface.cpp by accident. So it was not in correspondence with info.json file.
Thank you very much

**Comment by dgirardeau** [comment]
Ah! Indeed, one shouldn't change ccDefaultPluginInterface.cpp or any core part of CloudCompare if he/she want to preserve the compatibility of the plugin with the official version of CloudCompare 👼
