### ISSUE TITLE
ccHObject::addChild() should recursively setDisplay if applicable

### ISSUE THREAD

**Issue by theadib** [CloudCompare/CloudCompare#1397]
**Describe the bug**
If I add a child group, then only the first element is displayed not the whole goup.

**How to reproduce**
If I load a file using qJsonRPC plugin and define parent element.
then the created group is appended to parent by ccHObject::addChild() function.
Then you would see no elements as the mesh element s are usually a child of the new group.

I made a workaound by additionally call newGroup->setDisplay_recursive(display); in 
JsonRPCPlugin::execute() when a parent is assigned.
The workaround is not needed when adding a group without parent m_app->addToDB(newGroup);
In this case in addToDB() the new group is displayed obj->setDisplay_recursive(activeWin);

**Expected behaviour**
in file ccHObject.cpp function ccHObject::addChild() 
line 370
```
  if (!child->getDisplay())
-    child->setDisplay(getDisplay());
+    child->setDisplay_recursive(getDisplay());


```
**Additional context**

**Your environment**
 - CC Version latest rom git
 - OS & Version: Linux Ubuntu 20.10
 - Graphics card: 
 - Qt Version (if compiling):

**Comment by WargodHernandez** [comment]
I'm not 100% sure but I thought this was intentional, anytime creating an object you need to set the display, it may some weird until you remember that some people use multiple display windows and there are times when you wouldn't want an object to be displayed at all right away.

**Comment by theadib** [comment]
Hello WargodHernandez ,

thanks for feedback. 
Both functions addChild() and addToDB() does a setDisplay() if the topmost object has no display set.

But the stranginess is that function 
ccHObject::addChild() does NOT do recursive setDisplay
comapred to 
addToDB does DO recursive setDisplay.

However , I am new to CC. So I can not really judge if that IS intentionally or not .
And if a change will break something else.

Regards, Adib.
--

**Comment by dgirardeau** [comment]
Well, addToDB is a method from MainWindow/AppInterface. While ccHObject::addChild() is much lower level, and is not necessarily GUI-oriented.

But I believe when calling ccHObject::addChild, any added child will automatically get the parent's display if it doesn't have any (and not necessarily the first one). But indeed, it's not a recursive call (as we would potentially overwrite some sub-children displays, or have a weird method to recursively set the display only for children that don't have any). It has always be like that 👼
