### ISSUE TITLE
Rasterize with OUTPUT_RASTER_Z option fails at assertion. 

### ISSUE THREAD

**Issue by GinaSt** [CloudCompare/CloudCompare#1398]
Hello! I am working with version 2.11.3 I am trying to rasterize a file and save it in geotiff format but it fails on this assertion. 

https://github.com/CloudCompare/CloudCompare/blob/e315347267fafca805fed0bdaea7b3b0da9ce7ed/qCC/ccCommandRaster.cpp#L258

My command is : 
cloudcompare.CloudCompare -SILENT 
               -o <new_input_path>
               -OCTREE_NORMALS 0.803
               -ORIENT PLUS_Z
               -MODEL LS
               -NORMALS_TO_DIP
               -RASTERIZE
               -GRID_STEP 0.2
               -PROJ MAX
               -SF_PROJ MAX
               -EMPTY_FILL INTERP
               -OUTPUT_RASTER_Z

It seems to me that this assertion does not allow the option outputRasterZ. Is this a known issue?

**Comment by dgirardeau** [comment]
Hum, it should... Can you test it with the 2.12.alpha version?

And if it doesn't work, can you maybe share the file with me so that I can try to reproduce the issue on my side?

**Comment by GinaSt** [comment]
I also tried with 2.12 but I had the same issue. I ended up deleting this assertion from the code before compiling.

**Comment by dgirardeau** [comment]
Does it mean you are running in debug mode by the way?

**Comment by GinaSt** [comment]
No, I am not running in debug mode.

**Comment by GinaSt** [comment]
UPDATE: You were right! I set the build more to Release and it solved the problem. 

`RUN cmake -DOPTION_USE_GDAL=1 -DPLUGIN_IO_QPDAL=1 -DCMAKE_BUILD_TYPE=Release ..`

No more deleting lines. However, it still does not make sense to me to have this assertion even in debug mode. 

Thanks for helping me out!

**Comment by dgirardeau** [comment]
Yes definitely, it's probably a deprecated assertion. I'll take a look at it.
