### ISSUE TITLE
Compilation of CloudCompare - errors when trying to generate the project

### ISSUE THREAD

**Issue by DoC-Noah** [CloudCompare/CloudCompare#1400]
Hi,
I am trying to compile CloudCompare with CMake following these steps: https://github.com/CloudCompare/CloudCompare/blob/master/BUILD.md

And I'm stuck on the 'Generating the project' step.

When I click 'Configure' in CMake GUI, I receive this output:
![image](https://user-images.githubusercontent.com/32445528/107983789-63259500-6f7b-11eb-9f6d-e8e2c9d3c65e.png)

I just recently cloned, using 
https://github.com/CloudCompare/CloudCompare.git

Does anybody have any suggestions?
Thank you!

**Comment by tmontaigu** [comment]
You most likely did not clone the submodules

https://github.com/CloudCompare/CloudCompare/blob/master/BUILD.md#prerequisites

**Comment by DoC-Noah** [comment]
You're right! Thank you!!
