### ISSUE TITLE
Failed builds

### ISSUE THREAD

**Issue by DoC-Noah** [CloudCompare/CloudCompare#1401]
I'm following the compilation instructions at https://github.com/CloudCompare/CloudCompare/blob/master/BUILD.md and when I try to build the INSTALL sub-project, it will say that 5 succeeded but 9 failed. I don't think any should fail. While it is building, there will be many unresolved external symbol errors. I attached the log of all of the output. Does anybody have any suggestions?

I'm using Windows 10, Visual Studio 2019, and Qt 5.15.2

[Output log.txt](https://github.com/CloudCompare/CloudCompare/files/5990473/Output.log.txt)

Thank you!

**Comment by dgirardeau** [comment]
Well, it seems Qt libraries are not properly linked/setup. Are you sure the CMake configuration was done properly? Can you check that all the Qt5XXX_DIR variables are pointing to a library file?

**Comment by DoC-Noah** [comment]
I think it's right! Here is the configuration I'm using:
![image](https://user-images.githubusercontent.com/32445528/108108981-30949e80-7046-11eb-82e1-33e56e76b248.png)

And here are the folders I think they are pointing on on my computer:
![image](https://user-images.githubusercontent.com/32445528/108109311-86694680-7046-11eb-845a-ef73072e725b.png)

**Comment by dgirardeau** [comment]
And when you look at the Visual Studio (failing) project properties, do you see the right Qt library files linked?

**Comment by tmontaigu** [comment]
You are using MSVC (Visual Studio Compiler) to compile the code and try to link to a Qt version that was compiled with mingw environment (gcc port on Windows) thus the linker cannot find Qt symbols. You have to install a Qt version compiled with msvc as well

**Comment by DoC-Noah** [comment]
@dgirardeau I didn't see them linked, but I also wasn't sure if I was looking correctly or how to link them.
@tmontaigu That worked!! Thank you!
