### ISSUE TITLE
Submodule packaging for releases

### ISSUE THREAD

**Issue by hobu** [CloudCompare/CloudCompare#1404]
I have begun working on a @conda-forge package for CloudCompare, but one of the challenging things is current building of some plugins like poisson require ``git submodule`` commands. 

Would it be possible to get a release tarball with all modules that are expected to work vendor'd in? Conda doesn't allow providing packages from git, all packages must come from released code with SHAs. While CloudCompare has enough history to not be problem to have a Conda Forge package, the packaging is a bit problematic if we want to build a fully-featured build.

**Comment by hobu** [comment]
In PDAL's case, we vendor modules such as the poisson code so that we know which versions were used for a specific PDAL build. This also allows us to hide the symbols if that matters. It probably doesn't for an end user application like CloudCompare, but the ability to configure a full build from a single source tree is an expectation by many packaging systems.

**Comment by dgirardeau** [comment]
What would these tarballs look like? And I guess tarballs would be for Linux then? (I'm personally not a Linux expert 👼). Do you need the equivalent for Windows? (since it's tightly linked to the compiler it's a little bit tricky).

**Comment by hobu** [comment]
> What would these tarballs look like?

A ``.tar.gz`` dump of the entire source tree plus any submodules with release numbering would be a sufficient start.

> Do you need the equivalent for Windows? (since it's tightly linked to the compiler it's a little bit tricky).

I'm not quite sure what you mean. In what way is it tightly linked to the compiler?

**Comment by dgirardeau** [comment]
Oh now I understand better. I thought you wanted a .tar.gz of the libaries (binaries).

Isn't there any simple (potentially external) solution to call 'git checkout --recurse-submodules' and create the tarball on the fly? Or do we need to do it manually for each release?

**Comment by hobu** [comment]
> Or do we need to do it manually for each release?

You should do it manually for each release and attach the tarball to the GitHub release as an artifact for download. When you tag a release with GitHub, it doesn't include any submodule stuff.

**Comment by dgirardeau** [comment]
Do you need a particular syntax to be respected? (for the tarball filename?)

**Comment by dgirardeau** [comment]
(and can it be zip, as I wouldn't be able to generate a .tar.gz easily on my side :p)

**Comment by hobu** [comment]
zip would be fine. Something like cloudcompare-x.x.x-src.zip would be perfect.

**Comment by alexmyczko** [comment]
github automatically allows .tar.gz downloads for tagged/released source projects (even for the ones it only displays .zip for)
