### ISSUE TITLE
[Load] Can't guess file format: unhandled file extension 'XXX'

### ISSUE THREAD

**Issue by 3dman-git** [CloudCompare/CloudCompare#1405]
No matter in Windows 10  or Ubuntu ( LST-20.04), compile the CloudCompare project from source code, using the default configure setting, the following error occurs:

[Load] Can't guess file format: unhandled file extension 'XXX'

My programming environment is :

1. Qt 5.14.2
2. Qt Creator 4.14
2. Visual studio 2017 (in Windows OS)
3. Cmake (the latest)
4. Cloudcompare 2.11.3 

Do we need some special settings or third party dependency library to read the (*.wrl、*.obj、*.stl、*.off) format files?

Any suggestions ?

**Comment by dgirardeau** [comment]
It's typically an issue if:
- you didn't compile the  qCoreIO plugin
- or you haven't "installed" the files (by compiling the INSTALL project, and then running CC from the 'installation' folder = CMAKE_INSTALL_PREFIX under CMake)

**Comment by 3dman-git** [comment]
@dgirardeau Thanks, I made it as your suggestions. That's great.

I compiled the INSTALL project and installed the CC to the specified folder (CMAKE_INSTALL_PREFIX ). Open the CC from specified folder and then you will find many format files.

If you want to debug the code, please copy the files 'plugins/QCORE_IO_PLUGINd.dll' to the directory of  CloudCompare.exe.

The catalog looks like this. (in windows)

.
├── CC_CORE_LIBd.dll
├── CloudCompare.exe
├── CloudCompare.ilk
├── CloudCompare.pdb
├── QCC_DB_LIBd.dll
├── QCC_IO_LIBd.dll
└── plugins
    └── QCORE_IO_PLUGINd.dll

enjoy it.

**Comment by 3dman-git** [comment]
@dgirardeau  Thanks, I made it as your suggestions. That's great.

I compiled the INSTALL project and installed the CC to the specified folder (CMAKE_INSTALL_PREFIX ). Open the CC from specified folder and then you will find many format files.

If you want to debug the code, please copy the files 'plugins/QCORE_IO_PLUGINd.dll' to the directory of CloudCompare.exe.

The catalog looks like this. (in windows)

.
├── CC_CORE_LIBd.dll
├── CloudCompare.exe
├── CloudCompare.ilk
├── CloudCompare.pdb
├── QCC_DB_LIBd.dll
├── QCC_IO_LIBd.dll
└── plugins
         └── QCORE_IO_PLUGINd.dll

enjoy it.

**Comment by dgirardeau** [comment]
Not sure about your need to move the plugin file next to the executable. At least it works without doing that in Visual Studio if you set the project settings to launch the right 'installed' executable - look at the build.md file, the "Working with Visual Studio on Windows" section. Or the "Debugging plugins" section if you are using another IDE.

**Comment by 3dman-git** [comment]
Thanks, it solved.

**Comment by 3dman-git** [comment]
The perfect answer was given in the [BUILD.md file](https://github.com/CloudCompare/CloudCompare/blob/master/BUILD.md), Thanks @dgirardeau ,you are great.
