### ISSUE TITLE
How to change the language?

### ISSUE THREAD

**Issue by x12901** [CloudCompare/CloudCompare#1406]
**Describe the bug**

 I saw that the project has CloudCompare_chs.qm. I tried to change main.cpp, but it didn't work.
```
//specific commands
	int lastArgumentIndex = 1;
	QTranslator translator;
	if (commandLine)
	{
		//translation file selection
		//if (QString(argv[lastArgumentIndex]).toUpper() == "-LANG")
		{
			QString langFilename = "CloudCompare_chs.qm";//QString::fromLocal8Bit(argv[2]);

			ccTranslationManager::get().loadTranslation(langFilename);
			commandLine = false;
			lastArgumentIndex += 2;
		}
	}
```

**Your environment**
 - OS & Version:Windows10
 - Graphics card: MX230
 - Qt Version (if compiling): 6.0.1
 - Microsoft Visual Studio Professional 2019 
 - CMake:3.18.2

**Comment by dgirardeau** [comment]
The language should be changed either via the GUI (via the 'Display > Display options' menu) or with the -LANG command line option.
