### ISSUE TITLE
ICP: RMS difference can not be changed

### ISSUE THREAD

**Issue by SchmidL** [CloudCompare/CloudCompare#1407]
When using ICP / "Fine Registration" it is not possible to change the "RMS difference" in the text field
The numbers can be marked, but nothing is changed when typing. 
**How to reproduce**

**Expected behaviour**
able to change the base, exponent of the RMS dfifference
**Your environment**
 - CC Version v2.11.10
 - OS & Version: Windows 10 Enterprise LTC, 1809

**Comment by dgirardeau** [comment]
I believe you are right 😅. I'll take a look at that ASAP.

**Comment by dgirardeau** [comment]
Ok, I fixed the bug: d22c7b0e55ec490c4c3ab9c7d5a96d9503016e23

And I've also updated the 2.12.alpha version online (for Windows).

Thanks for the feedback.
