### ISSUE TITLE
Subtracting pointclouds difference

### ISSUE THREAD

**Issue by zapaishchykova** [CloudCompare/CloudCompare#1410]
Hi! Is there a way of subtracting the difference in the point clouds after the comparison? (see the attached pic, the difference is the chair in the middle of the room, its highlighted in green(
![image](https://user-images.githubusercontent.com/17569461/109179323-0fd8f100-778a-11eb-9dbf-b6ed5c3f35cc.png)

**Comment by WargodHernandez** [comment]
You can translate the difference by selecting what you want to move and pressing "ctrl T" then entering the difference calculated previously

**Comment by zapaishchykova** [comment]
Nope, I dont want to select the region manually. Is there an automatic approach to threshold it?

**Comment by WargodHernandez** [comment]
you can use either Connected Components or filter by value 
![image](https://user-images.githubusercontent.com/7495752/109189380-d207a880-7748-11eb-8c03-19876b413c71.png)
With connected components you will need to experiment a bit to find what settings will segment how you want. with filter by value essentially you will use the SF display to highlight what you want like this 
![image](https://user-images.githubusercontent.com/7495752/109189757-375b9980-7749-11eb-9d43-814c672a9ccc.png)
which will fill in the filter by value range when you enter that tool
![image](https://user-images.githubusercontent.com/7495752/109189868-5a864900-7749-11eb-8aa8-fd4831167e79.png)
I would split so the chair becomes its own object which can then be translated by itself

**Comment by WargodHernandez** [comment]
I believe that is as automated as you can get through the stock application but you could if your comfortable with C++ automate those steps in a plugin.

**Comment by zapaishchykova** [comment]
Thanks, filtering by the range is really helpful! Although I am thinking whatever it is possible to avoid manual settings of the ranges?
![image](https://user-images.githubusercontent.com/17569461/109191288-4caae500-7796-11eb-80f9-c2cd68a9cdc2.png)

**Comment by WargodHernandez** [comment]
Other than coding something for your specific case in a plugin... 

Maybe someone would by willing to implement a version of filter by value which had set points based around the statistics of the SF so you could select say all points within 1σ or outside of 2σ. That maybe a generic enough function to add to the system.

**Comment by zapaishchykova** [comment]
Thank you!
