### ISSUE TITLE
Pasting 3D coordinates

### ISSUE THREAD

**Issue by nonbasketless** [CloudCompare/CloudCompare#1411]
Hi! Been using CC for a while and love it, thanks all who are involved :)

Here is my feature request: rapid viewing of 3D points via copy and pasting textual content. Take this point cloud for example:

```
0.047547, -0.783396, 2.964272
0.047737, -0.750514, 2.985018
0.084269, -0.751200, 2.985765
0.083718, -0.785039, 2.971308
-0.282909, -0.789537, 2.981960
-0.284190, -0.755929, 2.995557
-0.252870, -0.762543, 3.027143
-0.254049, -0.799088, 3.022431
-0.077661, -0.132547, 3.607446
-0.078201, -0.090097, 3.633071
-0.036181, -0.090330, 3.615974
-0.036944, -0.133086, 3.607036
1.895094, -1.001523, 17.378687
1.923255, -0.570525, 17.656338
2.308621, -6.347891, 28.849396
3.353315, -4.215259, 41.837437
3.144361, -4.089162, 40.445160
2.209076, -6.234653, 28.356081
-0.036078, -0.933538, 3.019748
0.002265, -0.928701, 3.006854
0.051018, -0.924803, 2.996218
0.134354, -0.914776, 2.969162
0.030528, -0.451065, 3.564727
0.080440, -0.480194, 3.549048
-0.653984, -0.002416, 3.435881
-0.515801, -0.811845, 3.102992
-0.547099, -0.798622, 3.064914
-0.346458, 0.001379, 3.537696
-0.274700, -0.000147, 3.528277
-0.360672, -0.123014, 1.383408
```

It was outputted from a console window. If I want to view this in CC, my fastest workflow is to paste it into a txt file, save the txt file, drag + drop that into CC, and then delete the file. Essentially, it's a convoluted way of copy and pasting into CC.

So, what if instead I could simply Ctrl+V with CC open, and the same thing would happen without an intermediate file. Thoughts?

**Comment by dgirardeau** [comment]
That is a fun idea actually! I made something 'simple' (pasting a block of text will actually take the same route as loading an ASCII file). However, since CTRL+V was already used, I chose CTRL+P.

See https://github.com/CloudCompare/CloudCompare/pull/1420

I'll update the online version a little bit later.

**Comment by nonbasketless** [comment]
Wonderful :D. Thank you!

**Comment by dgirardeau** [comment]
Okay I've updated the latest 2.12.alpha release online.

**Comment by nonbasketless** [comment]
<3

Do you recommend using alphas? I've always just used release builds

**Comment by dgirardeau** [comment]
Ah ah yes, alphas, when they are out for some time, are definitely very interesting and globally safe.

Of course you should report any strange behavior / bug you would encounter.

**Comment by nonbasketless** [comment]
Noted, thank you!
