### ISSUE TITLE
how to compile libe57?

### ISSUE THREAD

**Issue by HlKun** [CloudCompare/CloudCompare#1412]
is there any details about how to compile lib57?

**Comment by dgirardeau** [comment]
You may want to take a look at https://github.com/asmaloney/libE57Format (or at least ask the question on their Issue board?)

**Comment by HlKun** [comment]
what does “Checkout the submodule in plugins/core/IO/qE57IO/extern/libE57Format or download and extract the latest libE57Format release”mean?I can not understand.so is there  
some details about thissentence.

**Comment by dgirardeau** [comment]
That's a 'git' action, that consists in pulling the sources from another git repository in a specific sub-folder of this (CloudCompare) repository. In effect you just have to call 'git submodule update --init --recursive'
