### ISSUE TITLE
LibE57

### ISSUE THREAD

**Issue by HlKun** [CloudCompare/CloudCompare#1413]
![libE57](https://user-images.githubusercontent.com/46489569/109908253-e1ee3200-7cde-11eb-8d6e-2407d46090f8.PNG)

What file should I choose  for this “E57_CLANG_FORMAT_EXE”?

**Comment by dgirardeau** [comment]
You can leave these fields empty. As long as you don't get a CMake error after clicking on Generate, it generally means that the missing fields are optional.

**Comment by HlKun** [comment]
![libe57_1](https://user-images.githubusercontent.com/46489569/109956355-880d5c80-7d1e-11eb-9abc-5f41eb3c0710.PNG)

When I build cc ,there is some wrong. How to solve this?

**Comment by dgirardeau** [comment]
You'll have to check the Xerces library version/configuration that you must have set in CMake (make sure to have the right compiler / architecture / etc.)
