### ISSUE TITLE
Code for connected components

### ISSUE THREAD

**Issue by FarahSaeed** [CloudCompare/CloudCompare#1414]
Hi!

Can you share the code for connected components on point clouds. I have written Depth first search in python but it takes a lot of time.

**Comment by dgirardeau** [comment]
See https://github.com/CloudCompare/CCCoreLib/blob/master/src/AutoSegmentationTools.cpp#L18 and https://github.com/CloudCompare/CCCoreLib/blob/master/src/DgmOctree.cpp#L2815 (as we are using our Octree structure)

**Comment by nihalanurag** [comment]
Hey @RauchLukas ,  did you manage to translate connected components snippet in python? I was exploring the python script that could be used in large point cloud setups.

**Comment by RauchLukas** [comment]
> Hey [@RauchLukas](https://github.com/RauchLukas) , did you manage to translate connected components snippet in python? I was exploring the python script that could be used in large point cloud setups.


no, I haven't really been following the whole thing any further.
