### ISSUE TITLE
 Compiling PLUGIN_STANDARD_QCANUPO of CC on windows 

### ISSUE THREAD

**Issue by HlKun** [CloudCompare/CloudCompare#1423]
I install dlib with vcpkg ,then select the root path("D:\vcpkg-master\packages\dlib_x64-windows") of dlib for "DLIB_ROOT".but when I rebuild, there is a error like this "cannot open include file 'dlib matrix.h'".

How should I resolve this error？

**Comment by dgirardeau** [comment]
Ah, I believe there's a glitch in the default 'dlib' sources that needs to be fixed...

See https://github.com/CloudCompare/CloudCompare/blob/master/plugins/core/Standard/qCanupo/include/trainer.h#L85

Is it the same problem?

**Comment by HlKun** [comment]
I don not think it is the same problem,I use dlib v19.21,dlib's "matrix_utilities.h" need not be modified.
Iguess whether I selected the wrong path for "DLIB_ROOT". I am not sure what path should be selected for "DLIB_ROOT".
![e1](https://user-images.githubusercontent.com/46489569/110447944-b2cf2a80-80fb-11eb-82f7-3720760085ec.png)

**Comment by dgirardeau** [comment]
On my side I point to dlib's root: ```E:/[...]/libs/dlib-18.6```

**Comment by HlKun** [comment]
thank  you ! it works.
