### ISSUE TITLE
Debuging exe of CC and getting variable values

### ISSUE THREAD

**Issue by x12901** [CloudCompare/CloudCompare#1427]
I need to debug CC to get values of different variables to learn CC.

I build CloudCompare project in VS2019 which starts "CloudCompare.exe" from Install directory.
I want to set some break point somewhere in the code (e.g., mainwindow.cpp) to stop the debuging and to get values of some variables. How can I do it?
I read this article but it doesn't seem to work for me.
https://www.danielgm.net/cc/forum/viewtopic.php?f=9&t=4364&p=20068&hilit=breakpoint&sid=869a3d785cdde0a9abb99279f8fa261f#p20068

https://github.com/x12901/error/blob/master/Screenshot%202021-03-15%20190614.png
https://github.com/x12901/error/blob/master/Screenshot%202021-03-15%20190655.png
https://github.com/x12901/error/blob/master/Screenshot%202021-03-15%20190641.png
https://github.com/x12901/error/blob/master/Screenshot%202021-03-15%20190707.png

**Your environment**
 - CC Version (or git hash/tag):2.12
 - OS & Version:Win10
 - Graphics card: mx230
 - Qt Version (if compiling): 5.12

**Comment by dgirardeau** [comment]
Well, just make sure you compile in Debug mode (should be the default). Then update the Visual Studio "CloudCompare" project properties to start the installed debug executable (should be something like 'XXX\CloudCompare_debug\CloudCompare.exe). Eventually launch the CloudCompare project with the debugger (F5).

**Comment by x12901** [comment]
> Well, just make sure you compile in Debug mode (should be the default). Then update the Visual Studio "CloudCompare" project properties to start the installed debug executable (should be something like 'XXX\CloudCompare_debug\CloudCompare.exe). Eventually launch the CloudCompare project with the debugger (F5).

Thank you
