### ISSUE TITLE
Simpler ccHObject?

### ISSUE THREAD

**Issue by x12901** [CloudCompare/CloudCompare#1430]
**Describe the feature you would like**

I want to connect the software to my 3d camera. The data of the 3d camera is directly imported into the software for processing, which can save a lot of time.But I see that the ccHObject class that stores data is a bit complicated.Can you tell me how to solve it?
**Describe alternatives you've considered**

The current solution is to export the 3D camera data to cloud.txt, and then the software will load cloud.txt, but there will be a window to select the data format. How can I hide it or set a default value for it?

**Comment by dgirardeau** [comment]
Ok, I fear I don't fully understand your question.

But I think I understand you want to import a flow of data from a 3D camera? In this case you'll have to make a plugin for that. That's not impossible, but if you find the ccHObject structure (or is it more the ccPointCloud class maybe?) complicated, then the rest of the development work might also be challenging? Creating a point cloud and filling it with points is done in many places, so you should find a lot of examples throughout the code.

And if you want to load a file in CloudCompare without being prompted about its internal format, you would have to use a non-ambiguous format, such as E57 for instance. If your 3D camera doesn't produce such files, one option is to use the command line to convert the ASCII file to E57 (or even a bin file, which would allow CC to load it super quickly). I think you could create a script that would take the file as input argument, convert it to bin, and then open it with the graphical version of CC (you can even drag and drop files on such scripts in Windows).

**Comment by x12901** [comment]
Thanks. I will try it.
