### ISSUE TITLE
cannot open cloudcompare and no error show

### ISSUE THREAD

**Issue by yangyongyongyong** [CloudCompare/CloudCompare#1432]
**Describe the bug**

Click on the icon, spin around for a few seconds, and then nothing happens, no interface opens, no error.

**How to reproduce**

**Expected behaviour**

**Additional context**

**Your environment**
I used Aliyun's Windows Server without graphics card
 - CC Version (or git hash/tag):
 - OS & Version: win10
 - Graphics card:  i donnot know
 - Qt Version (if compiling): 

![image](https://user-images.githubusercontent.com/46118358/112709750-efba6000-8ef6-11eb-9ba5-ed93fcd63289.png)

![1](https://user-images.githubusercontent.com/46118358/112709810-6bb4a800-8ef7-11eb-8661-b7be8e4330a1.gif)

**Comment by yangyongyongyong** [comment]
2.11 version

**Comment by dgirardeau** [comment]
Have you tried with the 2.12.alpha version?

Otherwise, you can try to update your graphic card driver (whatever it is).

And last, you can also launch regedit.exe (Windows + R), then delete the folder "CloudCompare" under "Computer\HKEY_CURRENT_USER\SOFTWARE\CCCorp".

**Comment by yangyongyongyong** [comment]
> 您是否尝试过使用2.12.alpha版本？
> 
> 否则，您可以尝试更新图形卡驱动程序（无论它是什么）。
> 
> 最后，您还可以启动regedit.exe（Windows + R），然后删除“ Computer \ HKEY_CURRENT_USER \ SOFTWARE \ CCCorp”下的“ CloudCompare”文件夹。

No, or no effect before the error of the DLL lost after the installation of the DLL on the circle

**Comment by yangyongyongyong** [comment]
> 您是否尝试过使用2.12.alpha版本？
> 
> 否则，您可以尝试更新图形卡驱动程序（无论它是什么）。
> 
> 最后，您还可以启动regedit.exe（Windows + R），然后删除“ Computer \ HKEY_CURRENT_USER \ SOFTWARE \ CCCorp”下的“ CloudCompare”文件夹。

2.12 Alpha also failed to open

**Comment by dgirardeau** [comment]
Which DLL is missing on your side? (if I understood you correctly)

**Comment by yangyongyongyong** [comment]
> Which DLL is missing on your side? (if I understood you correctly)

DLL is missing  has been solved, current is cannot be open with circle circle mouth

**Comment by dgirardeau** [comment]
Yes but I want to fix this DLL issue as well ;) (and it looks easier to fix :D )

**Comment by yangyongyongyong** [comment]
i can use dodesk let you control my pc;     https://www.todesk.com/

**Comment by dgirardeau** [comment]
Hum, I fear that if you have fixed the DLL filename, it won't be easy to find it anymore. Do you remember its name? Was it something like VCRUNTIME140_1.DLL ?

**Comment by yangyongyongyong** [comment]
msvcp120.dll

**Comment by yangyongyongyong** [comment]
i use vcredist_x64.exe to resolve this dll issue. then cirle when open software.

**Comment by yangyongyongyong** [comment]
> Hum, I fear that if you have fixed the DLL filename, it won't be easy to find it anymore. Do you remember its name? Was it something like VCRUNTIME140_1.DLL ?

msvcp120.dll

i use vcredist_x64.exe to resolve this dll issue. then cirle when open software.

**Comment by dgirardeau** [comment]
Thanks, I've updated the installation script accordingly.

And for your other issue, it's always tricky when there's no error message. Can you maybe remove/rename the 'plugins' filter and see it helps?

**Comment by yangyongyongyong** [comment]
> Thanks, I've updated the installation script accordingly.
> 
> And for your other issue, it's always tricky when there's no error message. Can you maybe remove/rename the 'plugins' filter and see it helps?

Elder brother. Or you remote control computer...

**Comment by dgirardeau** [comment]
I don't really know what else to do actually. No error message, means something is wrong with Windows?!

**Comment by yangyongyongyong** [comment]
> I don't really know what else to do actually. No error message, means something is wrong with Windows?!

I strongly suspect that the server graphics card is the cause, because my local two computers have been successfully installed.

**Comment by dgirardeau** [comment]
Ah it's a server?! Sorry I missed that line 'I used Aliyun's Windows Server without graphics card' 😓

Then yes, running CC from a server is quite hard because it looks for a real graphic card and won't run if none is detected... I think there are some ways to make it work (with the right RPC / remote graphic stream protocol) but I don't know personally (I never tried it myself).

**Comment by yangyongyongyong** [comment]
> Ah it's a server?! Sorry I missed that line 'I used Aliyun's Windows Server without graphics card' 😓
> 
> Then yes, running CC from a server is quite hard because it looks for a real graphic card and won't run if none is detected... I think there may be some ways to make it work (with the right RPC / remote graphic stream protocol) but I don't know personally (I never tried it myself).

Can you provide some solutions or links to try?

**Comment by dgirardeau** [comment]
Nope. I believe a few people talked about that on the forum. Or you may want to look at 'Qt application + OpenGL + server without graphic card' 😅

**Comment by yangyongyongyong** [comment]
> Nope. I believe a few people talked about that on the forum. But I never heard about a real solution.
> 
> Or you may want to look at 'Qt application + OpenGL + server without graphic card' 😅 .
Thank you anyway.
