### ISSUE TITLE
fine registration (icp)

### ISSUE THREAD

**Issue by Boruson** [CloudCompare/CloudCompare#1434]
I am learning to use cloudcompare to register a point cloud. I would like to know the principle and code of the "fine registration (ICP)" algorithm. Where can I find it? Can you help me?

**Comment by dgirardeau** [comment]
I guess you should take a look at:
- https://www.cloudcompare.org/doc/wiki/index.php?title=Alignment_and_Registration
- https://en.wikipedia.org/wiki/Iterative_closest_point
