### ISSUE TITLE
Flatpak PDAL plugin missing LASzip

### ISSUE THREAD

**Issue by mccarthyryanc** [CloudCompare/CloudCompare#1438]
**Describe the bug**
PDAL Exception when trying to open LAZ file:

```
PDAL exception: readers.las: Can't read compressed file without LASzip or LAZperf decompression library.
```

**How to reproduce**
I installed via flatpak and tried opening [autzen_trim.laz](https://github.com/PDAL/PDAL/blob/master/test/data/laz/autzen_trim.laz) and got the error.

**Expected behaviour**
Should open LAZ files.

**Your environment**
 - CC Version (or git hash/tag): 2.11.0 (Anoia)
 - OS & Version: Pop!_OS 20.04
 - Graphics card: Nvidia Quadro M1200 (nvidia driver version 460.67)

I installed via flatpak.

**Comment by mccarthyryanc** [comment]
Tested the apt version and it worked, but it is a different version:
```bash
apt-cache policy cloudcompare
```
```
cloudcompare:
  Installed: 2.10.3-4build1
  Candidate: 2.10.3-4build1
  Version table:
 *** 2.10.3-4build1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by digital-idiot** [comment]
Unable to open `laz` files with`flatpak` packaged CloudCompare

**Comment by tmontaigu** [comment]
Late response but, the CloudCompare "team" does not provide the flatpak.

So issues about missing LAZ support in the flatpak should be posted in the [flatpak's repo](https://github.com/flathub/org.cloudcompare.CloudCompare)
