### ISSUE TITLE
compile in release mode, but the CloudCompare project needs Debug DLL, such as Qt5Guid.dll Qt5Cored.dll

### ISSUE THREAD

**Issue by jackieiou123** [CloudCompare/CloudCompare#1441]
**Describe the bug**
I compile ALL_BUILD and INSTALL successfully in release mode in VS2017, but I failed to open CloudCompare.exe in CMAKE_INSTALL_PREFIX because of  missing Qt5Guid.dll and Qt5Cored.dll. 

![image](https://user-images.githubusercontent.com/31461596/113235193-392ef480-92d5-11eb-912f-bce703f378b0.png)

I check my CloudCompare project in solution and found that Qt5Guid.lib and Qt5Cored.lib are depended.

![image](https://user-images.githubusercontent.com/31461596/113234306-9c1f8c00-92d3-11eb-8c11-7e274f01c3fc.png)

Although the problem can be fixed when I delete these two dependencies, but I was confused how to build the solution successfully becasuse I want to build the project in Qt Creator but I don't know how to remove these tow dependencies like what I have done in VS2017. 

**How to reproduce**
1. Configure and generate the solution by CMake(V3.20), MSVC2017,  with Qt 5.12.9, PCL 1.9.1
2. Open project and Build ALL_BUILD, then build INSTALL
3. Open the CloudComPare.exe in CMAKE_INSTALL_PREFIX

**Expected behaviour**

**Additional context**

**Your environment**
 - CC Version (or git hash/tag): tag 2.11.3
 - OS & Version: Windows 10 
 - Qt Version (if compiling): QT5.12.9 msvc2017

**Comment by dgirardeau** [comment]
That's weird, because everything happens in CMake, and there's no reason that it mixes debug and release libraries.

It seems that you already have Qt5Gui (release) above in the list. Therefore it's as if a plugin or something adds this dependency to Qt5Guid/Qt5Cored. Are you compiling anything additional? Or are you testing the bare project?

**Comment by jackieiou123** [comment]
> That's weird, because everything happens in CMake, and there's no reason that it mixes debug and release libraries.
> 
> It seems that you already have Qt5Gui (release) above in the list. Therefore it's as if a plugin or something adds this dependency to Qt5Guid/Qt5Cored. Are you compiling anything additional? Or are you testing the bare project?

I'm sorry for ignore telling the detail, I have compiled QPCL and QPCV plugins.

**Comment by jackieiou123** [comment]
> That's weird, because everything happens in CMake, and there's no reason that it mixes debug and release libraries.
> 
> It seems that you already have Qt5Gui (release) above in the list. Therefore it's as if a plugin or something adds this dependency to Qt5Guid/Qt5Cored. Are you compiling anything additional? Or are you testing the bare project?

The problem is still existed although I compile the bare project. (I just add QT_ROOT_PATH and nothing else change)
![image](https://user-images.githubusercontent.com/31461596/113392832-4bd62600-93c8-11eb-957b-9dea455a8f73.png)

**Comment by dgirardeau** [comment]
Yes, I was more thinking about a custom plugin (as I compile on my side with all the official plugins, and I don't see this issue.

Still, something in your CMake configuration is causing this. But it's hard to imagine what.
