### ISSUE TITLE
Memory cannot be reclaimed

### ISSUE THREAD

**Issue by winnerCR7** [CloudCompare/CloudCompare#1443]
When using a discrete graphics card, the memory occupied by the program can be recovered normally. However, if there is no discrete graphics card or we disable the discrete graphics card, load the point cloud and delete it. After repeated times, the memory occupied by the program will continue to increase. If the loaded point cloud file is relatively large, this phenomenon will be more obvious.

**How to reproduce**
Steps to reproduce the behaviour - include images if relevant:
1. Disable the discrete graphics card or run cloudcompare on a computer without a discrete graphics card
2. Click on File-Open, and load point cloud file
3. Delete the point cloud
4. Repeat step 2 and step 3 multiple times
5. View the memory occupied by cloudcompare

**Expected behaviour**
After point cloud is deleted, memory occupied by cloudcompare should return to the state before point cloud was loaded

**Additional context**
Initial memory usage：
![image](https://user-images.githubusercontent.com/42593104/113278593-b037ad80-9314-11eb-87d7-2ce4dac6e9df.png)

Load point cloud file for the first time：
![image](https://user-images.githubusercontent.com/42593104/113278798-ed9c3b00-9314-11eb-8d3d-cb9c4c07aac4.png)
delete point cloud file for the first time:
![image](https://user-images.githubusercontent.com/42593104/113278891-0c023680-9315-11eb-8066-5d4c7bdba81f.png)

Load point cloud file for the second time：
![image](https://user-images.githubusercontent.com/42593104/113279040-3bb13e80-9315-11eb-8c77-cd4e3bb137f6.png)
delete point cloud file for the second time：
![image](https://user-images.githubusercontent.com/42593104/113279184-6602fc00-9315-11eb-874f-02db84a8b566.png)

Load point cloud file for the third time：
![image](https://user-images.githubusercontent.com/42593104/113279346-8cc13280-9315-11eb-8ed9-19ed74a0e909.png)
delete point cloud file for the third time：
![image](https://user-images.githubusercontent.com/42593104/113279457-abbfc480-9315-11eb-92c8-3ca20eed864e.png)

Repeatedly load and delete point cloud, memory usage may continue to increase?

**Your environment**
 - CloudCompare v2.12 alpha
 - windows10 64bit (version 2004 / DirectX 12)
 - Graphics card: card1: Intel(R) UHD Graphics 630; card2: NVIDIA GeForce GTX 1050
 - Qt Version (if compiling): Qt5.9.8

**Comment by dgirardeau** [comment]
We added a function 'Display > Reset all VBOs'. Does it help?

**Comment by winnerCR7** [comment]
> We added a function 'Display > Reset all VBOs'. Does it help?

I tried it, but it does not seem to work

**Comment by winnerCR7** [comment]
> We added a function 'Display > Reset all VBOs'. Does it help?
I clicked 'Display > Reset all VBOs'. Console printed these: 
![image](https://user-images.githubusercontent.com/42593104/113370101-9c805b80-9395-11eb-9725-a02b17eea25e.png)

**Comment by winnerCR7** [comment]
> We added a function 'Display > Reset all VBOs'. Does it help?

I might solve my question. I did not load cloud on GPU, as follows:
![image](https://user-images.githubusercontent.com/42593104/113371391-c8e9a700-9398-11eb-9142-5738b5fbcd49.png)
loading and deleting cloud repeat many times without a discrete GPU, memory can be completely reclaimed.

**Comment by dgirardeau** [comment]
Oh, then it means that you have the bug when you don't use 'VBOs'... That's very strange. Because in this case we don't copy anything, we just let the driver transfer the data to the GPU memory and manage it itself. Which maybe means that the bug is on the driver side...

**Comment by ren2504413601** [comment]
I got a same question. When i load a obj mesh through function FileIOFilter::LoadFromFile() . I try to delete this object by delete ccHObject pointer, but the memory did not fully released.  I need to read a lot of obj file, so the memory need to released. Could you tell me how to release memory, thank you very much!

**Comment by dgirardeau** [comment]
Are you also referring to the VRAM? (the GPU memory)

**Comment by ren2504413601** [comment]
No, not refers VRAM.

**Comment by dgirardeau** [comment]
But are you using an Intel Chipset just as winnerCR7? Have you the same issue if you uncheck the 'Try to load clouds on GPU for faster display'?

(I need to know that to look at the right part of the code)

**Comment by ren2504413601** [comment]
It should not use GPU. i just use the part of  src code to read mesh, actually did not display the mainwindow interface.

**Comment by dgirardeau** [comment]
Last question (hopefully): do your meshes have textures/materials?

**Comment by ren2504413601** [comment]
yes, it contains textures. 
This is a example file.
[Tile_+1346_+1485.zip](https://github.com/CloudCompare/CloudCompare/files/9450501/Tile_%2B1346_%2B1485.zip)

**Comment by dgirardeau** [comment]
Thanks for the file.

With the latest version of CC (2.13.alpha - but it should be the same on 2.12 normally) I couldn't detect any memory leak. I used VLD on Windows.

**Comment by dgirardeau** [comment]
How fast does the memory increases?

Here is how I would write this code, but it doesn't explain the leak at least:
vector<ccBBox> getRegionBox(QStringList objfileList)
{
	vector<ccBBox> boxList;
	boxList.reserve(objfileList.size());
		
	for (int i = 0; i < objfileList.size(); ++i)
	{
		int mType = 0;
		qDebug() << "tackling mesh file :" << QFileInfo(objfileList.at(i)).absoluteFilePath();

		CCVector3d loadCoordinatesShift(0, 0, 0);
		bool loadCoordinatesTransEnabled = false;
		FileIOFilter::LoadParameters parameters;
		parameters.alwaysDisplayLoadDialog = false;
		parameters.shiftHandlingMode = ccGlobalShiftManager::NO_DIALOG;
		parameters.coordinatesShift = &loadCoordinatesShift;
		parameters.coordinatesShiftEnabled = &loadCoordinatesTransEnabled;
		parameters.parentWidget = nullptr;
		
		ccHObject inputMesh;
		if (CC_FERR_NO_ERROR == ObjFilter().loadFile(objfileList.at(i), inputMesh, parameters))
		{
			boxList.push_back(inputMesh.getBB_recursive());
		}
		else
		{
			qDebug() << "mesh load failed:" << objfileList.at(i);
		}
	}
	return boxList;
}

It just avoids to deal with the inputMesh pointer (which is by the way not the mesh, but a container under which the mesh is stored) and the vector size won't increase "geometrically".

**Comment by ren2504413601** [comment]
It depends on the size of mesh file. I watch the memory on windows.  Nearly 50MB/s the memory increases
![image](https://user-images.githubusercontent.com/46491473/187478766-5524bc07-d7b1-47b7-8927-4b8b981967c7.png)

![image](https://user-images.githubusercontent.com/46491473/187478810-67c05975-f2f3-4511-9644-dce09f9e0544.png)

![image](https://user-images.githubusercontent.com/46491473/187479192-9b6a3402-72b8-4ca0-ac74-7089c17ee9d3.png)

**Comment by dgirardeau** [comment]
Nope, that was the point of my last chunk of code (manually detaching the mesh, and deleting it explicitly). But I'm not surprised that it doesn't change the situation as ccHObject automatically does this with its children normally.

**Comment by dgirardeau** [comment]
Another explanation would be that Qt doesn't release the texture image memory right away. You could test that by commenting out 3 lines in ccMaterialSet (lines 320-322): 
https://github.com/CloudCompare/CloudCompare/blob/master/libs/qCC_db/src/ccMaterialSet.cpp#L320
