### ISSUE TITLE
About ICP registration time cost

### ISSUE THREAD

**Issue by winnerCR7** [CloudCompare/CloudCompare#1444]
I call CCCoreLib::ICPRegistrationTools::Register function in another Qt application, but registration time is longer than using ccRegistrationTools::ICP directly in cloudcompare. When both using the following parameters: 
![image](https://user-images.githubusercontent.com/42593104/113403510-59e07280-93d9-11eb-9cb8-5428a62412d9.png)
![image](https://user-images.githubusercontent.com/42593104/113403568-71b7f680-93d9-11eb-9fcf-bfda8a1925d1.png)
My own application will always be 1 second to 1.5 seconds slower than directly execute ICP. Then I found the time of [subsampleCloudRandomly] model cloud and data cloud is basically same, and each iteration time is also the same. The extra 1 second to 1.5seconds occurred in computing the initial distance between two clouds. Further, this is caused by the synchronizeOctrees function. Function synchronizeOctrees executes DgmOctree::build for model cloud and data cloud, and the extra time of my own application comes from this. I didn't figure out the reason. The following are test results of cloudcompare and my own Qt application, The first is the result of cloudcompare, and the second is the running result my own application.
![image](https://user-images.githubusercontent.com/42593104/113407805-a7aca900-93e0-11eb-8872-aaae35fc699b.png)
![image](https://user-images.githubusercontent.com/42593104/113407824-b3986b00-93e0-11eb-9163-0c9b525054f3.png)
Can you give some advice? Thanks!

**Comment by dgirardeau** [comment]
Have you activated multi-threading? I.e. compiling both CCCoreLib and your application with the CCCORELIB_USE_QT_CONCURRENT option enabled?
