### ISSUE TITLE
Possibility to open ECW files.

### ISSUE THREAD

**Issue by migvel** [CloudCompare/CloudCompare#1445]
Hello,

I have a lidar dataset in ECW format, is there any way to load it in CloudCompare?

Thanks and regards.

**Comment by dgirardeau** [comment]
Apparently GDAL supports the ECW (raster) format. Have you tried loading it as a 'raster' (you'll have to select the 'raster' filter in the File loading dialog).

**Comment by migvel** [comment]
Thanks, indeed you can add support to GDAL with ECW, by installing the proprietary driver, since it is a proprietary format.
