### ISSUE TITLE
Unicode-related Issue at FileIO::createdDateTime()

### ISSUE THREAD

**Issue by taehongjeong** [CloudCompare/CloudCompare#1446]
Dear CloudCompare maintainers,

This is about the below line (specifically, **Qt::SystemLocaleShortDate**):
https://github.com/CloudCompare/CloudCompare/blob/8b69f016884e69dbf98ab15a397a08a70149224c/libs/qCC_io/src/FileIO.cpp#L64

My system (Windows 10) locale is "Korean," which introduces Unicode letters in the DateTime string.
This produces invalid characters in the header of an output PLY file.
For example:
![image](https://user-images.githubusercontent.com/3079060/113687040-e012f680-9702-11eb-8212-01996ae38b2c.png)

I believe this may not be a problem in most cases.
However, I have noticed a certain scenario failing due to this issue.

I think it would be much safer to use `Qt::ISODate` instead.
Because the returned string is usually fed into `qPrintable`.
https://github.com/CloudCompare/CloudCompare/blob/8b69f016884e69dbf98ab15a397a08a70149224c/libs/qCC_io/src/PlyFilter.cpp#L393

Best,
Hugh

**Comment by dgirardeau** [comment]
Interesting. Have you been able to test that on your side?

Otherwise I can still update the code and generate a new release for you to test.

**Comment by taehongjeong** [comment]
Thank you for your quick response!

I've tested what I suggested above.

This is BEFORE (w/ `Qt::SystemLocaleShortDate`):
![image](https://user-images.githubusercontent.com/3079060/113834553-ea49f900-97c5-11eb-8377-5cd3c82f2ebd.png)

And this is AFTER (w/ `Qt::ISODate`):
![image](https://user-images.githubusercontent.com/3079060/113834660-0e0d3f00-97c6-11eb-8c1b-ff92fa7a9a01.png)

I made a PR: #1447

**Comment by dgirardeau** [comment]
Perfect, thanks!
