### ISSUE TITLE
CloudCompare fails to load ply with empty comment section

### ISSUE THREAD

**Issue by h4k1m0u** [CloudCompare/CloudCompare#1448]
**Describe the bug**
Ply files with an empty comment in the header cannot be read. Below is the popup that appears

![screenshot](https://user-images.githubusercontent.com/4227512/114167102-d5d54000-992e-11eb-9f7c-23068799c835.png)

There's another one appears just after that basically says: `the third-party library in charge of saving/loading the file has failed to perform the operation`

**How to reproduce**
Simply edit the ply file with a text editor and remove any text that comes after `comment` and on the same line.

**Additional context**

**Your environment**
 - CC Version (or git hash/tag): 2.11.3
 - OS & Version: Ubuntu 20.04.2 LTS
 - Graphics card: Intel
 - Qt Version (if compiling): Qt version 5.12.8

**Comment by dgirardeau** [comment]
![image](https://user-images.githubusercontent.com/2735509/114295070-371e2000-9aa3-11eb-8eda-9732be2f7d22.png)

With this file it works on my side.

**Comment by dgirardeau** [comment]
If you remove the carriage return after comment, then yes it's likely to produce a broken file.

**Comment by h4k1m0u** [comment]
The ply files I was trying to read with CloudCompare were generated on Linux Ubuntu with basic C++ file IO functions (`std:ofstream::operator<<()` and `std:ofstream::fwrite()`). If I remove the text after the comment from a ply file using `vim` on linux, I see the same problem opening the ply.

I think on linux, only a `\n` exists on the end, whereas on the screenshot you showed which has to be on windows, lines end with `\r\n`.

**Comment by dgirardeau** [comment]
Can you share a file with us?

**Comment by h4k1m0u** [comment]
Try with this file (it contains a ply with 3 points whose coordinates are in double)
[double.zip](https://github.com/CloudCompare/CloudCompare/files/6295681/double.zip)

**Comment by dgirardeau** [comment]
Okay, I looked at it more in depth, and it seems the 3rd party library we use to read PLY files expects at least one character after 'comment' (otherwise this breaks its parsing mechanism). On Windows the CR/LF pair of bytes magically avoids this.

Anyway, if you don't want any comment, you should simply avoid writing the 'comment' line. RPly will be happy with it, as the 'comment' line is optional.

**Comment by h4k1m0u** [comment]
Thanks for the reply, I don't mind having a comment line with a string after the comment keyword so it's not empty.
I guess I'll close this issue since it has been answered.
