### ISSUE TITLE
MovingLeastSquaresOMP is deprecated

### ISSUE THREAD

**Issue by tkircher** [CloudCompare/CloudCompare#1449]
Building qPCL with a recent version of PCL fails due to MovingLeastSquaresOMP not existing. Theoretically it should be aliased to MovingLeastSquares, but I had to make the change manually in plugins/core/Standard/qPCL/PclUtils/filters/MLSSmoothingUpsampling.cpp. After that everything builds fine.

**Comment by dgirardeau** [comment]
Hi. Can you maybe make a pull request, or show us the line you changed?

Thanks

**Comment by tkircher** [comment]
There's only one instance of that function in the referenced file. I just replaced pcl::MovingLeastSquaresOMP with pcl::MovingLeastSquares. Like with many things that depend on PCL though, it's not that simple in general because what the code should be depends on the version.

**Comment by dgirardeau** [comment]
Ok that's done. Thanks for the feedback.
