### ISSUE TITLE
Can I compute unsigned distance between cloud and mesh using command line?

### ISSUE THREAD

**Issue by melhashash** [CloudCompare/CloudCompare#1450]
Hello,

According to this [wiki ](https://www.cloudcompare.org/doc/wiki/index.php?title=Command_line_mode#Cloud-to-mesh_distance), I can compute the distance between cloud and mesh, can I specify some options like disabling the signed distance (similar to the GUI)?

**Comment by dgirardeau** [comment]
Nope, it doesn't seem that this option has been added to the command line mode.
