### ISSUE TITLE
fails to read ply with additional properties

### ISSUE THREAD

**Issue by christian-rauch** [CloudCompare/CloudCompare#1455]
**Describe the bug**
When using a ply that has an additional `property` for the `vertex` defined, CloudCompare will fail to load the PLY. E.g. in the example data below, the vertex coordinates and a list with additional features is defined as:
```
element vertex 10
property float x
property float y
property float z
property list uint float64 descriptor
```
and CloudCompare will fail to parse the vertex information, and thus ignoring all vertices.

**How to reproduce**
1. download and decompress [test.zip](https://github.com/CloudCompare/CloudCompare/files/6451621/test.zip), it contains example data `test.ply`
2. open the `test.ply` in CloudCompare, e.g. by drag&drop
3. see that no vertices are shown in the import dialog

**Expected behaviour**
Like MeshLab, CloudCompare should read the first 3 `vertex` properties:
```
property float x
property float y
property float z
```
as the vertices of the points.

**Additional context**
The import dialog not showing the vertices:
![Screenshot from 2021-05-10 12-21-04](https://user-images.githubusercontent.com/8226248/117651877-626f5a00-b18a-11eb-8087-caff5e5fd832.png)

**Your environment**
 - CC Version (or git hash/tag): 2.11.0
 - OS & Version: Ubuntu 20.04
 - Graphics card: irrelevant
 - Qt Version (if compiling): 5.12.7

**Comment by Hilarius86** [comment]
Using a "property list" in a vertex definitions results in it being interpreted as a mesh / face list for CloudCompare. The list can be found under "Faces" and the coordinates under "Texture Index".
Guess CC has to decide if it is valid to have lists in vertices...

**Comment by Hilarius86** [comment]
I guess you mean which `element `s can have `property list `s right? But I concur, it's a reasonable expectation to be able to load this file and get a correct assignment on X/Y and Z. I don't know of any data structure in CC to hold the 256 descriptor values per vertex apart from generating 256 scalar fields and that seems wrong to me. Maybe someone else can shine a light on this and set the expectation straight.
At the moment the only solution I see is the same as you: Hard code element names to read them in correctly, but that would break other kind of files that are readable now I guess.

**Comment by dgirardeau** [comment]
So the thing is that CloudCompare was considering any PLY element that contains a LIST as a 'face' element (as they are generally containing vertex indexes, texture coordinates, etc.).

As a workaround for now, I added the subtlety that if no LIST is composed of integer values, then the element will be considered as a 'point' element: 56e5617f60d2db776850c62484b44dbfe4aca01c

**Comment by dgirardeau** [comment]
Mind that if you select this 'LIST' property to be loaded as a scalar field for instance, I believe only the first value will be loaded.
