### ISSUE TITLE
CMake configuration failure on MacOS 11.3.1

### ISSUE THREAD

**Issue by ATL-Flaneur** [CloudCompare/CloudCompare#1456]
CMake GUI fails to generate build files on MacOS 11.3.1 (Intel) when following the [build instructions](https://github.com/CloudCompare/CloudCompare/blob/master/BUILD.md#optional-setup-for-las-using-pdal). I'm guessing that something is missing in build configuration. Error messages are:

```
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
Configuring incomplete, errors occurred!
```
I have CMake 3.19.8 installed through MacPorts compiled with the QT GUI enabled. Qt is 5.15.2.

After doing:

```
git clone --recursive https://github.com/cloudcompare/CloudCompare.git
```

I'm starting CMake with `cmake-gui &`, selecting directory `/Users/ayank/Documents/programming/CloudCompare` as the source code directory and `/Users/ayank/Documents/programming/CloudCompare/build` as the build directory. Clicking _Configure_ I'm keeping the defaults of `Unix Makefiles` and `Use default native compilers`.

I then get a pop-up window with `Error in configuration process, project files may be invalid` and the error messages listed above.

CloudCompare builds fine if I do:

```
cd build
cmake ..
make
```

However, I want to compile CloudCompare with PDAL support for reading .las/.laz files.

**Comment by ATL-Flaneur** [comment]
Typo. I put the source code in `./CloudCompare` and made `./CloudCompare/build` for building.

I also tried putting the source code in `./CloudCompare/CloudCompare` and building in `./CloudCompare/build`. Same error.

**Comment by tmontaigu** [comment]
```
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
```

This error message seems to indicate that the problem is on your end.

I don't know how you installed cmake-gui but it seems that it is not correctly installed,

**Comment by WargodHernandez** [comment]
here is [stackoverflow ](https://stackoverflow.com/questions/18615451/cmake-missing-modules-directory) discussing this issue (7 years old but still looks relevant)

**Comment by ATL-Flaneur** [comment]
Yeah, I don't think that this is particular to CloudCompare. Closing.
