### ISSUE TITLE
v2.11.3 (Anoia) will make system reboot?

### ISSUE THREAD

**Issue by whu-lyh** [CloudCompare/CloudCompare#1458]
just as the title shows the new version of cc (e.g. v2.11.3 (Anoia)) installation will make the system reboot? Is this a bug? or not. thanks.

**Comment by dgirardeau** [comment]
Well, that's not a 'bug', but more an undesired feature of the Visual Studio Redistributable package that doesn't ask the user to confirm before rebooting after being (silently) installed...

I guess we should make the installation not silent anymore.

**Comment by dgirardeau** [comment]
Ok this should be fixed now (hopefully).
