### ISSUE TITLE
compile error with CCCORELIB_USE_CGAL  on

### ISSUE THREAD

**Issue by sjq-shanghai** [CloudCompare/CloudCompare#1462]
**Describe the bug**
I complie CGAL using vcpkg, then set CCCORELIB_USE_CGAL to on in CMAKE. Config.Generate.
complie error:
..\cloudcompare\libs\qcc_db\extern\cccorelib\include\CCConst.h(36): error C2131: expression did not evaluate to a constant
.\cloudcompare\libs\qcc_db\include\ccColorTypes.h:error C2127	'ccColor::lightGreyRGB': illegal initialization of 'constexpr' entity with a non-constant expression
errors all about "constexpr"

**Your environment**
 - CC Version (or git hash/tag): 13812d5
 - Windows 10 64bits
 - VS2015 8.1 SDK
 - Qt Version 5.8

notice #1258 same problem on ubuntu. solve by compling via clang as a work round.
Should I also complie with clang on windows?

**Comment by dgirardeau** [comment]
I'm compiling with Visual Studio (2017) and I don't have this issue ... It's probably a issue with the compiler indeed.

**Comment by sjq-shanghai** [comment]
Thanks for your imformation.I compiler with vs 2019 successfully. Maybe vs 2015 is just too old.

**Comment by dgirardeau** [comment]
Well, I guess you would have to comment/remove this 'constexpr' and replace it by static const or something like that.

**Comment by yingxiongyanjin** [comment]
I also have a problem about "constexpr".And I successfully Generate it in the CMake GUI.
![image](https://github.com/CloudCompare/CloudCompare/assets/77706601/15ff6f72-aefb-4320-b1f0-9248bc7d6734)
 but  I failed run INSTALL
 error:
cloudcompare\libs\qcc_db\extern\cccorelib\include\CCConst.h(50): error C2131: 表达式的计算结果不是常数
cloudcompare\libs\qcc_db\extern\cccorelib\include\CCConst.h(50): note: 对未定义的函数或为未声明为“constexpr”的函数的调用导致了故障
\cloudcompare\libs\qcc_db\extern\cccorelib\include\CCConst.h(50): note: 请参见“std::numeric_limits<float>::quiet_NaN”的用法

My Environment is
    -  Windows 10 64bits
    - VS2015 14.0
    - Qt Version 5.9.4
    - CMake 3.26
