### ISSUE TITLE
[CCCoreLib] bad commit ref.

### ISSUE THREAD

**Issue by bartoszek** [CloudCompare/CloudCompare#1467]
`CCCoreLib` is pined to https://github.com/CloudCompare/CCCoreLib/commit/d6ef2b0dd83168011091af8581231928ad8fccf7 witch is an orphaned commit. Correct one reachable from `master` branch would be https://github.com/CloudCompare/CCCoreLib/commit/be52fc2f9981a80cd457cd914f44f17f6ebf04f1

**Comment by dgirardeau** [comment]
Yes sorry, I was in the middle of something, and I forgot to fix it! That should be ok now.
