### ISSUE TITLE
CLI - octree resampling function missing and scala fields missing when applying octree resampling

### ISSUE THREAD

**Issue by Halfknow** [CloudCompare/CloudCompare#1468]
**Describe the feature you would like**

octree resampling function missing in command line mode which is quite robust function for  resampling

**Describe alternatives you've considered**

the effect is quite similar to octree downsampling but the effect of downsampling is quite poorer than resampling. However, strangely, after the octree downsampling the scalar fields still exist but after resampling the intensity of cloud points are all missing!

**Is your feature request related to a problem? Please describe.**

when using octree resampling the scalar fields like intensity is missing. so the point clouds are shown in white

**Comment by WargodHernandez** [comment]
Resampling will create a new cloud the points of which aren't actually in the original cloud, that is why the new points do not include scalars, the software has no way to know what you would want to do with the scalars. Some scalars are categorical and wouldn't make sense to blend between.

The workaround I use is to resample and then calculate the closest point set between the original and the resampled. This will create a new cloud which is made up of the original cloud points but only having a subset of points closest to the resampled cloud.

**Comment by dgirardeau** [comment]
In the GUI version, you can also use the 'Edit > Scalar fields > interpolate from another entity' method to project the scalar values on the resampled cloud.

And mind that the standard subsampling method (-SS) would retain the scalar field.
