### ISSUE TITLE
PCL Plugin function extract sift

### ISSUE THREAD

**Issue by Halfknow** [CloudCompare/CloudCompare#1470]
**Describe the bug**

I look at the source code of the cloudcompare. There are plugin source codes named ExtractSIFT.cpp and SIFTExtractDlg.cpp existed in pcl plugin folder. But I cannot find out where this function is.

**How to reproduce**

open qpcl pugin src file folder. There are two source codes named ExtractSIFT.cpp and SIFTExtractDlg.cpp. It even used sift.png icon in .\CloudCompare\plugins\core\Standard\qPCL\PclUtils\icons

**Expected behaviour**

I wanna know where is this plugin function

**Comment by dgirardeau** [comment]
Ah, I'm not even sure this code works, since it has never been exposed. I believe this is because of the fact that the SIFT algorithm is patented and shouldn't be used without a lot o disclaimers/conditions I guess.
