### ISSUE TITLE
OPENGL

### ISSUE THREAD

**Issue by HlKun** [CloudCompare/CloudCompare#1472]
![image](https://user-images.githubusercontent.com/46489569/121139793-bb0a4380-c86b-11eb-8a38-432a3357f4c3.png)
![image](https://user-images.githubusercontent.com/46489569/121139809-bfcef780-c86b-11eb-8077-a31b55d4530c.png)
![image](https://user-images.githubusercontent.com/46489569/121139824-c3fb1500-c86b-11eb-9cdc-9df55a29951e.png)
![image](https://user-images.githubusercontent.com/46489569/121139834-c65d6f00-c86b-11eb-83d4-5c34a974f5f0.png)
 
I tried to add a polygon on the view ,but the display will be incomplete when rotating.

**Comment by dgirardeau** [comment]
Sorry, I'm not sure to understand what you are trying to achieve.

According to your function name (drawGrid), do you actually want to display a 2D grid in the background? Then you should display it on the 2D layer (background or foreground).

Otherwise I really didn't understand your question :D

**Comment by HlKun** [comment]
yes,I want to draw a polygon and add to the  GLWindow,I have drawn the polygon.
But when i perform the rotation operation，the polygon  display is incomplete.

**Comment by dgirardeau** [comment]
And what do you mean by "incomplete"? I see the same polygon but rotated (and with some perspective applied apparently).

**Comment by HlKun** [comment]
![image](https://user-images.githubusercontent.com/46489569/121142841-f9553200-c86e-11eb-8882-767ee84a76c5.png)
em.... 
After rotating,part of this polygon is invisible.
But I want see the whole polygon.

**Comment by dgirardeau** [comment]
Is it really 'invisible', or is the polygon shrinked?

Then, another remark: you should use a ccPlane entity (or similar) and add it to the view database if you want CC to manage it properly. Otherwise you'll have to manage OpenGL yourself (and especially the frustum boundaries, etc.).

**Comment by WargodHernandez** [comment]
What is displayed is exactly what should be expected if you just call the drawGrid function as it is shown where it is shown.
That is inside of the draw3D function after the modelView and projection matrices are calculated and applied. If you want the grid stationary regardless of your 3d viewpoint, you need to work in the background to be behind the 3d objects or the foreground to be in-front of them.

if this is truly a basic grid that you want and there aren't any other interaction or object management you want to do then I would follow the example of the drawTrihedron method and place before or after where it is [called ](https://github.com/CloudCompare/CloudCompare/blob/6f877def975c98ff0ee8140114639cfee4ab1280/libs/qCC_glWindow/src/ccGLWindow.cpp#L2602)
``` C++
//trihedron
drawTrihedron();
```

**Comment by HlKun** [comment]
Thank you for your reply.
It worked by modifying "getVisibleObjectsBB(ccBBox& box)"
