### ISSUE TITLE
How to use python script with np library in cloud compare? I have script ready but new to cloud compare any hint. 

### ISSUE THREAD

**Issue by vimalchawda** [CloudCompare/CloudCompare#1473]
**Describe the feature you would like**

**Describe alternatives you've considered**

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by vimalchawda** [comment]
No sir. I have script for ICP and I want to use ICP script in cloud compare. As ICP from the cloud compare are not accurate. Have you implemented any python script in cloud compare or manually controlled the point cloud environment?

**Comment by dgirardeau** [comment]
CloudCompare is a C++ program. The only way to run Python code (but with a lot of constraints) is to use https://github.com/tmontaigu/CloudCompare-PythonPlugin

**Comment by dgirardeau** [comment]
<< As ICP from the cloud compare are not accurate >> ... Well, you'll have to tell more about this ;)

**Comment by vimalchawda** [comment]
I am sorry, but python plugin is not working as it is not supported for me in my latest version. Can you please make one video and upload on YouTube, so everyone can see it ?

**Comment by WargodHernandez** [comment]
> 
> 
> I am sorry, but python plugin is not working as it is not supported for me in my latest version

What version are you talking about? you haven't supplied what version of CloudCompare you are using, whether or not you compiled, your Operating system, or which python plugin you tried. 

Please supply some details if you want some form of help.

**Comment by dgirardeau** [comment]
The 'python plugin' version is a separate project. See the build instructions here: https://tmontaigu.github.io/CloudCompare-PythonPlugin/

**Comment by dgirardeau** [comment]
If you have questions about the Python plugin, then it might be better to ask them on @tmontaigu's repository directly?

However I don't see why CloudCompare would work on your machine but not this plugin...
