### ISSUE TITLE
ccPickingHub

### ISSUE THREAD

**Issue by HlKun** [CloudCompare/CloudCompare#1474]
The ccPickingHub does not work after I modified the m_mdiArea.
![image](https://user-images.githubusercontent.com/46489569/121664098-b4810380-cad9-11eb-8da9-e79b0a141c4d.png)
![image](https://user-images.githubusercontent.com/46489569/121664117-b945b780-cad9-11eb-973c-a45f02651811.png)

**Comment by dgirardeau** [comment]
I guess it's more a Qt-related issue/question?
