### ISSUE TITLE
Fail to load PLY file

### ISSUE THREAD

**Issue by brendanlb** [CloudCompare/CloudCompare#1480]
**Describe the bug**
PLY pointcloud files can't be loaded.

**How to reproduce**
Try to open the following simple PLY file.

> ply
> format ascii 1.0
> element vertex 10
> property float x
> property float y
> property float z
> end_header
> -0.0428855 -56.3155 -58.553 
> 9.57255 -10.8189 -2.59601 
> 3.89937 -14.9626 -6.60628 
> -3.3853 -24.4685 -1.18553 
> -13.4855 -4.96936 -0.406737 
> 5.95937 -14.9185 -3.90656 
> 6.10296 -15.1341 -4.59465 
> 0.224866 0.525186 -0.482537 
> 5.50944 -13.0959 -3.75329 
> -11.7411 -9.737 7.60285 

**Expected behaviour**
File should be loaded, instead the following error messages are printed : 

> Error
> [PLY] 'Unable to open file'
![cc_error](https://user-images.githubusercontent.com/53862807/123601750-50a84b80-d7f8-11eb-9b2e-c28ba5184fe4.png)

> Error
> An error occurred while loading 'pointcloud_name': the third-party library in charge of saving/loading the file has failed to perform the operation.
![cc-error2](https://user-images.githubusercontent.com/53862807/123601747-500fb500-d7f8-11eb-90e0-790ff0e621a5.png)

**Additional context**
No problem opening the PLY file with Meshlab.

**Your environment**
 - CC 2.1.11
 - Ubuntu 20.04.2 LTS
 - Graphics card: GeForce GTX 1060 3GB

**Comment by dgirardeau** [comment]
Have you tried with the latest 2.12.alpha version? At least it works fine on my side.

**Comment by tmontaigu** [comment]
How did you install CloudCompare ? Via snap, apt-get or flatpak ?

On windows i tried both 2.11 and 2.12 and they worked.

The error just says 'unable to open', this vague message makes me think its related to CC not having the rights to read the file

**Comment by A-Leaner** [comment]
Hi, do you solve the problem?  I have the same problem now...

**Comment by tmontaigu** [comment]
You have to give more information, like your OS, how you installed CloudCompare and the path of the file

**Comment by A-Leaner** [comment]
> You have to give more information, like your OS, how you installed CloudCompare and the path of the file

Ubuntu18.04, installed by snap and both 2.11 and 2.12 have tried but not work, I open the file by file->open, and the errors are as follow:

Error in CloudCompare:
[PLY]'Unexpected end of File'
[PLY]'Error reading 'x' of 'vertex' number '1919032'
An error occurred while loading 'resule_00_mesh': the thirdparty library in charge of saving/loading the file has failed to perform the operation.

Error in MeshLab:
Error : Unespected eof

**Comment by dgirardeau** [comment]
Well, I guess this file is... corrupted?

You can try to change the 3rd line by

**Comment by supercooledith** [comment]
guys, I have the same issue!

**Comment by supercooledith** [comment]
OK, I've already solved this issue, you just need to change the element vertex number { } of the header!

**Comment by zw-92** [comment]
Perhaps it's because your file is on the mounted hard drive.
