### ISSUE TITLE
What is the reference for quadratic cloud to cloud distance computation?

### ISSUE THREAD

**Issue by melhashash** [CloudCompare/CloudCompare#1481]
For the local modeling in the [cloud-cloud distance](https://www.cloudcompare.org/doc/wiki/index.php?title=Distances_Computation), is there a reference for the quadratic (formerly known as height function) modeling?

**Comment by dgirardeau** [comment]
Do you mean an article or something like that? If yes, then no, there's no particular reference. It's an old code that relies on Conjugate Gradient to solve a 'Ax = b' problem.

See https://github.com/CloudCompare/CCCoreLib/blob/master/src/Neighbourhood.cpp#L300

**Comment by melhashash** [comment]
@dgirardeau Thanks for your reply. I searched for this function `computeQuadric`, it is never called. I think I am missing something.

**Comment by dgirardeau** [comment]
The function is called whenever you 'getQuadric' is called the first time (and especially in https://github.com/CloudCompare/CCCoreLib/blob/master/src/LocalModel.cpp#L206)

**Comment by melhashash** [comment]
So this is just fitting a quadratic surface and then measure the distance, instead of plane fitting?
I am assuming that's why the document states that this is more accurate since it is like a general case.

**Comment by dgirardeau** [comment]
Correct. That's just a little bit slower than fitting a plane (which 15 years ago made a difference :D). But now it's hardly noticeable.

**Comment by melhashash** [comment]
Thanks for your prompt response!
