### ISSUE TITLE
“CloudCompare” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by cherukumilli** [CloudCompare/CloudCompare#1484]
Downloaded the latest version of **CloudCompare** from `https://asmaloney.com/software/`

I am on a Macbook Pro 2019 with macOS Big Sur Version 11.4.

I see the following error when I try to start CloudCompare:
![Screen Shot 2021-07-09 at 1 28 59 PM](https://user-images.githubusercontent.com/5217007/125122287-d52d8080-e0ba-11eb-9322-7825a1253bf8.png)

Anyone know of a workaround? or some other way to install CloudCompare?

**Comment by tmontaigu** [comment]
Have you tried this: https://github.com/CloudCompare/CloudCompare/issues/1267#issuecomment-641468640 ?
