### ISSUE TITLE
Old third-party libraries in recent alpha releases

### ISSUE THREAD

**Issue by norbertwenzel** [CloudCompare/CloudCompare#1486]
I have just used the latest Windows binary release of ccViewer from cloudcompare.org (1.40.alpha). These releases seem to have been created at 2021-07-11 (ie. a week ago).

I recognized that while the `ccViewer.exe` has actually been built a week ago some external dependencies are very old. I know that @NeroBurner provided (in #1370) a build step that automatically downloads the latest release of the Riegl RDB library. But the bundled `rdblib.dll` is from 2018-04-05 (version 2.1.6) while the current version is 2.3.5 from 2021-06-30.

Looking at the output of the last build job ([Build #883](https://github.com/CloudCompare/CloudCompare/actions/runs/1017692021) from 2021-07-09) I could see that the script was actually working as expected; downloading and building against the most recent version. So my current assumption is that these release binaries are not built in CI but with a local configuration that has been set up some time ago.

While distributing an old version of RDB library version is not a big deal (as this can easily be fixed by replacing the DLL locally) I am not sure whether this is true for all external libraries. Looking around a bit more I've seen that the Apache Xerces C library provided in the alpha release is version 3.1 while in the previously mentioned build the version used was 3.2.3. Also `ssleay32.dll` is provided in version 1.0.1h, which is officially unsupported now.

I am not sure whether this is an issue at all, but I was merely surprised to find old libraries in a recent alpha release, especially given that there is a CI job that actually builds everything from scratch using more recent third party dependencies. But it seems that the job rebuilds the software it does not create any artifacts (at least I did not find any).
Would it be easily possible to distribute CI built artifacts as binary packages?

**Comment by dgirardeau** [comment]
Ok, I finally had the time to look at this issue. And actually, @NeroBurner script only copies the rdblib DLL to CloudCompare's folder (not ccViewer).

I fixed the script: c5f5a6df59996cd9ae144aada2746a94f132f7fb

I'll try to update ccViewer ASAP (it is not compiled by the CI indeeed, as the CI is not able to compile all the plugins).
