### ISSUE TITLE
Command line equivalent of Display -> Render to file

### ISSUE THREAD

**Issue by nonbasketless** [CloudCompare/CloudCompare#1488]
Hi there! Is there a command line way of rendering a mesh? I see there is a new RASTERIZE command, but can't find any documentation. Along GRID_STEP I can get CC to execute without error, but no image is saved.

**Comment by nonbasketless** [comment]
Ah... poking around some more, I found info in this documentation:

https://www.cloudcompare.org/doc/wiki/index.php?title=Command_line_mode

RASTERIZE isn't what I thought it was, I now understand it's basically converting a mesh to a height map.

In that case, this is a feature request: command line equivalent of Display -> Render to file. Would save much time in examining many meshes. Perhaps viewing down cardinal directions, or something like that.

**Comment by dgirardeau** [comment]
The command line mode has no 'OpenGL' context/rendering support sadly...

**Comment by nonbasketless** [comment]
Darn. Thanks for the response!

**Comment by jo-chemla** [comment]
You could go with the `RASTERIZE`CLI command, using optional tags like `-OUTPUT_RASTER_RGB` as well as project along the 6 dimensions in orthographic mode using `-VERT_DIR {0/1/2}` and `-PROJ {MIN/AVG/MAX}`. 

For example, `-VERT_DIR 0 -PROJ MIN`, `-VERT_DIR 0 -PROJ MAX`, `-VERT_DIR 1 -PROJ MIN`, `-VERT_DIR 1 -PROJ MAX`, `-VERT_DIR 2 -PROJ MIN`, `-VERT_DIR 2 -PROJ MAX`. Note that the min directions reverts the image along the X axis of the image.

**Comment by nonbasketless** [comment]
Interesting. How would I specify file to output? I might try that, if it works I'll post a complete invokation.
