### ISSUE TITLE
Apply transform to single cloud from command line

### ISSUE THREAD

**Issue by JoeWise** [CloudCompare/CloudCompare#1491]
Currently, when using the -APPLY_TRANS option on the command line, the given transformation matrix is applied to every point cloud that is currently open in the project. Instead, I would like to apply a transformation matrix to a single point cloud in a project from the command line.

For example, I have a transform that aligns B.ply to A.ply, and a separate transform that aligns C.ply to B.ply. I would like to be able to open all three files and apply transform B to B.ply and transform C to C.ply without affecting the other clouds.

Is this currently possible?

**Comment by dgirardeau** [comment]
Hi, indeed, for now commands apply to all loaded entities.

You have to do it piece by piece for now (mind that you can control the exact name of the output file if you need to write a result in a temporary file to load in a next call, etc.).

**Comment by HeadLessHUN** [comment]
Can be closed?

**Comment by dgirardeau** [comment]
Yes!
