### ISSUE TITLE
Using 'A' key to toggle a DB item doesn't update the checkbox immediately

### ISSUE THREAD

**Issue by tpwrules** [CloudCompare/CloudCompare#1497]
**Describe the bug**
When an item is selected in the DB tree and I press 'A' to toggle it, the item is toggled in the view, but the checkbox beside its name does not get updated until some other update is made to the DB tree.

**How to reproduce**
1. Load something into the DB tree
2. Select it with e.g. the mouse
3. Press the 'A' key
4. Observe that the item disappears from the 3D view but the checkbox is still checked
5. Deselect the item in the DB tree and observe that the checkbox is now unchecked

**Expected behaviour**
I expect the checkbox to be immediately updated when the key is pressed

**Additional context**
I find selecting two items, one enabled and one not, and using the 'A' key to toggle between them is an effective method of making A/B comparisons. But this is difficult when the DB tree does not accurately show which item is actually visible.

**Your environment**
 - CC Version (or git hash/tag): 2.12alpha (71f7fb2)
 - OS & Version: Ubuntu 18.04
 - Graphics card: 
 - Qt Version (if compiling): 5.15.2

**Comment by dgirardeau** [comment]
Ok that's fixed now: 0bab08772971ffebb05c5deaa12dac718a648f45
