### ISSUE TITLE
Installation of CloudCompare on Windows 10 Pro

### ISSUE THREAD

**Issue by mirjanavugrinski** [CloudCompare/CloudCompare#1498]
Hi!
I'm trying to install CloudCompare on Windows 10 Pro and when I install it and open the icon for CloudCompare on my Desktop, an error is displayed and it's impossible to open CloudCompare. Can you  tell me how can I properly install the software?
Thank you!

**Describe the bug**

**How to reproduce**

**Expected behaviour**

**Additional context**

**Your environment**
 - CC Version (or git hash/tag):
 - OS & Version:
 - Graphics card: 
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
Well, this looks a lot like an issue with your graphic card? (do you have an old Intel chipset maybe? If not, can you try to update the graphic card driver?)

**Comment by mirjanavugrinski** [comment]
I didn't solve the problem. When I install CloudCompare and open it there is an error: "The code execution cannot proceed because MSVCR120.dill was not found." The problem isn't in installing, I think that the issue is in running the program. Please advise!
