### ISSUE TITLE
Installation of  CloudCompare cmakeLists.txt file missing? 

### ISSUE THREAD

**Issue by Claireera** [CloudCompare/CloudCompare#1499]
Dear all, 

I'm trying to install CloudCompare from cmake on a windows 10 computer. I downloaded the CloudCompare-master.zip today. However it seems that it is missing a cmakelist.txt file to finalize the configuration.   Do you have any idea how I can deal with this issue? 

**Describe the bug**
During the configure phase the following error appeared 

"vCMake Error at libs/qCC_db/CMakeLists.txt:8 (add_subdirectory):
  The source directory

    C:/Users/XXXX/CloudCompare-master/libs/qCC_db/extern/CCCoreLib

  does not contain a CMakeLists.txt file." 

**Your environment**
 - CC Version (or git hash/tag): downloaded from git : https://github.com/cloudcompare/cloudcompare/ the 25/08/2021
 - OS & Version: Wind10
 - Qt Version (if compiling): Qt\5.12.11\msvc2017_64
CMake 3.20.2

Thanks a lot for your help 

Claire

**Comment by cai-xiaoming** [comment]
Today when i try to compile this source code(v2.12.4) on window32 platform by using cmake,i met this problem.And by changing the source code(v2.10.3),this problem is disapped.Is it the mistake of the way I use compiling?

**Comment by dgirardeau** [comment]
Recent versions of CC are 64bits only. 32 bits architectures are not supported anymore.
