### ISSUE TITLE
Background subtraction of multiple frame 

### ISSUE THREAD

**Issue by vimalchawda** [CloudCompare/CloudCompare#1501]
I have merged all the frames,
![1](https://user-images.githubusercontent.com/45018639/131116654-771c033b-6e31-44bf-8a26-0e405dca75d2.JPG)
 but the car and other object are in motion, so I am getting very bad view.  One can see the curve , how can I remove it and just I need static objects first? 
 
 2- Secondly, I want to do features extraction from the static point cloud after removing the dynamic points?

**Comment by dgirardeau** [comment]
For 'user' questions, the forum would be a better place (https://www.cloudcompare.org/forum/).
