### ISSUE TITLE
Crash When computing distance cloud-mesh with cloud from xyz file

### ISSUE THREAD

**Issue by prascle** [CloudCompare/CloudCompare#1502]
Hi,
I'm observing a bug that appeared with the recent CloudCompare commits. 
The bug can be reproduced with the latest 2.12 alpha windows binary (08/26/2021) .

- Load an xyz file, for instance [this one](https://www.simulation.openfields.fr/binaries/sampleData/dataSample2_3.0_0_0.1.xyz).
- Create a sphere of radius 2.0 centered in (3.0, 3.0,  8.8) default precision.
- Select the cloud and the sphere, compute cloud/mesh distance, default options : **crash**

The bug seems related to the CCCoreLib commit 32b2ed03d "Distances computation tools improvement (#68)"
(tests on Windows and Linux with and without this commit)

Regards,
Paul

**Comment by dgirardeau** [comment]
Hi Paul, good catch!

I fixed it (hopefully): https://github.com/CloudCompare/CCCoreLib/commit/6424a0bf90baceb512186ee028015c414ba2650f
