### ISSUE TITLE
Support for point cloud compression

### ISSUE THREAD

**Issue by copyme** [CloudCompare/CloudCompare#1508]
You may have heard of [Draco](https://github.com/google/draco) project, which is an implementation of point cloud and mesh data compression algorithms. It would be nice to add support for it in CloudCompare.

**Comment by dgirardeau** [comment]
Interesting. So it is basically a new file format (.drc). If there are not too many dependencies to build the Draco library, it could be easy to incorporate.

**Comment by copyme** [comment]
@dgirardeau compiling draco is straightforward, and I do not see any big obstacle to incorporate it into CloudCompare. With the default parameters a point cloud of around 250 MB can be reduced to just around 40 MB. The gain is obvious. Also, draco is extremely fast.

**Comment by dgirardeau** [comment]
And I've just merged the PR. The new I/O plugin should support point clouds (with normals, RGB and up to one scalar field) as well as plain meshes (just triangles) both for import and export.
