### ISSUE TITLE
Fails to build on Archlinux

### ISSUE THREAD

**Issue by DRM-Free** [CloudCompare/CloudCompare#1509]
**Describe the bug**
Can't build on archlinux. This will crash while building the vxl library.

```
[ 31%] Building C object v3p/netlib/CMakeFiles/v3p_netlib.dir/sparse/spOutput.c.o
[ 31%] Linking CXX shared library ../../lib/libvgl.so
[ 31%] Linking CXX shared library ../../lib/libv3p_netlib.so
[ 31%] Built target v3p_netlib
[ 31%] Built target vgl
make: *** [Makefile:146 : all] Erreur 2
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…
erreur lors de la construction : vxl
```

In addition, my package manager indicates that vxl is obsolete.
```
aur/vxl 2.0.2-2 (+6 0.19) (Obsolète : 2021-08-14)
```

**How to reproduce**
```shell
$ yay cloudcompare
2 aur/cloudcompare 2.11.3-4 (+9 0.00) 
    A 3D point cloud (and triangular mesh) processing software
1 aur/cloudcompare-git 2.10.2.r977.g6cdbeb53-1 (+10 0.00) 
    A 3D point cloud (and triangular mesh) processing software
==> Paquets à installer (ex. 1 2 3, 1-3 or ^4)
==> 

```
Then select either git or non-git version.

**Expected behaviour**
Successful build

**Your environment**
```
$ cat /etc/*-release
LSB_VERSION=1.4
DISTRIB_ID=EndeavourOS
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="EndeavourOS Linux"
DISTRIB_CODENAME=rolling
NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID=endeavouros
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://endeavouros.com/wiki/"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://github.com/endeavouros-team"
LOGO=endeavouros

```

**Comment by tmontaigu** [comment]
It looks like its the vxl package that fails to build, not CloudCompare.

The PKGBUILD on AUR says that it list vxl as a dependency, but I don't see why, the only plugin that uses vxl is 
qGMMReg  but it does not seem to be built

**Comment by FederAndInk** [comment]
qGMMReg has been discontinued, hasn't it? IIRC

**Comment by tmontaigu** [comment]
Yes it has been discontinued since c3196177b1e7c8caa94ef3f97a4599931e4b7df4

**Comment by FederAndInk** [comment]
I see that it's still mentioned in https://github.com/CloudCompare/CloudCompare/blob/master/BUILD.md, maybe that should be removed or write that it's been discontinued?

**Comment by tmontaigu** [comment]
I would say that it should be removed since the plugin's code is not part of the soure code since 2018.
But I see that the qKinect plugin is listed as being discontinued 🤔

**Comment by tmontaigu** [comment]
Closing as its not purely CloudCompare that can't be built and the AUR package should be fixed https://github.com/bartoszek/AUR-cloudcompare/issues/9
