### ISSUE TITLE
Automatically name scalar fields when importing from csv

### ISSUE THREAD

**Issue by jlinBE** [CloudCompare/CloudCompare#1517]
**Describe the feature you would like**
Right now when importing data from csv, scalar fields are named 'scalar field', 'scalar field #2', 'scalar field #3', etc, and I have to rename them manually.  Would it be possible to automatically name them according to the column headers?

**Comment by dgirardeau** [comment]
You simply have to 'skip' the first line (with the 'Skip lines' field) and then check the 'extract field names from first line'.
