### ISSUE TITLE
Random resampling results in unexpected behaviour

### ISSUE THREAD

**Issue by rcastlebury** [CloudCompare/CloudCompare#1524]
Performing a random resampling results in randomly kept points rather than randomly removed points 

1. Open point cloud
2. Use function located at Edit>Subsampling, choosing random as method

**Expected behaviour**

Subsampling randomly should remove points at random rather than keep points at random (can there be a toggle to choose?).

The expected behaviour is to achieve uniform distance between samples, that high density areas are randomly sampled more often, thus thinning those areas out, and achieving greater uniformity between sample distances.
Thanks for excellent software!

**Additional context**

**Your environment**

 - CC Version (or git hash/tag): v2.12 alpha 64-bit
 - OS & Version: Windows 10 LTSC
 - Graphics card: Nvidia
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
Well, the 'random' subsampling is really random. This means that a given number of points is randomly chosen. The aim is for it to be super fast.

You have to use the 'spatial' option if you want to subsample based on the distance.
