### ISSUE TITLE
CloudCompare on M1 MacBooks

### ISSUE THREAD

**Issue by TheBiggestNumber** [CloudCompare/CloudCompare#1528]
Hi. Thank you for the great tool. Is the Mac version of CloudCompare fully compatible with the new M1 chips?

**Comment by duhlmanator** [comment]
Hi, I've been running the cloud compare 2.12 
-MacBook Pro M1 Max 64GB Ram (basically most powerful model)

Cloud Compare works, however seems to freeze quite frequently considering the supposed power of the new machine I'm on (for comparison Metashape Pro works 10-15x faster on this new machine than my old Mac). 

I'm wondering if there is anything I can do to help it not freeze.

**Comment by tmontaigu** [comment]
Does it freeze when using any functionnalities or does it seems like some functionnalities trigger the freeze more often ?

Is it the 3D display (like moving, rotating zooming objects) that freezes or computations also creates those freeze ?

**Comment by duhlmanator** [comment]
Hi tmontaigu, it has no problem handling the display of large (up to 130 million) point clouds. 

Its been continually getting "not responding" (spinning wheel) when doing:

1) Fine registration
2) Computing cloud / cloud distance

I'm not sure if the CC is just not suited that well for Mac or if I'm missing something I could do to make it smoother (aside from desampling the point cloud; I typically need the full point cloud at least for the point picking step of registration)

I'd be grateful for any tips!

**Comment by tmontaigu** [comment]
Maybe its just that these computations are written in a way that they don't let the UI 'breathe' or refresh itself making it appear as not responding  as I don't see any reason why CC would perform poorly on M1 or perform worse on M1 than on x86_64.

One quick way to be sure of that would be test on a non M1 mac or windows or linux

**Comment by duhlmanator** [comment]
Hi tmontaigu,

After a long pause on my project, I'm back at it. Was frustrated by constant and unavoidable "not responding" while computing c2c distance on my Macbook Pro M1 Max with 64 GB ram. I just found the really obvious solution. You have to limit the thread count to less than the max # of available threads. In my case there are 10, so I use 5 and it goes very fast, no freezing so far. Thanks!

**Comment by tmontaigu** [comment]
Cool 🎉 

I think that would tend to confirm my hypothesis that the c2c distance does not let the ui thread do its work, i'll try to see if its actually that and if something can be done about it.

Have you tried allowing 9/10 threads just to see ?
