### ISSUE TITLE
How to install a plugin on Ubuntu

### ISSUE THREAD

**Issue by emmbertelen** [CloudCompare/CloudCompare#1530]
Tried to do the installation with the qE57IO plugin on Ubuntu 18.04  in  CloudCompare/build dir  with:

`$cmake --install . -DMY_OPTION=ON  -DPLUGIN_IO_QE57=ON` and got:
```
Unknown argument -DPLUGIN_IO_QE57=ON
Usage: cmake --install <dir> [options]
...
```

I am quite a beginner with cmake installation, can you please help me with how could I install with the plugin named above?

**Comment by tmontaigu** [comment]
`-DPLUGIN_IO_QE57=ON` is only for the first step (generation) of cmake, the activated plugins will install themselves
