### ISSUE TITLE
RGB segmentation plugin crashes CC

### ISSUE THREAD

**Issue by TokyoWarfare** [CloudCompare/CloudCompare#1531]
**Describe the bug**
RGB segmentation plugin will crash CC if click on BKG

**How to reproduce**
https://youtu.be/80Is3GjSIXg

pleaseo also add small window that show the color that has been picked, like in the color picker.
please also save the previously selected colors in case you whant to repeat operation but with wider tolerance.
please also add color saving option like in picker for recurrent RGB cleaning processes like sky blue  etc,

**Comment by dgirardeau** [comment]
Ok this is now fixed. And I also added some of the improvements you suggested (but the last one, as it's much more complicated when not using the system RGB edition dialog).

**Comment by TokyoWarfare** [comment]
I confirm it's working. Thank you so much for this EXTREME quick fix and feature expansion, theese small tweaks have much improved the use of this (great) plugin.  I use for fine tune segmentation once run CANUPO, mainly to remove artifacts on RGB coloring, typical on treese that get white/blue on borders,  after RTB to scalar field filtering, usually.
