### ISSUE TITLE
Apply transformation bug

### ISSUE THREAD

**Issue by cainhaaa** [CloudCompare/CloudCompare#1533]
**Describe the bug**
when using the apply transformation to rotate, the rotation doesn't correspond to the rotation angle entered. And the same angle will give different rotations each time is used. In the image, the same rotation was applied to several scans. After the rotation they should be aligned because the rotation was equal, but they are not aligne ...

**Your environment**
 - CC Version (or git hash/tag): Firts it was in version 2.12 for MAC, but also occurred in 2.12 windows and in 2.11.1
 - OS & Version:Catalina 10.15.3
 - Graphics card: Intel Iris Plus Graphics 655 1536 MB
 - Qt Version (if compiling): 
<!--- Include any other relevant details about your environment --
<img width="466" alt="Screenshot 2021-11-03 at 23 02 54" src="https://user-images.githubusercontent.com/93686444/140230711-b9a55ffa-8235-4e97-ab66-91d0428f03f3.png">
<img width="968" alt="Screenshot 2021-11-03 at 22 58 56" src="https://user-images.githubusercontent.com/93686444/140230723-1c2b5553-8b48-4733-8354-d1af49345578.png">
>

**Comment by dgirardeau** [comment]
I don't see any image.

But mind that the rotation is (by default) performed about the origin (0, 0, 0). Which means that depending on where your objet is, the rotation may not be the same.
