### ISSUE TITLE
Stereo Support AMD GPUs

### ISSUE THREAD

**Issue by fsadough** [CloudCompare/CloudCompare#1534]
Any documentation available on supported AMD/ATI GPUs?

**Comment by dgirardeau** [comment]
I don't know of any list.

But since CloudCompare relies on OpenGL for this kind of things (there's no manufacturer specific code), I guess you just need to check if the driver supports "Quad-Buffer Stereo".

**Comment by dgirardeau** [comment]
And I have tested it successfully on a ATI Radeon WX8200 by the way.

**Comment by fsadough** [comment]
Thank you. Try to go Full Screen and exit => Do you get black screen?

**Comment by fsadough** [comment]
![CloudCompare_StereoMode](https://user-images.githubusercontent.com/66113850/140301791-6b578187-8296-4b29-a425-b18007baad38.jpg)
The Stereo options are kinda confusing

**Comment by dgirardeau** [comment]
Which version are you using?

Fore reference, here is how the latest version looks like:
![image](https://user-images.githubusercontent.com/2735509/140302085-c46a9b69-6d7b-434c-ac71-6424d7302d93.png)

And on which kind of device/screen are you trying to display the result?

**Comment by fsadough** [comment]
Uhm, I was using CloudCompareStereo_v2.10.2_setup_x64.exe, I see there is new Beta version v2.12. Which version is your screenshot from?

**Comment by dgirardeau** [comment]
Version 2.12 (but the official stable release 2.11 should have the same I believe).

**Comment by fsadough** [comment]
I will try 2.11.3 in Full Screen mode. Thank you

**Comment by dgirardeau** [comment]
Oh, you can try the latest 2.12.beta version right away, that will make things easier to 'debug'.

**Comment by fsadough** [comment]
> Oh, you can try the latest 2.12.beta version right away, that will make things easier to 'debug'.

Sure, I will

**Comment by fsadough** [comment]
Black screen when exiting Full Screen. Will investigate on AMD side.
