### ISSUE TITLE
CloudCompare Disappearance of Viewing ToolBar in the interface 

### ISSUE THREAD

**Issue by Djack63** [CloudCompare/CloudCompare#1535]
Hi,

CloudCompare Interface problem.

The Viewing Toolbar in the left of interface has disappeared. I try to find it but impossible. Is it a bug? Maybe it's already happen to others Users ? Let's me know. 

This thing comes when I open a .ply file from EveryPoint app.

Thanks for your attention

Best regartds.

Jacques

**Comment by dgirardeau** [comment]
Hum, that's strange, especially if it's a direct consequence of loading a file 😅 

Anyway, just call 'Display > Reset all GUI element positions' and restart CC. It should put the toolbar back at his original position.

**Comment by Djack63** [comment]
Not a bug!  I finally find the solution. Press Right-Click on an empty toolbar and a list appear:  Viewing Tool and Filters GL were disabled. How they were unchecked? I don't know.. Sorry to have bothered you with this false problem.

**Comment by dgirardeau** [comment]
Can you share a file with us maybe?

**Comment by Djack63** [comment]
Vous êtes donc le créateur de ce superbe soft sur lequel je débute. Chapeau bas! 

Oui je  vous envoie le fichier en question en fichier-joint. C'était vraiment un petit test. D'habitude, j'utilise Sitescape et je n'ai jamais eu pas eu ce problème? J'ai re-essayé et aucun problème. Certainement une touche appuyée par inadvertance. Bizzare.


 Sinon j'avais une question. Prevoyez-vous d'ajouter du feather pour adoucir les bords de l'outil de segmentation?  Je sais bien que ce n'est pas un outil de compositing (quoique) mais pour des scans captés à des heure différentes cela aurait une certaine utilité.

Cordialement,

Jacques 



----- Mail original -----
De: "Daniel Girardeau-Montaut" ***@***.***>
À: "CloudCompare/CloudCompare" ***@***.***>
Cc: "Djack63" ***@***.***>, "Author" ***@***.***>
Envoyé: Vendredi 5 Novembre 2021 16:07:36
Objet: Re: [CloudCompare/CloudCompare] CloudCompare Disappearance of Viewing ToolBar in the interface  (Issue #1535)





Can you share a file with us maybe? 

— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or unsubscribe . 
Triage notifications on the go with GitHub Mobile for iOS or Android .
