### ISSUE TITLE
CloudCompare on RaspberryPi with Raspbian (Buster)

### ISSUE THREAD

**Issue by spatial-mk** [CloudCompare/CloudCompare#1536]
Dear CloudCompare Community,

I am trying to compile and run CloudCompare on a RaspberryPi 4B with Raspbian (Buster).
When running cmake/make with the usual steps according to the BUILD.md I do get an error for "QOpenGLFunctions_2_1" in the ccFrameBufferObject.cpp.
Installing CloudCompare via snap does not work on the armhf architecture.

Is there any way or possibility to run CloudCompare on a RaspberryPi?

Best regards,
Matthias

**Comment by dgirardeau** [comment]
Is there actually any OpenGL support on a RaspberryPi?

**Comment by spatial-mk** [comment]
Yes, it should support OpenGL ES 3.0 and OpenGL 2.1
(see https://www.raspberrypi.com/news/vc4-and-v3d-opengl-drivers-for-raspberry-pi-an-update/)

**Comment by dgirardeau** [comment]
And which version of Qt are you compiling with? (because QOpenGLFunctions_2_1 is part of Qt 5 normally - even if Qt was not supported). Or at least are you compiling with a version of Qt that supports OpenGL? (and not Angle)

**Comment by spatial-mk** [comment]
Qt5 using `cmake -DCMAKE_PREFIX_PATH=/lib/qt5/bin ..` within the build folder
I installed all the base dependencies as in a Debian since Raspbian is a Debian based OS.

**Comment by dgirardeau** [comment]
And what's the error with QOpenGLFunctions_2_1 then? Can it find the header file at least? Or is it something else?

**Comment by spatial-mk** [comment]
`[  1%] Built target shapelib
[ 10%] Built target CCCoreLib
[ 10%] Automatic MOC for target CC_FBO_LIB
[ 10%] Built target CC_FBO_LIB_autogen
[ 11%] Building CXX object libs/CCFbo/CMakeFiles/CC_FBO_LIB.dir/src/ccFrameBufferObject.cpp.o
In Datei, eingebunden von /home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:18:
/home/pi/CloudCompare/libs/CCFbo/include/ccFrameBufferObject.h:105:2: Fehler: »QOpenGLFunctions_2_1« bezeichnet keinen Typ
  105 |  QOpenGLFunctions_2_1 m_glFunc;
      |  ^~~~~~~~~~~~~~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/include/ccFrameBufferObject.h:106:2: Fehler: »QOpenGLExtension_ARB_framebuffer_object« bezeichnet keinen Typ; meinten Sie »QOpenGLExtension_ANGLE_framebuffer_blit«?
  106 |  QOpenGLExtension_ARB_framebuffer_object m_glExtFunc;
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |  QOpenGLExtension_ANGLE_framebuffer_blit
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp: In Elementfunktion »void ccFrameBufferObject::reset()«:
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:51:3: Fehler: »m_glExtFunc« wurde in diesem Gültigkeitsbereich nicht definiert
   51 |   m_glExtFunc.glDeleteFramebuffers(1, &m_fboId);
      |   ^~~~~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp: In Elementfunktion »bool ccFrameBufferObject::init(unsigned int, unsigned int)«:
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:62:8: Fehler: »m_glFunc« wurde in diesem Gültigkeitsbereich nicht definiert
   62 |   if (!m_glFunc.initializeOpenGLFunctions())
      |        ^~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:67:8: Fehler: »m_glExtFunc« wurde in diesem Gültigkeitsbereich nicht definiert
   67 |   if (!m_glExtFunc.initializeOpenGLFunctions())
      |        ^~~~~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:82:2: Fehler: »m_glExtFunc« wurde in diesem Gültigkeitsbereich nicht definiert
   82 |  m_glExtFunc.glGenFramebuffers(1, &m_fboId);
      |  ^~~~~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp: In Elementfunktion »bool ccFrameBufferObject::start()«:
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:93:3: Fehler: »m_glExtFunc« wurde in diesem Gültigkeitsbereich nicht definiert
   93 |   m_glExtFunc.glBindFramebuffer(GL_FRAMEBUFFER_EXT, m_fboId);
      |   ^~~~~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:93:33: Fehler: »GL_FRAMEBUFFER_EXT« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »GL_DRAW_BUFFER_EXT«?
   93 |   m_glExtFunc.glBindFramebuffer(GL_FRAMEBUFFER_EXT, m_fboId);
      |                                 ^~~~~~~~~~~~~~~~~~
      |                                 GL_DRAW_BUFFER_EXT
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp: In Elementfunktion »void ccFrameBufferObject::stop()«:
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:106:3: Fehler: »m_glExtFunc« wurde in diesem Gültigkeitsbereich nicht definiert
  106 |   m_glExtFunc.glBindFramebuffer(GL_FRAMEBUFFER_EXT, 0);
      |   ^~~~~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:106:33: Fehler: »GL_FRAMEBUFFER_EXT« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »GL_DRAW_BUFFER_EXT«?
  106 |   m_glExtFunc.glBindFramebuffer(GL_FRAMEBUFFER_EXT, 0);
      |                                 ^~~~~~~~~~~~~~~~~~
      |                                 GL_DRAW_BUFFER_EXT
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp: In Elementfunktion »void ccFrameBufferObject::deleteColorTexture()«:
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:112:40: Fehler: »m_glFunc« wurde in diesem Gültigkeitsbereich nicht definiert
  112 |  if (m_isValid && m_ownColorTexture && m_glFunc.glIsTexture(m_colorTexture))
      |                                        ^~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp: In Elementfunktion »void ccFrameBufferObject::deleteDepthTexture()«:
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:122:40: Fehler: »m_glFunc« wurde in diesem Gültigkeitsbereich nicht definiert
  122 |  if (m_isValid && m_ownDepthTexture && m_glFunc.glIsTexture(m_depthTexture))
      |                                        ^~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp: In Elementfunktion »bool ccFrameBufferObject::initColor(GLint, GLenum, GLenum, GLint, GLenum)«:
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:143:2: Fehler: »m_glFunc« wurde in diesem Gültigkeitsbereich nicht definiert
  143 |  m_glFunc.glPushAttrib(GL_ENABLE_BIT);
      |  ^~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:143:24: Fehler: »GL_ENABLE_BIT« wurde in diesem Gültigkeitsbereich nicht definiert
  143 |  m_glFunc.glPushAttrib(GL_ENABLE_BIT);
      |                        ^~~~~~~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp: In Elementfunktion »bool ccFrameBufferObject::attachColor(GLuint, bool, GLenum)«:
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:179:7: Fehler: »m_glFunc« wurde in diesem Gültigkeitsbereich nicht definiert
  179 |  if (!m_glFunc.glIsTexture(texID))
      |       ^~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:191:2: Fehler: »m_glExtFunc« wurde in diesem Gültigkeitsbereich nicht definiert
  191 |  m_glExtFunc.glFramebufferTexture2D(GL_FRAMEBUFFER_EXT, GL_COLOR_ATTACHMENT0_EXT, target, texID, 0);
      |  ^~~~~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:191:37: Fehler: »GL_FRAMEBUFFER_EXT« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »GL_DRAW_BUFFER_EXT«?
  191 |  m_glExtFunc.glFramebufferTexture2D(GL_FRAMEBUFFER_EXT, GL_COLOR_ATTACHMENT0_EXT, target, texID, 0);
      |                                     ^~~~~~~~~~~~~~~~~~
      |                                     GL_DRAW_BUFFER_EXT
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:199:7: Fehler: »GL_FRAMEBUFFER_COMPLETE_EXT« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »GL_FRAMEBUFFER_COMPLETE«?
  199 |  case GL_FRAMEBUFFER_COMPLETE_EXT:
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       GL_FRAMEBUFFER_COMPLETE
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp: In Elementfunktion »bool ccFrameBufferObject::initDepth(GLint, GLenum, GLint, GLenum)«:
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:233:2: Fehler: »m_glFunc« wurde in diesem Gültigkeitsbereich nicht definiert
  233 |  m_glFunc.glPushAttrib(GL_ENABLE_BIT);
      |  ^~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:233:24: Fehler: »GL_ENABLE_BIT« wurde in diesem Gültigkeitsbereich nicht definiert
  233 |  m_glFunc.glPushAttrib(GL_ENABLE_BIT);
      |                        ^~~~~~~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:241:35: Fehler: »GL_DEPTH_TEXTURE_MODE« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »GL_DEPTH_STENCIL_TEXTURE_MODE«?
  241 |  m_glFunc.glTexParameteri(target, GL_DEPTH_TEXTURE_MODE, GL_LUMINANCE);
      |                                   ^~~~~~~~~~~~~~~~~~~~~
      |                                   GL_DEPTH_STENCIL_TEXTURE_MODE
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp: In Elementfunktion »bool ccFrameBufferObject::attachDepth(GLuint, bool, GLenum)«:
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:271:7: Fehler: »m_glFunc« wurde in diesem Gültigkeitsbereich nicht definiert
  271 |  if (!m_glFunc.glIsTexture(texID))
      |       ^~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:283:2: Fehler: »m_glExtFunc« wurde in diesem Gültigkeitsbereich nicht definiert
  283 |  m_glExtFunc.glFramebufferTexture2D(GL_FRAMEBUFFER_EXT, GL_DEPTH_ATTACHMENT_EXT, target, texID, 0);
      |  ^~~~~~~~~~~
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:283:37: Fehler: »GL_FRAMEBUFFER_EXT« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »GL_DRAW_BUFFER_EXT«?
  283 |  m_glExtFunc.glFramebufferTexture2D(GL_FRAMEBUFFER_EXT, GL_DEPTH_ATTACHMENT_EXT, target, texID, 0);
      |                                     ^~~~~~~~~~~~~~~~~~
      |                                     GL_DRAW_BUFFER_EXT
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:283:57: Fehler: »GL_DEPTH_ATTACHMENT_EXT« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »GL_DEPTH_ATTACHMENT«?
  283 |  m_glExtFunc.glFramebufferTexture2D(GL_FRAMEBUFFER_EXT, GL_DEPTH_ATTACHMENT_EXT, target, texID, 0);
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~
      |                                                         GL_DEPTH_ATTACHMENT
/home/pi/CloudCompare/libs/CCFbo/src/ccFrameBufferObject.cpp:291:7: Fehler: »GL_FRAMEBUFFER_COMPLETE_EXT« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »GL_FRAMEBUFFER_COMPLETE«?
  291 |  case GL_FRAMEBUFFER_COMPLETE_EXT:
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       GL_FRAMEBUFFER_COMPLETE
make[2]: *** [libs/CCFbo/CMakeFiles/CC_FBO_LIB.dir/build.make:89: libs/CCFbo/CMakeFiles/CC_FBO_LIB.dir/src/ccFrameBufferObject.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:1898: libs/CCFbo/CMakeFiles/CC_FBO_LIB.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2
`

**Comment by spatial-mk** [comment]
I found a solution:
The problem was caused by using a 32bit Raspbian OS. Installing a 64bit Raspbian OS (I tested with 2021-05-07-raspios-buster-arm64.img) solved the problem. Once all dependencies are installed and CloudCompare is compiled according to the BUILD.MD it works (I just tested the basic install so far, not yet the additional options).
Note: In order to make it run I had to additionally export the path to where the 'libCCAppCommon.so' file was `> export LD_LIBRARY_PATH=/usr/local/lib` after the install with cmake has finished.
The following libraries I also had to install for successful compilation: `qt5-default qttools5-dev qttools5-dev-tools libpdal-dev libxerces-c-dev libjsoncpp-dev`

**Comment by dgirardeau** [comment]
Thanks for the feedback. That's good to know.
