### ISSUE TITLE
Python setup in IDE

### ISSUE THREAD

**Issue by dheejha** [CloudCompare/CloudCompare#1540]
Dear Team, I was looking at various instructions given on CloudCompare GitHub links to install CloudCompare or cloudComPy, however I am unsuccessful. I want to install it in one of the Anaconda IDE (For. e.g. Spyder, Jupyter). I am quite new to python, however know few package installations techniques like conda install/ pip install / adding the path in Tool>PythonPath Manager.
My intention is to repeat below steps done in software in python, as I need to do it for more than 10 such pair of stl files.
Steps to automate in cloud compare:

1. Import two stl files (reference, new model)
2. Fine registration (ICP) (default settings with 100% final overlap)
3. Save the Registration info image/csv respective new model location
4. Measure cloud/mesh distance with default settings
5. Compute stat. params(active SF) gaussian distribution fitting
6. Save gaussian distribution plot in respective new model location
7. Save new model modified stl (which was transformed for step 2 by the software)
I know how to loop these steps in python. I am unable to import cloudCompy as cc or import pycc to try building my steps in python. Do you think these steps can be done in python wrapper of the software?
Any suggestion is welcome.

**Comment by 459737087** [comment]
Hello! would you like to add cloudcompare to pip package?

**Comment by dheejha** [comment]
> Hello! would you like to add cloudcompare to pip package?

Yes, it would become seamless and easier to access over different platform. Thank you.
