### ISSUE TITLE
CC crash when using myown plugin(based on PCL1.12)

### ISSUE THREAD

**Issue by iskywater** [CloudCompare/CloudCompare#1546]
I wrote a RadiusOutlierRemoval plugin in CloudCompare based on PCL ([Here](https://github.com/iskywater/RadiusOutlierRemoval-CloudCompare-Plugin-) is my files). It works well when I using PCL1.11.0. But, with the same code, CC will crash if I change the PCL version to PCL1.12. The pointcloud data to be processed is very small (about 20000 points). I'll will be grateful if someone can give me some advice.

I will get these two windows if I run the plugin directly 
![1](https://user-images.githubusercontent.com/85938821/143156249-5a5689c0-b819-4124-b3c1-e1c315cee029.jpg)
![2](https://user-images.githubusercontent.com/85938821/143156254-9f495c56-397e-40c1-aa5e-57961a7d33be.jpg)

after a while CC will crash

I try to debug the code, here is what I got

<img width="691" alt="2021-11-24_132016" src="https://user-images.githubusercontent.com/85938821/143179530-ef91ffe9-90b6-4b0f-bb6c-68421dfadf40.png">
I hope my plugin will work well when using PCL1.12.

Environment
CloudCompare2.11.3
Win10
PCL1.12
Qt5.14.2

**Comment by dgirardeau** [comment]
Are you using the right PCL DLLs? (if any)

Otherwise, it may be an issue with Eigen alignment (not sure how this is setup for PCL 1.12? Did you compile PCL yourself?

**Comment by iskywater** [comment]
I install PCL with PCL-1.12.0-AllInOne-msvc2019-win64.exe  package. I believe that the PCL DLLs is right.

**Comment by dgirardeau** [comment]
Are the DLLs copied next to the executable? (just in case, since it was working with PLC 1.11, I thought it may be an issue with the plugin using the wrong DLL at runtime)

**Comment by iskywater** [comment]
The DLLs are gererated while comping  CloudCompare. Just now I try to copy PCL DLLs directly from PCL1.12 bin directory to CloudCompare executable it still doesn't work.

**Comment by dgirardeau** [comment]
Ok, on my side I'm currently compiling PCL 1.12, but it will take a while

**Comment by iskywater** [comment]
Thanks a lot.

**Comment by dgirardeau** [comment]
!Ok, at least I can confirm that I reproduce the issue!

**Comment by dgirardeau** [comment]
But "sadly", only in Release mode, not in Debug mode... Which doesn't help me to debug the issue 😅

**Comment by dgirardeau** [comment]
And it's not related to your plugin, I reproduce the crash with any call to PCL...

**Comment by dgirardeau** [comment]
Update: looking at this thread (https://github.com/PointCloudLibrary/pcl/pull/4698), I tried to deactivate the AVX feature (you have to re-compile PCL) and it now works on my side!

**Comment by iskywater** [comment]
Awesome! Just as what you have done, I deactivated the AVX feature when compiling PCL1.12.0. My CloudCompare plugin woks now. Thank you very much Daniel
