### ISSUE TITLE
Native M1 / Apple Silicon version

### ISSUE THREAD

**Issue by alexrfholland** [CloudCompare/CloudCompare#1547]
**Describe the feature you would like**

Is there a plan for an apple silicon version of cloud compare? Got a new MacBook Pro with the M1 Pro chip and cloud compare is pretty great on it -- it would be phenomenal where it native!

**Describe alternatives you've considered**

Yes, emulation.

**Is your feature request related to a problem? Please describe.**

Native support for m1 Macs is the clear future for cloudcompare on apple devices. 

**Additional context**

**Comment by dgirardeau** [comment]
Yes, I believe @tmontaigu is working on it ;)

**Comment by tmontaigu** [comment]
Yep binaries for the beta are on slack, ready to be uploaded on the website

**Comment by alexrfholland** [comment]
Oh amazing! any chance I could get a link to the slack / download? Got a 300 mil point cloud I’m working on right now!

**Comment by tmontaigu** [comment]
Its better to wait for thel to be uploaded on the main website

**Comment by alexrfholland** [comment]
Yeah no worries. Would you have a rough idea when they’ll be there?
Thanks for your great work!

**Comment by tmontaigu** [comment]
Relatively soon™ i think

**Comment by dgirardeau** [comment]
Ok, it's now online! Many thanks @tmontaigu ;)
