### ISSUE TITLE
Description of facets construction algorithm

### ISSUE THREAD

**Issue by Zvyozdo4ka** [CloudCompare/CloudCompare#1549]
I am gonna use exported file facets.svg, to extract information about facets. However, I can't understand the algorithm of evaluating facets, and how can I draw on threeJs scene these facets.

I have following information:
Index,
Center X,
Center Y, 
Center Z,
Normal X,
Normal Y,
Normal Z,
RMS,
Horiz ext,
Surf ext,
Surface,
Dip dir.
Family ind,
Subfamily ind.

I have glanced through:
manual for user - https://cloudcompare.org/doc/qCC/CloudCompare%20v2.6.1%20-%20User%20manual.pdf
main web-site,
links from manual and web-site.

There is no suitable data on this problem. Please, share the information. 
Thanks in advance for any help, guys

**Comment by dgirardeau** [comment]
Hi,

The official documentation is the wiki... The 2.6 version is quite old ;)

You can find a little bit more pieces of information here: https://www.cloudcompare.org/doc/wiki/index.php?title=Facets_(plugin)#Export_facets_as_a_SHP_file

**Comment by Zvyozdo4ka** [comment]
> Hi,
> 
> The official documentation is the wiki... The 2.6 version is quite old ;)
> 
> You can find a little bit more pieces of information here: https://www.cloudcompare.org/doc/wiki/index.php?title=Facets_(plugin)#Export_facets_as_a_SHP_file

Hi! Thanks but I have already seen that, they just listing variables from returned file. But how to use that measure? How to draw the plane? 
It is so unfair to close the issue. It is still unclear how to build the facets from x,y,z, normal vectors etc.

**Comment by dgirardeau** [comment]
Were you actually referring to **SHP** instead of **SVG** in your original message?

If your question is how to read SHP files in three.js, this is probably not the best place to ask this question. I can mostly say that in CloudCompare we are relying on ShapeLib (https://github.com/OSGeo/shapelib - C++ library) to do it. SHP is an old and standard format in the GIS world.

Otherwise, if you were referring to the list of features above (that you can more easily access via the CSV file), then I guess you could display small rectangles instead of facets (with the center, the normal, Horiz_ext and Vert_ext). This list is better described in the wiki (and complete - _yours is missing the Vert_ext column for instance_, thus I thought you were maybe missing this key value).

The wiki (again) also points you to an article that explains how the algorithm works.

**Comment by Zvyozdo4ka** [comment]
> Were you actually referring to **SHP** instead of **SVG** in your original message?
> 
> If your question is how to read SHP files in three.js, this is probably not the best place to ask this question. I can mostly say that in CloudCompare we are relying on ShapeLib (https://github.com/OSGeo/shapelib - C++ library) to do it. SHP is an old and standard format in the GIS world.
> 
> Otherwise, if you were referring to the list of features above (that you can more easily access via the CSV file), then I guess you could display small rectangles instead of facets (with the center, the normal, Horiz_ext and Vert_ext). This list is better described in the wiki (and complete - _yours is missing the Vert_ext column for instance_, thus I thought you were maybe missing this key value).
> 
> The wiki (again) also points you to an article that explains how the algorithm works.

Where does it points to an article with algorithm? It points to:
1. FACETS : A CLOUDCOMPARE PLUGIN TO EXTRACT GEOLOGICAL PLANES FROM UNSTRUCTURED 3D POINT CLOUDS
2. France’s reference public institution for Earth Science applications
3. (https://en.wikipedia.org/wiki/Stereographic_projection)
4. https://en.wikipedia.org/wiki/K-d_tree
5. https://www.cloudcompare.org/doc/wiki/index.php?title=Facets_(plugin)#Export_facets_as_a_SHP_file

Where is the description of algorithm?
All I need, is to use any of files: Svg or SHp to draw facets. How to draw it by knowing information given in file?

For example, by knowing Normal vectors, and the the x,y,z we can draw a line, but how did you define facets? How was it drawn in your program? there is no description on wiki.

**Comment by Zvyozdo4ka** [comment]
![QFacetsSHPinQGis](https://user-images.githubusercontent.com/74532816/144731617-ae9dcfd0-15cb-4d28-a214-8e243af99151.jpg)


How did you defined all these facets? There are more than thousand of them. For example, facet # 786, by knowing 

Index,
Center X,
Center Y,
Center Z,
Normal X,
Normal Y,
Normal Z,
RMS,
Horiz ext,
Surf ext,
Surface,
Dip dir.
Family ind,
Subfamily ind.

How your program defined black borders? I dont need to understand how did you get facets, I just wanna draw them as you defined in your program.

**Comment by Zvyozdo4ka** [comment]
![facet](https://user-images.githubusercontent.com/74532816/144731690-1c742ea7-8556-4672-809e-f126dc8439c4.jpg)

Cloud Compare has defined my ply object's facets as it shown here. But I must draw the same in my program, I can't use screen shot, to draw same on three js. Just give me kindly the algorithm for describing facets. How did you get the shape and borders of facet?

**Comment by Zvyozdo4ka** [comment]
For example if you give me coordinates of three points, i can draw triangle by linking the points. What about facets? how to get it from the final svg or shp file?

**Comment by dgirardeau** [comment]
> ![QFacetsSHPinQGis](https://user-images.githubusercontent.com/74532816/144731617-ae9dcfd0-15cb-4d28-a214-8e243af99151.jpg)
> 
> How did you defined all these facets? There are more than thousand of them. For example, facet # 786, by knowing
> 
> Index, Center X, Center Y, Center Z, Normal X, Normal Y, Normal Z, RMS, Horiz ext, Surf ext, Surface, Dip dir. Family ind, Subfamily ind.
> 
> How your program defined black borders? I dont need to understand how did you get facets, I just wanna draw them as you defined in your program.

The capture above is QGis, not CloudCompare... But that's exactly what you can get by loading... a **SHP** file in QGis ;).

You should dig in the specifications of SHP files, as you'll find everything you need there...

**Comment by Zvyozdo4ka** [comment]
> You should dig in the specifications of SHP files, as you'll find everything you need there...

I appreciate your advice. Thank you so much
