### ISSUE TITLE
Cannot save in PCD

### ISSUE THREAD

**Issue by equal-l2** [CloudCompare/CloudCompare#1552]
**Describe the bug**
Saving a cloud in PCD format fails.

**How to reproduce**
1. Load any of cloud
2. Select the cloud
3. Try to save the cloud as PCD
4. Fail to save, with the message "the third-party library in charge of saving/loading the file has failed to perform the operation"

**Expected behaviour**
Successfully save the cloud as PCD

**Additional context**
My collague (in Windows 11) also experiences this problem.

**Your environment**
 - CC Version (or git hash/tag): 2.12 beta [Windows 64-bit] (Downloaded at 12/02/2021)
 - OS & Version: Windows 10 Pro 21H1
 - Graphics card: NVIDIA GeForce RTX 2070 with Max-Q Design
 - Qt Version (if compiling): (not compiling)

**Comment by equal-l2** [comment]
Running CloudCompare in command line mode shows additional errors as below:
```
[pcl::concatenateFields] Dimensions of input clouds do not match: cloud1 (w, 0, h, 0), cloud2 (w, 10000, h, 1)
[pcl::PCDWriter::writeBinary] Input point cloud has no data!
```

**Comment by equal-l2** [comment]
2.11.3 Anoia is free from the issue on our env, so this is presumably a regression.

**Comment by dgirardeau** [comment]
I confirm the issue. I'll fix it quickly.

**Comment by dgirardeau** [comment]
Ok I've pushed a fix commit (94cec1a31a2c020106479e702c5802ee58a8bab7). I'll update the online 2.12.beta installers a bit later as I'll try to fix another issue with PCD files (issue #522)

**Comment by dgirardeau** [comment]
(the Windows 2.12.beta version online has been updated)

**Comment by equal-l2** [comment]
Thank you for the fix!
As the windows environment is only available on my part-time job, I'll try on the next work day.

**Comment by equal-l2** [comment]
I confirmed the issue is fixed.
Thank you again for the fix!
