### ISSUE TITLE
Cloudcompare CLI can't guess file extension in filenames with spaces

### ISSUE THREAD

**Issue by h4k1m0u** [CloudCompare/CloudCompare#1554]
**Describe the bug**
When the filename includes spaces and a CloudCompare command is called from the command-line, quotes need to be used around filenames. However this prevents CloudCompare from guessing file extension

**How to reproduce**
CloudCompare ' -O "/home/hakim/pointcloud 1.ply" -O "/home/hakim/pointcloud 2.ply"' -C_EXPORT_FMT PLY -MERGE_CLOUDS

The last double-quote (") after the ply extension is the one causing the problem I think.

**Your environment**
 - CC Version (or git hash/tag): 2.11.3
 - OS & Version: Ubuntu
 - Graphics card: GeForce 950
 - Qt Version (if compiling):  5.12.8

**Comment by dgirardeau** [comment]
I don't have any issue on Windows with a similar pattern. Maybe it's a Linux-only issue?

And what about the single quote after CloudCompare in your example?

**Comment by h4k1m0u** [comment]
Yes I had this command in a bash script running on Ubuntu's terminal. Unfortunately, I couldn't use single-quotes in this case as the path to the ply file was in a bash variable. I guess I can close this issue (just wanted to notify you about it), since I can always rename my input files.
