### ISSUE TITLE
Trying to open LAZ file crashes the application

### ISSUE THREAD

**Issue by fabiopicchi** [CloudCompare/CloudCompare#1559]
**Describe the bug**

Hi! I just came across this wonderful project I wish I knew about before :)
I have been using [displaz](https://github.com/c42f/displaz) so far but CloudCompare seems to be way more robust.

Anyway, I have just built the project on my machine (macOS) and I am trying to load a laz file, but the program crashes with no report as soon as I try to open the file.

**How to reproduce**
My steps to build everything were the following:

1. Cloned CloudCompare
2. Installed qt@5 and pdal using `homebrew`
3. Ran the following commands inside the build folder:

```
cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt@5 -DCMAKE_INSTALL_PREFIX=/Users/fabiopicchi/Applications/ -DPLUGIN_IO_QPDAL=ON -DPDAL_DIR=/Users/fabiopicchi/tools/PDAL .. 
```
**OBS**: I added this PDAL_DIR option after trying a first build and crashing the application... and it didn't work. `/Users/fabiopicchi/tools/PDAL` is the path to where I cloned the PDAL repo to.

**Expected behaviour**

LAZ file is correctly displayed!

**Your environment**

 - CC Version (or git hash/tag): 08b7ae9a36ccd82db6275180defc0f2ae03af30a
 - OS & Version: macOS 12.0.1 (21A559)
 - Graphics card: AMD Radeon Pro 5300M 4 GB
 - Qt Version (if compiling): 5.15.2

**Comment by tmontaigu** [comment]
Have you tried the prebuilt macOs binaries from the website ? http://cloudcompare.org

Also you are mixing pdal from hombrew with a pdal you cloned so that is causing the crash when you open a LAZ/LAS.

If you just let cmake use the PDAL from hombrew the app installed after `cmake --install` will crash on startup and that is normal on macOs it is due to the app having wrong signing.

If you still want to use your own compiled app, you should do
 ```
codesign --deep --force --timestamp --options=runtime --sign "-" /Users/fabiopicchi/Applications/CloudComapre.app
```

The app will only be valid on you computer.

**Comment by fabiopicchi** [comment]
Sorry for the delayed response @tmontaigu 

I applied the snippet you suggested and that makes the application crash as soon as it opens. Otherwise, the application opens just fine and crashes when I try to open a LAZ file (without any error message).

I removed the `-DPLUGIN_IO_QPDAL=ON -DPDAL_DIR=/Users/fabiopicchi/tools/PDAL` flag and it still doesn't work :/

I have also confirmed that the PDAL library is in the app folder, so no idea on what is going on here...
<img width="719" alt="Screenshot 2021-12-12 at 1 20 45" src="https://user-images.githubusercontent.com/1087462/145694604-fbcee087-4305-457f-9c7e-b1df3c3d6b2b.png">
 
Thanks for the pre-built link though! I won't prolong this thread, I am posting this information just to raise the issues I had trying to build the CloudCompare myself.

**Comment by tmontaigu** [comment]
Do you have a mac with a M1 ?

**Comment by fabiopicchi** [comment]
Nope, still rolling the old Intel one but I should get my hands on an M1 soon. I grabbed the prebuilt binary but unfortunately found out that it doesn't have the PDAL plugin included (in the beta).

The stable version only supports LAS up to 1.3 :/

I'm able to natively build https://github.com/c42f/displaz quite easily in my computer with the latest version of LasLib (not packaged as an `.app` though). I'm wondering if I can help with this effort in CloudCompare 🤔

**Comment by tmontaigu** [comment]
The beta pn the website should have the PDAL plugin bundled within

The CloudCompare console should print a message about successfully /unsuccessfully loading the PDAL plugin

**Comment by fabiopicchi** [comment]
Damn, sorry for the misunderstanding, I just confirmed that it works!

I must have made a mess with all the versions I had available locally
