### ISSUE TITLE
libCCAppCommon.so cannot open shared object file

### ISSUE THREAD

**Issue by reppiZ** [CloudCompare/CloudCompare#1560]
Just installed CloudCompare following the directions in BUILD.md. Even built the binary out of source like suggested and used the 
"--recursive" argument when cloning the repository. It installed successfully and I verified that the shared library objects are in /usr/local/lib however, when I run the command "CloudCompare" i get the following: "error while loading shared libraries: libCCAppCommon.so: cannot open shared object file: No such file or directory"

However, "libCCAppCommon.so" is indeed in /urs/local/lib along with other needed shared libraries. 

Am i missing something? Also please forgive me if this is not in the right spot. I'm not use to GitHub.

Environment: 
 - Ubuntu 21.10 x64
 - Qt Version 5.15.2

**Comment by reppiZ** [comment]
Fixed with running "sudo ldconfig"

**Comment by EpicWink** [comment]
Related: #1294 , #1346
