### ISSUE TITLE
Can't open anything other than than .las files.

### ISSUE THREAD

**Issue by burnsjake** [CloudCompare/CloudCompare#1562]
**Describe the bug**
I'm running the linux beta flatpack. When I try and open any file other than a LAS file I get this dialog box: 
"**PDAL exception: readers.las: File signature is not 'LASF', is this an LAS/LAZ file?** "
 
If I open a .ply file I get the same dialog with a follow-up:
"**An error occurred while loading 'testhoughnormal': the third-party library in charge of saving/loading the file has failed to perform the operation**"

Oh, and exporting an STL seems to leave me with a corrupt format that cannot be opened, even in meshlab or open3d.

**Your environment**
 - 2.12 beta 64bit via flatpack
 - Slackware64 Current
 - Intel
 - NA
 

PDAL exception: readers.las: File signature is not 'LASF', is this an LAS/LAZ file?
**How to reproduce**

**Expected behaviour**
I expect CC to open and save files normally.

**Additional context**

**Comment by tmontaigu** [comment]
I'm on fedora and I don't have this problem :thinking:
