### ISSUE TITLE
Error in scale output when "render to file".

### ISSUE THREAD

**Issue by yamahirog** [CloudCompare/CloudCompare#1564]
**Describe the bug**

When using "render to file" to render an image and changing the "zoom" value, the value above the scale bar is not correct.

**How to reproduce**

**Expected behaviour**

I want the numbers on the scale bar to be displayed correctly even if I change the zoom value.

**Additional context**

For example, if you set the Zoom value to 2, the value on the scale will be one-half.

**Your environment**
 - CC Version (or git hash/tag):release: 2.12.beta (12/22/2021)
 - OS & Version:Windows 10
 - Graphics card: NVIDIA GeForce RTX 2080
 - Qt Version (if compiling): 

I checked on several other Windows PCs and found the same bug.

**Comment by dgirardeau** [comment]
Good catch!

That's fixed with the latest 2.12.beta version online.

Thanks for the feedback.
