### ISSUE TITLE
Segmentation toolbar: mouse clicks are not registered properly after I or O key stroke

### ISSUE THREAD

**Issue by ryukisai** [CloudCompare/CloudCompare#1566]
**Summary**
When using I or O hotkeys to perform cuts on a cloud, the whole user interface loses focus. It does not register mouse clicks properly anymore. The clicks are registered in 3d view space instead of the toolbars.

**Steps to reproduce the behaviour**
1. Open any cloud with CC 2.12 β
2. Select the cloud
3. Enable the Segmentation tool (scissors)
4. Make any segmentation (using polygon selection mode)
5. Validate this segmentation using I or O hotkeys
6. Try to click on any icon of the interface: the clicks are registered in the 3d view, through the toolbars
7. This persists even after closing the segmentation tool via the Return key (but not if you cancel the segmentation with Escape)

**Expected behaviour**
For step 6, the clicks should be registered by the toolbars instead of through (this was working fine in 2.11).

**Your environment**
 - CC Version (or git hash/tag): 2.12 β (all versions until 2022-01-02)
 - OS & Version: Win10 x64 20H2 (also tested on 21H2 at home)
 - Graphics card: Nvidia MX130 (also tested on RTX2080Ti at home)
 - I use a multi-screen setup at work, but single screen at home

**Comment by dgirardeau** [comment]
Hi,

I managed to reproduce it, but only if the polyline is not 'closed' (i.e. the user has not pressed the right mouse button yet). Is it the case on your side as well?

I'll try to fix it quickly anyway.

**Comment by ryukisai** [comment]
Hi! I’ll check that right away and report, but i can already say that i indeed did not close the polyline with right click. Be right back, merci !

**Comment by ryukisai** [comment]
I’ve tried, yes as you said the bug is only there if you end the polyline selection with I or O, without right-clicking. If i close the polyline before pressing I or O, all works well indeed (i need a huge number of segmentations in my current workflow so i’ve learnt to appreciate the 1 less click).
Thanks in advance! No need to hurry, i’m still using 2.11.3 for production work. Merci par avance et bravo pour votre travail !

**Comment by dgirardeau** [comment]
Ok that should be fixed now with the latest 2.12.beta version.

One thing of interest is that previously, when using 'i' or 'o' on an 'non-closed' polyline, CC would ignore the latest vertex (= the current mouse position). This might have led to a strange behavior sometimes?

I've also fixed another bug at the same time (clicking on the reset button would prevent the segmentation to work until the tool was closed and reopened again!)

**Comment by ryukisai** [comment]
Merci beaucoup !
I’ll test and report ASAP. Yes, actually yesterday i tested this more, and the segmentation tool was broken in more ways, as you mentionned.
However, i believe that the segmentation tool used the mouse position as an active vertex when i pressed I or O in 2.11. That was pretty cool, because it essentially i just pointed the desired closing vertex, and pressed I or O and i was done. However i’ll adapt to whatever decision you took!

**Comment by dgirardeau** [comment]
This should work as well now in 2.12.beta.

**Comment by ryukisai** [comment]
Perfect, both issues are now solved indeed (the I O hotkey bug and also the reset button bug).
You are right i also noticed that latter problem yesterday, i’m glad you already found and fixed it.
I’m glad you kept the previous behaviour for unclosed polygons too.
Merci encore, à bientôt! alban.

**Comment by ryukisai** [comment]
Hey there, this issue is partially still here, and i found a way to reproduce it (hopefully). I'm currently in 2022-10-02 α version.
How-to:
1. select a cloud and press T to open scissors tool
2. click 1 vertex in the 3d view
3. press space to pause the section tool
4. the interface stops registering clicks (you can escape by pressing escape or enter)
If you could have a look, thanks a lot!

**Comment by dgirardeau** [comment]
Good catch! That's fixed now (eab5e754574839a51e900821b86ade36b7d7ad09).

And I updated the 2.13.alpha version online.

**Comment by ryukisai** [comment]
Thanks a lot Daniel!
