### ISSUE TITLE
How to compile debug build locally?

### ISSUE THREAD

**Issue by reppiZ** [CloudCompare/CloudCompare#1570]
I have a release build of CloudCompare installed on my Ubuntu distro which runs and works fine. I used cmake and invoked `-DCMAKE_BUILD_TYPE=Debug` and set the prefix install path to `/home/ccDebugInstall`. However when I try to run the CloudCompare binary in the bin directory, it cant find the shared libraries in the directory above it which are in /home/ccDebugInstall/lib. Why is this? Can i invoke an arugment in the command line to fix this? 

Here is a screenshot of whats not linked: 

![ldd_cap](https://user-images.githubusercontent.com/42074531/148578902-7b820137-8773-46e2-89c6-6fbc7079a0ef.png)

**Your environment**
 - CC Version (or git hash/tag): 2.12
 - OS & Version: Ubuntu 21.10 x86_64 
 - Graphics card: Nvidia Quadro M2000M

**Comment by dgirardeau** [comment]
I'm still not the Linux expert here, but I believe it has something to do with LD_LIBRARY_PATH?

**Comment by tmontaigu** [comment]
Yes using LD_LIBRARY_PATH could help.

But on my linux machine I don't have this problem, i'll have to check

**Comment by reppiZ** [comment]
I know that you can set `$LD_LIBRARY_PATH` to the correct directory, but this is only temporary and I would have to do this every time I logged out or rebooted the computer. Is there a way to permanently tell the program where the libraries are?

**Comment by tmontaigu** [comment]
I don't know if there is a way to do that other than using a script.

But actually you don't need to do the install step on linux, just building and starting CC from the build folder should work.
