### ISSUE TITLE
qPDALIO plugin fails to build against current PDAL (from git master branch).

### ISSUE THREAD

**Issue by klassenjs** [CloudCompare/CloudCompare#1573]
It appears that PDAL/PDAL#3616 moved some of the ExtraDim and VLR stuff into another namespace and to a "private" header.  This causes many build errors in `plugins/core/IO/qPDALIO/src/LASFilter.cpp`

This itself appears mostly fixable by adding the header (`pdal/io/private/las/Utils.hpp`) and adding a `using namespace pdal::las;`, however the signature of ExtraBytesIf::toExtraDims() has also changed (and I get the impression that the header being moved to `private` indicates the use of these methods outside of PDAL is discouraged).

I'm not quite following the code in the PDAL plugin well enough to figure out if there is a more PDAL friendly way to get at the information this code is trying to access.

Tested against PDAL/PDAL@ac8068c.  CloudCompare works as expected with the older PDAL/PDAL@c5b273e25.

**Comment by dgirardeau** [comment]
Maybe @tmontaigu's branch will solve that? (https://github.com/CloudCompare/CloudCompare/pull/1561). It's work in progress, but since it's meant to be the future of the qPDALIO plugin, I guess it will work with the most recent version of PDAL 😋
