### ISSUE TITLE
E57 support not working for Linux flatpak distribution

### ISSUE THREAD

**Issue by sdslavin** [CloudCompare/CloudCompare#1574]
Hi there. I am a new user of CloudCompare, and do most of my work in a Linux environment, with the rest mostly on MacOS. We have a number of workloads that begin with E57-formatted point clouds. My initial tests of CC on MacOS worked fine, and so I downloaded the flatpak distribtuion (tried both 2.11 and 2.12beta) on my Linux workstation (Linux Mint 20.2; effectively Ubuntu).

The flatpak distribution of both versions installs with no problem, and runs easily from the conveniently installed icons (an added bonus). Unfortunately, every E57 file I've tried fails to load properly. I've even tried sample data (the bunny) found at http://www.libe57.org/data.html. Works fine on MacOS, not at all on Linux. Downloading sample CC .bin files works great on both platforms.

I think it's an issue with the libe57 implementation, as compiled. The error is such that when I go to load the .e57 file, I'm prompted with a pop-up window asking me if I really want to load some enormous number of point clouds. It seems like a byte-order or alignment issue with the binary E57 format.

For what it's worth, I've compiled my own version from source, using the excellent instructions. It wasn't trivial, but straightforward, and the E57 functionality works fine.

**Comment by dgirardeau** [comment]
Which version of libE57 have you manually compiled? The one shipped with CloudCompare (as a submodule) or another one?

Maybe @christian-rauch or @tmontaigu have an idea?

**Comment by christian-rauch** [comment]
The flatpak simply uses [`PLUGIN_IO_QE57=ON`](https://github.com/flathub/org.cloudcompare.CloudCompare/blob/5da65ba07e99d73d47590f908148b4d7be08f0ab/org.cloudcompare.CloudCompare.yaml#L344) to enable E57 support. This will be the same version as defined in the plugin CMake subproject https://github.com/CloudCompare/CloudCompare/tree/master/plugins/core/IO/qE57IO. This was recently updated to [version 2.3](https://github.com/CloudCompare/CloudCompare/commit/3a261edc92ca896882993b231c39bff11fe74587).

**Comment by christian-rauch** [comment]
@sdslavin I tested the [BunnyDouble.e57 - XYZ - 726KB](http://sourceforge.net/projects/e57-3d-imgfmt/files/E57Example-data/bunnyDouble.e57/download) file and it renders without errors. I am not prompted with a pop-up window. The file just loads and shows the bunny.

**Comment by tmontaigu** [comment]
I have the same behaviour as christian-rauch, the bunny load fine on the flatpak

**Comment by sdslavin** [comment]
> Which version of libE57 have you manually compiled? The one shipped with CloudCompare (as a submodule) or another one?
> 
> Maybe @christian-rauch or @tmontaigu have an idea?

I built it against the E57 library supplied with the CC git base. Seeing that others are not having this problem, but I am on two different machines with Mint 20.2 makes me think it's related to my distribution (or other stuff I've installed). Not sure why yet, but I am happy to see it's just me.

**Comment by sdslavin** [comment]
Daniel,

I manually compiled the CloudCompare source, using the E57 submodule. I will admit that I don’t use flatpak for anything else on the two machines I tried it on. I have no idea why I’d be getting this behavior, but I’m guessing it’s somehow related to a shared library in my Linux Mint distribution (and so Ubuntu, or Debian). Those machines are running Linux Mint 20.2.

Here’s some potentially useful info from one of those two machines (which are just about identical in s/w setup):

> flatpak --version
Flatpak 1.6.5

> flatpak --default-arch
x86_64

> uname -a
Linux myhostname 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

> cat /etc/os-release
NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal




From: Daniel Girardeau-Montaut ***@***.***>
Date: Monday, January 17, 2022 at 2:21 AM
To: CloudCompare/CloudCompare ***@***.***>
Cc: Slavin, Shawn ***@***.***>, Author ***@***.***>
Subject: [External] Re: [CloudCompare/CloudCompare] E57 support not working for Linux flatpak distribution (Issue #1574)
This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Which version of libE57 have you manually compiled? The one shipped with CloudCompare (as a submodule) or another one?

Maybe @christian-rauch<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchristian-rauch&data=04%7C01%7Cslavin%40iu.edu%7C50905dc127954ae819b508d9d989d58a%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637780008911599015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=F5yPNeFXvsp8LGEnVv3RIBqfA66jJMWPh3JjMjjlomg%3D&reserved=0> or @tmontaigu<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftmontaigu&data=04%7C01%7Cslavin%40iu.edu%7C50905dc127954ae819b508d9d989d58a%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637780008911599015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FujhAbxM0Dc%2BMdSffjMGauCRXZAkfsOK4L%2FQzpEWgKU%3D&reserved=0> have an idea?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCloudCompare%2FCloudCompare%2Fissues%2F1574%23issuecomment-1014212549&data=04%7C01%7Cslavin%40iu.edu%7C50905dc127954ae819b508d9d989d58a%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637780008911599015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rX4l6H0ZY8zOUkfjCvPACU61%2BsXS76%2FjrynpxsNo42E%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF2TVDXOL3JV2N3VOU6LJN3UWO7LRANCNFSM5MBRNBHA&data=04%7C01%7Cslavin%40iu.edu%7C50905dc127954ae819b508d9d989d58a%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637780008911599015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RoB1SAs%2B%2F0Jdo3yoblayqxsuC0qd1QHo5TY26%2FjM4WM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cslavin%40iu.edu%7C50905dc127954ae819b508d9d989d58a%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637780008911599015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=M0SS%2BuFAhSWr4MtMMSFvuhzhOsTbjcsHNAjuDFxnzJc%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cslavin%40iu.edu%7C50905dc127954ae819b508d9d989d58a%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637780008911599015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zKKoVTcezRyHCSzNtn0wFAxbA7eyDdweuXzlzBv6zww%3D&reserved=0>.

**Comment by christian-rauch** [comment]
> Flatpak 1.6.5

Can you upgrade your flatpak via the ppa at https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak and see if this helps?

If you still observe different behaviour with the same flatpak version and the same CloudCompare flatpak on different systems, then I think this is a flatpak issue. If this is the case, please open an issue at the flatpak repo (https://github.com/flatpak/flatpak).

**Comment by sdslavin** [comment]
Christian,

It looks like the older Flatpak was the culprit. I upgraded to Linux Mint 20.3 (Una; not Uma), and the updated flatpak version is:


> flatpak --version
Flatpak 1.12.2

Using the newer version, the CloudCompare v2.12beta flatpak installs, runs, and loads the sample E57 file correctly.

Thanks for nudging me to look into the flatpak upgrade.

-Shawn
________________________________
From: Christian Rauch ***@***.***>
Sent: Tuesday, January 25, 2022 1:15 PM
To: CloudCompare/CloudCompare ***@***.***>
Cc: Slavin, Shawn ***@***.***>; State change ***@***.***>
Subject: [External] Re: [CloudCompare/CloudCompare] E57 support not working for Linux flatpak distribution (Issue #1574)

You don't often get email from ***@***.*** Learn why this is important<http://aka.ms/LearnAboutSenderIdentification>
This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Flatpak 1.6.5

Can you upgrade your flatpak via the ppa at https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Flaunchpad.net%2F~alexlarsson%2F%2Barchive%2Fubuntu%2Fflatpak&data=04%7C01%7Cslavin%40iu.edu%7C93c13e988cb44a9ec71d08d9e02ebcc0%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637787313610703286%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7yUms259OFkUvawpnJfB05rHdBFFB%2BTYWUj8PeVZgIw%3D&reserved=0> and see if this helps?

If you still observe different behaviour with the same flatpak version and the same CloudCompare flatpak on different systems, then I think this is a flatpak issue. If this is the case, please open an issue at the flatpak repo (https://github.com/flatpak/flatpak<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflatpak%2Fflatpak&data=04%7C01%7Cslavin%40iu.edu%7C93c13e988cb44a9ec71d08d9e02ebcc0%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637787313610703286%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MmYOFZRGMQCh%2B7650Dg%2F2jc6fWH9q5oGd%2FpZjOYGXU8%3D&reserved=0>).

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCloudCompare%2FCloudCompare%2Fissues%2F1574%23issuecomment-1021473821&data=04%7C01%7Cslavin%40iu.edu%7C93c13e988cb44a9ec71d08d9e02ebcc0%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637787313610703286%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Rp0yh4yN3g2TgwrT5ZNtguq9PPdvElKC4kwJCw%2F%2F%2FzM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF2TVDQWZ77SYAXOZIMIZ7LUX3SE7ANCNFSM5MBRNBHA&data=04%7C01%7Cslavin%40iu.edu%7C93c13e988cb44a9ec71d08d9e02ebcc0%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637787313610703286%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WFkmqmLvc%2BY0gr0dXOw5myT32NJeALleLqJGq0Rl1dk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cslavin%40iu.edu%7C93c13e988cb44a9ec71d08d9e02ebcc0%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637787313610703286%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kD9NJaM0rcRvil0l8%2BLU%2BqfXA4oBesmP%2FR8VY1lvwOQ%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cslavin%40iu.edu%7C93c13e988cb44a9ec71d08d9e02ebcc0%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637787313610703286%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ICkeF4fO6Tyq4mXdRyuMhpFPPX5WQvYm3golSq9Lh4M%3D&reserved=0>.
