### ISSUE TITLE
align shift not added to point cloud

### ISSUE THREAD

**Issue by Yourbee** [CloudCompare/CloudCompare#1577]
**Describe the bug**

After align two point cloud by picking 4 points, when the point`s coordinates are very large, the global shift will not added to point cloud。
**How to reproduce**

just align point clouds to large coordinates who need global shift. The results will not have the given global shift
**Expected behaviour**

**Additional context**

**Your environment**
 - CC Version (or git hash/tag):
2.12 beta and master branch have this problem.
2.11.3 works well.

**Comment by dgirardeau** [comment]
Can you provide us with more information:
- is the original cloud already 'shifted'? (do you have something else than (0, 0, 0) in the 'Global shift' field of the cloud)
-  do you have maybe a message in the console about the management of the Global Shift after you close the Align tool?

And if you can provide us with a sample cloud and the coordinates of the 4 points you define, that would be awesome.

Thanks

**Comment by Yourbee** [comment]
> Can you provide us with more information:
> 
> * is the original cloud already 'shifted'? (do you have something else than (0, 0, 0) in the 'Global shift' field of the cloud)
> * do you have maybe a message in the console about the management of the Global Shift after you close the Align tool?
> 
> And if you can provide us with a sample cloud and the coordinates of the 4 points you define, that would be awesome.
> 
> Thanks

1. No, original cloud is not already shifted.
2. 2.12 beta has not, 2.11.3 has: 
![1](https://user-images.githubusercontent.com/10266225/150459727-d7619ab7-018a-4602-bfee-da8a5d6f3e52.png)
![2](https://user-images.githubusercontent.com/10266225/150459734-9c4b1b94-d836-4d1b-be83-097b563ae2ab.png)

test data:
[test point clouds.txt](https://github.com/CloudCompare/CloudCompare/files/7909979/test.point.clouds.txt)
pick any 4 points, align them to 
[align points.txt](https://github.com/CloudCompare/CloudCompare/files/7910115/align.points.txt)

**Comment by dgirardeau** [comment]
Thanks. I was able to reproduce the issue!

I'm working on it...

**Comment by dgirardeau** [comment]
Ok, that should be fixed now! You can try the latest 2.12.beta version.

Thanks again for the feedback.
