### ISSUE TITLE
open cloudcompare.exe 0xc000007b error!

### ISSUE THREAD

**Issue by 155cannon** [CloudCompare/CloudCompare#1578]
I install the CloudCompare_v2.11.3_setup_x64.exe. My OS is Win10 64. First I open the cloudcompare.exe ,then "no msvcp120.dll and msvcr120.dll" cannot open the cloudcompare.exe. I copy msvcp120.dll and msvcr120.dll from other PC to the system32 folder. It has the new 0xc000007b error! 
How to solve the problem?

**Comment by dgirardeau** [comment]
Instead of manually copying these DLLs, you should instead install the 'Visual C++ 2013 Redistributable Package (64 bits)':
https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by 155cannon** [comment]
You are awesome ! @dgirardeau
