### ISSUE TITLE
cannot directly copy characters on software interfaces, such as the Properties panel

### ISSUE THREAD

**Issue by 155cannon** [CloudCompare/CloudCompare#1584]
Thanks for the great software. 
I find it impossible to directly copy characters on software interfaces, such as the Properties panel. I'm using the cloudcompare to do some annotation work for point cloud deep learning and would love to be able to directly copy the characters on the Properties panel. Expect future version to add the ability to directly copy characters from the Properties panel.

**Comment by chenmu1204** [comment]
有能直接导出属性面板参数的方法吗？

**Comment by 155cannon** [comment]
> 有能直接导出属性面板参数的方法吗？

鼠标点击属性面板后，直接按键盘Ctrl+C可以复制
