### ISSUE TITLE
Why is the point cloud loaded WGS84 by cloudcompare rendered as a vertical strip？

### ISSUE THREAD

**Issue by Lshanny** [CloudCompare/CloudCompare#1585]
![image](https://user-images.githubusercontent.com/39947011/151127601-a6366839-7bed-4299-8c7b-a6e82f53d6c5.png)
like this

**Comment by dgirardeau** [comment]
Ah, that's the classical issue where your coordinates are (probably) in non-cartesian coordinates. Typically X and Y are angles (in degrees) while Z is in metric coordinates, hence with much larger values. Once displayed in all metric-coordinates, it appeares as an elongated cloud...
