### ISSUE TITLE
Error opening SHP file with "Polygon (MultiPolygonZ)"

### ISSUE THREAD

**Issue by ruslo** [CloudCompare/CloudCompare#1586]
CloudCompare reports this error while trying to open the `*.shp` file with `Polygon (MultiPolygonZ)` (without M) geometry:

```
[SHP] Shape 1072145817 has an invalid shape code (1303204527)
```

I'm not experiencing any problem while opening the same `*.shp` file with `Polygon (MultiPolygonZM)` (with M) geometry.

I've checked the source code, and it seems for both geometries, the type is set to `POLYGON_Z	= 15`:
- https://github.com/CloudCompare/CloudCompare/blob/v2.11.3/libs/qCC_io/ShpFilter.cpp#L67

And `HasMeasurements` method will return `true` always:
- https://github.com/CloudCompare/CloudCompare/blob/v2.11.3/libs/qCC_io/ShpFilter.cpp#L128-L145

Does it seem that logic for whether M is present or not should be different? Any hints for fixes are welcome.

Both files are opening fine in [QGIS](https://github.com/qgis/QGIS).

Attaching `*.shp` samples: [arrows.zip](https://github.com/CloudCompare/CloudCompare/files/7948647/arrows.zip)

 - CC Version: 2.11.3
 - OS & Version: Ubuntu 18.04
 - Graphics card: GeForce GTX 880M
 - Qt Version: 5.12.9

**Comment by dgirardeau** [comment]
In the official documentation I have (https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf), I don't see a "PolygonZM" shape:
![image](https://user-images.githubusercontent.com/2735509/151328108-fa8810bd-3365-485c-b1cb-20118a2dbc3f.png)

And the "PolygonZ" is actually a "PolygonZM":
![image](https://user-images.githubusercontent.com/2735509/151328369-c1dfd62e-19c1-4151-81d3-e6788b95ed1f.png)

Where do these "PolygonZ-With-No-M" come from? Is it a new version of Shapefiles?

**Comment by tmontaigu** [comment]
As @dgirardeau said, there is nothing called `PolygonZM` in the specification there are  `Polygon`, `PolygonM` and `PolygonZ` where `PolygonM = Polygon + M values` and `PolygonZ = Polygon + Z values + M Values`.

However it is true that there is probably a problem in CloudCompare's implementation as when I did it, I thought the `M` values were mandatory (so always present even if it meant 0 / NO_DATA filled) however its not the case, the M values are optional and so the array written in the file can be empty.

So what I think happens with your file is that we see shapes of type `PolygonZ` we read the M values no matter if they are actually there, for at least one of the PolygonZ in the file, the M values are not present which mean that from this shape and onwards we are out of sync resulting in your error.

**Comment by dgirardeau** [comment]
How do you know that the M values are there or not?

**Comment by ruslo** [comment]
> Where does this "PolygonZ-With-No-M" shape come from? Is it a new version of Shapefiles?

To be honest, I don't know. I'm using GDAL to generate the shapefile with geometry type `wkbPolygon25D`:
- https://github.com/OSGeo/gdal/blob/bb19b0f20328a3d6673fc31c7cedaa7788bcebdd/ogr/ogr_core.h#L454

Also, on the Wikipedia page, I see that M is optional for PolygonZ = 15:
- https://en.wikipedia.org/wiki/Shapefile

> Mandatory: MBR, Number of parts, Number of points, Parts, Points, Z range, Z array
> Optional: M range, M array

**Comment by tmontaigu** [comment]
Each shape is preceded by a small header containing its type (which must be the same type as the one written in the header as all shapes in a shapefile have to be identical) and a size, by using the size and information like number of points in the shape you can guess if it contains M values or not.

**Comment by dgirardeau** [comment]
I'll try to do something similar then

**Comment by ruslo** [comment]
> Here is PR: #1588

> CC Version: 2.11.3

I've cherry-picked the https://github.com/CloudCompare/CloudCompare/commit/3c08435aec5f0a6f6194b65a1522f05303ab6d1a into 2.11.3, and now both `*.shp` files with M and without M open fine for me. Thanks!
