### ISSUE TITLE
Default naming after segmentation

### ISSUE THREAD

**Issue by eiffelbastin** [CloudCompare/CloudCompare#1587]
can the default naming function of point clouds after segmenting a point cloud (eg. Point_Cloud_XYZ.segmented) be turned off ??
and make CC prompt to ask for the new name of the segmented part
![Screenshot 2022-01-27 152801](https://user-images.githubusercontent.com/83037376/151336410-29e08b3e-1d0c-4d01-a132-a4d81b416fe5.png)

**Comment by dgirardeau** [comment]
I'm sure people will rant a lot if we display a popup each time 😅 

I guess it would be simpler to have an option to override the default '.segmented' suffix ... but you'll need to find a motivated dev to add this option I guess.

**Comment by ryukisai** [comment]
Good idea!
I agree with Daniel, too many popups are really bothering and not a streamlined way.
Maybe we could add 2 fields on the segmentation toolbar to optionally edit the suffixes?

My point of view (highly subjective and dependent on my workflow) is that i’d love to be able to keep the source cloud name as is (what i "keep"), and define a custom destination cloud for excluded/selected points. It’s even more complicated to implement though.

**Comment by Hilarius86** [comment]
I gave this issue a go.
Options button in the Graphical Segmentation Toolbar, a GearIcon.
![SegmentationToolbar](https://user-images.githubusercontent.com/16589816/172020047-f2e56141-287b-4f10-bcae-3caf43362746.PNG)

Options Dlg with 2 input possibilities, can be left empty for original name.
![segmentationOptions](https://user-images.githubusercontent.com/16589816/172020056-afbf0a7f-1c7a-471e-b036-fbb83834737d.PNG)

Implementation with a QSettings object.

@dgirardeau If this seems reasonable, I will prepare a PR.

**Comment by ryukisai** [comment]
Awesome [Hilarius86](https://github.com/Hilarius86), thanks a lot for your time!

**Comment by dgirardeau** [comment]
Ah yes, @Hilarius86 , don't hesitate to make a PR!
