### ISSUE TITLE
[Feedback] Step3 in BUILD.md

### ISSUE THREAD

**Issue by hiroyuki-sato** [CloudCompare/CloudCompare#1593]
Hello, developers.

This proposed instruction change may help for building CloudCompare on Linux.
I thought that step3 can skip on Linux. What do you think?

[BUILD.md](https://github.com/CloudCompare/CloudCompare/blob/master/BUILD.md#3-cmake-configuration)

## Current

```
# Windows
mkdir build & cd build
cmake -DCMAKE_PREFIX_PATH=C:\Qt\5.15.2\msvc2019_64 ..

# macOs
mkdir build && cd build
cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt@5 ..
```

## Proposed change

Add Linux part.

```
# Windows
mkdir build & cd build
cmake -DCMAKE_PREFIX_PATH=C:\Qt\5.15.2\msvc2019_64 ..

# macOs
mkdir build && cd build
cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt@5 ..

# Linux
mkdir build && cd build
cmake ..
```

Best regards.

**Comment by tmontaigu** [comment]
yes the last step, the "install" step is now optional (since 03e7af8dee6cb26180bb89812ab678f3bbaec5e7) in order to build cloudcompare, but if you want to properly install the cloudcompare you just built it is required.

And if we remove it, then its very likely people  will come and ask how to install once build is done, so for exhaustivity it should be kept

**Comment by hiroyuki-sato** [comment]
Hello, @tmontaigu. Thank you for your reply.

My feedback was about step3. Step3 executes `cmake ..`.
The current document shows an example of macOS and Windows.
And It doesn't exist Linux example. So I skip step3 and execute `cmake --build .` without `cmake ..`. 

That's why, I proposed to add the following line into **step3**.

```
# Linux
mkdir build && cd build
cmake ..
```

Best regards.

**Comment by tmontaigu** [comment]
Ah yes sorry I read to fast, indeed this could be added

**Comment by hiroyuki-sato** [comment]
Hello, @tmontaigu. Thank you for your reply. I created #1595

**Comment by dgirardeau** [comment]
I approved.
