### ISSUE TITLE
Add "X", "Y", "Z" label for Trihedron.

### ISSUE THREAD

**Issue by hackery98** [CloudCompare/CloudCompare#1597]
Add "X", "Y", "Z" label for Trihedron.
![图片](https://user-images.githubusercontent.com/6083117/152943878-73b6a17e-51f7-4133-b5a4-e44334a349a7.png)
I'm not sure if adding these labels is necessary.
![图片](https://user-images.githubusercontent.com/6083117/152944873-a63f791d-bcc9-443e-8719-89ff28c2e677.png)

**Comment by dgirardeau** [comment]
On my side it looks like that:
![image](https://user-images.githubusercontent.com/2735509/152957103-d1339e7d-9ff0-41dc-91aa-1efabeb030b2.png)

**Comment by dgirardeau** [comment]
I wonder if we could be smarter on the positioning of the letters...

**Comment by hackery98** [comment]
> I wonder if we could be smarter on the positioning of the letters...

QFont font("Calibri", 8, QFont::Thin);
![图片](https://user-images.githubusercontent.com/6083117/152963980-cfd84868-7581-477c-9da9-bbc8f3030dae.png)
QFont font("Calibri", 9, QFont::Thin);
![图片](https://user-images.githubusercontent.com/6083117/152964254-cb6df9e7-d5eb-43a5-84d5-e6e738606baa.png)
QFont font("Calibri", 10, QFont::Thin);
![图片](https://user-images.githubusercontent.com/6083117/152963454-160ba42c-2edf-4e68-b7da-5bf28c575c68.png)

I'm going to take a while to see how to make the text and coordinates fit when rotated.   novice -_-

**Comment by dgirardeau** [comment]
Yes, I was thinking about placing the letter on the right side of each line so as to not be hidden / overlapping

**Comment by hackery98** [comment]
![图片](https://user-images.githubusercontent.com/6083117/152975203-045e4f7e-681d-4331-a1f5-7c3b7d4333d0.png)
Sometimes The lettters are overlapping.

After reducing the line width, it looks better
![图片](https://user-images.githubusercontent.com/6083117/152975823-25f60542-606d-4375-9473-5a4f650da3dc.png)
![图片](https://user-images.githubusercontent.com/6083117/152975852-c02b41dd-2acd-4b1a-96d0-1797f68c62c5.png)
![图片](https://user-images.githubusercontent.com/6083117/152975927-d3f02b5c-ab09-43b1-9583-e4d14129f4d0.png)
![图片](https://user-images.githubusercontent.com/6083117/152975963-a0a546d8-beec-4540-85b6-d689392f3cad.png)

**Comment by dgirardeau** [comment]
Hum, let me see if I can come up with something

**Comment by dgirardeau** [comment]
Ok, I think I've got something working (and not too complicated):
![image](https://user-images.githubusercontent.com/2735509/153090716-804a448d-ff7c-44fe-9417-a62dcb6d9110.png)

**Comment by dgirardeau** [comment]
See 9ae9d5d7290953482257812775ae8dd8972dd272

**Comment by hackery98** [comment]
> See [9ae9d5d](https://github.com/CloudCompare/CloudCompare/commit/9ae9d5d7290953482257812775ae8dd8972dd272)
![图片](https://user-images.githubusercontent.com/6083117/153107883-b52c50dd-5781-4672-8b1b-2ec62c76b26f.png)
It's great! Thanks.
