### ISSUE TITLE
Unintentionally change spinbox's value in "Properties" scroll area.

### ISSUE THREAD

**Issue by hackery98** [CloudCompare/CloudCompare#1600]
When I scroll "Properties" widget, unintentionally change spinbox's and comboBox's value in "Properties" scroll area.

Solutions:

**First,**  install EventFilter 'FilterMouseWheelNoFocusEvent' for spinbox and comboBox to avoid such mistake.

FilterMouseWheelNoFocusEvent:  ignore MouseWheel event when the widget has no current focus.

**Second,** add m_lastFocusItemRole to  record which widget's value changed.  
Then using it to setFocus the widget in ccPropertiesTreeDelegate::updateModel(). 
 so you can continuous scroll the spinbox's value as before.

here is the main code: is that ok?
![图片](https://user-images.githubusercontent.com/6083117/153350761-84adbb59-c113-4ef3-956d-964a9c0c9be9.png)

![图片](https://user-images.githubusercontent.com/6083117/153350715-41590002-fa46-422a-87b3-7bab671a1775.png)

![图片](https://user-images.githubusercontent.com/6083117/153350859-22766cc4-edb3-403e-a3fd-4a423fb43cb6.png)

**Comment by tmontaigu** [comment]
Closing because #1602 was merged
