### ISSUE TITLE
2D label name is shown in bottom left of the display.

### ISSUE THREAD

**Issue by SchmidL** [CloudCompare/CloudCompare#1608]
**Describe the bug**
The label name of a 2D label is shown in the bottom left of the display, instead at the label origin.

**How to reproduce**
1. Create a label via the "point picking" tool and save it in the popup menu.
2. Enable "show name (in 3D)" in the properties menu. 

**Expected behaviour**
the name is displayed at the origin or in the vicinity of the picked point

**Additional context**

**Your environment**
 - CC Version: v2.12 beta (64bit)
 - OS & Version: Windows 10 Enterprise LTSC 1809
 - Graphics card: Nvidia

**Comment by SchmidL** [comment]
No bug. misinterpretation of the naming

**Comment by SchmidL** [comment]
Not directly related but this caused confusion. 
In my opinion, are the effects of the properties menu are not related effect in the viewer.
Examples:
- when I disable the legend, then the name disappear but the information in the box stays
- when I disable the name in 3D, then the button left text is gone, but not the text directly attached to the location
![lables_cc](https://user-images.githubusercontent.com/9334090/156749503-08fe6695-f5b3-4e64-9e8e-2911b8413669.png)

Maybe it's just me misinterpreting the menu, but for me, it's not intuitive.
.

**Comment by dgirardeau** [comment]
Ah, I think there's still a bug here, as the 'Show name (in 3D)' option should display the name of the entity at the center of the bounding-box. But for a label, it doesn't make sense, and this option should probably not even be visible... I'll try to fix that.

**Comment by dgirardeau** [comment]
Ok that's fixed (e7d889588819722252ec515a7c6952803f24e2a1). Entities that don't have a valid bounding-box (such as labels) won't have the 'Show name (in 3D)' option visible anymore in their properties. And this option won't have any effect of course.

Thanks for the feedback.
