### ISSUE TITLE
Qt fusion style makes  ui more tidy  on macOS

### ISSUE THREAD

**Issue by hackery98** [CloudCompare/CloudCompare#1610]
Hi, guys, I found Qt fusion style makes  ui more tidy  on macOS 12.2.1.

can we add it?   `QApplication::setStyle(QStyleFactory::create("fusion"));`

before
![image](https://user-images.githubusercontent.com/6083117/157871165-6b96c50b-5e5f-4a99-9a30-db3172a41a0c.png)
after
![image](https://user-images.githubusercontent.com/6083117/157871186-c35a72ae-32df-4c2f-bcf0-da72568a22dc.png)

**Comment by dgirardeau** [comment]
Ok, I added a new options in the 'Display > Display settings' dialog to select the application style:
![image](https://user-images.githubusercontent.com/2735509/158014798-98d35020-8280-4977-87e3-0b34c1f73e32.png)

This will be available in the next release.

**Comment by hackery98** [comment]
That's great! Thanks.
