### ISSUE TITLE
When compiled with vs2022,pulled errors

### ISSUE THREAD

**Issue by davidaio** [CloudCompare/CloudCompare#1614]
**Describe the bug**

**How to reproduce**

**Expected behaviour**

**Additional context**

**Your environment**
 - CC Version (or git hash/tag):
 - OS & Version:
 - Graphics card: 
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
You could at least paste the error messages, don't  you think?

**Comment by davidaio** [comment]
Sorry about that!
When i compiled with the vs2022,it can't compiled the ALL_BUILD file and got the _cloudcompare.exe_.There were lots of errors such as LNK2001\2002\2019 , etc.（I followed the tutorial of BUILD.md.But i failed.The picture shows the error.）








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Daniel ***@***.***&gt;; 
发送时间: 2022年3月19日(星期六) 晚上7:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CloudCompare/CloudCompare] When compiled with vs2022,pulled errors (Issue #1614)





 
You could at least paste the error messages, don't  you think?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by davidaio** [comment]
Dear administrator
Excuse me,i want to use the e-mail adress ***@***.***'(the right adress i always use) to register account on the Cloudcompare.org,but it always paste the error&nbsp; 'Please note that you will need to enter a valid email address before your account is activated. You will receive an email at the address you provide that contains an account activation link.'So what's wrong with it?
Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CloudCompare/CloudCompare"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月19日(星期六) 晚上7:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CloudCompare/CloudCompare] When compiled with vs2022,pulled errors (Issue #1614)





 
You could at least paste the error messages, don't  you think?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dgirardeau** [comment]
Hi,

Sorry I can't see the list of link errors (there's no image, maybe it would be better to paste it directly on github instead of replying by email?).

That's generally an issue with the Qt version you use. And of course I don't know if all the 3rd party libraries you are using are compatible with VS2022? Have you tried with VS2017 or VS2019? Make sure also that Qt has the right architecture (64bits).

**Comment by dgirardeau** [comment]
> Dear administrator Excuse me,i want to use the e-mail adress ***@***.***'(the right adress i always use) to register account on the Cloudcompare.org,but it always paste the error&nbsp; 'Please note that you will need to enter a valid email address before your account is activated. You will receive an email at the address you provide that contains an account activation link.'So what's wrong with it? Thanks!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CloudCompare/CloudCompare" ***@***.***&gt;; 发送时间:&nbsp;2022年3月19日(星期六) 晚上7:02 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [CloudCompare/CloudCompare] When compiled with vs2022,pulled errors (Issue #1614) You could at least paste the error messages, don't you think? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Can you send this message by email to admin[at]cloudcompare.org? (replace [at] by @). Otherwise I can't see the email address.
