### ISSUE TITLE
Internal error: object has no parent

### ISSUE THREAD

**Issue by ruslo** [CloudCompare/CloudCompare#1615]
The next error message appears after two clouds merged:

```
[ccDBRoot::removeElement] Internal error: object has no parent
```

Two dummy point clouds:

```
> cat 1.txt 
1 1 1
2 2 2
```

```
> cat 2.txt 
3 3 3
4 4 4
```

Steps to reproduce:
- Open both in CloudCompare
- Select them
- Click `Merge multiple clouds`

Environment:
- CC Version (or git hash/tag): 541800c
- OS & Version: Ubuntu 18.04
- Qt Version (if compiling): 5.12.9

Error source code: https://github.com/CloudCompare/CloudCompare/blob/541800c958e52d0379d62ac6bbfecd099dc09829/qCC/db_tree/ccDBRoot.cpp#L488-L494

**Comment by dgirardeau** [comment]
Good catch!

I fixed the issue: c364b77a9f7c5f73204e3f3ae051204ba361e19c
