### ISSUE TITLE
octree getCellCodes() keeps crashing du to bad m_alloc

### ISSUE THREAD

**Issue by dagata-mining** [CloudCompare/CloudCompare#1616]
Hi,

I'm trying to implement a new cloud cleaning approach. However when I'm trying to get the cellCodes of my octree I keep getting an error on that function which seems to be a bad allocation memory error. I've tried using truncated codes, or even reducing the octree level to 1 but keep getting that error. The Is there another way to iterate through octree cells, I've looked for indexes approach but does not look promisin

```cpp
ccPointCloud* ccStichedImageViewer::cleanUnroll(float octreeSize)
{
	ccPointCloud* resultCloud = nullptr;
	//unique parameter: the octree subdivision level
	int octreeLevel = 3;
	assert(octreeLevel >= 0 && octreeLevel <= CCCoreLib::DgmOctree::MAX_OCTREE_LEVEL);

	//compute octree if cloud hasn't any
	ccOctree::Shared theOctree = m_unrolledCloud->getOctree();
	if (!theOctree)
	{
		theOctree = m_unrolledCloud->computeOctree();
	}

	if (!theOctree)
	{
		ccLog::Error("Couldn't compute octree!");
		return resultCloud;
	}

	float leafSize = theOctree.data()->getCellSize(octreeLevel);
	CCVector3 bbMin;
	CCVector3 bbMax;
	theOctree.data()->getBoundingBox(bbMin, bbMax);
	
	ccLog::Error(QString("leaf size %1").arg(leafSize));

	//New approach
	{
		CCCoreLib::DgmOctree::cellCodesContainer cellCodes;
		int OctreeNumber = theOctree.data()->getCellNumber(octreeLevel);
		cellCodes.reserve(theOctree.data()->getCellNumber(OctreeNumber));
		
		ccLog::Error(QString("Qty of cells %1").arg(OctreeNumber));
		// Get cell codes
		if (!theOctree.data()->getCellCodes(octreeLevel, cellCodes, false));
		{
			ccLog::Error("Couldn't fetch the list of octree cell indexes! (Not enough memory?");
			return resultCloud;
		}
		ccLog::Error("Passed");
		// Generate matrix
		.....
```

**Comment by dagata-mining** [comment]
Yes I get a correct cell number depending on the octreeLevel I put in.

**Comment by dgirardeau** [comment]
But what it this number?

**Comment by dgirardeau** [comment]
Oh sorry, you said that you had the issue even for level 1, so the number must be pretty low in this case ;)

**Comment by dagata-mining** [comment]
On level 3 its 56 with leaf size of 4.5m

**Comment by dgirardeau** [comment]
Can you try in debug mode maybe?

**Comment by dagata-mining** [comment]
But I'll try to use the octree directly from the pointCloud object instead of using the shared poiner

**Comment by dagata-mining** [comment]
Still getting this error if I use the point cloud directly
 
```cpp
if (!m_unrolledCloud->getOctree()->getCellCodes(octreeLevel, cellCodes, true));
or
if (!m_unrolledCloud.data()->getOctree()->getCellCodes(octreeLevel, cellCodes, true));
```

**Comment by dgirardeau** [comment]
Are you using CCCoreLib as a DLL or a static library? Have you kept the default compilation scheme? (on Windows or Linux by the way?)

**Comment by dagata-mining** [comment]
> Are you using CCCoreLib as a DLL or a static library? Have you kept the default compilation scheme? (on Windows or Linux by the way?)

Windows
and .dll

**Comment by dgirardeau** [comment]
There's no mix of DLLs? Are you compiling it yourself?

**Comment by dagata-mining** [comment]
> 
I'm using cmake to create a Visual Studio 2017 .sln 

I've also tried running this function:
int DistanceComputationTools::computeApproxCloud2CloudDistance() which is using the same function getCellCodes() and it is working properly...

**Comment by dagata-mining** [comment]
So,
I just bypassed the if statement and I got all the cellCodes needed, don't know what error the getCellCodes is catching but its returning all my data correctly... 

So instead of verifying memory with this:
if (!theOctree.data()->getCellCodes(octreeLevel, cellCodes, false));
I'm verifying by reserving memory for the cellCodes vector based on the number of cells at the octree level.
Its a temporary fix.. but its working. 
Anyways, thanks for the help!!
