### ISSUE TITLE
Implementing ccImage Export to .dxf export

### ISSUE THREAD

**Issue by dagata-mining** [CloudCompare/CloudCompare#1620]
Hi Daniel,

I'm trying to export images to .dxf format from a cloudcompare plugin. I've tried to follow qcad or librecad approaches but can't seem to find the correct approach for the last 2 days. My .dxf is exporting but no sign of images in autocad.

Based on this approach :   https://github.com/LibreCAD/LibreCAD/blob/master/librecad/src/lib/filters/rs_filterdxf.cpp#L1384

Code starting from: https://github.com/CloudCompare/CloudCompare/blob/master/libs/qCC_io/src/DxfFilter.cpp#L1002
 I've hardcoded a few parameters to make sure I was passing them correctly
```cpp
...		
//Writing the Objects Section
		dxf.writeObjects(*dw);

		int handle = dxf.writeImage(*dw, DL_ImageData(std::string(""), 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 3141, 7866, 50, 50, 0),
			DL_Attributes(qPrintable("0"), DL_Codes::bylayer, -1, "BYLAYER", 1.0));
		dxf.writeImageDef(*dw, handle, DL_ImageData(qPrintable("C:/Users/Asus/Documents/shaft/BG_Image_001.png"),
                0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 3141, 7866, 50, 50, 0));

		dxf.writeObjectsEnd(*dw);

		//Ending and Closing the File
		dw->dxfEOF();
		dw->close();
	}
	catch (...)
	{
		ccLog::Warning("[DXF] DxfLib has thrown an unknown exception!");
		result = CC_FERR_THIRD_PARTY_LIB_EXCEPTION;
	}

	delete dw;
	dw = nullptr;

	return result;

#endif
}
```

**Comment by dgirardeau** [comment]
Have you tried to open the generated DXF file to see if its syntax is correct? (if you can maybe compare with a DXF file embedding images and that works with AutoCAD ?)

I'm thinking especially about the path? Can you use '/' characters? Or should it be '\\' maybe? (by the way I don't think you need to call qPrintable() since you already have a C-style string).

**Comment by dagata-mining** [comment]
[Updates]
So when I tried qcad export first the .dxf in AC1015 was working with images, but this was in the non-community version and they have a better export library that is non-opensource, when using the community version it was not working and neither with librecad. I also tried building cloudcompare with libdxfrw, but it didn't work either when exporting. 
So I started to do comparison between .dxf files created by autocad and the ones generated by the dxflib, and there is a few things missing in the dxflib version.
IMAGEE_DEF_REACTOR
IMAGE_DICT
RASTER_VARIABLES
Anyways I'll be rewritting some part of the dxflib based on the https://github.com/mozman/ezdxf python lib and this https://github.com/haplokuon/netDxf lib in c#
I'll PR when it will finally works

**Comment by dagata-mining** [comment]
So after 1 week of trying libdxfrw was not properly supporting the images and neither did the dxfLib. Tried to use libredwg and build it, but it does not support MSVC building due to C99 convention and a poor msvc compiler (even 2022 could not compile, just minGW and clang but the libs were not compatible). So after multiple approaches, I'm building an api with the netDXF lib in order to communicate and make it work. But before I finish I'm using yaml files to parse the information to the .dxf executable. netDxf is quite a robust and up-to-date library and I think that could be an interesting approach for further dxf export implementation.
