### ISSUE TITLE
System error - MSVCP120.dll missing

### ISSUE THREAD

**Issue by Dezorian** [CloudCompare/CloudCompare#1621]
Just got a new laptop with Windows 11 and installed CloudCompare v2.11.3 (stable). When trying to start the application I get a System Error saying: 

_"The code execution cannot proceed because MSVCP120.dll was not found. Reinstalling the program may fix this problem"._

So I search for the file. It seems that W11 now has the file named msvcp120_clr0400.dll.

After I duplicated the file and renamed that to msvcp120.dll it gave me the same error for msvcr120.dll. That one is now also called msvcr120_clr0400.dll

Did the same duplicate rename action and now CloudCompare just works.

**Comment by dgirardeau** [comment]
I believe you should install the Visual Studio 20013 Redistributable package (64 bits).

**Comment by Dezorian** [comment]
Thanks, that works as well :)
