### ISSUE TITLE
Display sum of points in selected clouds

### ISSUE THREAD

**Issue by ryukisai** [CloudCompare/CloudCompare#1624]
When one cloud is selected, CC displays its amount of points in the Properties section.
When two or more clouds (or a group of clouds) are selected, this info is not displayed.
It would be quite useful to display the total points amount of points in all selected clouds (or groups).
Thanks!!

**Comment by dgirardeau** [comment]
Hi,

For that, just select multiple point clouds or their common parent folder. Then, right-click and choose the first option: 'Information (recursive)'

![image](https://user-images.githubusercontent.com/2735509/162017924-3de3c147-0b09-42bc-9c71-1c3776baac77.png)

**Comment by ryukisai** [comment]
Ok thanks Daniel for that. I still think that having all these data in the properties panel directly would be helpful / better, but i understand that this is not a priority / strictly needed. Cheers!
