### ISSUE TITLE
Scissors Tool Display

### ISSUE THREAD

**Issue by LarryKu** [CloudCompare/CloudCompare#1625]
In version 2.11.3, when a shapefile outline is used to segment a selected lidar in the DB tree with the Scissors tool, the lidar was hidden so you could see the shapefile outline and draw an segment around it. In 2.12, the lidar is always displayed and the shapefile outline is hidden. Either hide the lidar, or draw the shapefile outline on top of the lidar so it is visible.

**Comment by LarryKu** [comment]
Found a solution. Uncheck the visibility of the lidar root in the DB tree, select the lidar child, then select the Scissors tool. That displays the shapefile outline with out the lidar being displayed, the same is version 2.11.3.

**Comment by dgirardeau** [comment]
I guess that the shapefile outline is lower than the lidar points and that's why you couldn't see it 'below' the cloud?

**Comment by dgirardeau** [comment]
In this case, another way around would be to segment the lidar cloud by looking at it from the opposite side? 😅

**Comment by LarryKu** [comment]
Closed this issue.
