### ISSUE TITLE
A Saved Point Cloud Does Not Locate To The Same Position As The Original

### ISSUE THREAD

**Issue by LarryKu** [CloudCompare/CloudCompare#1626]
**Describe the bug**
When a point cloud is saved and then reloaded, it is offset from the original.

**How to reproduce**
1. Load LAZ/LAS tile(s) and accept the default "Global shift/scale. Merge and filter classifications as desired.
2. Select the point cloud in the DB tree and click the save button.
3. Set "Save as type:" to "LAS cloud (*.las, *.laz)".
3. Choose Original Resolution when prompted.
4. Click the "Save" button.
5. Drag and drop the saved LAS file into the main window and accept the default "Global shift/scale".
6. When displayed the saved LAS does not overlay the original point cloud, but is shifted. In my case above and to the right (see attached images).
7. Click on the original point cloud and note the "Shifted box center".
8. Click on the reloaded saved point cloud and note the "Shifted box center" values are not the same.

**Expected behaviour**
The saved point cloud should be located at the exact same position as the original. I verified that in version 2.11.3 the saved point cloud loaded at the same position as the original.

**Additional context**
Screenshots attached.

**Your environment**
 - CC version 2.12
 - OS: Windows 10 
 - Graphics card: Gigabyte GA-Z170MX-Gaming
 - 
![Original-Point_Cloud](https://user-images.githubusercontent.com/1071803/162102899-1becbb27-d19d-47f3-86dc-fc438fcbf474.jpg)
![Saved_Point_Cloud](https://user-images.githubusercontent.com/1071803/162102958-f7415af7-eef5-4977-8be3-e7586a760b86.jpg)

**Comment by dgirardeau** [comment]
So the problems seem different to me.

@LarryKu: make sure the applied shift is the same in both cases. Sometimes the one suggested by CC might not be the same as the previous one

@copyme: do you apply any processing before exporting to E57?

**Comment by LarryKu** [comment]
I checked that shift for both and they were identical.

**Comment by dgirardeau** [comment]
On your example above, can you select the clouds and show what the 'Global shift' entry is? (below 'Cloud')

**Comment by LarryKu** [comment]
Here is the info you requested
![SavedShift2](https://user-images.githubusercontent.com/1071803/162608144-4a4b69bf-95dd-4752-8b78-842b5a2e5180.jpg)
![OriginalShift2](https://user-images.githubusercontent.com/1071803/162608148-a86f0e74-295b-41c6-87a0-0e8f7c3cf3a5.jpg)
.

**Comment by LarryKu** [comment]
The top one is the saved lidar, the bottom is the original.

**Comment by dgirardeau** [comment]
Ok, so that's what I thought. Look at the Y coordinate of the global shift, it's not the same.

**Comment by LarryKu** [comment]
I messed the y shift difference of 100. What is the solution. If I load both in CC 2.11.3, They overlay as expected.

**Comment by dgirardeau** [comment]
Just make sure the right shift is applied when loading the file. For LAS files, the "las offset" may be used by default, even if the previous shift is different but would also work. You should normally have multiple choices in the "Global shift" dialog (something like 'Input' and 'Previous input').

I believe the issue comes from the "las offset" chosen by CC when saving to a LAS file, in the specific case where no las_offset was defined in the original file (i.e. either the LAS file had no 'las offset' defined, or it was not a LAS file). In this case CC was using the min corner of the bounding box, while the suggested global shift might be slightly different. I tried to fix that to avoid confusion. This will be available in the 2.12.1 release (that should come soon).

**Comment by LarryKu** [comment]
I redid the import of the original and saved point clouds and made certain the input was set to "Previous Input" for the saved point cloud. This overlayed the original as expected. What I noticed when I load the saved point cloud, the input defaults to "Input". That is when I get the offset. 

In CC 2.11.3, when the saved point cloud is loaded, it defaults to "Last input" and It always loaded correctly. That appears to be the difference between 2.11.3 and 2.12.

**Comment by LarryKu** [comment]
Closed/

**Comment by copyme** [comment]
> So the problems seem different to me.
> 
> @LarryKu: make sure the applied shift is the same in both cases. Sometimes the one suggested by CC might not be the same as the previous one
> 
> @copyme: do you apply any processing before exporting to E57?

I have registered the faulty set with another. For working versions I use bin format and I only export to e57 at the last stage. Other sets in the whole project were exported correctly.

**Comment by copyme** [comment]
I will review your answers later on.

**Comment by laurieuasinc** [comment]
Hi all,  This should still be open.  There is a persistent problem with 2.12.2.  When opening files, if you click No to the suggested offset, it applies it anyway.  If you explicitly type 0,0,0, it is positioned correctly.  To test, open two coregistered files, selecting No for the shift.  They will not align (assuming bounds are different).  If you do that again, but type 0,0,0, they will load correctly.  This was found and reproduced in 2.12.2.  It does not exist in 2.11.0 which was used as a back check.

**Comment by laurieuasinc** [comment]
Also, it does not KNOW that it applied the shift.  It shows 0,0,0 as the shift even though it has applied the defaults.

**Comment by dgirardeau** [comment]
Resolved in https://github.com/CloudCompare/CloudCompare/issues/1659
