### ISSUE TITLE
Align two clouds by picking with less than 4 pairs of points

### ISSUE THREAD

**Issue by rvouilloz** [CloudCompare/CloudCompare#1629]
I have two photogrammetric pointclouds built with Meshroom, of two adjoining rooms in a flat.
I have placed targets (CCTag3) and so I have some very accurate known points.
Unfortunately I only have two such points in common betwenn these two rooms. Why is there this limit of four pairs of points with the _Align by picking_ Tool? Geometrically an alignment by just two pairs of points seems possible to me.

Thanks

**Comment by dgirardeau** [comment]
That would only be possible in 2D (if you know for instance that the ground is perfectly horizontal in both rooms).
 
For 3D alignment, you need at least 3 points (and not aligned by the way).
