### ISSUE TITLE
Save options differ between selection modes

### ISSUE THREAD

**Issue by runxel** [CloudCompare/CloudCompare#1632]
**Describe the bug**
I have pointclouds were I will fit planes to some areas and I will export them seperately as an extra reference for my CAD programm later on.
Saving `.stl`s works fine if I select the planes by myself; using the auto-select dialog will however limit the options massively for no apparent reason.

**How to reproduce**
1. Rightclick on group
2. Click "Select children by type"
3. Type: "Plane", hit enter
4. Save the selected planes
5. Only options now are `dxf`, `shp`, `bin`, and `fbx`.

**Expected behaviour**
All saving options should be available (like `stl`, which is no longer an option).

**Additional context**

n/a

**Your environment**
 - CC Version (or git hash/tag): v2.12.0
 - OS & Version: Win 10 21H1
 - Graphics card: nVidia Geforce GTX 960M
 - Qt Version (if compiling): n/a

**Comment by dgirardeau** [comment]
The reason is simple: the STL format can only save one mesh at a time. If you select a mix of meshes, clouds and/or other entities, CC wouldn't know what to do.

So CC only let you choose the file formats that can save your whole selection.

Mind that you can make a smart selection by right clicking on a node of the DB tree and select the 'Select children by type and/or name' option.

**Comment by runxel** [comment]
Ah yes, makes total sense. Don't know why I had perceived it would be possible to save multple meshes at once as `.stl`, but probably because CC uses the very weird `ctrl` instead of usual `shift` as modifier for multi-selection. Force of habit!... 🤦‍♂️
Thanks anyway!

**Comment by dgirardeau** [comment]
'ctrl' is for selective multiple selection, and 'shift' is for contiguous multiple selection... just as in the Windows explorer for instance, and many other programs ;).

And that's not specific to CC, as that's built-in in Qt actually.

**Comment by runxel** [comment]
Sure, you're right. Should have specified "selecting _in the 3 view_, and not in the DB tree". (where a shift click will place a label, not do multi-selection...)
I just realized how much context sensitive selection can be. Of course, if there is a kind of pre-sort, or mode which implies a sense of order, ctrl and shift will be different in how they work – and make brilliant sense (I mean, in the explorer I use it all the time without thinking about it). 
But if there is no order (like geometry floating in a viewport), a difference between contigous and selective makes no sense, there will only be the latter. And now my remark might make more sense for you, because all CAD programms I've touched so far used  shift as a multi-select modifier, at least I far I can remember. Force of habit! 😄

**Comment by dgirardeau** [comment]
To make things even more confusing, we use 'ALT + right mouse button' to draw a rectangle over the entities you want to highlight directly in the 3D view. That would be the closest thing we have to the concept of 'contiguous' selection.
