### ISSUE TITLE
Minor error in Simple Binary File (SBF) documentation

### ISSUE THREAD

**Issue by fwrite** [CloudCompare/CloudCompare#1637]
The documentation on the Simple Binary File contains a minor mistake, that makes it very difficult to generate a compliant file. The documentation repeatedly lists `myfile.data.sbf` as the data file. This should be `myfile.sbf.data` (see [SimpleBinFilter.cpp](https://github.com/CloudCompare/CloudCompare/blob/b64aa418a46d9404fd9cf63db697e076af99e67c/plugins/core/IO/qCoreIO/src/SimpleBinFilter.cpp#L275)).

Furthermore, I found the file to be expected as big-endian, non-native on my platform. The following snippet might help (at least) python users to create the required header:
```python
struct.pack('>2BQH3d28x', 42, 42, no_pt, no_sf, offset_x, offset_y, offset_z)
```
Likewise, the format for points (and scalar fields) is `>f`.

The variables `p` and `s` in `myfile.sbf` behaved differently between versions. I expect this was due to them being integer in my experiment, instead of float/decimal.

As I do not have wiki-access, I can not apply these updates.

**Comment by dgirardeau** [comment]
Thanks for the feedback! I applied the corrections (see https://www.cloudcompare.org/doc/wiki/index.php/SBF).

If you think there are more things you want to fix, I can create an account for you (just send me an email to admin[at]cloudcompare.org).
