### ISSUE TITLE
Manual translation not stored in las export (global shift) in v2.12.1 (Kyiv). In v2.11.3 it was ok.

### ISSUE THREAD

**Issue by booleeny** [CloudCompare/CloudCompare#1639]
**Describe the bug**

If i do a manual translation Edit->Apply transformation -> Axis, Angle -> Translation parameters  and export the translated pointcloud  it is not stored in the *.las file. The export is not translated in version v2.12.1. That worked before in v2.11.3. That has to do with global shift settings.

**How to reproduce**
Steps to reproduce the behaviour - include images if relevant:
1. Open a las file (switch from Input to suggested, Preserve global shift on save is active) as refrence.
![2022-05-17 11_55_56-Global shift_scale](https://user-images.githubusercontent.com/19393195/168784796-f5b2dadd-2e97-4285-81c5-850321f1ed58.png)
2. Open a second las file that is somehow shifted (switch from input to Previous input in the dialogue, Preserve global shift on save is active)
![2022-05-17 11_58_18-Global shift_scale](https://user-images.githubusercontent.com/19393195/168785435-d5ec8aab-97bb-4331-bdb9-880c41592aac.png)
3. The first reference file and the second shifted file is opened as expected
![2022-05-17 12_01_23-CloudCompare v2 12 1 (Kyiv)  64-bit  -  3D View 1](https://user-images.githubusercontent.com/19393195/168786524-ca5da53f-dfee-4550-86de-79298616ff00.png)
4. Use Edit->Apply transformation -> Axis, Angle -> Translation parameters on the shifted file to align it with the first reference file
![2022-05-17 12_15_26-Apply transformation](https://user-images.githubusercontent.com/19393195/168788727-364687df-207d-495c-813c-046c410266ae.png)
Both files match on top of each other
![2022-05-17 12_16_18-CloudCompare v2 12 1 (Kyiv)  64-bit  -  3D View 1](https://user-images.githubusercontent.com/19393195/168788893-97f2b294-8210-494c-81c8-ae6bc7b04efe.png)
Save the translated file to *.las 1.4
![2022-05-17 12_17_17-Save file](https://user-images.githubusercontent.com/19393195/168789046-1eccfa37-0b29-431c-9692-4fb4589341ab.png)
5. Close CC, open it again and repeat step 1.
6.  Open the just saved and translated file. Nothing has changed
![2022-05-17 14_13_42-CloudCompare v2 12 1 (Kyiv)  64-bit  -  3D View 1](https://user-images.githubusercontent.com/19393195/168808280-b946199f-644f-4899-95ef-712e1b4e816d.png)

**Expected behaviour**
If i open the translated file I expect it to be translated. 

**Additional context**
Sometimes only the hight Z is shifted but not X + Y

### Data package for the reference and shifted pointcloud
https://www.transfernow.net/dl/20220517ogkOW1ow
valid until **24.05.22**

**Your environment**
 - CC Version (or git hash/tag): v2.12.1 Kyiv
 - OS & Version: Windows 10 Enterprise 64bit  Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz   2.71 GHz, 32,0 GB RAM
 - Graphics card: NVIDIA Quadro RTX 3000
 - Qt Version (if compiling): -

**Comment by booleeny** [comment]
Data reference and shifted Pointclouds
https://www.transfernow.net/dl/20220517ogkOW1ow
valid until **24.05.22**

**Comment by dgirardeau** [comment]
Thanks for the data, I was able to reproduce the issue. It seems the 'LAS 1.3/1.4' filter is indeed doing something strange!

**Comment by dgirardeau** [comment]
Ok I found the bug! The LAS 1.3 or 1.4 I/O filter was not handling properly the case when the Global Shift was different from the LAS offset (in the original LAS file). I fixed this: https://github.com/CloudCompare/CloudCompare/commit/8dc495ea862a1c2690695f217950db6238362a1c

I'll release the 2.12.2 version ASAP.

**Comment by dgirardeau** [comment]
The 2.12.2 version for Windows is now online!
