### ISSUE TITLE
Crash after Mesh_Smooth(Laplacian)

### ISSUE THREAD

**Issue by Spartacus1** [CloudCompare/CloudCompare#1644]
CloudCompare in any version and either in Windows (10) or macOS (Monterey), crashes after using Edit->Mesh->Smooth(Laplacian). Once in a while it does not crash at first try but as soon as we try to do the same operation in the same session, it will crash. The crash occurs while using the default values of 20 iterations and 0.2.

**Comment by dgirardeau** [comment]
I haven't been able to reproduce the issue. Could you maybe share with us the mesh file you use? (or by sending us an email to admin [at] cloudcompare.org)

**Comment by Spartacus1** [comment]
Hi dgirardeau

Of course. grab it from here https://u.pcloud.link/publink/show?code=XZP6vHVZtL24YsAOzrm6ajddX30j3pIxJciX
After import, I clone the mesh and then apply the Smooth(Laplacian) filter with default values. You might need a couple of tries to reproduce the issue since, sometimes, it does not happen. 
Cheers

**Comment by dgirardeau** [comment]
Ok, the crash was indeed related to the file (due to the fact that the number of per-triangle normals was smaller than the number of triangles - which is ok, but CC was not expecting that ;) ).

I'll try to release the 2.12.2 version quickly.

**Comment by Spartacus1** [comment]
Thank you so much. This is very common in flat and cropped models that come directly from Agisoft Metashape. I'll now be waiting for the 2.12.2 for macOS since this feature is very useful in my case.

**Comment by dgirardeau** [comment]
The 2.12.2 version for Windows is now online. You might have to wait a little bit for the macOS version to be ready...

**Comment by Spartacus1** [comment]
Great! Thank you so much. I'll be patient to wait :-)
Best regards
