### ISSUE TITLE
ICP RMS stored in logfile in command line mode

### ISSUE THREAD

**Issue by CatchmentSci** [CloudCompare/CloudCompare#1645]
When using CC in command line mode it appears that only a subset of the text displayed in the terminal is exported to the logfile. It would be great if the logfile could be expanded to include the final RMS of the alignment. This would enable the quality of the aligment to be queried when automating alignment using the command line. Thanks for considering this, and for all of your work on the software!

**Comment by dgirardeau** [comment]
Are you referring to the log file generated with the -LOG_FILE option? And the RMS of the -ICP command?

**Comment by dgirardeau** [comment]
Because with these options I can see:
[22:26:04] RMS: 0.216

(just make sure the -LOG_FILE option is at the beginning of the command, or at least before -ICP)

**Comment by CatchmentSci** [comment]
Hi Daniel, yes I was refering to the -log_file option and the -icp command. Your suggestion has resolved the issue I was having. I was placing the -LOG_FILE command towards the end of the statement whereas when I place it at the front it works well. Thanks for your advise on this
