### ISSUE TITLE
CCCoreLib has not find SimpleCloud.h when compile qCSF plugin

### ISSUE THREAD

**Issue by priseup** [CloudCompare/CloudCompare#1650]
** implementation of Cloud2CloudDist.cpp, Rasterization.cpp both include <SimpleCloud.h>, there no this file in https://github.com/CloudCompare/CCCoreLib , so compile qCSF error. i dont know how to get SimpleCloud.h？**

**Comment by dgirardeau** [comment]
Which version of qCSF are you using? Because CCCoreLib has been updated quite some time ago.

The latest version of qCSF can be found in the master branch of CloudCompare: https://github.com/CloudCompare/CloudCompare/tree/master/plugins/core/Standard/qCSF

**Comment by priseup** [comment]
the newest of master branch

**Comment by dgirardeau** [comment]
The code you are referring to is deprecated (it's inside a #else statement that shouldn't be compiled since it comes after a '#if 1' statement).

**Comment by priseup** [comment]
yes, i know. the #if 1 statement is very very slow(350M binary .pcd file costs 25min), so change to #else to get the time cost.

**Comment by dgirardeau** [comment]
Well, the code comments tell that the other code is slower... But if you want to use it, you'll have to make it compile ;)

**Comment by priseup** [comment]
it's tooooo difficult. qCSF is no almost no change from https://github.com/jianboqi/CSF. call CGAL is quick than #if 1. "we use CC_CORE_LIB --> potentially much faster" so want to test the CCCoreLib

**Comment by dgirardeau** [comment]
The default code '#if 1' is using CCCoreLib.

**Comment by priseup** [comment]
thank u for replay so detail..  i will test #if 1 again
