### ISSUE TITLE
Clipboard Paste & Trace Polyline keyboard shortcuts collision

### ISSUE THREAD

**Issue by the-mush** [CloudCompare/CloudCompare#1653]
**Describe the bug**
If I have the clipboard loaded with anything (well, I tried with images and text...) the "Trace Polyline" keyboard shortcut doesn't work. According to the changelog, the same key combination has been assigned to the "Paste from Clipboard" tool on `v2.12.0`, so I assume there must be a collision somewhere causing the first shortcut to stop working as soon as there is something on the clipboard. However, the "Paste from Clipboard" tool also only works while I have no cloud loaded in CC.

**A fix for now is to clear the clipboard** (if you want the Trace Polyline shortcut). On Windows 11, you can find it by going to `Settings` -> `System` -> `Clipboard` -> `Clear clipboard data`

**How to reproduce**

1. Open CloudCompare.
2. Copy some text to clipboard.
3. Press Ctrl + P. Paste from Clipboard dialogue shows up, close it.
4. Load a cloud.
5. Press Ctrl + P. Nothing happens.
6. Clear clipboard (on Windows 11, try method described above).
7. Press Ctrl + P. Trace Polyline tool opens. 

**Expected behaviour**
Please don't take away my beloved Trace Polyline shortcut 😅. I respect users of the `Save viewport as object` shortcut, but they are wrong!! We Tracers will not tolerate this aggression! ⚔️

**Additional context**
Long time fan of CC, love to help any way I can.

**Your environment**
 - CC Version (or git hash/tag): v2.12.0
 - OS & Version: Windows 11 Pro 21H2 OS Build 22000.708
 - Graphics card: AMD Radeon RX 6800 XT

**Comment by dgirardeau** [comment]
Good catch! I'll try to fix it as soon as possible.

(and no, I won't touch the Trace polyline shortcut ;) ).

**Comment by dgirardeau** [comment]
The code has been fixed: dc127f6a59c9af9b2996dc41d53d77d1cf20d30e

This will be available in the next 2.13.alpha release (soon).

**Comment by dgirardeau** [comment]
It's online now ;)

**Comment by the-mush** [comment]
Thy lord has spoken! Let the changelog account this victory for the Tracers.

Hail to the King!
