### ISSUE TITLE
Rasterize empty cell interpolation don't fill holes - linux issue

### ISSUE THREAD

**Issue by yotopo** [CloudCompare/CloudCompare#1658]
When rasterizing a point cloud, and want to fill the empty cell with the interpolation method, the result is an empty cell or fill  with the `empty cell value` like `fill with user specified value`

Error only on Linux, work fine on Windows 

**How to reproduce**
Edit -> projection -> Rasterize
Empty cells -> interpolate 

There are not the same options on both screenshots, but even with the same value, results are the same.

![Capture du 2022-06-08 10-41-18](https://user-images.githubusercontent.com/102863870/172585502-d9611efb-cbac-4123-b24d-6aa74817a12b.png)

On Windows environment, empty cells are fill with interpolate value :

![cc_w10](https://user-images.githubusercontent.com/102863870/172585748-c7cc0e28-58a0-48b6-b602-e6944b62532a.PNG)

**Your environment**
 - CC Version : 2.12.2
 - OS & Version: Archlinux

**Comment by dgirardeau** [comment]
Is it maybe related to the fact that this version of CC has been compiled without CGAL? (in which case we can't triangulate the cloud, hence we can't perform any interpolation...)

**Comment by kikislater** [comment]
Ok ! 
It was build with CGAL but ignored because CMakeLists changed from `-DCOMPILE_CC_CORE_LIB_WITH_CGAL=ON` to `-DCCCORELIB_USE_CGAL:BOOL=ON` 
This kind of things needs a special advise IMO

**Comment by yotopo** [comment]
latest release in archlinux with proper cmake options solve issue, Thanks @kikislater  for the latest build and tips!
