### ISSUE TITLE
Exporting local centroid while computing normals using cloudcompare

### ISSUE THREAD

**Issue by alexwangxiang** [CloudCompare/CloudCompare#1660]
Dear Daniel Girardeau-Montaut,
I'm using CloudCompare to compute local geometric features on point clouds, such as eigenvalues in radius nearest neighbourhood, and normal vectors. You implemented these functions in -OCTREE_NORMALS {type} {radius} and -FEATURE {radius} plugins in command line mode. I've read your source code, and see that the ComputeCloudNormals function uses CCCoreLib::DgmOctree data structure, while the ComputeGeomCharacteristic function uses ccOctree::Shared data structure. Both of these functions use the CCCoreLib::Neighbourhood class while computing local geometric features.
I notice that during the process of calculating local normals, we can access the local centroid of a point and its radius nearest neighbourhood, using Neighbourhood::getGravityCenter() function or  Neighbourhood::computeGravityCenter() function. And actually you called "G = getGravityCenter();" in functions Neighbourhood::computeLeastSquareBestFittingPlane() and Neighbourhood::computeCovarianceMatrix().
Now given a point cloud and a local radius, I want to export the local centriod of the radius nearest neighbourhood at every point, which is exactly "G = getGravityCenter();" while calculating normal vectors. How can I implement this idea? I don't want to compile CloudCompare in my computer although I have some experience compiling it. I want to use the .so shared library files in /snap/cloudcompare directly. Moreover, I want to know why does CloudCompare computes normal vectors of a point cloud so efficiently? I compared the result of CloudCompare and PCL, the result of the former is much better than that of the latter.
To my knowledge, CloudCompare doesn't have a plugin that exports the local centroid at every point. It's a little bit wierd since the CCCoreLib::Neighbourhood class already has a member variable "CCVector3 m_gravityCenter;" and two menbers functions "const CCVector3* getGravityCenter();" and "void computeGravityCenter();".
Yours,
Wang Xiang

**Comment by alexwangxiang** [comment]
Moreover, I noticed that in your slides on the Point Cloud Processing Workshop at Stuttgart, Germany, December 4-5, 2019, you mentioned that CloudCompare has too many users but the developers were barely enough. I am very interested in the CloudCompare software, and I would speak highly of it. I don't know if I can be a developer of this software? Can we discuss in detail about it exchange our personal contact informations? Thank you!

**Comment by dgirardeau** [comment]
Hi,

Well, I guess we don't export this centroid (G) simply because no one ever asked for it, and it didn't look an interesting output so far ;)

And sadly, I don't see how to export this new point cloud without modifying the code / recompiling it...

I would say: don't hesitate to modify the code ;). Especially since in your case it should be rather easy. And don't hesitate to make new contributions (via github).
