### ISSUE TITLE
QPCL_PLUGIN.dll  and QPCL_IO_PLUGIN.dll does not seem to be a valid plugin ?

### ISSUE THREAD

**Issue by hustlmh** [CloudCompare/CloudCompare#1662]
hi all, 
I git clone the CC source code and hope to compile it with some private plugins on the platform of windows. In order to compile the plugin related QPCL, I downloaded and installed the "PCL-1.12.1-AllInOne-msvc2019-win64.exe" in my windows where the PCL have been added to the system PATH for all the users by the install program.
While CMake outputs two warnings, no errors occur when compiling these 3 QPCL related plugins(qpcl, io and util PLUGIN)
However, CC reports “does not seem to be a valid plugin ” error "the specified module could not be found" when loading QPCL_PLUGIN.dll and QPCL_IO_PLUGIN.dll (please ref the figure)
<img width="1277" alt="截屏2022-06-20 下午1 33 11" src="https://user-images.githubusercontent.com/53802172/174531909-bc4cc2e1-b762-4100-8caf-1c2d2e698fa3.png">
<img width="1277" alt="截屏2022-06-20 下午2 41 01" src="https://user-images.githubusercontent.com/53802172/174540695-76d074c5-e2f8-4a20-87d7-239f7be9885e.png">

I don't know how to fix it .  
Could you give me some advices?

Thanks a lot!
Best Regards,
mh

My environment:
CMake 3.23.0
CC 2.12.1
Win10 x64 
VS 2019
Qt V5.12.2
PCL 1.12.1

**Comment by dgirardeau** [comment]
It's probably due to missing DLLs. All PCL dependencies (maybe in a 'bin' folder?) should be copied next to CloudCompare.exe.

You can use the Depency Walker tool to determine which DLL is missing exactly (just drag and drop the QPCL_PLUGIN.dll file on it).

**Comment by dgirardeau** [comment]
Yes, because I pay attention to compile the plugin with static libraries and not dynamically linked ones (to reduce the number of DLLs that needs to be shiped next to CloudCompare.exe).

**Comment by dgirardeau** [comment]
No it really means to use statically linked libraries (with all the code inside, and not associated to dynamically linked components such as DLLs). I compile PCL myself so as to build it 'static'.
