### ISSUE TITLE
Segmentation tool, cuts ahead and behind

### ISSUE THREAD

**Issue by TokyoWarfare** [CloudCompare/CloudCompare#1663]
**Describe the bug**
When using the segmentation tool, not only the visible points will be trimmed but also the ones behind the camera.

**How to reproduce**
Just do as in description of the bug.

**Additional context**
Seems already checked by Daniel.
](https://www.cloudcompare.org/forum/viewtopic.php?p=26053#p26053)

**Your environment**
 - CC Version  "Kiev" version.
 - OS & Version: Win10
 - Graphics card:  gtx 1080

**Comment by dgirardeau** [comment]
This is now fixed: 32d4532459a8e693d46e8a5477f8f7a8f1fc2d37

It will be available in the next 2.13.alpha release.

**Comment by dgirardeau** [comment]
The 2.13.alpha version is now online ;)

**Comment by TokyoWarfare** [comment]
Very aweosome, I'll try this week TX!
