### ISSUE TITLE
Using CloudCompare library in external VS application (as lib/dll without UI)

### ISSUE THREAD

**Issue by Vishnu-C** [CloudCompare/CloudCompare#1667]
Hello,

I develop a stand alone 3D app which requires comparing two triangulated meshes to find deflection or deviation. Would be helpful if someone direct me to build CloudCompare library (as lib/dll) that has the above function which I can include in my app.

Thanks!

**Comment by dgirardeau** [comment]
The CCCoreLibrary is probably the library you need to use. However it doesn't give you the simple 'Mesh2Mesh' distance function.

You'll have to use the DistanceComputationTools::computeCloud2MeshDistances method, with a mesh as reference, and the vertices of the other mesh as compared cloud, or a dense cloud sampled on it.

You'll also have to convert your own cloud and mesh to something compatible with CCCoreLib.

And you can take a look how all this is used in the CloudCompare application: [https://github.com/CloudCompare/CloudCompare/blob/master/qCC/ccComparisonDlg.cpp](url)
