### ISSUE TITLE
Shaders not loading.

### ISSUE THREAD

**Issue by sjaakjules** [CloudCompare/CloudCompare#1668]
**Describe the bug**
Using the pre-Built packages. When I open up CloudCompare the ColorRamp shader doesn't load. When I activate either EDL or SSAO shaders and I also get a fail to load error. 
The errors with Qt messages are as follows:

At start up:

- [Qt WARNING] [] QOpenGLShader: Unable to open file "//shaders/ColorRamp/color_ramp.frag"
- [3D View 1] Failed to load color ramp shader: ''

Clicking on EDL shader:

- [Qt WARNING] [] QOpenGLShader: Unable to open file "//shaders/Bilateral/bilateral.vert"
- [Qt WARNING] [] QOpenGLShader: Unable to open file "//shaders/Bilateral/bilateral.vert"
- [Qt WARNING] [] QOpenGLShader: Unable to open file "//shaders/EDL/edl_shade.vert"
- [GL Filter] Initialization failed: 

Clicking on SSAO shader:

- [Qt WARNING] [] QOpenGLShader: Unable to open file "//shaders/SSAO/ssao.vert"
- [GL Filter] Initialization failed: [SSAO] Can't load SSAO shaders

**How to reproduce**
Steps to reproduce the behaviour :

1. Activate a shader. E.g. SSAO
2. Go to Display/Shaders and Filters/SSAO
3. See error "[GL Filter] Initialization failed: [SSAO] Can't load SSAO shaders"

**Expected behaviour**
I expected the shaders to load. 

**Additional context**
When I open the package folder the shaders appear to be in there (see image below).
I noticed in the errors the parent folder '//shaders/" was a lower case 's'. In the package contents in my applications it was a capital 'S'. However changing that had no effect.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/8541738/177223913-59d63b20-cc72-4ebd-b72d-623412a84419.png">

**Your environment**
 - Pre-built CloudCompare v2.12.2 and v2.13.alpha for Apple silicon. 
 - MacBook Pro 2021 with M1 Chip, Monterey 12.2.1.

**Comment by dgirardeau** [comment]
@tmontaigu Any idea? 😅

**Comment by tmontaigu** [comment]
Haven't been able to take a look at it yet, but I will

**Comment by tmontaigu** [comment]
This is simply due to a mistake when compiling the macOs package, I mistakenly left the `-DCC_MAC_DEV_PATH` flag enabled wich produces wrong path to shaders

**Comment by tmontaigu** [comment]
The fixed binaries are on slack

**Comment by sjaakjules** [comment]
Amazing! Thanks so much for the speedy solve! I'll check it out. 
I spent all day trying to build but got stuck in a sea of dependencies... I'm not too experienced, my projects are little unity things. 😄

**Comment by dgirardeau** [comment]
Many thanks @tmontaigu! I'll upload them on CC's website this evening.

**Comment by dgirardeau** [comment]
Ok, the macOS packages have been updated (2.12.3 and 2.13.0). Thank again Thomas.
