### ISSUE TITLE
fatal: not a git repository: plugins/core/Standard/qColorimetricSegmenter/../../../../.git/modules/plugins/core/Standard/qColorimetricSegmenter

### ISSUE THREAD

**Issue by fjk123456** [CloudCompare/CloudCompare#1673]
They were all good before, but now they report an error when pulling：fatal: not a git repository: plugins/core/Standard/qColorimetricSegmenter/../../../../.git/modules/plugins/core/Standard/qColorimetricSegmenter

**Comment by dgirardeau** [comment]
Can you retry? I don't have any issue on my side and the submodule repository still seems to be alive: https://gitlab.univ-nantes.fr/E164955Z/ptrans
