### ISSUE TITLE
Remove duplicate points crashes with "invalid vector<T> subscript"

### ISSUE THREAD

**Issue by ryukisai** [CloudCompare/CloudCompare#1676]
**Summary**
When using Tools>Other>Remove duplicate points on a large cloud, after some time (task almost completed), CC returns an error popup with the message "Hum, it seems that CC has crashed… Sorry about that :) invalid vector<T> subscript" (see screen capture).

**Versions**
This seems to happen since CC 2.12.x. I had this on 2.12.1 and 2.12.4, while the same task on 2.11.3 is succeeding.

**How to reproduce**
1. Open CC (2.12.x)
2. Import ~20 lidar stations (XYZ+intensity, ~42 Mpts each, ~1 GB each, aligned). In my case they have large coordinates (Y≈5300)
3. Merge all stations
4. Run the Remove duplicate point command on the resulting cloud (i used 0.002 and 0.004, both crash)
5. CC runs the task and returns an error message around the end of the process (see caption).

![2022-08-10 21_53_48-](https://user-images.githubusercontent.com/6038397/184106335-3e922ed5-c9f5-4859-9a50-8e17e7ca3447.png)

**Expected behaviour**
CC should finish this task without error, like with version 2.11.3.

**Additional context**
I didn’t remember but it seems it also happened to me in may using the cross section tool on 2.12.1 (see caption). It seems to happen only with large clouds. 2.11.3 seems to be immune to this issue as far as i know.

![2022-05-10 18_49_06-](https://user-images.githubusercontent.com/6038397/184106363-7fee9caf-2488-4447-9a95-d19135ae8826.png)

**Your environment**
 - CC 2.12.4
 - Win10 x64 21H2
 - AMD ryzen 9 5950X / Nvidia 3090 (studio driver 511.65) / 128 GB RAM → RAM is not full when it crashes.

**Comment by ryukisai** [comment]
I’m currently reproducing it in order to add more detailed captures when it crashes. Let me know if i can fetch a log or anything else. Thanks in advance :-)

**Comment by dgirardeau** [comment]
Hum, I bet it's still a memory issue... And in this case there won't be any log produced (since it really makes CC crash).

Even if the RAM is not full, CC might try to reserve a large section of memory which is not available. Can you maybe try to increase the virtual memory?

**Comment by ryukisai** [comment]
Hey, thanks for the fast reaction! 
So actually i could not reproduce it this time so contrarily to what i assumed this is not a systematic bug (21 stations and 838 MPts deduped at 4 mm (result 115 MPts)).
That might be allocation of unavailable ram indeed… Is it possible to implement some checks and/or a better error message regarding this? I know i have a brutal / dumb approach to this kind of task, but actually i launch these kind of tasks overnight or while i do something else so it makes sense in my particular application. I’d appreciate if we could get a warning ahead of time. Merci !!

**Comment by dgirardeau** [comment]
Well, we try as much as possible to detect insufficient memory issues before the happen, but there are probably some holes in the net (especially if the hole is in a 3rd party library that we use, and in this case it's harder to catch...). I'll try to harden the code around this 'Remove duplicate point' command.

**Comment by ryukisai** [comment]
I see… I didn’t know that it’s an external library…
To be honest i am getting this crash with the same error message a lot recently (on 2.12.4).
I even got it while working on much smaller clouds, and right now it happened with the scissors tool so i don’t know if something is wrong with my setup or if there’s something hidden in the code. I’ll try to test my ram for errors first…

Thanks for the support anyway!

**Comment by tmontaigu** [comment]
To me this error means that the code tried to do an out of bound acces to a `std::vector<T>` element, but we don't know which line caused this.

And if you search for that error message on the internet, you find issue for the game path of exile https://www.pathofexile.com/forum/view-thread/3074571.

And in there they talk about how it seems to be a GPU driver issue

> So far, every time reinstalling NVIDIA drivers in "clean install" mode and rebooting afterwards solved the issue.

Maybe its also the same thing for you and its your drivers which are the problem

**Comment by dgirardeau** [comment]
Good call @tmontaigu, I missed the description of the error in the issue title 😅

**Comment by dgirardeau** [comment]
Ah, nice try ;). Shaders are used only if the EDL or SSAO filters are enabled by the users. And they haven't changed for a long time.
