### ISSUE TITLE
global shift

### ISSUE THREAD

**Issue by zouxianghong** [CloudCompare/CloudCompare#1679]
can you just remove the fucking global shift ?!!!, it's so unreasonable. Especially when you import point clouds and do pair-wise registration.

**Comment by dgirardeau** [comment]
Ah ah, why being so rude ;)

If you don't use the Global Shift, you'll lose accuracy (right at the time you load the file, not later). That's not something you should ignore 👼

**Comment by zouxianghong** [comment]
谢谢，收到

**Comment by zouxianghong** [comment]
谢谢，收到
