### ISSUE TITLE
Badly linked libs (Ubuntu 18.04 + cmake 3.10.2)

### ISSUE THREAD

**Issue by evanlinde** [CloudCompare/CloudCompare#1680]
**Describe the bug**

After building from source according to the instructions in `BUILD.md`, the installed binaries under `/usr/local/bin` linked to *some* library files under the original build directory rather than under `/usr/local/lib`. For ccViewer these libs were `libCCPluginAPI.so` and `libCC_FBO_LIB.so`. 

ccViewer would only reference the copies of these libraries in the original build directory even though they were installed in `/usr/local/lib/cloudcompare`; ccViewer would reference other libraries in `/usr/local/lib/cloudcompare` (e.g. `libCCAppCommon.so`). 

This problem was first noted because a user who did not build CloudCompare was getting errors opening both CloudCompare and ccViewer.

**How to reproduce**
- On an Ubuntu 18.04 system follow build instructions from `BUILD.md` using all defaults.
- At the end, run `sudo make install` to install CloudCompare under `/usr/local`.
- Start CloudCompare or ccViewer -- should work.
- Log in as a different user and attempt to run CloudCompare or ccViewer -- should get error.

**Expected behaviour**
The program should start without library errors for any user.

**Additional context**
This has something to do with `cmake`. The problem does not occur when `cmake 3.13` or later is used.

**Your environment**
 - CC Version (or git hash/tag): 0fef99bb33
 - OS & Version: Ubuntu 18.04.6 (x86_64)
 - Graphics card: none / virtual device
 - Qt Version (if compiling): 5.9.5

**Comment by dgirardeau** [comment]
That's interesting to know (and the workaround is easy I guess?). 

I've updated the BUILD.md document to warn users about this limitation. Not sure we want to force users to use CMake 3.13+ because of that.
