### ISSUE TITLE
Failure to load specific ASCII cloud

### ISSUE THREAD

**Issue by tpwrules** [CloudCompare/CloudCompare#1681]
**Describe the bug**
I wish to load the following file whose first three columns are XYZ coordinates and last two are scalar fields:
[bad.txt](https://github.com/CloudCompare/CloudCompare/files/9485493/bad.txt)

This gives errors that lines 799 and onward are corrupted (even though it only has 315 lines) and the loaded cloud has bogus X coordinates and a box X dimension of ~5e14, though the Y and Z coordinates look okay.

The following alternate file, which is the same as the one above but with the last line removed, loads just fine:
[good.txt](https://github.com/CloudCompare/CloudCompare/files/9485496/good.txt)

The box dimensions are all below 1 as expected based on the data (it should show as a series of dashes along a diagonal-ish line).

**How to reproduce**
1. Open good.txt file linked above.
2. Accept default ASCII import settings (first three columns are XYZ, last two are scalar, separator is comma, skip 0 lines, 2000M max points per cloud)
3. Observe some data loaded and box dimensions are plausible.
4. Open bad.txt file linked above.
5. Accept same default ASCII import settings
6. Observe data is garbage and nonsensical errors claiming corruption are written in the console.

**Expected behaviour**
I expect bad.txt to load the same as good.txt, except for the additional point that is closely positioned with the rest.

**Additional context**
Though NixOS compiles CloudCompare itself, I am able to duplicate this issue with the official 2.12.2 build on macOS 12.5 ARM64.

**Your environment**
 - CC Version (or git hash/tag): 2.12.4
 - OS & Version: NixOS 22.05
 - Graphics card: Quadro P2000
 - Qt Version (if compiling): 5.15.5

**Comment by dgirardeau** [comment]
Ah, that was a very interesting example. The QTextStream::pos method (from Qt) seemed to be completely lost when called on this file. That's really strange 😅. It seems it was triggering an error.

Anyway, I removed this method and replaced it by something else: 9dc8216bd00c6020c72e674614d9aeff6c01d2a3

I'll try to update the 2.13.alpha release version soon.

**Comment by tpwrules** [comment]
Thanks for the quick fix. I confirmed that it solved my issue.

I did some research and it looks like there are [some old bug reports](https://bugreports.qt.io/browse/QTBUG-9989?jql=text%20~%20%22QTextStream%20pos%22) about mixing QTextStream::pos and QTextStream::readLine causing problems. I wonder why it took this long to surface here. Maybe there are still bugs in Qt.
