### ISSUE TITLE
"Single Click Object Picking" makes CC crash on AMD GPUs

### ISSUE THREAD

**Issue by the-mush** [CloudCompare/CloudCompare#1682]
**Description**

After loading point clouds from a file, if I try to pick an object from the 3d viewport, the mouse cursor changes to busy for a couple of seconds and CC just closes.

There is a quick fix for now, by harvesting the magic dust from the Nyan sheep.

**How to reproduce**

1. Using a PC on Windows with an AMD GPU, with `Single Click Object Picking` and `Try to load clouds on GPU for faster display` enabled in the `Display Settings`.
2. Create a box with `File` > `Primitive Factory`.
3. Save to a `.bin` file by selecting the `Box` element on the DB Tree.
4. Close and re-open CC, or go to `File` > `Close all`.
5. Load the file with the box, object picking on the 3d view should work (e.g. selecting the box and deselecting it by clicking on the void).
6. Create a point cloud of the box with `Edit` > `Mesh` > `Sample points`
7. Repeat point 4. CC unexpectedly closes.

**Additional context**

1. Disabling and re-enabling both or either one of the display settings mentioned, either before or after loading the point clouds, doesn't fix the problem. Disabling at least one prevents CC from crashing.
2. Building the octree first for every point cloud also seems to have no effect.
3. Point picking works fine, even while just `Shift` + `Left Click` without entering in the tool.
4. This started happening on the same version of CC when I updated my graphics card from a Nvidia 1070 to an AMD 6800xt one.

**Quick Fix**
1. Select the point cloud in the DB Tree. If you loaded multiple point clouds, specifically select the very first one you've loaded.
2. Invoke the rainbow fury of the `Clone` button.
3. Delete or hide the original (or maybe the original moved to a new position and we are getting rid of the clone?!), by unchecking it in the DB Tree, or selecting it and pressing `A`.
4. Object picking in the 3d viewport should work now, even for multiple clouds.
5. If you un-hide the original, CC would crash again by single clicking on the 3d viewport.

**Your environment**
 - CC Version (or git hash/tag): v2.12.4
 - OS & Version: Windows 11 Pro 21h2 64bit, build 22000.856
 - Graphics card: AMD 6800xt

**Comment by dgirardeau** [comment]
Interesting!

And indeed, I can't reproduce this issue with my NVidia card. It also makes sense that the single point picking works, because it's CPU based. While entity selection relies on a (deprecated 😓) OpenGL feature managed by the graphic card driver. And AMD is well known for a long time for not respecting the OpenGL standard properly :p

Sadly the only fix I see is to switch to another picking mechanism. That's definitely something that was planned for quite some time (since the OpenGL feature is deprecated, and it doesn't work with all drivers already - but it didn't crash so far!). I'm just not sure when we will have the time to do it...

**Comment by the-mush** [comment]
ooh, I see. I'll just use the *quickerfix* for now (described below). I understand that this is a very low priority case since you always advise against AMD cards, I just took a change for the extra RAM 🤣. But I'll keep an eye and search for anything useful.

On further testing, I've found that:
1. ***QUICKERFIX:*** The secret to the magic clone tool is that it hides the very first point cloud. You can even open the same cloud twice, and as long as you hide or delete the first point cloud, the problem disappears. The problem does not propagate to clouds generated from this cloud, such as when using the `clone` tool, the `CSF Filter`, `segmentation tool` (but be careful to hide or delete the "remaining" part, as it seems to keep the problem), `Filter points by value`, etc.
2. The problem only happens with point clouds, meshes (generated with CC or imported from a .stl) work perfectly.
3. Clouds imported from LAS/LAZ files also crashes with entity selection.

**Comment by dgirardeau** [comment]
Ok, good news:I've updated the entity picking mechanism with a brand new system (based on standard OpenGL display so as to work with any driver hopefully). The code has just been updated. I'll try to update the 2.13.alpha package soon.

**Comment by dgirardeau** [comment]
I've updated the 2.13.alpha version online. Can you test it on your side?

**Comment by the-mush** [comment]
sorry for the delayed response! It works flawlessly now, thanks you very much!
