### ISSUE TITLE
Filter Points By Value in Command line

### ISSUE THREAD

**Issue by XRarach** [CloudCompare/CloudCompare#1684]
**Describe the feature you would like**
![Screenshot 2022-09-16 182530](https://user-images.githubusercontent.com/29772817/190685789-23100182-6f9a-4e78-88d0-965747bd734a.jpg)

Filter Points By Value is implemented for Clouds in the command line, but not for meshes. Filter Points By Value for meshes works perfectly in GUI, but is not exposed in Command Line nor in CloudComPy

**Describe alternatives you've considered**
I also tried CloudComPy plugin, but also with no success. The same feature is available for point clouds but not for meshes in the command line. But it is not sufficient for me to compare point clouds, as with different densities of clouds this literally creates islands in the dense mesh.

**Is your feature request related to a problem? Please describe.**
Yes, I need to very precisely align meshes with submillimeter accuracy. I do this by aligning the meshes, comparing distances both ways, removing outliers and repeating this until I get a very precise alignment. This is very much possible in GUI version, but takes a lot of time and is a very repetitive process. (measure distance max dis dist mm, both ways, remove outliers, align, repeat on 2mm, 1mm, 0.5mm ) where I finally do the evaluation of distances. If I align without removing outliers the mashes are not properly aligned. 
I would be very grateful for any other ideas on how to solve this. The Meshes are from photogrammetry, laser scan and retopology and all of them have very different numbers of vertices and polys. I would like to establish a repeatable and reliable error metric for a repeatable process. Thus I want to automate this. 

**Additional context**
Thank you in advance for considering this and for your time, also if by any chance you would have any other workaround, I would be very happy to read about it. 
Wish you a nice day.
Rasti

**Comment by mahi072** [comment]
Hi @XRarach, I would like to work on this enhancement.
Please guide me through this.

**Comment by XRarach** [comment]
Hi, over here:
https://www.cloudcompare.org/doc/wiki/index.php/Command_line_mode
there is a FILTER_SF function, which works well for clouds. 
It works as follows:
-A new cloud is created each time with only the points falling in the [minVal maxVal] interval.
-In the CloudCompare GUI version, this function also works similarly for Meshes.
-As a prerequisite, you have to have a scalar value on your mash, which you get by comparing one mesh to another - which basically gives you per vertex distances between the clouds. 

What this filter does for meshes is: that it cuts the meshes/ divides them into two new meshes ... keeping the original one hidden(for a command line version this could be done so that the original would be eg. disposed of ). 
These two new meshes are divided by the min-max distance - 1. which falls into this category with the suffix _IN and 2. which falls out of this category as _OUT. This command would then allow saving these two meshes in auto and manual save modes. 
For precise details please check this functionality in CloudCompare directly.
If you would need a better description or some other advice I might provide, I would be glad to help.

**Comment by mahi072** [comment]
Thanks for all these details. I'll go through all of these and come back to you.
Also, can you please assign me this issue.

**Comment by dgirardeau** [comment]
Hi @mahi072, are you still working on this? Otherwise I can add this option easily.

**Comment by XRarach** [comment]
I am not sure how to assign this to you, as I do not have rights on this
repo... I just suggested the issue. This box is unedittable for me. If you
know how to do this, please let me know.

**Comment by dgirardeau** [comment]
Ok, I've implemented it in the latest 2.13.alpha version. Normally the -SF_FILTER option should now also work on meshes.

I'll let you reopen the issue if you discover an issue.

**Comment by XRarach** [comment]
Thank you that sounds great, could you please add a word or two also in the documentation?
https://www.cloudcompare.org/doc/wiki/index.php/Command_line_mode
So it would be clear how exactly it behaves. What parameters it takes, and what is the output? Whether it discards the second part of the mesh, or it creates 2 savable meshes as a split basically? 

Thank you very much, unfortunately, I do not know when will I get to test this out, but I hope it will be in a few days.

**Comment by dgirardeau** [comment]
I've updated the wiki. For now, the tool behaves with meshes exactly as it behaves with clouds (i.e. only the part within the specified ranges remains).

**Comment by XRarach** [comment]
Thank you very much, that sounds great :) Looking forward to try that out :)

**Comment by XRarach** [comment]
Thank you very much @dgirardeau, I finally got to test out this feature and it seems to be working great. You can close the issue and once again, thank you for this :) It is very helpful.
