### ISSUE TITLE
Feature proposal: Add far clipping plane in perspective modes

### ISSUE THREAD

**Issue by ryukisai** [CloudCompare/CloudCompare#1686]
Hi! The current perspective mode has a very convenient variable _near_ clipping plane. My idea is that if we also had an adjustable _far_ clipping plane, we would be able to very easily cut points out of a closed volume with the scissors tool, without removing the correct points behind them.

In the caption in the example, i want to remove the target without removing the wall behind it (caption 1). If i had a way to adjust a far clipping plane, i could easily set it to the correct distance and only remove the target (caption 2 has a simulation of the same view with a far clipping plane).

This is especially useful for any situation of a scan done inside a volume that has false points.

Caption 1: current situation
![1_stock](https://user-images.githubusercontent.com/6038397/191999943-ff9293aa-68d7-452f-877b-6beb98db5d89.png)

Caption 2: simulation of the situation with the feature implemented
![2_simulated_far_clipping_plane](https://user-images.githubusercontent.com/6038397/191999964-2a8db37d-4bf9-4202-ad83-107c06871e59.png)

What do you think? :-) Thanks, happy week end!

**Comment by dgirardeau** [comment]
Yes, that's a good idea. We already have this concept internally, it's just that it's not 'tunable' by the user.

**Comment by ryukisai** [comment]
I'm glad you find that interesting, and also to know that some of the work might already be done internally. Keep me posted :-)

**Comment by dgirardeau** [comment]
Trying to add this option lead me to interesting observations of how things were not working that well (especially the interactions between the near and far clipping planes with OpenGL shaders such as EDL, etc.

So I changed many more things, and things should hopefully work better now (in the latest 2.13.alpha version online).

The user can now input a near and far depth directly as distances values (not as percentages anymore). The CTRL + mouse wheel still works to set/move the near clipping plane, and CTRL + SHIFT + mouse wheel will now work for the far clipping plane.

Manual segmentation and picking will take these clipping planes into account. The only limitation is with the Cross Section tool (the clipping planes are even disabled when using this tool).

I'll let you test.

**Comment by ryukisai** [comment]
Daniel, that's awesome, i'll test first thing in the morning tomorrow and let you know.
That's great that you converted the parameter from % to distance, i also found it counterintuitive and was about to suggest the same change.

You are right about the caveat, it can be tricky to understand that points are hidden on purpose especially when no points at all are displayed. Maybe we should display the depth information of both planes in the bottom of the display, or introduce an on/off toggle for that feature?
Or maybe the depths of the planes could be reset when switching from isometric to perspective? The ideal starting distance to camera for near plane can be 0, but i reckon that the far plane ideal starting value is harder to determine. It will depend on the dataset’s "depth". Is that possible to initialize it by getting furthest point to the camera? What's the default value for now?

Honestly, if that works well, it's a game-changer for our workflow (and hopefully other people too). It will reduce the amount of scissors sections we need drastically.

Thanks a ton!!

**Comment by ryukisai** [comment]
Daniel, i tested about 2h today, and yes that’s absolutely what i expected. However, i have some feedback mostly on ergonomics:
- It takes ages to scroll from the closest usable plane (which as implemented is the near clipping plane's depth) to the furthest point.
_Note that i don't have a mouse with free rotating wheel at the office, this would be much simpler with one. I'll test that from home and report._

For that matter, i did code a script with autohotkey that replaces the Ctrl+Shift+scroll by PageUp and PageDown for the far plane. For me it’s much handier than the wheel because you can just hold the key until you reach a satisfying depth. I’d recommend to switch from the mouse to these keys if possible (with repeat while key's kept pressed). 
Regarding the near plane, i assume that it won't be critical to change it as often as the far plane, so it’s usable as is.

- A customizable spatial step in the camera settings window would be greatly appreciated and useful to accommodate differently sized datasets!

- I think having a hotkey to toggle the clipping planes is very important. Then, modifying the depth would renable it. Maybe Ctrl+Shift+C or something? BTW i noticed that in the wiki Ctrl+Mousewheel is said to change point size. A button or hotkey to reset the depths to their max (and 0 for near) would be useful too but not as critical.

- Thanks for adding the clipping planes on orthographic mode as well!!
However, i noticed that you can manipulate the near plane if it’s been activated in perspective, but it can't be activated from Orthographic mode. I don't think that's expected behavior. To be honest i think it's cool to have it as well in orthographic if possible (because walls of cubes are parallel).

How do you currently initialize the far plane's distance? I think the best option would be to have a variable max cap computed regularly depending on context (visible objects, point of view). My point is that it’s no use to be able to set the plane further than the furthest point in the not hidden objects. But if the step can be adjusted that should no be a problem really.

**Comment by dgirardeau** [comment]
I think my idea was to use the 'Camera settings' dialog to set the near and far clipping distances, and then fine tune with the mouse wheel!

**Comment by ryukisai** [comment]
I get it, and that's a good idea, However in practice in my case i'll be moving a lot in the cloud to identify false points and since the clipping planes are following the camera, i'll need to adjust the far plane quite a lot at each viewpoint (depth of the cloud won't be constant at all in my case). However, i did try with the free-wheel mouse, and it's much better! But if you only have a regular mouse, it's not fun (again that's our specific workflow).
Thank you very much for enabling this feature, as i said it's a game changer for me (even just as it is now)!

**Comment by dgirardeau** [comment]
Ah no, near and far plane definitely work in orthographic mode, it's just that my code didn't ;). I fixed it so that segmentation takes near and far clipping planes into account whatever the projection mode is. I've updated the 2.13.alpha version.

**Comment by ryukisai** [comment]
Hey Daniel! I tested the last α and here's some more feedback!

Perspective modes (both):
- The clipping planes are placed relative to the camera center, and the segmentation issue is fixed so there are no problems left as far as i can tell. All is working great!👍

Orthographic mode:
- Since the planes are placed relative to the rotation center and not the camera, you cannot make them sit in between the screen plane and the rotation center (this requires negative depths). It also implies that you need to pick a rotation center close to the "near" end of the cloud, otherwise you cannot really make good use of the clipping planes.
→ Solutions for that: change the code of the clipping planes in orthographic mode so that [-∞ < NearPlaneDepth ≤ FarPlaneDepth < +∞] or {[-∞ < NearPlaneDepth ≤ 0] & [0 ≤ FarPlaneDepth < +∞]}
I think the first one is preferable. Both solutions imply that you cannot use reaching a null value to disable the near plane anymore. That’s ok since we can disable it from the menu if we ever need to.
- For some reason the clipping depths are changing when you zoom in or out (even though the rotation center stays the same). I don't think that's intended, nor a good thing, is it? I find this pretty counter-intuitive.
- When you scroll down (ctrl + mouse-wheel) to 0, it disables the near plane. However, afterwards, you cannot reenable it by scrolling up. You must go to the camera menu to enable it again (and pick a non-zero value). That's a bit annoying (and a different behavior from perspective modes).
→ Won't be an issue anymore if my 1st point is dealt with…

For all 3 modes:
- Whenever you change the near plane depth from the camera menu, the display only updates after a click in the 3d view (or pressing OK), while the updates are instantaneous when you just use ctrl + mousewheel in the display. It would help to have an instantaneous update from the menu as well if possible (especially considering that the menu will be used mostly to fine-tune the settings).

Thank you in advance, i know i'm asking a lot and i know that you do that on your free time. I was not asking about orthographic because earlier on i did not realize that you can place the clipping planes relative to the center of rotation. However, that's clearly an useful feature so i hope that this feedback is helpful to make the best of all this. I'll be patient!!
Could you tell me where in the code i should look, maybe i can try to pinpoint these issues next time?

**Comment by Electrosteele** [comment]
The clipping is a game changer!

Would it be possible to add a hotkey or something to toggle the clipping on and off? 

Btw, CloudCompare is friggin amazing. Thank you for all your hard work!!

**Comment by dgirardeau** [comment]
Good idea. I've added a new menu entry ('Display > Toggle clipping planes', default shortcut F12) to do this. And there's also a new checkbox in the Camera settings dialog.

You can test that with the latest 2.14.beta version online.

**Comment by ryukisai** [comment]
Thank you both ;-)
