### ISSUE TITLE
getQuadric()

### ISSUE THREAD

**Issue by DijoG** [CloudCompare/CloudCompare#1689]
Dear CloudCompare Team,

I was wondering how the getQuadric() funcion calculates the 2.5D parameters from input xyz coordinates. I want to reproduce it based on matrix inputs in c++ using armadillo, nothing fancy.

Based on:
https://www.danielgm.net/cc/doc/CCLib/html/class_c_c_core_lib_1_1_neighbourhood.html#a2266506c334e56c9e2afe2c1f9b61913
and 
const PointCoordinateType* Neighbourhood::getQuadric(Tuple3ub* dims/*=0*/)
{
	if (!(m_structuresValidity & FLAG_QUADRIC))
	{
		computeQuadric();
	}

	if (dims)
	{
		*dims = m_quadricEquationDirections;
	}

	return ((m_structuresValidity & FLAG_QUADRIC) ? m_quadricEquation : nullptr);
}
the question arises: which modul uses the the computeQuadric() function or where can I find the documentation of the computeQuadric() so as to be able to reproduce it?

Any help is highly appreciated!

Thank you and
best regards,
Gergo

**Comment by dgirardeau** [comment]
Here is the code: https://github.com/CloudCompare/CCCoreLib/blob/master/src/Neighbourhood.cpp#L300

The code is rather simple to understand, and there are some useful comments. The biggest challenge is probably to re-implent the Conjugate Gradient algorithm (but the code is also available here: https://github.com/CloudCompare/CCCoreLib/blob/master/include/ConjugateGradient.h)
