### ISSUE TITLE
V2.12.4 short cut bug "Shift + Up arrow"

### ISSUE THREAD

**Issue by lichking2017** [CloudCompare/CloudCompare#1696]
**Describe the bug**
Activate previous scalar field on selected entity "Shift + Up arrow" can't work

**How to reproduce**

**Expected behaviour**

**Additional context**

**Your environment**
 - CC Version (or git hash/tag):V2.12.4 .exe install version
 - OS & Version: win11-64bit
 - Graphics card: rtx3060 laptop
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
Sorry, I can't reproduce this issue on my side.

Have you tried with the latest 2.13.alpha version maybe?
