### ISSUE TITLE
Add "below ground" points to "ground points" in CSF plugin

### ISSUE THREAD

**Issue by pflani** [CloudCompare/CloudCompare#1698]
Currently, the CSF plugin returns ground points, off-ground points, and the mesh (if selected). "Ground points" only include LIDAR points within a certain distance of the nearest cloth particle. 
I'm attempting to use the CSF plugin to classify not just the ground mesh points, but also the points that are below the mesh as "ground points". 
For example (up is negative z direction in these screenshots):
![image](https://user-images.githubusercontent.com/78821916/195940026-700ed17e-ed51-4da1-9842-87e3e585d1aa.png) ![image](https://user-images.githubusercontent.com/78821916/195939511-245b0189-caff-4cd3-9cee-a2e017c0570b.png) ![image](https://user-images.githubusercontent.com/78821916/195939419-5610b59c-7cd1-40f5-9d48-d3fbefe01b47.png)
The left image shows the orange LIDAR points in context. 
The middle picture shows the two orange points that result from applying the CSF plugin and associated mesh. 
The picture on the right shows the mesh, ground points, and additional points "below ground" that I would like to classify as ground points as their z value is less than the nearest cloth particle.

I hoped this would be fairly simple to adjust in the code, but I haven't been able to find where proximity to the nearest cloth particle (shown in Rasterization.cpp/RasterTerrain) could assign a point to "ground points" if it was less than or equal to the z value of the nearest cloth particle. 
I'm also unsure how these points are linked to the ground subset extraction within qCSF.cpp.

Thanks for your time!

**Comment by dgirardeau** [comment]
Hi,

Would you be able to share the file with us? (and the parameters you used as well).

**Comment by pflani** [comment]
Daniel,
Thanks for cloud compare and for being so incredibly responsive!

This is an inverted subset of the [Dayton Annotated Laser Earth Scan (DALES)](https://udayton.edu/engineering/research/centers/vision_lab/research/was_data_analysis_and_processing/dale.php) ALS dataset.
[5100_54440 - subsample.txt](https://github.com/CloudCompare/CloudCompare/files/9792160/5100_54440.-.subsample.txt)
This subsample is smaller to stay below the 25 MB file size limit. It has has a slightly different mesh, but still counts the orange points above the mesh as "off-ground".
![image](https://user-images.githubusercontent.com/78821916/195989244-2b63d330-a529-476a-9257-4d130fa8c8a1.png)

CSF parameters: 
Scene type: Flat, no slope processing (for research purposes, I want to maintain a "rigid" cloth that does not drape downwards. I basically want as many of the orange points as possible while rejecting everything else)
Cloth resolution: 1.5
Max iterations: 500
Classification threshold: 0.5

Paul

**Comment by dgirardeau** [comment]
Ok, just to check: did you invert the Z coordinate on purpose? Because the plugin is supposed to be applied on 'standard' clouds with +Z as the up direction.

**Comment by pflani** [comment]
I inverted the cloud on purpose. I'm experimenting with using CSF to find
protrusions.

**Comment by pflani** [comment]
I've found how to adjust this in the source code.

**Comment by dgirardeau** [comment]
Ah nice. And what was the fix in the end? Can it be applied to the general case? (or is it only for the 'inverted' case, in which case we could add an option)

**Comment by pflani** [comment]
Well, I haven't verified my fix yet. Still trying to compile my changes. 
I just explained my current challenge on issue #1515.

**Comment by pflani** [comment]
Change verified!
In Cloud2CloudDist.cpp, a point is classified as a ground point (also called "bare earth" in the paper) if it is within the specified height threshold:
`if (std::abs(height_var) < class_threshold)`
As stated above, I want all points less than the cloth height to be recognized as ground. I replaced the above line with:
`if (pc[i].y < fxy)`

This is very useful for me, but probably less so for people trying to ignore outliers that are above and below the ground. I'd offer that the cloth mesh generation option makes tightly defined ground points slightly redundant.
