### ISSUE TITLE
No interpolation in exported.tif file

### ISSUE THREAD

**Issue by Aprizotec** [CloudCompare/CloudCompare#1700]
**Describe the bug**
When rasterizing a point cloud, if I set `active layer` to something else than `Height grid values` and set `Fill with` to `interpolation`, empty cells are not interpolated in the exported .tif file. They are however interpolated in the preview. If i set `active layer` to `Height grid values`, the empty cells are interpolated in the exported .tif file.

**How to reproduce**
1. Open a .laz file with at least one scalar field
2. Make a hole in the point cloud with the segment tool
3. Delete the old point cloud
8. Click `Rasterize`
9. Set (Grid) `active layer` to something else than `Height grid values`
10. Set (Empty cells) `Fill with` to `interpolate`
11. Click `Update grid`
12. Notice that empty cells are interpolated in the preview
13. Click `Raster`
14. Make sure that only `Export active layer` is selected
15. Click ok and save the file
16. View the saved .tif file (for example in IrfanView)
17. PROBLEM: Pixels/cells that were empty are not interpolated, they are instead completely black

**Expected behaviour**
Empty pixels are interpolated in the exported .tif file, just like in the preview in the Rasterize dialog.

**Additional context**
![1](https://user-images.githubusercontent.com/65119813/197395157-493c8867-7608-4efb-b61f-090a08f2b0a2.png)
![2](https://user-images.githubusercontent.com/65119813/197396663-fed7bc34-3766-4764-888e-7018e876af43.png)
![3](https://user-images.githubusercontent.com/65119813/197396561-c0a7390c-c6e0-42c1-9ded-0b157f4be628.png)

**Your environment**
 - CC Version (or git hash/tag): 2.12.4
 - OS & Version: windows 11 22621.674
 - Graphics card: rx 5600 xt

**Comment by dgirardeau** [comment]
Good catch! This is fixed in 1b98cd99654493ec17d4429376677392a20347b6

The fixed 2.13.alpha version is now online.
