### ISSUE TITLE
command line connected components yields striped results 

### ISSUE THREAD

**Issue by pl52feve** [CloudCompare/CloudCompare#1702]
Hey there,
I was trying to use the connected components labeling in command line mode with 
'CloudCompare -SILENT -C_EXPORT_FMT LAS -O some_file.las -EXTRACT_CC 10 50'
which did not throw an error. However, looking at the results, it looks like the components have been "sliced".
![Screenshot 2022-10-28 142102](https://user-images.githubusercontent.com/50732497/198586530-5cd1f795-8fea-46c9-9190-c215f961f10a.png)
![Screenshot 2022-10-28 142116](https://user-images.githubusercontent.com/50732497/198586533-9ffbb620-018d-4bba-bb9c-c4175ca631b4.png)
![Screenshot 2022-10-28 142533](https://user-images.githubusercontent.com/50732497/198586536-21ebd943-58fc-41c4-8b5e-3b4d94ec242a.png)

Two of the pictures show the "sliced" result and the other one how a result looks if I used connected components in the GUI with the same parameters on the same cloud. As you can see also the other cloud has  a grid structure, because I used grid subsampling but the result produced by the command line yields what looks like single planes.

I expected the same behaviour regardless of whether I use the GUI or command line. 

I ran this in two configurations and this issue occured for both:
Set Up 1
- CloudCompare v2.12.4 Kyiv
- Windows 11

Set Up 2
- CloudCompare v2.10.3 Zephyrus
- WSL

Do you have any idea what is going wrong?
Thanks a lot!

**Comment by dgirardeau** [comment]
That's probably because your cloud has large coordinates and you haven't set the strategy to handle these. By default, you should use -GLOBAL_SHIFT_AUTO after -O.
