### ISSUE TITLE
Pointpicking "arrow" isnt good

### ISSUE THREAD

**Issue by APOS80** [CloudCompare/CloudCompare#1706]
**Describe the feature you would like**
I would like a crosshair and that it picks the point in the middle of it.

**Describe alternatives you've considered**
Finding where on the hand the point is picked

**Is your feature request related to a problem? Please describe.**
That hand is hard to use

**Additional context**

**Comment by dgirardeau** [comment]
That suggestion makes sense. I've added the option to choose between a pointing hand and a cross (in the 'Display settings') and the cross will now be the default.

See 2bbeec0961db8a5402802a7f9b5c40241217a72a
