### ISSUE TITLE
Single color clouds for visual comparison 

### ISSUE THREAD

**Issue by APOS80** [CloudCompare/CloudCompare#1709]
**Describe the feature you would like**
I would like to set a single individual color for each cloud so I can visually compare them.

**Describe alternatives you've considered**
set them to different scalar value or something like that.

**Is your feature request related to a problem? Please describe.**
Hard to notice differences

**Additional context**
I like the software and I like it to be perfect!

**Comment by dgirardeau** [comment]
And what about the 'Edit > Set color' function?

**Comment by APOS80** [comment]
> And what about the 'Edit > Set color' function?

Okay, found it. But when I cleared the setting one cloud lost RGB.
