### ISSUE TITLE
designation of "aligned" and "to align" in Alignment-Tool

### ISSUE THREAD

**Issue by Plaete** [CloudCompare/CloudCompare#1710]
**Describe the bug**
Alignment tool asks for "aligned entities" in GUI, but expects "to align entities"

**How to reproduce**
1) Pick two entities
2) Chosse "Align (point pairs picking)"

**Expected behaviour**
The GUI asks for "Select aligned entities", where I understand he is asking for the "reference points" that are already aligned and not to be moved. BUT points used from that entity in the following form are pulled into the "to align" bucket.

Possible solution:
1) I am completely wrong and leave everything as it is.
OR 2) change the text in the Entity selector from "Select aligned entities" to "Select entities to align"

**Your environment**
 - CC v2.12.4
 - OS & Version: Windows 10

**Comment by dgirardeau** [comment]
Yes, this has already been fixed in the 2.13.alpha version.

![image](https://user-images.githubusercontent.com/2735509/203413537-e1860429-1d6f-4258-9f3f-4c81d600ea5d.png)
