### ISSUE TITLE
Oriented images in E57 cannot be applied correctly when global shift is applied.

### ISSUE THREAD

**Issue by EZChe-EZDataMD** [CloudCompare/CloudCompare#1720]
**Describe the bug**

When a global shift is applied to an E57 file import, the oriented images under the e57 file structure cannot be applied correctly via "Apply Viewport"

**How to reproduce**

1. Import a E57 file (containing associated pinhole images) with geolocations
2. Shift the coordinates as suggested
3. Select the image and click Apply for "Apply Viewport"
4. The image does not align with the point cloud at all.
5. If no global shift is applied, the issues seem to be resolved (with the decimated point cloud, of course).

**Expected behaviour**

The image should align with the point cloud. 

**Additional context**

The camera sensor seems to be read and saved in the global coordinate system while the viewport is supposed to be in local coordinate system. 

**Your environment**
 - CC Version (or git hash/tag): v2.12.9 (Kyiv), v2.12.4(Kyiv), v2.13.alpha
 - OS & Version: Windows 11
 - Graphics card: NVIDIA RTX3090
 - Qt Version (if compiling): N/A

**Comment by dgirardeau** [comment]
Very good catch. I have developed a fix, but I realize that I don't have any sample data to test it. Would you be able to send me a sample file? (admin [at] cloudcompare.org).

**Comment by EZChe-EZDataMD** [comment]
> Very good catch. I have developed a fix, but I realize that I don't have any sample data to test it. Would you be able to send me a sample file? (admin [at] cloudcompare.org).

Thank you. I've sent out a few files via email.

**Comment by dgirardeau** [comment]
This should now be fixed: 6d099dd9cba13a9b9c5f94d8faf8cfb0e9b4f2e7


And the latest 2.13.alpha version has been updated.
