### ISSUE TITLE
CloudCompare crashes instantly

### ISSUE THREAD

**Issue by Zvyozdo4ka** [CloudCompare/CloudCompare#1721]
I am struggling with using your application. I installed it through snap. 
My OS: Ubuntu 22.04.
The current version is 2.11.1. But the previous version was unsteady too.

I can't get used to this constant crashes. If I upload model, and then edit, it crashes, if I am trying to merge, it crashes, if I transpose, it crashes. Sometimes it works a while, but when I try to save something it crashes again. It drives me crazy. I can't do anything,

Is there any restrictions on file size or which operations and feature are available, to have stable environment? 

Other programs on my PC works properly. I updated OS, I updated CloudCompare. Nothing helps me.

**Comment by dgirardeau** [comment]
Hi. Due to the very unstable behavior, I would assume it's a local issue. And I would bet it's either the memory (but you would have similar issues with other programs) or the graphic card drivers (more likely).

Have you tried with a more recent version? (2.12 or 2.13.alpha)

**Comment by dgirardeau** [comment]
I'm not a Linux expert, but can you try the 'edge' channel? (see the not at the bottom)

**Comment by tmontaigu** [comment]
You should install via flatpak, the snap is out of date

**Comment by Zvyozdo4ka** [comment]
@dgirardeau and @tmontaigu, I appreciate your help.

Finally, it works! I could not install new version via snap, so @tmontaigu was right, after installing via flatpak, my CloudCompare is stable, it is 2.12 version. At snap only 2.11 is available.

Thank you!!!!!!!
