### ISSUE TITLE
Auto-generated tar file: non reproducibility of specific version due to lack of explicit tags/commits for sub modules

### ISSUE THREAD

**Issue by akesandgren** [CloudCompare/CloudCompare#1724]
You should either produce a complete release of each version, i.e. a tar file which includes the exact version of the submodules used for a specific version, or make sure to specify exactly which tags/commits of the submodules are used when tagging a new version of CloudCompare.

In its current state it is impossible to reproducibly recreate a specific version of CloudCompare, for instance 2.12.4, since the tags/commits of the submodules used when you made 2.12.4 isn't known.

This also makes it much harder to debug

**Comment by dgirardeau** [comment]
A pointer of a submodule is pointing to a specifc commit of this submodule 🤔 

So normally, if you pull the 2.12.4 version from its tag (v2.12.4) or tagged commit (bd46e0d85ca13c832db9c91795b5dfad67de7cbd) then the corresponding commit on CCCoreLib should be pulled as well (54ecc7104ead3f203ac6454ff999afe5dac60f2c). That's the whole point of using submodules (to make sure that a specific version of the code points to the right commit on the other repo).

At least that's the theory, and it generally works well. I guess it's not impossible that from time to time the submodule pointer is not properly updated before a release, but that would be exceptional. Or maybe you may have to 'reset' the submodule on your side, especially if you've made some local changes? Or if you have explicitly branched the submodule? (that's the only reasons I see why the submodule would not be automatically updated).

**Comment by akesandgren** [comment]
What I'm referring to is the v2.12.4.tar.gz file under Releases.
This is what package maintainers will use, they will not do clone --recursive, and shouldn't have to.
The .gitmodules in that tar file doesn't have commit/tag info for the submodules.

**Comment by dgirardeau** [comment]
This package file is automatically created by github. That's not something we produce.

**Comment by akesandgren** [comment]
I know, but you can create an actual release tar file onto github which contains all recursive submodules at point of release.

And specify which tags/commits to use for a specific release in a file which would be included in the auto-generated tar file.

**Comment by dgirardeau** [comment]
Well, if anyone wants to do it, I'll happily give him/her the rights to do so. Personally, I spend already too much of my (free) time maintaining this project, I am not able to add this kind of chores to my TODO list (_and I'm working on Windows, so I don't have an easy way to create tar.gz files_).

Meanwhile, I would advise anyone to use instead git to pull the right tag and submodules, instead of relying on a tar.gz file 👼
