### ISSUE TITLE
How to open las/laz files on debian-based (debian/ubuntu) distros 

### ISSUE THREAD

**Issue by fghoussen** [CloudCompare/CloudCompare#1726]
**Describe the feature you would like**
Running debian-based (debian/ubuntu) distros, I'd like to be able to open las/laz files (toolbar: file / open / select las file).

**Describe alternatives you've considered**
No solution / alternative found for now

**Is your feature request related to a problem? Please describe.**
On debian, the `CloudCompare` exe from the apt repositories does not allow to open las files.
After googling, seems that to open las files, `CloudCompare` needs to be compiled with both PDAL and QLAS support.

So, I git-cloned  CloudCompare and compiled it from source:
```
>> export CMAKE_PREFIX_PATH=/path/to/laszip-src-3.4.3/local
>> export PDAL_DIR="$CMAKE_MODULE_PATH:/path/to/PDAL/local/lib/cmake/PDAL"
>> cmake -DCMAKE_INSTALL_PREFIX=/path/to/cloudcompare/local -DPLUGIN_IO_QPDAL=ON -DPLUGIN_IO_QLAS=ON ..
>> make all install
```

But even the compiled `CloudCompare` (with PDAL and QLAS suppport) does not allow to open las files.

**Additional context**
Here is the error message I get when trying to open a las file with `CloudCompare` 
![image](https://user-images.githubusercontent.com/20612589/208107270-6a1895f3-182e-4669-a4ef-b2f2a6947b82.png)

Did I get something wrong or do I misuse `CloudCompare`?
Are there more dependencies to add to build-from-source to allow opening las files?

**Comment by dgirardeau** [comment]
I guess your compilation/installation is not complete (have you compile the 'install' project?) as normally either of these plugins should be sufficient to load LAS or LAZ files. And you wouldn't get this message (you can look at the loaded plugin with 'Help > About plugins'.

Not also that with the latest version ('master' branch = version 2.13.alpha) a new plugin qLAS_IO can be compiled. It depends on the lighter LASzip package, and works with any version of LAS/LAZ files (from 1.0 to 1.4, with full-waveform, etc.).

**Comment by fghoussen** [comment]
I'am a very new user. I provided the exact commands I used.

> have you compiled the 'install' project?

How should I do that?
I trying to check out plugins: in toolbars help / about plugins give me 
![image](https://user-images.githubusercontent.com/20612589/208130163-c7eb7e4e-953c-4d77-b938-11c4a750079c.png)

Plugins needs to be compiled and loaded? Can you guide me through that?

**Comment by tmontaigu** [comment]
Can you paste the full log that are in the console window

The problem might be that cloudcompare is not looking for the plugins in the correct repository

**Comment by fghoussen** [comment]
@tmontaigu: seems you're right. How to fix this?

> The problem might be that cloudcompare is not looking for the plugins in the correct repository

![image](https://user-images.githubusercontent.com/20612589/208378569-89f8695f-85eb-4985-b002-fed2cbc1f096.png)

**Comment by fghoussen** [comment]
@tmontaigu: I installed PDAL and laszip the usual way, that is 

For PDAL
```
>> cmake -DCMAKE_INSTALL_PREFIX=/path/to/pdal/local
>> make all install
```

For laszip
```
>> cmake -DCMAKE_INSTALL_PREFIX=/path/to/laszip-src-3.4.3/local
>> make all install
```

And for CloudCompare:
```
>> export CMAKE_PREFIX_PATH=/path/to/laszip-src-3.4.3/local
>> export PDAL_DIR="$CMAKE_MODULE_PATH:/path/to/PDAL/local/lib/cmake/PDAL"
>> cmake -DCMAKE_INSTALL_PREFIX=/path/to/cloudcompare/local -DPLUGIN_IO_QPDAL=ON -DPLUGIN_IO_QLAS=ON ..
>> make all install
```

Following this track, I've just set
```
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/path/to/PDAL/local/lib:/path/to/laszip-src-3.4.3/local/lib"
/path/to/CloudCompare
```

And it works!

![image](https://user-images.githubusercontent.com/20612589/208619270-31a44947-8adb-467a-b688-a7a0bfd251fd.png)


Merci ! :)

**Comment by tmontaigu** [comment]
If you compile the libs yourself, be sure to do so in Relase mode not to lose performances (unless you need to debug something)
