### ISSUE TITLE
The surface I reconstructed in the cloudcompare VS I reconstructed the resulting surface with Poisson reconstruction.Why is the difference between the two meshes so big here? 

### ISSUE THREAD

**Issue by zaoyueri** [CloudCompare/CloudCompare#1732]
![屏幕截图 2022-12-24 164551](https://user-images.githubusercontent.com/115647574/210316627-fba309f8-169f-4008-959a-75d7e0d79f8e.png)
![屏幕截图 2022-12-24 165631](https://user-images.githubusercontent.com/115647574/210316636-a2d1b3a4-1229-455f-beb6-f8503db74c64.png)

**Comment by zaoyueri** [comment]
Why are my own generated meshes so heavily jagged?

**Comment by dgirardeau** [comment]
Do you have large coordinates maybe? Have you accepted the Global Shift suggested by CloudCompare? (and was it sufficient to have all the local coordinates small enough?)

**Comment by zaoyueri** [comment]
![image](https://user-images.githubusercontent.com/115647574/210326543-b32c8c40-004e-4071-85b4-a6d377ba9c74.png)
Professor, I think there is something wrong with the values of y, they are distributed in specific values. Could this be the cause of the jaggedness?

**Comment by zaoyueri** [comment]
yeah，I have.

**Comment by dgirardeau** [comment]
Make sure the Global Shift is sufficient (i.e. something around (-403000; -3604900; -1000.0) so that the local coordinates are small enough, and there's no loss of precision once the points are imported in CloudCompare.

**Comment by zaoyueri** [comment]
Can the local coordinates after the global offset be exported? I'm trying to export local coordinates for use.

**Comment by dgirardeau** [comment]
If you want to export the local coordinates only, you have to 'remove' the Global Shift with 'Edit > Edit Global Shift & Scale' and set all values to 0.

![image](https://user-images.githubusercontent.com/2735509/210355872-0acecb8f-fe22-44a3-925e-c4023ad1e2ae.png)

**Comment by dgirardeau** [comment]
Ah in this case this is what will happen by default. The Global Shift is only applied temporarily while the cloud is loaded in CloudCompare, and original coordinates are restored when exported to a file.

**Comment by zaoyueri** [comment]
Thank you for your reply, then it seems that I need to figure out how to export the coordinates after global offset myself.

**Comment by dgirardeau** [comment]
Not sure to understand. You don't have to do anything (it's automatic, when you save the cloud or the mesh). Mind that some rare formats don't support large coordinates (such as STL).
