### ISSUE TITLE
Fail to display more then one polyline load from bin file

### ISSUE THREAD

**Issue by zhangzscn** [CloudCompare/CloudCompare#1738]
**Describe the bug**

When drawing multiple polyline on the point cloud, and then saving these polylines and the point cloud as a bin format file, when the bin file is read again, only one polyline can be displayed on the software。
**How to reproduce**

**Expected behaviour**

**Additional context**

**Your environment**
 - CC Version (or git hash/tag):2.11.1
 - OS & Version:ubuntu 22.04.1
 - Graphics card: 4090
 - Qt Version (if compiling): 5.9.5

**Comment by dgirardeau** [comment]
Can you give us a little bit more context? Maybe share the bin file with us?

**Comment by zhangzscn** [comment]
[test.zip](https://github.com/CloudCompare/CloudCompare/files/10398511/test.zip)
@dgirardeau

**Comment by dgirardeau** [comment]
Thanks. I can see 2 polylines in this file, but twice the same.

Maybe it's related to how the entities were selected at saving time. Only the highlighted entities and their children are saved in a BIN file. So you have either to select all the entities at once (CTRL+A), or at least select all the top level entities.

**Comment by zhangzscn** [comment]
select all the entities at once (CTRL+A), or at least select all the top level entities, don't work, you can try it.

**Comment by dgirardeau** [comment]
Once again, you'll have to give us more context, as it works fine on my side. See attached example.
[export_polylines.zip](https://github.com/CloudCompare/CloudCompare/files/10409155/export_polylines.zip)
