### ISSUE TITLE
Support needed to load PCD files in hidden directories that contains "." in Ubuntu Linux

### ISSUE THREAD

**Issue by hanzheteng** [CloudCompare/CloudCompare#1743]
**Describe the feature you would like**
Provide support to read and write to paths that contain hidden directories (i.e. those names starting with a ".") in Ubuntu Linux.

**Describe alternatives you've considered**
Please at least add a meaningful error message to let users know what to do next (i.e. move files to another path).

**Is your feature request related to a problem? Please describe.**
I saved a PCD file using PCL interfaces in C++ and was trying to view it in CloudCompare. I just opened CC and dragged the file into the software. Then it provided me with the following error messages.
```
[17:31:35] /home/hteng/.ros/1674498827.pcd: Point Count: 0
[17:31:35] [PCL] An error occurred while converting PCD cloud to CloudCompare cloud!     [text in dark red]
[17:31:35] An error occurred while loading '1674498827': see console       [text in bright red]
```
I was frustrated after trying a few more means, i.e. to change the file saving mode (binary, ascii), point types in the cloud, etc. 
In the end, I happened to figure out that the issue was on the path! After I moved the file to another location, it worked just fine.
```
[17:32:20] /home/hteng/Documents/test/1674498827.pcd: Point Count: 76106
[17:32:20] [I/O] File '/home/hteng/Documents/test/1674498827.pcd' loaded successfully
```

Environment:
 - CC Version (or git hash/tag): 2.11.1 (Anoia)
 - OS & Version: installed from Snap store in Ubuntu 20.04 
 - Graphics card: Intel® Iris(R) Plus Graphics 655

**Additional context**
I understand that this ".ros" folder name in the path might be a pain, but it is really ubiquitous in Linux. If it is very hard to provide support for this, please at least provide a meaningful error message to users.

**Comment by dgirardeau** [comment]
This has been discussed several times. I believe this is not a CloudCompare limitation, but a more general Snap limitation (see https://askubuntu.com/questions/1033344/how-to-give-snaps-access-to-somedir for instance).

Have you tried the flatpak version of CC instead (+ it's the only one supported now).

**Comment by hanzheteng** [comment]
Thanks for your advice. The flatpak version of CC solved this issue. Thanks!
