### ISSUE TITLE
Custom plug-in compilation failed

### ISSUE THREAD

**Issue by improve100** [CloudCompare/CloudCompare#1751]
I am imitating the qcv plug-in to customize my own plug-in, but the compiler has reported this error all the time. Who has experience can guide me,thank you!

/home/xxx/3rdparty/CloudCompare/plugins/example/TestPlugin/src/TestPlugin.cpp: In member function ‘virtual QList<QAction*> TestPlugin::getActions()’:
/home/xxx/3rdparty/CloudCompare/plugins/example/TestPlugin/src/TestPlugin.cpp:91:45: error: no matching function for call to ‘TestPluginDlg::TestPluginDlg(QMainWindow*)’
     TestPluginDlg dlg(m_app->getMainWindow());
                                             ^
In file included from /home/xxx/3rdparty/CloudCompare/plugins/example/TestPlugin/src/TestPlugin.cpp:38:0:
/home/xxx/3rdparty/CloudCompare/plugins/example/TestPlugin/include/TestPluginDlg.h:27:11: note: candidate: TestPluginDlg::TestPluginDlg(QWidget*)
  explicit TestPluginDlg(QWidget* parent = nullptr);
           ^
/home/xxx/3rdparty/CloudCompare/plugins/example/TestPlugin/include/TestPluginDlg.h:27:11: note:   no known conversion for argument 1 from ‘QMainWindow*’ to ‘QWidget*’
plugins/example/TestPlugin/CMakeFiles/TestPlugin.dir/build.make:109: recipe for target 'plugins/example/TestPlugin/CMakeFiles/TestPlugin.dir/src/TestPlugin.cpp.o' failed
make[2]: *** [plugins/example/TestPlugin/CMakeFiles/TestPlugin.dir/src/TestPlugin.cpp.o] Error 1
CMakeFiles/Makefile2:3041: recipe for target 'plugins/example/TestPlugin/CMakeFiles/TestPlugin.dir/all' failed
make[1]: *** [plugins/example/TestPlugin/CMakeFiles/TestPlugin.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dgirardeau** [comment]
I would guess that you need to include the Qt header for QMainWindow maybe?

(else, I'll need to see some code to understand what happens ;) )

**Comment by improve100** [comment]
Thank you very much for your reply. This is my test code.
[TestPlugin.zip](https://github.com/CloudCompare/CloudCompare/files/10811524/TestPlugin.zip)

**Comment by dgirardeau** [comment]
I was not able to read these files. Maybe an issue with the way it's zipped?

Anyway, have you tried to include <QMainWindow> ?

**Comment by improve100** [comment]
I tried to add #include <QMainWindow>,
the compiler does not report an error. 
Thank you for your reply!
