### ISSUE TITLE
Define an 'up direction' to compute signed roughness values via command line

### ISSUE THREAD

**Issue by killickm** [CloudCompare/CloudCompare#1755]
I would like to be able to compute signed roughness via the command line.

[Command](https://www.cloudcompare.org/doc/wiki/index.php/Command_line_mode) `-ROUGH {kernel size}` only takes the radius parameter, I would like to also be able to specify I want a signed distance with default direction (x=0, y=0, z=1), and the option to change the up direction.

At the moment I believe this option is currently only available via the GUI (#1572).
![image](https://user-images.githubusercontent.com/62104891/221444412-de6be076-e7d7-441f-9abf-1dd6c2159db5.png)

Thank you
Matt

**Comment by HeadLessHUN** [comment]
It seems to be existing feature, but not documented.

-ROUGH {kernel size} -UP_DIR {x} {y} {z}

@dgirardeau documentation needs updated, otherwise implemented, but not tested.

**Comment by dgirardeau** [comment]
Good catch! What a shame, it seems I forgot to report that the work has been done 😅  (and to update the wiki).

I've updated the wiki.
