### ISSUE TITLE
Kriging is not submitted 

### ISSUE THREAD

**Issue by cuttingdust** [CloudCompare/CloudCompare#1759]
**Describe the bug**

Kriging is not submitted 

![image](https://user-images.githubusercontent.com/46484327/223002407-24f46a5c-87ba-46d8-b643-3cfcb603741a.png)

**How to reproduce**

**Expected behaviour**

**Additional context**

**Your environment**
 - CC Version (or git hash/tag): git tag 1ae2611e 
 - OS & Version: * windows10 *  
 - Graphics card: * GTX 1050 *
 - Qt Version (if compiling): * 5.15.2 *

**Comment by dgirardeau** [comment]
Have you updated your submodules?

**Comment by cuttingdust** [comment]
Oh, I forgot. Thank you, I see
