### ISSUE TITLE
SVG icon rendered incorrectly

### ISSUE THREAD

**Issue by christian-rauch** [CloudCompare/CloudCompare#1760]
**Describe the bug**
The SVG icons (https://github.com/CloudCompare/CloudCompare/blob/master/qCC/images/icon/cc_icon.svg, https://github.com/CloudCompare/CloudCompare/blob/master/qCC/images/icon/cc_viewer_icon.svg) are rendered incorrectly.

**How to reproduce**

Open the SVG icons in Firefox on Ubuntu. In my setting, this looks like:

![svg_render_firefox](https://user-images.githubusercontent.com/8226248/224516581-fe27aff6-8f5f-44fa-a726-28f7ddd94c55.png)

**Expected behaviour**
The SVG icons should render like the PNG files.

**Additional context**
This was originally reported as https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6495 but it seems that this is an issue with the SVG.

**Your environment**
 - OS & Version: Ubuntu 22.04.2 LTS

**Comment by gucr** [comment]
I can confirm, the icon is not rendered correctly in Firefox & Chrome on Osx either.
After looking into the SVG code, the "CC" is not outlined and requires the availability of the Mangal font family.

Also, the svg image is 370KB. I can fix it & reduce its size under a KB if needed. Happy to make a PR

**Comment by dgirardeau** [comment]
Thanks, don't hesitate to make a PR indeed!
