### ISSUE TITLE
Large Clouds - Can't Transform Manually

### ISSUE THREAD

**Issue by rukie** [CloudCompare/CloudCompare#1762]
**Describe the bug**
When loading extremely large clouds (>50 million points) I cannot manually translate them. I get stuck with calculating new LoDs each time I interact with the cloud, but it does not actually move/transform. I can spin, rotate, and view perfectly fine, but I cannot transform the clouds against each other. 

**How to reproduce**
Open 2 extremely large clouds (pcd format, about 1.4 gb in size)
Select the appropriate cloud
Use the red transform icon
Attempt to transform cloud into rough alignment.

**Expected behaviour**
I should be able to 'roughly' align my clouds.

**Additional Context**

**Your environment**
 - CC 2.12 Beta
 - Windows 10.0.19044
 - Nvidia Quadro RTX 4000

** Possible quick fixes?
Is there a possibility of locking the displayed Level of Detail (LoD)?
Is there a method to translate/rotate through manually input values?

**Comment by dgirardeau** [comment]
Is it with the 2.12 beta or the 2.13 beta?

I can't reproduce the issue with the 2.13 beta. And I'm not sure to see the link with the LoD mechanism anyway. Can you try to deactivate it? (with 'Display > Display settings' and then uncheck the 'When moved, decimate clouds over XXX points' option).

Make sure also you select only one cloud when using the 'Edit > Translate / rotate' tool (and not a group/folder for instance).

**Comment by rukie** [comment]
![image](https://user-images.githubusercontent.com/6559628/225426538-0e2c1c0f-2d4c-44eb-ae01-19b7775b42bb.png)

To clarify, I can spin it with rotate about xyz. But Translation does not work.

**Comment by dgirardeau** [comment]
Are you keeping the red button pressed to translate the highlighted cloud?

**Comment by rukie** [comment]
I seem to have trouble reproducing the issue. Closing.
