### ISSUE TITLE
What is the principle for calculating the distance from a point cloud cloud to a mesh?

### ISSUE THREAD

**Issue by zaoyueri** [CloudCompare/CloudCompare#1768]
Find the nearest neighbor patch of a point in the mesh?

**Comment by dgirardeau** [comment]
Nope, for each point of the cloud, we find the 'nearest' triangle. The distance from a point to a triangle is defined as in https://www.geometrictools.com/Documentation/DistancePoint3Triangle3.pdf

**Comment by zaoyueri** [comment]
![image](https://user-images.githubusercontent.com/115647574/229993590-18173dab-2705-495e-a20d-1b416b64cca9.png)
The distance calculation between the surface generated by Poisson reconstruction and the original point cloud shows a maximum distance of 23.4554. By observing the presence of triangles near the points where these maximum distances are located, what is the unit?

**Comment by dgirardeau** [comment]
The units are the same than those of the original point coordinates (CC doesn't know about the units, as it's not specified in most of the file formats). So CC will compute and display the distances in the same implicit 'units'.

If you think there's a point which has a larger distance than what it should have, don't hesitate to share the files with me.

**Comment by zaoyueri** [comment]
In the distance calculation function, the time required for distance estimation is much shorter than the subsequent calculations. Is the result of distance estimation the one-way Hausdorff distance calculated by octree segmentation?I understand that the subsequent calculations are based on the principle of point to nearest neighbor patches.

**Comment by dgirardeau** [comment]
Are you still speaking about the point to mesh distance calculation? I'm not fully sure to understand the difference between "distance calculation function" and "subsequent calculations" (what are these "subsequent calculations" exactly?

**Comment by zaoyueri** [comment]
In fact, I would like to ask what is the difference between the calculation principles of "distance estimation" and "calculation".Usually, users use the value obtained from "distance estimation" as the threshold for subsequent calculations.

**Comment by dgirardeau** [comment]
Ah, you mean the "approximate distances". They are derived from a distance map (a regular 3D grid, in which distances are 'propagated' in very fast way). But they are very approximate... You can see the estimation of the error in the last panel of the Distance computation dialog. Basically, it's the largest dimension of the bounding box divide by a 128 or 256.

For more information about the way distance maps are computed, refer to "Chamfer distance transform".
