### ISSUE TITLE
Symlink following is too aggressive when opening OBJ+MTL

### ISSUE THREAD

**Issue by nh2** [CloudCompare/CloudCompare#1772]
**Describe the bug**

CloudCompare fails to open a pair of `.obj`+`.mtl` files when these two are symlinks into separate directories:

![image](https://user-images.githubusercontent.com/399535/231237614-f4e3d1b0-dd55-42c0-8429-051b30fc8e06.png)

Error: `[OBJ] Failed to load material file!`

Other programs, such as Meshlab, succeed opening in this case.

The issue here is most likely that CloudCompare resolves symlinks too aggressively itself.
Likely, CloudCompare should not follow a symlink and then open the OBJ from the dereferenced file's parent folder; instead it should simply `open()` the symlink itself and let the OS derefence it.

**How to reproduce**

Repro scenario:

```
% tree
.
├── joined-symlinks-dir
│   ├── untitled.mtl -> ../mtl-dir/untitled.mtl
│   └── untitled.obj -> ../obj-dir/untitled.obj
├── mtl-dir
│   └── untitled.mtl
└── obj-dir
    └── untitled.obj
```

Repro as a tar: [obj-symlink-test.tar.zip](https://github.com/CloudCompare/CloudCompare/files/11203061/obj-symlink-test.tar.zip)

**Expected behaviour**

CloudCompare opens symlinked OBJs just as well as Meshlab.

**Your environment**
 - CC Version (or git hash/tag): 2.12.1
 - OS & Version: Ubuntu 22.04.1

Thanks!

**Comment by dgirardeau** [comment]
Well, Qt is doing all the job here... I guess the issue might come from the call to QFileInfo::canonicalPath?
https://github.com/CloudCompare/CloudCompare/blob/master/plugins/core/IO/qCoreIO/src/ObjFilter.cpp#L1137

**Comment by nh2** [comment]
Thanks for the pointer.

Yes, that seems to be the issue. Just [`.path()`](https://doc.qt.io/qt-6/qfileinfo.html#path) should be enough here.

The `.obj` is also opened as a relative path if given as such, here:

https://github.com/CloudCompare/CloudCompare/blob/ff67e236d6c29db172422d1f5a77cae0f968c2bf/plugins/core/IO/qCoreIO/src/ObjFilter.cpp#L489

confirmed via `strace -fy -e open,openat`:

```
openat(AT_FDCWD</home/niklas/tmp/obj-symlink-test>, "joined-symlinks-dir/untitled.obj", O_RDONLY|O_CLOEXEC) = 23</home/niklas/tmp/obj-symlink-test/obj-dir/untitled.obj>
```

so opening the `.mtl` without without aboluting or canonicalising the `.obj`'s path should work equally well.

---

PR is in #1775.

**Comment by dgirardeau** [comment]
Ah, I already changed the code on my side. And it was a little bit trickier than that, as when loading the files via the Loading dialog, symbolic links were also resolved. See https://github.com/CloudCompare/CloudCompare/commit/0fb46ddb6fd3ed35ddb7c92a8b8befb141b87668#diff-118975ad9a78954af9c80785ac1a7b5c5e2486f5466712dd322e8c01e5a6bf85R177

(I also took the opportunity to clean some code ;) ).

**Comment by nh2** [comment]
Ah, thanks!

**Comment by dgirardeau** [comment]
For reference, the latest 2.13.alpha version (for Windows) that incorporates this change has been updated.
