### ISSUE TITLE
Plugins not picked up for simple cmake build/install

### ISSUE THREAD

**Issue by nh2** [CloudCompare/CloudCompare#1776]
As an aside from #1772, in case it helps the project:

I had some trouble on Linux getting the built CloudCompare to use the IO plugin that contains this code.

I built with

```sh
cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt/cloudcompare .. 
cmake --build .
cmake --install . 
```

but neither `./qCC/CloudCompare` nor `/home/niklas/opt/cloudcompare/bin/CloudCompare` would pick up the IO plugin (`libQCORE_IO_PLUGIN.so`) automatically.

Instead, they'd pick up my system's plugin from `/usr/lib/x86_64-linux-gnu/cloudcompare/plugins/libQCORE_IO_PLUGIN.so` which is quite wrong because it is for a much older CloudCompare version.

When deleting my system CloudCompare, no IO plugin would load at all so OBJ loading would not be possible.

The only workaround I found was

```sh
mkdir -p /home/niklas/opt/cloudcompare/lib/x86_64-linux-gnu/cloudcompare/
cd /home/niklas/opt/cloudcompare/lib/x86_64-linux-gnu/cloudcompare/
ln -s ../../../lib/cloudcompare/plugins .
```

It would be nice if a a build CloudCompare picked up the correct libraries directly from the build and install dir.

**Comment by nh2** [comment]
Sorry, I should say that this happend for the version `2.11.3-4` that I got with `apt-get source` on Ubuntu 22.04.1 because that was the easiest to build on this machine to quickly test #1772.

If this issue is already fixed in a newer version, please close :)

**Comment by dgirardeau** [comment]
As I am a complete Linux-n00b, I'll have to rely on the experts: @rjanvier and @tmontaigu ;)

**Comment by nh2** [comment]
I think it's related to this code:

https://github.com/CloudCompare/CloudCompare/blob/0fb46ddb6fd3ed35ddb7c92a8b8befb141b87668/libs/CCAppCommon/src/ccApplicationBase.cpp#L215-L229

## 1. `cmake --install .` case

In my `apt-get source` build tree, this line is changed:

```diff
-		m_PluginPaths << (theDir.absolutePath() + "/lib/cloudcompare/plugins");
+		m_PluginPaths << (theDir.absolutePath() + "/lib/x86_64-linux-gnu/cloudcompare/plugins");
```

That is why it doesn't work for the `cmake --install .` case: `x86_64-linux-gnu/` does not exist.

I have verified that this problem does not exist when building directly from the upstream source, tag `v2.11.3`.

This suggest it's the debian packagers fault for performing that `cloudcompare` -> `x86_64-linux-gnu/cloudcompare` source code replacement (though maybe they think that hardcode is OK and that installation via `apt-get source` + `cmake --install .` is out of scope).

## 2. Running straight from `qCC/CloudCompare`

This happens also for the upstream source tag `v2.11.3`.

In the `build/` dir, the plugin is at `plugins/core/IO/qCoreIO/libQCORE_IO_PLUGIN.so`.

So maybe the CMake build should assemble a `plugins/` dir in the build tree into which all plugins are copied or symlinked at `cmake --build .` time.

Then the above code could `m_PluginPaths <<` that dir.

**Comment by rjanvier** [comment]
Hey Niklas, thanks for noticing that.

I think @alexmyczko took the source package I made long time ago for @ArcheOS and is responsible for uploading and maintaining the package for Debian (an thus ubuntu) maybe you can see with him, if it's package related. You can check in the Debian/patches of the directory if there is a patch that is currently induicing this behavior. 

About the upstream behavior, I think maybe @tmontaigu or somoene else changed things in path handling in 2.12 or 2.13 so it's maybe fixed, but I was no longer an active contributor at this time so I do not remember well and I am no longuer a 100% linux user. Feel free to propose a patch if you think it's still the current behavior in the current master branch.

**Comment by tmontaigu** [comment]
On my linux the master branch of cloudcompare almost correctly picks up the plugins when I start the "installed" CloudCompare binary. (It tries to load from `(theDir.absolutePath() + "/lib/cloudcompare/plugins");` when my plugins are at `(theDir.absolutePath() + "/lib64/cloudcompare/plugins");`


Also we have since last year the `CC_PLUGIN_PATH` env var which allows you to specify additional paths in which cloudcompare should look for plugins

**Comment by nh2** [comment]
@tmontaigu Yes, that also works for me from master with installing, see https://github.com/CloudCompare/CloudCompare/issues/1776#issuecomment-1512027604. It was the "installed" with Debian sources that didn't because it changes the loouph path in the code.

So only for "built" CloudCompare does it not work yet.

`CC_PLUGIN_PATH` sounds good, but I guess it would still be convenient if the built would produce a single `plugins/` dir that this could be set to by default.

**Comment by dgirardeau** [comment]
On Windows as well, you should not expect things to work by only building the project. Installing is required (as per the BUILD instruction).
