### ISSUE TITLE
Version number is not correctly updated on latest builds (alpha build date)

### ISSUE THREAD

**Issue by ryukisai** [CloudCompare/CloudCompare#1777]
**Description**
Lately, a date has been added to the title bar of CC, and also to the about menu.
This is really helpful for alpha build tests.
The issue is that the date’s been wrong in both versions 2023-04-06 and 2023-04-17 (the current one). See caption.
I’m guessing that the script does not properly update the date at build time.

Sidenote, i think using the ISO 8601 date format would be great but that’s just a personal preference. It’s just better for sorting imho.
See https://en.wikipedia.org/wiki/ISO_8601

**How to reproduce**
Install the latest build of CC (alpha channel).

**Expected behaviour**
The current build should display its actual build date and not "(Apr  2 2023)".

**Environment**
 - CC Version (or git hash/tag): alpha builds 2023-04-06 and 2023-04-17
 - OS & Version: Win11 pro x64 22H2 (tested on 2 computers with the same OS version)

Thanks in advance!

![2023-04-19 15_12_51-CloudCompare](https://user-images.githubusercontent.com/6038397/233088334-834aa741-ab0b-43c1-95fe-728fdc665363.png)

**Comment by dgirardeau** [comment]
Good catch, it's actually because I don't recompile the .cpp file in which this code is interpreted. I need to force its compilation each time one way or another...

**Comment by dgirardeau** [comment]
1fb63dfaf4e0cc06daf31fe6c908143dae1e7b4a should fix this.

**Comment by ryukisai** [comment]
Thanks Daniel!
