### ISSUE TITLE
Class or Fragment of code to read *.BIN and extract X,Y,Z

### ISSUE THREAD

**Issue by marcel-bariou** [CloudCompare/CloudCompare#1780]
Hello thanks for your work.
Is in the WIKI, on the BIN page, are Header and data descriptor correct ? If not have you you somewhere an updated Header and data descriptor for your *.BIN format , because it seems very difficult to deciphered in  your header file binFilter, FileIOFilter and other cchObjet. Thanks!

**Comment by dgirardeau** [comment]
Thanks for the donation!
