### ISSUE TITLE
Command Line - Rasterize with empty_fill Interp - not interpolating

### ISSUE THREAD

**Issue by cpmessina** [CloudCompare/CloudCompare#1784]
**Describe the bug**
Rasterizing from the command line with "-EMPTY_FILL INTERP" results in a geotiff that's not interpolated. It comes out the same as 'leave cells empty'.

Choosing the appropriate options in the GUI results in an interpolated image, as expected.

**How to reproduce**

cloudcompare.exe -SILENT -AUTO_SAVE OFF -O -GLOBAL_SHIFT AUTO temp-inner.las -RASTERIZE -GRID_STEP .252 -VERT_DIR 2 -PROJ AVG -SF_PROJ AVG -MAX_EDGE_LENGTH 1 -EMPTY_FILL INTERP -OUTPUT_RASTER_Z

**Expected behaviour**

The resulting geotiff image should be the same as what the GUI puts out.

**Additional context**
GUI Settings:
![image](https://github.com/CloudCompare/CloudCompare/assets/16737358/99d8b34a-4d7e-4065-9f69-73cfaae2e6e0)

Good image result from GUI: 
![image](https://github.com/CloudCompare/CloudCompare/assets/16737358/3f1b19db-d215-4250-a530-accc25c0053e)

Bad image result from command line:
![image](https://github.com/CloudCompare/CloudCompare/assets/16737358/a88c2e27-2938-445a-bb60-3c45d3c80570)

**Your environment**
 - CC Version (or git hash/tag): v2.13.alpha (same result in older versions)
 - OS & Version: Win 10 Pro
 - Graphics card: NVidia GeForce 1660 SUPER
 - Qt Version (if compiling): n/a

**Comment by dgirardeau** [comment]
On my side it works. Are you sure about the "-MAX_EDGE_LENGTH 1" setting? It's quite small compared to the cell size (0.252). Which means that only small 3-cells wide holes or less would be filled...

What's the value in the GUI version? (you have to click on the gear icon next to the 'interpolate' drop down menu.

**Comment by cpmessina** [comment]
That's definitely having an affect on it!

I've been overlooking that gear icon - it looked grayed out/disabled, but sure enough it opens and actually says 0.000001 in there. Using that number had no better result, but...

I'm playing around with larger numbers on the command line and it's filling in like it should.

Issue is PEBKAC, not program related.  Thank you for the quick assist!
