### ISSUE TITLE
Accessing individual polyline store in a single SHP file for cropping a point cloud

### ISSUE THREAD

**Issue by giplessis** [CloudCompare/CloudCompare#1789]
Hi, all

Is there a way to access to the individual polyline stored in a single SHP file for cropping a point cloud.
something like : 

```
c_cropped_list=list()
polys = cc.loadPolyline(filename=myfilepath, mode=cc.CC_SHIFT_MODE.XYZ)
for poly in polys:
    c_cropped_list.append(cloud.crop2D(poly, 2, True))
```
  
**Context :** 
I've a SHP file containing potentially multiple polygones. I want to load and use them for cropping a point cloud. 
I work perfectly when my SHP file contains only one polygone but gave me only the first one when it contains multiple polygones.

**Comment by dgirardeau** [comment]
Is it a question about CloudCompy maybe? (if yes, then the question should be asked here: https://github.com/CloudCompare/CloudComPy/issues)

**Comment by giplessis** [comment]
You're right, my mistake. I post it to the CloudComPy repository.
Best regards,
