### ISSUE TITLE
CC crashing with Rasterize tool

### ISSUE THREAD

**Issue by xyleme** [CloudCompare/CloudCompare#1793]
Whenever I try to start the Rasterize tool, CloudCompare crashes.

Steps to reproduce the behaviour:
1. Open CC
2. import a point cloud
3. Tools>Projection>Rasterize

Context:
 - CC Version: 2.12.4 (Kyiv) [Linux 64-bit]
 - OS: Debian GNU/Linux 11 (bullseye)
 - Graphics card: Nvidia Quadro P1000

After much pain compiling every new version of CC on my Debian, I gave up, now running latest flatpak versions (so much easier, thanks :+1:). When started from a terminal, I can read the following error message after it crashed:
`flatpak run org.cloudcompare.CloudCompare`
[.../...]
`CloudCompare: /run/build/CloudCompare/libs/qCC_db/src/ccRasterGrid.cpp :88 : static bool ccRasterGrid::ComputeGridSize(unsigned char, const ccBBox&, double, unsigned int&, unsigned int&):  l'assertion « false » a échoué.`
Hope this helps,
Yours,
V.

**Comment by dgirardeau** [comment]
Are you able to run the latest 2.13.alpha version with Flatpak? I believe this may have been fixed already.

**Comment by xyleme** [comment]
As I'm quite new to flatpak, I fear I missed something about the ability to pick a specific version on flathub. My guess is I can only access the latest stable, am I wrong?
Another solution is to compile from sources, but it's always a bit tricky...

**Comment by xyleme** [comment]
Yes, compiling 2.13.alpha solves the issue.
