### ISSUE TITLE
Compilation of cloudcompare-2.13 occurred a error .

### ISSUE THREAD

**Issue by zhangjian58** [CloudCompare/CloudCompare#1794]
**Describe the bug**

Compilation of cloudcompare-2.13 occurred a error . CMake message "Error in configuration process, project files may be invalid". I use VS2017 x64 ,QT5.9,CMake 3.26.Thanks!
**How to reproduce**

**Expected behaviour**

**Additional context**

**Your environment**
 - CC Version (or git hash/tag):2.13
 - OS & Version:windows10
 - Graphics card: 
 - Qt Version (if compiling): 5.9

**Comment by zhangjian58** [comment]
what  versin of VS or QT for compilation of cloudcompare-2.13?

**Comment by dgirardeau** [comment]
Maybe you could share the error with us?

Anyway, it would be safre to user Qt 5.12 or Qt5.15 (64 bits).

**Comment by zhangjian58** [comment]
follow CMake Message
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19045.
OpenMP found
Install shared library: CCAppCommon
Install shared library: CC_FBO_LIB
Install shared library: CCPluginAPI
CMake Error at libs/qCC_db/CMakeLists.txt:8 (add_subdirectory):
  The source directory

    D:/cloudcompare/CloudCompare-2.13.alpha.230227/libs/qCC_db/extern/CCCoreLib

  does not contain a CMakeLists.txt file.


Install shared library: CCCoreLib
CMake Error at cmake/Install.cmake:222 (install):
  install TARGETS given target "CCCoreLib" which does not exist.
Call Stack (most recent call first):
  cmake/Install.cmake:31 (_InstallSharedTarget)
  libs/qCC_db/CMakeLists.txt:21 (InstallSharedLibrary)


CMake Error at cmake/Install.cmake:228 (install):
  install TARGETS given target "CCCoreLib" which does not exist.
Call Stack (most recent call first):
  cmake/Install.cmake:31 (_InstallSharedTarget)
  libs/qCC_db/CMakeLists.txt:21 (InstallSharedLibrary)


CMake Error at cmake/Install.cmake:234 (install):
  install TARGETS given target "CCCoreLib" which does not exist.
Call Stack (most recent call first):
  cmake/Install.cmake:31 (_InstallSharedTarget)
  libs/qCC_db/CMakeLists.txt:21 (InstallSharedLibrary)


CMake Error at cmake/Install.cmake:222 (install):
  install TARGETS given target "CCCoreLib" which does not exist.
Call Stack (most recent call first):
  cmake/Install.cmake:31 (_InstallSharedTarget)
  libs/qCC_db/CMakeLists.txt:21 (InstallSharedLibrary)


CMake Error at cmake/Install.cmake:228 (install):
  install TARGETS given target "CCCoreLib" which does not exist.
Call Stack (most recent call first):
  cmake/Install.cmake:31 (_InstallSharedTarget)
  libs/qCC_db/CMakeLists.txt:21 (InstallSharedLibrary)


CMake Error at cmake/Install.cmake:234 (install):
  install TARGETS given target "CCCoreLib" which does not exist.
Call Stack (most recent call first):
  cmake/Install.cmake:31 (_InstallSharedTarget)
  libs/qCC_db/CMakeLists.txt:21 (InstallSharedLibrary)


Install shared library: QCC_DB_LIB
Install shared library: QCC_GL_LIB
Install shared library: QCC_IO_LIB
Added io plugin: QCORE_IO_PLUGIN
Install plugins
 Types: gl;io;standard
 Destination: CloudCompare/plugins
 Shader Destination: CloudCompare/shaders
 Install QCORE_IO_PLUGIN (io)
Installing CloudCompare to CloudCompare
Installing ccViewer to ccViewer
Install plugins
 Types: gl;io
 Destination: ccViewer/plugins
 Shader Destination: ccViewer/shaders
 Install QCORE_IO_PLUGIN (io)
Configuring incomplete, errors occurred!
And follow CMake Picture
![微信截图_20230529155429](https://github.com/CloudCompare/CloudCompare/assets/68043992/16b362b5-b2cf-4876-b00a-26d01a7670ff)
![微信截图_20230529155445](https://github.com/CloudCompare/CloudCompare/assets/68043992/97c45ce9-6473-4b1a-8d16-26c2a894f3ea)

**Comment by zhangjian58** [comment]
follow CMake message
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19045.
OpenMP found
Install shared library: CCAppCommon
Install shared library: CC_FBO_LIB
Install shared library: CCPluginAPI
CMake Error at libs/qCC_db/CMakeLists.txt:8 (add_subdirectory):
  The source directory

    D:/cloudcompare/CloudCompare-2.13.alpha.230227/libs/qCC_db/extern/CCCoreLib

  does not contain a CMakeLists.txt file.


Install shared library: CCCoreLib
CMake Error at cmake/Install.cmake:222 (install):
  install TARGETS given target "CCCoreLib" which does not exist.
Call Stack (most recent call first):
  cmake/Install.cmake:31 (_InstallSharedTarget)
  libs/qCC_db/CMakeLists.txt:21 (InstallSharedLibrary)


CMake Error at cmake/Install.cmake:228 (install):
  install TARGETS given target "CCCoreLib" which does not exist.
Call Stack (most recent call first):
  cmake/Install.cmake:31 (_InstallSharedTarget)
  libs/qCC_db/CMakeLists.txt:21 (InstallSharedLibrary)


CMake Error at cmake/Install.cmake:234 (install):
  install TARGETS given target "CCCoreLib" which does not exist.
Call Stack (most recent call first):
  cmake/Install.cmake:31 (_InstallSharedTarget)
  libs/qCC_db/CMakeLists.txt:21 (InstallSharedLibrary)


CMake Error at cmake/Install.cmake:222 (install):
  install TARGETS given target "CCCoreLib" which does not exist.
Call Stack (most recent call first):
  cmake/Install.cmake:31 (_InstallSharedTarget)
  libs/qCC_db/CMakeLists.txt:21 (InstallSharedLibrary)


CMake Error at cmake/Install.cmake:228 (install):
  install TARGETS given target "CCCoreLib" which does not exist.
Call Stack (most recent call first):
  cmake/Install.cmake:31 (_InstallSharedTarget)
  libs/qCC_db/CMakeLists.txt:21 (InstallSharedLibrary)


CMake Error at cmake/Install.cmake:234 (install):
  install TARGETS given target "CCCoreLib" which does not exist.
Call Stack (most recent call first):
  cmake/Install.cmake:31 (_InstallSharedTarget)
  libs/qCC_db/CMakeLists.txt:21 (InstallSharedLibrary)


Install shared library: QCC_DB_LIB
Install shared library: QCC_GL_LIB
Install shared library: QCC_IO_LIB
Added io plugin: QCORE_IO_PLUGIN
Install plugins
 Types: gl;io;standard
 Destination: CloudCompare/plugins
 Shader Destination: CloudCompare/shaders
 Install QCORE_IO_PLUGIN (io)
Installing CloudCompare to CloudCompare
Installing ccViewer to ccViewer
Install plugins
 Types: gl;io
 Destination: ccViewer/plugins
 Shader Destination: ccViewer/shaders
 Install QCORE_IO_PLUGIN (io)
Configuring incomplete, errors occurred!


follow the CMake picture
![微信截图_20230529161337](https://github.com/CloudCompare/CloudCompare/assets/68043992/18a43f95-a85c-4dbd-85dc-a8c7b4cdda9d)
![微信截图_20230529161345](https://github.com/CloudCompare/CloudCompare/assets/68043992/3df973b5-6c98-4c6f-98ad-f86492ed16dc)

**Comment by dgirardeau** [comment]
Seems to me that you haven't pulled the submodules properly? It seems the CCCoreLib folder is empty?

**Comment by zhangjian58** [comment]
i check the CCCoreLib folder ，it‘s empty，i download another CC source code ,it works,but another error occurred 
CMake Error at libs/qCC_db/extern/CCCoreLib/CMakeLists.txt:138 (add_subdirectory):
  The source directory

    D:/cloudcompare/CloudCompare-v2.13.alpha.230227/CloudCompare/libs/qCC_db/extern/CCCoreLib/extern/nanoflann

  does not contain a CMakeLists.txt file.



however , in the CC source code ,nanoflann folder is empty.

**Comment by dgirardeau** [comment]
You should use git to retrieve the sources, not download them (otherwise you'll have to download each submodule one by one, and also submodules of submodules...).

With git, it's only one command (and the important part of the command is '--recursive' ;) ).

**Comment by zhangjian58** [comment]
it works!thanks!
