### ISSUE TITLE
Normal vector arrow display

### ISSUE THREAD

**Issue by improve100** [CloudCompare/CloudCompare#1800]
When I use the menu bar Edit->Normal->Compute to get normal vectors, the normal vectors displayed in the main window are black dots and cannot display arrows
![image](https://github.com/CloudCompare/CloudCompare/assets/6092914/fe19fa38-906b-4057-829a-250c09bc46a8)

**Comment by dgirardeau** [comment]
Ah, the normals vectors are used to change the coloring of the points (shading). But they are not displayed as vectors indeed.

**Comment by dgirardeau** [comment]
Sorry, I didn't see that it was an improvement request. So I guess what you want is a way to display the normals as vectors.

**Comment by improve100** [comment]
This is using the PCL visualization method to display the vector , which will be much more intuitive.
 viewer->addPointCloudNormals<pcl::PointXYZ, pcl::Normal>(filtercloud, normals, 10, 0.3, "normals");

![image](https://github.com/CloudCompare/CloudCompare/assets/6092914/f4155ed5-6881-4dde-8fb2-ce57f29e1be7)

**Comment by WilliamWalker** [comment]
I would also like to see something similar.  OR at least be able to select a normal component (normal_x, normal_y, normal_z) as a scalar field when visualizing a PCD file with normal fields.  Perhaps I overlooked that functionality elsewhere?

**Comment by dgirardeau** [comment]
The 2.13.beta version has a new feature that allows to display the normals this way.

![image](https://github.com/CloudCompare/CloudCompare/assets/2735509/e0b80b0e-d440-4a31-9561-1421889f6cc3)

Look at the section 'Draw normals as lines' in the cloud properties. Of course the cloud needs normals. You may need a real GPU to make it work also.
