### ISSUE TITLE
qTreeIso git submodule configuration

### ISSUE THREAD

**Issue by p-leroy** [CloudCompare/CloudCompare#1802]
I have strange messages since qTreeIso were added to the plugins in the sources.
In the Git Gui on my laptop, in the unstaged changes: "Submodule plugins/core/Standard/qTreeIso 8010819a...f6f833c5 (commits not present)"
On GitHub, about the commit 8010819a94 "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."
https://github.com/truebelief/cc-treeiso-plugin/tree/8010819a946f6b6fe242f1fbcf1c2cd7eea52192

**Comment by p-leroy** [comment]
The latest master points to :
https://github.com/truebelief/cc-treeiso-plugin/tree/8010819a946f6b6fe242f1fbcf1c2cd7eea52192
![qTreeIso](https://github.com/CloudCompare/CloudCompare/assets/26645710/9f96e8ba-8de4-4381-8997-fae2f877bec9)

**Comment by dgirardeau** [comment]
Hum, weird. Is it better now?
