### ISSUE TITLE
Cloudcompare doesn't start because colorscale assertion fails

### ISSUE THREAD

**Issue by meyerjo** [CloudCompare/CloudCompare#1809]
I am currently unable to start CloudCompare on my system having installed it via flatpak. It was working smoothly in the past. 
```
(base) xx@xxr:~$ flatpak run org.cloudcompare.CloudCompare
QSocketNotifier: Can only be used with threads started with QThread
Gtk-Message: 11:25:32.885: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:25:32.885: Failed to load module "canberra-gtk-module"
qt.qpa.qgnomeplatform: Could not find color scheme  ""
Qt: Session management error: None of the authentication protocols specified are supported
CloudCompare: /run/build/CloudCompare/libs/qCC_db/src/ccColorScale.cpp:151: void ccColorScale::update(): Assertion `m_steps.back().getRelativePos() == 1.0' failed.

```

Running: ```sudo flatpak update --commit=b5fa0aaaf9d456432056f3fb6d00046bd1444c4781b1ee285fdda3b87af4c461 org.cloudcompare.CloudCompare``` brought me back to the version of Cloudcompare which was workng for me

**Your environment**
 - CC Version (or git hash/tag): 2.12.4
 - OS & Version: Ubuntu 22.04
 - Graphics card: Geforce RTX 2070 with  Driver Version: 525.116.04   CUDA Version: 12.0
 - Qt Version (if compiling): 

```
(base) xx@xx:~$ flatpak list
Name                             Application ID                                             Version          Branch            Installation
CloudCompare                     org.cloudcompare.CloudCompare                              2.12.4           stable            system

```

**Comment by rjanvier** [comment]
I can't tell since we do not maintain the 2.12.x flatpak pakage. Maybe you will have more chance [here](https://github.com/flathub/org.cloudcompare.CloudCompare). I'm in the process of updating the flatpak for 2.13. if you have flatpak-builder you can try to build the v2.13 branch of this repo https://github.com/flathub/org.cloudcompare.CloudCompare

**Comment by rjanvier** [comment]
I will try to make a beta channel for CC on Flathub, meanwhile maybe if you want, you can test the flatpak attached here.
https://github.com/CloudCompare/org.cloudcompare.CloudCompare/releases/tag/v2.13-beta0

**Comment by rjanvier** [comment]
Hi, beta version is available on Flathub
Please read [this](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) if you want to know the basic about beta channel on flathub. For CC, basically you have to do:

```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta org.cloudcompare.CloudCompare
```

You may need to make the beta version the default one with

```
flatpak make-current org.cloudcompare.CloudCompare beta
```

**Comment by meyerjo** [comment]
Finally, I was back at the computer with the problems. I can confirm that it is working with the beta.
