### ISSUE TITLE
Remove Duplicate Points with Command line mode

### ISSUE THREAD

**Issue by Tamu** [CloudCompare/CloudCompare#1814]
**Describe the bug**
The result of the RDP command is very different from the version in the interface (Tools > Other > Remove duplicate points).

1. Example (original file)

<img width="400" alt="Capture d'écran 2023-06-27 120522" src="https://github.com/CloudCompare/CloudCompare/assets/5020311/b5f39d60-7bb5-4241-b0c1-578e72e21579">

2. Example with interface (RDP : 0.05)

<img width="400" alt="Capture d'écran 2023-06-27 120752" src="https://github.com/CloudCompare/CloudCompare/assets/5020311/88f5ac93-d48f-4710-93ea-3eeb788ca11e">

3. Example with commande line (RDP : 0.05)

<img width="400" alt="Capture d'écran 2023-06-27 121511" src="https://github.com/CloudCompare/CloudCompare/assets/5020311/ead44823-1c49-4007-a5e7-b94dcfdce302">

According to my tests, I can’t adjust the RDP value correctly.
 

**How to reproduce**

Steps to reproduce the behaviour - include images if relevant:
1. Go to Menu > Tools > Other > Remove duplicate points
2. Input the RDP value (in my example : 0.05)
3. Make the same with commande line : ``CloudCompare.exe -C_EXPORT_FMT BIN -O o:\test.laz -RDP 0.05 -SAVE_CLOUDS FILE "o:\test-c.bin"``
4. Compare the two result files !

**Expected behaviour**
I would like to have exactly the same result between the commands (interface vs Commande Line)

**Your environment**
 - CC Version (or git hash/tag): 2.13 Alpha (Jun 7 2023)
 - OS & Version: Win 11 (22H2)
 - Graphics card:  GeForce RTX 2070 (last Gforce driver)
 - Qt Version (if compiling): -

**Comment by rjanvier** [comment]
Sorry I can't reproduce the issue and the code is clearly the same in both cases. The command line output seems very quantized in your case. Maybe it's more an issue with global shift / las reading parameters than something related to RDP. Did you use global shift to display your cloud in CC?

**Comment by dgirardeau** [comment]
You have to specifically set the Global Shift strategy (with '-GLOBAL_SHIFT AUTO' for instance).

**Comment by Tamu** [comment]
Thanks @dgirardeau  ! It's awesome !

How can I participate in the documentation or examples? I think with some additional examples, I will not have missed the point ?

Here is my working command :
`CloudCompare.exe -C_EXPORT_FMT LAS -o -GLOBAL_SHIFT AUTO test.laz -RDP 0.05 -SAVE_CLOUDS FILE "test-c.laz"`

**Comment by dgirardeau** [comment]
I've added a new example at first place ('Example 0'):
https://www.cloudcompare.org/doc/wiki/index.php/Command_line_mode#Example_0

But if you wish to make more edits, additions, I can create an editor account for you on the wiki?

**Comment by Tamu** [comment]
Thanks for the new example !

I'm willing to contribute to the wiki !

**Comment by dgirardeau** [comment]
Thanks. Can you send an email to admin@cloudcompare.org with your expected login/username? (and so that I have your email address)
