### ISSUE TITLE
Allow translation only alignment between 2 pointclouds

### ISSUE THREAD

**Issue by bedaberner** [CloudCompare/CloudCompare#1818]
**Describe the feature you would like**
When generating point clouds using photogrammetry based on non-RTK drone imagery, I will often get multiple meters XYZ-offset between different flights (absolute accuracy is not good enough to allow direct comparison).

Since the relative accuracy of the individual flights is normally quite good, orientation is comparable and does not need to be aligned.
It would therefore be very nice to just align the 2 clouds by selecting 1 single point and lock the rotation axis 

**Describe alternatives you've considered**
Alternative 1 is to use the 4 point alignment tool, this has the disadvantage of including rotations even if I don't want any and having to select many more points.

Alternative 2, what I currently do is to manually select the point in both clouds, note the coordinates down, calculate the difference and then apply the transformation manually, it's a bit tedious.

**Comment by the-mush** [comment]
You can disable Rotation on the Fine Registration (ICP) tool, on the Research tab.

**Comment by collinjroland** [comment]
> You can disable Rotation on the Fine Registration (ICP) tool, on the Research tab.

Does this work for you? When I run that command with Rotation disabled the identity matrix is returned.

**Comment by the-mush** [comment]
Never actually tried it until today! On which version did you try? On the latest stable (2.12.4) it does seem to throw more identity matrices way more often if you disable rotation. On the latest beta (2.13.beta of 29 Jan 2024), it works A LOT better.

To me, an identity matrix is one of the silent failure modes of the tool, one that says "I've tried to randomly wiggle it, and didn't find any better position with the specified parameters". If I keep tweaking the parameters, eventually I get it to move, and it does give a matrix with only the 3 top right parameters changed. Another silent failure is when it takes waaay too long between steps; it usually falls into the wrong valley and finds a lower RMS value on a totally wrong alignment, almost like it knows that it's wrong but can't find an escape route 😓

**Comment by collinjroland** [comment]
I've been trying it on the latest stable version (2.12.4). I'll give beta a shot! Thanks for the reply.

**Comment by collinjroland** [comment]
Can confirm, this worked for me in v2.13.beta! Recommend closing this issue.

**Comment by themightyoarfish** [comment]
Cannot confirm that it works better for me on master. I have a bit of a degenerate case (line scan to 3d scan registration) and i get weird reflective transforms with 6dof, and identity when i fix known degrees of freedom.
