### ISSUE TITLE
3d Mouse causes crash.

### ISSUE THREAD

**Issue by leojwilhelm** [CloudCompare/CloudCompare#1821]
**3d Mouse causes crash.**
is there any way to fix this? it is so much easier to navigate with this 3d mouse.

**Describe the bug**
My 3d space mouse wireless causes a crash when i use it.  I can star to move around the space, sometimes i get further than others, but the the program crashes every time i start rotating around the space.  I have current drivers. 
**How to reproduce**
navigate anything with the space mouse

**Your environment**
 - CC v2.12.4 stereo kyiv 64 bit
 - windows 10
 - Graphics card: Nvidia quadro m1200
- 2 external screens
- intel core i5 7th gen
- tons of memory

**Comment by dgirardeau** [comment]
Have you tried with the latest 2.13.alpha version?

**Comment by leojwilhelm** [comment]
Just downloaded and tried the new version.  Initially - 1st 2 minutes, no crashes. I'll let you know how it fairs over the next several hours.

**Comment by leojwilhelm** [comment]
Been working for hours. Solid.
