### ISSUE TITLE
error: ‘AdaptiveDecimalStepType’ is not a member of ‘QAbstractSpinBox’; ‘class QDoubleSpinBox’ has no member named ‘setStepType’

### ISSUE THREAD

**Issue by xxx695470536** [CloudCompare/CloudCompare#1824]
Hi, thanks for your great work!!
I am using Ubuntu(20.04), Qt(5.9.7) and g++ (Ubuntu 7.5.0-6ubuntu2)  to compile the latest CloudCompare and got an error as below:

> [ 71%] Building CXX object qCC/CMakeFiles/CloudCompare.dir/CloudCompare_autogen/mocs_compilation.cpp.o
In file included from /media/xinqiang_329/FE6041CE60418E79/qianli/CloudCompare/build/qCC/CloudCompare_autogen/EWIEGA46WW/../../../../qCC/ccGraphicalTransformationTool.h:24:0,
                 from /media/xinqiang_329/FE6041CE60418E79/qianli/CloudCompare/build/qCC/CloudCompare_autogen/EWIEGA46WW/moc_ccGraphicalTransformationTool.cpp:9,
                 from /media/xinqiang_329/FE6041CE60418E79/qianli/CloudCompare/build/qCC/CloudCompare_autogen/mocs_compilation.cpp:27:
/media/xinqiang_329/FE6041CE60418E79/qianli/CloudCompare/build/qCC/ui_graphicalTransformationDlg.h: In member function ‘void Ui_GraphicalTransformationDlg::setupUi(QDialog*)’:
/media/xinqiang_329/FE6041CE60418E79/qianli/CloudCompare/build/qCC/ui_graphicalTransformationDlg.h:322:29: error: ‘class QDoubleSpinBox’ has no member named ‘setStepType’; did you mean ‘setStyle’?
         incrementalRotSpin->setStepType(QAbstractSpinBox::AdaptiveDecimalStepType);
                             ^~~~~~~~~~~
                             setStyle
/media/xinqiang_329/FE6041CE60418E79/qianli/CloudCompare/build/qCC/ui_graphicalTransformationDlg.h:322:59: error: ‘AdaptiveDecimalStepType’ is not a member of ‘QAbstractSpinBox’
         incrementalRotSpin->setStepType(QAbstractSpinBox::AdaptiveDecimalStepType);
                                                           ^~~~~~~~~~~~~~~~~~~~~~~
/media/xinqiang_329/FE6041CE60418E79/qianli/CloudCompare/build/qCC/ui_graphicalTransformationDlg.h:344:31: error: ‘class QDoubleSpinBox’ has no member named ‘setStepType’; did you mean ‘setStyle’?
         incrementalTransSpin->setStepType(QAbstractSpinBox::AdaptiveDecimalStepType);
                               ^~~~~~~~~~~
                               setStyle
/media/xinqiang_329/FE6041CE60418E79/qianli/CloudCompare/build/qCC/ui_graphicalTransformationDlg.h:344:61: error: ‘AdaptiveDecimalStepType’ is not a member of ‘QAbstractSpinBox’
         incrementalTransSpin->setStepType(QAbstractSpinBox::AdaptiveDecimalStepType);
                                                             ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [qCC/CMakeFiles/CloudCompare.dir/build.make:530：qCC/CMakeFiles/CloudCompare.dir/CloudCompare_autogen/mocs_compilation.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:2253：qCC/CMakeFiles/CloudCompare.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2

Would you help me fix the bug? Thank you so much!!!

**Comment by dgirardeau** [comment]
You'll need Qt 5.12 at least to compile the latest version of CloudCompare (see https://doc.qt.io/qt-5/qdoublespinbox.html#setStepType)
