### ISSUE TITLE
LAS Scan Angle Scale

### ISSUE THREAD

**Issue by EZChe-EZDataMD** [CloudCompare/CloudCompare#1825]
https://github.com/CloudCompare/CloudCompare/blob/33521c10bfa5592ec790775cce202760089195de/plugins/core/IO/qLASIO/include/LasDetails.h#L43C1-L43C1

LAS scan angle scale (for the extended scan angle rank) should be 0.006 degrees rather than 0.06. 
https://www.asprs.org/wp-content/uploads/2019/07/LAS_1_4_r15.pdf

**Comment by dgirardeau** [comment]
@tmontaigu do you approve?

**Comment by tmontaigu** [comment]
Yes we are missing a 0

p 30:
> The Scan Angle is a signed short that represents the rotational position of the emitted laser pulse
 with respect to the vertical dimension of the coordinate system of the data. Down in the data coordinate system is the  0.0 position. **Each increment represents 0.006 degrees**

**Comment by dgirardeau** [comment]
Thanks @EZChe-EZDataMD, good catch (and thanks Thomas for the confirmation).

I've fixed the code. I'll try to publish a new 2.13.alpha version for Windows soon.

**Comment by EZChe-EZDataMD** [comment]
Thank you all so much!

Best,
Ezra
