### ISSUE TITLE
impossible to save in LAS format

### ISSUE THREAD

**Issue by zonderr** [CloudCompare/CloudCompare#1826]
My CloudCompare v2.12.4 flatpak on Debian 5.5.17-1~bpo10+1 (2020-04-23) x86_64 GNU/Linux doesn't save in LAS format. Instead, the save BIN window open and I indeed get a bin file.

**Comment by dgirardeau** [comment]
Well, I don't know if the Debian 2.12 version supports LAS output, but I would have guessed that it should have at least the PDAL plugin (you can check that in the 'Help > About plugins' dialog.

If yes, make sure to select only one point cloud (not several, and not a group/folder). Then you should be able to change the output file type in the File saving dialog.

**Comment by zonderr** [comment]
Thank you Daniel, I have the PDAL plugin, I can select the output file as LAS, but at the end, the save BIN window pops and I get a bin file.

**Comment by dgirardeau** [comment]
Not sure to understand what the "Save BIN window" is... Are you using the 'File > Save' menu entry? (or CTRL+S)

Because this is where you can select the output file type (on Windows, the drop-down list is named 'Save as type').

**Comment by zonderr** [comment]
Sorry, I'll try to be clear, I don't get a "save as type", File/Save (or CTRL+S) opens a window where I can type the file name and select:
![image](https://github.com/CloudCompare/CloudCompare/assets/13493670/d01acbc3-9e9a-4036-a8f3-43694279a4fd)

**Comment by dgirardeau** [comment]
And what happens if you choose "LAS cloud"? (and make sure the extension is
.las as well)

**Comment by zonderr** [comment]
I get a bin file called something.las. 
md5sum confirms me that it is the exact same bin file whatever I select:
md5sum bug.bin bug.las bug.shp
f43cac9d9bd019c67b5f6fa1fdaa9f51  bug.bin
f43cac9d9bd019c67b5f6fa1fdaa9f51  bug.las
f43cac9d9bd019c67b5f6fa1fdaa9f51  bug.shp

**Comment by dgirardeau** [comment]
What is surprising is that the filters should have the file extensions in addition to the name (e.g. "LAS file (*.las *.laz)").

It's as if the filter was truncated (and that probably explains why CC saves the files as BIN files as it doesn't understand the selected filter / file type).

**Comment by bgpantojar** [comment]
Hello... I have the same problem on Ubuntu 18.04LTS.. did you find any solution?

**Comment by rjanvier** [comment]
Hi, I was unable to reproduce it with the current 2.13beta. Could you please try it?

This new beta version is available on Flathub
Please read [this](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) if you want to know the basic about beta channel on flathub. For CC, basically you have to do:

```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta org.cloudcompare.CloudCompare
```

You may need to make the beta version the default one with

`flatpak make-current org.cloudcompare.CloudCompare beta`

**Comment by zonderr** [comment]
A colleague tried for me and the error remains, same dd.las file made.

**Comment by rjanvier** [comment]
So it's platform independent. Please open another issue, thank you. In another hand I think this one could be closed if you agree.

**Comment by zonderr** [comment]
ok, done : #1991

**Comment by rjanvier** [comment]
thank you.
