### ISSUE TITLE
Plane orientation error

### ISSUE THREAD

**Issue by adririquelme** [CloudCompare/CloudCompare#183]
I have been using Cloud Compare to extract planes from point clouds, and I found something that I think that it is wrong.

Fortunately, the planes are defined using the "dip direction / dip angle" convention (geology), but it is not correctly applied. Dip direction is the angle between the north and the horizontal projection of the dip. The software is calculating and showing the strike or direction, that is the angle between the north and the horizontal line of the plane.

http://en.wikipedia.org/wiki/Structural_geology#Geometries

By the way, congratulations for the software.

**Comment by ao2** [comment]
@cloudcompare hi, @luca-penasa is right: the definition of dip direction requires to ignore the orientation of the plane, setting all normals pointing upwards. Parallel planes have the same dip direction regardless of their orientation.

I will file a new issue for that where I propose a fix and give more details.

BTW that does not interfere with having the 0-360 degrees covered, think to a northern hemisphere, all the normals point upwards, but their projections on the horizontal plane still span 0-360 degrees:
![north_hemishere_normals](https://cloud.githubusercontent.com/assets/1249395/10824260/fe051248-7e5f-11e5-9665-850d985c44d7.jpg)

Ciao,
   Antonio

**Comment by luca-penasa** [comment]
the changes should be in ccNormalVector.cpp:
from the line 864:
```cpp
double dip_rad = atan(fabs(N.z)/sqrt(r2)); //atan's result in [-pi/2,+pi/2] but |N.z|/r >= 0
```

to something like:
```cpp
double dipDir_rad;
    if (N.z <= 0)
         dipDir_rad= atan2(-N.x,-N.y); //result in [-pi,+pi]
    else
         dipDir_rad = atan2(N.x,N.y); //result in [-pi,+pi]
```

**Comment by ao2** [comment]
yes, @luca-penasa I did something similar but using the sign of N.z directly in the calculation, I will post my patch very soon
