### ISSUE TITLE
Is there a way to import multiple headers automatically 

### ISSUE THREAD

**Issue by henrypearce4D** [CloudCompare/CloudCompare#1831]
I have a file that is a .ply that contains more headers and data than a usual .ply, I'm looking to import the full file, perform cropping, delete points and save the file with the same structure, could this be possible using CC ?

Here are the headers;
```
ply
format binary_little_endian 1.0
element vertex 526889
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float f_rest_0
property float f_rest_1
property float f_rest_2
property float f_rest_3
property float f_rest_4
property float f_rest_5
property float f_rest_6
property float f_rest_7
property float f_rest_8
property float f_rest_9
property float f_rest_10
property float f_rest_11
property float f_rest_12
property float f_rest_13
property float f_rest_14
property float f_rest_15
property float f_rest_16
property float f_rest_17
property float f_rest_18
property float f_rest_19
property float f_rest_20
property float f_rest_21
property float f_rest_22
property float f_rest_23
property float f_rest_24
property float f_rest_25
property float f_rest_26
property float f_rest_27
property float f_rest_28
property float f_rest_29
property float f_rest_30
property float f_rest_31
property float f_rest_32
property float f_rest_33
property float f_rest_34
property float f_rest_35
property float f_rest_36
property float f_rest_37
property float f_rest_38
property float f_rest_39
property float f_rest_40
property float f_rest_41
property float f_rest_42
property float f_rest_43
property float f_rest_44
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
end_header
```

I have attempted editing the file via a aabb cropping using python  open3d  plyfile, but those modules do not support extended headers than the standard xyz and and normals.

Any help would be much appreciated.

**Comment by dgirardeau** [comment]
Well, you can the full file with the GUI version of CC (importing all the fields as 'scalar fields', as long as all the fields are per-vertex fields (and not per triangles, if any).

You will be able to segment and transform the entity without losing these fields.

The only drawback is that at export time, CC might add a prefix to the scalar field names (such as 'scal_'). But you can probably edit the header and fix it afterward.

**Comment by henrypearce4D** [comment]
Hey thanks for the info, so what I understand is that I would have to add and select all the headers maually?

**Comment by dgirardeau** [comment]
Ah, actually you have to add 'scalar_' in front of all the additional field names, so that CC automatically recognizes them as scalar fields. That would work with both the GUI and command line versions in this case.

**Comment by henrypearce4D** [comment]
thanks, I had some issues adding scaler_ to opacity, getting this error, any ideas?
![image](https://github.com/CloudCompare/CloudCompare/assets/106480554/107fc2f0-f3ac-4227-b5e7-977f87f53f84)

thanks for your help!

**Comment by dgirardeau** [comment]
Hum, not easy to understand the issue...

Could you share with us this ply file (with only a few number of points)?

**Comment by henrypearce4D** [comment]
Hi, I prepared a small file, I haven't edited any of the headers.

Thanks for looking at this!

[point_cloud.zip](https://github.com/CloudCompare/CloudCompare/files/12226743/point_cloud.zip)

**Comment by kllgjc** [comment]
> Hi, I prepared a small file, I haven't edited any of the headers.
> 
> Thanks for looking at this!
> 
> [point_cloud.zip](https://github.com/CloudCompare/CloudCompare/files/12226743/point_cloud.zip)

This for gaussian splatting? Trying the same thing, Exporting to CC to remove points. Did you figure out how to import them all automatically? and does it work in the sibr viewer again (before I go down a rabbit hole, halfway there already!)

**Comment by henrypearce4D** [comment]
Hi @kllgjc yes it was for gaussian splatting. I didn't go any further than this with CC.

We ended up implementing filtering and editing into the SIBR viewer directly.

**Comment by kllgjc** [comment]
> Hi @kllgjc yes it was for gaussian splatting. I didn't go any further than this with CC.
> 
> 
> 
> We ended up implementing filtering and editing into the SIBR viewer directly.

Is this on the official implementation? When i open mine it only lets my crop xyz, which doesn't always line up. Or was there a recent update since I cloned the repo?

**Comment by henrypearce4D** [comment]
Its our own modified version we are testing for R&D, not an open project

**Comment by dgirardeau** [comment]
@henrypearce4D Sorry for the delay.

I edited the ply file by adding 'scal_' in front of each scalar field name:
![image](https://github.com/CloudCompare/CloudCompare/assets/2735509/9d8bea16-8c3d-4cc4-a1dd-4e0887fcc3d0)
[point_cloud_modified.zip](https://github.com/CloudCompare/CloudCompare/files/12640841/point_cloud_modified.zip)

And CC was able to load all the fields automatically without any error.

I attached the file for reference.

**Comment by henrypearce4D** [comment]
@dgirardeau I forgot to say, thanks for letting me know!
