### ISSUE TITLE
question about handling .pcd files in plugin.

### ISSUE THREAD

**Issue by zyx-99** [CloudCompare/CloudCompare#1833]
hi,
I want to use my own plugin for processing PCD point cloud files, but during the conversion process between PCD files and ccPointCloud, I will lose the point cloud intensity attribute.
Because my point cloud is PointXYZI, and during the conversion process, ccVector3 can only store the XYZ attributes of the point cloud, is there a way for me to keep the intensity information as well?

**Comment by dgirardeau** [comment]
You have to create a scalar field I guess? Where you'll be able to store the intensity values.

**Comment by zyx-99** [comment]
> You have to create a scalar field I guess? Where you'll be able to store the intensity values.

Yes, could you give me an example or tell me the corresponding API interface? Thank you.

**Comment by zyx-99** [comment]
> You have to create a scalar field I guess? Where you'll be able to store the intensity values.

Yes, could you give me an example or tell me the API interface? Thank you.

**Comment by dgirardeau** [comment]
There are loads of examples throughout the code, but you can take a look at: https://github.com/CloudCompare/CloudCompare/blob/master/plugins/core/IO/qDracoIO/src/DRCFilter.cpp#L487C3-L487C3
