### ISSUE TITLE
EDL Filter bug?

### ISSUE THREAD

**Issue by jaquilio** [CloudCompare/CloudCompare#1837]
In ccEDLFilter.cpp, I see the following code. The settings are identical for "half resolution" and "quarter resolution". I am wondering whether that is just a copy-and-paste code that never got edited after pasting? I would expect sigma to be 4.0 for the quarter resolution case.

	//smoothing filter for full resolution
	m_bilateralFilters[0].enabled  = false;
	m_bilateralFilters[0].halfSize = 1;
	m_bilateralFilters[0].sigma    = 1.0f;
	m_bilateralFilters[0].sigmaZ   = 0.2f;

	//smoothing filter for half resolution
	m_bilateralFilters[1].enabled  = true;
	m_bilateralFilters[1].halfSize = 2;
	m_bilateralFilters[1].sigma    = 2.0f;
	m_bilateralFilters[1].sigmaZ   = 0.4f;

	//smoothing filter for quarter resolution
	m_bilateralFilters[2].enabled  = true;
	m_bilateralFilters[2].halfSize = 2;
	m_bilateralFilters[2].sigma    = 2.0f;
	m_bilateralFilters[2].sigmaZ   = 0.4f;

**Comment by dgirardeau** [comment]
No, that's something I wondered in the past, but it actually gives a nicer result this way (so I believe the author did it on purpose).
