### ISSUE TITLE
Segment tool: add shift+click to remove last vertex (polygonal selection mode)

### ISSUE THREAD

**Issue by ryukisai** [CloudCompare/CloudCompare#1838]
**Describe the feature you would like**
When using the segment tool with the polygon selection mode, when you begin adding vertices of a complex shape, it’s quite frustrating to be unable to correct a misclick. I think it would be awesome to have a way to cancel the last vertex. I was considering shift+click, but another key combination can be used if easier.

**Additional context**
About my use case, i use the segment tool to cleanse my clouds (remove false points). It’s really common for me to draw complex polygons with 10+ vertices in order to do so.

Below, an example of my work with a 10+ vertex polygonal selection (here i’m cutting out a wall from top view).
![2023-08-18 11_26_55-](https://github.com/CloudCompare/CloudCompare/assets/6038397/c6243742-48a4-4032-92cd-5609dd8cb226)

**Comment by dgirardeau** [comment]
That's a nice and simple idea, I like it ;)

This is implemented. It will be available in the next 2.13.beta release.

**Comment by ryukisai** [comment]
Thank you Daniel! Looking forward to test it!

**Comment by dgirardeau** [comment]
Yes, I've already uploaded the 2.13.beta release.
