### ISSUE TITLE
Unable to open las file after build of CC with QLAS on Debian

### ISSUE THREAD

**Issue by pfmephisto** [CloudCompare/CloudCompare#1841]
**Describe the bug**
I am trying to compile CC with support for Las/Laz using the `LAS-IO` plugin on Debian since it does not seem to be included in the packaged version.
Both cmake and build appear to run through fine and the `./build/plugins/core/IO/qLASIO/libQLAS_IO_PLUGIN.so` file is being created and later placed in the install directory.

<details>
<summary>Overview of the files and folders in the install directory </summary>

```
.
├── bin
│   ├── ccViewer
│   └── CloudCompare
├── lib
│   └── cloudcompare
│       ├── libCCAppCommon.so
│       ├── libCCCoreLib.so
│       ├── libCC_FBO_LIB.so
│       ├── libCCPluginAPI.so
│       ├── libQCC_DB_LIB.so
│       ├── libQCC_GL_LIB.so
│       ├── libQCC_IO_LIB.so
│       └── plugins
│           ├── libQCORE_IO_PLUGIN.so
│           └── libQLAS_IO_PLUGIN.so
└── share
    └── cloudcompare
        ├── CHANGELOG.md
        ├── global_shift_list_template.txt
        ├── license.txt
        ├── shaders
        │   ├── Bilateral
        │   │   ├── bilateral.frag
        │   │   └── bilateral.vert
        │   └── ColorRamp
        │       └── color_ramp.frag
        └── translations
            ├── CloudCompare_chs.qm
            ├── CloudCompare_de.qm
            ├── CloudCompare_es_AR.qm
            ├── CloudCompare_fr.qm
            ├── CloudCompare_ja.qm
            ├── CloudCompare_kr.qm
            ├── CloudCompare_pt.qm
            ├── CloudCompare_ru.qm
            └── CloudCompare_zh.qm
```

</details>

**How to reproduce**
```
cd /home/<USER>/Repos/
git clone --recursive https://github.com/cloudcompare/CloudCompare.git
cd CloudCompare 
mkdir build && cd build
cmake ..  -DPLUGIN_IO_QLAS=ON -DLASZIP_INCLUDE_DIR=/home/<USER>/Repos/LASzip/include -DLASZIP_LIBRARY=/home/<USER>/Repos/LASzip/build/lib/liblaszip.so -DCMAKE_INSTALL_PREFIX=/home/<USER>/Repos/CloudCompare/install -DCMAKE_PREFIX_PATH=/ACG/acgdev/gcc-x86_64/qt/5.15.2/gcc_64
cmake --build .
cmake --install .
```

Open CC:
`/home/<USER>/Repos/CloudCompare/install/bin/CloudComare`
Open -> select file with .las extension
Error: [Load] Can't guess file format: unhanded file extension 'las'

**Expected behaviour**
CC should load the file and display the point cloud.

**My environment**
Git hash CC: c79c7a749b10fa3544d01b64650ed6debd05a3de
OS: Debian GNU/Linux 12 (bookworm)
Graphics card:  NVIDIA GeForce RTX 2070
Qt Version: 5.15.2
Git hash LASzip: 78b71a53147bb81e361dd39227121fd5dcb4d9eb

**Comment by tmontaigu** [comment]
Can you post what printed in  CloudCompare's Console ?

**Comment by pfmephisto** [comment]
@tmontaigu , sure. Here it is.


```
[10:20:20] [ccColorScalesManager] Found 0 custom scale(s) in persistent settings
[10:20:20] [Plugin] Searching: /usr/lib/cloudcompare/plugins
[10:20:20] [Plugin] Searching: /home/<user>/.local/share/CCCorp/CloudCompare/plugins
[10:20:20] [Plugin] Searching: /home/<user>/.local/share/flatpak/exports/share/CCCorp/CloudCompare/plugins
[10:20:20] [Global Shift] Max abs. coord = 1e+04 / max abs. diag = 1e+06
[10:20:20] Quad Buffered Stereo mode: not supported
[10:20:20] [ccGLWindow] Perspective is off by default
[10:20:20] CloudCompare started!
[10:20:20] [3D View 1] Graphics card manufacturer: NVIDIA Corporation
[10:20:20] [3D View 1] Renderer: NVIDIA GeForce RTX 2070/PCIe/SSE2
[10:20:20] [3D View 1] GL version: 4.6.0 NVIDIA 525.125.06
[10:20:20] [3D View 1] GLSL Version: 4.60 NVIDIA
[10:20:20] [3D View 1] VBOs available
[10:20:20] [3D View 1] Shaders available
[10:20:20] [3D View 1] GL filters available
[10:20:20] [3D View 1] Color ramp shader loaded successfully
[10:20:20] [3D View 1] Stereo mode: not supported
[10:20:20] [ccGLWindow] 3D view initialized
[10:20:20] [ccGLWindow] Succesfully initialized PBO for faster depth picking
[10:20:20] [Global Shift] Max abs. coord = 1e+04 / max abs. diag = 1e+06
[10:20:31] [Load] Can't guess file format: unhandled file extension 'las'
```

I can see that it is looking in the wrong folders for the plugins. I have both the Debian and my custom build. 
Could that be the source of the issue?

**Comment by pfmephisto** [comment]
I do not have sudo privileges on the machine that I am on.
Should I be setting my CMAKE_INSTALL_PREFIX to something like.  `/home/<user>/.local/`?
I currently have it in a custom folder in the repo to keep it completely separate form the other version.

**Comment by tmontaigu** [comment]
What is strange, is that it does no seems to be looking for plugins in the `${installdir}/lib` like it shoud (and does on my machine).

Is your install directory as descrtibed in the first post ?

In the meantime you can use the `CC_PLUGIN_PATH` environment variable to tell CC to look into that directory

**Comment by pfmephisto** [comment]
Alright using `CC_PLUGIN_PATH` and additionally adding the directory of the `liblaszip.so` to `LD_LIBRARY_PATH` variable seems to have done the trick.
I still have some issues with screen flickering and currently CC is only running if I launch it from within Qt Creator.
But I guess I need to have another look at my environment variables.
