### ISSUE TITLE
CC CLI command: Edit Global Shift and Scale

### ISSUE THREAD

**Issue by jo-chemla** [CloudCompare/CloudCompare#1843]
**Describe the feature you would like**
Being able to use via the CC CLI a command equivalent to the UI modal `Edit Global Shift and Scale` with the ability to toggle on or off the `Keep original positions fixed` setting would be helpful for some workflows. It does not seem like this feature is implemented from the [CLI doc](https://www.cloudcompare.org/doc/wiki/index.php/Command_line_mode). Would probably be applied to all pointclouds instances within the scene tree. Probably the CLI would invoke the [doActionEditGlobalShiftAndScale function](https://github.com/CloudCompare/CloudCompare/blob/94788080ee541a7a540cb9c5a0edee8937e26519/qCC/mainwindow.cpp#L1469).

**Describe alternatives you've considered**
 - Using a global shift option on `-O` open via the CLI, one can only use a `GLOBAL_SHIFT` value among `AUTO, FIRST, or xyz` with a given xyz vector, but we cannot edit the global shift afterwards. 
 - Could also use the `APPLY_TRANSFORM` command, but for large shifts this would result in floating point precision errors. 

**Is your feature request related to a problem? Please describe.**
Trying to batch process via CLI a manual workflow done in the UI which involves editing the global shift.

**Comment by dgirardeau** [comment]
So you would like a kind of -SET_GLOBAL_SHIFT method? (with X, Y Z and -KEEP_ORIG_FIXED)

**Comment by jo-chemla** [comment]
Yes exactly! This would be perfect to have such a CLI command with xyz coords input and that tag equivalent to keep origin fixed toggle on/off.

**Comment by HeadLessHUN** [comment]
Can be closed it's available in the latest beta 2024-01-01.
