### ISSUE TITLE
CC Export las 1.4 sets zero min/max in las header

### ISSUE THREAD

**Issue by jo-chemla** [CloudCompare/CloudCompare#1845]
**Describe the bug**

A pointcloud loaded into CC can be exported via either the `las` or `las 1.4` IO filters. 
 - Exporting it as a `standard las`, the resulting file has the correct min/max xyz in the header. 
 - Exporting it as a `las 1.4`, the resulting file has `min/max xyz` in the header set to `0,0,0`. 

See below lasinfo commands. 
```bash
(env_pdal) E:\TEMP\>LAStools\bin\lasinfo.exe pointcloud-las1.4.las
lasinfo (221128) report for 'pointcloud-las1.4.las'
reporting all LAS header entries:
  file signature:             'LASF'
  file source ID:             0
  global_encoding:            0
  project ID GUID data 1-4:   00000000-0000-0000-0000-000000000000
  version major.minor:        1.4
  system identifier:          ''
  generating software:        ''
  file creation day/year:     0/0
  header size:                375
  offset to point data:       375
  number var. length records: 0
  point data format:          7
  point data record length:   36
  number of point records:    0
  number of points by return: 0 0 0 0 0
  scale factor x y z:         0.00001 0.00001 0.00001
  offset x y z:               673359 4563220 109.422

  # WRONG min/max xyz
  min x y z:                  0.00000 0.00000 0.00000
  max x y z:                  0.00000 0.00000 0.00000

  start of waveform data packet record: 0
  start of first extended variable length record: 0
  number of extended_variable length records: 0
  extended number of point records: 647127956
  ...
(env_pdal) E:\TEMP\>LAStools\bin\lasinfo.exe pointcloud-las-standard.las
lasinfo (221128) report for 'pointcloud-las-standard.las'
reporting all LAS header entries:
  file signature:             'LASF'
  file source ID:             48
  global_encoding:            16
  project ID GUID data 1-4:   00000000-0000-0000-0000-000000000000
  version major.minor:        1.4
  system identifier:          'PDAL'
  generating software:        'PDAL 2.1.0 (828987)'
  file creation day/year:     236/2023
  header size:                375
  offset to point data:       375
  number var. length records: 0
  point data format:          7
  point data record length:   36
  number of point records:    647127956
  number of points by return: 647127956 0 0 0 0
  scale factor x y z:         0.00001 0.00001 0.00001
  offset x y z:               673359 4563220 109.422

  # CORRECT min/max xyz
  min x y z:                  673359.35894 4563218.84000 109.42151
  max x y z:                  674300.22919 4564265.00916 223.96440

  start of waveform data packet record: 0
  start of first extended variable length record: 1821770311
  number of extended_variable length records: 0
  extended number of point records: 647127956
  extended number of points by return: 647127956 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

**How to reproduce**
Select pointcloud and export as either las or las 1.4 file formats, and read via [lastools/lasinfo](https://github.com/LAStools/LAStools/releases/tag/v2.0.2). 

**Expected behaviour**
LAS header values should be set accordgin to the pointcloud bbox.

**Your environment**
 - CC Version (or git hash/tag): 2.13 alpha
 - OS & Version: Windows 11

**Comment by dgirardeau** [comment]
@tmontaigu any idea? 😅

**Comment by tmontaigu** [comment]
I tried and I don't have this problem

> A pointcloud loaded into CC can be exported via either the las or las 1.4 IO filters.

Does this mean you are using the old LAS 1.4 filter available from the menu ?
If yes that means its the old filter that has a problem

**Comment by dgirardeau** [comment]
Ah that's weird, since it's the 2.13.alpha version. Or is it a very old 2.13.alpha maybe?

**Comment by tmontaigu** [comment]
Also the file in the second example saved with the 'standard las filter'  has
```
 system identifier:          'PDAL'
  generating software:        'PDAL 2.1.0 (828987)'
```

which means its written by the pdal filter we had

**Comment by dgirardeau** [comment]
Good catch ;)

Ok then @jo-chemla you should update to the latest 2.13.beta version.

**Comment by jo-chemla** [comment]
Yes, must have been a very old 2.13.alpha with the old LAS 1.4 export filter, thanks for the hint. Using the new 2.13.beta, the min/max xyz coords are indeed correct. Note that for a pointcloud that was loaded as ply, when trying to save the ptc as las, then the `Original Scale is (0, 0, 0)`, so the user has to be careful in selecting either `Optimal` or `Custom` scale for a meaningful resulting file.

Out of curiosity, would love to know why you removed the pdal filter and what library the current las filter uses.

**Comment by tmontaigu** [comment]
For a long time we had two LAS filters one for 'general' las stuff but did not handle las with waveforms, and another which handled las with waveform but was hard to build on non windows platform.

So the qLASIO filter was made so that there is only one LAS filter which handles all features
