### ISSUE TITLE
No color in the grid image I projected

### ISSUE THREAD

**Issue by Coo1Sea** [CloudCompare/CloudCompare#1849]
I want to use cli to project my point cloud to RGB image. I can do the same process in GUI smoothly but it went wrong in cli. The code can run. However, the image just has the edge of cloud but no color on it (all black).
I put my code here and want to get help to solve the problem：

`for %%f in ("%POINTCLOUD_DIR%\*.pcd") do (
  %CLOUDCOMPARE_BIN% -O "%%f" -SET_ACTIVE_SF intensity -AUTO_SAVE OFF -SF_COLOR_SCALE %COLOR_FILE% -RASTERIZE -GRID_STEP 0.1 -OUTPUT_RASTER_RGB) `

**Comment by Coo1Sea** [comment]
Is `-OUTPUT_RASTER_RGB` equal to the choice 'output image' in GUI ?

**Comment by dgirardeau** [comment]
Sorry for the late answer.

-OUTPUT_RASTER_RGB allows to export a Geotiff raster. It's not equivalent to a simple 'image' export. You cannot export a raster to a simple image via the CLI currently...1
