### ISSUE TITLE
MAX_TCOUNT command line flag does not work with MAX_DIST flag

### ISSUE THREAD

**Issue by skoloCFD** [CloudCompare/CloudCompare#1850]
**Describe the bug**
The -MAX_TCOUNT command line flag does not work with the MAX_DIST (c2c or c2m) flag:

**How to reproduce**
Run CloudCompare with:
`-c2m_dist -MAX_TCOUNT 1 -MAX_DIST 1` 

and you should get the following error:
```
[Distances] Will use 1 threads
[Cloud/Mesh comparison] Max search distance is not supported in multi-thread mode! Switching to single thread mode...
CloudCompare: /data/CloudCompare/libs/qCC_db/extern/CCCoreLib/src/DistanceComputationTools.cpp:1432: static int 
CCCoreLib::DistanceComputationTools::computeCloud2MeshDistancesWithOctree(const CCCoreLib::DgmOctree*, 
const CCCoreLib::GridAndMeshIntersection&, CCCoreLib::DistanceComputationTools::Cloud2MeshDistancesComputationParams&, 
CCCoreLib::GenericProgressCallback*): Assertion `!params.multiThread || params.maxSearchDist <= 0' failed.
```

**Expected behaviour**
Should only use one core, and when doing so, be compatible with the MAX_DIST option.

**Comment by dgirardeau** [comment]
So for the first issue, I don't reproduce that on my side. I'm using Windows and OpenMP for multithreading.

Are you maybe using a different configuration and especially a different multithreading library?

I also guess you must compile in Debug mode to hit the assertion? Is it intentional?

And for the second issue, I've fixed it (it will be soon available on github)

**Comment by skoloCFD** [comment]
I'm using openMPI on ubuntu2204, compiled from source. I didn't take any steps to compile in debug mode, so unless that's somehow the default, I think the answer is no.

Nonetheless, I actually commented out this check, and it seems the max_dist flag works perfectly fine in parallel.
https://github.com/CloudCompare/CCCoreLib/compare/master...skoloCFD:CCCoreLib_MAX_DIST_fix:master

Do you think this assertion is necessary anymore?

**Comment by tmontaigu** [comment]
> I'm using openMPI on ubuntu2204, compiled from source. I didn't take any steps to compile in debug mode, so unless that's somehow the default, I think the answer is no.

unless you specified `-DCMAKE_BUILD_TYPE=Release` to cmake, the build is in debug mode.

**Comment by dgirardeau** [comment]
So I confirm that to see this warning, you had to run CloudCompare in Debug mode (which is much slower than thre Release mode).

But I also agree, this assert was deprecated, and it is ok to set a max search distance and use multithreading at the same time.
