### ISSUE TITLE
CloudCompare can not open in windows 11 with AMD processor and RADEON graphics

### ISSUE THREAD

**Issue by laragutz** [CloudCompare/CloudCompare#1853]
Hi everyone!!

In my actual job I need to use CloudCompare, but this is my first time using it. The real problem is that I can not open it, I mean that I can install and the installation ends very well, but the programa can not start. Also doesnt apears the folder in the path HKEY_CURRENT_USER/SOFTWARE/CCCORP/CLOUDCOMPARE

My laptop is Acer Model AN515 and has AMD Radeon R7 graphics and AMD FX-9830P processor with windows 11 pro.

Thnaks and I hope someone can help me

**Comment by dgirardeau** [comment]
I have fixed the forum and replied there directly: https://www.cloudcompare.org/forum/viewtopic.php?t=6598
