### ISSUE TITLE
LNK2019 LZ4_ in exampleplugin

### ISSUE THREAD

**Issue by ChenPointCloud** [CloudCompare/CloudCompare#1858]
I compiled my code with PCL alone without any errors, but when I ported the code to ExamplePlugin , I encountered multiple LNK2019 errors. I have provided 'flann_cpp_s.lib' in the additional dependencies and tried adding a few other lib files, but it didn't change the errors. I attempted to use 'CCLib::KDTree,' but it's significantly slower than 'KdTreeFLANN.' Additionally, it seems to conflict with PCL's console output. When I comment out the PCL-related code, the 'unresolved external symbol pcl::console::print' error reported in LNK2019 disappears.

When I comment out these two lines of code, the related LNK2019 errors disappear:
pcl::KdTreeFLANN<PointT> kdtree;		
kdtree.setInputCloud(cloud);

My CloudCompare version is 2.11.0, and my PCL (Point Cloud Library) version is 1.10.1.
Here is the compilation error report provided by VS2019:
7>ExamplePlugin.obj : error LNK2019: 无法解析的外部符号 "void __cdecl pcl::console::print(enum pcl::console::VERBOSITY_LEVEL,char const *,...)" (?print@console@pcl@@YAXW4VERBOSITY_LEVEL@12@PEBDZZ)，函数 "protected: virtual void __cdecl pcl::VoxelGrid<struct pcl::PointXYZ>::applyFilter(class pcl::PointCloud<struct pcl::PointXYZ> &)" (?applyFilter@?$VoxelGrid@UPointXYZ@pcl@@@pcl@@MEAAXAEAV?$PointCloud@UPointXYZ@pcl@@@2@@Z) 中引用了该符号
7>ExamplePlugin.obj : error LNK2019: 无法解析的外部符号 LZ4_decompress_safe，函数 "private: void __cdecl flann::serialization::LoadArchive::decompressAndLoadV10(struct _iobuf *)" (?decompressAndLoadV10@LoadArchive@serialization@flann@@AEAAXPEAU_iobuf@@@Z) 中引用了该符号
7>ExamplePlugin.obj : error LNK2019: 无法解析的外部符号 LZ4_setStreamDecode，函数 "public: __cdecl flann::serialization::LoadArchive::LoadArchive(struct _iobuf *)" (??0LoadArchive@serialization@flann@@QEAA@PEAU_iobuf@@@Z) 中引用了该符号
7>ExamplePlugin.obj : error LNK2019: 无法解析的外部符号 LZ4_decompress_safe_continue，函数 "private: void __cdecl flann::serialization::LoadArchive::loadBlock(char *,unsigned __int64,struct _iobuf *)" (?loadBlock@LoadArchive@serialization@flann@@AEAAXPEAD_KPEAU_iobuf@@@Z) 中引用了该符号
7>ExamplePlugin.obj : error LNK2019: 无法解析的外部符号 LZ4_resetStreamHC，函数 "public: virtual void __cdecl flann::AutotunedIndex<struct flann::L2_Simple<float> >::saveIndex(struct _iobuf *)" (?saveIndex@?$AutotunedIndex@U?$L2_Simple@M@flann@@@flann@@UEAAXPEAU_iobuf@@@Z) 中引用了该符号
7>ExamplePlugin.obj : error LNK2019: 无法解析的外部符号 LZ4_compress_HC_continue，函数 "public: void __cdecl flann::serialization::SaveArchive::save_binary<void const >(void const *,unsigned __int64)" (??$save_binary@$$CBX@SaveArchive@serialization@flann@@QEAAXPEBX_K@Z) 中引用了该符号
7>D:\cloudcompare_plugin\build\plugins\example\ExamplePlugin\Release\ExamplePlugin.dll : fatal error LNK1120: 6 个无法解析的外部命令

**Comment by dgirardeau** [comment]
Any reason why you use such an old version of CloudCompare? (the 2.13.beta is the 'master' version).

Otherwise can you show us the cmake file for your plugin? Have you explicitely linked it with PCL?

**Comment by ChenPointCloud** [comment]
I didn't modify the CMake configuration, but I configured the properties required by PCL in the Property Manager of Visual Studio. This property table works fine in a newly created blank project, but it encounters above issues in the CloudCompare project.

Here is the CMakeLists.txt:

cmake_minimum_required( VERSION 3.0 )

# CloudCompare example for standard plugins

# REPLACE ALL 'ExamplePlugin' OCCURENCES BY YOUR PLUGIN NAME
# AND ADAPT THE CODE BELOW TO YOUR OWN NEEDS!

# Add an option to CMake to control whether we build this plugin or not
option( PLUGIN_EXAMPLE_STANDARD "Check to install example plugin" OFF )

if ( PLUGIN_EXAMPLE_STANDARD )
	# Name the plugin
    project( ExamplePlugin )
    
    # load any subdirectories (see qAdditionalIO for an example)
    # add_subdirectory( LIB1 )
    
    include( ../../CMakePluginTpl.cmake )
    
    # set dependencies to necessary libraries (see qPCV for an example)
    # target_link_libraries( ${PROJECT_NAME} LIB1 )
    # include_directories( ${LIB1_INCLUDE_DIR} )
endif()

**Comment by ChenPointCloud** [comment]
By the way, I later used the qPCL plugin as a template, and it also works fine. It's just the ExamplePlugin that doesn't seem to work well.

**Comment by dgirardeau** [comment]
I'm a bit confused by why you would add the dependencies directly in Visual instead of CMake (as any change will be overwritten/lost as soon as you re-generate the CMake solution).

Anyway, using CMake's qPCL plugin as a template was probably the best move ;)
