### ISSUE TITLE
I was trying to see how 3D Fin plugin works. I did not find cloud compare 2.13 alpha version 7-16-2023 so that I can install it. I did not find in official cloud compare download website.

### ISSUE THREAD

**Issue by munachau** [CloudCompare/CloudCompare#1859]
**Describe the feature you would like**

**Describe alternatives you've considered**

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by munachau** [comment]
2.13 alpha version 7-16-2023
for 3DFin Plugin working

**Comment by rjanvier** [comment]
have you try latest alpha here : https://www.danielgm.net/cc/.

**Comment by munachau** [comment]
I haven't tried latest alpha? Because my computer support windows cloud compare alpha
Version. I don't find the link where I can download and install windows version in my computer.

**Comment by rjanvier** [comment]
Please look under the download section of the CloudCompare website in order to dowload CC alpha.

**Comment by munachau** [comment]
Thanks for the information. But I checked it in download section. It has alpha version for MacOS and beta version for windows. I donot find alpha version for windows.

**Comment by rjanvier** [comment]
please take the beta.

**Comment by rjanvier** [comment]
So.., have you tried with the beta? please close the issue if it works for you.

**Comment by munachau** [comment]
Yes I tried beta version. I don't see 3DFin plugin already installed there. In guideline I saw 
That the plugin is already installed in new alpha version.

**Comment by dgirardeau** [comment]
You have to activate the option in the installer so that the 3DFin plugin is installed.

**Comment by munachau** [comment]
Yesterday I installed it once but I don't see that option. Thanks Daniel I will try it again and try to find the option.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
