### ISSUE TITLE
cloudcompare open this  .obj error

### ISSUE THREAD

**Issue by xuzhuang1996** [CloudCompare/CloudCompare#1864]
**Describe the bug**

cloudcompare open this  .obj error,the model color is white, but the same file displays normally in MeshLAB.

in cloudcompare v2.13alpha
![image](https://github.com/CloudCompare/CloudCompare/assets/24559901/bb48b397-f857-4ed4-af93-e3938101a4e0)

in meshlab
![image](https://github.com/CloudCompare/CloudCompare/assets/24559901/852fc44b-91a6-41c9-8a0b-e0bcdfc0eae7)

**How to reproduce**
This OBJ model was exported in OpenMVS. The data source of the model is also sample data from OpenMVS. If you need it, I can provide it here.

**Your environment**
Windows

**Comment by dgirardeau** [comment]
Can you share the file with us? Or at least show the contents of the Console (F8)?

**Comment by xuzhuang1996** [comment]
> Can you share the file with us? Or at least show the contents of the Console (F8)?

the console is:
![image](https://github.com/CloudCompare/CloudCompare/assets/24559901/8229b04c-f4d1-42ed-a83c-3519d45372a2)

Perhaps the normal vector of Mesh was not calculated. But after executing Edit>Normals>Compute, it still remains the same

here is the obj file:

 https://drive.google.com/file/d/1RsXWgDtPlgGzpKYcRJUgw5zvQR0yGhiM/view?usp=drive_link

**Comment by xuzhuang1996** [comment]
> Can you share the file with us? Or at least show the contents of the Console (F8)?

I know the reason:
![image](https://github.com/CloudCompare/CloudCompare/assets/24559901/56088507-346a-4cef-9529-3b9406d14160)

I set Tr=0,and solve it.

but I don't know how MeshLAB handles it

Thank you very much!

**Comment by dgirardeau** [comment]
Either Meshlab ignores this parameters (if it doesn't manage transparency for instance). Or they are automatically fixing the issue assuming that Tr = 1 doesn't make sense...
