### ISSUE TITLE
Windows build + E57 plugin : QE57_IO_PLUGIN - fatal error LNK1181 - Cannot open the file '{path}\libs.obj

### ISSUE THREAD

**Issue by Pourfex** [CloudCompare/CloudCompare#1869]
**Describe the bug**
While trying to build Cloud Compare with E57 Plugin on, I cannot go throught the QE57_IO_PLUGIN compilation with a fatal link error on a "libs.obj" file that does not exist anywhere. Building Cloud Compare without e57 plugin is good and running.

**How to reproduce**
Compile Xerces 3.2.4:
  - mkdir build + cd build in Xerces's downloaded folder.
  - cmake -G "Visual Studio 16 2019" -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_INSTALL_PREFIX=**D:\cloudcomparebuild\libs** ..
  - cmake --build . --config Release
  - cmake --build . --config Release --target install

Everything is now in **D:\cloudcomparebuild\libs**

Compile Cloud Compare:
 - mkdir build + cd build in CloudCompare's downloaded folder.
 - cmake -DCMAKE_PREFIX_PATH=D:\Qt\Qt5.15.2\5.15.2\msvc2019_64 -DPLUGIN_IO_QE57=ON -DXercesC_LIBRARY=D:\cloudcomparebuild\libs -DXercesC_INCLUDE_DIR=D:\cloudcomparebuild\libs\include -DXercesC_VERSION="3.2.4" ..
 - cd ..
 - cmake --build build --config Release --parallel

Error linking on the libs.obj file

**Expected behaviour**
Should finish the compilation

**Your environment**
 - CC Version (or git hash/tag): e243efbb3e6ae65a96e42da7620fd46771f90fbe
 - OS & Version: Windows 10
 - Graphics card: GTX 1050TI
 - Qt Version (if compiling): 5.15.2

**Comment by dgirardeau** [comment]
I am personally using the visual studio solution file provided with Xerces (compiling the 'Static Release' configuration) to build it.

I guess that's what you try to replicate with the -DBUILD_SHARED_LIBS:BOOL=OFF option? Does it create proper static libraries?
