### ISSUE TITLE
Mainwindow flicker and delay problems

### ISSUE THREAD

**Issue by Loris-L** [CloudCompare/CloudCompare#1873]
Hi again. After been manged to compile CloudCompare with most of plugins available, also with @tmontaigu 's python plugin and 3DFin in Ubuntu 22.04, i encountered delays in mainwindow when i use it. For example: when i move a points cloud, the pivot remain and i've to refresh the viewer (zoom in or zoom out) to make it disappear; the pivot is set to visible with rotation only (see image). 

![Screenshot](https://github.com/CloudCompare/CloudCompare/assets/117673134/3ceb9216-7995-4a48-aeca-6facea3dfa16)

Even when i toggle files in db tree, when i scroll in the console or in properties window, i've to refresh the viewer because these actions described don’t work immediately but there are delays/lags.
I encountered this problem both after CloudCompare compilation and with the installation of flatpak package shared by @rjanvier [here](https://github.com/CloudCompare/org.cloudcompare.CloudCompare/releases).
It isn't a problem of my PC because the windows installer of last beta release that i used to install CloudCompare in Windows 11 doesn't have these lag/delay problems.

**Comment by rjanvier** [comment]
Hi, it seems there are some issue with rendering under linux. (I'm not impacted on my side). see https://github.com/CloudCompare/CloudCompare/issues/1867. Could you please compile this specific revision of CC https://github.com/CloudCompare/CloudCompare/commit/1d5f74ee1c18027abff10824210d922f7a9f84a0 (without any plugin) and tell us if the issue remains?

**Comment by tmontaigu** [comment]
> It isn't a problem of my PC because the windows installer of last beta release that i used to install CloudCompare in Windows 11 doesn't have these lag problems.

Did that include an install of the python plugin ?

**Comment by Loris-L** [comment]
@rjanvier i'll compile that revision of CC and i hope we'll find the problem.
@tmontaigu probably it isn't python plugin, i compiled CC also without it and the lags there are still.

**Comment by Loris-L** [comment]
So, the situation is this: i compiled CC from source code at this commit [`1d5f74e`](https://github.com/CloudCompare/CloudCompare/commit/1d5f74ee1c18027abff10824210d922f7a9f84a0) without any plugin and there aren't lag problems. I also compiled CC from last master branch (that one for which i opened this issue) without any plugin and there are the lag problems described above. So the problem isn't due by CC plugins.

**Comment by rjanvier** [comment]
Ok thanks a lot for the debuging, so it's also related to the "unified" rendering. what kind of GPU are you using. if you use a nvidia one are you using `Nouveau` or the closed source driver?

**Comment by Loris-L** [comment]
My PC is a Dell Inspiron 5510, a laptop with Intel core i7 11th generation and integrated gpu Intel Iris Xe. I haven't a dedicated gpu such as Nvidia

**Comment by Loris-L** [comment]
UPDATE

I've seen that when there is a points cloud load in CC and decimate points options is activated with a number of points lower than the entire points cloud, for some seconds there are no more delays.
So when the viewer is forced to autorefresh, CC on linux works fine like on Windows, even if for a very short time. I think it's due to the viewer, but maybe I'm wrong. @dgirardeau where is the part of source code about viewer refresh? Or do you have some idea?

**Comment by dgirardeau** [comment]
Are you referring to the LOD mechanism? The automatic decimation of point clouds when the view is moved (by default it triggers above 10M. points)?

**Comment by Loris-L** [comment]
Yes, exactly that.

**Comment by dgirardeau** [comment]
Well, you have to look at how the 'm_lod' structure is used in ccPointCloud.cpp (qCC_db) --> see for instance here: https://github.com/CloudCompare/CloudCompare/blob/master/libs/qCC_db/src/ccPointCloud.cpp#L2635

CC will display a chunk of the point cloud, then update the context so that the view draw3D method is aware that some more points need to be displayed. See here: https://github.com/CloudCompare/CloudCompare/blob/master/libs/qCC_glWindow/src/ccGLWindowInterface.cpp#L4683

But eventually,

**Comment by Loris-L** [comment]
@dgirardeau i think the problem is in ccGLWindowInterface or at least in ccGLWindow (i've more certainty about the first), but i don't know where exactly. I'll see where you pointed me.

**Comment by Loris-L** [comment]
As i was saying, the problem is ccGLWindowInterface. I found that the problem is due by the [rendering params](https://github.com/CloudCompare/CloudCompare/blob/e00df2edb0dc876787d4427e5004fba458263faa/libs/qCC_glWindow/src/ccGLWindowInterface.cpp#L4606) in "doPaintGL", and i tried to add a request update function (requestUpdate()) in [line 4611](https://github.com/CloudCompare/CloudCompare/blob/e00df2edb0dc876787d4427e5004fba458263faa/libs/qCC_glWindow/src/ccGLWindowInterface.cpp#L4611) after ifdef-endif or at the end of doPaintGL ([here](https://github.com/CloudCompare/CloudCompare/blob/e00df2edb0dc876787d4427e5004fba458263faa/libs/qCC_glWindow/src/ccGLWindowInterface.cpp#L4703)). In this way, there aren't the delays described above and CC works smoothly like in Windows, but there are other delay problems when i create a new 3D view, open the 2 3Dview in cascade mode and i try to restore one of them to full size (with the classic square button). In addition, there are other problems such as the freezing of CC when you click on "open files" button and about the LOD mechanism (infinity reload of point clouds open with drag and drop method).
So, this is the right way, but it probably requires a lot of effort to solve the whole problem

**Comment by dgirardeau** [comment]
I will have to look at that with more attention, but do you have any clue why this happens only on Linux and not on Windows?

**Comment by Loris-L** [comment]
@dgirardeau I don't know why but i think Linux OSes are more picky when referring to code. I fixed an issue in 3DForest program that opened in Windows but not in Linux OSes, and i found that original source code created 2 interactors ([see here](https://github.com/VUKOZ-OEL/3d-forest-classic/pull/35)) that in Linux OSes created a segfault at the start, not in Windows where it opened normally even if the code was wrong on that side, like if Windows bypass the problem. So this to say that if in Windows a code works, not always it works in Linux OSes and if there is this situation probably the code is wrong or something miss somewhere.
In this specify case, i think that there is an implementation problem of ccGLWindowInterface that in previous commit of unified version there wasn't because there was only ccGLWindow. An implementation problem which in Windows doesn't create rendering problems because Windows bypass them.
If you will make some changes and want to check if these modifies works in Linux OS, you can rely on me too.

**Comment by Loris-L** [comment]
I'd like to update this issue post.
I recently took a new laptop and compiled CC from master. The CC behaviour is the same described in #1867: many and frequent black flickers moving in mainwindow (but not in ccGLwindow) or using events, but there aren't mainwindow delays/lags described in my issue.
My new laptop configuration is:
- OS: Ubuntu 22.04.3 LTS with Linux kernel 6.5.0-1009-OEM
- Graphics card: NVIDIA Geforce RTX 4060 with 545.29.06 driver version and 12.3 CUDA version (also CUDA toolkit)
- OpenGL: 4.6 version provided by NVIDIA driver
- QT version: 5.15.3

In my previous laptop that showed mainwindow delays/lags, the configuration is:
- OS: Ubuntu 22.04.3 LTS with Linux kernel 6.2.0-xx-generic
- Graphics card: Intel Iris XE (iGPU)
- OpenGL: 4.6 version provided by Mesa drivers from kisak ppa, oibaf ppa or proprietary intel ppa
- QT version: 5.15.3

So in Linux OSes, with only iGPU and OpenGL provided by Mesa drivers, CC has mainwindow lag/delay problems; with dGPU and OpenGL provided by NVIDIA drivers, CC has many and frequent flickers.
I hope these informations are usefull

**Comment by Loris-L** [comment]
I've seen that on wayland session CC hasn't any of these problems, only with xorg.
@rjanvier If you haven't experienced these problems, do you use wayland session?

**Comment by dgirardeau** [comment]
Should be fixed now.
