### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by yinshuli-dot** [CloudCompare/CloudCompare#1875]
cmake --build . error as follows 
/mnt/d/project/github/CloudCompare/qCC/ccGraphicalTransformationTool.h:24:0,
                 from /mnt/d/project/github/CloudCompare/qCC/ccGraphicalTransformationTool.cpp:18:
/mnt/d/project/github/CloudCompare/build/qCC/ui_graphicalTransformationDlg.h: In member function ‘void Ui_GraphicalTransformationDlg::setupUi(QDialog*)’:
/mnt/d/project/github/CloudCompare/build/qCC/ui_graphicalTransformationDlg.h:322:29: error: ‘class QDoubleSpinBox’ has no member named ‘setStepType’; did you mean ‘setStyle’?
         incrementalRotSpin->setStepType(QAbstractSpinBox::AdaptiveDecimalStepType);
                             ^~~~~~~~~~~
                             setStyle
/mnt/d/project/github/CloudCompare/build/qCC/ui_graphicalTransformationDlg.h:322:59: error: ‘AdaptiveDecimalStepType’ is not a member of ‘QAbstractSpinBox’
         incrementalRotSpin->setStepType(QAbstractSpinBox::AdaptiveDecimalStepType);
                                                           ^~~~~~~~~~~~~~~~~~~~~~~
/mnt/d/project/github/CloudCompare/build/qCC/ui_graphicalTransformationDlg.h:344:31: error: ‘class QDoubleSpinBox’ has no member named ‘setStepType’; did you mean ‘setStyle’?
         incrementalTransSpin->setStepType(QAbstractSpinBox::AdaptiveDecimalStepType);
                               ^~~~~~~~~~~
                               setStyle
/mnt/d/project/github/CloudCompare/build/qCC/ui_graphicalTransformationDlg.h:344:61: error: ‘AdaptiveDecimalStepType’ is not a member of ‘QAbstractSpinBox’
         incrementalTransSpin->setStepType(QAbstractSpinBox::AdaptiveDecimalStepType);
                                                             ^~~~~~~~~~~~~~~~~~~~~~~
qCC/CMakeFiles/CloudCompare.dir/build.make:1336: recipe for target 'qCC/CMakeFiles/CloudCompare.dir/ccGraphicalTransformationTool.cpp.o' failed
make[2]: *** [qCC/CMakeFiles/CloudCompare.dir/ccGraphicalTransformationTool.cpp.o] Error 1
CMakeFiles/Makefile2:2617: recipe for target 'qCC/CMakeFiles/CloudCompare.dir/all' failed
make[1]: *** [qCC/CMakeFiles/CloudCompare.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Your environment**
 - CC Version (or git hash/tag):
 - wsl ubuntu18.04  :
 - Graphics card:  
 - Qt Version (if compiling):

**Comment by rjanvier** [comment]
Hi. It seems you are using a too old version on QT. You need at least qt 5.12. Unfortunatly it's not available in ubuntu 18.04 package repository. You can still download QT 5.15 from the website, compile it from source, get it from a PPA or a conda env.
