### ISSUE TITLE
Korean language identification code error

### ISSUE THREAD

**Issue by Backstree** [CloudCompare/CloudCompare#1878]
In [ISO-639](https://www.andiamo.co.uk/resources/iso-language-codes/) ，the Korean language abbreviation is ko, not kr.

[updateTranslations.bat](https://github.com/CloudCompare/CloudCompare/blob/master/scripts/windows/updateTranslations.bat)

Need to change
 %QT_DIR%\lupdate.exe %SRC_DIRS% %OPTIONS% -ts qCC\translations\CloudCompare_kr.ts 
to 
%QT_DIR%\lupdate.exe %SRC_DIRS% %OPTIONS% -ts qCC\translations\CloudCompare_ko.ts 

Then regenerate the ts file。

**Comment by dgirardeau** [comment]
Good catch. That should now be fixed: e00df2edb0dc876787d4427e5004fba458263faa
