### ISSUE TITLE
How to run the icp cloud registration in command line?

### ISSUE THREAD

**Issue by lin-name** [CloudCompare/CloudCompare#1881]
Hi, the CloudCompre project is a great work, thank you for all your efforts. 
Now  i can easily run the icp cloud registration to register the two point clouds in the UI as below:

![icp_in_UI](https://github.com/CloudCompare/CloudCompare/assets/65641960/ce74b6d6-210e-40f6-8b05-7b153e94890c)

but, when i tried to use the command line like:
> CloudCompare.exe  -ICP  1.txt 2.txt 
and 
> CloudCompare.exe  -ICP  -Load 1.txt -Load 2.txt 

but both of them output the error: 
**Not enough loaded entities (expect at least 2!)**

So, how to use the icp cloud registration(and the option **adjust scale** as well) to registerthe two cloud: 1.txt and 2.txt in command line?

Looking forward for your reply! Thanks.

**Comment by dgirardeau** [comment]
Look at the documentation again (https://www.cloudcompare.org/doc/wiki/index.php/Command_line_mode). You have to load the entities first, and then call the ICP command.

**Comment by lin-name** [comment]
Yes，after read the documentation, i can use the algorithm satisfactorily. Thank you very much.

About another question, how can i use the 4pcs registration algorithm? Is there a buttom in the UI  or the command in the command line? And which version of the CloudCompare can use this algorithm? Thanks!

**Comment by dgirardeau** [comment]
The implementation of the 4CPS algorithm in CloudCompare has always been very unstable and buggy. This is why it has been disabled for a long time. But I don't remember in which version (just that it's a long time ago). You could try with the 2.6.3.beta version available online.

But once again, it's quite buggy.

**Comment by lin-name** [comment]
ok, thank you! I will try it. 
Keep in touch!
