### ISSUE TITLE
Opening a ply file by double-clicking fails on MacOS

### ISSUE THREAD

**Issue by jackjansen** [CloudCompare/CloudCompare#1883]
**Describe the bug**
Opening a ply file on MacOS (by double-clicking the file, or using `open xyzzy.ply` from the command line) fails with the error

```
[Load] Can't guess file format: unhandled file extension 'ply'
```

Opening it from within CloudCompare (after selecting the `ply` filetype) works.

**How to reproduce**
Steps to reproduce the behaviour - include images if relevant:
1. Double click a PLY file

**Expected behaviour**
The ply file opens.

**Additional context**
None.

**Your environment**
 - CC Version (or git hash/tag): 2.13.alpha (macOS 64 bits)
 - OS & Version: macOS Sonoma 14.1, Mac mini M1 (Silicon)
 - Graphics card: n.a.
 - Qt Version (if compiling): n.a.

**Comment by dgirardeau** [comment]
Can you try with the version shipped with CloudCompy? https://www.simulation.openfields.fr/

You can ignore the Conda/Python stuff, and use CloudCompare.app which is in the Cloudcompare folder of his macOS packages.

**Comment by prascle** [comment]
I do not reproduce the bug with the latest binary published [here](https://www.simulation.openfields.fr/index.php/cloudcompare-downloads)

**Comment by runxel** [comment]
Probably same root issue as in #1665.
Please try 2.13.1 where it finally seems to work (not in 2.13 alpha tho!).

**Comment by jackjansen** [comment]
Confirmed fixed. Thanks!
