### ISSUE TITLE
 Cannot specify link libraries for target "qFBXIO" which is not built by   this project.

### ISSUE THREAD

**Issue by 992308385** [CloudCompare/CloudCompare#1886]
Windows11 ， I have set the laszip and fbxsdk. 
**Describe the bug**

**How to reproduce**

**Expected behaviour**

**Additional context**

**Your environment**
 - CC Version (or git hash/tag):
 - OS & Version:
 - Graphics card: 
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
Let me spend the exact same time you spent on creating this issue and providing us with enough information to understand your problem...

I don't know ;)

**Comment by dgirardeau** [comment]
Feel free to re-open the issue, but with more information please.
