### ISSUE TITLE
CloudCompare problem with last updated feature for LAS files

### ISSUE THREAD

**Issue by Loris-L** [CloudCompare/CloudCompare#1887]
This time i've opened an issue for the last windows installer available on CC site: i've also windows 11 in my PC and with the last CC, when i try to open las files, CC crashes after click on a button of the first window about the setting of scalar fields. Instead, when i try to save e.g. a bin file in las file, CC isn't able to save it with the error described in the next image.

![IMG_20231124_104106_113.jpg](https://github.com/CloudCompare/CloudCompare/assets/117673134/69a73684-793f-49c2-825e-c3a8cdbab651)

I saw the last @tmontaigu 's PR, maybe is it something related to that?

**Comment by dgirardeau** [comment]
The 2.13.beta version has been updated (online). Thanks for the feeback!

(and thanks @tmontaigu for the quick fix)

**Comment by Loris-L** [comment]
I'm sorry but CC still crashes when i try to import a las file. Saving to las instead now works.

**Comment by dgirardeau** [comment]
Bug confirmed 😢

**Comment by dgirardeau** [comment]
Ok that's fixed (for good hopefully)... I'll re-upload CC tonight.

**Comment by dgirardeau** [comment]
And it's uploaded!

**Comment by Loris-L** [comment]
Great! Now also works opening las files.
Will this correction merged with a PR to master branch? I'd like to rebuild CC with these corrections also on my Linux OS

**Comment by dgirardeau** [comment]
Yes, that's merged. Another fix by Thomas will be merged soon, but that's just syntax/code hardening. It won't change the behavior.

**Comment by Loris-L** [comment]
Thanks to you and @tmontaigu for quick answers and fixes
