### ISSUE TITLE
  Cannot specify link libraries for target "qFBXIO" which is not built by   this project.

### ISSUE THREAD

**Issue by 992308385** [CloudCompare/CloudCompare#1891]
**Describe the feature you would like**

**Describe alternatives you've considered**

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by 992308385** [comment]
I want to compile the las, but it says:   Cannot specify link libraries for target "qFBXIO" which is not built by
  this project.

**Comment by dgirardeau** [comment]
So you are definitely not asking for an enhancement, not sure why you picked the 'enhancement' template.

We will need to know your compilation environment (environment, compiler, version of Qt, version of the FBX SDK, etc.).
