### ISSUE TITLE
Crash when merging scans on Linux.

### ISSUE THREAD

**Issue by ajcraig99** [CloudCompare/CloudCompare#1895]
**Describe the bug**
I am experiencing a crash when I try to "merge" 21 small scans in an imported .E57 file. The total file size for the .E57 is 2.5GB.

**How to reproduce**

**Steps to reproduce the behavior - include images if relevant:**

To reproduce, I simply select all scans, click "merge" and when prompted to regen scalar fields I select yes or no (makes no difference) and then the program immediately closes.

I can also reproduce the crash using CloudCompare CLI by running 
`cloudcompare -o scan.e57 -MERGE_CLOUDS`

**Expected behaviour**
The 21 clouds should merge into one cloud without crashing.

**Additional context**

1. When running CloudCompare CLI, or by launching CloudCompare from the terminal, I can see the below exception when it crashes.

`CloudCompare: /run/build/CloudCompare/libs/qCC_db/src/ccPointCloud.cpp:991: const ccPointCloud& ccPointCloud::append(ccPointCloud*, unsigned int, bool): Assertion `false' failed.`

2. I have no issues merging other scans from downloaded sources. I can reproduce the crash with a number of scans generated from the same scanner and software (Leica Register 360 & Leica RTC360 scanner).

**3. Removing a single point by subsampling and reducing the point count by 1 from each cloud before merging avoids the crash. This is the really interesting part** 
4. I cannot reproduce the crash on Windows 10 with CC 2.13 beta or 2.12.4 Stable.

**Your environment**
 _- CC Version (or git hash/tag):_ 2.12.4 Stable (flatpak), also tested on 2.13 beta and an older version in the ubuntu repo (2.11)
 _- OS & Version:_ Kubuntu 23.10 x86_64 , Kernal: 6.5.7-060507-generic 
 _- Graphics card:_ RTX 3060 Ti
 _- Qt Version (if compiling):_ Not compiling, N/A

```
OS: Kubuntu 23.10 x86_64 
Kernel: 6.5.7-060507-generic 
Uptime: 27 mins 
Packages: 2532 (dpkg), 9 (flatpak), 14 (snap) 
Shell: bash 5.2.15 
Resolution: 3840x2160 
DE: Plasma 5.27.8 
WM: KWin 
WM Theme: Breeze 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], McMojave-circle-dark [GTK2/3] 
Terminal: konsole 
Terminal Font: Ubuntu Mono 10 
CPU: AMD Ryzen 9 5950X (32) @ 3.400GHz 
GPU: NVIDIA GeForce RTX 3060 Ti Lite Hash Rate 
Memory: 3980MiB / 31990MiB 
```

**Comment by dgirardeau** [comment]
I forgot to ask on the forum, but does it work with 21 (or at least a lot of) small clouds?

**Comment by dgirardeau** [comment]
So it's only with E57 files 😅 

Can you share one file with us maybe?

**Comment by ajcraig99** [comment]
It appears to only be .e57 but I don't have immediate access to many other scan files to confirm. I would have to test this when I'm back home in a few days. 

https://drive.google.com/file/d/1R6jBwCP5B8Zr0sPvcUaE9U_hY2hNFZjW/view?usp=sharing

**Comment by dgirardeau** [comment]
Thanks for the dataset. I looked a little bit more into this, and there's one last thing you could try: can you deactivate the 'LoD' mechanism ('When moved, decimate clouds over XXX points" option in the Display > Display settings dialog).

Or also simply to disable the top entity (the E57 file group) in the DB tree before attempting the merge.

(It's a long shot, but I wonder if it might be a display issue as I don't see any obvious issue with the 'merging' code itself).

And by the way, instead of subsampling the individual scans, does 'cloning' them help? (with the 'Edit > Clone' tool)

**Comment by tmontaigu** [comment]
I tried and also get the same crash when using the 2.14 flatpak, but not when using my compiled local 2.13 version

**Comment by rjanvier** [comment]
Hi! is there anyway to get the files in order to reproduce the bug. The drive link seems to be dead now. thanks you.

**Comment by tmontaigu** [comment]
I tried with the 2.13 flatpak beta on the file that was shared in the drive and it does not crash
