### ISSUE TITLE
ICP in CLI- Translation parameters not adjustable

### ISSUE THREAD

**Issue by SchmidL** [CloudCompare/CloudCompare#1898]
**Describe the bug**
Not sure if it's a bug, or not implemented at all, but the translation parameters, which can be turn on/off cannot be set via the CLI

**Additional context**
The rotation  are forwarded to the CLI via `constexpr char COMMAND_ICP_ROT[]`

**Your environment**
 - CC Version (or git hash/tag): v12.3 beta
 - OS & Version: Win 10

**Comment by dgirardeau** [comment]
That's not implemented indeed. Someone would need to do it ;)

**Comment by HeadLessHUN** [comment]
I think this could be closed. :)

**Comment by dgirardeau** [comment]
See https://github.com/CloudCompare/CloudCompare/pull/1931
