### ISSUE TITLE
Error during plugin development build Detection problems with cloudcompare-config.cmake or cloudCompareConfig.cmake

### ISSUE THREAD

**Issue by ryuga-otsuka** [CloudCompare/CloudCompare#1899]
**Describe the bug**

I am currently facing difficulties in setting up a development environment for CloudCompare plugin development. Despite following standard plugin development procedures, my setup is giving me errors.
The process is as follows

1. Cloned the CloudCompare repository from GitHub.
2. Installed all necessary dependencies.
3.Successfully built CloudCompare using CMake.
4. We then proceeded to create the plugin using the method in the link below.
https://github.com/CloudCompare/CloudCompare/blob/master/CONTRIBUTING.md
I copied the plugin EXAMPLE and did everything up to renaming.
5. Then when I try to build, I get an error message that CMake cannot find the CloudCompare configuration file. The error message is as follows

CMake Error at plugins/private/PointCloudSegmentationPlugin/CMakeLists.txt:17 (find_package):.
  By not providing "FindCloudCompare.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CloudCompare", but CMake did not find one.

  Could not find a package configuration file provided by "CloudCompare" with any of the following names: "CloudCompare", but CMake did not find one.
  Could not find a package configuration file provided by "CloudCompare" with any of the following names: CloudCompareConfig.cmake

    CloudCompareConfig.cmake
    cloudcompare-config.cmake

  Add the installation prefix of "CloudCompare" to CMAKE_PREFIX_PATH or set
  "CloudCompare_DIR" to a directory containing one of the above files.
  "CloudCompare" provides a separate development package or SDK, be sure it has been installed.
  If "CloudCompare" provides a separate development package or SDK, be sure it has been installed.

**Expected behaviour**

**Additional context**

**Your environment**
 - CC Version (or git hash/tag):
 - OS & Version: Windows10
 - Graphics card: Quadro T2000
 - Qt Version (if compiling): 5.15.16

**Comment by dgirardeau** [comment]
Hi,

Can you share with us your CMakeLists.txt file? How does it compare with the other plugins CMakeLists.txt files?

And do we agree that you get the error when you generate the global CloudCompare CMake project?

**Comment by ryuga-otsuka** [comment]
Sorry for asking the question.
I was able to solve it.
[CMakeLists.txt](https://github.com/CloudCompare/CloudCompare/files/13643924/CMakeLists.txt)

It seems the problem was that the setting was not done after the if on line 9.
if ( PLUGIN_EXAMPLE_STANDARD )

**Comment by dgirardeau** [comment]
No problem.
