### ISSUE TITLE
Create rpm for openSUSE/Fedora

### ISSUE THREAD

**Issue by tigerfoot** [CloudCompare/CloudCompare#190]
This is mostly a reminder for myself to enhance CC to be able to produce rpm for openSUSE/Redhat

Developement will be visible at 
https://build.opensuse.org/package/show/home:bruno_friedmann:branches:Application:Geo/cloudcompare

First point : distribution hate static lib or imported source they should be reside in their own package
Case of glew.h 

Second point : Find  nice CMake macro find gdal, liblas, dxflib to make the system more flexible on where those lib can reside. Get rid of numerous export etc.

**Comment by asmaloney** [comment]
This is really old - closing.
