### ISSUE TITLE
Cannot import LAS/LAZ file with PDAL IO plugin

### ISSUE THREAD

**Issue by owenh28** [CloudCompare/CloudCompare#1900]
**Describe the bug**
CC fails to import LAS file using PDAL reader.
**How to reproduce**
1. Application launches
2. I go to open the LAS file
3. it opens the pre import window with fields and information about the file
4. When I click "Apply" or "Apply to all", the window closes and I get an error that states: `PDAL exception: readers.las: Extra byte specification exceeds point length beyond base format length. `

**Expected behaviour**
LAS file would open and present a point cloud.
**Additional context**
I have tried updating all pdal libs, including compiling latest from source off of the PDAL github. 
This happens both on self compiled version and flatpak version

**Your environment**
 - master branch git pull
 - Arch Linux, ran a full system update in my troubleshooting
 - Radeon 5600xt
 - Qt 5.15.11

**Comment by Loris-L** [comment]
You could use LAS IO plugin that is maintained and supported, PDAL IO plugin is deprecated

**Comment by owenh28** [comment]
Alright, I just tried to recompile without pdal, and with LAS IO instead. I ran into an issue where both make and ninja failed to compile `CloudCompare/plugins/core/IO/qLASIO/include/LasExtraScalarField.h`, citing an issue with  a `uint8_t` on line 95 causing an unknown type. Ninja suggested adding `#include <cstdint>` to the libraries section of the file, and it compiled successfully, and ran successfully. I am not a cpp programmer and do not know if this issue was me specific. Hope this means something/helps someone who has the same issue as me.

**Comment by dgirardeau** [comment]
Thanks for the feedback. I'll add this `#include <cstdint>` statement to the code, it cannot do harm ;)

**Comment by ArcticSnow** [comment]
FYI, it seems you solved the issue but for the record, I also ran in the same error while wanting to open the French IGN airborne lidar data. 
I am using CC v2.12.4 on linux.

**Comment by dgirardeau** [comment]
Yes, you'll have to compile the newest version (2.13.beta), or wait for the official package to come out when we release the 2.13 version officially (hopefully before the end of the month 😅 )
