### ISSUE TITLE
Setting initial precision for cylinders not functioning

### ISSUE THREAD

**Issue by ataeub** [CloudCompare/CloudCompare#1901]
**Describe the bug**
When creating a cylinder with a non-default precision in the primitive factory interface, the selected precision isn't considered and the default precision (24) is used.

**How to reproduce**
1. Go to primitive factory
2. Go to the cylinder interface
3. Set radius and height to some values and change the initial precision from 24 to a higher value
4. Klick "Create" or hit Enter
5. In the Properties tab for the created cylinder, the precision won't match the set one but 24 (the default precision)

**Expected behaviour**
The precision will be the value that's set in the primitive factory interface

**Your environment**
 - CC Version: 2.12.4 (Kyiv) 
 - OS & Version: Windows 11 Pro (10.0.22621 Build 22621)
 - Graphics card: NVIDIA GeForce GTX 1080 Ti

**Comment by dgirardeau** [comment]
Good catch!

Actually none of the entities were using this 'precision' field 😅.

That's fixed now: 227a71e146ca92010e706a9b6728880b0607c6d6

The new 2.13.beta version will be updated this week-end.

**Comment by dgirardeau** [comment]
Yes, I haven't updated the 2.13.beta version though (still in my plans for today)

**Comment by dgirardeau** [comment]
Ok it's updated now!
