### ISSUE TITLE
how to uninstall

### ISSUE THREAD

**Issue by Tobethebestman** [CloudCompare/CloudCompare#1906]
**Describe the bug**
how can i fully uninstall cloudcompare, i need to reinstall the newst version

**Comment by dgirardeau** [comment]
Normally the new installer should take care of that.

If not, you should be able to remove the previous version of CloudCompare via the Windows Settings: https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-4b55f974-2cc6-2d2b-d092-5905080eaf98

**Comment by Tobethebestman** [comment]
thank you fro your advice, but my platform is Ubuntu system, please is there any command to uninstall completely？

**Comment by dgirardeau** [comment]
@tmontaigu or @rjanvier maybe?

**Comment by tmontaigu** [comment]
No one can help with such level of detail in the report.
The Os was not specified.

Now we know its ubuntu, ok  cool, but how was cloudcompare installed ? because depending on how it was installed then knowing how to uninstall it is easy

**Comment by Loris-L** [comment]
@Tobethebestman If in build directory `make uninstall` doesn't remove all files related to CloudCompare, you have to remove them manually.
Consider using `checkinstall` which creates a deb package and installs it, so it'll be easier to remove an app later
