### ISSUE TITLE
CLI silent read las/laz gui

### ISSUE THREAD

**Issue by HeadLessHUN** [CloudCompare/CloudCompare#1910]
Desc:
During command line mode with -silent flag the new las/laz io still throws gui loading element on every loading. Otther commands stays silent (output to console)

Env:
Windows
Latest master as of now (2023-12-14)

Reproduce:
CloudCompare.exe -SILENT -O "file.laz"

**Comment by dgirardeau** [comment]
Ok I can add that check.

**Comment by dgirardeau** [comment]
This should be fixed with this PR: https://github.com/CloudCompare/CloudCompare/pull/1915

**Comment by HeadLessHUN** [comment]
thanks i'll test it out as soon as it's out. :)

**Comment by dgirardeau** [comment]
That's online now!
