### ISSUE TITLE
function Jacobi ComputeEigenValuesAndVectors calculate problem

### ISSUE THREAD

**Issue by YuBoTao123** [CloudCompare/CloudCompare#1911]
**Describe the bug**

 eigen vector and eigen value differ from calculation by eigen lib 3.4.0? 

**Your environment**
 - CC Version (or git hash/tag): v2.13.alpha
 - OS & Version: linux64 bit
 - Graphics card: 
 - Qt Version (if compiling): 

![image](https://github.com/CloudCompare/CloudCompare/assets/49198890/ba90e442-1bbb-4da6-8bcf-7915fd358bfe)
![image](https://github.com/CloudCompare/CloudCompare/assets/49198890/e7cf1e46-e799-4676-89f2-aa038e25c358)

**Comment by dgirardeau** [comment]
Interesting (and concerning). And which one is the closest to the truth?

**Comment by YuBoTao123** [comment]
I think eigen lib.
Tow solution have same eigen values, but the first eigen vector is not same.(I have set absoluteValues parameter to false in ComputeEigenValuesAndVectors function, although this matrix eigen value is Positive value)

**Comment by dgirardeau** [comment]
So I looked at this again, and actually I misread your results. The only difference is the sign of the first eigenvector isn't it?

As the definition of an eigenvector and eigenvalue is that `M(X) = lambda.X`, X or -X are both acceptable (as `M(-X) = -lambda.X`).

It took me some time to realize that it was the only difference between your 2 results. For the records, I used https://github.com/jewettaij/jacobi_pd/tree/master and https://matrixcalc.org/vectors.html to double check everything.

**Comment by YuBoTao123** [comment]
Yes, the difference is the sign of the first eigenvector. But why two first eigen value is same?

**Comment by dgirardeau** [comment]
Well, all eigenvalues are the same.

I should have written the equation above:
`M(-X) = lambda.(-X)`

The eigenvector can be flipped, it won't change the eigenvalue sign.

I guess the only thing we could do is to make sure that the 3 eigenvectors form a direct orthonormal basis (E3 = E1 ^ E2). But that's not a requirement per se, and we don't use eigenvectors this way in CloudCompare anyway.

**Comment by YuBoTao123** [comment]
I think I figured it out .Thanks for your patient answer!
