### ISSUE TITLE
Command line wiki corrections for recently added commands

### ISSUE THREAD

**Issue by HeadLessHUN** [CloudCompare/CloudCompare#1923]
Hello, Daniel.

On the wiki you added the new functions i made, but there are some problem.

In SET_GLOBAL SHIFT, the -KEEP_ORIGIN was replaced (in the refactor commit) with -KEEP_ORIG_FIXED.

So the whole command
-SET_GLOBAL_SHIFT {x} {y} {z} -KEEP_ORIG_FIXED

In the APPLY_TRANS
currently
-APPLY_TRANS {filename} {-INVERSE}
But it should be
-APPLY_TRANS {-INVERSE} {filename}
Because the filename always  be the last param. This is how the param handling is wrote in -O as well.

Another smaller problem, this one is just cosmetics, not breaking
Currently
-COMMAND_FILE{base name}
It should be
-COMMAND_FILE {file}

**Comment by dgirardeau** [comment]
Good catch!

Should be fixed now.
