### ISSUE TITLE
Normals not flipped when "mirroring" with Multiply/Scale tool

### ISSUE THREAD

**Issue by Edg422** [CloudCompare/CloudCompare#1928]
**Describe the bug**
When trying to make a mirror of a point cloud, one option is to Scale it by -1 on the required axis. It correctly mirrors the points by repositioning them, but the normals on the mirrored direction are not flipped. In my case I wanted to mesh a whole object by flipping one half and then joining the points, but since the other half has different normals it is causing issues on the edges.

**How to reproduce**
Get a point cloud of a symmetric object (half of it). Check the normals orientation by light or by creating a SF of it (Edit>Normals>Export Normals to SF). 

![image](https://github.com/CloudCompare/CloudCompare/assets/22987995/19f4ce5e-880c-4ce0-9595-ebdab81fa18e)

Use Edit>Multiply/Scale to mirror the cloud on the required axis. Check again the normals orientation, and the original moved points will point in the same direction, having the normals flipped on the mirrored axis.

![image](https://github.com/CloudCompare/CloudCompare/assets/22987995/e57351f3-6dab-48c7-af44-27913446d7cb)

**Expected behaviour**
Normals should be flippled on the axis if the scale is negative (or give and option to do that)

**Additional context**

**Your environment**
 - CC Version (or git hash/tag): 2.13.alpha Stereo
 - OS & Version: Windows 11
 - Graphics card: NVidia GTX 3070
 - Qt Version (if compiling):

**Comment by HeadLessHUN** [comment]
Workaround,

Conert normals to SF, 
flip the required axis's SF with sf arithmetic tools
Set normal from scalar fields.

**Comment by dgirardeau** [comment]
Ok, I've improved the code: a2bb0842b5734d5cf23377d49cb29917cfcfa022

I'll try to release a new 2.13.beta version today or tomorrow.

**Comment by dgirardeau** [comment]
This should now be fixed (for quite some time ;) )
