### ISSUE TITLE
Examples for command lines for testing and for the public

### ISSUE THREAD

**Issue by HeadLessHUN** [CloudCompare/CloudCompare#1929]
Hello Daniel.

I was thinking about to save COMMANDS_FILE for testing purposes and for making them public.

Can we save somewhere in the git repo these kind of COMMAND_FILEs? And few small clouds to test (I mean about 100-1000 points in a bin file, it can be enough to show how the most majority of commands works)

And i was thinking about to allow comment lines in command file, so it could be commented, whats done.

these example files would be 2 part first ( Prerequisites ) (Actual command/option usage.)

#TODO List
https://github.com/CloudCompare/CloudCompare/blob/master/qCC/TODO.txt

can we cross out things in the list or flag them as solved?

**Comment by dgirardeau** [comment]
Yes, comments would definitely help (maybe with # and/or // as marker?)

Else, don't hesitate to clean/update the TODO list whenever you see something already implemented.

And last but not least, the example command scripts could fall either in a 'qCC/cli' or equivalent subfolder, or equivalently in a 'scripts/cli' subfolder.

**Comment by HeadLessHUN** [comment]
I'm planning to to do 
# and // and it will affect the whole line after the comments, like in other languages.

And i was thinking about to make some kind of inline comments /* */, but don't want to reimplement the wheel and support the same kind of functionality what is done already. 

So maybe if someone wants to use inline comments they should do it inside quotes. Other wise it would be a little bit harder to implement.  But i'll see maybe i do inline/multiline comments available with /* */.

-COMMAND_TO_RUN '/*my comments goes here with spaces*/' -COMMAND_TO_RUN
