### ISSUE TITLE
Official website showed the same command for BETA and STABLE release for Linux

### ISSUE THREAD

**Issue by HowcanoeWang** [CloudCompare/CloudCompare#1935]
**Describe the bug**
The release website: https://www.danielgm.net/cc/release/

For the **beta** release: 

![image](https://github.com/CloudCompare/CloudCompare/assets/19968935/c5337fe6-611c-4beb-b3a7-d2ae11c13726)

For the **stable** release:

![image](https://github.com/CloudCompare/CloudCompare/assets/19968935/633de7e8-7776-40a5-a35d-dc62bb1cf0f5)

It seems they share the same command to install, but the flatpak only provide the **stable** version:

https://flathub.org/apps/org.cloudcompare.CloudCompare

It may have some tricks to install the dev branches by flathub? But I have not search out about the solution.

Any installation guide to install the **beta** version on Linux except compling by myself?

**Comment by Loris-L** [comment]
> Any installation guide to install the beta version on Linux except compling by myself?

No, at the moment the only way to have latest beta of CloudCompare for Linux OSs is to compile from master branch. But @rjanvier plans to create a beta channel on flathub, so he could probably give some more information

**Comment by rjanvier** [comment]
Hi, beta version is available on Flathub
Please read [this](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) if you want to know the basic about beta channel on flathub. For CC, basically you have to do:

```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta org.cloudcompare.CloudCompare
```

You may need to make the beta version the default one with

```
flatpak make-current org.cloudcompare.CloudCompare beta
```

**Comment by rjanvier** [comment]
close as the website is updated with these informations
