### ISSUE TITLE
Gaussian filter to color

### ISSUE THREAD

**Issue by HeadLessHUN** [CloudCompare/CloudCompare#1938]
Hello Daniel i just want to check in on an idea of mine.

I'm planning to smooth colors with some gaussian filtering. And i was thinking that cannot we speed things up somehow to run a single pass instead of converting every component (rgb) to sf then run gauss filtering on each color then convert that back to colors.

Results can be really good:
![Screenshot_20240109-091353_Microsoft Remote Desktop](https://github.com/CloudCompare/CloudCompare/assets/10095691/2845cfc2-7d30-4b91-a37d-608431fd47d3)
![Screenshot_20240109-091410_Microsoft Remote Desktop](https://github.com/CloudCompare/CloudCompare/assets/10095691/11521b09-2504-4262-820e-a0c9eca90252)

**Comment by dgirardeau** [comment]
Yes, you can probably create a dedicated tool (duplicating what's done in CCCoreLib with the SF Gaussian Filtering, but moving that in the ccPointCloud class typically, and applied to RGB colors?

See https://github.com/CloudCompare/CCCoreLib/blob/master/src/ScalarFieldTools.cpp#L232

**Comment by HeadLessHUN** [comment]
Do you think that, we could gain significant performance, if we do it in one pass, but triple (R,G,B) gauss averaging in a single iteration?

**Comment by HeadLessHUN** [comment]
Would you be fine with a command line command

-FILTER {SF (sf name/sf id)|RGB} {GAUSSIAN|BILATERAL}
Of course i'll add a gui option as well similar to sf filters

**Comment by dgirardeau** [comment]
Yes that should be good.

**Comment by dgirardeau** [comment]
I'll try to take a look when I'll have more time (after the 2.13 release ;)  ). Hopefully at the end of the week.

**Comment by dgirardeau** [comment]
Ok, so the main issue was that your method was not static.

But then I realized how old the code you copied was, so I cleaned it on CCCoreLib's side. And I also merge the Guassian and Bilateral filters code on CC's side (for the existing SF versions, and your new RGB versions).

I had to push everything on the CloudCompare's repo (as I don't have write access on your repo): https://github.com/CloudCompare/CloudCompare/tree/gaussian_filter

I haven't had the time to test anything! I'll try to do it later but it won't be very fast...

**Comment by dgirardeau** [comment]
I added you as a collaborator of the project so that you can create and update branches directly.

To speed up things by using only the points inside the cells, you will have issues for points lying close to the borders of the cell (as you will only consider 'neighbors' on one side and not all around the point). This may create artefacts / seems.

**Comment by dgirardeau** [comment]
I also opened a PR : https://github.com/CloudCompare/CloudCompare/pull/1970

**Comment by DuVogel87** [comment]
Is there some kind of documentation on how to apply those settings you demonstrating here?

I am training some splats and would love to learn more about how to use cloudcompare to improve my .ply

Thanks for the help!

**Comment by dgirardeau** [comment]
Ah, good point. The wiki was never updated to explain these methods....

@HeadLessHUN Do you maybe have some bandwidth to populate the wiki pages? I've created placeholders here:
https://www.cloudcompare.org/doc/wiki/index.php/Methods#Colors

(I don't remember if you already have an account, don't hesitate to ask for one)

**Comment by HeadLessHUN** [comment]
Hello, i could create a short documentation for these, but not sure when. Maybe on the weekend, i'll find some time.

I don't have account for editing wiki pages, you made the changes in the cli page as far as i remember.

**Comment by dgirardeau** [comment]
Thanks @HeadLessHUN 

You should have received an email. No particular hurry, but you are probably the best placed to document these methods :)

You can simply copy-paste the wikimedia 'code' of another tool description and change it to your needs.

**Comment by DuVogel87** [comment]
What do you mean by "no particular hurry"?

I needed it yesterday! :-D

**Comment by HeadLessHUN** [comment]
I created the subpage for the wiki. If i made some mistakes, then correct me pls :) writing the documentation i came across with the real "mean filter" which is used in image processing, maybe i'll try that later. because currently i just apply arithmetic mean with the mean filter.

**Comment by dgirardeau** [comment]
Thanks. I made minor edits.

**Comment by HeadLessHUN** [comment]
I copied those changes to the 3 other page, however i think it could be one page so we don't have to copy it multiple times, however since it is done probably not gonna be changed after this, so we could leave it like that.
