### ISSUE TITLE
CLI: add -REMOVE_SENSORS command

### ISSUE THREAD

**Issue by ryukisai** [CloudCompare/CloudCompare#1941]
Hello! Happy new year everyone!
Could you please add a command in CLI mode that would remove the sensors (TLS/GBL or else) from the selected entities?
Thank you!

**Comment by dgirardeau** [comment]
Ok, this one was easy. You can test that with the latest 2.13.beta version.

Option: -REMOVE_SENSORS

(don't hesitate to reopen the issue if you experience an issue)

**Comment by ryukisai** [comment]
Thanks a lot, i'll test and report asap!
Bon week end!

**Comment by ryukisai** [comment]
Hi, i just tested the command in CLI, it works well (note that i only have a TLS so i can't test with other sensors).
Thank you! :-)
