### ISSUE TITLE
[CLI] implement a way to get less verbosity

### ISSUE THREAD

**Issue by ryukisai** [CloudCompare/CloudCompare#1949]
**Describe the bug**
Hi, i'm using CLI for most of my pre-processing steps. I'm very happy with it but even though i'm using the -SILENT option, i find there is a ton of verbose left that i find unwanted (especially 60 lines just for the plugins), see the caption:
![2024-01-31 17_58_08-Export](https://github.com/CloudCompare/CloudCompare/assets/6038397/9c598357-2451-4f32-945e-5c072322b383)

**How to reproduce**
My win CMD batch uses series of commands and the call to CC is this:
set CloudComparePath="C:\Program Files\CloudCompare\CloudCompare.exe"
%CloudComparePath% -SILENT -O "blabla.e57" -AUTO_SAVE OFF -MERGE_CLOUDS […]

**Expected behaviour**
If i'm not using the option wrong, i'd appreciate an option to further reduce the verbose level.
Thank you!

**Your environment**
 - CC Version (or git hash/tag): 2.13 β build from 2024-01-27
 - OS & Version: win 11 22H2 & 23h2

**Comment by dgirardeau** [comment]
Yes, I believe this is because we load the plugins before anything else (even before interpreting the commands...). I guess we should check if -SILENT is the very first option at least.

**Comment by ryukisai** [comment]
Ok this makes sense to load the plug-ins first as some commands might rely on them.
This request is definitely low priority so let me know whenever this reaches the to-do list.
Merci!

**Comment by HeadLessHUN** [comment]
-SILENT means that it won't load the gui. And not a verbosity level :)
I was thinking about a verbosity level for command line but probably too much work would be to sort every message to a correct level.
Currently only 3 level are available info/warning/error

We could easily create a command to set these levels, but there will be little to none meaning because almost all message is at info level, unless it is an error and then it just halts the command so you will notice that.

**Comment by ryukisai** [comment]
Hi! I took another look and the wiki, the description for -SILENT is:
> enables silent mode (no console will appear)
> Warning: must be first if required. 
Indeed it has nothing to do with verbose level. However console for me meant the text console, not the whole GUI.

Well it would be good if we could skip the plugins info messages. But it would require creating another level just for these, which does not make a lot of sense, i agree.
Otherwise you're right my batch is not in debugging phase anymore so i could ignore all messages. It's helpful to know which command is currently running to have an idea of the progress, but it's not mandatory.

**Comment by HeadLessHUN** [comment]
Well to silent those plugin message i suppose all the plugin must be changed. So probably not the easiest one to implement.

**Comment by ryukisai** [comment]
Well i think it would rather need some changes to ccPluginManager.cpp. A boolean setting could be implemented and and checked  before the ccLog::Print(…) commands @ lines #144 and #213.
