### ISSUE TITLE
2.13.Beta Doesn't save complete cloud on Spatial Subsample can be a small slice of data

### ISSUE THREAD

**Issue by LKlingenberg** [CloudCompare/CloudCompare#1959]
**Describe the bug**
When using SS from .bat or python on .e57 files for example "CloudCompareFile" /W "C:\Program Files\CloudCompare\cloudcompare.exe" -SILENT -O %%f -C_EXPORT_FMT E57 -SS SPATIAL 0.002. The exported file is of similar size e.g. 567 MB for 2.13.beta and 561 for 2.12.4  however on opening the file in CC only a slice of the points are visible.  (The new version of the files is saving the images in the file where 2.12.4 was not which is nice just points are missing.)

**How to reproduce**

1. Install new version
2. Run script with a 1 or a group of E57 scans. 
3. open subsampled scans in CC (older or Beta)
4. See error by comparing original scan/ 2.12.4subsampled with the new scan subsampled scan by 2.13.beta

**Expected behaviour**

Run script, output file is subsampled with all points above specified distance present like in older versions.

**Additional context**

Have tested on a number of different scans with the same results, slices are often in different directions. (we have tested on many files (maybe 100's))

Scan was processed on the same machine, same input file and same script. image shows top down comparison where only a small slice of the scan file is visible in the new 2.13.Beta version. the viewpoint has not changed i have simply toggled the scan data on or off. 
![2 13 Beta New Beta Version same script](https://github.com/CloudCompare/CloudCompare/assets/42199606/7780da32-89d4-4a98-8d1a-3fa60721274b)
![2 12 4 same script](https://github.com/CloudCompare/CloudCompare/assets/42199606/dfd698e8-3bf7-4fb1-b8c5-19a67c65af6f)

**Your environment**
 - CC Version (or git hash/tag): 12.13.beta
 - OS & Version: intel 13th gen, with 128GB ram, windows 11 pro 10.0.22621 build 22621
 - Graphics card: 4090
 - Qt Version (if compiling): 

Thank you

**Comment by HeadLessHUN** [comment]
Hello, What if you just open and save? That will eliminate the subsample step from the probably issue list.

**Comment by dgirardeau** [comment]
Seems to be a bug with the E57 file export! I was able to reproduce it on my side 😓

**Comment by dgirardeau** [comment]
Ok I've found the bug. It was introduced on the 27th Jan... CC was only saving the 1 million first points (over and over again). 😰

**Comment by HeadLessHUN** [comment]
I'm not able to reproduce with the build of january 7. And i think there were no changes to the writer.

I've tried to open save structured e57 (exported by cyclone register 360, 2020.1/cc 2.13 jan 7), tried spatial sampling all of them looks fine. 

as for unstructured setups i did not get any client told me that our clouds not full, and looked one of them and seems fine. (i have tried it in the gui)

UI so that is why i did not have issues :D

**Comment by dgirardeau** [comment]
See https://github.com/CloudCompare/CloudCompare/commit/d4f63da560f1dc49f60503327f6515d071785376#r138491939

**Comment by dgirardeau** [comment]
The fix is on its way...

**Comment by dgirardeau** [comment]
https://github.com/CloudCompare/CloudCompare/pull/1960

**Comment by dgirardeau** [comment]
The latest 2.13.beta (10th of Feb) should fix this issue.

@LKlingenberg  Thanks for the feedback!!!

**Comment by LKlingenberg** [comment]
Amazing! The new version works flawlessly now, Thank you for all your efforts!
