### ISSUE TITLE
Spelling error when exporting as .las

### ISSUE THREAD

**Issue by benhask** [CloudCompare/CloudCompare#1964]
**Describe the bug**

When saving a pointcloud in the .las format the "LAS Save Options" open, in the tab "Basic Params" it says "Point Fornat" instead of "Point Format".

**How to reproduce**

1. Click "Save current entity"
2. Change file type to LAS file
3. Save document
4. LAS Save Options open
5. Go to tab "Basic Params"

**Expected behaviour**

The parameter should be name "Point Format" instead of "Point Fornat"

**Additional context**

**Your environment**
 - CC Version (or git hash/tag): 2.13.0
 - OS & Version: Windows 10
 - Graphics card: NVIDIA Quadro RTX 4000

![Bug](https://github.com/CloudCompare/CloudCompare/assets/154432278/0ab3c082-1973-44d2-807c-8fa7e9bc39d0)

**Comment by dgirardeau** [comment]
That's fixed: 36cc2b5c910f6999d5ce3f906a27084061509b28

For the next release ;)
