### ISSUE TITLE
Looks like no 2.13 dmg artifact for macos intel platform

### ISSUE THREAD

**Issue by chenrui333** [CloudCompare/CloudCompare#1977]
👋 it looks like for 2.13 release, there is no dmg artifact but just artifact for macos arm? Thanks!

<img width="1700" alt="image" src="https://github.com/CloudCompare/CloudCompare/assets/1580956/213da7bd-c42f-4f60-8e66-7203405004b0">

**Comment by dgirardeau** [comment]
Yes, see https://github.com/CloudCompare/CloudCompare/issues/1974

And by the way, we are looking for someone able to create these packages 👼

**Comment by chenrui333** [comment]
I wonder if you can leverage github action to create the packages and upload there (but there might be some codesign issue)

The bit context in here is I was trying to look for updating the Homebrew cask and realized it does not have dmg file for intel platform.

**Comment by dgirardeau** [comment]
I am far from being a macOS expert, but I believe the challenge is also to compile all the plugins and manage the dependencies (which would be tricky via the github actions, currently the CI is only compiling a small part of them)

**Comment by dgirardeau** [comment]
Good news, Paul has been able to generate a package for arm: https://www.simulation.openfields.fr/index.php/cloudcompare-downloads

(Paul sadly has an issue with his github account and cannot use it at the moment...)
