### ISSUE TITLE
Cloud to cloud distance and point picking distance X and Y signs are opposite to axis positive representation. 

### ISSUE THREAD

**Issue by philosadelphos** [CloudCompare/CloudCompare#1981]
For version 2.13.0 of CC.
In cloud to cloud (distance) computation and point picking distance computation the positive and negative sign of X and Y are not in accordance with the represented XYZ figure or axis schematics.  Please take a look to the next figure in perspective of two clouds.
![Perspective](https://github.com/CloudCompare/CloudCompare/assets/41594980/812fd41a-2ce5-45e0-9f5c-48ab379c9f01)

and also consider the same clouds viewed from the top view (XY plane):
![YX_plane](https://github.com/CloudCompare/CloudCompare/assets/41594980/249cced5-8f9d-4fa1-81df-33651e892930)

If I compute distance by point picking between two clouds, starting from blue (at the top) to red (at the bottom) Z comes negative (which is ok) and X and Y comes positive (which is not ok - should be negative). Then if do the same procedure, but now starting from the red cloud to the blue one, the results are inverted (Z positive and X and Y negative). This results are not in accordance with positive orientation of X and Y axis (represented on bottom right of the image - see top view).

Moreover,  the Cloud to Cloud distance in the X and Y values are opposite at to what one should expect.

**Comment by dgirardeau** [comment]
Well, it would be hard to explain such a bug, as the values are literally the coordinates of one point minus the coordinates of the other point (X2 - X1, Y2 - Y1, Z2 - Z1).

On your captures, it's hard to see the orientation of the axes in the bottom right corner.

One easy test you can do is to apply the opposite translation via the 'Edit > Apply transformation' tool. Normally you'll see the 2 picked points overlap, and the values should be almost zero.

**Comment by philosadelphos** [comment]
> Well, it would be hard to explain such a bug, as the values are literally the coordinates of one point minus the coordinates of the other point (X2 - X1, Y2 - Y1, Z2 - Z1).
> 
Hi there dgirardeau.
The point here is not the math. 
The point is that measured results sign is not in accordance with the positive axis orientation given by scale for X and Y axis, only for Z. 
If you look to the top view (please click the image to expand to full screen), you will see that if you compute distances from rigth to left (X)  and up to down(Y) (i.e., from blue cloud to red cloud) the Z values comes negative (which is correct, according to scale) and Y and X values output are positive (which is not correct, since positive values according to scale are given from left to right orientation for X axis and down to up for Y axis). Inversely, if you compute starting from the red to the blue cloud, Z axis output is positive (which is correct) and this time, X and Y comes negative (which is not in accordance with X, Y scale positive orientation). 

Today I'm not able to print another images with values, in the future I will try to do it. 

I invite you to test and verify the signal of the distance measurements according to the positive axis scale presented in CC. And also to compute C2C distance and see if the signal is an accordance with axis positive orientation.
