### ISSUE TITLE
Apply transformation text box bug when copy and past values

### ISSUE THREAD

**Issue by philosadelphos** [CloudCompare/CloudCompare#1982]
CC version 2.13.0
When one copies to the text box the 3x3 matrice to apply transformation, the values that the matrix on text box exhibits (after copying the intended values) are these ones:

```
1.000178694725 0.000001842324 -0.000724409998 269.427001953125
0.000001842324 1.000166058540 0.005087289959 110.836997985840
0.000724409998 -0.005087289959 1.000165820122 165.822006225586
0.000000000000 0.000000000000 0.000000000000 1.000000000000 
```
meaning that one has to copy again / repeat the past of the copied values for the matrix to assume the intended values I first copied.

Example: 
The default values are these:
```
1.00000000 0.00000000 0.00000000 0.00000000
0.00000000 1.00000000 0.00000000 0.00000000
0.00000000 0.00000000 1.00000000 0.00000000
0.00000000 0.00000000 0.00000000 1.00000000
```
If I copy my values, this ones:
```
0.994	0.111	-0.001	269.427
-0.111	0.994	0.005	110.837
0.001	-0.005	1.000	165.822
0.000	0.000	0.000	1.000
```
The text box exhibits, these:
```
1.000178694725 0.000001842324 -0.000724409998 269.427001953125
0.000001842324 1.000166058540 0.005087289959 110.836997985840
0.000724409998 -0.005087289959 1.000165820122 165.822006225586
0.000000000000 0.000000000000 0.000000000000 1.000000000000 
```
If I copy again, my values, then the final result are what it should be, these:
```
0.994	0.111	-0.001	269.427
-0.111	0.994	0.005	110.837
0.001	-0.005	1.000	165.822
0.000	0.000	0.000	1.000
```
The t

**Comment by dgirardeau** [comment]
Ok, so the fix made by @HeadLessHUN should help normally. You can test the 2.11.1.preview version here: https://www.cloudcompare.org/release/CloudCompare_v2.13.1.preview_setup_x64.exe
