### ISSUE TITLE
Transformation Matrix seems to be wrong/buggy in 2.13.1

### ISSUE THREAD

**Issue by FronoX99** [CloudCompare/CloudCompare#1995]
Our Workflow to Allign a Laser scan to an existing georeferenced Pointcloud seems to not be working as inteded anymore since the update from 2.12 to 2.13

We usualy do small cutouts through both clouds (reference and to be aligned) and start a point allignment with these cuts.

We then apply the resulting Transformation Matrix on the "to be alligned" cloud to bring it as close as possible to the Georefferenced Pointcloud.
 
When i try to execute this Workflow in 2.13 the resulting Transformation Matrix from the Allignment Tool seems to be wrong or is applied in a wrong way when i try to execute it via "apply Transformation".

Furthermore a the Global Shift dialogue opens and seems to double the Original Koordinates from the Pointcloud im trying to Transform and all options seem to shift/transorm in a compleetly wrong direction. 

I tried several things to avoid this "wrong shift" but the only thing to fix it was to rollback to vers. 2.12.

**Comment by HeadLessHUN** [comment]
can you check that it is not related to this bug? So your matrix is changed before apply.

#1982

**Comment by FronoX99** [comment]
thanks for the advice but it was my fault :) .I simply messed up and used the matrix with the applied global shift instead of the matrix to shift..... .
