### ISSUE TITLE
How to Save console output ? I want to save Align Transform Matrics!

### ISSUE THREAD

**Issue by Ever-Bright-V** [CloudCompare/CloudCompare#2013]
![图片](https://github.com/CloudCompare/CloudCompare/assets/57551787/c4f4ab64-0cab-42e7-9f4a-bfe5fdd4e1bb)

**Comment by dgirardeau** [comment]
Hi,

You can simply use CTRL+C / CTRL+V (once the matrix is highlighted, just as in your screen capture).
