### ISSUE TITLE
ICP + CLI - Constraint the translations

### ISSUE THREAD

**Issue by SchmidL** [CloudCompare/CloudCompare#2016]
**Describe the feature you would like**
It is possible to constraints the rotations to 'X', 'Y', 'Z' or even none (Combinations would also be nice)
But I would appreciate that this would also be possible for the translation, as for example, with stationary instruments, the translation is more or less 0

**Describe alternatives you've considered**
Only in the GUI, but that's not very efficient and error-prone

**Comment by HeadLessHUN** [comment]
Hello there is an option see wiki.

https://www.cloudcompare.org/doc/wiki/index.php/Command_line_mode

you can pass argument to  -ROT "value"
where value can be any of "X","Y","Z","XYZ" or "NONE" (similar to the gui version.)

however the documentation seems to be missing but i've implemented the skip translation functions earlier this year.

-SKIP_TX
-SKIP_TY
-SKIP_TZ

#1931

**Comment by dgirardeau** [comment]
Good catch! I've updated the wiki.

**Comment by SchmidL** [comment]
Amazing support! thank you for the fast response! :)
