### ISSUE TITLE
can't save ply txt format file, only can save .bin file on ubuntu18.04 

### ISSUE THREAD

**Issue by Zzzzzz1013** [CloudCompare/CloudCompare#2019]
![image](https://github.com/CloudCompare/CloudCompare/assets/64320952/e775e753-d027-481b-b508-abeba547afff)
When I use Cloudcompare v2.13.1 (Kharkiv -Mar 20, 2021) on Ubuntu 18.04 and drag a ply file into this app, when I try to output the point cloud as a ply file and select the ply format, the result is that only a .bin file is saved. Even changing the extension to .ply, the saved file is still a bin file.

**Comment by tony-hj** [comment]
Hi@Zzzzzz1013 ,have you slove it ? I have metting the same problem.

**Comment by rjanvier** [comment]
I have no such issue on my side. Maybe it's related to the mix with ubuntu 18.04 which is not supported anymore. Please try to update your system if possible.
