### ISSUE TITLE
Cant do measurments anymore

### ISSUE THREAD

**Issue by APOS80** [CloudCompare/CloudCompare#2021]
Cant measure or pointpicking anymore

Cant measure or pointpicking anymore in LAS

**Expected behaviour**

**Additional context**

**Your environment**
 - CC Version (or git hash/tag):
 - OS & Version:
 - Graphics card: 
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
Hey, can you give more information about your setup? OS / screen size / graphic card ...

**Comment by dgirardeau** [comment]
(picking is
