### ISSUE TITLE
Show point cloud normals from Las 1.4 files

### ISSUE THREAD

**Issue by maz-1** [CloudCompare/CloudCompare#2022]
Las specification version 1.4 allows extra dimensions not defined in standard point formats. 
If you read Las point cloud with normals in PDAL, it will map extra dimensions with names like "nx", "normal_x", "normalx", "normal x"  to pdal::Dimension::Id::NormalX (same for y and z)
Currently CloudCompare only treat these dimensions as scalar fields instead of setting ccPointCloud normals.

**Comment by maz-1** [comment]
![屏幕截图 2024-05-31 110549](https://github.com/CloudCompare/CloudCompare/assets/5277060/73554e2d-00fc-4e1a-995d-c4b8df5008bc)

By default, PDAL write normals as dimensions "NormalX" "NormalY" "NormalZ"

**Comment by dgirardeau** [comment]
Which version are you using? Normally, the 2.13.X versions have a "Load As Normals" frame at the bottom to allow specifically for that:
![image](https://github.com/CloudCompare/CloudCompare/assets/2735509/ee8ed558-1f80-45f2-9b6f-5843908c0783)

**Comment by maz-1** [comment]
> Which version are you using? Normally, the 2.13.X versions have a "Load As Normals" frame at the bottom to allow specifically for that: ![image](https://private-user-images.githubusercontent.com/2735509/335443778-ee8ed558-1f80-45f2-9b6f-5843908c0783.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjI1OTMsIm5iZiI6MTcxNzE2MjI5MywicGF0aCI6Ii8yNzM1NTA5LzMzNTQ0Mzc3OC1lZThlZDU1OC0xZjgwLTQ1ZjItOWI2Zi01ODQzOTA4YzA3ODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMTMzMTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE2NGY0Y2I2M2IzYWE3OTFkNWQ5ZTdiMDNhY2ExZWU3MzEwZmFlMjUzMzBhYTZlZDA4M2EwMmQ0NzhlZDZjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JDm5rey_lGjOCD66lRytHdGSrQZ5f-fm4_W1tpooUaM)

I think it is an option in qLASIO? It does not handle las 1.4 files unfortunately. I don't see this option in qPDALIO.

**Comment by dgirardeau** [comment]
(and if you are compiling the project yourself, mind that the old LAS plugins are deprecated 😉 . The only official / supported plugin is qLASIO.

**Comment by maz-1** [comment]
> (and if you are compiling the project yourself, mind that the old LAS plugins are deprecated 😉 . The only official / supported plugin is qLASIO.

You are right, obviously i am using the old laszip3 based plugin
