### ISSUE TITLE
Wrong orientation of rotated point cloud

### ISSUE THREAD

**Issue by bharathrajad** [CloudCompare/CloudCompare#2025]
I tried opening two set of point clouds, one is with zero deg rotation. and another poitn cloud is rotated about z-axis with 45 degree angle. when i open, both the point clouds are showing aligned to z-axis with same angle.
[testPlaneCloud.csv](https://github.com/user-attachments/files/15758388/testPlaneCloud.csv)
[testPlaneCloud_out_rotated.csv](https://github.com/user-attachments/files/15758390/testPlaneCloud_out_rotated.csv)

attaching cloud compare gui screenshot with two point cloud selection, the bounding box is overlapping. 

![Screenshot from 2024-06-10 13-16-18](https://github.com/CloudCompare/CloudCompare/assets/160234928/89ad774e-e3c9-4d05-bd96-efa7aa329a57)

same point clouds visualized in another library vedo for comparison, which shows correctly. 

![Screenshot from 2024-06-10 13-17-48](https://github.com/CloudCompare/CloudCompare/assets/160234928/ba4a98a9-3cb9-49b9-809e-7adfbac4f3f1)

**Comment by dgirardeau** [comment]
If you open the files with a text editor or Excel, you'll see that the contents is exactly the same ;)

Which means that the rotation information is stored somewhere else, and your other tool is finding it one way or another. But I can assure you that the rotation is not stored in the 'rotated' file.
