### ISSUE TITLE
[Load] Can't guess file format: unhandled file extension 'las'

### ISSUE THREAD

**Issue by DapengFeng** [CloudCompare/CloudCompare#2032]
**Describe the bug**

**How to reproduce**

**Expected behaviour**

**Additional context**

**Your environment**
![Screenshot from 2024-07-09 20-59-12](https://github.com/CloudCompare/CloudCompare/assets/18318646/d907c714-4c25-4077-ad73-8528e1e5d6ac)
 - CC Version (or git hash/tag): 7a52d790b9f1afeb16e5bd079db0451651e85cdd
 - OS & Version: Ubuntu 22.04
 - Graphics card:  RTX 4090
 - Qt Version (if compiling): qt 5.15

**Comment by rjanvier** [comment]
Hi, maybe you forgot to compile with las support (PLUGIN_IO_QLAS=ON)?

**Comment by DapengFeng** [comment]
THX! :smile:  @rjanvier
