### ISSUE TITLE
CCCoreLib::HornRegistrationTools::FindAbsoluteOrientation

### ISSUE THREAD

**Issue by YMH-H** [CloudCompare/CloudCompare#2037]
Where can I find the implementation of this function？I want to know the calculation process.Thank you very much.

**Comment by HeadLessHUN** [comment]
you can always use visual studio to trace a code press ctrl and click on the function you are calling.
but here you go the definition, and it just calls another function.
https://github.com/CloudCompare/CCCoreLib/blob/master/src/RegistrationTools.cpp#L928
which is this below.
https://github.com/CloudCompare/CCCoreLib/blob/master/src/RegistrationTools.cpp#L962
