### ISSUE TITLE
Cloud Compare from 2.13.2 saves pcd only in compressed_binary

### ISSUE THREAD

**Issue by christianbussmann** [CloudCompare/CloudCompare#2048]
**Describe the bug**
In our frameworks we use the .pcd format to read pointclouds saved sometimes with tools (e.g. CC)
But since CC 2.13.2 the .pcd saver writes binary_compressed only, which can not be supported in our framework.
Would it be possible to create an option to either save binary, binary_compressed or ascii?
This is a breaking change for us.

**How to reproduce**
1. Load Pointcloud in CC
2. save as .pcd
3. open .pcd with Notepad to view header

**Your environment**
 - CC Version (or git hash/tag): 2.13.2
 - OS & Version: Windows 10
 - Graphics card: -
 - Qt Version (if compiling): -

**Comment by christianbussmann** [comment]
PS....Issue #2048 :D nice ^^

**Comment by dgirardeau** [comment]
Would you need such an option in the GUI version or the command line version?

**Comment by christianbussmann** [comment]
best would be of course both but GUI would be my main concern :)

**Comment by dgirardeau** [comment]
Took me some time, but I have added a GUI dialog and a command line option to control this behavior (see c0226640a35e5fd9b9d83a93499cc40796a9c42a)

The GUI dialog lets you choose the output file format directly upon saving:
![image](https://github.com/user-attachments/assets/2f428d8b-9260-4588-b341-a55d17af1d1c)

And the command line option is:
-PCD_OUTPUT_FORMAT {COMPRESSED_BINARY/BINARY/ASCII}

(to be called before any PCD file is saved)

You can test it with the latest 2.14.alpha version (on Windows): https://www.cloudcompare.org/release/CloudCompare_v2.14.alpha_setup_x64.exe

**Comment by christianbussmann** [comment]
Nice! Looks good. Tested it and it works. 

Maybe an easier option would be (just as another Idea for you) to just add two additional *.pcd Selections in the file format Dropdown? Like here: 
![grafik](https://github.com/user-attachments/assets/345de7ac-0354-4a47-b501-a84eb95f5b8f)
Point Cloud Library cloud Binary Compressed (.pcd) and
Point Cloud Library cloud Binary (.pcd) and
Point Cloud Library cloud Ascii (.pcd).

Then you wouldn't even need the dialog?!

Just as an idea to simplify it maybe. But even when not, this solution is also great. 

Thanks a lot for your work!

Greetings

Christian

**Comment by dgirardeau** [comment]
Ah, sadly that's not possible (plugins and I/O filters can only have one 'filter' each). And the dialog allows me to warn the user about the consequences of choosing the 2 others formats ;)
