### ISSUE TITLE
CC crashes when spatial subsampling with scalarfield

### ISSUE THREAD

**Issue by FelixEickeler** [CloudCompare/CloudCompare#2050]
**Describe the bug**
When -inf (maybe also inf) values are present in the scalarfield the spatial subsampling crashes CloudCompare

**How to reproduce**
1. Open the provided inf.bin 
2. Edit -> Subsample -> Spatial
3. check "Use active SF", and input e.g. 1 & 2
4. click ok

**Expected behaviour**
No crash; Fallback to given value.

**Additional context**
The comandline options are named Fallback, it seems a little different than the interface ?

**Your environment**
 - CC Version: 2.13.1
 - OS & Version: Windows 11 
 - Graphics card: Nvidia A1000
 - Qt Version (if compiling): -
[inf.zip](https://github.com/user-attachments/files/16690235/inf.zip)

**Comment by dgirardeau** [comment]
Ah, I guess it's because all values in your scalar field are -infinity 😅 

I'll try to see how we can make the code more robust to it.

**Comment by dgirardeau** [comment]
For the records, CC should new be more robust to this issue. See commit 5b050db2b40820ad74d4c8f2b488bd306c2762c0 (and https://github.com/CloudCompare/CCCoreLib/commit/06dfe42db46491b357233281cc7f89b6d42c51ac)

And you can test that with the latest 2.14.alpha version (on Windows): https://www.cloudcompare.org/release/CloudCompare_v2.14.alpha_setup_x64.exe
