### ISSUE TITLE
Scaling error on import of second STEP file

### ISSUE THREAD

**Issue by KChludzinski** [CloudCompare/CloudCompare#2053]
When importing STEP files, the first STEP imports normally, but the second will be scaled 1000x smaller than correct. 

Import two STEP files that were originally created in inches into Cloud Compare. 
The first file will import correctly, the second will be scaled to a smaller metric size. 

 - CC Version (or git hash/tag): 2.12.4
 - OS & Version: Windows 11
 - Graphics card: Intel Integrated
 - Qt Version (if compiling): 5.15.2

**Comment by dgirardeau** [comment]
Ok I can confirm this odd behavior.

I believe I have fixed it. See 9c82a819a5e0db71eb00a21a9e5200057b9c2997

You can test it with the latest 2.14.alpha version (on Windows): https://www.cloudcompare.org/release/CloudCompare_v2.14.alpha_setup_x64.exe

**Comment by KChludzinski** [comment]
Just checked the new version and it seems to be fixed - thank you for the help!
