### ISSUE TITLE
ICP stuck irregularly

### ISSUE THREAD

**Issue by fangxiang123** [CloudCompare/CloudCompare#2055]
**Describe the bug**

I successfully compiled the program from the source code. I opened a cloud with 3GB and a mesh of the cloud's model. I did ICP between these two enties, but the congress bar stuck at 99% then the program notices "No Response". This bug won't happen when I first do ICP,  but when I delete the two clouds and reload them again, the ICP trucked and the program crashed.
**Your environment**
 - CC Version (or git hash/tag): 2.13.2
 - OS & Version: Windows10
 - Graphics card: RTX 3080Ti
 - Qt Version (if compiling): 5.14.2

**Comment by dgirardeau** [comment]
Hum, that's a bit weird. Maybe a memory issue...

Have you compiled in Release or Debug mode by the way?

And why are you specifically compiling version 2.13.2? Instead of the master branch (2.14.alpha)?

**Comment by fangxiang123** [comment]
> Hum, that's a bit weird. Maybe a memory issue...
> 
> Have you compiled in Release or Debug mode by the way?
> 
> And why are you specifically compiling version 2.13.2? Instead of the master branch (2.14.alpha)?

I compiled in Release mode.
As a newbie, I have just downloaded the latest source code from the releases.
But I have downloaded the archive version of 2.14.alpha from the https://www.cloudcompare.org/ and the problem reproduced.
Now, I disabled the progress bar during the ICP procedure, the probability of the crash reduced but it will still happen sometimes.
I did the same thing(open two clouds->ICP->delete the two clouds->ICP) on a installer version of 2.11.3,I used before, the crash nerver happend.
Could you tell me the difference between the installer version and the version cmaked by myself? Thank you very much!

**Comment by fangxiang123** [comment]
I guess it's a memory issue but the memory is not full during the whole process

**Comment by dgirardeau** [comment]
Maybe a different version of Qt? Or a different version of the compiler? Which one are you using?

**Comment by fangxiang123** [comment]
> Maybe a different version of Qt? Or a different version of the compiler? Which one are you using?

Qt: 5.14.2
visual studio 2019

**Comment by dgirardeau** [comment]
Hum, not too far away from the official version: Qt 5.15.2 and VS 2017 (but VS 2019 should also work well).

**Comment by dgirardeau** [comment]
See the above PR, I believe this issue should be fixed now with the latest version of CC (online) or the latest master branch if you compile it yourself.
