### ISSUE TITLE
CLI ICP weighting doesn't work

### ISSUE THREAD

**Issue by risto-silvere** [CloudCompare/CloudCompare#2058]
When running ICP algorithm through command line, the -DATA_SF_AS_WEIGHTS parameter doesn't work as expected. 

- If data point cloud contains only 1 scalar field then it will be used as weight if there is a number following DATA_SF_AS_WEIGHTS (doesn't matter if its 0 or 100) but if it is a string then weighting wont be used even if the string is the correct name of scalar field
- If point cloud contains more than 1 scalar field then no weighting will be used no matter what scalar field index or scalar field name is given
- No errors are given if one inputs wrong scalar field name or scalar field index

While doing little bit of debugging I found out that if using CLI this if statement is never true and the code inside is never run
https://github.com/CloudCompare/CloudCompare/blob/ece094a82f2f1fe7c272e0b56b3288c99366e3be/qCC/ccCommandLineCommands.cpp#L6972

If I use GUI to run ICP with weights it works as expected. Also when using CLI with Cloudcompare v2.11.1 installed through snap I was able to use weighting in correct way.

I have attached point clouds which one can use to reproduce this: 
[point_clouds.zip](https://github.com/user-attachments/files/17043572/point_clouds.zip)

They are all las files (don't know if this issue is related to how they are handled) 

- model.las = reference target for ICP
- data_weight_only.las = Point cloud to be aligned with only 1 scalar field containing the weights.
- data_3_fields.las = Point cloud to be aligned with weight scalar field + 2 additional scalar fields
- data_weight_only_REGISTERED.las = Point cloud successfully aligned with ICP using weights

Weights for ICP are in User Data field. 

If I run this I get the correct results:
`/var/lib/flatpak/exports/bin/org.cloudcompare.CloudCompare -SILENT -VERBOSITY 0 -NO_TIMESTAMP -O -GLOBAL_SHIFT AUTO /data/path/data_weight_only.las -O -GLOBAL_SHIFT FIRST /data/path/model.las -C_EXPORT_FMT LAS -ICP -OVERLAP 30 -MIN_ERROR_DIFF 1e-05 -DATA_SF_AS_WEIGHTS 100`

But with these following commands the weights are not used even though they should be:
`/var/lib/flatpak/exports/bin/org.cloudcompare.CloudCompare -SILENT -VERBOSITY 0 -NO_TIMESTAMP -O -GLOBAL_SHIFT AUTO /data/path/data_weight_only.las -O -GLOBAL_SHIFT FIRST /data/path/model.las -C_EXPORT_FMT LAS -ICP -OVERLAP 30 -MIN_ERROR_DIFF 1e-05 -DATA_SF_AS_WEIGHTS 'User Data'`
`/var/lib/flatpak/exports/bin/org.cloudcompare.CloudCompare -SILENT -VERBOSITY 0 -NO_TIMESTAMP -O -GLOBAL_SHIFT AUTO /data/path/data_3_fields.las -O -GLOBAL_SHIFT FIRST /data/path/model.las -C_EXPORT_FMT LAS -ICP -OVERLAP 30 -MIN_ERROR_DIFF 1e-05 -DATA_SF_AS_WEIGHTS 'User Data'`
`/var/lib/flatpak/exports/bin/org.cloudcompare.CloudCompare -SILENT -VERBOSITY 0 -NO_TIMESTAMP -O -GLOBAL_SHIFT AUTO /data/path/data_3_fields.las -O -GLOBAL_SHIFT FIRST /data/path/model.las -C_EXPORT_FMT LAS -ICP -OVERLAP 30 -MIN_ERROR_DIFF 1e-05 -DATA_SF_AS_WEIGHTS 0`

Environment
CC v2.13.2 installed through flatpak (same thing happens when I compiled from sources inside a docker container)
Ubuntu 20.04
Graphics card not used

**Comment by HeadLessHUN** [comment]
well, i did not take a look at the source code right now, but what if you set active scalarfield before and run the command without a scalar field name? Similar to how it works in the gui?

**Comment by risto-silvere** [comment]
> well, i did not take a look at the source code right now, but what if you set active scalarfield before and run the command without a scalar field name? Similar to how it works in the gui?

I'm not quite sure if this is what you meant but it doesn't seem to work.

`/var/lib/flatpak/exports/bin/org.cloudcompare.CloudCompare -SILENT -VERBOSITY 0 -NO_TIMESTAMP -O -GLOBAL_SHIFT AUTO /data/path/data_3_fields.las -O -GLOBAL_SHIFT FIRST /data/path/model.las -C_EXPORT_FMT LAS -SET_ACTIVE_SF 1 -ICP -OVERLAP 30 -MIN_ERROR_DIFF 1e-05 -DATA_SF_AS_WEIGHTS -1`

**Comment by dgirardeau** [comment]
Good catch, that was a silly bug. It's fixed now: d48f07da52685ba203b2b53bda5677fed458c394

Are you able to compile and test on your side?

**Comment by risto-silvere** [comment]
> Good catch, that was a silly bug. It's fixed now: [d48f07d](https://github.com/CloudCompare/CloudCompare/commit/d48f07da52685ba203b2b53bda5677fed458c394)
> 
> Are you able to compile and test on your side?

Yeah I was able test it and everything works as expected! Thank you very much!
