### ISSUE TITLE
ICP randomly frozen with latest Windows version: September 14 binary

### ISSUE THREAD

**Issue by prascle** [CloudCompare/CloudCompare#2060]
**Describe the bug**
I use the defaults parameters on the GUI ICP dialog, with the clouds provided below. The only parameter changed is the overlap: 10%.
On dialog execute, ICP sometimes stays frozen at 99%
![Capture d’écran 2024-09-20 184253](https://github.com/user-attachments/assets/2b9192db-590d-404d-a9d8-0a9c5a7d1297)

**How to reproduce**
Download install and use Windows binary 2.14 alpha (sep 14 2024).
Load clouds22.bin
ICP with cloud01 as reference and cloud02 to be aligned
change Final Overlap to 10%
Execute

**Expected behaviour**
Was working with previous versions

**Additional context**

**Your environment**
 - CC Version  2.14 alpha (sep 14 2024).
 - Windows 11
[clouds22.zip](https://github.com/user-attachments/files/17078145/clouds22.zip)

**Comment by dgirardeau** [comment]
Interesting, let me look at that.

When you say 'previous versions', is it the 2.13.2 or another one in particular?

**Comment by dgirardeau** [comment]
Also, how many threads are used by default on your side?

**Comment by dgirardeau** [comment]
Ha, I've finally managed to reproduce it! It will be hard to debug 😓

**Comment by prascle** [comment]
> Interesting, let me look at that.
> 
> When you say 'previous versions', is it the 2.13.2 or another one in particular?

I am not sure about 2.13.2, this is the first time I have this issue, I have detected it wit my Python tests on CloudComPy while trying to build CloudCompy with CloudCompare up to date...

**Comment by prascle** [comment]
> > Interesting, let me look at that.
> > When you say 'previous versions', is it the 2.13.2 or another one in particular?
> 
> I am not sure about 2.13.2, this is the first time I have this issue, I have detected it with my Python tests on CloudComPy while trying to build CloudCompy with CloudCompare up to date...

I tried without success to reproduce the bug on 2.13.2 Windows binary: The bug has probably been introduced after.

**Comment by dgirardeau** [comment]
Yes, I see that I changed a few things regarding thread safety here: https://github.com/CloudCompare/CCCoreLib/commit/dea0b620c3cfb446f94deeffd4bb6a6d645473af#diff-d9ef26e800aa5a3d944bf264e925ab23fe4ce46065bf7aa5b79f4578a1274769

I'm currently trying to change this and see if it helps.

**Comment by dgirardeau** [comment]
And it could be other commits in CCCoreLib, as the 2.13.X branch still points to this 'old' commit of March 2023 (a8ce4270dfa41d5817842447b27f36094f9dfb51).

**Comment by dgirardeau** [comment]
Ok, I am not sure to fully grasp what the issue was, but apparently, this commit is sufficient to prevent the freeze:
https://github.com/CloudCompare/CCCoreLib/commit/38355ef3e5dd175a99dd52fe21fdcb96fb1d4c7d

And it's only what was modified at lines 819 and 826...

I'll let you test the new version (online).

**Comment by prascle** [comment]
Hello @dgirardeau, I think it's fixed! I can't reproduce the bug anymore.
I tried on Linux with my CloudComPy build and with the corresponding CloudCompre GUI, and also with the latest Windows build.
Nice work! I took a look at the correction in CCCoreLib, sometimes the subtleties of C++ baffle me!

**Comment by prascle** [comment]
Maybe this fix works also for #2055 ?

**Comment by dgirardeau** [comment]
Yes probably! I was looking for this other issue!
