### ISSUE TITLE
Multiple plugin warnings at start up

### ISSUE THREAD

**Issue by Karltlbm** [CloudCompare/CloudCompare#2062]
Hello CloudCompare <3 

Not critical at all because I don't have any crashes or real bug but I am working on a new (but probably old) computer now and ...

Opening Cloud Compare generates multiple warning windows saying "cloudcompare Q_XXX_PLUGIN.dll does not supply metadata in the Q_PLUGIN_METADATA (see one of the example plugins)"
It is the case for several plugins : BLUR, CANUPO, EDL, FACETS, LAS_FWF_IO, QM3C2, QSSAO

Then CC opens normally and it seems that the plugins are here (at least I can see CANUPO in the plugins tab).
I have tried to reinstall and the warnings stay.

Any ideas ?

 CC Version: 2.13.2
 OS & Version: W10

**Comment by dgirardeau** [comment]
Hum, it's possible that there are some outdated plugins left in the CloudCompare 'plugins' folder? What you can do: uninstall CloudCompare, if there's a leftover 'CloudCompare' folder in the Program files directory, delete it. Then re-install CloudCompare. At leas this will guarantee that you have up-to-date plugins. And you should not get this error messages anymore 😅

**Comment by Karltlbm** [comment]
Everything is fine now thanks !
I can enjoy seeing CC open peacefully :)
