### ISSUE TITLE
LAS/LAZ RGB Export Issue

### ISSUE THREAD

**Issue by PMDevine1** [CloudCompare/CloudCompare#2068]
In the latest version of CC 2.14, I am experiencing an issue with saving LAS/LAZ from the GUI.  When I toggle between LAS version 1.2 and 1.4, the "Normals as extra field" toggle box on the Standard LAS Fields tab disappears. 

Additionally, if I proceed to export the LAS/LAZ after this bug occurs, weirdly the normals are exported correctly, but the RGB values are stripped away and lost.

**Comment by dgirardeau** [comment]
Hi, good catch.

Normally, EVLRs (extra bytes) are only officially supported by the LAS 1.4 format. This is probably why the checkboxes were hidden with more recent point formats. And I guess CC should not save extra bytes if a lower format is selected. That's probably a glitch.

However, it seems that some software packages may be saving extra bytes even with V1.2 and V1.3? (TerraScan for instance - at least for some specific fields according to: https://geocue.com/resources/articles/making-use-of-extra-bytes/).

I have a fix where I always show the checkboxes but I prevent the user from interacting with the 'Extra bytes' checkboxes for versions < 1.4. It won't save the extra bytes if they are disabled.

@tmontaigu Do you think it's ok like this, or should we allow to save extra bytes for versions 1.2 and 1.3? (maybe with a warning message).

P.S.: not sure about the colors, unless the point format was not compatible?

**Comment by dgirardeau** [comment]
I've updated a few more things. You can see the PR here: https://github.com/CloudCompare/CloudCompare/pull/2069

**Comment by tmontaigu** [comment]
Yes it should be fine to allow extra bytes for files version less than 1.4, I think I also allow that in laspy

**Comment by dgirardeau** [comment]
Okay I've simplified the code in my PR (so that it's always possible to use the 'export normals' and 'export remaining SFs', unless there's no normal or no SF).

**Comment by dgirardeau** [comment]
This is now merged. It will be integrated in the next 'alpha' release.

Meanwhile, you can use the trick to switch to version 1.4, change the parameters, and then switch back to version 1.2.
