### ISSUE TITLE
Linux Flatpak applications failed to load .las file via 'Open' dialog on Kubuntu

### ISSUE THREAD

**Issue by kekeliu-whu** [CloudCompare/CloudCompare#2072]
**Describe the bug**

Linux Flatpak applications seem to have issues loading the file map.las through the "Open" interface, possibly due to the file being incorrectly identified as a binary type. However, dragging and dropping the file directly into the CloudCompare software with the mouse allows the file to be opened normally.
Additionally, saving files always results in a .ccb format, regardless of the file extension I assign.

**How to reproduce**

Open file failed through the "Open" interface is abnormal:
```
[11:08:16] [BIN] Opening file '/home/rick/lio_out/map.las'...
[11:08:16] [BIN] Version 1.0
[11:08:17] An error occurred while loading 'map': wrong file type (check header)
```
Dragging and dropping is normal:
```
[11:08:35] [LAS] Time SF has been shifted to prevent a loss of accuracy (1715740000.00)
[11:08:43] [LAS] File loaded in 0m8s277ms
[11:08:43] [I/O] File '/home/rick/lio_out/map.las' loaded successfully
```
Saving file through the "Save" interface is abnormal:
```
[13:40:12] [BIN] Output file version: 3.4 (automatically deduced from selected entities)
[13:40:13] [I/O] File '/home/rick/map.las' saved successfully
```

**Expected behaviour**

**Additional context**

```
➜  ~ flatpak info org.cloudcompare.CloudCompare 

CloudCompare - 3D point cloud and mesh processing

          ID: org.cloudcompare.CloudCompare
         Ref: app/org.cloudcompare.CloudCompare/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.13.2
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 693.6 MB
     Runtime: org.kde.Platform/x86_64/5.15-23.08
         Sdk: org.kde.Sdk/x86_64/5.15-23.08

      Commit: 58e6e5984826aed0d5c404aee3dfcddc33dc171a00137a4700174f214b71226e
      Parent: 15ac88c9860b2d2a2df29085927df3b0647f08d3b6dd61084f4800cf16f081bf
     Subject: PROJ: Update proj-9.4.1.tar.gz to 9.5.0 (716e769b)
        Date: 2024-09-16 17:33:16 +0000
```

**Your environment**
 - CC Version (or git hash/tag): 2.13.2
 - OS & Version: Ubuntu20.04
 - Graphics card: 
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
When you open the file via the 'Open' dialog, is the filter set to '*.las' or '*.*'? It looks like you or CloudCompare has selected the BIN filter for a strange reason.

**Comment by kekeliu-whu** [comment]
https://github.com/user-attachments/assets/570b44cf-aa59-4d79-aff0-d83e22c489c8

I have uploaded a reproduction video of the issue. When using the Flatpak version of CloudCompare to open LAS files through the 'Open' option in the interface, the problem always occurs. However, the CloudCompare installed via apt or snap opens the same LAS file without any issues.

**Comment by rjanvier** [comment]
Sorry it seems that I can't access to the screencast and as I wrote before, unfortunately I can't reproduce the bug locally. Be sure to select the good extension in the Ad-Hoc dropdown menu as "bin" extension could be selected by default, thanks.

**Comment by dgirardeau** [comment]
I confirm that the dropdown menu is the right one (according to the video). For a strange reasons, CC uses the BIN filter instead of the LAS one.

**Comment by rjanvier** [comment]
Which desktop environment are you using?

**Comment by kekeliu-whu** [comment]
I've used three PCs, two with `KDE` environments and one with `GNOME` environment. The issue exists on all of them when installing CloudCompare via flatpak install. Besides the problem where reading LAS files is recognized as reading in BIN format, when saving files, regardless of whether I choose LAS, PLY, PCD, or any other format, the point cloud is always forcibly saved as a binary file starting with 'CCB'.

**Comment by rjanvier** [comment]
Sorry I just installed a fresh ubuntu 20.04.6 system on a virtual machine and I was unable to reproduce your issue.
Please give me the output of `flatpak --version`.

**Comment by rjanvier** [comment]
Ok, so we have a suspect :)! is your KDE destktop env a vanilla KUbuntu 20.04?

**Comment by kekeliu-whu** [comment]
Yes, I installed kubuntu using `https://cdimage.ubuntu.com/kubuntu/releases/20.04.6/release/kubuntu-20.04.6-desktop-amd64.iso`.

**Comment by kekeliu-whu** [comment]
Thank you for your help. I can try upgrading my KUbuntu if necessary :)
