### ISSUE TITLE
STL点id出现错误

### ISSUE THREAD

**Issue by wanghao-98** [CloudCompare/CloudCompare#2075]
CC在打开STL文件后，选取点时，其点id是有问题的，因为STL文件本身是存储三角形的，其点顺序是根据三角形的遍历顺序确定的，在使用过程发现CC读取STL文件后，点id存在错误。测试数据如下：
![image](https://github.com/user-attachments/assets/c9187440-b029-476c-a40e-3331fc054536)

第一个三角形顺序为012，第二个134，第三个524
但CC中显示第三个三角形的第一个点的id是10，出现了错误。

![image](https://github.com/user-attachments/assets/6cb75f50-b4c9-458d-b8cc-e030d95a797f)
使用meshlab进行测试法线结果正确。
![image](https://github.com/user-attachments/assets/ea37d6ae-0ce1-4114-9174-0af313237585)

**Comment by dgirardeau** [comment]
CloudCompare does not preserve the original STL vertex order, because it merges the duplicate vertices to have a watertight mesh (and less vertices). So as to be properly processed as any other triangular mesh, or converted to another format.

**Comment by wanghao-98** [comment]
Thank you for your reply! I was testing the normal of the algorithm, CC processing STL and most software or libraries (CGAL, meshlab) have some differences, check the CC source code, found a function to read the STL file to merge duplicate points, maybe the processing method here is different. Maybe the developers have their own ideas when designing, but the difference between the STL point id and the mainstream software/library does make me spend some time looking for possible errors in the algorithm, and I look forward to the developers being able to achieve unity in this convenience, thank you again for your reply, thank you!
![image](https://github.com/user-attachments/assets/50cd0504-5d30-41b0-b79c-04d9d768e2a9)
