### ISSUE TITLE
Will not launch in Mac10.14.6, despite requiring 10.12 or later

### ISSUE THREAD

**Issue by sgath92** [CloudCompare/CloudCompare#2086]
Upon downloading CloudCompare_2.13.2_Universal.dmg or CloudCompare_2.13.2__arm64_PythonPlugin.dmg, neither binary application will launch in Mac 10.14.6. When it launches it will show an alert window that says:

"You can't use this version of the application "CloudCompare" with this version of macOS. You have macOS 10.14.6. The application requires macOS 10.12 or later."

**Comment by dgirardeau** [comment]
@prascle or @rjanvier maybe?

**Comment by rjanvier** [comment]
Hi. I'm not sure you can use the arm64 version of the package, looking at your macOS version, you should have an Intel processor. So at least, the universal dmg should be the right one for you but the universal is compatible with macOS 12.7 or later see https://www.simulation.openfields.fr/index.php/cloudcompare-downloads/7-cloudcompare-macos-binaries/110-cloudcompare-2-13-2-universal-intel-x86-64-and-apple-arm64-without-python-plugin.

**Comment by sgath92** [comment]
That file was one of the two I already tried and returns the same error.

    On Wednesday, November 6, 2024 at 04:45:49 AM EST, Romain Janvier ***@***.***> wrote:  
 
 


Hi. I'm not sure you can use the arm64 version of the package, looking at your macOS version, you should have an Intel processor. So at least, the universal dmg should be the right one for you but the universal is compatible with macOS 12.7 or later see https://www.simulation.openfields.fr/index.php/cloudcompare-downloads/7-cloudcompare-macos-binaries/110-cloudcompare-2-13-2-universal-intel-x86-64-and-apple-arm64-without-python-plugin.

**Comment by rjanvier** [comment]
I sent you the link because it contains the statement it is compatible only with macOS 12.7+ "Built and tested on macOS SONOMA 14.5 (arm64). Compatible with macOS 12.7 and later."
