### ISSUE TITLE
saving/loading pcd file fail when the file path containing none-ascii charactor 

### ISSUE THREAD

**Issue by ZhuLingfeng1993** [CloudCompare/CloudCompare#2087]
When saving/loading pcd file when the file path containing none-ascii charactor, an error occurs, for example, loading file '3 - 副本.pcd', will cause error:
An error occurred while loading '3 - 副本': the third-party library in charge of saving/loading the file has failed to perform the operation

**Comment by dgirardeau** [comment]
Which version are you using? This issue should now be fixed in the latest 2.14.alpha version.
