### ISSUE TITLE
Can not filter cloud with "SOR filter"

### ISSUE THREAD

**Issue by HlKun** [CloudCompare/CloudCompare#2091]
**Describe the bug**

[cloud.zip](https://github.com/user-attachments/files/17798200/cloud.zip)

Use "SOR filter" to filter the point cloud, the progress is stuck at 54%.
Only this one point cloud cannot be processed. I tried other point clouds and they can be processed successfully.

**How to reproduce**
![cdff36559cb4865b29e0a5552d4ef89](https://github.com/user-attachments/assets/575cedda-a8ab-4395-bfc0-0afffb8e039e)

![image](https://github.com/user-attachments/assets/89dd57b5-af1c-4d7e-a00d-75e079e8a6c8)

**Expected behaviour**

This cloud can be filtered by “SOR filter”

**Additional context**

**Your environment**
 - CC Version (or git hash/tag): V2.14alpha （Nov 4 2024）
 - OS & Version: Windows 11
 - Graphics card: Nvidia 4090D

**Comment by dgirardeau** [comment]
Try using 'Tools > Other > Remove duplicate points' first.

It seems there's a lot of points at the same position in this cloud:
`[11:06:02] Cloud 'cloud.laz' has 2468534 duplicate point(s)`

This causes the process to hang because it hangs on this position due to the huge number of points.
