### ISSUE TITLE
There are two problems at compile time

### ISSUE THREAD

**Issue by Canees** [CloudCompare/CloudCompare#2094]
**Describe the bug**

hardware：mac m2 ventura13.0 
qt version: 5.15.10
nanoflann version:1.6.2
The first question is:  A namespace field error occurred while packing（Solution: **The field is replaced**）
<img width="1320" alt="image" src="https://github.com/user-attachments/assets/0fd212af-22be-44f7-9d45-fbafd3b04145">
The second question is:  Certificate cannot be associated
<img width="1320" alt="image" src="https://github.com/user-attachments/assets/f891c1c5-ab9d-4c87-9536-ae39af9c1f3f">

**How to reproduce**
1. cmake --build .
2. cmake --install .

**Expected behaviour**

Compile and install successfully

**Your environment**
 - OS & Version: mac m2 ventura13.0 
 - Qt Version (if compiling): 5.15.10

**Comment by rjanvier** [comment]
Hi, Please update your git submodules in CCCore lib (/libs/qCC_db/extern/CCCoreLib/) (or simply run `git submodule update --recursive .` in CC root folder).

**Comment by Canees** [comment]
> Hi, Please update your git submodules in CCCore lib (/libs/qCC_db/extern/CCCoreLib/) (or simply run `git submodule update --recursive .` in CC root folder).

Thank you for your reply. I have successfully operated, but the running software is unavailable

<img width="1075" alt="image" src="https://github.com/user-attachments/assets/1e4fd043-f31e-4310-871b-4056853dfd6b">
![image](https://github.com/user-attachments/assets/18f6a89b-47d0-4bd7-a92b-6198a55e81d6)
![image](https://github.com/user-attachments/assets/e827b3d7-1901-4d3b-8798-d8b6ab7afa2f)
![image](https://github.com/user-attachments/assets/69a9f0a0-29fb-4eb3-b669-4203fd85e794)

**Comment by Canees** [comment]
> On macOS do not `cmake --install `/ `make instal` because in this case you could to need to sign the bundle (because of things that could land in .app/Content/Framework). Instead simply use the binaries/app present in the build tree and use` -DCC_MAC_DEV_PATHS`.
> 
> If you want to build CC with almost all plugins, we provide a [pixi file](https://github.com/CloudCompare/CloudCompare/blob/3970d2e9a5227c5dd665e5e2f37a286b21554db3/pixi.toml). Simply install [pixi](https://pixi.sh/latest/). Note that unfortunately this build will fail starting from [9f925da](https://github.com/CloudCompare/CloudCompare/commit/9f925da7d2f6381a99c704ef517dbe59fd70f002) because CCPythonRuntime is now out of sync with CC current repo. So you have to either remove all ref to CCPythonRuntime in the pixi.toml file or to work from an older commit
> 
> ```shell
> git checkout 9987df570e071442d53985322d1dc3457997664e  
> git submodule update --recursive .
> pixi run build
> pixi run CloudCompare
> ```

Thanks again for your reply. I am a novice in this field and do not know much about it. According to your prompt, I can already use the dev version
