### ISSUE TITLE
ExamplePlugin Installation

### ISSUE THREAD

**Issue by GEORGIAN86** [CloudCompare/CloudCompare#2096]
I am facing issues while installing it . The whole repo is being cloned but the Plugin is not being shown in GUI.

**Comment by dgirardeau** [comment]
Have you activated it in CMake? (you should have a 'PLUGIN_EXAMPLE_STANDARD' option). Also, you probably need to move its folder to 'plugins/Core/Standard', and add it to the plugins/Core/Standard/CMakeLists.txt file.

But in fact, I would also advise you to duplicate an existing plugin instead (especially one which has a similar behavior to what you are trying to do), as it will be more up-to-date than this old example plugin.

**Comment by GEORGIAN86** [comment]
Thanks got it .
