### ISSUE TITLE
Wrong number of points when opening a point cloud, however OK in CLI/ccViewer

### ISSUE THREAD

**Issue by YDX-2147483647** [CloudCompare/CloudCompare#2099]
**Describe the bug**

While loading a simple 6-point cloud, I get:

> **Oops**
> Hum, do you really expect to load 741682736 point clouds?

![](https://github.com/user-attachments/assets/cdfc7612-637a-4ca4-83d4-5a1393f0ec9b)

However, both CLI mode and ccViewer can load successfully.

**How to reproduce**

1. Save the following as `example.csv`

```csv
0.5,-0.1,0.0,100
0.5,-0.2,0.0,100
0.5,-0.3,0.0,100
0.4,-0.1,0.0,100
0.4,-0.2,0.0,100
0.4,-0.3,0.0,100
```

2. Open CloudCompare,
3. Click on _File → Open_, change file type to _All_, select `example.csv`.
4. Now `Hum, do you really expect to load 741682736 point clouds?`

**Expected behaviour**

The cloud should be loaded successfully.

**Additional context**

I can confirm that none of the following fix it:
- changing the fille name to `example.txt`,
- selecting other file types in the open dialog,
- converting to SBF,
- `flatpak repair`.

However, [CLI mode](https://www.cloudcompare.org/doc/wiki/index.php/Command_line_mode) works:
```shell
$ flatpak run org.cloudcompare.CloudCompare -O example.csv
…
Found one cloud with 6 points
…
```

Dragging into ccViewer also works:

![](https://github.com/user-attachments/assets/0c85cbc0-eeb2-42b9-83d5-3410fa3e750f)

Besides, CloudCompare v2.13.2 (Jul 6 2024) on Windows x86-64 works as expected.

**Your environment**
 - CC Version (or git hash/tag): v2.13.1 (af26e1bd), current latest https://github.com/flathub/org.cloudcompare.CloudCompare/commit/a38a3f5263e60ccfa76d8824c1d68790a71dc54d also fails.
 - OS & Version: Ubuntu 20.04.1, x86_64
 - Graphics card: Intel
 - Qt Version (if compiling): N/A

(I can try to provide further information if needed.)

**Comment by dgirardeau** [comment]
I believe it was a known issue on Linux (the wrong file filter was selected in the File opening dialog, and CC tries to load the ASCII file as a BIN one).

I don't know if it was fixed or if it's a local issue due to the configuration of Ubuntu. Maybe @rjanvier remembers?

**Comment by rjanvier** [comment]
yes that's the issue documented [here](https://github.com/CloudCompare/CloudCompare/issues/2072).

**Comment by YDX-2147483647** [comment]
OK, so possible solutions are the following:.

- Do not _Open_. Instead, just drag the file into CC with the mouse (which is documented in [the wiki](https://www.cloudcompare.org/doc/wiki/index.php/Open#Procedure)).
- Alternatively, upgrade Ubuntu to 22.04+.

(Nevertheless, CloudCompare is really a fantastic libre software that enables insights of point clouds. Thank you all for maintaining it!)

And I see that you added `wontfix`. Closing this issue…

**Comment by rjanvier** [comment]
Yes sorry, Ubuntu 20.04 will reach EOL in April 2025 and I do not have de bandwidth for such issue right now.
