### ISSUE TITLE
Cross section command line not outputting all sections

### ISSUE THREAD

**Issue by m-cross** [CloudCompare/CloudCompare#231]
When using cross section via command line the output differs from the result using the same parameters in the GUI, partial boxes along two edges are not being saved when performed using command line.

The screenshot below shows the same point cloud loaded twice, one being cross sectioned in the GUI and the selected one showing the bounding box of the output files from command line cross section.

![cc_cross_section_output](https://cloud.githubusercontent.com/assets/13248903/9723913/8c38d7ac-5610-11e5-9582-241a6aa7e360.png)

The command line used is:

call "C:\CloudCompare_v2.6.2.beta_bin_x64\CloudCompare.exe" -O "D:\66000_84000_A_Filtered_Transformed.las" -C_EXPORT_FMT LAS -AUTO_SAVE OFF -CROSS_SECTION "D:\CC_Tile.xml" -SAVE_CLOUDS

CC_Tile.xml contents are:

<?xml version="1.0" encoding="utf-8"?>
<CloudCompare>
    <BoxThickness x="100" y="100" z="10" />
    <RepeatDim>0</RepeatDim>
    <RepeatDim>1</RepeatDim>
    <RepeatDim>2</RepeatDim>
    <RepeatGap>0</RepeatGap>
</CloudCompare>

**Comment by cloudcompare** [comment]
Can you repost the content of the xml file? (it has been lost somewhere apparently).

And by the way, in this particular case I don't think you need to call '-SAVE_CLOUDS' (it will just save your input cloud as the sections generated by the 'CROSS_SECTION' tool are not kept in memory). Same thing for 'AUTO_SAVE' (it will be ignored by 'CROSS_SECTION').

**Comment by m-cross** [comment]
Sorry, not used to GitHub markdown. I'm also getting reports from a coworker that this particular script is causing overwritten files due to z axis values in the naming not being correct, I think it's being used without timestamps but I'll look more into it and get back to you if I can get some repro steps.
`<?xml version="1.0" encoding="utf-8"?>
<CloudCompare>
	<BoxThickness x="100" y="100" z="10" />
	<RepeatDim>0</RepeatDim>
	<RepeatDim>1</RepeatDim>
	<RepeatDim>2</RepeatDim>
	<RepeatGap>0</RepeatGap>
</CloudCompare>`

**Comment by asmaloney** [comment]
If this is still an issue with the latest release, please reopen or create a new issue with the details.
