### ISSUE TITLE
Issue more detailed error messages when reading a PLY file (= rPly hack)

### ISSUE THREAD

**Issue by RebelMoogle** [CloudCompare/CloudCompare#276]
If  PLY file conatins a float property that is too large, it gives the error:
[11:23:13] An error occurred while loading 'SurfacePoints_test': reading error (no access right?)

Couldn't attach the file for some reason, so here is a pastebin: http://pastebin.com/1JgWwCej (the last value on the first line makes it break) ( -9.25596e+61 )

**Comment by cloudcompare** [comment]
> too large

Can you provide more information? (figures, examples, etc.)

**Comment by RebelMoogle** [comment]
Sorry hit enter accidentally, should contain more information now.

**Comment by cloudcompare** [comment]
-9.25596e+61 as a float ;)

I'll look at this asap. I guess it's an issue with the way rPly decodes the file.

**Comment by cloudcompare** [comment]
Hum, as I feared there's an internal test in rPly:

`if (*end || *value < -FLT_MAX || *value > FLT_MAX) return 0;`

And as FLT_MAX is 3.402823466e+38F the last value is rejected.

It bugs me a little to remove this internal check (especially since it's legit ;). Where does this value come from?

**Comment by RebelMoogle** [comment]
Well, I think it's good to have the check there, and makes total sense, since it's too large. 
The value itself was actually an error in my code and shouldn't have been there in the first place. 

Maybe a better error message would be nice to have. "value to large for type float" or something.

**Comment by cloudcompare** [comment]
Yep, but sadly rPly (which is a third party library) doesn't give us any feedback.. apart from 0 or 1 when the reading process ends :D
