### ISSUE TITLE
PCL plugins causes seg fault during startup

### ISSUE THREAD

**Issue by cy-goh** [CloudCompare/CloudCompare#292]
/usr/local/CloudCompare/CloudCompare causes seg fault when program is starting. If I delete  libQPCL_IO_PLUGIN.so and pcl 1.7.2 libQPCL_PLUGIN.so, then it'll work.

cloudcompare (trunk 9478bf776f93)

Warnings during cmake:
 OpenMP found

 OpenMP found

 *\* WARNING *\* io features related to pcap will be disabled

 *\* WARNING *\* io features related to png will be disabled

 *\* WARNING *\* io features related to pcap will be disabled

 *\* WARNING *\* io features related to png will be disabled

**Comment by cloudcompare** [comment]
Can you run it in debug mode maybe? This plugin is pretty outdated and personally I only use it on Windows...

**Comment by asmaloney** [comment]
Please open a new issue and fill in the appropriate information if this is still a problem.
