### ISSUE TITLE
Print Mean distance and std deviation from ComputeDistances in Command Line

### ISSUE THREAD

**Issue by Jip-Hop** [CloudCompare/CloudCompare#362]
Hi,

When computing the distance between two point clouds from the command line, the Mean distance and std deviation are only printed to the internal CloudCompare Console. These values are not accessible from external scripts.

I was hoping to fix this by adding a simple Print() statement after line 870 in this file:
https://github.com/cloudcompare/trunk/blob/043170869fdd9157c6f5d2778c8ec48bae9cec37/qCC/ccComparisonDlg.cpp#L870
I'm not sure if that would work but it expect it should be fairly easy to add this functionality.

Best,
Jip

**Comment by cloudcompare** [comment]
Of course this is a hack you could do on your side. We won't be able to add it to the official branch though.

Would it be useful if we add an option to output all the internal Console messages to the system console? Will you be able to retrieve the information then?

**Comment by Jip-Hop** [comment]
That would be awesome! And it would probably solve a lot of similar requests. Sure, I will be able to retrieve the info I need with a regex: `/Mean distance = (.*) \/ std deviation = (.*)/`.

Would this option you suggest be another command line switch?

**Comment by cloudcompare** [comment]
Indeed

**Comment by Jip-Hop** [comment]
Great that would really solve my problem. I'll be looking forward to this new option :)

**Comment by rtoepfer** [comment]
This feature has been implemented.  Use the -LOG_FILE log.txt command line option.

**Comment by amjack0** [comment]
> That would be awesome! And it would probably solve a lot of similar requests. Sure, I will be able to retrieve the info I need with a regex: `/Mean distance = (.*) \/ std deviation = (.*)/`.
> 
> Would this option you suggest be another command line switch?

Can you please type the complete command ? for extracting the data `/Mean distance = (.*) \/ std deviation = (.*)/`
