### ISSUE TITLE
Select points by color / or create custom scalar field based on RGB values

### ISSUE THREAD

**Issue by jo-chemla** [CloudCompare/CloudCompare#363]
I've read the topic http://www.danielgm.net/cc/forum/viewtopic.php?f=9&t=1094 on the forum which explains how to select points by color using Edit > Colors > Convert to SF and Edit > Scalar fields > Filter by value). However, this does not work if I want to select green points for example. 
The ideal would be to allow setting a custom scalar field from RGB values. For example, I could set X = 2^16 x R + 2^8 x G + B and find points where X=000000001111111100000000 in binary. 

Would that be possible ? Or can you implement the select by color functionnality directly ?
Thanks a lot,

**Comment by cloudcompare** [comment]
Well, it's always possible. But the issue is always the same: it's hard to find the time for such very particular requests. Apart if you can actively help for this it won't be on the top priority list.

**Comment by cloudcompare** [comment]
Back on this: to select green points can't you simply export the Green components and filter the points based on this SF?

Otherwise with the 'SF arithmetic' tool you can already build up your custom SF (65536 * R + 256 * G + B) and then filter the points based on this.

**Comment by jo-chemla** [comment]
All points with G=255 are not green (for example RGB=(255,255,255) are white, but have their green channel set to 255. 
But the SF arithmetic tool is exactly what I needed, thanks a lot for that ! I just have to create two constant scalar fields, and make this operation with the SF arithmetic (two operations at a time). Thanks a lot !

**Comment by asmaloney** [comment]
If this isn't solved, please reopen.

**Comment by TokyoWarfare** [comment]
There is a enw plugin Colorimetric Segmenter--->Filter by RGB

So, in the todo list the line 96 could be removed.

"[*] Select points by color (https://github.com/cloudcompare/trunk/issues/363)"

**Comment by dgirardeau** [comment]
Good point! That's a rare event ;)
