### ISSUE TITLE
Model not centering properly

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#371]
From @mankoff #223 

> 3) When loading a file, it is positioned with the center in the upper right corner of the screen, not centered. It also moves there if I re-center with the "1:1" toolbar icon. Even if I manually pan it to center, when I zoom, the zooming only goes to the upper right corner, not the screen center or the new location of the object after I pan it.

I can't reproduce this.  All files I'm loading are centered in the window.  1:1 pulls it right back to the center at the correct zoom level.

What format are you loading?  Maybe we can get a look at the model?

**Comment by mankoff** [comment]
I can re-create this after what I **think** is a clean install. I deleted `~/Library/Preferences/CloudCompare.plist` and `~/Library/Preferences/com.cccorp.CloudCompare.plist`, and am using the bunny https://graphics.stanford.edu/data/3Dscanrep/

Perhaps CC should include a test/sample data set that does *not* require downloading some new file decompressor (7z isn't standard on most computers).

**Comment by asmaloney** [comment]
> (7z isn't standard on most computers).

I'm not seeing any 7zip files there - just the tarred & gzipped **bunny.tar.gz**.  Is that the one you used?

I did the following:

- downloaded that .tar.gz file
- decompressed it
- ran CC 2.7
- opened the **data/bun315.ply** file

The model opened properly centered.

- move it around and zoom in with the mouse
- hit the 1:1 button

And it properly centered.


Maybe you can give me more info about your machine?

- make/model
- OS version
- graphics card
- screen resolution
- anything unusual about your setup?  multiple monitors, etc.
- do you have a "retina" display?  (This might be it?  I don't have one of those.)

**Comment by mankoff** [comment]
Bunny is `.tar.gz`. The example files on the CC website are `.7z`.

Yes, **Retina Display** seems like the likely culprit. Single monitor, 2560x1600.

I'm on a MacBook Pro 2015 version, OS X 10.11.4. 

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Intel Core i7
  Processor Speed:	3.1 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	16 GB
```

And

```
  Chipset Model:	Intel Iris Graphics 6100
  Type:	GPU
  Display Type:	Retina LCD
  Resolution:	2560 x 1600 Retina
  Retina:	Yes
```

**Comment by asmaloney** [comment]
RE: examples
Oh - I thought you were referencing the bunny you'd just mentioned.  "Better downloadable examples" - another issue!

Yes, retina seems like the good explanation for what you're seeing.  I know @cloudcompare made some changes that were supposed to support retina displays.  I'll wait for him to weigh-in on it.

Unfortunately neither he nor I have one to develop and test with.

**Comment by cloudcompare** [comment]
I agree, this looks a lot like an issue with the OpenGL viewport. I guess the only way to fix this will be to get a hand on a 'Retina' screen.

**Comment by cloudcompare** [comment]
And here is some more info:
http://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/

**Comment by mankoff** [comment]
`1:1` works on Retina display with CC beta7.
