### ISSUE TITLE
Smooth zoom

### ISSUE THREAD

**Issue by foobarbecue** [CloudCompare/CloudCompare#382]
The recent addition of the ability to change the zoom increment was very welcome. However, it would be nice if we could click and drag to zoom smoothly. I'd be happy with a key combo or middle mouse click+drag.

(I work on landscape-scale models where there are a few areas where high detail is needed so I'm often working at the km scale and then the cm scale on the same point cloud / mesh.)

**Comment by cloudcompare** [comment]
Okay I added this to the TODO list.

**Comment by NeroBurner** [comment]
Any updates on this? Where would I have to start to add this functionality to the viewer?

**Comment by dgirardeau** [comment]
I guess you would have to change how the zoom is handled, typically with the wheel mouse for now: https://github.com/CloudCompare/CloudCompare/blob/master/libs/qCC_glWindow/ccGLWindow.cpp#L4520
