### ISSUE TITLE
qCC on osx: cannot drag and drop dbtree items when main window is not maximized

### ISSUE THREAD

**Issue by luca-penasa** [CloudCompare/CloudCompare#389]
- possibly related to issue #372 
- to be indipendently verified by somebody on an osx
  
  When having the qCC window open at half-monitor size  (e.g. in the right half monitor space) drag and drop operations on the tree cannot be performed as expected. dragging works as expected creating the "dragging" icon that can be moved around with the mouse, but when dropping the "dragging" icon rapidly moves on the screen without finishing the drop operation - exactly like when one try to drop on the wrong place - and the icons just goes back to its own place. Unfortunately qt seems to think that the "original place" is where the dragged icon would be if cc was completely open on the screen (not full screen mode, but just maximized) and you see the dragged icon fly  to that location. I suspect qt is fooled in retrieving the right on-screen coordinates, thus it does no recognize the drop location as acceptable and it moves back the dragging ion to the wrong place too.

**Comment by asmaloney** [comment]
@luca-penasa When you get a change can you please try to reproduce this with beta3 from [here](https://asmaloney.com/software/)?

I fixed #372 but could never reproduce this issue.  I did read about a Qt issue with it using global vs. local coordinates in D&D at some point, so maybe that's what this is...

**Comment by mankoff** [comment]
Dragging of toolbars and DB/Properties/Console all work for me on Retina display if the window is maximized or not. However, I can put any of the three below the 3D View window, and DB/Properties to the left or right, but I can only have the Console on the bottom.

**Comment by asmaloney** [comment]
I think what you're describing is exactly the way Qt lays out toolbars and dock widgets in the main window.  Please see [the diagram here](https://doc.qt.io/qt-5/qmainwindow.html#details). So you can't sort of mix-and-match toolbars and dock widgets.

Does that fit with what you're seeing?

**Comment by mankoff** [comment]
Sorry my previous comment was unclear. "Any of the three" meant "DB/Properties/Console", which are all the same item as far as I can tell. Yet I can't put the Console on the side, the way I can the DB and Properties. This has nothing to do with the toolbars, and I don't think it matters much. I think the bug could be closed - dragging items seems to work on Retina now.

**Comment by asmaloney** [comment]
Oh I see.  Yes - all three of those are dock widgets. The console is not marked as "movable", and it's only allowed in the bottom dock area.  It can be turned into a floating window though.

So I think this is as designed.

What you're describing with the dock widgets is not what I read Luca's issue to be though.  I read it as something to do with dragging items around in the db tree itself. I'll let @luca-penasa try the latest version and chime-in about this issue when he gets a chance.

**Comment by asmaloney** [comment]
If this isn't solved, please reopen.
