### ISSUE TITLE
Crash loading multiple PLY files

### ISSUE THREAD

**Issue by ghost** [CloudCompare/CloudCompare#393]
- Drag and drop a first file (PLY) on a 3D view: the Load PLY dialog appears.
- Drag and drop a second file (PLY) on a 3D view (while the previous Load PLY dialog is already active). A second Load PLY dialog appears
- Accept the first dialog (ok)
- Accept the second dialog (crash)

**Comment by asmaloney** [comment]
Cannot reproduce on macOS - does not allow the second drag.

**Comment by tmontaigu** [comment]
Closing as the issue is quite old, the OP is a deleted account and I also cannot reproduce the bug either.
