### ISSUE TITLE
Request --> IO --> ASCII --> cloud name in comments

### ISSUE THREAD

**Issue by aboulch** [CloudCompare/CloudCompare#394]
Hello,

I am using the ASCII export for project export, could it be possible to add the cloud name as a comment line (like the column labels). It would be useful when loading the ASCII files with other soft (python, matlab...).

ex : 
// here_goes_the_name
// X Y Z
0.101 0.22 6.7
0.8 ...

Thanks.

**Comment by ORNis** [comment]
is filename not enough ?

**Comment by aboulch** [comment]
Actually, when I have a project looking like:

# Dir: Cloud_0
    |
    --> Pointcloud: subCloud_1
    |
    --> PointCloud: subCloud_2

and when I save the Cloud_0 as ASCII, it saves all subcloud as: 
    Cloud_0_000000.asc
    Cloud_0_000001.asc
    ...
where the name correspond to an index I cannot relate to "subCloud1" or "subCloud2".
What I propose could be either that the saving names are:
    Cloud_0_000000_subCloud_1.asc
    Cloud_0_000001_subCloud_2.asc
or in Cloud_0_000000.asc to be able to get something like:
    // subCloud_1
    // X Y Z
    0.101 0.22 6.7
   0.8 ...

I am not sure I am very clear.

**Comment by ORNis** [comment]
Ok, I push the change

**Comment by aboulch** [comment]
Thank you.

**Comment by asmaloney** [comment]
Looks like this is fixed? If not, please reopen.
