### ISSUE TITLE
include "PlyFilter.h" in a standalone app breaks linkage

### ISSUE THREAD

**Issue by vdaanen** [CloudCompare/CloudCompare#400]
Hi,
# including file PlyWriter.h in a source file from a standalone project, breaks compilation with the following errors:

1>....\cc\trunk-master\plugins\qpoissonrecon\poissonreconlib\src_cc_wrap../Src/Ply.h(190): error C2733: 'ply_write' : second C linkage of overloaded function not allowed
1>          ....\cc\trunk-master\libs\qcc_io\rply.h(342) : see declaration of 'ply_write'
1>....\cc\trunk-master\plugins\qpoissonrecon\poissonreconlib\src_cc_wrap../Src/Ply.h(200): error C2733: 'ply_read' : second C linkage of overloaded function not allowed
1>          ......\cc\trunk-master\libs\qcc_io\rply.h(166) : see declaration of 'ply_read'
1>....\cc\trunk-master\plugins\qpoissonrecon\poissonreconlib\src_cc_wrap../Src/Ply.h(209): error C2733: 'ply_close' : second C linkage of overloaded function not allowed
1>          .....\cc\trunk-master\libs\qcc_io\rply.h(351) : see declaration of 'ply_close'

Any hint on how to fix this ?

V

Ps: my configurationn is the following: Visual Studio 2013 SP5,  Qt 5.6.0, Windows 10

**Comment by dgirardeau** [comment]
It's because PoissonRecon includes its own blend of RPly... The easiest way to fix this may be to comment all these methods in Poisson as they are not used.

**Comment by vdaanen** [comment]
Functions 'ply*' are used by templated class 'PLYOrientedPointStreamWithData'.. It seems to be non trivial to remove  the 'ply' file related functions...at least for me

**Comment by dgirardeau** [comment]
Then you could encapsulate PoissonRecon in a simple shell (exchanging only points, normals and triangles indexes)?

**Comment by asmaloney** [comment]
If this is still an issue, please reopen.
