### ISSUE TITLE
Build issue on MacOSX 

### ISSUE THREAD

**Issue by enptfb55** [CloudCompare/CloudCompare#407]
Looks like there is an issue in the last commit (2bf36e50fb83997bc32ea8d9bde37f95253f4bb3) of ccviewer.cpp for the MacOSX build 

The variable name pluginsPath was replaced by appPath but it was not updated in the Mac section

[ccviewer_patch.txt](https://github.com/cloudcompare/trunk/files/333718/ccviewer_patch.txt)

**Comment by dgirardeau** [comment]
Thanks for the feedback!

Can you make a pull request or should I apply your patch myself?

**Comment by asmaloney** [comment]
As I mention [over here](https://github.com/cloudcompare/trunk/pull/410), I don't think this is a complete fix.  It will make it compile, but I don't think it will use all paths properly for finding plugins.

**Comment by enptfb55** [comment]
Sorry! Didn't realize this issue was already being tracked.

**Comment by asmaloney** [comment]
I think you were first to report it and offer a fix - the other one just put the issue on my radar.

Either way, thanks to both of you for the report and looking into it!  I'll look at doing some cleanup for it as soon as I have some time.
