### ISSUE TITLE
How to compile the plugins by using QT

### ISSUE THREAD

**Issue by scjhan** [CloudCompare/CloudCompare#435]
I'm compiling the cloudcompare source code with QT5.6 in  windows10, now I have completed those work:
1. Using Qt to generate and build the trunk-master.
2. Generating the folder(`C:\Program Files\CloudCompareProjects`), and I can open the **CloudCompare.exe**.
Now the question is that the plugins seem not be loaded, Actually, I haven't compile the plugins, So how can I compile the plugins and let them loaded by CloudCompare.
For example, the `qBlur` plugin which has those file in it's private folder:

```
CMakeLists.txt
qBlur.cpp
qBlur.h
```

@cloudcompare ,How can I compile it ?

**Comment by cloudcompare** [comment]
You'll have to enable the corresponding options in CMake.

All plugins have a ```INSTALL_XXX_PLUGIN``` option. You have to check it and the click on 'Configure' again. Depending on the plugin you may have to setup additional dependencies.

And last but not least, when you generate the project file don't forget to compile the 'INSTALL' project (it will copy everything in the right place).
