### ISSUE TITLE
Multi-thread segmentation and colouring up

### ISSUE THREAD

**Issue by PeterJCC** [CloudCompare/CloudCompare#437]
I would like to run Segmentation and Colouting up multi-threaded.

Is it true that clouds are splitted to smaller chunks in RAM?

Could you point me in right direction to multi-tread function call. Are you using somewhere in code multi-thread?

**Comment by cloudcompare** [comment]
Hi,

We are using two multi-threading mechanisms:
- either the Qt Concurrent Framework (and more especially the ```QtConcurrent::blockingMap``` function). See DgmOctree.cpp for instance.
- or the simpler Open MP ```#pragma omp parallel for``` macro that automatically executes a 'for' loop in parallel (search for _OPENMP and you'll see it's used in many places)
