### ISSUE TITLE
CC crashes on startup with MacOS Sierra

### ISSUE THREAD

**Issue by forensicarchitecture** [CloudCompare/CloudCompare#439]
I'm have been running CC for over a year now on my MB Pro. since updating to MacOS Sierra CC has been crashing as it opens up. attaching the crash report below. 
Has anyone encountered this? 

Crash Report
Process:               CloudCompare [14903]
Path:                  /Applications/CloudCompare.app/Contents/MacOS/CloudCompare
Identifier:            CloudCompare
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           CloudCompare [14903]
User ID:               501

Date/Time:             2016-09-27 15:11:12.392 +0100
OS Version:            Mac OS X 10.12 (16A323)
Report Version:        12
Anonymous UUID:        55A00A8C-BABC-CCFA-2F12-16D0FD5FAED3

Sleep/Wake UUID:       AF33A7AF-988B-4177-96C9-44EFDDCFD347

Time Awake Since Boot: 60000 seconds
Time Since Wake:       12000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGKILL)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    EXEC, [0xc] This UPX compressed binary contains an invalid Mach-O header and cannot be loaded.

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib          0x00007fffeb89cbb2 __posix_spawn + 10
1   libsystem_kernel.dylib          0x00007fffeb897ef2 posix_spawn + 386
2   xpcproxy                        0x000000010d6dfd75 0x10d6dd000 + 11637
3   xpcproxy                        0x000000010d6e0992 0x10d6dd000 + 14738
4   libdyld.dylib                   0x00007fffeb76e255 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000000000000d  rbx: 0x0000000000000000  rcx: 0x00007fff52522388  rdx: 0x00007fff525223a0
  rdi: 0x0000000000000000  rsi: 0x00007f9af38006e5  rbp: 0x00007fff52522430  rsp: 0x00007fff52522388
   r8: 0x00007f9af2c02ef0   r9: 0x00007f9af2c02ef0  r10: 0x00007f9af2d00250  r11: 0x0000000000000202
  r12: 0x00007f9af2d00250  r13: 0x00007f9af38006e5  r14: 0x00007fff52522950  r15: 0x00007fff52522958
  rip: 0x00007fffeb89cbb2  rfl: 0x0000000000000203  cr2: 0x00007ffff444c0a8

Logical CPU:     0
Error Code:      0x020000f4
Trap Number:     133

Binary Images:
       0x10d6dd000 -        0x10d6e1ffb  xpcproxy (2.0.0 - 972.1.5) <625A730D-D6CA-3B26-ABFC-E0FD9005BAB6> /usr/libexec/xpcproxy
       0x110a3b000 -        0x110a781c7  dyld (421.1) <A525EAEA-AF86-30C2-B360-3D093B4F0828> /usr/lib/dyld
    0x7fffea176000 -     0x7fffea177ff3  libSystem.B.dylib (1238) <168B3C56-081B-3998-9A44-681EB4C6828F> /usr/lib/libSystem.B.dylib
    0x7fffea2ed000 -     0x7fffea2edff3  libauto.dylib (187) <5BBF6A00-CC76-389D-84E7-CA88EDADE683> /usr/lib/libauto.dylib
    0x7fffea30e000 -     0x7fffea364ff7  libc++.1.dylib (307.4) <BEE86868-F831-384C-919E-2B286ACFE87C> /usr/lib/libc++.1.dylib
    0x7fffea365000 -     0x7fffea38ffff  libc++abi.dylib (307.2) <1CEF8ABB-7E6D-3C2F-8E0A-E7884478DD23> /usr/lib/libc++abi.dylib
    0x7fffeae7e000 -     0x7fffeb253127  libobjc.A.dylib (706) <47104A1B-13E8-369F-BC36-27FF465809FD> /usr/lib/libobjc.A.dylib
    0x7fffeb692000 -     0x7fffeb696ff7  libcache.dylib (79) <84E55656-FDA9-3B29-9E4F-BE31B2C0AA3C> /usr/lib/system/libcache.dylib
    0x7fffeb697000 -     0x7fffeb6a1fff  libcommonCrypto.dylib (60092.1.2) <79F738D8-0AD7-3DEA-AF80-E0F8B90B74E3> /usr/lib/system/libcommonCrypto.dylib
    0x7fffeb6a2000 -     0x7fffeb6a9fff  libcompiler_rt.dylib (62) <486BDE52-81B4-3446-BD72-23977CAE556F> /usr/lib/system/libcompiler_rt.dylib
    0x7fffeb6aa000 -     0x7fffeb6b2fff  libcopyfile.dylib (138) <0DA49B77-56EC-362D-98FF-FA78CFD986D6> /usr/lib/system/libcopyfile.dylib
    0x7fffeb6b3000 -     0x7fffeb735ff3  libcorecrypto.dylib (442.1.3) <1CA8B679-810E-3C04-945A-4AC19372CDC7> /usr/lib/system/libcorecrypto.dylib
    0x7fffeb736000 -     0x7fffeb768fff  libdispatch.dylib (703.1.4) <12B1D95B-283D-325D-85AB-29A2FFD36987> /usr/lib/system/libdispatch.dylib
    0x7fffeb769000 -     0x7fffeb76eff3  libdyld.dylib (421.1) <CDFBDC9C-418C-369D-B433-F64B0630E640> /usr/lib/system/libdyld.dylib
    0x7fffeb76f000 -     0x7fffeb76fffb  libkeymgr.dylib (28) <09CD7CA6-46D2-3A9F-B9F1-7C4CA5CA0D68> /usr/lib/system/libkeymgr.dylib
    0x7fffeb77d000 -     0x7fffeb77dfff  liblaunch.dylib (972.1.5) <DC31FDEA-FD81-335E-BAA8-5A7395D20772> /usr/lib/system/liblaunch.dylib
    0x7fffeb77e000 -     0x7fffeb783fff  libmacho.dylib (894) <1EAE5ADD-490C-3B1F-9F97-447BA8E0E90F> /usr/lib/system/libmacho.dylib
    0x7fffeb784000 -     0x7fffeb786ff3  libquarantine.dylib (85) <78EF62D8-C890-3FC0-937A-C2FD8CEF8992> /usr/lib/system/libquarantine.dylib
    0x7fffeb787000 -     0x7fffeb788ffb  libremovefile.dylib (45) <C4FC07FF-ED86-382E-B06F-33C34718080C> /usr/lib/system/libremovefile.dylib
    0x7fffeb789000 -     0x7fffeb7a1ff7  libsystem_asl.dylib (349.1.1) <F0987490-8427-367F-B302-A05A7D61FEBF> /usr/lib/system/libsystem_asl.dylib
    0x7fffeb7a2000 -     0x7fffeb7a2ff7  libsystem_blocks.dylib (67) <B8C3701D-5A91-3D35-999D-2DC8D5393525> /usr/lib/system/libsystem_blocks.dylib
    0x7fffeb7a3000 -     0x7fffeb830fe7  libsystem_c.dylib (1158.1.2) <5F260836-48E4-3F57-8553-62D2DA228A1F> /usr/lib/system/libsystem_c.dylib
    0x7fffeb831000 -     0x7fffeb834ffb  libsystem_configuration.dylib (888.1.2) <67BB9D8B-2430-38AD-81A7-F0EC924B2590> /usr/lib/system/libsystem_configuration.dylib
    0x7fffeb835000 -     0x7fffeb838fff  libsystem_coreservices.dylib (41.1) <11F22E6C-0DCB-3699-A4F0-C99E301E56E9> /usr/lib/system/libsystem_coreservices.dylib
    0x7fffeb839000 -     0x7fffeb851ffb  libsystem_coretls.dylib (121.1.1) <8F7E9B12-400D-3276-A9C5-4546B0258554> /usr/lib/system/libsystem_coretls.dylib
    0x7fffeb852000 -     0x7fffeb858fff  libsystem_dnssd.dylib (765.1.2) <C5FF2025-C60B-39C6-B205-6BF1BC51D1B3> /usr/lib/system/libsystem_dnssd.dylib
    0x7fffeb859000 -     0x7fffeb882fff  libsystem_info.dylib (503) <C686B834-5E7D-382C-AF6E-44AB78EE83E2> /usr/lib/system/libsystem_info.dylib
    0x7fffeb883000 -     0x7fffeb8a5ff7  libsystem_kernel.dylib (3789.1.32) <5C68A0D7-C3C9-3E52-B983-EDE9A28AB6FC> /usr/lib/system/libsystem_kernel.dylib
    0x7fffeb8a6000 -     0x7fffeb8edfe7  libsystem_m.dylib (3121.4) <E3370D16-EBAA-3C7F-AC56-2D6EAD7DB0A4> /usr/lib/system/libsystem_m.dylib
    0x7fffeb8ee000 -     0x7fffeb90cff7  libsystem_malloc.dylib (116) <3DD17B88-B7A4-38B9-9E95-AB88E1C3B647> /usr/lib/system/libsystem_malloc.dylib
    0x7fffeb90d000 -     0x7fffeb963fff  libsystem_network.dylib (856.1.8) <A8973360-956A-33BF-9971-14D59C84E0D1> /usr/lib/system/libsystem_network.dylib
    0x7fffeb964000 -     0x7fffeb96dff3  libsystem_networkextension.dylib (563.1.11) <1C551832-9360-36DD-A7BA-52B55A171720> /usr/lib/system/libsystem_networkextension.dylib
    0x7fffeb96e000 -     0x7fffeb977ffb  libsystem_notify.dylib (165) <AF77D471-6B13-36BA-B144-7E7DDB9DBA9F> /usr/lib/system/libsystem_notify.dylib
    0x7fffeb978000 -     0x7fffeb980fe7  libsystem_platform.dylib (126.1.2) <884DDF42-3CAE-334A-82CE-965617130FB1> /usr/lib/system/libsystem_platform.dylib
    0x7fffeb981000 -     0x7fffeb98bfff  libsystem_pthread.dylib (218.1.3) <050AE77B-4F4B-334A-A5BA-CF0D10AF5304> /usr/lib/system/libsystem_pthread.dylib
    0x7fffeb98c000 -     0x7fffeb98ffff  libsystem_sandbox.dylib (592.1.3) <90FEF628-316D-3F84-9EF4-F7F510A4FBBB> /usr/lib/system/libsystem_sandbox.dylib
    0x7fffeb990000 -     0x7fffeb991fff  libsystem_secinit.dylib (24) <A54B8FEF-E792-3C54-8E0B-E80A376662F2> /usr/lib/system/libsystem_secinit.dylib
    0x7fffeb992000 -     0x7fffeb999fff  libsystem_symptoms.dylib (532.1.1) <B26F656E-94F9-3834-9B03-51C4FF11D1BF> /usr/lib/system/libsystem_symptoms.dylib
    0x7fffeb99a000 -     0x7fffeb9baff7  libsystem_trace.dylib (518.1.16) <C3CDF7BC-CA3D-34F5-ADF8-46AAAB0B47F8> /usr/lib/system/libsystem_trace.dylib
    0x7fffeb9bb000 -     0x7fffeb9c0ffb  libunwind.dylib (35.3) <9F7C2AD8-A9A7-3DE4-828D-B0F0F166AAA0> /usr/lib/system/libunwind.dylib
    0x7fffeb9c1000 -     0x7fffeb9eaff7  libxpc.dylib (972.1.5) <2A901937-48E1-3BF2-83F1-2431156D82B7> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 31679
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=119.2M resident=0K(0%) swapped_out_or_unallocated=119.2M(100%)
Writable regions: Total=36.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=36.4M(100%)

```
                            VIRTUAL   REGION 
```

REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        2 
MALLOC                            28.2M        8 
MALLOC guard page                   16K        4 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                          4K        2 
__DATA                            1460K       43 
__LINKEDIT                       111.3M        4 
__TEXT                            8104K       42 
shared memory                       12K        4 
===========                     =======  ======= 
TOTAL                            212.8M      103 

Model: MacBookPro10,1, BootROM MBP101.00EE.B0A, 4 processors, Intel Core i7, 2.3 GHz, 8 GB, SMC 2.3f36
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Graphics: NVIDIA GeForce GT 650M, NVIDIA GeForce GT 650M, PCIe, 1024 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54333531533642465238432D50422020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54333531533642465238432D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xEF), Broadcom BCM43xx 1.0 (7.21.171.10.1a16)
Bluetooth: Version 5.0.0f18, 3 services, 17 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM256E, 251 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
USB Device: My Passport 0827
Thunderbolt Bus: MacBook Pro, Apple Inc., 23.4

**Comment by asmaloney** [comment]
I use UPX binary compressor when packaging CC, and apparently Apple has decided to break binary compression with macOS 10.12.  It's probably going to break a variety of apps.

The UPX developers are [tracking the issue](upx/upx#4) and will likely have a fix "soon".  I might be able to repackage 2.7 to work once they've released a fix.  If not, I'll make sure the next release of CC fixes this.

**Comment by forensicarchitecture** [comment]
Hi Andy, thank you for the reply. I’ll look out for the fixed update or release once they come out.
Ariel

On 27 Sep 2016, at 21:11, Andy Maloney <notifications@github.com<mailto:notifications@github.com>> wrote:


I use UPX binary compressor when packaging CC, and apparently Apple has decided to break binary compression with macOS 10.12. It's probably going to break a variety of apps.

The UPX developers are tracking the issue<x-msg://1/upx/upx#4> and will likely have a fix "soon". I might be able to repackage 2.7 to work once they've released a fix. If not, I'll make sure the next release of CC fixes this.

**Comment by pyscajor** [comment]
I have this problem too on both my Macs. Good to know that it's a known problem with a fix on the horizon. It looks like UPX might have been [fixed](https://github.com/upx/upx/issues/4#issuecomment-250995829).

Thanks @asmaloney for all your hard work!

**Comment by asmaloney** [comment]
They're still working on it - issue is still open and I think they are testing all the combinations - but they haven't put out a release yet.

Thanks!

**Comment by DavidFDuggins** [comment]
Wish I had read this before updating to Sierra. CC now crashes when I try to run it.

**Comment by swinersha** [comment]
Same for me too.

**Comment by bsdooby** [comment]
+1

**Comment by Xactsense** [comment]
Please please please... this is really effecting my workflow.
Love you guys ! Thanks !

**Comment by asmaloney** [comment]
I have put up a 2.8 beta release that removes compression for now.  You can get it here:

  https://asmaloney.com/software/

It's a beta so you will encounter other issues I'm sure.  Please report them as noted on that page.  (Especially any high DPI display issues - please check what has [already been reported](https://github.com/cloudcompare/trunk/labels/Retina%20hell) and add to those issues instead of creating new ones.)

So this issue isn't fixed and I will be asking for people to test a future beta when the UPX guys get their end sorted out.

**Comment by swinersha** [comment]
Thanks Andy!
-----
Tom Swinfield, PhD
RSPB Technical Advisor
Environment, Research & Development
Harapan Rainforest 
(+44) 07496 549142

**Comment by forensicarchitecture** [comment]
Amazing! thanks so much Andy.

On 17 Nov 2016, at 16:38, Andy Maloney <notifications@github.com<mailto:notifications@github.com>> wrote:


I have put up a 2.8 beta release that removes compression for now. You can get it here:

https://asmaloney.com/software/

It's a beta so you will encounter other issues I'm sure. Please report them as noted on that page. (Especially any high DPI display issues - please check what has already been reported<https://github.com/cloudcompare/trunk/labels/Retina%20hell> and add to those issues instead of creating new ones.)

So this issue isn't fixed and I will be asking for people to test a future beta when the UPX guys get their end sorted out.

**Comment by DavidFDuggins** [comment]
Thank You!!!!

Best Regards,

*Dave*

Dave Duggins
Director of Customer Engagement
dave@kaarta.com
5001 Baum Blvd Suite #430
Pittsburgh, PA   15213
www.kaarta.com

**Comment by pyscajor** [comment]
Thank you. Works perfectly! Deeply appreciated.

**Comment by asmaloney** [comment]
**Update:** The UPX guys have a fix for this and a tentative release date of [27 November](https://github.com/upx/upx/commit/27d30121ab7ed61e0dbdcb264d1544132ae5169a).

In the meantime I have [beta3 up for download](https://asmaloney.com/software/) with fixes for launching CC Viewer and the toolbar dragging causing the window to jump around and resize.

**Comment by asmaloney** [comment]
I'm going to ship 2.8 with UPX compression since there still seem to be problems with it. Will look at using it again in the next release.
