### ISSUE TITLE
Point picking and Retina display

### ISSUE THREAD

**Issue by macsurveyr** [CloudCompare/CloudCompare#461]
Choosing Point picking and selecting a point results in the point being selected and highlighted correctly but the info box leader is not to/from the point. The attached image Point_picking.png shows the issue

The same symptoms seem to be with Point List picking as well - see the attached image Point_list_after_picking.png
<img width="1680" alt="point_picking" src="https://cloud.githubusercontent.com/assets/810679/20409731/f22340ba-acd7-11e6-97f3-fc73b9f00586.png">
<img width="1680" alt="point_list_after_picking" src="https://cloud.githubusercontent.com/assets/810679/20409737/fb45c2e4-acd7-11e6-97bf-89ccb6ff8a1b.png">

## Expected Behavior
On other macOS systems with non-retina displays leader line properly points to the selected point correctly.
## Your Environment

* OS & Version: macOS 10.12.1 
* CC Version: 2.8 beta Mac OS 64 bit
* Graphics card: AMD Radeon Pro 460

**Comment by macsurveyr** [comment]
@asmaloney Here are 4 screenshots of the latest beta behavior. Point as picked and then point picked then zoomed out a bit. Notice the label and text do not move when zooming but the leader does. Point list picked two points and then also zoomed out a bit. The point labels move when zooming.

Tom
<img width="640" alt="point_picked" src="https://cloud.githubusercontent.com/assets/810679/20630920/37ebd08e-b2f1-11e6-8c90-0f99403a9bfb.png">
<img width="640" alt="point_picked_zoomedout" src="https://cloud.githubusercontent.com/assets/810679/20630926/42501c74-b2f1-11e6-876c-b92c1f2d0bd5.png">
<img width="640" alt="pointlist_picked" src="https://cloud.githubusercontent.com/assets/810679/20630934/4bc6d838-b2f1-11e6-8705-c46d3304dbd4.png">
<img width="640" alt="pointlist_zoomedout" src="https://cloud.githubusercontent.com/assets/810679/20630938/5352fe38-b2f1-11e6-8839-5393f8e9eca3.png">

**Comment by asmaloney** [comment]
Ok - it's going to be too time consuming to do blind fix/build/upload/remote test/repeat.  I'm going to have to leave the high DPI issues to someone who has one and can fix and test them.

@D-Alex - you fixed one of these in the past - can you figure out and fix [any more of them](https://github.com/cloudcompare/trunk/labels/Retina%20hell)?

**Comment by macsurveyr** [comment]
@asmaloney I can do some programming and some testing but I cannot seem to get things to compile correctly. Perhaps I have directory structure incorrect or something. Actually trying to compile on an older machine that has a lot of history. If you have advice on how to set up a clean machine I might give it a try on the new one.

Tom

**Comment by asmaloney** [comment]
@dgirardeau figured out a way to emulate a high DPI display using Qt and jumped head-first into the depths of CC to fix this and other high DPI issues.

Could you please download and test [CC beta7](https://asmaloney.com/software)?

Those of you following issues #398, #389, and #371 please try it as well.

**Comment by macsurveyr** [comment]
@dgirardeau @asmaloney 

The point picking and point list picking issues are much, much improved!

However, I think the point pick box info and the point list label are pretty small

I tried multiple scaled resolutions as well and the size of the box info and the point list label remained basically the same small size.

I am attaching four screen shots showing results from picking a point then zooming out a bit as well as picking two points in the point list function and then zooming out a bit. Point label placement is correct and stays correct when zooming, but again, pretty small - too small to read easily.

Thank you very much for your efforts!

Tom 
<img width="474" alt="point_list_pick_zoomout" src="https://cloud.githubusercontent.com/assets/810679/20871508/c692bb0e-ba53-11e6-8e60-9cd18c7595c8.png">
<img width="473" alt="point_pick_zoomout" src="https://cloud.githubusercontent.com/assets/810679/20871509/c6a6ec96-ba53-11e6-83d4-baab0425303e.png">
<img width="475" alt="point_list_pick" src="https://cloud.githubusercontent.com/assets/810679/20871510/c6abd86e-ba53-11e6-923e-3ddee49cef10.png">
<img width="474" alt="point_pick" src="https://cloud.githubusercontent.com/assets/810679/20871511/c6acc170-ba53-11e6-884f-006f6127e677.png">

**Comment by dgirardeau** [comment]
Yes I forgot the fonts! They are twice as small as they should be. Can you try increasing them in the 'Display options' dialog? You have to double their size: the 'Label font size' in the 'Labels' section, and the 'Default font size' in the 'Other options' section.

Can you tell me if it fixes the issue? If yes I'll fix that easily.

**Comment by macsurveyr** [comment]
@dgirardeau I believe you are right. Doubling the Label font size and the Default font size make both point picking and point list picking appear correct.

Tested using Mac OS X Beta v2.8b7 from @asmaloney

**Comment by mankoff** [comment]
CC beta7 point picking works for me. Font is small as discussed above, but location and dragging of the textbox all work for me on Retina display.

**Comment by asmaloney** [comment]
@dgirardeau made some changes for font sizes on high DPI displays earlier today.

I made a further macOS-specific adjustment to fonts because I've always found them too small on a regular monitor anyways.

Please check out [macOS beta8](https://asmaloney/software) and let me know what you think.

**Comment by mankoff** [comment]
My earlier comment said `beta7`, but I meant `beta8`. Point picking and textbox location bugs seem to be fixed.

**Comment by asmaloney** [comment]
I put up beta 8 right before I posted that comment 30 minutes ago. Is that the one you have?

If so, please post an image of what you're seeing.

**Comment by mankoff** [comment]
Must have been v7. v8 fonts are good.

**Comment by macsurveyr** [comment]
@dgirardeau @asmaloney 

Using the latest macOS beta8, I opened up the same point cloud on a MacBook Pro retina and an iMac non-retina. The only difference that is noticeable is the default Point size. The point size on the retina machine appears approximately the same as the non-retina machine when set to the point size of two instead of Default.

The point picking and point list picking work as expected and virtually identical on both computers. 

I consider this issue closed.

**Comment by dgirardeau** [comment]
Retina displays really have twice more pixels (in both directions). Mac OS  and/or Qt take most of the GUI elements in charge, but not OpenGL. So we have to virtually double the size of everything we display via OpenGL. This is generally not a problem for most entities. But as the available point sizes are already limited (from 1 to 10) I decided not to scale them because this would reduce the range even more (from 1 to 5). 

Moreover this can be very interesting to get very small points when you have a lot of them :D
