### ISSUE TITLE
CCviewer compiling problem

### ISSUE THREAD

**Issue by ivivyfei** [CloudCompare/CloudCompare#479]
## Current Behavior

When compiling the CCviewer only using Cmake, an error encounters like that:
CMake Error at CMakeLists.txt:42 (qt_wrap_ui):
  Unknown CMake command "qt_wrap_ui".

## Steps to Reproduce (for bugs)

![image](https://cloud.githubusercontent.com/assets/17590408/20919520/2ca1fe12-bbd7-11e6-96b1-b89fbdffda7e.png)

## Your Environment

* OS & Version: Win 10
* CC Version: 2.6.3
* Graphics card:

**Comment by dgirardeau** [comment]
Which version of Qt are you actually using?

**Comment by ivivyfei** [comment]
I am using qt 4.8.0. But the CCviewer can build  successfully when building the CloudCompare with the option checked.

**Comment by dgirardeau** [comment]
Oh, I didn't pay attention to your snapshot: you can't build ccViewer 'alone'. You have to launch CMake on the previous folder (/trunk-2.6.3.1). Then you'll have the right options, etc.

Moreover, to avoid issues, don't put the 'build' folder in the 'sources' folder.

Example:
source code: 'D:/XXX/trunk-2.6.3.1'
build path: 'D:/XXX/build'
