### ISSUE TITLE
build with LibLas support

### ISSUE THREAD

**Issue by shloog** [CloudCompare/CloudCompare#490]
## Current Behavior

I am building lateset cc with cmake 3.7 and liblas suported to visual studio 14 2015  Win64 。 I  installed liblas with osgeo4w 64  and boost_1_62_0。 But there are some errors when I run it in vs2015。Is the versions of softwares and libs  incompatible? I am going to be mad. Help me!

## Your Environment

* OS & Version:windows 10
* CC Version: latest
* Graphics card:

**Comment by shloog** [comment]
When I run the  camke builded project in vs2015, the errors are: 
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'liblas/point.hpp': No such file or directory	QCC_IO_LIB	E:\cloudcompare\cloudcompare_1228\trunk-master\libs\qCC_io\LASFilter.cpp	36

**Comment by dgirardeau** [comment]
What version of liblas are you using? Do you have a 'point.hpp' file in the 'liblas' folder? If yes, make sure the include path is right in CMake.

**Comment by shloog** [comment]
liblas-1.8.0-1
