### ISSUE TITLE
Always bad orientation of GEOTIFF with rasterize tool in QGIS

### ISSUE THREAD

**Issue by arnaudstephan** [CloudCompare/CloudCompare#491]
## Current Behavior

When exporting a raster goetiff with the rasterize tool and when importing this raster into QGIS, the raster is non well oriented.

## Steps to Reproduce (for bugs)

- Create M3C2 distance from the plugin
- Select the output result
- choose Rasterize tool
- Select M3C2 distance
- export raster
- import geotiff in QGIS

## Context/Comments

In QGIS, my project is in RGF93 - CC46
## Your Environment

* OS & Version: Windows 10 64 bits
* CC Version: 2.8 (18/12/2016)
* Graphics card: Nvidia Quadro K2200

**Comment by dgirardeau** [comment]
Ok, I finally found the bug! That was tricky...

I've uploaded a 2.9.alpha version accessible on the CloudCompare website:
http://www.cloudcompare.org/release/

**Comment by arnaudstephan** [comment]
Thank you!!
