### ISSUE TITLE
qAnimation plugin does not export frames.

### ISSUE THREAD

**Issue by ryancwicks** [CloudCompare/CloudCompare#493]
## Current Behavior
When using the standard workflow to save export frames (ie, selecting an output file with the dialog box and hitting Export Frames), the animation plugin will stop, reporting failure to save frame 0. 

## Expected Behavior
The plugin should export frames into the output file directory saved as frame_0, frame_1...

## Steps to Reproduce (for bugs)
Open the qAnimation plugin, select an ouput file using the ... button. Press Export Frames.

## Context/Comments
The plugin currently requires you to choose a file name for the output file when using the file dialog selection. The code for setting the output filename for the exported frames does not strip this filename from selected output file path. When the export frames code appends the new filename, the originally chosen filename appears as part of the path as a non-existent directory.

There is a work around where after selecting the output file using the dialog, you remove the file name from the path manually. This will allow you to export the frames properly.

As a fix, I would suggest changing line 577 of the qAnimationDlg.cpp from 

QString fullPath = QDir(outputFilename).filePath(filename);
    -to-
QString fullPath = QDir ( QFileInfo(outputFilename).absolutePath() ).filePath(filename);

The above code is untested as I don't have a build environment set up.

## Your Environment

* OS & Version: Windows 7
* CC Version: 2.8 stereo
* Graphics card: NVIDIA something or other.

**Comment by dgirardeau** [comment]
Oops ... I'm sure I tested this :(

Anyway, thanks for the report AND the bug fix! It's fixed.
