### ISSUE TITLE
Point pair registration strange result

### ISSUE THREAD

**Issue by zihahage** [CloudCompare/CloudCompare#498]
## Current Behavior

I know about the bug as described here https://github.com/CloudCompare/CloudCompare/issues/236.

But in CloudCompare 2.8, i think there is still a small bug.
Try

-1196.980 -714.234 -462.745
-1189.511 -1432.834 -466.560
1093.892 -1431.045 -469.854
1099.111 -711.013 -467.206

and

3039.947 117.745 -499.787
3040.068 837.800 -499.773
760.000 837.800 -499.787
759.928 117.900 -499.773
The two points with same index are equivalent.

It works well with any subset of 3 points but it gives strange result with the 4 points at once! Although the resultant alignment is correct, RMS displayed is very big, like 2395.55.

## Your Environment

* OS & Version: win7 Enterprise 64 bit SP1
* CC Version: 2.8
* Graphics card:

**Comment by dgirardeau** [comment]
I finally had some time to test this: even though the result 'seems' ok when using the 4 points, in fact one of the cloud is totally flipped (A0 is sent to R2, A1 is sent to R3, A2 to R0 and A3 to R1). This is why the RMS becomes huge.

This can indeed happen in some degenerate cases, with points aligned on a plane and with symmetries. This makes the registration maths fail...

We use Horn's algorithm, but I believe Arun's algorithm is more robust to this degenerate cases (see http://graphics.stanford.edu/~smr/ICP/comparison/eggert_comparison_mva97.pdf). Maybe we should switch to this method. However these cases really are degenerate and very particular.

**Comment by zihahage** [comment]
After i read Horn's paper, i commented the two lines,
    for (unsigned ip = 0; ip < n; ip++)
	d[ip] = fabs(d[ip]);
which lie in line 263-264 in jacobi.h.

It now works well, and the result is correct. Even the  #236.

**Comment by dgirardeau** [comment]
Well, the negative eigenvalues are here because the case is degenerate... Therefore keeping their original sign may fix the issue but it may be by pure luck?

On the other hand, as this case is degenerate it won't work even if we use the absolute values instead of the negative ones...

For now I have made this automatic 'absolute' conversion optional. And it's only disabled for the case of the registration.
