### ISSUE TITLE
Cannot start Windows build 

### ISSUE THREAD

**Issue by embeh** [CloudCompare/CloudCompare#499]
## Current Behavior

When extracting CloudCompare_v2.8.0_bin_x64.7z to a new folder and double-clicking CloudCompare.exe, I get this error message:

```
D:\download\CloudCompare_v2.8.0_bin_x64\CloudCompare.exe

The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
```

## Expected Behavior

Should start normally

## Steps to Reproduce (for bugs)

Just download, unzip and try to run the .exe

## Context/Comments

I also have an older installation in a similar folder that runs fine:
D:\download\CloudCompare_v2.6.2_bin_x64\CloudCompare.exe

## Your Environment

* OS & Version: Win 7 Enterprise, 64-bit (SP1)
* CC Version: 2.8.0
* Graphics card: GeForce GTX 780

**Comment by embeh** [comment]
In addition, sxstrace brings up this error:

`ERROR: Cannot resolve reference FARO.LS,processorArchitecture="amd64",publicKeyToken="1d23f5635ba800ab",type="win32",version="1.1.505.3".`

**Comment by dgirardeau** [comment]
It looks that the FARO 'LS' SDK failed to install properly... Can you retry to install the CC with the installer?

And if it fails again, then you'll have to manually delete the 'CloudCompare.exe.manifest' file next to CloudCompare.exe (and the FARO plugin won't work).

**Comment by dgirardeau** [comment]
It seems you haven't launched the installer. Did you use the archive version? I may have mistakenly left the manifest file in it (it shouldn't be present in the archive).

**Comment by embeh** [comment]
Correct, I used the archive version. Have not tried the installer.

**Comment by Jean-Roc** [comment]
Hi, would it be possible to get an updated archive ? I have the same problem but I cannot use the installer due to lack of admin rights.

**Comment by embeh** [comment]
@Jean-Roc - just delete the file CloudCompare.exe.manifest

**Comment by Jean-Roc** [comment]
Simple and super effective, thanks :)
