### ISSUE TITLE
Rasterize: Empty cell value

### ISSUE THREAD

**Issue by MartinPetitMarteau** [CloudCompare/CloudCompare#501]
## Current Behavior
When generating a raster, cells which do not contain a point from the point cloud are not assigned a NULL value, but a seemingly arbitrary float value.

## Expected Behavior
Cells not containing a point of the point cloud should be NULL value cells (empty cells)

## Steps to Reproduce (for bugs)
Load point cloud (in my case, negative coordinates occur as the point cloud is in a local coordinate system). The point cloud contains only XYZ, no further values:
![01_pointcloud](https://cloud.githubusercontent.com/assets/16595636/22341295/9a69a558-e3f0-11e6-9318-ac8a7ee5e5b0.PNG)
Rasterize (e.g. maximum z value; leave empty cells empty):
![02_rasterize](https://cloud.githubusercontent.com/assets/16595636/22341329/b57d015a-e3f0-11e6-9059-a605a34759a9.PNG)
Export raster to tif format.
Load resulting raster in GIS and extract value of an empty cell. In this case, the value is 3.124000072479248, but it varies without known system with the input point cloud. It can even be negative):
![03_rasterloadedingis](https://cloud.githubusercontent.com/assets/16595636/22341388/e6e6d31a-e3f0-11e6-99c3-a23d2c1109a4.PNG)

## Your Environment

* OS & Version: MS Windows 8.1 Pro
* CC Version: 2.8.beta

**Comment by dgirardeau** [comment]
The convention is to set the 'no data value' to the minimum grid height minus 1 (we use GDAL's SetNoDataValue function.

However it's not very clear how this 'no data' information is used by CGAL afterwards (http://www.gdal.org/frmt_gtiff.html).

**Comment by MartinPetitMarteau** [comment]
Thanks for your quick and clear answer!

So it may be recommendable to set an own no data value:
![userspecifiednodatavalue](https://cloud.githubusercontent.com/assets/16595636/22364994/6f09d3d0-e475-11e6-9d44-67d9dba34109.PNG)
