### ISSUE TITLE
Consider creating a new account for the snap store

### ISSUE THREAD

**Issue by mardy** [CloudCompare/CloudCompare#509]
Hi again :-)
  I realize only now that, despite you having uploaded a new package to the snap store, I still figure as being the "owner" of the app:

  https://uappexplorer.com/app/cloudcompare.mardy

This is obviously not right. I suggests that I delete the app and unregister the "cloudcompare" name, and that you publish it instead under your own account; another option might be to register a "neutral" account for the whole team, and then add all CloudCompare developers (and me, if you'd like me to be able to upload snaps) as collaborators.
Please let me know if you agree, I'll unregister the CC name as soon as you confirm it's fine.

**Comment by dgirardeau** [comment]
I like the second option, this way it will work just as the github account (which in an 'organization').

**Comment by rjanvier** [comment]
Agree too.

**Comment by mardy** [comment]
Perfect! Please let me know once you get the account ready.

**Comment by dgirardeau** [comment]
@rjanvier Can you do it?

**Comment by rjanvier** [comment]
Ok @mardy , the account is ready.

**Comment by mardy** [comment]
Mmm... it looks like I cannot unregister the name. Please try to register it yourself (with the account you just created) at https://myapps.developer.ubuntu.com/dev/click-apps/register-name
Please ask for the "cloudcompare" name, and in the "Registrant comment" field write that I agree to give up the name (and link to this issue in github as proof).
Sorry for the trouble!

**Comment by noise** [comment]
Name transfer is complete. Enjoy!

**Comment by mardy** [comment]
Please try publishing a package. :-)

**Comment by rjanvier** [comment]
Ok, thanks @noise, @mardy. It's done. Alberto, I will add you to the list of uploader. Should I use your sourceforge adress?

**Comment by mardy** [comment]
Yes please :-)
