### ISSUE TITLE
Build failed with Code::Blocks

### ISSUE THREAD

**Issue by Samaalir** [CloudCompare/CloudCompare#511]
Hello, I was trying to build CC, after using CMake as indicated, but I have an issue with it, I don't know exactly the source of this error, but here is the code::blocks log:

`||=== Build: all in CloudCompareProjects (compiler: GNU GCC Compiler) ===|
CMakeFiles\Makefile2|263|recipe for target 'libs/qCC_db/CMakeFiles/QCC_DB_LIB.dir/all' failed|
C:\Users\Samaali\Desktop\build\Makefile|128|recipe for target 'all' failed|
||=== Build failed: 2 error(s), 0 warning(s) (3 minute(s), 28 second(s)) ===|`

I would greatly appreciate it if you kindly help me

**Comment by dgirardeau** [comment]
I have personally no idea about the signification of this error (but I don't use gcc). Maybe another user will have a hint.

Otherwise, have you googled this CMake error? (the 'recipe for target ... failed' one)

**Comment by luca-penasa** [comment]
You should probably scroll up and find where the errors actually happened... The errors you reported are only the final report that is printed at the end of the build command and it gives an overview of what happened but not the actual errors.
Somebody might help if you link to the full error log, eg. on pastebin.com

Luca

**Comment by Samaalir** [comment]
Hello @dgirardeau and @luca-penasa , I've tried to compile the project with Qt Creator, and it runs successfully (without plugins),
in my opinion I think building and running the project with Qt is better than using Cmake ...
thank you for your answers

**Comment by luca-penasa** [comment]
glad you solved the problem. qt creator actually uses cmake to configure the build, thus it should work the same. Probably qt creator has some pre-configured setting (as the compiler) that made it to compile fine.
