### ISSUE TITLE
Unable to build with Visual Studio 10

### ISSUE THREAD

**Issue by fairchild88** [CloudCompare/CloudCompare#514]
When compile the source with VS2010 on win32,  there are many errors like 
ERROR:F:\UncoopertiveObject\software_pro\CloudCompare-master\libs\qCC_db\ccPointCloud.h(450): error C2216: “override”can not be  used with "inline”.
........

It seems that is a bug of VS2010.

**Comment by fairchild88** [comment]
Should I change to VS2012? or is there an older version?

**Comment by rjanvier** [comment]
Since 2.7. CloudCompare require a Compiler with "good" c++11 support, I think it should be at least Visual 2013. You can try to build 2.6.3 with an older version of Visual
