### ISSUE TITLE
Cloucompares 2.9 (and 2.8) : setup Ok but hangs

### ISSUE THREAD

**Issue by AlbanUR2** [CloudCompare/CloudCompare#516]
We setup CC 2.9 on 2 Windows 7 computers (1 server Precision WorkStation R5400 with NVIDIA Quadro FX3700 and 1 relatively new laptop HP EliteBook 840 G1 without dedicated graphic card). 

When starting-up Cloudcompare nothing appears : even the splash screen. One cloudcompare process runs however during some time before then dying).

## Context/Comments

Windows log (Application item) complains about Qt5 :
```
Nom de l’application défaillante CloudCompare.exe, version : 0.0.0.0, horodatage : 0x5855b2b7
Nom du module défaillant : Qt5Gui.dll, version : 5.7.0.0, horodatage : 0x575a6a26
Code d’exception : 0xc0000005
Décalage d’erreur : 0x000000000005dcb0
ID du processus défaillant : 0xa6c
Heure de début de l’application défaillante : 0x01d2928f58128750
Chemin d’accès de l’application défaillante : C:\Program Files\CloudCompare\CloudCompare.exe
Chemin d’accès du module défaillant: C:\Program Files\CloudCompare\Qt5Gui.dll
```
Using Cloudcompare Command line, I've got anoter error message about 'QRDB_IO_PLUGIN.dll'
```
C:\Program Files\CloudCompare>CloudCompare.exe -AUTO_SAVE ON -LOG_FILE C:\Users\
the_user\Desktop\cc_log.txt
```
Log :

> [15:01:24] [Plugin] File 'QRDB_IO_PLUGIN.dll' doesn't seem to be a valid plugin (Cannot load library C:\Program Files\CloudCompare\plugins\QRDB_IO_PLUGIN.dll: Le module spécifié est introuvable.)

After removing this plugin, we got a Window but can't go any further.

Should we understand CC > 2.8 is not compatible with our hardware ? We are using CC 2.6.1 that works well. In CC Release Notes :

> v2.6.3 (= pre 2.7.0 for systems that don't support Qt5) - 03/13/2016

Do you mean new CC versions can not be used on old computers and on laptops ?

Thanks for your answers

## Environment
* OS & Version: Windows 7
* CC Version: 2.9 & 2.8.1
* Graphics card: Nvidia Quadro FX3700 / motherboard integrated graphic card

**Comment by rjanvier** [comment]
Well it's the kind of issue that can occurs when you try to launch CC on a through desktop. Did you launch CC physically on thoses computer or through a remote destkop ?

**Comment by dgirardeau** [comment]
Indeed, Romain's right. Accessing CC through remote desktop generally implies that a low version of OpenGL is used and the new version of Qt doesn't like it.

Same thing for the laptop if it's too old. But in this case updating the display drivers might help.

**Comment by AlbanUR2** [comment]
Indeed I didn't mention it.

- The server is accessed through RDP (I can make a try of direct access)
- The laptop is accessed directly, and is about one year old

**Comment by rjanvier** [comment]
Yes please could try to run CC on your sever with direct access. It won't work with RDP.
is that an Intel HD Graphics 4400 on your laptop?

**Comment by AlbanUR2** [comment]
Concerning the server:

- I have accessed directly and started CloudCompare: I have observed the same behavior.

_NB: I have tried 3 times : with CC2.8 (installer), then CC2.8.1 (installer), and then CC2.8.1 (7zip version)_

- CC2.6.3 works (starts at least, and the gui is opened) on the server, and can be used through RDP. Do you confirm CC >= 2.8 can not be used through RDP anymore?


I am not the owner of the laptop but I am 90% sure it is an Intel HD Graphics 4400.

**Comment by rjanvier** [comment]
Sorry, i have no clue concerning the server, maybe you can try to update your graphic card driver. The NVIDIA Quadro FX3700 is a bit "old" but it should support OpenGL 2.1 and thus it should run fine with CC > 2.6.3.
I will let @dgirardeau confirm that RDP is no longer supported, but on my own experience it does not work.

**Comment by dgirardeau** [comment]
I don't really know what's happening here. I just know that Qt has decided to blacklist some graphic cards / drivers because they are too old. I don't know the official list, and it's a bit surprising that 'not that old' NVidia cards are also impacted...

**Comment by asmaloney** [comment]
Not sure if this helps this discussion, but I just ran across the default Qt OpenGL blacklist in another context. Here are the latest cards and their issues (mostly Intel):

https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/windows/openglblacklists/default.json?h=5.9

This is used to handle fallback to other renderers if there are problems. I haven't yet figured out how to access the info in this file to present something intelligent to the user.

**Comment by dgirardeau** [comment]
This helps a lot actually!

It would be cool to be able to detect this at startup (before CC tries to create a GUI and crashes ;).

**Comment by AlbanUR2** [comment]
Hi,

I'm finally back and I give another try to new version of Cloudcompare : 

- version: 2.9.1
- Dell Poweredge R715 without any additional graphic card

I have tested through RDP and in front of its screen and the same result is observed: a "cloudcompare" process starts and then dies without complaining...

`.\CloudCompare.exe -AUTO_SAVE ON -LOG_FILE C:\Users\Administrateur\log_cc.txt
`
did not mention any issue.

Windows logs mention an application error:

`
La description de l’ID d’événement 1000 dans la source Application Error est introuvable. Le composant qui a déclenché cet événement n’est pas installé sur l’ordinateur local ou l’installation est endommagée. Vous pouvez installer ou réparer le composant sur l’ordinateur local.

Si l’événement provient d’un autre ordinateur, les informations d’affichage doivent être enregistrées avec l’événement.

Les informations suivantes étaient incluses avec l’événement : 

CloudCompare.exe
0.0.0.0
59fc5344
Qt5Gui.dll
5.9.1.0
59532d7d
c0000005
0000000000062b40
12fc
01d35def8039367e
C:\Program Files\CloudCompare\CloudCompare.exe
C:\Program Files\CloudCompare\Qt5Gui.dll
be04b342-c9e2-11e7-b210-f04da23e7b18
`
I'm sorry but I can not dig further and check if this file (Qt5Gui.dll) is really missing. I needed to quickly rollback to previous version (2.6.3) and stop working on this server.

**Comment by dgirardeau** [comment]
You don't have any graphic card at all?! In this case you should start the command with -SILENT at the beginning (to avoid displaying any widget and therefore avoid using the Qt5 GUI module).

And if you do have a graphic card, then I guess it's still an issue with Qt?

**Comment by asmaloney** [comment]
I'm going to close this issue since it is really old. Please open a new issue and fill in the appropriate information if you're still having problems with the latest version of CloudCompare.
