### ISSUE TITLE
qCANUPO - linux.

### ISSUE THREAD

**Issue by bartoszek** [CloudCompare/CloudCompare#520]
What is the procedure of building qCANUPO plugin on linux system ?
I found the source for cli application ( git://nicolas.brodu.net/canupo ), but can't find the plugin source.

**Comment by dgirardeau** [comment]
Sadly the Canupo sources have not been released yet... It's only available on Windows.

**Comment by asmaloney** [comment]
Added in CloudCompare 2.10...
