### ISSUE TITLE
Rasterize's step limited to 0.001

### ISSUE THREAD

**Issue by Jean-Roc** [CloudCompare/CloudCompare#521]
I'm trying to generate a DEM on a PLY cloud using the Rasterize tool and height grid values, it seems that the tool set a limit on the grid size's step that can be used.

The lower value that can be given is 0.001 unit; if I set it to 0.0005 and click on _"Update Grid"_, the value is set back to the previous valid value.

I've tested this behavior with CC 2.8 and the latest 2.9 beta on Win7 x64, the clouds are in local coordinates (no shift applied) and have the point density required for this resolution.

![rasterize](https://cloud.githubusercontent.com/assets/736212/24194578/e0ec6674-0ef6-11e7-86d3-180040a228c4.png)

**Comment by dgirardeau** [comment]
Yes, it was mainly meant to prevent accuracy issues, or also too big grids (if the user doesn't pay attention to the current grid step value).

Actually I thought that even if the user works in mm, 0.001 would be a micron (therefore it should be sufficient). But I also know that whatever the limit I set a user will eventually try to set a lower value ;)

Is it possible for you to scale your cloud before rasterizing it (with 'Edit > Multiply / scale') or do you really need to work with such small coordinates?

**Comment by Jean-Roc** [comment]
The clouds we create use meter as base unit so 0.0005 means 0.5mm/500microns but now that I know the cause of this limitation, I'll scale the cloud accordingly and then do an extra-step by scaling it back with gdal.

To avoid confusion, maybe should you reduce the 7 digits displayed after the comma to only the 3 usable ?

My take would be to remove any hard limit, you'll already provide a preview of the grid size and display a warning when the pixel count is over 10M pixels so if the user want to jump over the bridge after 2 warnings, let him go :)

**Comment by dgirardeau** [comment]
Ok, I'll probably lower the limit a little bit but it will only be available in the next (beta) version.

And mind that the number of digit is not necessarily linked to the lower bound. One may need to set the step to something like 1.000025 (because of a particular frequency pattern in your input data).
