### ISSUE TITLE
RANSAC_orig in release doesn't work

### ISSUE THREAD

**Issue by imanolooo** [CloudCompare/CloudCompare#523]
First of all mention that I'm using your code in my research, customizing it.

## Current Behavior
When I call the Detect function in release mode, it can not get any solution. The program never exits the function. In debug it works properly.

## Expected Behavior
Detect planes from a point cloud.

## Your Environment

* OS & Version: OS X 10.11.4
* CC Version: Qt Creator 4.0.2 Based on Qt 5.7.0.
* Graphics card: NVIDIA GT750M

**Comment by imanolooo** [comment]
Debuging I've found that the function:

```
template< class Cell >
	inline bool BaseTree< Cell >::IsLeaf(const CellType &cell) const
	{
        return &(cell[0]) == NULL;
	}
```

returns true in debug and false in release. any idea?

**Comment by asmaloney** [comment]
Sounds like uninitialized data.

Some compilers will set pointers to NULL in debug builds but not in release. (This has to do with the fact that C sees declaration & initialization as two distinct steps.)

So maybe look at the stack when you hit that and trace back to find out what's uninitialized?

_Aside:_ I don't include the RANSAC plugin in the macOS build because when I last looked it wasn't supported and had a ton of issues compiling cleanly. Have you had to make any changes to get it building properly?

**Comment by imanolooo** [comment]
Hi, thanks for answering.

I also thought on that, but i haven't found any uninit variable...
Debugging in qt creator is like a nightmare sometimes... I arrived to the
problem commented. When it is creating the acceleration structure it
doesn't subdivide the root because the isLeaf function return false when it
should return true... In debug it worls properly... No sense on that...

Oh what a pitty that you don't include ransac on mac. So I am alone in the
dark. Ransac doesn't support mac directly and I used your code thinking it
work on mac. Not many adaptations I done to make it work, but it only does
in debug mode...

I can pass you the adapted code if you want.

Best,

El dia 11 abr. 2017 21:21, "Andy Maloney" <notifications@github.com> va
escriure:

Sounds like uninitialized data.

Some compilers will set pointers to NULL in debug builds but not in
release. (This has to do with the fact that C sees declaration &
initialization as two distinct steps.)

So maybe look at the stack when you hit that and trace back to find out
what's uninitialized?

*Aside:* I don't include the RANSAC plugin in the macOS build because when
I last looked it wasn't supported and had a ton of issues compiling
cleanly. Have you had to make any changes to get it building properly?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CloudCompare/CloudCompare/issues/523#issuecomment-293445371>,
or mute the thread

**Comment by imanolooo** [comment]
I forget to mention that if I print the values of the both sides of the
comparisson i get 0x0 == 0. In debug it returns true in release false...

El dia 11 abr. 2017 21:33, "Imanol Muñoz Pandiella" <
imanol.munoz.pandiella@gmail.com> va escriure:

**Comment by dgirardeau** [comment]
Note that we use the original code from Ruwen Schnabel (the author of RansacSD). We haven't modified it.

It's also interesting that on Windows (Visual Studio) at least, we don't have this issue while the compiler does init pointers to 0 in Debug mode and left them uninitialized in Release mode...

**Comment by imanolooo** [comment]
Yes it's quite weird, but luckily I've found a solution. I use the keyword volatile and it works. I guess the compiler was affecting it with optimizations or maybe some thread... how knows!

`template< class Cell >
	inline bool BaseTree< Cell >::IsLeaf(const CellType &cell) const
	{
        std::cout << "IsLeaf " << &(cell[0]) << " == " << NULL << " => " << (&(cell[0]) == NULL) << std::endl;
        std::cout << "IsLeaf " << &(cell[0]) << " == " << NULL << " => " << (&(cell[0]) == 0) << std::endl;
        std::cout << "IsLeaf " << &(cell[0]) << " == " << NULL << " => " << (&(cell[0]) == 0x0) << std::endl;
        std::cout << "IsLeaf " << (&(cell[0])) << " == " << NULL << " => " << (&(cell[0]) == (CellType *)0) << std::endl;
        volatile size_t st = (size_t)(&(cell[0]));
        std::cout << "IsLeaf " << st << " == " << NULL << " => " << (st == 0) << std::endl;
//        std::cout << "IsLeaf " << (int)(&(cell[0])) << " == " << NULL << " => " << ((int)(&(cell[0])) == 0) << std::endl;
		//return !(&(cell[0]));
        return st == 0;
        return (&(cell[0])) == 0x0;
        return &(cell[0]) == NULL;
	}`

**Comment by dgirardeau** [comment]
Would the following code work? (to avoid the cast)

`volatile CellType* st = (&(cell[0]));
 return st == nullptr;`

**Comment by asmaloney** [comment]
Looks like this was solved? Since RANSAC is not included with CC on macOS I'm not going to make any changes to the code.
