### ISSUE TITLE
LAS 1.3/1.4 exported files canot be read back

### ISSUE THREAD

**Issue by Azing** [CloudCompare/CloudCompare#528]
## Current Behavior
Export a cloud to LAS 1.3/1.4
Re-import it into CloudCompare
Error during import File is not accepted

Saving the loaded cloud:
[11:16:29] [I/O] File 'Cloud.las' saved successfully

Re-reading the saved file above
[11:16:37] Liblas exception: 'invalid point data format'
[11:16:39] An error occurred while loading 'Cloud.las': the third-party library in charge of saving/loading the file has thrown an exception

## Expected Behavior
I expect a saved file to be readable 

## Steps to Reproduce (for bugs)
Load XYZintensity ASCII CSV file in CC
Export as LAS 1.3/1.4
Close CC
Open CC
Load LAS file exported above
File not accepted.
## Your Environment
* Windows 10 64 Professional
* CC v2.9 beta
* NVidea GeForce GT740

**Comment by dgirardeau** [comment]
Have you loaded the file with the same file filter (LAS 1.3/1.4)?

**Comment by Azing** [comment]
No, it was a comma separated ASCII XYZintensity data set. If I follow the same steps with the 1.2 LAS version it works as expected. Import XYZ file, save as LAS. Import LAS file.

 

So there is a work-around. Thought I’d let you know.

**Comment by dgirardeau** [comment]
Oh, what I meant is: have you tried to open the LAS file created with the 'LAS 1.3/1.4' file filter with the same filter afterwards? (and not the default 'LAS' filter, or by drag and drop on the 3D view for instance).

**Comment by Azing** [comment]
I apologize. I misunderstood. When selecting the proper import filter (through file open) the file works as expected. It is the drag & drop that demonstrates the issue I reported. So it is just a trivial issue.

**Comment by dgirardeau** [comment]
Yep, as multiple 'filters' support the same extension, when you drag & drop a file CC will use the default one... However the fact that there are 2 filters should be temporary (hopefully).

**Comment by geoeki** [comment]
Problem still occurs when drag & drop exported LAS file from CC back into CC.

**Comment by dgirardeau** [comment]
Yes because when drag & drop is used, only the file extension is used to select the I/O filter. And with LAS files, the other filter (based on PDAL) is used.
