### ISSUE TITLE
[Mac OSX 10.10.5, CC v2.81] Camera Sensor location / rot doesn't apply entered values.

### ISSUE THREAD

**Issue by endeebee** [CloudCompare/CloudCompare#529]
## Current Behavior
I am  trying to visualize camera locations in a .ply model by manually adding camera extrinsics with
Edit->Sensors->Camera->Create
No matter what I enter as translation, the resulting camera box always ends up at the same coordinates in my .ply model. 
Also when I then look at the Position/Orientation->"Matrix" attribute of the camera, it shows
an identity matrix and a zero translation.
## Expected Behavior
I was expecting the camera to be positioned according to what I enter in the Sensors->Camera->Create dialog.

## Steps to Reproduce (for bugs)
1) Load the .ply file 
2) Edit->Sensors->Camera->Create. 
3) Enter values for translation differing from 0
4) The Position/Orientation->Matrix attribute in camera info doesn't reflect the changes made.
5) Editing the info in the matrix view in Position/Orientation->Matrix manually, then exporting the camera and importing it again does not change the outcome.

## Context/Comments
I'm trying to visualize the camera locations for all the photos in a multi view stereo set, specifically
the fountain-p11 model available at http://cvlabwww.epfl.ch/data/multiview/denseMVS.html.
The .ply file, as well as the camera matrices are all available on the website.
## Your Environment
Mac OsX 10.10.5
CloudCompare 2.81

**Comment by dgirardeau** [comment]
Yep, this bug has been fix (but in the latest 2.9 beta version, so it's not available on Mac OS for the moment). Right now you have to create the camera (don't set any parameters) and then use the 'Edit > Sensors > Edit' to set the right parameters (it's the 'Create' method that is broken).
