### ISSUE TITLE
Hollow issue to hold images for improvments suggestions

### ISSUE THREAD

**Issue by Remi-C** [CloudCompare/CloudCompare#533]
See CloudCOmpare forum 👍 
http://www.danielgm.net/cc/forum/posting.php?mode=post&f=16

![image](https://user-images.githubusercontent.com/4725794/27243703-6c9e187c-52e3-11e7-98dd-382e71c0ddc5.png)
![image](https://user-images.githubusercontent.com/4725794/27245698-5f1b2eb0-52ed-11e7-86a6-1eae647e0165.png)
![image](https://user-images.githubusercontent.com/4725794/27245892-3a699678-52ee-11e7-9ec0-4e85561ab314.png)

![image](https://user-images.githubusercontent.com/4725794/27246291-e94ffe78-52f0-11e7-8b13-ffe9e57141b0.png)

**Comment by asmaloney** [comment]
Thanks Remi. Your link didn't work,so here's the link to your post:

http://www.danielgm.net/cc/forum/viewtopic.php?f=14&t=2548

Also you should consider making issues here on GitHub for the bugs you mention. They are easier to track and less likely to get lost.

**Comment by dgirardeau** [comment]
Ok, that occurred when the lights were off. I changed the code so that the arrows always appear correctly.

Thanks for the feedback.
