### ISSUE TITLE
Still cannot open PCD files on Linux

### ISSUE THREAD

**Issue by eric-schleicher** [CloudCompare/CloudCompare#536]
## Current Behavior
Using snap install on ubuntu 16.04LTS still cannot open .pcd files.   fails and provides the much hated

![image](https://user-images.githubusercontent.com/8261783/27660047-8e5e31d8-5c0a-11e7-9733-6f21bcf357eb.png)

## Expected Behavior
per documentation and discussion thread this problem is believed to have been solved.    Expected to be able to open ASCII pcd file, but cannot.

## Steps to Reproduce (for bugs)

Install CloudCompare with snap (any channel)
open cloud compare; file->open -> select a .pcd file from the local file system
![image](https://user-images.githubusercontent.com/8261783/27660112-d02c838a-5c0a-11e7-8c1a-f7f687589478.png)

click open results in unexpected failure

## Context/Comments

From reading around it looks like this has been an issue previously, but looked like it had been fixed?  this system does have ROS installed which also has PCL.

Is there a way ensure that dependencies are resolved/validated?

## Your Environment

* OS & Version:
Ubuntu 16.04 LTS
* CC Version:
All; most recently 2.9 Beta
* Graphics card:
Nvidia 1060

**Comment by rjanvier** [comment]
Well it's simply because CC is not linked againt PCL in the snap package.

**Comment by eric-schleicher** [comment]
ok, that makes it sound like there is a *simple* way to set it up correctly.  how to do that?

**Comment by danielluehr** [comment]
Hi, 

Any update on this issue? I have just CC "upgraded" from an older version (deb packaged) to the snap version and I found out it has less features (at least, the PCL support is missing).

Is there any way to re-enable PCL support (without having to clone the repo and manually compile)?

Thanks

**Comment by rjanvier** [comment]
Hi,
Not for now unfortunatly. Maybe for the next release, but the PCL plugin is not maintained anymore by the original author.
Regards

**Comment by danielluehr** [comment]
Crystal clear. Thanks. Just one more question, is the plugin functional? I mean, should it work if compiling from the repo with the required dependencies? or is there something seriously broken?

**Comment by melodybinbin** [comment]
Look forward to open .pcd file in ubuntu14.04. Thanks in advance!

**Comment by va9abund** [comment]
Hello,
Could you recommend any other application to work with .pcd files (I just need to display the content as an image)? 'cause as I guess I'll spend more time just configuring PCL for CCviewer.

**Comment by asmaloney** [comment]
I don't know of other software offhand, but I don't work with too many different formats.

Based on the [PCL download page](http://pointclouds.org/downloads/) and the [news](http://https.www.pointclouds.org/news/)/[blog](http://https.www.pointclouds.org/blog/) pages it seems to be a dead project. (The last macOS binary release was 2012.10.04 for example.)

My suggestions would be to (1) not use the .pcd file format for any new work and (2) find a converter to convert existing files to another format. I seem to recall PCL included some converters?

**Comment by va9abund** [comment]
@asmaloney , it looks like Blender has some extension with allows to convert .pcd, however heven't checked it yet. Your suggestion nr.1 doesn't really possible to apply for me, because there is no more tools plug-and-play to record data from Velodyne except pcl_ros.

I will check other possibilities to convert pcd's and let you know if anything will work out.

**Comment by melodybinbin** [comment]
Thank you for your reply! @va9abund  @asmaloney 
I'm studying 3D reconstruction of indoor scenes. To evaluate the result of 3D reconstruction, I use the CloudCompare to compute distances between the reconstruction point cloud with the ground truth by the ICL-NIUM dataset.
The input files to CloudCompare are .pcd file and .ply file or .pcd file and .obj file or .pcd file and .pcd file.
I have not converted .pcd file to another file format. Maybe this conversion will bring error to the evaluation.

**Comment by va9abund** [comment]
@asmaloney, Well, I still haven't tried conversion because I gave up on trying to open .pcd on Linux and for Windows it works just fine. I suggest try this "method" to anyone has the same issue.
Best regards,

**Comment by asmaloney** [comment]
Ok - glad you found a solution.

I think @dgirardeau mentioned on another issue here that this plugin hasn't been maintained by its original author, so it is possible that it will stop working or even be removed at some point. If you know any developers who are interested in working on it, please point them here!

**Comment by eric-schleicher** [comment]
@asmaloney PCL is not frequently updated because it provides a defacto set of standard interfaces that are completely stable.  New/frequent releases aren't required, but don't confuse that for the project being dead or interpret that PCD generally should be deprecated.

We should endeavor to keep it real regarding formats.  PCD is a clearly established and implemented representation for point data.   It's not a meaningful guidance to avoid using PCD or to pre-convert it into a point cloud workbench application.  

The issue here is the is whackadoodle snap distribution of cloudcompare, that for reasons tied to choices the snap packager made, doesn't support some industry standard format(s) via PCL.  The unfortunate parts is that this crippled version has become the defacto install for linux users.

If i had the aptitude i would build a properly linked version and try to get it setup for official linux releases, but alas it's outside my wheelhouse.

**Comment by eudoxos** [comment]
Is there at least one format which can be written with PCL and loaded with the (crippled) CC snap? That way I would avoid recompilations, as a short-term solution.

**Comment by asmaloney** [comment]
@eudoxos What do you mean by "crippled"? Do you mean "working for lots of people but not for my specific needs?"

**Comment by eudoxos** [comment]
Sorry for a too strong word, I thought it is obvious in the context of *this* issue what it means: the PCD plugin is not included in the snap. Not to deviate: I am really asking for suggestion of intermediary format as temporary workaround.

**Comment by rjanvier** [comment]
Ply maybe.

**Comment by rjanvier** [comment]
PCD handling is now part of the snap package. It's only available on the edge channel for now maybe it will be available in the next release.

**Comment by hiyyg** [comment]
I got this error:
```
[PCL] An error occurred while converting PCD cloud to CloudCompare cloud!
```

**Comment by hug-dev** [comment]
I still had this issue with the cloud compare version in the Ubuntu Software manager (2.11.1). Installing the latest CloudCompare via Flathub ([here](https://flathub.org/apps/org.cloudcompare.CloudCompare)) worked!
