### ISSUE TITLE
Building the solution - problems on windows vs2015

### ISSUE THREAD

**Issue by jo-chemla** [CloudCompare/CloudCompare#537]
## Current Behavior  

1. I am trying to build the CloudCompare project on Windows, so followed instructions of _BUILD.md_ file. I've used CMake-gui to set **QT 5 Root path** to `C:/Qt/5.9/msvc2015_64`, and checked the QAnimation plugin to build it too - I didn't change any other settings, apart from **CMake install prefix** set to `C:/Dev/CloudCompare_Dev/trunk_install`. 

2. I configured and generated the project, and managed to open the visual studio solution with VS 2015 (vs14), and build the INSTALL project - in Release or Debug, x64 - with no compilation errors. 

3. This produces the executables in install folder, in debug or release subfolders.  When I run the `CloudCompare.exe`, the splash screen with CloudCompare logo displays, but the app does not start. When running in Debug mode in visual studio - I set the CloudCompare as startup Project, changed the **debugging command** property to `C:\Dev\CloudCompare_Dev\trunk_install\CloudCompare_debug\CloudCompare.exe` as in http://www.danielgm.net/cc/forum/viewtopic.php?t=992 - I get an Unhandled exception : 

`Unhandled exception at 0x00007FFA2F8E3628 (ntdll.dll) in CloudCompare.exe: 0xC0000005: Access violation reading location 0x00000000D5D7AA70.`

Have you already seen this error ? Can I give you more intel to help me get going ? Not sure also if this should not be posted on the forums instead. All the best, Jonathan

![image](https://user-images.githubusercontent.com/16822841/27919453-01991e16-6272-11e7-8bf4-dc224c18fb1b.png)

## Your Environment

* OS & Version: Windows 10 
* CC Version: trunk 2.8
VS 2015 & Qt 5.9

**Comment by dgirardeau** [comment]
This error is quite typical from old graphic cards (mostly Intel and ATI cards).

It may be fixed by updating the graphic card driver... sometimes...

**Comment by jo-chemla** [comment]
I forgot to include this reference, I indeed have an old GTX 780ti (Nvidia, not amd or intel), but the driver version is 382.53, quite recent; although the version 384.76 is available. Will try with that new driver version on the 780ti and a GTX 980 and/or Titan X and report.

**Comment by jo-chemla** [comment]
- Same happen with the updated drivers on the 780ti, in release or debug modes. 
 - And trying to run directly the built executables on a PC with a 980, cloudcompare crashes during splash screen. I've therefore set up the dev env on this new machine, qt cmake and cloned with git, and built the visual studio solution (INSTALL project) (by the way, with the new version of cmake, an error showed up at line 76 of CMakeLists.txt :  _A duplicate ELSE command was found inside an IF block_ )
   - in Debug-x64, launching the exe itself shows a splash screen and quits before starting (exe in trunk_install/CloudCompare_debug/CloudCompare.exe). Same happens for release mode. 
   - when building and setting CloudCompare project as startup project with correct link to debug executable, a new error appears, `Exception levée à 0x00007FF97896E7CE (Qt5Guid.dll) dans CloudCompare.exe : 0xC0000005 : Violation d'accès lors de la lecture de l'emplacement 0x0000000033CE59C8.` However, all was set up as previously, Qt5 root path to E:/ROMAIN/CloudCompare_Dev/Qt/5.9/msvc2015_64, install directory, ... See the stack below: 
![image](https://user-images.githubusercontent.com/16822841/27953688-00b4ace0-630d-11e7-87f4-1295f1677353.png)
Thanks again for your help!

**Comment by dgirardeau** [comment]
Hum, that's weird... I tried myself with Qt 5.9 and it worked fine. However I compile with Visual 2013.

Are you compile the project in stereo mode maybe? (with quad buffer support)

**Comment by dgirardeau** [comment]
By the way I fixed the CMake syntax issue (nice catch ;) )

**Comment by jo-chemla** [comment]
Actually, I used Qt 5.9.1, latest available, and the only option I changed compared to defaults is install_qanimation_plugin, so no quad buffer support. Seems related to https://github.com/CloudCompare/CloudCompare/issues/543 as the error stack was the same no ? Will try to compile with an older Qt version and report back ! :)

**Comment by jo-chemla** [comment]
It compiles nicely with Qt 5.8, msvc15_64 under visual studio 2015. Will start from there and tweak the QAnimation plugin a bit!

**Comment by dgirardeau** [comment]
Thanks for the reports!
