### ISSUE TITLE
Rotation around third axis is missing

### ISSUE THREAD

**Issue by klainkaliber** [CloudCompare/CloudCompare#54]
Hi,
I am sadly missing the possibility to rotate the 3D view around the third axis. Moving the mouse left-right rotates around vertical axis, up-down around the axis lying horizontal, but rotating around the axis pointing "into" or "out of" the screen is not possible yet. This would ease the exact positioning of the field of view a lot.
Could be done wiht holding CTRL or ALT while moving mouse left-right.

TIA
Roland

**Comment by NeroBurner** [comment]
@klainkaliber better late then never ^^
