### ISSUE TITLE
updateOverlayDialogsPlacement() not called when dbTree/console are resized

### ISSUE THREAD

**Issue by samthiele** [CloudCompare/CloudCompare#540]
Resizing the dbTree or console windows doesn't result in a call to updateOverlayDialogsPlacement( ... ), causing incorrect placement of some ccOverlayDialogs.

e.g. A ccOverlayDialog registered to sit at Qt::Corner::TopLeftCorner will end up overlapping the dbTree window if the dbTree window made larger.

Hopefully an easy fix?

**Comment by dgirardeau** [comment]
Ineed, that was quite easy ;). That's fixed.

Thanks for the feedback.
