### ISSUE TITLE
qCompass plugin - questionable unused code

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#542]
In **ccMouseCircle.cpp**, lines 102-103 don't do anything. It looks like the results should be assigned to something?:

```c++
static_cast<float>(dC.x + P.x);
static_cast<float>(dC.y + P.y);
```
@samthiele what's supposed to be happening here?

**Comment by samthiele** [comment]
Hum - you're correct that those two lines won't do anything... it's presumably a relic left over from debugging at some point.

I'm working currently on a big update for ccCompass, so I'll clean it up as part of that.

**Comment by asmaloney** [comment]
Removed this and other unused variables/assignments in f5bfaaba3a8a5af670a47f40ffd835134950468c.
