### ISSUE TITLE
Build w/Qt 5.9.0 & 5.9.1 crashes on startup

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#543]
## Current Behavior
I'm adding this as an issue because I saw a couple of other issues on Linux that may be related (fonts) and I wanted to keep track of this one for macOS.

## Steps to Reproduce (for bugs)

1. Build w/ official Qt 5.9.1
2. Run CC

*BOOM*

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.qt-project.QtGui          	0x000000010e1febfc QRasterPaintEngine::alphaPenBlt(void const*, int, int, int, int, int, int, bool) + 156
1   org.qt-project.QtGui          	0x000000010e1ffc16 QRasterPaintEngine::drawCachedGlyphs(int, unsigned int const*, QFixedPoint const*, QFontEngine*) + 1462
2   org.qt-project.QtGui          	0x000000010e200636 QRasterPaintEngine::drawTextItem(QPointF const&, QTextItem const&) + 534
3   org.qt-project.QtGui          	0x000000010e21ac79 QPainterPrivate::drawTextItem(QPointF const&, QTextItem const&, QTextEngine*) + 2793
4   org.qt-project.QtGui          	0x000000010e217f3c QPainter::drawText(QPointF const&, QString const&, int, int) + 1756
5                                 	0x00000001081d2fd5 QPainter::drawText(int, int, QString const&) + 69 (qpainter.h:893)
6                                 	0x00000001084bd419 ccGLWindow::renderText(int, int, QString const&, QFont const&) + 761 (ccGLWindow.cpp:6543)
7                                 	0x00000001084c241e ccGLWindow::drawForeground(ccGLDrawContext&, ccGLWindow::RenderingParams&) + 2702 (ccGLWindow.cpp:2470)
8                                 	0x00000001084c01d1 ccGLWindow::fullRenderingPass(ccGLDrawContext&, ccGLWindow::RenderingParams&) + 6321 (ccGLWindow.cpp:2102)
9                                 	0x00000001084be0c7 ccGLWindow::paintGL() + 1415 (ccGLWindow.cpp:1521)
...
```
## Context/Comments
This looks like it might be a Qt regression. When built with Qt 5.6.2 it works fine.

## Your Environment

* OS & Version: macOS 10.12.5
* CC Version: 2.9 (git)
* Graphics card: NVIDIA GeForce GTX 780M 4096 MB

**Comment by asmaloney** [comment]
Submitted Qt bug report: [QTBUG-61863](https://bugreports.qt.io/browse/QTBUG-61863)

**Comment by jo-chemla** [comment]
Might be related to https://github.com/CloudCompare/CloudCompare/issues/537 although it was built with Qt 5.9.0
Here is the stack of the exception : 
![image](https://user-images.githubusercontent.com/16822841/28008530-36d45dc8-6558-11e7-9a8e-f86543732d57.png)

**Comment by asmaloney** [comment]
Thanks @jo-chemla - that looks like the same thing.

**Comment by dgirardeau** [comment]
Hi @jo-chemla, Andy just found a nasty bug in Qt 5.9.X and he also found a (dirty) fix that seems to work on Windows and Mac OS at least. Can you try it on your side? (simply update the trunk).

**Comment by asmaloney** [comment]
This will be fixed in Qt 5.9.2: https://codereview.qt-project.org/#/c/199820/

In the meantime I've added a workaround that seems to work for macOS and Windows. Needs to be tested on Linux though.

**Comment by jo-chemla** [comment]
Thanks a lot! Will try in the coming days, I need to finish some things first. 
All the best, 
Jonathan

**Comment by mevatron** [comment]
@asmaloney Just wanted to confirm that your workaround does work on Linux (I'm using Ubuntu 16.04 here). I too was seeing the above Qt bug.

**Comment by asmaloney** [comment]
Great - thanks for the info @mevatron!

**Comment by dgirardeau** [comment]
Can I close the issue then?

**Comment by asmaloney** [comment]
I was going to leave it until we confirm that 5.9.2 fixes it going forward, but I'll close it and if it's still a problem later on, reopen.
