### ISSUE TITLE
{macOS} Cannot cancel Level operation

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#547]
## Current Behavior
Cannot cancel Level operation

## Expected Behavior

I should be able to cancel it. Preferably with the esc key.

## Steps to Reproduce (for bugs)

- select a point cloud
- choose "Level" from the Tools menu

The text says to "click on icon/menu entry again to cancel", but this is not possible because the menu item is no longer active, and there is no button in the toolbar.

The esc key doesn't do anything either.

## Your Environment

* OS & Version: macOS 10.12.5
* CC Version: 2.9 beta

**Comment by dgirardeau** [comment]
You don't have the 'level' button in the 'view' toolbar on the left?

**Comment by asmaloney** [comment]
Ah yes - I was looking along the top not the side. Oops.

Is your menu item still active when you do this? If not we should maybe change the wording a bit.

I would still recommend adding ESC as an option - it's a standard shortcut for "cancel the current action".

**Comment by dgirardeau** [comment]
Nope, the menu is voluntarily grayed out to avoid strange interactions with the current picking process (well, this was before the 'ccPickingHub' was introduced).

ESC would be good of course, but I'm not sure how to do this properly ...
