### ISSUE TITLE
CloudCompare Command Line C2C_DIST core dumped when -SILENT is enabled

### ISSUE THREAD

**Issue by pbach3** [CloudCompare/CloudCompare#548]
## Current Behavior

When CloudCompare command line for Cloud-to-Cloud distance is ran with silent mode enabled the command fails with:
 "CloudCompare: /*/CloudCompare/gCC/ccConsole.cpp53: static ccConsole* ccConsole::TheInstance(): Assertion 'false' failed.
Aborted (core dumped)"

## Expected Behavior

The same command runs successfully when silent mode is disabled. The expected behavior is to have an output log with the mean and std value in text format.

## Steps to Reproduce (for bugs)

Terminal:
CloudCompare -SILENT -LOG_FILE *.txt -O *.pcd -O *.pcd -C2C_DIST

![2017-07-17_135407](https://user-images.githubusercontent.com/25772656/28282226-bb565872-6af7-11e7-8868-a2aa0d2df976.jpg)

## Your Environment

* OS & Version: Ubuntu 16.04 LTS
* CC Version: 2.9
* Graphics card: NVIDIA GeForce GTX 650

**Comment by dgirardeau** [comment]
Okay that's fixed. Thanks for the feedback.

However mind that this assert is only triggered in debug mode. I don't know if you run CC in debug mode on purpose (it's verrrrryyyyyyyy slow).
