### ISSUE TITLE
Cannot open las file on macOS 10.12.4

### ISSUE THREAD

**Issue by conorhub** [CloudCompare/CloudCompare#550]
First of all, forgive any naivity in my descriptions - I've new to CloudCompare but seem to have hit a brick wall immediately. I have a single las file of interest to me (and zero lidar experience outside of this) that I'm trying to open in CloudCompare.

## Current Behavior

I cannot open a .las file in CloudViewer.  When I tried doing so through the 'open' menu option, the ability to select the las file was initially greyed out. Through some luck, I found out it's possible to bring up a filetype combobox through selecting 'options'. This isn't typical macOS dialog box procedure so I nearly missed it. Once done, I get the following errors:

`Liblas exception: 'Unhandled PointFormatName id 4'`

Followed by:

`An error occurred while loading 'filename': the third-party library in charge of saving/loading the file has thrown an exception.`

Doing some research, I found a similar issue suggesting that this is an issue with assumption of file version in the drag and drop window, and to use a different 'las' option in the file filter dialog box. I only see a single 'las' option in my version (2.8.1) on macOS and nothing about las file versions.

## Expected Behavior

I expected the file to not throw an error. Like I mentioned earlier, I've zero experience with las files or lidar prior to this, so cannot comment on the error with other files. But I got the file from a reputable source that I would be surprised if it had something unorthodox or corrupted in it.

## Steps to Reproduce (for bugs)

Literally try to open a file after opening the application. I get the same error if I drag and drop the file onto the window, and if I try and do the same in ccViewer.

## Your Environment

* OS & Version: macOS 10.12.4
* CC Version: 2.8.1
* Graphics card: nVidia GT 750m

**Comment by dgirardeau** [comment]
Indeed, the library that was originally used to load LAS file doesn't handle LAS 1.3+ and 1.4 files.

We have added another library for loading these files but it only works on the Windows for now!

**Comment by conorhub** [comment]
Thanks for the prompt response @dgirardeau . Should I stick around optimistically in the near future or is this likely going to remain a Windows-only library for now? It looks like macOS is a bit deprived in the lidar department, despite all the cli tools that usually provide more scope for such projects over Windows.

**Comment by dgirardeau** [comment]
We are actually testing a third option that should work on MacOS. However this is not for the 2.9 version at least (the one that will be released soon). Maybe for the 3.0 but I can't promise anything ;)

**Comment by asmaloney** [comment]
In general, the main issue on the macOS side is the lack of support in the underlying libraries. For example the E57 library is very old (2012) and never supported macOS in any form. I (we?) are not aware of any suitable replacements for it.

In terms of LAS - I will look again at the current solutions before we release 2.9 to see if there are any updates/changes that will help.

**Comment by dgirardeau** [comment]
@asmaloney I tested very recently PDAL (see this fork: https://github.com/tmontaigu/CloudCompare/tree/pdal). I managed to make it work on Windows and it seems to work also on Linux (the original target of the fork owner). I guess it should also work on MacOS?

**Comment by asmaloney** [comment]
OK - I will look at PDAL. There is a homebrew for version 1.5...

**Comment by conorhub** [comment]
Thank you both for that synopsis and the work you guys have put in. I'm following the repository now and look forward to the forthcoming releases.

**Comment by kainoa21** [comment]
Checking in to see if there are any update here.  I also ran into this issue while trying to load LAS 1.4 data on macOS (10.12).  I have used brew to install libLAS which seems to be able to handle LAS 1.4, not sure if that helps at all.  Thanks for all the effort in making this kind of tooling available!

**Comment by asmaloney** [comment]
There has been a bunch of work put into switching the LAS handling to PDAL which should make its way into the next release. As to when that will be - we haven't even begun discussing the next release yet...

**Comment by jgrn307** [comment]
I'm having this issue right now on the Mac version of CC -- is this ever going to be fixed?
