### ISSUE TITLE
Suggestion: Turn normals off by default when loading clouds

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#552]
## Current Behavior
Loading a small cloud (~1.2M points) results in a 3D display that is not very usable because normals are on. Zooming and moving around the point cloud is problematic.

## Expected Behavior
When loading a cloud I would expect to be able to interact with it immediately.

## Suggestion
Possible solutions:

- leave normals off by default when loading clouds and let the user turn them on if they need them
- provide a preference to set a threshold - loading any point clouds with > N points turns off normals (if there are any)

## Your Environment

* OS & Version: macOS 10.12.6
* CC Version: 2.9 beta
* Graphics card: NVIDIA GeForce GTX 780M 4096 MB

**Comment by Wiezzenger** [comment]
I second this idea. I am using CC to view and analyze >15 point clouds of ~ 6.5 million points each, having the ability to not load normals initially would save me from going through each one manually to turn them off.

**Comment by dgirardeau** [comment]
Ok, I guess most people don't need normals anyway... we can have a warning message in the console about the fact that the clouds have normals but they are not displayed by default.

**Comment by dgirardeau** [comment]
That's finally done! The user can now control this in the 'Display' options dialog.

**Comment by msy22** [comment]
I can't find this option, it's not mentioned in the [display options documentation](http://www.cloudcompare.org/doc/wiki/index.php?title=Display%5CDisplay_settings) and I haven't been able to find it by digging through other options menus.

I'm using CC Omnia, version 2.9.1 on Linux Ubuntu 14.01. Has the disable normals by default option been implemented in this version of CC?
