### ISSUE TITLE
Compass button shoudn't be active

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#554]
## Current Behavior
When I start up CC, the compass plugin's button is active.

In fact there are several buttons active that probably shouldn't be...

## Expected Behavior
It probably shouldn't be active unless there's a point cloud selected to work on.

## Your Environment
* OS & Version: macOS
* CC Version: 2.9 beta

**Comment by dgirardeau** [comment]
Should be fixed by 988fb9cd649b5f93520a7014c5f96277fa6ed901
