### ISSUE TITLE
Linux installation: Cannot find cmake-qt-gui

### ISSUE THREAD

**Issue by msy22** [CloudCompare/CloudCompare#563]
I'm trying to install CloudCompare and get it running, I've installed the latest versions of CMake and Qt, but when I run `cmake-qt-gui` I just get this:

```
user@computer:~$ cmake-qt-gui
cmake-qt-gui: command not found

```

I'm not sure if I'm running this command in the right place, or if I need to have something else installed (I have run `sudo apt-get install cmake-qt-gui` but this didn't work). I've wasted several hours searching the internet/forums/help pages for a solution and nothing has worked.

Does anyone know how to fix this issue?

**Comment by asmaloney** [comment]
If you are just trying to install it, you probably don't need to play with CMake - that's just for compiling it.

It looks like you're using Linux. I think it will depend on which distribution you're using (I'm not the Linux guy). The instructions [here](http://www.danielgm.net/cc/release/) say:

> On Ubuntu, starting from version 16.04 it's as simple as typing "snap install cloudcompare".
On other distributions, you may need to install snap first (please refer to the corresponding documentation if necessary).

**Comment by msy22** [comment]
Thanks for your help asmaloney! Sorry, I should have been clearer - I am using Linux, specifically Ubuntu 14.04. And unfortunately I've already tried that command, and it doesn't work (this is after installing snap):
```
user@computer:~$ snap install cloudcompare
ZOE ERROR (from /usr/lib/snap/snap): error opening parameter file
ZOE library version 2006-07-28
```
Nothing I could find on the internet fixed this error either.

**Comment by asmaloney** [comment]
According to [this](http://ubuntu-bugs.narkive.com/8yFEzyDh/bug-1614587-new-unable-to-run-snap-on-ubuntu-14-04-zoe-error) and [this](https://askubuntu.com/questions/793607/snappy-with-ros), on Ubuntu 14.04 you need to install `snapd` (not `snap` - or maybe in addition to? unclear):

`sudo apt-get install snapd`

**Comment by msy22** [comment]
Unfortunately installing `snapd` doesn't seem to change anything. 

What's odd is that running `sudo apt-get install cmake-qt-gui` tells me that I've already got the latest version of cmake-qt-gui installed. Is there another way to invoke/launch the GUI? Or is there a specific folder I should be in when running this command?

**Comment by asmaloney** [comment]
I don't use Linux at the moment, so I'm afraid I don't have much else to offer other than maybe the name of the command is wrong? Have you tried `cmake-gui`?

**Comment by rjanvier** [comment]
@andy is right, on linux you should use `cmake-gui` command. For snap package on 14.04, I'm not sure you can use CC but maybe you should run `sudo apt-get update && sudo apt-get upgrade` before and also restart your computer after that and eventually run `sudo snap install cloudcompare`. Could you do this and then report back? Thanks.

**Comment by msy22** [comment]
Okay, so both options seem to work. 

When building from source, `cmake-gui` does bring up the GUI, not `cmake-qt-gui`. I haven't progressed beyond this, but the GUI seems to have all the correct options for proceeding with the build. This doesn't match the [BUILD.md ](https://github.com/CloudCompare/CloudCompare/blob/master/BUILD.md) file which explicitly states that the `cmake-qt-gui` command is required for Linux, so should this be updated?

Installing the binaries using `snap install cloudcompare` also works (see below), although the installation instructions on the [CloudCompare downloads page](http://www.danielgm.net/cc/) explicitly say that this works on Ubuntu "_starting from version 16.04_"... So since it also seems to work on version 14.04 should these instructions also be updated? 

Otherwise, the binaries run well for CloudCompare and ccViewer, and I haven't had any trouble with either of them so thank you both very much for your help!

![20170801_ccviewer_test](https://user-images.githubusercontent.com/17462459/28798784-a98fa73a-7699-11e7-92bc-5a2c4f4d13e0.png)

**Comment by dgirardeau** [comment]
Is it Geoslam data? By any chance, do you have any connection to Geoslam?

**Comment by rjanvier** [comment]
@msy22, thanks for your feedback. We will make the ad hoc changes. For snap support in U14.04: it was not ready when we did the snap package and when it was released, I preferred to not advertise it since I didn't now if it was a full support and didn't have the time to test it.
Note that the snap package is not compiled with pcl support (on purpose) so it's normal pcd format is not supported.

**Comment by msy22** [comment]
@dgirardeau No I don't sorry. I've never heard of Geoslam before. That point cloud is of the Deutsche Museum in Germany, which I got by running through the [Google Cartographer 3D demo](https://google-cartographer-ros.readthedocs.io/en/latest/index.html).

@rjanvier Not a problem. Regarding snap support for pcd formats, does that only apply to CloudCompare on Linux? And is there a work-around?

**Comment by msy22** [comment]
Regardless, we have a solution to this issue, so I'll close it for now.
