### ISSUE TITLE
Compute normals using command line

### ISSUE THREAD

**Issue by bill-lin** [CloudCompare/CloudCompare#568]
Could you please add command line support for Normals Calculation?

Many thanks!

**Comment by silcowitz** [comment]
And also a -CLEAR_NORMALS would be handy

**Comment by dgirardeau** [comment]
Okay both options are now available (see http://www.cloudcompare.org/doc/wiki/index.php?title=Command_line_mode):
* '-OCTREE_NORMALS {radius}'
* '-CLEAR_NORMALS'
