### ISSUE TITLE
Normals calculated from fls files may be inverted

### ISSUE THREAD

**Issue by jedfrechette** [CloudCompare/CloudCompare#571]
When scan grids are used to compute normals for some Faro .fls files patches with inverted normals can be created. An example of one such file can be downloaded here:

[http://download.laserscanning-europe.com/samples/FARO_Scan_000.fls.rar]

The raw scan linked above is a .fls directory copied off of the scanner.  When imported in to CloudCompare the normals estimated for the ground surface around the scanner are inverted, while the normals on the nearby trees and vehicle are correct.

After importing the scan in to Faro Scene and reexporting it to a .fls file the calculated normals are still incorrect.

If exported as a .ptx file from Scene the normals calculated in CloudCompare are correct.

If the scan is transformed in Scene so that the scan origin position is (0, 0, +22) the normals calculated in CloudCompare are correct. I've seen other scans with inverted normals that had positive scan positions though so this may just be a coincidence.

For the above testing all normals were calculated using a planar surface model, with a scan grid kernel of 3 to calculate normals and using the scan grid to calculate their orientation.

**Comment by dgirardeau** [comment]
Yep I reproduced the error. I'm currently changing the computation algorithm for something faster and more robust anyway ;).

**Comment by dgirardeau** [comment]
Hum, strange, with the new code I have the same issue. I wonder what's the trick here!

**Comment by dgirardeau** [comment]
Okay, the bug is fixed (it was in the FARO I/O plugin, the global transformation was applied twice on the scan grid...).

I will still modify the normal computation algorithm (with something more robust and faster, based on the scan grid triangulation algorithm).

And sadly it will take some time to update the online version...

**Comment by dgirardeau** [comment]
The online 2.9.beta version has just been updated.
