### ISSUE TITLE
Canupo Issue CMD 

### ISSUE THREAD

**Issue by ahmadshabbir2468** [CloudCompare/CloudCompare#578]
I follow This Tutorial
https://geosciences.univ-rennes1.fr/IMG/pdf/Point_cloud_classification_user_guide_v1-2.pdf
 
And when I try to use Canupo Using CMD Its works Only  on Given Examples But when i try Same procedure ON MY DATA Its Crash ..   Please Remember 
My Examples are Very Similar to  the Given Examples 

Its break  On 3rd Command 

1C:\Users\raj\Desktop\PointCloud_Classification\PointCloud_Classification\Exe\canupo_windows_static_64bits\canupo 0.04:0.02:0.3 : floor.xyz floor.xyz floor.msc

 2C:\Users\raj\Desktop\PointCloud_Classification\PointCloud_Classification\Exe\canupo_windows_static_64bits\canupo 0.04:0.02:0.3 : vegetation.xyz vegetation.xyz vegetation.msc

3**C:\Users\raj\Desktop\PointCloud_Classification\PointCloud_Classification\Exe\canupo_windows_static_64bits\suggest_classifier_lda proposal.svg : vegetation.msc - floor.msc**

* OS & Version: Window 8

**Comment by dgirardeau** [comment]
Hum, I don't think it's the right place to declare this issue.  The command line version of Canupo has nothing to do with CloudCompare. You should contact the authors directly (even though the tool is quite old).

**Comment by ahmadshabbir2468** [comment]
Mine Please Thanks Sir / Brother 
I'll
