### ISSUE TITLE
BIN file not centred when loaded in 2.9.1 beta

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#580]
## Current Behavior

Loading a BIN version 4.6 file in latest git does not centre it like it did in 2.8.1

![2 9 1beta](https://user-images.githubusercontent.com/391371/29544340-73ce2906-86b5-11e7-8947-8a636c1e7339.jpeg)

## Expected Behavior

Cloud should be centred.

![2 8 1](https://user-images.githubusercontent.com/391371/29544343-796e5f98-86b5-11e7-971e-073271d31054.jpeg)

## Steps to Reproduce (for bugs)

Load a v4.6 BIN file.

## Context/Comments

I went back as far as I could in the commits to see if I could find where it changed. I could only go back as far as f3c6b229f9b7ddbff6a97c46661cdfae0cf5ae30 (where I worked around the Qt 5.9 bug). The problem existed at that point.

## Your Environment

* OS & Version: macOS 10.12.6
* CC Version: 2.9.1beta
* Graphics card: NVIDIA GeForce GTX 780M 4096 MB

**Comment by asmaloney** [comment]
Indeed that is the cause.

If I toggle it off and load the cloud, it's in the right place.

I also notice that the toggle doesn't save its state, so it's on every time I run CC.

**Comment by dgirardeau** [comment]
Okay the option is now saved (61eed90a1073e8e723ef13daa5706aa31e45f4e0).

However, I'm not sure about the other part of the problem (the fact that the cloud is not centered), as I can't reproduce it on my side :D

**Comment by asmaloney** [comment]
After discussion with @dgirardeau this is working as intended.
