### ISSUE TITLE
Improve build process with automated download of dependencies using Nuget

### ISSUE THREAD

**Issue by whatnick** [CloudCompare/CloudCompare#581]
## Current Behavior

Current build system requires manual population of dependencies.
## Expected Behavior

Use Nuget to automatically fetch and manage dependencies
## Context/Comments

I am looking at easing the CC build process to encourage more developers and contribution to this excellent tool.
## Your Environment

* OS & Version: Windows 7
* CC Version: Source - master
* Graphics card: Nvidia 1080

**Comment by dgirardeau** [comment]
Isn't Nuget a Windows/Visual thing only? As CloudCompare is portable on Linux and MacOS, I don't know if Nuget could be used in our case (we use CMake+Qt for this).

Moreover I could only find one Qt package (QtCore) among the supported packages (not the others: OpenGL, Widgets, etc.). And for the plugins, a lots of packages are missing.

But of course if someone find a good solution to this, we will be happy to integrate it ;)

P.S.: note that Qt is the only dependency for the core application and you simply have to download the installer to get the binaries, then launch CMake and point to the right Qt directory. I know that some plugins require some more tinkering, but sadly CMake is the best solution we found so far.

**Comment by whatnick** [comment]
Nuget works with CMake to populate dependencies (a bit like Maven for Java
applications). In Linux getting dev packages for depencies is much easier
than in Windows. Nuget makes it a bit less painful for MSVC.

**Comment by asmaloney** [comment]
Hi Tisham. Maybe if you could explain more about what your proposal looks like it will be easier to explore & evaluate.

What changes are required? CMake only? Additional scripts?

How does this thing integrate with the current build process? Additional steps required? What are the drawbacks? What maintenance is required?

etc.

**Comment by whatnick** [comment]
What changes are required:

Adding nuGet external tool calls to CMakeList

How does this integrate with current build process:

If windows platform is detcted NuGet activates to fetch dependencies from
NuGet repository.

Drawbacks:

Additional NuGet tool dependency and build is version locked to whatever
NuGet hosts

Maintenance:

Packages on NuGet need to be maintained to sync with the version CC uses.

In my recent experience using NuGet with Caffe:

https://github.com/BVLC/caffe/tree/windows?files=1

Made the build process infinitely easier.

On Aug 25, 2017 22:36, "Andy Maloney" <notifications@github.com> wrote:

Hi Tisham. Maybe if you could explain more about what your proposal looks
like it will be easier to explore & evaluate.

What changes are required? CMake only? Additional scripts?

How does this thing integrate with the current build process? Additional
steps required? What are the drawbacks? What maintenance is required?

etc.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CloudCompare/CloudCompare/issues/581#issuecomment-324914339>,
or mute the thread

**Comment by asmaloney** [comment]
I don't think this solves any issues for us. @dgirardeau can reopen if he wants to pursue this since it's a Windows thing.
