### ISSUE TITLE
Selecting two files in the tree to run the Compute 2.5D Volume tool 

### ISSUE THREAD

**Issue by allilowe** [CloudCompare/CloudCompare#591]
## Current Behavior

In the new release you can still use Ctrl to select two seperate files in the DB Tree but when you go to use them in the Computer 2.5D Volume Tool however, it will not let you use both and has an error. It will not let me go to the compute 2.5D volume. 

In the older release v2.9beta you can select them and use them as the different Sources in the computer 2.5D volume tool.

## Expected Behavior

You should be able to select two of the files and be able to use them as separate sources in the volume calculation. 

I am still new to code and looking at it. I can provide additional information if given some guidance on where to look for the bug/change and can look at both versions to see where the error is. I would love to help but not sure where to start. 

## Steps to Reproduce (for bugs)

Download the newest version, bring in vertices and a point cloud that are the same area- use Ctrl to select both, then go to Tools->Volume->Compute 2.5D Volume tool- you will not be able to use it with two different files. 

I can re-download the new version if this helps but I deleted it and went back to the older downloaded version we have.

## Context/Comments

Using vertices at the ground source and a point cloud as the Ceil/After source to calculate a stockpile volume as almost a triangulation method to compare against the volumes calculated by triangulation in Pix4D. 

No- I'm sure I can run it and see if you can help me to know where to pull up the code when I am doing this I am happy to assist/I would really like to learn how to do this. 

## Your Environment

* OS & Version:
* CC Version: 2.9.beta[Windows 64-bit]
* Graphics card:Windows 10 Enterprise 64-bit, IntelR CoreTM i7-4600M CPU @ 2.90GHz 4CPUs. 8192MB RAM, Intel(R) HD Graphics 4600

**Comment by dgirardeau** [comment]
Nice catch ;)

Andy started a big cleanup of the code recently, and he must have replaced the part of the code that check that 2 clouds are selected by only one ;).

It's fixed now 242e9039c3c881445020fb1b33b179f0ea5c1485 (I'll try to update the online beta release soon).

Thanks for the feedback.

**Comment by asmaloney** [comment]
Mea Culpa. That's what code reviews are for, right? :-)

(For reference, this error was introduced in a4cd7b557efe783666154eb40ca456b271f7b033 on 22 July.)

Thanks a lot Alli!

**Comment by dgirardeau** [comment]
Ah ah that's exactly what I thought. But you are bound to do this kind of things when replacing so much things ;)
