### ISSUE TITLE
Set up a Travis build for ScalarType of "double"

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#598]
By default `ScalarType` is a float, but some people compile CC with `ScalarType` as a double.

We should set up a Travis build for this case.

**Comment by Bedzior** [comment]
Hey, I have just come by this issue. Until recently I have only occasionally used CloudCompare, but now I would love to make a contribution.

I'll try posting a merge request soon.

**Comment by Bedzior** [comment]
@asmaloney hopefully #936 resolved this one :)

**Comment by tmontaigu** [comment]
Closing this, as it was done in the PR linked above

**Comment by asmaloney** [comment]
Thanks @tmontaigu. I just looked at that PR and it's not doing what I expect it to do - i.e. it's not building when `ScalarType` is double.

Take a look at any of the Travis builds (like [this one](https://travis-ci.org/CloudCompare/CloudCompare/builds/653528935?utm_source=github_status&utm_medium=notification)). See how the `SCALAR_DOUBLE=ON` builds only take ~2 minutes? That's because it's not actually building.

For some reason in this PR, we find this: ` && [[ $SCALAR_DOUBLE != "ON" ]]; ` which turns off the build. ??

**Comment by tmontaigu** [comment]
Indeed, I looked at the logs took quickly
It seems to be a mistake that the build stops. What the author wanted to do, is disabling tests when building with scalar

According to the 3rd point in the PR :
> a modification to Travis' build script - turning off tests for double comparisons in TestShpFilter, as the test data seems to be intended for float only and I don't feel competent enough to do anything with it.

**Comment by Bedzior** [comment]
Sorry for this egregious oversight. The build script was obviously supposed to run independent of `ScalarType`'s actual type.

Here's the PR resolving this issue: #1042. I have conditionally turned the tests off (as, again, they seem type-specific). One type had to be fixed, but it seemed straightforward.

**Comment by asmaloney** [comment]
No problem. Thanks for the fix!
