### ISSUE TITLE
ccGLWindow - enumeration not handled in switch

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#600]
I'm going through and doing some cleanup and ran into this. May be a bug or the state may prevent the execution of this switch.

In `ccGLWindow::fullRenderingPass` around line 1896 there's a switch statement switching on `m_stereoParams.glassType`:

```cpp
switch (m_stereoParams.glassType)
{
case StereoParams::RED_BLUE:
   RGB = (renderingParams.passIndex == 0 ? RED : BLUE);
   break;

case StereoParams::BLUE_RED:
   RGB = (renderingParams.passIndex == 0 ? BLUE : RED);
   break;

case StereoParams::RED_CYAN:
   RGB = (renderingParams.passIndex == 0 ? RED : CYAN);
   break;

case StereoParams::CYAN_RED:
   RGB = (renderingParams.passIndex == 0 ? CYAN : RED);
   break;

default:
   assert(false);
}
```

`NVIDIA_VISION` and `OCULUS` aren't handled in the switch. When built with debug this will assert, but release build will crash.

What should these set RGB to?

**Comment by dgirardeau** [comment]
The trick is in the test above:
```if (m_stereoModeEnabled && m_stereoParams.isAnaglyph())```

Oculus and NVidia glasses aren't 'anaglyph' modes :D
