### ISSUE TITLE
Update included nanoflann?

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#604]
We include v1.2.2. There exists a v1.2.3:

https://github.com/jlblancoc/nanoflann/releases

Should we update it for 2.9?

**Comment by dgirardeau** [comment]
Do you refer to the version included in the qHoughNormals directory? I'm not sure as we don't know what will be the effect on this plugin (as I'm not the author). Moreover I don't think it's worth the price ;)

**Comment by asmaloney** [comment]
I was just updating/reviewing the list of libs in the spreadsheet and saw this listed.

**Comment by dgirardeau** [comment]
Indeed!
