### ISSUE TITLE
UI problems

### ISSUE THREAD

**Issue by JesseVelodyne** [CloudCompare/CloudCompare#608]
## Current Behavior
The UI buttons and cursor position do not align. The cursor will be on one button, the button above will be pressed/highlighted instead. See image below where the tooltip appears while the cursor is not on the button.
![image](https://user-images.githubusercontent.com/15914825/31846160-a3215526-b5bc-11e7-83cb-55f7096e789e.png)

## Expected Behavior
Button that is highlighted is the button that is selected.

## Steps to Reproduce (for bugs)
View > Reset all GUI element positions
Restart.

## Context/Comments
The left menu bar was in it's correct spot yesterday. Today the left menu bar had disappeared. All individual View > Toolbars were marked as on. Turning them on and off did not make the left toolbar appear. So I reset the UI and restarted the application. Now all interface is distorted. Less distorted at the bottom of the window, more distorted at the top of the window.

Restarting CC did not fix the issue. Restarting Windows did not fix the issue. Reinstalling did not fix the issue. Downgrading did not fix the issue.

## Your Environment
* OS & Version: Windows 10 Pro version 1703 build 15063.674
* CC Version: 9.0 beta, 8.1
* Graphics card: Nvidea Quadro M5000M

**Comment by dgirardeau** [comment]
Multiple issues may arrise at the same time:
- check that your quadro card is used when launching CloudCompare (you should have an option in the NVidia settings for that). Well, this is only If you have an Intel graphic card on the same computer. A recent Intel driver update has introduced a bug that shift the window contents.
- reset the GUI elements placement... If you manage to go to the Display menu, use the latest entry: 'Reset all GUI element positions'
- if the above doesn't work, you can remove the registry information of CloudCompare (HKEY_CURRENT_USER\Software\CCCorp\CloudCompare). You can remove the whole folder.

**Comment by dgirardeau** [comment]
I realize it is in fact probably related to the Intel graphic card driver issue that occurred a few months ago (see http://www.danielgm.net/cc/forum/viewtopic.php?f=10&t=2661&p=10525#p10445).
