### ISSUE TITLE
Flickering while segment tool

### ISSUE THREAD

**Issue by OrsHH** [CloudCompare/CloudCompare#619]
## Current Behavior
I was using segment tool in v.2.9.1 version, and the point cloud was flickering while moving the mouse.
## Expected Behavior
Usually, that happens just when orbiting around the cloud, but in this case happened too when the cloud was static.

I have to say that only has happened once, in my new computer, in the old one, it never has happened. 

## Steps to Reproduce (for bugs)
With a huge point cloud (>18,000,000 pts), using segment tool and selecting a part of the cloud.

## Your Environment

* OS & Version: Windows 10
* CPU: i9-7900X
* CC Version: v.2.9.1
* Graphics card: Nvidia GTX 1070ti

**Comment by dgirardeau** [comment]
I couldn't reproduce the issue (with 110M points ;).

On my side each time the cloud is moved, the full rendering may take some time (as only a small amount of points is drawn at each new frame). Therefore the display might change while the polygon is defined. But if you start the tool, move the cloud, wait for it to be fully displayed (the trop-left wheel should stop cycling), then the display shouldn't change anymore when you are drawing the polygon.

Note that each time you right click on the mouse (to close the polygon), the display is updated.

Random guess: do you have a 3D mouse maybe? (they can be be very sensitive and 'vibrate' sometimes).

**Comment by OrsHH** [comment]
It should be a puntual problem, because it hasn't happened again.

Normal mouse, by the way
