### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ibtaylor** [CloudCompare/CloudCompare#620]
Tested against current master (https://github.com/CloudCompare/CloudCompare/commit/6880bb8805b6c2cd2dc78d0bcd771b35c5d37f01)

I experienced a crash when using the crop (scissor tool) on a large point cloud. I think it is probably a race condition.

The problem went away when I modified this bit of code
https://github.com/CloudCompare/CloudCompare/blob/6880bb8805b6c2cd2dc78d0bcd771b35c5d37f01/libs/qCC_db/ccPointCloudLOD.cpp#L523-L537

to
```cpp
 void ccPointCloudLOD::clear() 
 { 
 	if (m_thread) m_thread->wait(); // XXX added this line
 	m_mutex.lock(); 
  
 	if (m_thread) 
 	{ 
 		delete m_thread; 
 		m_thread = 0; 
 	} 
  
 	m_levels.clear(); 
 	m_state = NOT_INITIALIZED; 
  
 	m_mutex.unlock(); 
 } 
```

I doubt this is the real solution to address the problem, but maybe it leads you to a more appropriate fix.

**Comment by dgirardeau** [comment]
Indeed, I guess that if the LOD structure has not finished to prepare itself, then we could end up blocked.

And it's not that bad of a solution ;). I just changed this to ```m_thread->terminate()``` as there's no point in waiting here (it should be still pretty safe... at least I hope so ;) ): 3eb67fa0953db6e90230fc3a598a758d733e586a

Anyway thanks very much for the feedback (and the fix!).

**Comment by ibtaylor** [comment]
Your patch seems to still cause a segmentation fault.

**Comment by ibtaylor** [comment]
I can post a gdb backtrace if that would be more helpful.

**Comment by dgirardeau** [comment]
Hum, you mean that ```m_thread->wait();``` works, but not ```m_thread->terminate();``` :(

Or is it because of the 'isRunning()' test?

**Comment by ibtaylor** [comment]
Well, after seeing your patch, I added the `isRunning()` test before my `wait()` and it continued to not segfault.

So yeah, `wait` works here and `terminate` doesn't... whatever that is worth.

**Comment by ibtaylor** [comment]
https://doc.qt.io/qt-5/qthread.html#terminate

Seems that `wait` should be called after `terminate` if you're going to do it, but `terminate` just sounds like a hack and a better solution should be used.

Typically, if I want an early exit, I set a flag `volatile bool done` and have the thread exit early (putting things in at least a consistent state) if that is set.
```cpp
done = true;
if (thread_.joinable()) thread_.join() // same as isRunning and wait probably
```

Methods like `interrupt()` or `terminate()` seem like asking for races, but I'm sure everything has its uses.

**Comment by dgirardeau** [comment]
Ok, for now we'll have to stick to the 'terminate' hack because stopping gracefully the LOD construction would not be easy (it's a recursive process, and it's quite long if one simply waits for a level to finish ... at least for the higher levels).
