### ISSUE TITLE
Invalid toolbar in win10

### ISSUE THREAD

**Issue by LiShuaixin** [CloudCompare/CloudCompare#624]
Hi, I use the latest CloudCompare 2.10.alpha archive version on my Win10 PC. When I open the software it will cover my system toolbar at the bottom of desktop. Moreover, the toolbar of the software at the top is invalid. Each button is invalid!!! How can I solve this?
![default](https://user-images.githubusercontent.com/22472452/33434193-7a7f27f6-d619-11e7-92e1-518c049477a1.png)
[Uploading license.txt…]()

**Comment by dgirardeau** [comment]
It looks like the same Intel graphics driver bug that appeared a while ago (see http://www.cloudcompare.org/forum/viewtopic.php?f=10&t=2661&p=10525#p10445).

Your best option is to updated (or downgrade) your Intel driver. Or force your computer to use a better graphic card if it has one.

If you don't have an integrated Intel chipset, don't hesitate to re-open this issue.

**Comment by LiShuaixin** [comment]
Thank you for your help! I fixed it by running it with discrete graphic card. The system default graphics card is integrated graphic card which causes the issue.
