### ISSUE TITLE
QMake - Build Error in (/plugins/qCompass)

### ISSUE THREAD

**Issue by Twittadrock** [CloudCompare/CloudCompare#625]
## Current Behavior
QMake fails due to typo in CloudCompare/plugins/qCompass/CMakeLists.txt

## Expected Behavior
QMake finds source files in:
CloudCompare/plugins/qCompass/ui/mapDlg.ui
CloudCompare/plugins/qCompass/ui/compassDlg.ui

## Steps to Reproduce (for bugs)
execute 'make'

## Context/Comments
Remove "ui" from the two paths in CloudCompare/plugins/qCompass/CMakeLists.txt
CloudCompare/plugins/qCompass/ui/mapDlg.ui
CloudCompare/plugins/qCompass/ui/compassDlg.ui

## Your Environment
Arch (All-up-to-date)

**Comment by dgirardeau** [comment]
Ok that's fixed (194663d5c168148ffdd96b9112a580ffec9b8fe4). Thanks for the feedback.
