### ISSUE TITLE
[Windows 10] Systematic crash at launch

### ISSUE THREAD

**Issue by nazga** [CloudCompare/CloudCompare#628]
## Current Behavior
CloudCompare is systematically crashing at launch (either launching through the binaries or through opening a file).
It was already a problem with  2.9.1 before I had to format the computer.  Then it was ok at the begining with a fresh install and now it's crashing again with 2.9.1 or 2.10 alpha.

## Steps to Reproduce (for bugs)
Since I have not been able to really understand what is going  on (incompatibility between my setup/laste version of Win10 and the current win x64 release of CloudCompare ?)

## Context/Comments
> Faulting application name: CloudCompare.exe, version: 0.0.0.0, time stamp: 0x5a17e3f3
> Faulting module name: ntdll.dll, version: 10.0.16299.64, time stamp: 0x493793ea
> Exception code: 0xc0000005
> Fault offset: 0x000000000002df29
> Faulting module path: C:\Windows\SYSTEM32\ntdll.dll

Possibly access violation of ntdll ?

## Your Environment
* OS: 64 bit Windows 10 Professional (Version 10.0 Build 16299)
* CPU: AMD Ryzen 5 1600 
* MEM: 32699 MB, 
* GFX: NVIDIA GeForce GTX 1080 4096 MB (latest drivers 388.59)
* SCREEN: 3840 x 2160 @ 32 bit

* CloudCompare: 2.9.1 x64, 2.9.1 stereo x64 and 2.10 alpha

===
UPDATE: I guess it's linked to Windows version and  the AMD CPU.
The faulty element is: 
* ntdll.dll!RtlpLowFragHeapAllocFromContext()	Unknown	Non-user code. Symbols loaded.
* Unhandled exception at 0x00007FFC23CB968A (ntdll.dll) in CloudCompare.exe: 0xC0000005: Access violation reading location 0x00000000CDF8FAB0.
* 00007FFC23CB968A  mov         rax,qword ptr [r9]

**Comment by dgirardeau** [comment]
For once it doesn't seem to be a graphic card related issue (you have the same as mine ;).

But I'm a bit clueless... have you tried to run without any antivirus maybe? Or with admin rights?

**Comment by nazga** [comment]
Yes, I tried:
- disabling the antivirus (the windows one)
- running the binaries as administrator
- compatibility modes
- no dpi scaling (4k screens).

In addition, I have every Visual C++ redist (both x86 and x64) and the last visual studio.

Nothing seems to work. The strangest thing is, I reinstalled windows two weeks ago because of the same  problem and because I also wanted a "fresh" install. 
With the last Windows 10 iso "out of the box", CC works, but a few update later, not anymore.

> Unhandled exception at 0x00007FF8D7A1DF29 (ntdll.dll) in CloudCompare.exe: 0xC0000005: Access violation reading location 0x00000000A8DD67E0.

> ntdll.dll!RtlpFreeHeap()	Unknown	Non-user code. Symbols loaded.

> 00007FF8D7A1DF29  mov         rax,qword ptr [r12] 

My only guess would be a problem with AMD CPU's/drivers maybe?

**Comment by dgirardeau** [comment]
Indeed, it could be a culprit. Maybe a issue with Qt then?

Or it could be the memory?

**Comment by nazga** [comment]
I doubt it's the memory. It's almost brand new and perfectly stable, also nothing wrong with memtest.
I was also looking at possible conflicts with other programs but I don't see what could be involved. 
So far I tried to shut down the usual suspects: Teamviewer services and Oculus services. Not working.

I don't know much about Qt, the easiest way to check that would be  for me to compile directly CloudCompare right ?

**Comment by dgirardeau** [comment]
Yes, in debug mode. But if it's an issue with Qt, you might end up crashing right at the start (even in debug mode) without much more info. If we are lucky, it may give more interesting clues however.

**Comment by nazga** [comment]
Small update, compiling the source with CMake 3.10.1, QT 5.6.0 and Visual Studio 2015 works without any plugin or option. I am able to launch CloudCompare.

Should I move forward and try to install plugins/option to pinpoint  what the culprit of the problem is or do you have already any idea about what is going on at this point?

To be honest, I am not used  to cmake stuff so I am not sure I will be able to get every dependencies right for the loaders/plugins.

**Comment by dgirardeau** [comment]
Have you tried to remove all plugins of the "official" version then? (you can simply remove or rename the plugins folder)

**Comment by nazga** [comment]
Yes, I tried to remove:
-plugins
-imagesformats
-non essential shaders
-every optional dll's, one by one

I was wondering if it has  something to do with the "qwindows.dll" and other "non-d" related dll's.
What is the difference between qwindows and qwindowsd?

I will try to move forward and process the entire CC with plugins/options.

**Comment by dgirardeau** [comment]
the 'd' versions are for the debug mode.

**Comment by dgirardeau** [comment]
On my side I'll try to recompile everything for Visual 2017 and see if it helps.

**Comment by nazga** [comment]
![cloudcompare](https://user-images.githubusercontent.com/8963759/34300536-d439fd0a-e728-11e7-91d5-b128dc73ca64.jpg)

It worked again with this setup but unfortunately setting up "pcl" and the "las/laz" seems to be out of my league. I don't really understand how to make the  boost stuff work.

Do you want me to host some files so that you can check it?

**Comment by dgirardeau** [comment]
For LAS it's normal, I've juste integrated a fork that introduces PDAL instead of LibLAS for reading LAS files.

Otherwise you'll find here a version of CC compiled with Visual 2017 and almost all plugins: http://www.cloudcompare.org/release/CloudCompare_v2.10.alpha.vc2017_setup_x64.exe

Can you try it and see if it works?

**Comment by nazga** [comment]
I tried to install it and it tells me that a bunch of dll's cannot  be found:
ogdi.dll 
expat.dll 
xerces-c_3_1.dll
LIBPQ.dll

![cloudcompareinstall](https://user-images.githubusercontent.com/8963759/34304974-65b1f4a0-e73c-11e7-951a-015678c9cdbb.jpg)

**Comment by dgirardeau** [comment]
Hum, it must be because I use GDAL from osgeo4w. I'll try to fix this.

**Comment by nazga** [comment]
I used the gdal include and libs from my Qgis installation.

**Comment by effgeegee** [comment]
I have the same problem of CC2.91 and 2.10 crashing on startup. Command line works, by the way. I also see faulting module ntdll.dll.

**Comment by effgeegee** [comment]
Installed http://www.cloudcompare.org/release/CloudCompare_v2.10.alpha.vc2017_setup_x64.exe, installed GDAL via osgeo4w, I copied the dlls (just all bc i kept getting error messages asking for different .dll from that directory) from GDAL bin folder to CC main folder.
I got an error that xerces_c_3_1.dll was missing, the one in my GDAL install is 3_2. Downloaded the legacy Xerces binaries from their websites, trying them one after another. All of the x86_64 ones, 3.1.0 vc8 and vc9, 3.1.1 vc8-10. (I really have no clue what I'm doing here, neat huh). also tried a "xerces-c-3.1.4.2052_64vc12" I found for good measure. All of them produce the same effect, the splash banner shows, then there's the "stopped working" window. 

Sooo I figure it might be about supplying the correct xerces C++ dll?

**Comment by nazga** [comment]
I don't think it's about xerces.

My 2.10 debug version (working but  without the options I need like las/laz loader) has the right xerces dll but it does not solve the error from the setup.

I am a bit clueless to be honest.
What is your pc setup by the way?

**Comment by effgeegee** [comment]
OS Name:                   Microsoft Windows 10 Pro N
OS Version:                10.0.15063 N/A Build 15063
Total Physical Memory:     16,303 MB
GPU:                AMD R9 Fury 4096mb RAM, latest driver 17.12.2
CPU i5 4440
screen: 3840x2160 10bpc

**Comment by effgeegee** [comment]
I just set the resolution to 1080p and lo and behold, it started without a hitch. Set to 2160p with the program running it continued albeit with 100% gui scaling. stopped and started again in 2160p, and the problem reappeared

**Comment by nazga** [comment]
Ok, same problem then !

I have one 4k monitor and two QuadHD side monitors.
If I set the three of them at 1080p and 100% scaling, it works (the 2.10_VC2017).
If I set the main monitor at 1080p/noscaling and leave the other at full resolution/150% scaling, it's still crashing.

I don't really get why the 2.10 that I am compiling myself is working without any problem in full  resolution/150%.

**Comment by dgirardeau** [comment]
Interesting! Are you using the quad buffering (stereo) mode? Because this mode will require twice more memory...

Otherwise there may be other issues specific to 4k screens?

**Comment by nazga** [comment]
On my side, I don't use quad buffering.
My understanding is that it's only available through Quadro drivers right?

It's very strange that:
- it works when I am compiling  the program myself.
- it is something that is happening with recent Win10 updates (again, no problem with a fresh install from the latest iso).
-both effgeegee and myself have AMD drivers installed.  Me for my CPU/Motherboard and him for the GPU.

**Comment by effgeegee** [comment]
Just an aside but i can use "ignore system gui scaling" on compatibility tab for the program. Also this has been tested only for the 2017vc build

**Comment by asmaloney** [comment]
One other thing to check is the versions of Qt. The official release of CC 2.9 from Daniel looks like it uses Qt 5.9.1. When you compiled it yourself, what version did you use? Qt 5.9.3 is the latest in the LTS and Qt 5.10 is the latest overall release so it's possible that there are changes related to this.

**Comment by dgirardeau** [comment]
For the records I've updated the installer and archive versions of the 2.10.alpha version compiled with Visual 2017 and with the full set of GDAL DLLs:
http://www.cloudcompare.org/release

**Comment by dgirardeau** [comment]
I compile the latest online 2.10.alpha version with Qt 5.9.3. Does it change anything?

**Comment by dgirardeau** [comment]
And it doesn't crash then? Does it mean the issue is fixed?

**Comment by nazga** [comment]
Yes, I guess we can close the issue if you agree.
