### ISSUE TITLE
Support for X, Y and Z coordinates in 64-bit double precision?

### ISSUE THREAD

**Issue by nangeschnappt** [CloudCompare/CloudCompare#638]
I have been working with point clouds with Universal Transverse Mercator (UTM) coordinates and the northing or Y may have large values in the order of 10^6 meters for which 32-bit single precision does not suffice. For example, using 32-bit single precision for point clouds of places in Germany would mean a quantization of approximately half a meter. This means that line segments become visible when one zooms in. Below you could find an example.

![quantizationerror](https://user-images.githubusercontent.com/18368359/34884270-821458f0-f7bc-11e7-84fb-c7b3dde7bddf.png)

My current workaround is to normalize the Y by their mean value, which is however cumbersome when one wants to simultaneously visualize point clouds of different places.
Therefore my question: would it be possible for the CloudCompare BIN format to support `X`, `Y` and `Z` coordinates in 64-bit double precision?

**Comment by nangeschnappt** [comment]
@dgirardeau Thanks a lot for your reply! Somehow CloudCompare didn't automatically suggest any global shift although my `x` and `y`.I tried manually editing the global shift but it didn't change anything. I suppose

**Comment by dgirardeau** [comment]
What format are you using for importing the clouds? Some formats are already storing the coordinates on 32 bits and CC won't even check for big coordinates (as it's already too late).

And once the cloud is loaded, it's too late to change the Global Shift. However you can also set the Global Shift 'triggering' thresholds (with Edit > File > Global Shift Settings).

**Comment by nangeschnappt** [comment]
@dgirardeau Alright, that explains everything. I use the CloudCompare own BIN format. Thus my former question was whether it would be possible for the CloudCompare BIN format to also support X, Y and Z coordinates in 64-bit double precision. Or does it already? At least according to the [documentation](http://www.cloudcompare.org/doc/wiki/index.php?title=BIN) it should be 32-bit float.

**Comment by dgirardeau** [comment]
No, the BIN format is actually a 'mirror' of the data in memory. Therefore it's 32 bits by default (if you use the default version of CloudCompare). But you can store big coordinates inside as the BIN format also contains the Global Shift information next to the coordinates. 

Normally, before saving a cloud to a BIN file, one should have already set the Global Shift correctly (when loading or generation the data inside CloudCompare).

How did you generate this BIN file the first time?

Note that programmatically, it's possible to use a BIN file with 64 bits coordinates.

**Comment by HTLife** [comment]
@nan2ge1 Do you have the 64 bit version?

**Comment by dgirardeau** [comment]
Hum, strangely I realize that I missed the last question from @nan2ge1. The BIN format can store 64bits values but only when used with the 'double-precision' version of CloudCompare (which one has to compile, this is not the standard version). Otherwise, by default the BIN format stores coordinates on 32 bis, along with the Global Shift & Scale information (as the standard version of CloudCompare).

**Comment by HTLife** [comment]
@dgirardeau Thanks for the reply. My target format is ply.  I notice that CloudCompare handle the data with double precision.  But the ply `WritePoints()` in `plugins/core/Standard/qPoissonRecon/extern/PoissonRecon/Src/ChunkPLY.cpp` only parse it as float.  However, standard PLY file supports double precision.  So my workaround is to save everything in ASCII and set the precision to 10 digits.
Where can I find the 64bit version and compile by myself (BIN support is ok, I can take a look and modify the PLY accordingly)

**Comment by dgirardeau** [comment]
Oh, In CloudCompare we don't use the PLY import/export from the PoissonRecon lib. We have our own PLY I/O filter, and this filter supports double precision (see https://github.com/CloudCompare/CloudCompare/blob/master/libs/qCC_io/src/PlyFilter.cpp)

**Comment by HTLife** [comment]
@dgirardeau I tested with PLY binary format, it handle data in double correctly.  For the ASCII format, it will produce fixed length string which cut-off the floating point completely.

**Comment by dgirardeau** [comment]
Ah good point (I never use the ascii format).

I fixed it: a0d4c151aad0773babdc5de62b6205450e9d262b
