### ISSUE TITLE
Apply All for Opening Ascii File not Skipping lines

### ISSUE THREAD

**Issue by Wiezzenger** [CloudCompare/CloudCompare#639]
## Current Behavior
Currently after selecting the fields and amount of lines to skip when importing an ascii file with headers and selecting apply all it loads the point cloud but adds in a point for the headers of the file. This occurs even if the skip lines option is set to 1. It also requires CC to be reopened to reset the import schema for ascii files.

## Expected Behavior
It should keep the skip lines count for each successive file.

## Steps to Reproduce (for bugs)
Import a .csv or other ASCII file with headers that are strings in the first line
Change skip lines to 1
Ensure the combo box for "extract scalar field names from first line" is selected
Click Apply All
Import another (or the same) file with headers in the first line
A point should be created at 0,0,0 along with the other points

## Context/Comments
I'm attempting to import a large amount of pre processed point clouds in .csv format with normals and a scalar field. I have other data sets that have several scalar fields that need to be changed for each individual cloud due to CC auto assigning the normal tag to what are scalar fields. Being able to import all 15-25 files (which will be growing as my project continues) is a very manual process currently that could be greatly automated by apply all working correctly.

The data sets have a huge translation that can make the 0,0,0 point easy to remove, and I just figured out how to delete the hidden points when cropping, so a work around that doesn't add more work to me does exist.

## Your Environment

* OS & Version: Windows 10 Home
* CC Version: 2.8.1 [64-bit]
* Graphics card:

**Comment by dgirardeau** [comment]
Have you been able to test this with the latest version? (2.9 or better 2.10.alpha). Because it reminds me of a bug that has been fixed.

However it might be something else ;)

**Comment by Wiezzenger** [comment]
I have not! Last time I looked 2.9 was still in beta so I was waiting, I'll update right now and double check.

I did a quick look through previous issues and nothing came up, which is why I posted.

**Comment by Wiezzenger** [comment]
Yes this has been fixed in 2.9.1, my bad for not double checking I was running the latest and greatest before submitting an issue!

**Comment by Wiezzenger** [comment]
With v2.9.1 the 0,0,0 point is no longer created, however the scalar fields are imported without their names. There is a warning from ASCIIFilter::load

![error in 2 9 1](https://user-images.githubusercontent.com/35580032/35243616-8c15f274-ff8b-11e7-887a-68f1f2230bd7.PNG)

I installed v2.10.alpha to see if it resolves the issue, however it crashes (by just hanging and then not responding) while attempting to load the second file. These are the settings I used and I clicked Apply All and Yes to All one each dialogue in both cases.

![input](https://user-images.githubusercontent.com/35580032/35243148-dc2209c6-ff89-11e7-8f0a-9275e7c2328f.PNG)
![shift menu](https://user-images.githubusercontent.com/35580032/35243149-dc352b78-ff89-11e7-88c0-999e0c7328ab.PNG)

**Comment by dgirardeau** [comment]
Hum interesting. So this seems to come mainly from the fact that the first line is skipped if I understand well? I'll take a look in this direction.

**Comment by Wiezzenger** [comment]
Yeah, I haven't tried skipping more then one line, but the second screenshot is what I've been using for all of my processing and currently it imports correctly, just without assigning the scalar fields their names correctly. Seems as though the full settings from the first import are not carried on for the next files.

As a side note (and I haven't tried this in 2.9.1 yet), it would be nice if the apply all in the Open ASCII File dialogue only applied to the files you were importing at that time, similar to how the Global shift/scale works. I regularly work with multiple csv files that have different structures.

**Comment by dgirardeau** [comment]
Okay, I already found why the header line was not processed the second time (the option was always reset).

For the change of behavior of the "Apply all" button ... I think we need to think about it a little (it's a big change ;). We could consider that's it's only for the current set of files ... if there is more than one file. Otherwise we keep the previous behavior.

**Comment by Wiezzenger** [comment]
For sure it's a big change, I wonder how many users batch import different data structures with the same file type regularly.

I like your proposed behaviour; if I'm bringing in a bunch of files I'm either going to drag and drop each individually and set up the first one or drag and drop all of the files I want to see in one go.

**Comment by dgirardeau** [comment]
For now I changed the behavior as you suggested ... because it is simpler :D. I'll see how the users of the alpha version will react (otherwise we'll have to add an option).

You can test the online 2.10.alpha version now. All the issues declared here should be resolved.
