### ISSUE TITLE
e57 import dialog issue

### ISSUE THREAD

**Issue by lasaa2** [CloudCompare/CloudCompare#641]
## Current Behavior

While importing .e57 file the "Global shift/scale" window appears only 3-5 seconds and then it comes background. I can't change anything or even click YES. I think that it's bug.

## Expected Behavior

"Global shift/scale" window appears until click YES/NO.

## Your Environment

* OS & Version: Windows 10 64bit
* CC Version: 2.9.1 AND 2.10alpha

**Comment by dgirardeau** [comment]
Do you maybe see a progress dialog that appears in place of the global/shift scale dialog?

I get one on my side if I wait for 5 or 10 seconds (but I can "cancel" it and the global/shift scale dialog reappears).

**Comment by lasaa2** [comment]
Yes I see. Same than you.

**Comment by dgirardeau** [comment]
Okay this is fixed. You can already download the latest 2.10.alpha version.
