### ISSUE TITLE
qAnimation plugin crash OSX

### ISSUE THREAD

**Issue by Bruzzlee** [CloudCompare/CloudCompare#643]
## Current Behavior
CloudCompare crashes after pushing "Render" in the animation window.

## Expected Behavior
Should start rendering the animation.

## Steps to Reproduce (for bugs)
OSX CloudCompare 2.9.1.
Load point cloud
Create view ports
Select view ports
Open plugin window
Click "Render"

## Context/Comments
The FFMPEG libraries might be the problem.

## Your Environment
See attached crash report.
[log.txt](https://github.com/CloudCompare/CloudCompare/files/1665956/log.txt)

**Comment by asmaloney** [comment]
Ok - according to the crash log this does not seem to be related to the older animation plugin issues that had to do with with lib paths and packaging. This is FFMPEG itself crashing. The version included with CC 2.9.1 is 3.4.0 and the latest from homebrew is 3.4.1, so it's possible they fixed whatever you've run into here.

I'm still puzzled why it doesn't crash on me though. I am running 10.12.6 as well.

Have you tried different point clouds?

Do you have access to another Mac to try it on?

**Comment by asmaloney** [comment]
Thanks. As I pointed out, I don't recommend that as a long-term solution for anyone else. It will break in the future when things move/update/go away.

I still can't reproduce it.

- What format are you writing to? mp4?
- Are you changing any of the settings? Framerate, bitrate, etc?
- How many viewports are you selecting - does it crash with just two?
- Do you have access to another Mac to try it on?

If anyone else is experiencing this crash, please chime in!

**Comment by Bruzzlee** [comment]
- I've tested avi, mpeg, mpg and mp4. Always the same crash.
- Yes, I played with them. But also the default 25 fps and 1000 kbps is not working.
- I've tried 2-3 view ports
- No. Sorry

**Comment by asmaloney** [comment]
I'm sorry but I've been unable to reproduce this here.

Hopefully someone else with the same problem will chime in and we can get more data.

**Comment by asmaloney** [comment]
Cannot reproduce. If you still have the problem in the next release, please reopen or create a new issue.
