### ISSUE TITLE
When point picking, the content of created label not shown properly

### ISSUE THREAD

**Issue by zihahage** [CloudCompare/CloudCompare#644]
## Current Behavior
When point picking, the first column content, like "X Y Z" in created label is not shown properly. The left half is covered by something else, as you can see from picture below.  I tried in several computers, it showed the same. 

## Your Environment

* OS & Version: Win 7
* CC Version: 2.9.1 & 2.10Alpha
* Graphics card: NVIDIA GTX650

![img](https://user-images.githubusercontent.com/16953542/35431074-097ceed4-02b6-11e8-89cc-f9a0ac9f384e.png)

**Comment by dgirardeau** [comment]
This doesn't happen on my side, even when I play with the label font size (in the Display properties dialog, 'Labels' section).

The font looks a bit odd to me, have you maybe changed the default system font?

**Comment by zihahage** [comment]
Thanks for your reply! I have not changed default system font. And I can see that CC 2.8.0 shows properly even with same system configuration.

**Comment by dgirardeau** [comment]
Hum, then it must be a Qt issue... Hope this will be fixed in the future. However it doesn't seem critical, therefore I'll close this issue as I don't see what we can do in the current state.
