### ISSUE TITLE
Cannot open PCD files: unhandled file extension 'pcd'

### ISSUE THREAD

**Issue by jancoow** [CloudCompare/CloudCompare#646]
## Current Behavior
So I compiled CloudCompare with the QPCK_PLUGIN. I placed this compiled .so plugin in the /usr/lib/cloudcompare/plugins directory. On startup, CloudCompare can find the QPCL plugin:

> [Found plugin: PCL wrapper (libQPCL_PLUGIN.so)

However, when I want to open a PCD file through file -> open I get an error:

> [Load] Can't guess file format: unhandled file extension 'pcd'

## Expected Behavior
It should open PCD files with the QPCL_PLUGIN 

## Your Environment
* CC Version:  2.9.1 compiled with QT 5.5.1
* OS & Version: Ubuntu 16.04 64-bit
* Graphics card: GeFore GTX 970

**Comment by dgirardeau** [comment]
I believe you need to compile the QPCL_IO plugin (the other one is just a wrapper on some PCL algorithms)

**Comment by jancoow** [comment]
I can't find the QPCL_IO plugin cmake files. Where can I find them?

**Comment by dgirardeau** [comment]
It's a sub-project of the PCL plugin in fact (plugins\qPCL\PclIO). You have to activate the PCL plugin and it will be automatically added to the project.

**Comment by dgirardeau** [comment]
Oh, by the way, you should only need to compile the 'INSTALL' project to copy everything at the right place (and not copy the plugins manually). At least that's the theory ;)

**Comment by chngdickson** [comment]
> Oh, by the way, you should only need to compile the 'INSTALL' project to copy everything at the right place (and not copy the plugins manually). At least that's the theory ;)

How Does one activate their plugin?

**Comment by munitioner** [comment]
> It's a sub-project of the PCL plugin in fact (plugins\qPCL\PclIO). You have to activate the PCL plugin and it will be automatically added to the project.
I have the same problem. How to activate the PCL plug-in？
