### ISSUE TITLE
won't start on windows???

### ISSUE THREAD

**Issue by AbbeyMac** [CloudCompare/CloudCompare#656]
I'm a first time user of CloudCompare (well, not even that yet)
Everything seemed to be fine with downloading although it did have to restart idk if that's normal
My background is now black but that's not a current concern, just added it in case it helps with anything
when I try to open cloudcompare, i get this:
![errorcc](https://user-images.githubusercontent.com/36908102/36767938-bcccaaa0-1c34-11e8-8a93-9ae7378452ef.PNG)

**Comment by AbbeyMac** [comment]
Update: background is no longer black. Taking the small victories. CC still not working

**Comment by asmaloney** [comment]
Please fill in the issue template properly - we don't know what version of CC you're using, what version of Windows you're using, what card you have, etc..

**Comment by dgirardeau** [comment]
And generally this kind of error comes from a old graphic card / driver (e.g. old Intel graphic cards).
