### ISSUE TITLE
Compile fails UBUNTU 16.04 LTX linux 4.10 gcc g++ 5.4.0 libcurl reference undefined

### ISSUE THREAD

**Issue by marcel-bariou** [CloudCompare/CloudCompare#657]
## Current Behavior

 > make failed with the following message : 
 > [ 74%] Linking CXX executable CloudCompare
> /usr/local/lib/libpdal_base.so : référence indéfinie vers « curl_easy_reset »
> /usr/local/lib/libpdal_base.so : référence indéfinie vers « curl_slist_free_all »
 > /usr/local/lib/libpdal_base.so : référence indéfinie vers « curl_easy_perform »
> /usr/local/lib/libpdal_base.so : référence indéfinie vers « curl_slist_append »
> /usr/local/lib/libpdal_base.so : référence indéfinie vers « curl_easy_cleanup »
> /usr/local/lib/libpdal_base.so : référence indéfinie vers « curl_global_init »
 > /usr/local/lib/libpdal_base.so : référence indéfinie vers « curl_easy_setopt »
> /usr/local/lib/libpdal_base.so : référence indéfinie vers « curl_easy_getinfo »
 > /usr/local/lib/libpdal_base.so : référence indéfinie vers « curl_easy_init »
 > collect2: error: ld returned 1 exit status 
> qCC/CMakeFiles/CloudCompare.dir/build.make:2785 : la recette pour la cible « qCC/CloudCompare » a échouée
> make[2]: *** [qCC/CloudCompare] Erreur 1
> CMakeFiles/Makefile2:1147 : la recette pour la cible « qCC/CMakeFiles/CloudCompare.dir/all » a échouée
> make[1]: *** [qCC/CMakeFiles/CloudCompare.dir/all] Erreur 2
> Makefile:127 : la recette pour la cible « all » a échouée
> make: *** [all] Erreur 2

PDAL works correctly with *.las capacity
I added path to shared an static library with LGD_LIBRARY_PATH in /etc/environment and in /etc/ld.so.conf with ldconfig activation, I create symbolic  link from /usr/local/lib to /usr/lib/x86-64-linux-gnu to libcurl.so & libcurl.a

## Expected Behavior
libcurl3 and libcurl3-dev correctly installed
Without PDAL_LAS of course no problem compile goes ahead and CloudCompare starts
with PDAL_LAS compile fails

## Steps to Reproduce (for bugs)
Configure and Generate with CMAKE 3.5.1

## Your Environment
* CC Version last one from GITHUB 2.10 alpha, compile with Qt 5.7: 
* UBUNTU 16.04 LTS linux 4.10 gcc g++ 5.4.0 
* NVIDIA K5000

I am lost help needed Thank you for any hint

**Comment by dgirardeau** [comment]
Shouldn't you ask this to the PDAL community maybe?

**Comment by marcel-bariou** [comment]
Thanks for your interest I have done, Il will tell you  the return if possible.

**Comment by marcel-bariou** [comment]
OK Daniel,  I fixed it. In fact libcurl need a C++ wrapper libcurlcpp0. I installed it and I can  link with libcurlpp.so. Now I have the libcurl symbol and PDAL as CloudCompare, are built correctly. Andrew from PDAL leads me on thee good way. Thank for your interest and your help it was great for me ! Thanks. Thanks also for your great work.
