### ISSUE TITLE
Can not run CC in command-line mode from Python script

### ISSUE THREAD

**Issue by alexbruy** [CloudCompare/CloudCompare#658]
## Current Behavior
I want to run CloudCompare in command-line mode from Python program. CloudCompare installed at `C:\CloudCompare`. In Python I construct command line command e.g.:
```
C:\CloudCompare\CloudCompare -SILENT -NO_TIMESTAMP -O lasfile.las -CROPD2D....
```
and execute it with `subprocess`
```
with subprocess.Popen(command,
                          shell=True,
                          stdout=subprocess.PIPE,
                          stdin=subprocess.DEVNULL,
                          stderr=subprocess.STDOUT,
                          universal_newlines=True) as proc:
# do something
```
But it does not work, instead a window pops-up with message
```
This application failed to start because it could not find or load the Qt platform plugin "windows" in "".

Available platform plugins are: direct2d, minimal, offscreen, windows, windows.

Reinstalling the application may fix this problem.
```
If I `cd` into `C:\CloudCompare`, open command line and execute the same command it works. Also same command work when executed from batch file.

Am I doing something wrong?

## Expected Behavior
CloudCompare runs in command-line mode when invoked via Python's `subprocess`.

## Your Environment
* CC 2.9.1: 
* Windows 7 Pro/Windows 10 Pro x64

**Comment by alexbruy** [comment]
Seems I've found what's wrong: I have another Qt app installed and it adds its libs to environment variables, so CC can not find its own libs. I've solved this by creating batch file with necessary commands and executing this batch from Python instead of executing CC commands directly.

But there is another issue. Execution still failed with message
```Syntax error in file name, folder name or drive letter```
Same batch file works fine when executed via command-line directly

**Comment by dgirardeau** [comment]
CloudCompare is based on Qt (https://www.qt.io/). And on Windows the application requires a plugin (windows.dll) which is located by default under the 'plugins' folder next to the executable.

Apparently, when you call the application from python, it prevents (or tricks) Qt which can't find the plugin file. You may want to look at how to change the active / current directory in your Python script? 

Or a Python guru might help you understand what's at stake ;)

**Comment by davidcaron** [comment]
I can call CloudCompare from command line without any issue... although the install directory of CloudCompare is in my PATH environment variable. I would say try doing that or `os.chdir("C:\CloudCompare")` before calling subprocess.

**Comment by WargodHernandez** [comment]
this isn't a CC issue, but the "fix" is to specify the cwd parameter in popen like

``` python
with subprocess.Popen(command,
			  cwd=C:\CloudCompare
                          shell=True,
                          stdout=subprocess.PIPE,
                          stdin=subprocess.DEVNULL,
                          stderr=subprocess.STDOUT,
                          universal_newlines=True) as proc:
# do something
```

this just tells the system the current working directory, otherwise cloudcompare will get the cwd equivalent to where the script was executed from.
