### ISSUE TITLE
Save/Export M3C2 values (Command line Windows)

### ISSUE THREAD

**Issue by xabierblanch** [CloudCompare/CloudCompare#670]
I'm working with M3C2 on the windows command line but I think that it not get work properly. I've been exploring all ways to export/save the new cloud point that M3C2 generate after apply the plugin but always save ONLY the two original cloud points, never the newest with the M3C2 values. I tried all configurations with the m3c2_params file but I don't reach my goal.

## Current Behaviour

CloudCompare -AUTO_SAVE ON -O C:\Users\Public\file1.xyz -O C:\Users\Public\file2.xyz -M3C2 m3c2_params.txt -SAVE_CLOUDS

With this command line CC only save the two cloud points loaded but not export or save the new cloud point generated by the M3C2 plugin. 
Cloud 1 -> Saved
Cloud 2 -> Saved
Cloud M3C2 calculated -> ??? not saved

## Expected Behaviour
I think that this command line (or something similar) have to export all cloud points that are "active". It means the two loaded cloud points and the new cloud point wit the M3C2 parameters calculated

Cloud 1 -> Saved
Cloud 2 -> Saved
Cloud M3C2 calculated -> Saved

## Steps to Reproduce (for bugs)
I only have been testing this command line:

CloudCompare -AUTO_SAVE ON -O C:\Users\Public\file1.xyz -O C:\Users\Public\file2.xyz -M3C2 m3c2_params.txt -SAVE_CLOUDS

Also, I have been working with similar commands. I tried -AUTO_SAVE and I tested all -C_EXPORT_FMT formats.

## Your Environment
* CC Version: 2.10
* OS & Version:  Win7
* Graphics card:  GPU (BIOS)

**Comment by dgirardeau** [comment]
I forgot to add the lines for saving the cloud! Looks silly isn't it ;) 

That's fixed now with 7b4bf7328480555f5df617eca97cd35b7b36d1fe

I've updated the online 2.10.alpha version (I'll wait for your feedback to confirm that now it's working as expected ;).

Thanks for the feedback...

**Comment by xabierblanch** [comment]
Hi Daniel,

It works properly! Thank you for quickly updating CloudCompare.

![image](https://user-images.githubusercontent.com/37353398/37516499-9af10df4-290e-11e8-8ed8-207501ab14a3.png)

I think that maybe there are other little bugs as for example the subsample options because as much as you make it disable the M3C2 make a subsample of the cloud points. It's not serious because you can introduce a very little subsample radius and it works with all the original points. But I think that soft doesn't "read" the SubsampleEnabled line

`SubsampleRadius=1e-6`
`SubsampleEnabled=false`

Thanks you for you help!

**Comment by dgirardeau** [comment]
Oh, good catch! It's fixed now.

Sorry about this, but you are probably the first user to test this new feature ;)

**Comment by xabierblanch** [comment]
Do not worry, we're on the same side! It is not a problem for me to communicate these little bugs. CC is a great software and access by command line is the best improvement.

It's great for me to help you testing M3C2 plugin
