### ISSUE TITLE
Question !

### ISSUE THREAD

**Issue by MahdiSMIDA** [CloudCompare/CloudCompare#671]
How can i apply & Display the "Compute octree" just for the mesh (BOX) and the Cloud intersection using CloudCompare Library?
Thanks

## Your Environment
* CC Version: 
* OS & Version: 
* Graphics card:

**Comment by dgirardeau** [comment]
I can't understand the question.

And as it seems you ALSO sent me an email, I'll close this ticket.

Please, don't "spam" us like this...
