### ISSUE TITLE
msvc/stdint.h required?

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#690]
Are the `CC/include/msvc/stdint.h` and `libs/qCC_db/include/msvc/stdint.h` files still required? Or are these for a much older version of msvc?

**Comment by asmaloney** [comment]
Found another one:

`libs/qCC_db/msvc/stdint.h`

Actually there's another one:

`plugins/core/qAnimation/src/QTFFmpegWrapper/win/stdint.h`

But it looks like that one is owned by QTFFmpegWrapper.

**Comment by dgirardeau** [comment]
Indeed, I removed those folders (16721a667a6fbc214da8d0eae417f383376be0a0à. For QTFFMPEG_LIB, I hope it will still compile with Visual 2013? (I guess it should, but I don't compile with it anymore).
