### ISSUE TITLE
The Open dialog (in Windows 10) appears to show the destination name (for Shortcuts), not the actual name.

### ISSUE THREAD

**Issue by RevitIRL** [CloudCompare/CloudCompare#695]
## Current Behavior
The Open dialog (in Windows 10) appears to show the destination name (for Shortcuts), not the actual name. For our Project Folders, we have a subfolder called "Revit 2016" (or "Revit 2017", etc.) that I make a shortcut to (but rename the shortcut to include the job number and name). However, when I use CloudCompare and click Open, the dialog presented shows a bunch of "Revit 20##" folders instead of all the job numbers & names (for the shortcuts). The Save dialog, on the other hand, shows the names correctly.

## Expected Behavior
The Open dialog should show the names of the shortcuts (like the Save dialog does).

## Steps to Reproduce (for bugs)
Click Open:
![cloud compare open dialog](https://user-images.githubusercontent.com/20117305/38000933-de9cdb40-31c5-11e8-87f5-3c573bc372fc.png)
vs. Click Save:
![cloud compare save dialog](https://user-images.githubusercontent.com/20117305/38000934-debc3698-31c5-11e8-92b8-02b39f06a00d.png)

## Context/Comments
I want to use by Shortcuts to get to the project folder (without having to navigate manually through the full path).

## Your Environment
* CC Version: 2.9.1
* OS & Version: Windows 10
* Graphics card: NVIDIA Quadro P1000

**Comment by dgirardeau** [comment]
It's probably because the loading dialog is not a native one (i.e. handled by Windows) but it's a generic dialog handled by Qt... This was due to avoid a bug that was caused by the native dialog and that was making CC crash on some systems... But it's quite old so I guess we could roll-back to the native dialog. I'll see what I can do asap.

**Comment by dgirardeau** [comment]
Okay I updated the latest version of CC (2.10.alpha, online).

By default the native dialog is used now. But the user can still revert to Qt dialogs in case of crash (via the 'Display Options')
