### ISSUE TITLE
Visual Studio Compilation Error

### ISSUE THREAD

**Issue by Salink** [CloudCompare/CloudCompare#697]
## Current Behavior
Compilation error in qCC\pluginManager\ccPluginManager.cpp, line 246.
interface is defined as:
```
#define __STRUCT__ struct
#define interface __STRUCT__
```
in combaseapi.h for windows 10 SDK.

Can we rename that variable to something else?

**Comment by asmaloney** [comment]
Absolutely. Give me a minute...
