### ISSUE TITLE
Please enable INSTALL_QADDITIONAL_IO_PLUGIN in snap (edge channel)

### ISSUE THREAD

**Issue by eudoxos** [CloudCompare/CloudCompare#698]
## Current Behavior
https://github.com/CloudCompare/CloudCompare/issues/536 was fixed via new snap package in https://github.com/CloudCompare/CloudCompare/commit/ca6740a6ab8b61f842fb0e45b127a7fc4c297597 which enables numerous plugins; it seems that additional IO plugin (https://github.com/CloudCompare/CloudCompare/tree/master/plugins/qAdditionalIO) was left out incidentally.

## Expected Behavior
Snap package supports the widest range of IO formats which is practically possible.

## Steps to Reproduce (for bugs)
```
$ sudo snap refresh --edge cloudcompare
$ cloudcompare.CloudCompare
$ ls /snap/cloudcompare/186/lib/cloudcompare/plugins/
libQANIMATION_PLUGIN.so
libQBLUR_PLUGIN.so
libQBROOM_PLUGIN.so
libQCOMPASS_PLUGIN.so
libQCSF_PLUGIN.so
libQEDL_PLUGIN.so
libQFACETS_PLUGIN_DLL.so
libQGMMREG_PLUGIN.so
libQHOUGH_NORMALS_PLUGIN.so
libQHPR_PLUGIN.so
libQM3C2_PLUGIN_DLL.so
libQPCL_IO_PLUGIN.so
libQPCL_PLUGIN.so
libQPCV_PLUGIN.so
libQPHOTOSCAN_IO_PLUGIN.so
libQPOISSON_RECON_PLUGIN.so
libQSRA_PLUGIN.so
libQSSAO_PLUGIN.so
```

![pverror](https://user-images.githubusercontent.com/1029876/38159967-ab99727a-34b4-11e8-86d7-84b220f63216.png)

## Context/Comments
As far as I can see, adding -DINSTALL_QADDITIONAL_IO_PLUGIN to snap/snapcraft.yml (https://github.com/CloudCompare/CloudCompare/commit/ca6740a6ab8b61f842fb0e45b127a7fc4c297597#diff-5fde7a6d86053f0e1d88c0a2a238941f) should do the trick.

## Your Environment
* CC Version: 181 (snap, edge channel)
* OS & Version: Ubuntu 17.10
* Graphics card: ATI FirePro

**Comment by rjanvier** [comment]
Closed by cd35273
