### ISSUE TITLE
"Show name" on a ccHObject does not show name

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#699]
## Current Behavior
If I have a top-level object (ccHObject) containing several meshes, clicking the "Show name" checkbox of the top-level object does nothing.

## Expected Behavior
I would have expected that turning on "Show name" for a group would apply it to all things in the group (recursively).

## Steps to Reproduce (for bugs)
- open a model containing sub-objects
- select the top-level object
- click "Show name"
- none of the children's settings change

**Comment by dgirardeau** [comment]
No, actually you should see the group's name. I guess the code is missing :D

**Comment by asmaloney** [comment]
Two problems then:

1) `ccHObject::draw` at line 698:

```c++
	if (m_visible && drawInThisContext)
```
There is no "visible" property on the top-level object, so m_visible is false. Therefore `drawNameIn3D()` is not called for this object.

2) After working around that, the top-level object doesn't have a BBox to use for drawing. In `ccHObject::drawNameIn3D()`:
```c++
	ccBBox bBox = getOwnBB();
	if (!bBox.isValid())
		return;
```
