### ISSUE TITLE
How to use a plugin

### ISSUE THREAD

**Issue by fernandojunior** [CloudCompare/CloudCompare#700]
Hi,

I'm creating a plugin that needs some classes from qPCL plugin. So, is there a way to use or import a class from qPCL plugin as a dependency to my plugin?

Thanks.

**Comment by asmaloney** [comment]
As far as I know, not easily (except copying the files directly of course). We don't have anything for declaring plugin dependencies.

If it's for loading files, I think you can go through the static members on `FileIOFilter`, but in general there is no mechanism to "register" features (classes) that can be queried and accessed by other plugins.

I suppose you could share code by creating a dynamic library for the code and have both plugins link against it.

**Comment by fernandojunior** [comment]
Thanks for suggestion @asmaloney.

Suppose I've already created a dynamic library, how could I use it in my plugin? By referencing through CMakeLists.txt? I tried to reference using Visual Studio, but it didn't work.

**Comment by asmaloney** [comment]
Yes you would reference it in the CMakeLists.txt.

If you look at the source for *qLAS_FWF* it links to a library.

```
include( LASLibSupport.cmake )
...
target_link_LASLib( ${PROJECT_NAME} )
```

`LASLibSupport.cmake` describes how to find the library and headers (and what cmake options to add for this).

**Comment by fernandojunior** [comment]
Nice, Thanks!
