### ISSUE TITLE
Unnecessary error message at close

### ISSUE THREAD

**Issue by davidcaron** [CloudCompare/CloudCompare#701]
## Current Behavior
An error message appears when closing CloudCompare while using the _point picking_ tool.
![image](https://user-images.githubusercontent.com/16667564/38376881-9da98544-38c7-11e8-88f4-e3c1a341e882.png)

## Expected Behavior
The error message is unneeded.

## Steps to Reproduce (for bugs)
- Open a point cloud
- Open the _point picking_ tool
- Close CloudCompare while the tool is active

## Context/Comments
It's related to the Compass plugin by @samthiele 
https://github.com/CloudCompare/CloudCompare/blob/d736d31baf181ce1b06b9242efb7ccf5c96b34c7/plugins/qCompass/ccCompass.cpp#L529

## Your Environment
* CC Version: Latest alpha
* OS & Version: Windows 7 x64
* Graphics card: Nvidia Quadro K4200

**Comment by dgirardeau** [comment]
Ok that's fixed (6179295e6035b90df98b6f3143fb0b62289dae64).

Thanks for the feedback!
