### ISSUE TITLE
Show normal vectors of points cloud

### ISSUE THREAD

**Issue by DamonsJ** [CloudCompare/CloudCompare#704]
## Expected Behavior
**I think it is necessary to implement " show normals "  function.
I mean I can check normals of point cloud in cloudcompare**

**Comment by dgirardeau** [comment]
Wow ... could you be a little bit more explicit?

Because you can "show normals" ... if the cloud has some normals :D. And you can even compute them if it hasn't...

**Comment by DamonsJ** [comment]
I mean if point cloud has normals,you can show,if not ,you do nothing.
It just like what it does in meshlab.
Just show the point cloud's normals

**Comment by rjanvier** [comment]
Maybe I'm wrong but If you want to display/hide normals you can right click on the name of the entity entity (on the DB tree on the left of the scree) and then choose "toggle normals". Does it help?

**Comment by rjanvier** [comment]
Ok from this thread http://www.cloudcompare.org/doc/wiki/index.php?title=Normals%5CCompute I assume you want to display normal vectors isn't it?

**Comment by DamonsJ** [comment]
yes,i want to display normal vector and i try toggle normals,but nothing apparently happened.
I just mean show the normal vector with a arrow line,if the cloud has normals

**Comment by rjanvier** [comment]
Does the workaround provided meet your needs somehow?

**Comment by dgirardeau** [comment]
Well in this case I would even rename this issue "Show normals as vectors" :D.

**Comment by DamonsJ** [comment]
I do not  think the  workaround "Edit > Normals > Convert To > HSV colors" will help, I mean some time you need to check whether the normal direction is correct, so I think show normal as vectors is better, just my opinion. It is not hard to implement.

**Comment by rjanvier** [comment]
Nice! Pull request are welcome.

**Comment by SalDiAngelus** [comment]
I was looking at adding this feature, but the point cloud rendering code is a little convoluted. Would you guys be open to just using vertex buffers in the fixed function pipeline?

**Comment by dgirardeau** [comment]
We are open to any contribution that improves the current code base of course (we know that the legacy OpenGL framework that we currently use need to be 'modernized' but that's a huge work).

**Comment by SalDiAngelus** [comment]
Could you look at SalDiangelus/CloudCompare#1 to see if this is the direction you want to go in?

**Comment by rjanvier** [comment]
fixed by #1852
