### ISSUE TITLE
Debian package fails to build for some architectures

### ISSUE THREAD

**Issue by alexmyczko** [CloudCompare/CloudCompare#709]
Please find the build logs at
https://buildd.debian.org/status/package.php?p=cloudcompare

You might maybe not want to support one or another architecture (because you don't have it, or
can't even buy it anymore).

**Comment by rjanvier** [comment]
Thanks for the report Alex. No one in the core team have other thing than x86 gears so I’m afraid we can’t support other arch right now... things like arm64 would be good indeed. Help or hardware donation is welcome.

**Comment by sebastic** [comment]
Adding `-fsigned-char` to the compiler flags should fix [Debian Bug #896192 - cloudcompare FTBFS on architectures where char is unsigned](https://bugs.debian.org/896192)

**Comment by asmaloney** [comment]
Aside: Here's a great little summary of the `char`/`signed char`/`unsigned char` issue: [ARM chars are unsigned by default](http://blog.cdleary.com/2012/11/arm-chars-are-unsigned-by-default/)

**Comment by rjanvier** [comment]
It is odd, I couldn't reproduce this issue by using the aarch64-linux-gnu-g++ on Ubuntu 18.04 and compiling CCLib.

**Comment by alexmyczko** [comment]
i think the issue is fixed.
