### ISSUE TITLE
How to configure and genarate solution using CLI in Windows

### ISSUE THREAD

**Issue by fernandojunior** [CloudCompare/CloudCompare#712]
Hey!

I need to automate CloudCompare build in Windows 10. I'm trying to **Configure** and **Generate** a Visual Studio Solution using **CLI** instead of **cmake-gui**.

I can **Configure** via CLI by running:
```
cmake 
  -DOPTION_USE_VISUAL_LEAK_DETECTOR:BOOL="0"  
  -DQT5_ROOT_PATH:PATH="C:/Qt/5.10.1/msvc2017_64" 
  -DCMAKE_INSTALL_PREFIX:PATH="C:/Users/xxx/Workspace/CloudCompare/install"
  ..
```

And I know how to **Generate** the build using **make** in Linux, but how could I Generate a Visual Studio Solution via CLI in Windows 10?

Ty!

**Comment by rjanvier** [comment]
You need to tell to cmake to use a generator for Visual Studio with the `-G` option. type `cmake -G` to see generators available for your plateform

**Comment by dgirardeau** [comment]
And to 'make' (compile) the solution with Visual you should use nmake or MSBuild I believe?

**Comment by fernandojunior** [comment]
Thanks @rjanvier, it works!

```
cmake
  -G "Visual Studio 15 2017 Win64"
  -DOPTION_USE_VISUAL_LEAK_DETECTOR:BOOL="0"
  -DQT5_ROOT_PATH:PATH="C:/Qt/5.10.1/msvc2017_64"
  -DCMAKE_INSTALL_PREFIX:PATH="C:/Users/xxx/Workspace/CloudCompare/install"
  ..
```

Now, I need to compile the solution. I'll try the @dgirardeau suggestions.

**Comment by fernandojunior** [comment]
Hey @dgirardeau 

I compiled the solution using MSBuild. Thanks!

After **Configure** and **Generate** using cmake, compile the INSTALL project from CloudCompare Visual Studio Solution:

```bat
cd CloudCompare\build
msbuild "INSTALL.vcxproj"
```

or

```bat
cd CloudCompare\build
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\MSBuild" "INSTALL.vcxproj"
```
