### ISSUE TITLE
Reading Error Occurs During Loading

### ISSUE THREAD

**Issue by Fathomers** [CloudCompare/CloudCompare#732]
## Current Behavior
When attempting to open a file, I receive the error message: "An error occurred while loading 'filename': reading error (no access right?)

## Context/Comments
The "reading error (no access right?)" is what has me confused. Has anyone else had experience with this? Any suggestions on how to access my files would be greatly appreciated.

## Your Environment
* CC Version: 2.9.1 [64-bit]
* OS & Version: macOs High Sierra Version 10.13.4
* Graphics card: Radeon Pro 560 4096 MB, Intel HD Graphics 630 1536 MB

**Comment by asmaloney** [comment]
- What kind of file is it?
- Is it on a local or network drive?
- Are you sure you have read access on the file? (check with command line using `ls -l <filename>`)

**Comment by Fathomers** [comment]
- It is *.las
- I've pulled it form Dropbox and also downloaded it to my desktop
- I've confirmed that I do have read access

The files I'm trying to load range from 60 MB to 7.5 GB. I'm able to successfully load files up to 1.36 GB, but run into this problem at about the 2 GB range.

**Comment by asmaloney** [comment]
That sounds suspiciously like a 32-bit integer maximum (2,147,483,647 bytes).

The code is using `std::ifstream` which I'm not familiar with. I'll have to look at it to see if it's limited to 32-bit integers somehow.

Would it be possible to get one of those files that is failing from you (one that's about 2 GB)? (You can find my email in my GitHub profile.)

**Comment by Fathomers** [comment]
asmaloney—thanks. I'll follow-up via email.

**Comment by asmaloney** [comment]
Please reopen if the problem still exists and you have an example file we can work with.
