### ISSUE TITLE
CC v2.9.1 doesn't exit cleanly in Win7

### ISSUE THREAD

**Issue by vernzimm** [CloudCompare/CloudCompare#734]
Greetings,

I think this has been an issue, but I don't see it open currently. When I close ("X" button) the CC window, (and click "OK" on confirmation message), I still see cloudcompare.exe in Process Viewer. In a previous version of CC (several months ago), the program would crash on exit. That has be solved as of v2.9.1, but I suspect the solution created this new issue. I am unsure if they eventually leave, but often I will have 6-8 cc.exe's still hanging around.

CC: v2.9.1
OS: Win7 Pro SP1
Graphics: nVidia Quadro M2000

P.S. email address is not correct in the instruction text for this window...
`<!--- If you are reporting a security issue, please email security@cloucompare.org directly -->`

**Comment by asmaloney** [comment]
I fixed the email address in the issue template. Thanks @vernzimm!
