### ISSUE TITLE
Error to load pcl io plugin after build release

### ISSUE THREAD

**Issue by Mun1z** [CloudCompare/CloudCompare#736]
I have a problem when compiling the cloud compare in release version and I put it to run on a machine that does not have the sdk of pcl installed it error loading the plugins that depend on pcl io, has anyone had a similar problem?

![error](https://user-images.githubusercontent.com/17263249/39719434-91460780-520f-11e8-86d6-ca5220cc441c.png)

**Comment by dgirardeau** [comment]
It's probably because the PCL DLLs are missing (either in the system PATH or in the CloudCompare directory). You can use Dependency Walker (on your own plugin DLL) to find which DLLs are missing.

**Comment by dgirardeau** [comment]
It's because when I compile it, I use static versions of the PCL libraries. So as to avoid having to redistribute the DLLs... Maybe you should keep the official version of CC ;)

**Comment by Mun1z** [comment]
How do you use this static version of pcl? the only thing I want is to add a new plugin in cc and generate an installer that already comes with the plugin inserted.
Sorry for the double post, I thought github would have more users than the forum.

**Comment by Mun1z** [comment]
Do you mean this configuration in projects? to change from dynamic to static?

![status](https://user-images.githubusercontent.com/17263249/39721099-bc688082-5214-11e8-9405-e5e44f8217ef.png)

**Comment by dgirardeau** [comment]
Nope you have to set the right PCL libraries in CMake (during the configuration of the project). This is not specific to CloudCompare, it's a standard compilation/linking mechanism.

Your version of CC probably lacks a lot of other plugins... It would be simpler to compile your plugin with the same tools as myself (Visual 2017 / Qt 5.9.3), and the create an additional installer that copies your plugin in the 'plugins' folder of CC (which is almost always the same...).

**Comment by Mun1z** [comment]
Is your installer generation script updated here in the repository? why there in the script that you passed me before it is using visual studio 2013 to compile and not the 2017, I used version 5.10.1 of qt, I will try to use the same as you then.

**Comment by dgirardeau** [comment]
I don't change the paths on the repository as it only depends on the local files (I only change it if the 'logic' changes).

**Comment by franklinwesley** [comment]
I have a similar problem, i'm trying to create an installer in release with only QPCL plugin, however the QPCL_IO does not load but the QPCL loads normally, I can even do operations on a point cloud but I can not import .pcd files. From what I've read, the problem may be some PCL DLL missing, but how to know which one? Since the QPCL works normally. 
Observation: In the machine that I generate the build works normally, but on another machine without the installed PCL does not work. But if I install the official version of CC the QPCL_IO works

CMake 3.11.0
PCL 1.8.1
VIsual Studio 15 2017
CloudCompare v2.9.1
Qt 5.10.1
Windows 10

CC error
<img width="931" alt="capturar" src="https://user-images.githubusercontent.com/5850409/39760793-ae1900cc-52ac-11e8-9010-5d64f858be8e.PNG">

CMake configuration
![image](https://user-images.githubusercontent.com/5850409/39760884-f32b631c-52ac-11e8-97f0-1aef80aa673b.png)
![image](https://user-images.githubusercontent.com/5850409/39760916-128d678c-52ad-11e8-83bd-fd67f99c68ae.png)

**Comment by asmaloney** [comment]
> the problem may be some PCL DLL missing, but how to know which one?

You can use [Dependency Walker](http://www.dependencywalker.com/) to find dynamic libs that are missing. After you've run your installer (on the non-build machine), look at the QPCL_IO plugin with Dependency Walker - it should show you what libs are missing.

Just to be clear - the CloudCompare code you're compiling is from the `2.9.1` tag, not `master`, correct?

**Comment by Mun1z** [comment]
I tried compiling the master version in release mode using vs 2017 with qt 5.9.3 had the same problem.

![error2](https://user-images.githubusercontent.com/17263249/39763323-2df50e3e-52b3-11e8-9952-e148d72e7071.png)

**Comment by dgirardeau** [comment]
In this case, you just need to copy your plugin DLL in the 'plugins' folder of the official version. Regarding why it doesn't work on your side, as said several time, you'll need to use Dependency Walker to determine which DLL is missing on your side...

**Comment by Mun1z** [comment]
In the machine in which I compile it works perfectly, when I move to another machine it is that the problem occurs.

![teste](https://user-images.githubusercontent.com/17263249/39763477-8cb462a8-52b3-11e8-9bfd-3079947ccdd8.png)

**Comment by Mun1z** [comment]
Daniel, I tried to put the plugins that I compiled in the plugins folder of your version, the same problem occurred.

![error3](https://user-images.githubusercontent.com/17263249/39763942-cefda59c-52b4-11e8-8bfb-b43a219da898.png)

The plugins that come in the installation of your release work, it can not be a problem with dll missing on the machine, but some problem in my way of compiling the release, but I do not know what can be, I followed all the steps of your build document.

![error4](https://user-images.githubusercontent.com/17263249/39764058-1e91f040-52b5-11e8-8d63-7758aaa121bc.png)

**Comment by dgirardeau** [comment]
Of course if your plugin also rely on PCL, you'll need to setup the PCL libraries right (i.e. with static versions only...).

**Comment by Mun1z** [comment]
Could you please explain better how I use the static version of pcl to compile CC?

**Comment by franklinwesley** [comment]
@asmaloney, i compile CC code from v2.9.1 tag. I used the Dependency Walker in oficial version CC and in my compilation of the CC, and there was no difference. I'm sending the 2 outputs in CSV. I have no idea what's missing

[QPCL_IO_PLUGIN.zip](https://github.com/CloudCompare/CloudCompare/files/1984442/QPCL_IO_PLUGIN.zip)

**Comment by asmaloney** [comment]
@franklinwesley Make sure you're running Dependency Walker on the machine you're installing to (the one that's not working), not your build machine. I don't know how to read (understand) those CSVs - I've only ever used the interface which highlights problems in red.

This is why Daniel links PCL as a static lib - so he doesn't have to track down and include all the dependencies (there are many IIRC).

**Comment by dgirardeau** [comment]
By the way in your CMake view, you are showing us the include directories of PCL :|

The libraries are the interesting part :D

**Comment by Mun1z** [comment]
I understand, I think the problem will be the same PCL, I'm trying to compile here to get the static version, would not you like to make them available already compiled?

**Comment by franklinwesley** [comment]
I installed the PCL following this blog http://unanancyowen.com/en/pcl181/. I will try to compile the PCL and see if it solves. Thanks for the tips
