### ISSUE TITLE
Poisson Reconstruction of large clouds - Memory issues

### ISSUE THREAD

**Issue by rukie** [CloudCompare/CloudCompare#737]
## Current Behavior
Poisson Reconstruction works great up to level 10 Octree depth. After 10, memory issues abound. Application crashes due to windows running low on memory.

## Expected Behavior
Expect application to create a surface.

## Steps to Reproduce (for bugs)
Import point cloud with x,y,z and nx,ny,nz data
Generate poisson surface mesh with a 53 million (53,501,749) point point cloud.
Use an octree depth of 12 or greater. Use a "hybrid" octree of 11 or greater.

## Context/Comments
Is there a method to handle high memory calculations?
I need more detail on the terrain surface (1 cm) on a 400x400 meter area.

## Your Environment
CC 2.9.1
Windows 10
64 gb memory

**Comment by dgirardeau** [comment]
Hum, there's no particular option in CloudCompare.

But note that the plugin is just a wrapper on the PoissonRecon library (https://github.com/mkazhdan/PoissonRecon), therefore you might ask this to the author directly.
