### ISSUE TITLE
Logo for CloudCompare

### ISSUE THREAD

**Issue by linadesteem** [CloudCompare/CloudCompare#742]
Hello, I am a graphic designer, and I see your project does not have logo. I think I can make one for your project.

![cloud1](https://user-images.githubusercontent.com/35618068/39968997-f936d398-56ff-11e8-9543-3e460eec06c4.png)
![cloud2](https://user-images.githubusercontent.com/35618068/39968998-f9afa304-56ff-11e8-8581-115d7aa3d635.png)

What do you think? do you like any of those? if you like it I will send you a pull request with svg file

**Comment by dgirardeau** [comment]
Thanks for the offer!

While we aren’t opposed to changing things up, we found that this logo doesn’t really represent this project. CloudCompare is software for working with 3D point cloud data and this feels more like it represents some kind of cloud-based software or website.

And even if it's not as nice as your own creation we already have a kind of logo:
https://github.com/CloudCompare/CloudCompare/blob/master/qCC/images/icon/cc_icon_256.png

Thanks again for the suggestion anyway.

**Comment by linadesteem** [comment]
no problem. let me know if you need any graphic design in the future :)
