### ISSUE TITLE
OpenGL Quad Buffer Stereo (NVidia 3D Vision)

### ISSUE THREAD

**Issue by saedrna** [CloudCompare/CloudCompare#743]
## Context/Comments
First, this is not issue about CloudCompare, but a general question about the QBS (Quad Buffer Stereo) for NVidia 3D Vision using Qt to develop my own rendering pipeline. Because 3D Vision is an almost obselete technique and terribly documented, CC is the only place that I found a working software using Qt+OpenGL+QBS. So I'm sorry if this is the wrong place to post this question.

I am using ```QOpenGLWidget``` to do the rendering in Qt and I have read related parts of ```CCGlWindow.cpp```. It seems that I only have to call ```glDrawBuffer(GL_BACK_LEFT)``` and ```glDrawBuffer(GL_BACK_RIGHT)``` before drawing the two frames.

However, this does not work for me. I have encountered the following unexpceted problems,
- ``'glGetBooleniv(GL_STEREO, is_supported)'`` returns false
- ```glDrawBuffer(GL_BACK_LEFT)``` raises GL_INVALIDE_OPERATION

I am quite sure, that I have made the monitor and NVIDIA Settings correct, because I have successfully running CC in stereo.

## Your Environment
* CC Version: 2.9.1 Stereo
* OS & Version: Win 10, 1803 / 17134.1
* Graphics card: Nvidia Quadro P4000

Thanks,

Han

**Comment by dgirardeau** [comment]
You have to initialize the OpenGL context with double buffering and stereo support. See how this is done in main.cpp (in the custom Qt application).

**Comment by dgirardeau** [comment]
See https://github.com/CloudCompare/CloudCompare/blob/master/qCC/ccApplication.cpp#L50

**Comment by saedrna** [comment]
In fact, I have already done this, and the format().stereo() returns true.

I think the difference is in the macro CC_GL_WINDOW_USE_QWINDOW, which uses QWindow rather than qopenglwidget. Is this related to the stereo mode?

**Comment by saedrna** [comment]
I have comfirmed that this is the problem between QWindow and QOpenGLWidget, QWindow is good for me. Although I have no idea why this is the case, using QWindow as the rendering target solves my problem.
