### ISSUE TITLE
deprecated use of qt5_use_modules

### ISSUE THREAD

**Issue by dcanelhas** [CloudCompare/CloudCompare#747]
## Current Behavior

compilation errors. cmake does not generate makefiles

instead of 
```cmake
qt5_use_modules(${target_name} module_a module_b)
```
do
```cmake
target_link_libraries(${target_name} Qt5::module_a Qt5::module_b)
```
to resolve issue

## Steps to Reproduce (for bugs)
attempt configuration /  generation using Qt 5.11 (or newer)

## Your Environment
* CC Version: 2.10-alpha
* OS & Version: Arch Linux x86_64 (4.16.12-1-ARCH May 25 2018)
* Graphics card: n.a.

**Comment by rjanvier** [comment]
Your are right, it's deprecated since QT 5.11. Do you want to make a pull request with those changes?

**Comment by dgirardeau** [comment]
Can you make a #ifdef test based on the version of Qt. And keep the old code for versions prior to 5.11 (or would it work also for 5.9 for instance?)

Because Qt 5.9 is the LTS version...
