### ISSUE TITLE
No qCANUPO plugin found in CloudComare/plugins folder

### ISSUE THREAD

**Issue by hajlyx** [CloudCompare/CloudCompare#749]
The qCANUPO plugin does exist in latest stable release (2.9.1 Omnia), but I couldn't find it in CloudCompare/plugins folder which is cloned from github

**Comment by asmaloney** [comment]
The source code for that plugin is not (yet?) open source which is why you won't find it in the GitHub repo.

**Comment by dgirardeau** [comment]
Indeed the code is still not open source. We should ask again to the user.
