### ISSUE TITLE
octree_normals (commandline) does not respect auto_save off

### ISSUE THREAD

**Issue by dcanelhas** [CloudCompare/CloudCompare#752]
## Current Behavior
computing octree normals using commandline interface produces a ```<filename>_OCTREE_NORMALS_<timestamp>.bin``` file regardless of the -AUTO_SAVE option being set to ON or OFF

## Expected Behavior
There should be no files written to disk, except when SAVE_CLOUDS or SAVE_MESHES is popped out of the command queue

## Steps to Reproduce (for bugs)
```bash
./CloudCompare -SILENT -O bunny70k.sbf -AUTO_SAVE OFF -OCTREE_NORMALS 0.1 -SAVE_CLOUDS
[LOADING]
Opening file: 'bunny70k.sbf'
Found one cloud with 34834 points
Auto-save is disabled
[OCTREE NORMALS CALCULATION]
	Radius: 0.1
computeNormalsWithOctree started...

computeNormalsWithOctree success
cloud->hasNormals: 1
[SAVING]
[SAVING]
Processed finished in 1.32 s.
```
(the -SILENT flag has no impact on this)

## Your Environment
* CC Version: 043be476e2c5ed9ba12663e9d871ba1c59a7464f
* OS & Version: n.a.
* Graphics card: n.a.

**Comment by dgirardeau** [comment]
Ok that's fixed (966753806ff25f65f6f53c9e7b5e6da78505d589).

Thanks for the feedback.
