### ISSUE TITLE
CloudCompare immediately crashes upon rendering in qAnimation plugin (MAC OSX HIGH SIERRA)

### ISSUE THREAD

**Issue by TheOrdinaryMan** [CloudCompare/CloudCompare#755]
## Current Behavior

Currently on my Macbook Pro, I am trying to render an animation of a point cloud flythrough, however when I click the render button it immediately crashes with no error message or pop-up window.

## Expected Behavior

Animation should render.

## Steps to Reproduce (for bugs)
 Set up an animation with 2 or 3 viewpoints inside a point cloud(or even without a point cloud, click render, immediate crash.

## Context/Comments

I am trying to create flythroughs of various point clouds.

The following logs were generated in console when trying to make the animation.

default	17:01:57.279890 -0400	lsd	SecTranslocateCreateSecureDirectoryForURL: created /private/var/folders/30/tr7gjpn14yg459_9cmf3cgdw0000gn/T/AppTranslocation/92107FDB-AD40-400A-80D6-BFEC4DE06787/d/CloudCompare.app
default	17:01:57.672225 -0400	kernel	AGC:: [CloudCompare pid:26202 mux-aware] starting, non-mux-aware app count 1 WS-ready 1 switch-state 0 IG FBs 0 EG FBs 1:f power-state 0 3D idle HDA idle
default	17:01:57.672363 -0400	kernel	AGC:: [CloudCompare pid:26202 non-mux-aware] starting, non-mux-aware app count 2 WS-ready 1 switch-state 0 IG FBs 0 EG FBs 1:f power-state 0 3D idle HDA idle
error	17:01:57.883949 -0400	CloudCompare	        AEGetDescData of non-desc type 'reco' not a good idea
default	17:02:19.702662 -0400	kernel	AGC:: [CloudCompare pid 26202 non-mux-aware] exiting, non-mux-aware app count 1, runtime: 0:00:22.031
default	17:02:19.702916 -0400	kernel	AGC:: [CloudCompare pid 26202 mux-aware] exiting, non-mux-aware app count 1, runtime: 0:00:22.031
default	17:02:24.780697 -0400	lsd	SecTranslocate: problem deleting translocation after app death: /private/var/folders/30/tr7gjpn14yg459_9cmf3cgdw0000gn/T/AppTranslocation/92107FDB-AD40-400A-80D6-BFEC4DE06787/d/CloudCompare.app

Full crash logs:
[CloudCompare_crash.zip](https://github.com/CloudCompare/CloudCompare/files/2072914/CloudCompare_crash.zip)

## Your Environment
* CC Version: Version 2.9.1 Mac OS 64 bit
* OS & Version: High Sierra 10.13.4
* Graphics card: NVIDIA GeForce GT 650M 1024 MB
Intel HD Graphics 4000 1536 MB

MacBook Pro Mid 2012

**Comment by asmaloney** [comment]
Can you please attach the crash log (the one macOS brings up when a program crashes)?

Maybe it's related to this translocation stuff somehow? I don't fully understand how the translocation is supposed to function (i.e. when does the Finder "turn it off").

**Comment by asmaloney** [comment]
From Apple:

"Starting with macOS Sierra, running a newly-downloaded app from a disk image, archive, or the Downloads directory will cause Gatekeeper to isolate that app at a unspecified read-only location in the filesystem. This will prevent the app from accessing code or content using relative paths."

Not 100% clear to me what that last part means and I don't know how to "fake it" for testing.

**Comment by TheOrdinaryMan** [comment]
[CloudCompare_2018-06-05-085136_Aidans-MacBook-Pro-2 copy.crash.zip](https://github.com/CloudCompare/CloudCompare/files/2072426/CloudCompare_2018-06-05-085136_Aidans-MacBook-Pro-2.copy.crash.zip)

Just crashed it. Two viewpoints, no point cloud at all, clicking render was immediate crash

**Comment by TheOrdinaryMan** [comment]
Disabling gatekeeper does not fix this issue.

**Comment by asmaloney** [comment]
I ran into a "translocation" issue like this in another project. What I had to do was drag the .app to another location, and then drag it back.

Sounds crazy, but I think this "resets" some bit in the Finder for the application to run where it is instead of from some random directory (which breaks relative paths).

**Comment by asmaloney** [comment]
Someone else reported a crash in ffmpeg's libavcodec.57.dylib.

I could never reproduce it, but I am now compiling my own ffmpeg lib (instead of using homebrew's) and statically linking to it. The other reporter said it works for him.

Please try 2.10.2 and reopen if this is still an issue.
