### ISSUE TITLE
What's the method of "Space" subsampling?

### ISSUE THREAD

**Issue by githubfragments** [CloudCompare/CloudCompare#756]
Hello, do you know what is the method of "Space" subsampling? The document says it is a kind of spatial subsampling. Do you know which algorithm for this spatial subsampling? And is there any reference papers? 
![image](https://user-images.githubusercontent.com/16164389/41075291-9062fdc2-6a3e-11e8-9a4c-123084fe731d.png)
![image](https://user-images.githubusercontent.com/16164389/41075304-9dccf0ee-6a3e-11e8-9195-d89888e32b34.png)

**Comment by dgirardeau** [comment]
Duplicate with #757

**Comment by githubfragments** [comment]
Thank you!
