### ISSUE TITLE
Load .PLY as pointcloud fails

### ISSUE THREAD

**Issue by cnovel** [CloudCompare/CloudCompare#760]
I have pointclouds saved in PLY format, ie `element vertex 214138` and `element face 0`

## Current Behavior
The import fails: "An error occured while loading 'pointcloud': nothing to load"

## Expected Behavior
The points and some attributes (normal, color, etc.) should be loaded as a pointcloud.

## Steps to Reproduce (for bugs)
This is what my header looks like
```
ply
format binary_little_endian 1.0
element vertex 214138
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float weight
property float intensity
property float sampling
property uchar type
property list uchar int view
element face 0
property list ushort int vertex_indices
end_header
```

## Context/Comments
I assume this has something to do with the header, but I can't figure out what's wrong.

## Your Environment
* CC Version: 2.9.1
* OS & Version: Windows 10
* Graphics card: Nvidia GTX 1060

**Comment by dgirardeau** [comment]
Can you share the file with us?

**Comment by asmaloney** [comment]
Please reopen if the problem still exists and you have an example file we can work with.
