### ISSUE TITLE
construction of ChunkedPointCloud exception

### ISSUE THREAD

**Issue by zihahage** [CloudCompare/CloudCompare#764]
## Current Behavior
I downloaded latest version 2.10 alpha and compiled it with nothing changed, neither the source code, nor the  cmake files. After compilation, i tested the new version and found a problem. 

When i am trying to segment a mesh with corss section function, my application falls. While debugging i see that problem lies in "ChunkedPointCloud* insideVertices1 = new ChunkedPointCloud;", 
in constructor of ChunkedPointCloud in ChunkedPointCloud.cpp. The error is "0xC0000005: Access violation reading location 0x0000000000000004", as you can see from screenshot below. I searched google and found the same problem others encountered: http://www.danielgm.net/cc/forum/viewtopic.php?t=3052.

I downloaded compiled installer version of 2.10 alpha and tested the same manipulation, it worked fine. In order to keep same with installer version of 2.10 alpha, i also compiled it with VS2017 and QT5.9.3, but the problem still exists. So is there anything i missed?

Thank you for your help!

![bugreport](https://user-images.githubusercontent.com/16953542/42304633-cec3cfc0-8059-11e8-9675-1a5f2e999a28.png)

## Your Environment
* CC Version: 2.10 alpha
* OS & Version: Win7
* Graphics card: NVIDIA GTX650

**Comment by dgirardeau** [comment]
Indeed, this old architecture makes Visual 2015 and 2017 crash...

You need to use the 'Simplification' (https://github.com/CloudCompare/CloudCompare/tree/Simplifcation) branch that fixes this issue. It will be merged very soon with the master branch.
