### ISSUE TITLE
Rasterize height export not respecting global shift

### ISSUE THREAD

**Issue by qume** [CloudCompare/CloudCompare#767]
Whe creating a projected height raster, the resulting TIFF file is offset by the global offset in height. X and Y are correct.

Open a pointcloud with an offset, go to projection -> rasterize. Choose a cell size, then set to MINIMUM HEIGHT. Save a raster with no SF fields. Compare the raster heights to the pointcloud, and the heights will be offset by the global offset amount in height, and be in the original pointcloud position for X and Y.

Version 2.9.1 64 bit

**Comment by dgirardeau** [comment]
Okay I fixed this (974261f0b52cf02c7d89cd1ac5ab3c9be0477aac). I finally understood that the raster generation was separated from the cloud and contour lines generation. This explains why the rasters were not shifted (at least I hope so ;).

I have updated the 2.10.alpha online version.
