### ISSUE TITLE
Ubuntu snap and CC command line

### ISSUE THREAD

**Issue by balazsdukai** [CloudCompare/CloudCompare#769]
I would like to call CC from the command line as it is described in the [documentation](https://www.cloudcompare.org/doc/wiki/index.php?title=Command_line_mode). However, the `CloudCompare` command is not available. With the snap install, I have two commands `cloudcompare.CloudCompare` and `cloudcompare.ccViewer`, both launching the respective GUI application. 

The bigger picture is that I want to point-to-mesh distances on several individual meshes, thus I have a python script to call CC for each mesh. To give you an idea:
```bash
CloudCompare -silent -c_export_fmt asc -auto_save off -o PC_FILE -crop2d Z NR_COORDS COORDS -o FOOTPRINT -match_centers -c2m_dist -save_clouds -clear
```
## My Environment
* CC Version: 2.10-beta (snap)
* OS & Version: Ubuntu 16.04 LTE

**Comment by dgirardeau** [comment]
Have you tried to call ```cloudcompare.CloudCompare -silent -etc.```?

Because the GUI mode and the command line mode are just two modes of the same application. It's just that if some strings are appended after the program name, then it automatically switches to the command line mode.

**Comment by alexmyczko** [comment]
Care to try the ubuntu cloudcompare package? I successfully rebuild it for 16.04 (internally), and that works fine (without snap):

$ dget http://http.debian.net/debian/pool/main/c/cloudcompare/cloudcompare_2.9.1+git20180223-1.dsc
$ dpkg-source -x *.dsc
$ cd cloudcomp*/
$ debuild

# cd ..
# dpkg -i cloud*.deb
