### ISSUE TITLE
Face recognition with Realsense D415 Camera...

### ISSUE THREAD

**Issue by atiato** [CloudCompare/CloudCompare#770]
The RealSense D415 camera has been shown to work for facial recognition purposes with open source software called CloudCompare.

Can you please provide C++ or C# sources/examples used for that ?

Thanks,
Omar Atia

**Comment by dgirardeau** [comment]
There must be a misunderstanding somewhere. CloudCompare has no facial recognition capability, no link to Intel (sadly!) or to the D415 camera. If someone developped a plugin to do that, we are not aware of it.
