### ISSUE TITLE
After poisson reconstruction, export new mesh by "Filter by Value" takes much longer time

### ISSUE THREAD

**Issue by zihahage** [CloudCompare/CloudCompare#773]
## Current Behavior
After poisson reconstruction, export new mesh by "Filter by Value" takes much longer time.

## Expected Behavior
I remember it takes only seconds in earlier version.

## Steps to Reproduce (for bugs)
I loaded a point cloud with more than 3 million points and meshed it by poisson surface reconstruction plugin with 'output density as SF' checked. When i tried to reduce the extents of the output mesh with 'Filter by value', CC hanged and did not respond. Later I segmented the mesh and tested with less faces, it took about 3 minutes to export new mesh.

## Your Environment
* CC Version: 2.10.alpha - 07/28/2018
* OS & Version: Win7 enterprise
* Graphics card: NVIDIA GTX650

**Comment by dgirardeau** [comment]
Yes indeed! I fixed the bug (110154e57e1424458e9e8c30fae4eb540a7600f7).

I also updated the latest 2.10.alpha version online. Thanks for the feedback!
