### ISSUE TITLE
the error of compiling the plugin 

### ISSUE THREAD

**Issue by zhuangleilei** [CloudCompare/CloudCompare#775]
hi, I hava a problem while comiling my plugin. I have compiled the source code of CC 2.9.1 using visual studio 2013 Win 10, and I also compiled the plugin template qDummyPlugin successfully. But when I add the opencv lib to the project of qDummyPlugin , the error came. The following is the errors:
Unresolved external symbol “void_cdecl cv::fastFree(void*)” ....

I have configure the opencv lib correctly, but it can not work. Thank you for your answer.

**Comment by zhuangleilei** [comment]
@dgirardeau I added the Opencv to the QDUMMY_PLUGIN project by modifying the property sheet file in the visual studio 2013. And I confirm that this way is right because the other projects work using the property sheet file. Maybe the generated CC sln cannot be configured by modifying the property sheet?

**Comment by zhuangleilei** [comment]
@dgirardeau I added the Opencv lib to the QDUMMY_PLUGIN project using cmake later, and it works. Thank you for your reply. But I want to know why the method of modifying the project's property sheet cannot work? Do you know ?

**Comment by dgirardeau** [comment]
This is because CMake manages everything (include folders, libraries, etc.) and updates the project whenever something changes in the configuration, etc. If you modify the project yourself, there's a good chance that your modifications will be discarded the next time CMake updates the project files.
