### ISSUE TITLE
Save as PCD adding random scalar fields

### ISSUE THREAD

**Issue by jefft255** [CloudCompare/CloudCompare#776]
Hi,

First, my system Info:
-Ubuntu 18.04
-Snap edge channel (so 2.10 alpha) because it's the easy way to get PCL support on Ubuntu
-GTX 1070 (although I don't think it's very relevant to this issue)

My problem has to do with saving PCD files. Random scalar fields with name "_", type U, size 1 and count 12 are added to my point cloud and this makes it go up in size quite a bit.

To highlight this issue, one can simply open a PCD file with scalar fields in CloudCompare and then save it. With one of my point clouds, the size will go up twofold!

Here is the PCD header before saving with CC:
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z intensity ring stamps_Msec stamps_sec stamps_nsec normal_x normal_y normal_z densities simpleSensorNoise observationDirections probabilityStatic probabilityDynamic dynamic_ratio
SIZE 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
TYPE F F F F F F F F F F F F F F F F F
COUNT 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1
WIDTH 5869007
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 5869007
DATA binary
```

Here is the PCD header of the same file after saving with CC:
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS dynamic_ratio _ probabilityDynamic _ probabilityStatic _ observationDirections _ simpleSensorNoise _ densities _ stamps_nsec _ stamps_sec _ stamps_Msec _ ring _ intensity _ normal_x normal_y normal_z _ x y z _
SIZE 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 4 4 1 4 4 4 1
TYPE F U F U F U F U F U F U F U F U F U F U F U F F F U F F F U
COUNT 1 12 1 12 1 12 1 12 1 12 1 12 1 12 1 12 1 12 1 12 1 12 1 1 1 4 1 1 1 4
WIDTH 5869007
HEIGHT 1
VIEWPOINT 0 0 0 0.707107 -0.707107 0 0
POINTS 5869007
DATA binary
```

Also the fields are inverted which is irritating. For some reason the viewpoint is also changed, although this does not affect me. Note that I can reload the saved point cloud in CC and these field do not appear in the SF list. I does not corrupt the cloud in any way. I have no clue about what could be causing this, except maybe data padding in memory for SIMD optimization, though this is unlikely because my scalar fields are all 32 bit in size and it would be insane to use this much padding. I can send you the point cloud in private if necessary.

Thank you for looking into it and un gros merci for all the hard work put into CloudCompare!

**Comment by dgirardeau** [comment]
In the end, what was the conclusion? Is it something made by PCL automatically? (I guess so as we use PCL to generate PCD files).

**Comment by jefft255** [comment]
Yes, this is not a CloudCompare issue. It happens when you save a PCLPointCloud2. To fix this issue one must use a custom PCL point type but this is impossible for CloudCompare because you need to know the scalar fields at compile time.
