### ISSUE TITLE
Cannot load mesh file from outside the home folder (Ubuntu snap)

### ISSUE THREAD

**Issue by christian-rauch** [CloudCompare/CloudCompare#778]
## Current Behavior

When drag&drop a mesh file from a folder outside of the user's home directory (`/home/$USER`), e.g. `/opt/`, CloudCompare fails to load the file with the message: `[Load] File '/opt/[...].stl' doesn't exist!`. The message is obviously wrong since the file indeed exists.

## Expected Behavior
When selecting a file from the home directory, this works as expected.

## Steps to Reproduce (for bugs)
- install CloudCompare under Ubuntu from the snap store
- open CloudCompare
- drag&drop a mesh file from somewhere in `/opt`

## Context/Comments

I assume this issue results from the confinement in the snap package format.
I would suggest providing up-to-date builds in the ppa `ppa:romain-janvier/cloudcompare`, which worked flawlessly before, or provide a flatpak package on `https://flathub.org/home`. This would probably also solve the theming issues.

## Your Environment
* CC Version: cloudcompare 2.10-beta (Ubuntu snap store)
* OS & Version: Ubuntu 14.04
* Graphics card: -irrelevant-

**Comment by christian-rauch** [comment]
The `cloudcompare` package was just added recently (2018-05-07). I doubt it will be released in the official repos for any of the Ubuntu LTS versions.

**Comment by alexmyczko** [comment]
True but I have backported packages for 18.04 LTS for my workplace and it works just fine.

**Comment by christian-rauch** [comment]
Since the ppa packages without confinement work just fine too, I assume that this issue is related to the snap packaging. There is also a cloudcompare flatpak in the deepin repo: https://xn--deepinenespaol-1nb.org/en/comunidad/aplicaciones-y-mas/llegan-las-aplicaciones-flatpak-a-la-tienda-de-deepin/#post-274 but this is maybe too much to setup just for a single program.

I think it would be better if the issues in the snap get resolved or if the ppa gets updated with newer versions of cloudcompare and Ubuntu.

**Comment by oscarmendezm** [comment]
This is happening to me too. I can't seem to install from universal (as @alexmyczko suggests) since that requires libc6 >=2.27, and 16.04 has 2.23 as the latest.

**Comment by alexmyczko** [comment]
@oscarmendezm Iwas suggesting backporting it, that means take the source package and built it on target system. Works for me.

**Comment by muzo583** [comment]
this command works well.

`sudo snap connect  cloudcompare:removable-media  :removable-media
`

**Comment by christian-rauch** [comment]
@muzo583 Thanks for that hint. Indeed this permission has to be granted manually.

You can also do this via the "Ubuntu Software" application:
![Screenshot from 2019-07-17 15-54-51](https://user-images.githubusercontent.com/8226248/61385938-427ef000-a8ab-11e9-929d-2c1adeb127c5.png)
There is a bug that will always show the permission as OFF after opening the menu again, but `snap connections cloudcompare` will verify that it is connected:
`removable-media  cloudcompare:removable-media  :removable-media  manual`

It would be nice, if this could be granted automatically or if it asks for permission if a file from a mounted drive openned.

**Comment by martinakos** [comment]
I have this problem and I've tried running `sudo snap connect  cloudcompare:removable-media  :removable-media`   but has no effect. running `snap connections cloudcompare` shows:
```
Interface        Plug                          Slot              Notes
home             cloudcompare:home             :home             -
mir              cloudcompare:mir              -                 -
opengl           cloudcompare:opengl           :opengl           -
removable-media  cloudcompare:removable-media  :removable-media  manual
unity7           cloudcompare:unity7           :unity7           -
x11              cloudcompare:x11              :x11              -
```
and I've enabled and disabled the permission switches to no effect. 
I'm in Ubuntu 18.04 and CC is v2.10.1 
Any suggestions? I have all my data in a mounted drive

**Comment by christian-rauch** [comment]
I am closing this issue since I am using the flatpak now https://flathub.org/apps/details/org.cloudcompare.CloudCompare. I've not encountered the issues that I had before with the snap.

**Comment by xins981** [comment]
> 
I solve it by building source code rather than sanp in ubuntu  18.04 and CC is 2.12.4
