### ISSUE TITLE
Rectangle selection not working for segment tool ? 

### ISSUE THREAD

**Issue by Nefira** [CloudCompare/CloudCompare#780]
## Current Behavior

The rectangle selection option in the "Segment" tool (Edit > Segment in the toolbar), is not working for me ? When I left click twice in two different locations of the visualisation, nothing happens, and I am not able to perform the segmentation. Polyline works well though.

## Expected Behavior

Rectangle selection works for the "Segment" tool, as described in https://www.cloudcompare.org/doc/wiki/index.php?title=Interactive_Segmentation_Tool .

## Steps to Reproduce (for bugs)

1. Open a file (in my case, a .las file containing a cloud of points).
2. Start the "segment" tool in Edit > Segment.
3. Use the "Rectangular Selection" (third icon from the left in the "Segment" toolbar).
4. Click twice anywhere on the screen.

## Your Environment
* CC Version: Version: 2.6.3 [Windows 64 bits], Compiled with MSVC 1700 and Qt 4.8.6
* OS & Version: Windows 8.1 Entreprise 64 bits 6.3 version 9600 
* Graphics card: VMware Virtual SVGA 3D Graphics Adapter (or maybe : Quadro M1000M/PCIe/SSE2)

I am launching CC from a windows virtual machine, while my physical machine runs on Debian GNU/Linux 8 (jessie) 64 bits).

**Comment by dgirardeau** [comment]
Sorry, contrarily to what's written in the documentation, you have to hold the left mouse button while drawing the rectangle: click, hold the button, move the mouse and release the button.

**Comment by Nefira** [comment]
Sorry, I forgot to mention that I tried that as well, to no avail ?

**Comment by dgirardeau** [comment]
Oh, I realize that you are working with a very old version... Have you tried with a more recent version?

**Comment by Nefira** [comment]
No, unfortunately, I wasn't able to launch versions 2.9.1 (Omnia) and
2.10.alpha on my machine. Is this a known bug on version 2.6.3 ?

**Comment by dgirardeau** [comment]
No, I don't remember any such bug. Does it work with the standard 'polygon' drawing mode?

**Comment by Nefira** [comment]
Yes

**Comment by dgirardeau** [comment]
Hum, and can you try holding the CTRL key while in the 'polygonal' mode (and left click, hold and release)?

**Comment by Nefira** [comment]
It is not doing anything ? Well, this is a bit annoying, but if the problem exists only for me then it might not be worth spending too much time on it. I think I can use other softwares for the rectangular clipping part. Thanks anyway !
