### ISSUE TITLE
Does CloudCompare provide volumetric measurement?

### ISSUE THREAD

**Issue by 717g301github** [CloudCompare/CloudCompare#787]
I have installed CloudCompare, and the only executable I can see is ccViewer.

Can CloudCompare provide volumetric measurement of stockpiles?

**Comment by asmaloney** [comment]
If you are having a problem with the installation, please create a new issue for that and fill in the template.

As for your question, I leave that to @dgirardeau :-)

**Comment by 717g301github** [comment]
Thank you.

I found CloudCompare binary, and I can find 2.5D volume calculation. Is that what I think it is?

Can I use inclinometer data to feed the CloudCompare to get volumetric measurement of a stockpile?

If so, let me plan the donation.

**Comment by dgirardeau** [comment]
Yes indeed. See http://www.cloudcompare.org/doc/wiki/index.php?title=2.5D_Volume
