### ISSUE TITLE
Save as ".PCD" creates broken pcd-File

### ISSUE THREAD

**Issue by mwingler** [CloudCompare/CloudCompare#804]
## Current Behavior
1. Import a binary .PCD-File (e.g. https://github.com/rollup/three-jsnext/blob/master/examples/models/pcd/Zaghetto.pcd) in CloudCompare
2. Save/Export it  "File" -> "Save" -> ".pcd"
3. The PCD-Header has been changed by CloudCompare (see Screenshot right) and the binary-part of the file contains "null"-values.

![pcd_header](https://user-images.githubusercontent.com/39303804/47418409-5b260380-d77a-11e8-92ad-e529335efb18.png)

## Expected Behavior
1. Import a binary .PCD-File (e.g. https://github.com/rollup/three-jsnext/blob/master/examples/models/pcd/Zaghetto.pcd) in CloudCompare
2. Save/Export it  "File" -> "Save" -> ".pcd"
3. The .pcd file is the same as before.

## Steps to Reproduce (for bugs)
1. Import a binary .PCD-File (e.g. https://github.com/rollup/three-jsnext/blob/master/examples/models/pcd/Zaghetto.pcd) in CloudCompare
2. Save/Export it  "File" -> "Save" -> ".pcd"
3. The PCD-Header has been changed by CloudCompare and the binary-part of the file contains "null"-values.

## Context/Comments
Due to the broken export, it is not possible to load an exorted .pcd-file from CloudCompare in this example: https://threejs.org/examples/webgl_loader_pcd.html

## Your Environment
* CC Version: v2.9.1
* OS & Version: Windows 10 Enterprise, x64

**Comment by dgirardeau** [comment]
I believe this 'issue' has already been declared before. If I remember well the conclusion was that this is done automatically by PCL itself (for the sake of data padding or something like that).

What happens exactly: CloudCompare imports the cloud from a PCD file thanks to the PCL library (and converts it to its own format). Then at the time of export, CloudCompare converts the cloud back to a PCL structure, and then calls the PCL library again to create the file. Therefore the file creation is done by PCL... If you know how to prevent PCL from adding this padding field, don't hesitate ;)

**Comment by dgirardeau** [comment]
See https://github.com/CloudCompare/CloudCompare/issues/776

**Comment by mwingler** [comment]
Thanks for your fast reply. So basically it is not CloudCompares fault, but PCL. 

Do you have any idea, why the binary data-Part of the .pcd-file is also broken? There are many strange "**?NULNULx80?**" values inside, after exporting it from CloudCompare?

![image](https://user-images.githubusercontent.com/39303804/47421509-05a12500-d781-11e8-8649-2ddcea1740dc.png)

**Comment by dgirardeau** [comment]
It's not really "broken" (the file can be loaded successfully afterwards - at least on my side).

It's probably the padding values that are displayed as 'NULL' (well, that's logical since they are probably zeros ;). Anyway looking at a binary file in a text editor is always a strange experience ;)

**Comment by mwingler** [comment]
Ok, that sounds logic. :D 

Did you try to open it in [this example](https://threejs.org/examples/webgl_loader_pcd.html)?

I can open it before it was saved by CloudCompare but not afterwards. :(

**Comment by mwingler** [comment]
I got the following error:
![error](https://user-images.githubusercontent.com/39303804/47422189-5d8c5b80-d782-11e8-8bd2-4597ce73528b.png)

**Comment by dgirardeau** [comment]
Oh I tried to load it with CloudCompare (i.e. PCL). I'm not sure how your own solution (three.js?) does it... Apparently it doesn't like this additional field?

**Comment by mwingler** [comment]
It's not my own solution. It's an example of Three.js itself. Is there any option to export the pcd without the additional field?

**Comment by dgirardeau** [comment]
Well, I don't know. It's all PCL dark magic for me ;)

**Comment by mwingler** [comment]
Ok. But thanks for your efforts!
