### ISSUE TITLE
CLI console still graphic dependend

### ISSUE THREAD

**Issue by anj-easyinspect** [CloudCompare/CloudCompare#808]
Hi

I'm trying to use Cloudcompares **CLI** Merge and ICP options from inside a Docker environment. But even though the -SILENT parameter is used, the console still appear at the end, making it hard to work with in Docker due to display dependencies, which should be none graphical.
Is this intended, or is there a way to completely use CC in CLI mode without graphics?

**Comment by dgirardeau** [comment]
Hum,

I'm would not expect the console to show (this might be a small glitch) but anyway the command line version of CloudCompare is actually the same application (i.e. a GUI application) but the main window is not shown and the command line is processed instead. Therefore I fear it might be perceived anyway as a graphical application.

For more details about this, we use a Qt "QApplication", and not a "QCoreApplication" (that would avoid instantiating any GUI component). Not sure if it's possible to switch to a QCoreApplication if the command line is activated...

**Comment by jgrn307** [comment]
I wanted to re-up this issue -- we are also trying to run CC on an HPC and even with the -SILENT flag with e.g. C2C comparison it fires up a GUI progress window.  I've confirmed this on Windows.  There are algorithms unique to CC that would be AMAZING if we can get them into a batch mode, but as long as the GUI remains operational, it limits our ability.  Can you see if this can be properly silenced?

**Comment by jgrn307** [comment]
BTW, I'm seeing the GUI pop up with -SILENT in 2.11 alpha.

**Comment by dgirardeau** [comment]
Okay I fixed this (19ed7cd537c49196ff7fb52c35561e01145c82eb).

I'll update the 2.11.alpha version soon (for Windows). For Linux/HPC I guess you'll have to compile it or get it with 'snap'.

**Comment by dgirardeau** [comment]
And I fixed the first issue as well! 8f85192b686680e28f36251179b507ed5c1b5440

Thanks for the feedback.
