### ISSUE TITLE
Cannot run the application on Azure VMs

### ISSUE THREAD

**Issue by jonstronggit** [CloudCompare/CloudCompare#814]
hi,
I have tried to run CloudCompare on Azure VMs (Windows Server, 2008, 2008R2, 2012, 2012R2, 2016), but they all failed to execute.

Event logs showing that there are errors when running Qt5Gui.dll. Other than that, we have no clues how to keep on troubleshooting. Is there any requirement of graphic card for this application to be executed?

Please let us know. Any insight would be appreciated.
Thanks!

**Comment by dgirardeau** [comment]
The issue with AWS (and similar solutions) is indeed with OpenGL/3D display handling.

Have you looked at the forum? https://www.danielgm.net/cc/forum/viewtopic.php?t=3299

Is this solution working for you?

**Comment by dgirardeau** [comment]
Well, CloudCompare uses OpenGL intensively. Actually some integrated Intel chipsets are supported, but some of them (the older ones) are outdated and not supported by Qt (the library upon which CloudCompare is built).

And for the command line version, it's actually just a 'hack' of the Graphical Interface version (therefore when it starts, it probably checks for the availability of some resources and OpenGL capabilities). I might have a way to change that now that I thinks about it...

**Comment by dgirardeau** [comment]
Okay I've updated the online beta version so that it requires the minimum OpenGL configuration when used in command line mode (but apparently we can't easily prevent any interaction between Qt and OpenGL). It might help running on system with low end graphic cards.

**Comment by jonstronggit** [comment]
@dgirardeau, 
Thanks for the clarification! I guess user does not want to use this via command line but GUI. However, this answers why the application keeps on quitting every time I try to launch on Azure VM...Thanks again!
