### ISSUE TITLE
CloudCompare crashes when trying to align 2 clouds

### ISSUE THREAD

**Issue by gap710** [CloudCompare/CloudCompare#817]
## Current Behavior
Anytime I select the option "Aligns 2 clouds by picking at least 4 equivalent point pairs" CloudCompare crashes and my Mac Air goes off. 

## Expected Behavior
It should let me select that option. 

## Context/Comments
I tried to run CC (latest version avaible) on Windows and have not had this kind of problem. Is it a bug of the Mac version?

## Your Environment
* CC Version: v29.1 (Macintosh)
* OS & Version: macOS Mojave (10.14.1)
* Graphics card: Intel HD Graphics 6000 1536 MB

**Comment by asmaloney** [comment]
I have not been able to reproduce this.

Can you give some more details and fill in the missing Steps to Reproduce section? Or is it literally "I click on the button in the tool bar and it crashes"?

**Comment by gap710** [comment]
It is literally “I click on the button in the tool bar and it crashes”. I does not matter what I am working on. Anytime I try and click that option, it crashes. 
I deleted and re-installed CC, however it keeps happening. I am hopeless by now. It only happens when I am working on the Mac version.

**Comment by asmaloney** [comment]
This might have something to do with macOS 10.14? I build & test on 10.12, so I don't have 10.14 to test with.
Do any of the other tools in the tool bar crash like this?

**Comment by gap710** [comment]
Nope. It looks like it’s the only tool (so far). That’s what I was thinking anyway. Such a reproducible crash must be caused by an incompatibility of CC and the newest version of macOS

**Comment by asmaloney** [comment]
@gap710 Please contact me through email (see profile) and I'll get you a recent build to try.

**Comment by asmaloney** [comment]
Problem seems to be resolved using a 2.10 beta build from here:

https://asmaloney.com/software/
