### ISSUE TITLE
Assertion failure in ccPointCloudLOD::addNPointsToIndexMap

### ISSUE THREAD

**Issue by zoukyle** [CloudCompare/CloudCompare#823]
## Current Behavior

After open a 6.4G las file (built with PDAL), the program can show the point cloud for a while. Then it crashed with the error:
CloudCompare: /home/liangzou/gitcloudcompare/CloudCompare/libs/qCC_db/ccPointCloudLOD.cpp:706: uint32_t ccPointCloudLOD::addNPointsToIndexMap(ccPointCloudLOD::Node&, uint32_t): Assertion `false' failed.
Aborted

## Expected Behavior

The program should not crash.

## Steps to Reproduce (for bugs)

Open a large LAS file. Wait for the LoD to finish and the use mouse wheel to zoom in/out.

## Your Environment
* CC Version: v2.10-beta
* OS & Version: Linux
* Graphics card: Nvidia 1080 Ti

**Comment by dgirardeau** [comment]
Indeed, this was due to a wrong test (the size was tested instead of the capacity of the vector). That's fixed with ee79b1069541e88424ec03648852e1f66acb75eb. Thanks for the feedback.
