### ISSUE TITLE
CC crashes during segmentation of a point cloud

### ISSUE THREAD

**Issue by mikkolaine** [CloudCompare/CloudCompare#831]
Greetings,

while segmenting a point cloud (.las) using the scissors tool, CC crashes:

```
$ CloudCompare 
CloudCompare: /wrk/applications/cloudcompare/libs/qCC_db/ccPointCloud.cpp:2712: virtual void ccPointCloud::drawMeOnly(CC_DRAW_CONTEXT&): Assertion `m_pointsVisibility.capacity() == m_points.size()' failed.
Aborted 
$ 
```

I'm running the latest cloudcompare built from source on devuan unstable.

**Comment by dgirardeau** [comment]
Thanks for the feedback. That's fixed with 60116117c748234bfa8fffc719639f899cf1b016.

However, mind that it was only a debug 'assert', it would have worked in release mode. I'm not sure that you really wanted to run CC in debug mode (it's much slower than in release mode).
