### ISSUE TITLE
Raise an exception when you close CC after saving an ASCII file

### ISSUE THREAD

**Issue by zihahage** [CloudCompare/CloudCompare#834]
## Current Behavior

When you close CC after saving a point cloud to ASCII file, like .txt or .asc, it throws an exception.

## Steps to Reproduce (for bugs)

Load a point cloud file, and save it back to .txt, then close CC, you will  catch that exception, and you will see "Exception thrown at ..." in the VS output window.

## Context/Comments

After checking the class AsciiFilter , i noticed that AsciiSaveDlg is wrapped by AutoDeletePtr, and is 
specified qwidget parent when it is constructed. Maybe during resource release, it is deconstructed twice.

## Your Environment
* CC Version: 2.10
* OS & Version: Win7
* Graphics card: Nvidia GTX650

**Comment by dgirardeau** [comment]
Thanks for the feedback. That's fixed with f8189c4cf939518e17c993a9505c1b73d00427a3
