### ISSUE TITLE
qPCV in command line

### ISSUE THREAD

**Issue by foobarbecue** [CloudCompare/CloudCompare#837]
It would be lovely if we could do ambient occlusion from the command line, using the qPCV plugin!

**Comment by foobarbecue** [comment]
I started working on this, and then realized it introduces a dependency between the command line parser and a plugin, which might not be installed... is there a policy on this? I guess we need some preprocecessor stuff in ccCommandLineCommands.h to check what plugins are available?

**Comment by foobarbecue** [comment]
I guess I can follow the pattern used by BUNLER_IMPORT?

**Comment by dgirardeau** [comment]
If you want to do it, then you have to use the new 'registerCommands' mechanism for plugins.

See how the M3C2 plugin implements it for instance (qM3C2Plugin::registerCommands):
https://github.com/CloudCompare/CloudCompare/blob/master/plugins/core/qM3C2/qM3C2.cpp#L104

To summarize, you have to create a ccCommandLineInterface::Command object that does the work, and register it to the main command line mechanism (this is automatically call on startup when loading the plugin).

**Comment by foobarbecue** [comment]
Thanks! See PR.
