### ISSUE TITLE
An error occurred while loading las file [v2.10.2] (only in Debug build)

### ISSUE THREAD

**Issue by miaowangtw** [CloudCompare/CloudCompare#841]
## Current Behavior

[CC v2.10.2]
"An error occurred while loading xxx", xxx is a normal LAS file
Got this error message when loading a LAS file, while loading point cloud in TXT file works fine.

## Steps to Reproduce (for bugs)

CC source code cloned from GitHub (at Jan 26, 2019)
PDAL (1.8.0-1) from OSGeo4W (64-bit), pdalcpp.dll (2018.11.6), pdal_util.dll (2018.11.6)
CMake v3.13.3, set PDAL_DIR = C:\OSGeo4W64\lib\pdal\cmake
Get required dlls from C:\OSGeo4W64\bin
Successfully build all project with VS 2017.
Error occurs at line 180 ( Options.hpp ) [ add(opt); ]

## Your Environment
* CC Version: 2.10.2 [64-bit], cloned from GitHub at Jan 26, 2019
* OS & Version: Windows 10
* Graphics card: nVidia GeForce GTX 1060 6GB

**Comment by dgirardeau** [comment]
Can you share this 'normal' LAS file with us maybe? Do you know the version of this LAS file by the way? (PDAL can't load all versions, especially not files with FWF data for instance)

**Comment by miaowangtw** [comment]
Attached ZIP file contains a simple LAS file which was saved by a program coded by myself. It is a LAS ver. 1.2 file with point format 3. The file can be loaded by CC v.2.10.1 installer version downloaded from www.cloudcompare.org. Therefore, I don't think the occurred error is related to the LAS file.
Hope you can reproduce the error and solve it.
[1_RGB.zip](https://github.com/CloudCompare/CloudCompare/files/2799027/1_RGB.zip)

**Comment by asmaloney** [comment]
Since you didn't build PDAL yourself, could it be link options related? Single vs. multithreaded?

`Options.hpp` isn't a CloudCompare file as far as I can tell - a PDAL file? (On macOS I don't use PDAL, but your file loads fine with the older LAS loader.)

**Comment by dgirardeau** [comment]
Load fine on my side too (on Windows). Can you maybe run in debug mode and try to get more info about when this error occurs?

**Comment by dgirardeau** [comment]
I use OSGeo4Win on my side.

**Comment by asmaloney** [comment]
​OSGeo4Win 32bit or ​64bit?

**Comment by dgirardeau** [comment]
64 bits of course (CC is only 64 bits now, isn't it?)

**Comment by miaowangtw** [comment]
Yes, it is 64bit.

**Comment by dgirardeau** [comment]
I managed to reproduce that on my side, but only in Debug mode actually. I don't know what happens (maybe because the precompiled PDAL library is not compatible with Visual Studio Debug mode?)

**Comment by MerlotQ** [comment]
@dgirardeau Hi Does CC support loading a .las file? The button open shows .bin .xyz etc but no .las suffix.

**Comment by dgirardeau** [comment]
Yes and for a long time now (which version are you using?). If you compile it yourself, you'll have of course to choose the right option and link to the right 3rd party libraries (PDAL mostly in this case).

**Comment by MerlotQ** [comment]
@dgirardeau Thanks. You are right. I should have enabled the option "OPTION_PDAL_LAS".

**Comment by leifeiyi** [comment]
Hello, I have encountered the same problem. When loading the .las file, [I/O] Exception: bad allocation appears. Is this problem solved?

**Comment by leifeiyi** [comment]
@dgirardeau

**Comment by leifeiyi** [comment]
@miaowangtw

**Comment by dgirardeau** [comment]
Do you also have this issue in Release mode?

**Comment by leifeiyi** [comment]
@dgirardeau I solved this problem in release mode, CloudCompare has been able to load the .las file correctly, but why is this problem in Debug mode? Can you explain it to me? Thank you very much for your reply.

**Comment by miaowangtw** [comment]
@leifeiyi @dgirardeau : The Release mode CC loads LAS file well, except the file path contains non-English characters, e.g. Chinese characters. CC shows a Error dialog "PDAL exception 'bad conversion' ". But this does not happen when loading a text format point cloud file whose path contain Chinese characters. And the Debug Mode still cannot load a LAS file.

**Comment by asmaloney** [comment]
@miaowangtw That sounds like a separate issue. Could you please create a new issue for that so it may be tracked separately? Thank you.
