### ISSUE TITLE
Error trying to compile v2.10.1 - missing qt5svg

### ISSUE THREAD

**Issue by chbrandt** [CloudCompare/CloudCompare#843]
## Current Behavior
I am following the steps from your BUILD.md to compile version v.2.10.1, but I'm stuck with Qt5Svg.
The Error I get from `cmake-gui` is the following:
```
The C compiler identification is GNU 6.3.0
The CXX compiler identification is GNU 6.3.0
Check for working C compiler: /usr/bin/cc
Check for working C compiler: /usr/bin/cc -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: /usr/bin/c++
Check for working CXX compiler: /usr/bin/c++ -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
cmake policies active: CMP0043
Performing Test COMPILER_SUPPORTS_CXX11
Performing Test COMPILER_SUPPORTS_CXX11 - Success
cmake policies active: CMP0043
CMake Warning at CC/CMakeLists.txt:26 (message):
  CCLib configured without parallel algorithm capabilities - see
  COMPILE_CC_CORE_LIB_WITH_TBB


CMake Error at cmake/CMakeExternalLibs.cmake:22 (find_package):
  By not providing "FindQt5Svg.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Svg", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Svg" with any
  of the following names:

    Qt5SvgConfig.cmake
    qt5svg-config.cmake

  Add the installation prefix of "Qt5Svg" to CMAKE_PREFIX_PATH or set
  "Qt5Svg_DIR" to a directory containing one of the above files.  If "Qt5Svg"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CC/CMakeLists.txt:32 (include)


Configuring incomplete, errors occurred!
See also "/usr/local/cloudcompare/CMakeFiles/CMakeOutput.log".
```

I Tried to point `QT5_ROOT_PATH` as indicated in BUILD.md, but the error persist,
```
# export QT5_ROOT_PATH=/usr/lib/x86_64-linux-gnu/qt5/bin/
```

## Expected Behavior
I expected the files for Qt5Svg to be found and compilation to run smooth.

## Steps to Reproduce (for bugs)
We can do it from a Docker container, the one I'm using is `continuumio/miniconda3`:
```
FROM continuumio/miniconda3

RUN git clone https://github.com/CloudCompare/CloudCompare.git \
    --single-branch --branch v2.10.1

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update                                              &&\
    apt-get install -y cmake cmake-qt-gui g++ gcc  &&\
    apt-get install -y qt5-default                               &&\
    apt-get clean
```
Run your container like that to have your X11 (`cmake-gui`) exported to your host (if running from a Linux host):
```
[host]$ docker run --rm -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix:0 <cloudcompare-container>
```
And adjust your host's `xhost`:
```
[host]$ xhost +
```
Now, from inside the container, we may go to `/CloudCompare` and "`cmake`" it:
```
[container]$ cd /CloudCompare
[container]$ cmake-gui
```

The error (above) should be seen when trying to "Configure" the project.

## Context/Comments

I want to contribute back to the CloudCompare project with a nice Docker container option for the users.

## Your Environment
* CC Version: gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
* OS & Version: Docker container from Debian 9.5
* Qt 5.7.1 (from package `qt5-default`)
* Graphics card:

**Comment by dgirardeau** [comment]
I'm not the Linux guru, but have you tried with a more recent version of Qt? I use 5.9 on Windows...

**Comment by tmontaigu** [comment]
The error message is telling you that it's missing `qt5svg` which is not installed in the `qt5-default` but in the `libqt5svg5-dev` (on unbuntu).

CloudCompare uses travis as a CI system, which uses docker to build the application so the [.travis.yml](https://github.com/CloudCompare/CloudCompare/blob/master/.travis.yml) contains the names of the package CC is depending on

**Comment by rjanvier** [comment]
yes you are missing some dependencies. @tmontaigu  is right, you can refer to the travis/or snap build to reproduce the build on your computer.

**Comment by chbrandt** [comment]
Yes, sorry for the silence.
After @tmontaigu pointed out the travis setup the dependencies were solved, I then had a small issue with a submodule that was not being cloned (`git --recursive` solved that).
In the torrent of the last weeks I lost the track of this thread, but I got this message from yesterday and made my homework: https://github.com/chbrandt/docker-cloudcompare
Thank you
