### ISSUE TITLE
Cannot open Las 1.4 on Mac OS

### ISSUE THREAD

**Issue by Amytipple** [CloudCompare/CloudCompare#844]
## Current Behavior
On attempting to load a las 1.4 file I get the following error messages:

```Liblas exception 'version minor out of range'```
```An Error occurred while loading 'file': the third party library in charge of saving/loading the file has thrown an exception```

## Context/Comments
The file was created using the Python library; Laspy. It opens as expected in a Linux Ubuntu 18.04 environment using CC but not on a Mac.

## Your Environment
* CC Version: 2.10.1 (Zephyrus)
* OS & Version: Mac OS Mojave version 10.14.1
* Graphics card: Radeon Pro 560X 4096 MB Intel UHD Graphics 630 1536 MB

**Comment by asmaloney** [comment]
The macOS build uses the older LAS libraries and only supports up to v1.3 of the LAS format. You could either try forcing `Laspy` to produce v1.3 files or you could try building the macOS version with the new LAS libraries.

**Comment by dgirardeau** [comment]
I don't believe PDAL handles LAS1.4 yet. The Windows version of CloudCompare uses a different 3rd party library to load LAS 1.4 files (sadly).

**Comment by tmontaigu** [comment]
PDAL is able to handle LAS 1.4, it was one of the reason to introduce it in CloudCompare

**Comment by dgirardeau** [comment]
Any LAS1.4 files? I have the impression some are still rejected? Maybe the ones with FWF then?

**Comment by tmontaigu** [comment]
Yes, PDAL does not support LAS files with waveform.
The waveform information is indenpendent of the file version, it is tied to the point format id

**Comment by Amytipple** [comment]
Thanks for the suggestions @tmontaigu and @dgirardeau  I shall 'try building the macOS version with the new LAS libraries'

**Comment by asmaloney** [comment]
For anyone finding this issue later - as noted above - CloudCompare 2.10 on macOS only supports up to v1.3 of the LAS format.
