### ISSUE TITLE
-EXTRACT_VERTICES followed by -SAVE_CLOUDS causes crash

### ISSUE THREAD

**Issue by foobarbecue** [CloudCompare/CloudCompare#847]
## Current Behavior
Using the command line, if I run `CloudCompare.exe -O my_mesh.ply -EXTRACT_VERTICES -SAVE_CLOUDS`, the program hangs.

## Expected Behavior
I was hoping to extract the vertices from my mesh, run some command line commands on it, and then save the output.

## Steps to Reproduce (for bugs)
`CloudCompare.exe -O my_mesh.ply -EXTRACT_VERTICES -SAVE_CLOUDS`

## Context/Comments
I actually originally noticed this with several more commands in between EXTRACT_VERTICES and SAVE_CLOUDS, but this seems to be the minimal case. When I run this in Visual Studio debugger, I see that it hangs because of an unhandled read access violation during type checking in `ccCommandLineParser::exportEntity`. I haven't tried very hard to track down the root cause yet.

## Your Environment
* CC Version: 2.10.alpha , also reproduced in a minimal build of 641f19c66586df8f4a41627875aae2903475825c with QT 5.12.1
* OS & Version: Windows 10
* Graphics card: GTX 980 Ti

**Comment by asmaloney** [comment]
`-EXTRACT_VERTICES` is removing the meshes with `removeMeshes()` in `CommandExtractVertices::process()` and then `-SAVE_CLOUDS` is trying to use the clouds within them in `ccCommandLineParser::saveClouds()`.

My guess is that the thing that's adding to `m_clouds` needs to make sure it's not grabbing the point cloud from inside the meshes.

I don't know if that has other implications though - @dgirardeau will have to weigh in.

**Comment by dgirardeau** [comment]
Arf, that was a silly bug (the vertices were deleted right after extracting them...). They were not 'detached' from their parent mesh. That's fixed: 58bc52a60699547871a541d6e891b6819af55c07.

Thanks for the feedback!
