### ISSUE TITLE
Cannot open 2.10.2 Zephyrus.

### ISSUE THREAD

**Issue by SheldonRoot** [CloudCompare/CloudCompare#858]
## Current Behavior

After installing Cloud Compare 2.10.2 Zephyrus, I get the following 4 errors:
  - MSVCO140.dll not found
  - VCOMP140.dll not found
  -  CONCRT140.dll not found 
  - VCRUNTIME140.dll not found

The error boxes tell me to try and install cloud compare again to try to fix the problem but it does not. Cloud Compare 2.6.3 beta seems to work.

## Expected Behavior

Cloud Compare opens.

## Steps to Reproduce (for bugs)

Double click on cloud compare icon after install.

## Your Environment
* CC Version: 2.10.2 Zephyrus
* OS & Version: Win10 pro
* Graphics card: 
* Qt Version (if compiling):

**Comment by dgirardeau** [comment]
Hum, it looks like the Visual Studio redistributable package was not installed... Can you try to install it manually? https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by SheldonRoot** [comment]
Thanks for the help! I installed Visual Studio from the link and Cloud 
Compare is working.

Cheers,

Sheldon Root, EIT | Automata Industrial Consulting - Project 
Management/Industrial Design |
Nanaimo, BC | 250-910-0491 | www.automata.pro
Home

------ Original Message ------

**Comment by dgirardeau** [comment]
Thanks for the feedback!
