### ISSUE TITLE
Mesh->Smooth->crash

### ISSUE THREAD

**Issue by geomujo** [CloudCompare/CloudCompare#864]
## Expected Behavior

From generated mesh i try to use smoothing-function. This function produces in  more than 75 percent of it's usage a complete CloudCompare-crash without any debug or information window.

## Steps to Reproduce (for bugs)

1) from point-cloud generated mesh via poisson-detection
2) 'Edit->Mesh->Smooth(Laplace)'
3) crash, imediately after new smoothed mesh was calculated and displayed
4) Parameter changes are insignificant and doesn't have influence to the tendency of crashing

## Your Environment
* CC Version: 2.10.2
* OS & Version: Windows 10 x64 (10.0.17134.648)
* Graphics card: Nvidia GT 740 4GB
* Qt Version (if compiling): 

Xeon E3-1245 v5, Fujitsu D3417, 2x8GB DDR4, IntelSSD 750 (PCIe)

**Comment by dgirardeau** [comment]
I can't reproduce the error. Can you maybe share the mesh with me? (admin [at] cloudcompare.org)
