### ISSUE TITLE
An error occurred when loading las file whose path contains multi-byte character [v2.11 alpha]

### ISSUE THREAD

**Issue by miaowangtw** [CloudCompare/CloudCompare#869]
## Current Behavior

 When trying to open a las file with multi-byte character in path, CC shows an Error dialog "PDAL exception 'bad conversion' "
## Your Environment
* CC Version: 2.11 alpha
* OS & Version: Windows 10
* Graphics card: nVidia GeForce GTX 1060 6GB
* Qt Version (if compiling): 

Character Set: Mulitbyte

**Comment by tmontaigu** [comment]
Hello, do you have an example of path that causes problems ?

**Comment by miaowangtw** [comment]
@tmontaigu In my case, the path and file name cannot contain Chinese characters, e.g. the file name "點雲.las" will occur this error.
