### ISSUE TITLE
DgmOctree uninitialized variables

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#871]
**Describe the bug**

Potential crash or corrupted data due to uninitialized variables.

**Additional context**

In `DgmOctree::findBestLevelForComparisonWithOctree()`:

```c++
for (int i=1; i<maxOctreeLevel; ++i) //warning: i >= 1
{
   int cellsA,cellsB,diffA,diffB;
   diff(i,m_thePointsAndTheirCellCodes,theOtherOctree->m_thePointsAndTheirCellCodes,diffA,diffB,cellsA,cellsB);

   //we use a linear model for prediction
   estimatedTime[i] = ((static_cast<double>(ptsA)*ptsB) / cellsB) * 0.001 + diffA;
...
```

None of those variables are initialized, and if `diff()` returns without setting them (in this case):

```c++
if (codesA.empty() && codesB.empty()) return;
```

then they contain garbage values so the `estimatedTime[i]` is bad. (If it happens to return `cellsB=0`, then we crash.)

**Suggested fix**

I would make `diff` return a bool and check that before trying to set `estimatedTime[i]`.

**Your environment**
 - CC Version (or git hash/tag): master

**Comment by dgirardeau** [comment]
Yes, go ahead ;)
