### ISSUE TITLE
Texture not reloaded correctly

### ISSUE THREAD

**Issue by philbarclay** [CloudCompare/CloudCompare#881]
**Description**
When reloading an updated .obj file, the associated texture (via a .mtl file) is not reloaded.

**How to reproduce**
1. Load an .obj with associated .mtl/.png texture
2. Right click on the obj object in CC and click delete
3. Change the .png texture file on disk (outside CC)
4. Load the .obj a second time
5. Observe the original texture image is used

Optional:
6. Close CC and relaunch
7. Load .obj
8. Observe correct texture image is used

**Expected behaviour**
When a obj is loaded the current texture image from disk should be used.

**Additional Context**
This is an on-going bug present in previous versions.

**Your environment**
 - CC Version 2.10.2 64-bit
 - OS & Version: Win10 Enterprise, Ver 1803
 - Graphics card: Intel HD Graphics 4600
 - Qt Version (if compiling): NA

**Comment by dgirardeau** [comment]
Yes, that's because we keep the textures loaded during the session and recognize them by their name (so as to avoid reloading them, especially if they are shared by multiple meshes).

I guess we should also check the creation date, or the size, etc.

**Comment by asmaloney** [comment]
One possibility might be to use [QFileSystemWatcher](https://doc.qt.io/qt-5/qfilesystemwatcher.html) to reload textures automatically when they change.

**Comment by philbarclay** [comment]
The current behavior makes sense for large textures that don't change.  In my case I am regenerating the obj and texture files externally.  In order to view the updated pair I need to completely close CC and relaunch which is a bit of a pain.

**Comment by philbarclay** [comment]
Sorry about the close/open, clicked the wrong button.

**Comment by dgirardeau** [comment]
Ok that should be fixed by 0c737629484a7789127d76400df384cd66153c42

**Comment by dgirardeau** [comment]
The 2.11.alpha version is now online.
