### ISSUE TITLE
COMMAND_ICP_ROT doesn't do anything

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#884]
**Describe the bug**

The [COMMAND_ICP_ROT](https://github.com/CloudCompare/CloudCompare/blob/5826308e20b5273a15cccd5e51047c9fdfe4b245/qCC/ccCommandLineCommands.cpp#L3584) command reads its parameter `transformationFilters` but doesn't do anything with it.

**Your environment**
 - CC Version (or git hash/tag): 5826308e20b5273a15cccd5e51047c9fdfe4b245

**Comment by dgirardeau** [comment]
Good catch! Fixed: aaf00749951eb457901fa5ee8da324c2d27859eb
