### ISSUE TITLE
Saving crash

### ISSUE THREAD

**Issue by albertograva** [CloudCompare/CloudCompare#889]
Hi all!
I'm not an pro level user, but every times I try to save a project CC close itself automatically before I try to push 'save' botton.
no error number.
I've no idea

environment
 - CC Version (or git hash/tag): 2.9.1 linux 64 (but when i download from web site it tells me 2.10.2)
 - OS & Version: Ubuntu 18.04.1 LTS
 - Graphics card: Intel® UHD Graphics 620 (Kabylake GT2)
 - Qt Version (if compiling): 4.8.7

thank you all

**Comment by rjanvier** [comment]
Hello. Are you sure you are using QT 4.8.7? do you use the snap package or did you compile it from scratch?

**Comment by albertograva** [comment]
Really i'm not sure, when i wrote, I've checked and the installed version
was that one...now I'm checking and it is 5.9.5.
I've installed qt when I've isntalled qgis, I didn't compile it

thx a lot

Il mar 2 apr 2019, 10:14 Romain Janvier <notifications@github.com> ha
scritto:
