### ISSUE TITLE
Update QCustomPlot to 2.x

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#892]
Our included QCustomPlot is version 1.3.2 from 2015 which isn't getting any fixes/updates anymore. We should update to 2.0.1.

This (quite likely) means changes on our side.

In addition, instead of including the code directly, we should consider adding it as a git submodule from here:

https://gitlab.com/DerManu/QCustomPlot

**Comment by dgirardeau** [comment]
Oh yes indeed!

I did that a long time ago, and never really used it that much so I simply forgot about it in a way :D
