### ISSUE TITLE
Cannot add pointcloud to mainwindow in the plugin

### ISSUE THREAD

**Issue by Micalson** [CloudCompare/CloudCompare#894]
Hello, thank you for your work. I have a problem about developing the plugin. I use the following code to add pointcloud to mainwindow, but it did not work. Could you tell the reason? thank you for your reply.
	ccPointCloud c1;
	c1.setName("c1");
	c1.addPoint(CCVector3f(2, 3, 2));
	ccHObject* container = new ccHObject("t");
	container->addChild(&c1);
	m_app->addToDB(container);
	m_app->refreshAll();

**Comment by asmaloney** [comment]
You will need to allocate your `ccPointCloud` on the heap rather than on the stack. If you allocate it on the stack it is destructed at the end of the function.

So try:
```cpp
ccPointCloud *c1 = new ccPointCloud( "c1" );
```

You will also have to reserve space before you start adding points. See `ccPointCloud::reserveThePointsTable()`.

**Comment by Micalson** [comment]
Thank you for your reply. I changed the code according to what you said, and it works. @asmaloney

**Comment by asmaloney** [comment]
Great!
