### ISSUE TITLE
Translate/rotate along an arbitrary vector

### ISSUE THREAD

**Issue by WargodHernandez** [CloudCompare/CloudCompare#895]
Adding an option to the graphical translate/rotate tool for translating along an arbitrary vector instead of only along cardinal axis (x, y, z). I frequently find it useful to translate along the normal vector of a plane. I've tested modifying the dialog source and didn't have any trouble adding the functionality by overwriting one of the other axis, but I have no experience with QT to make the dialog modifications.

Maybe an advanced mode to the dialog with more options? An xyz triplet showing the vector along with a button to pick a vector from the db? 

Currently I copy a vector into XL and have a scalar to translate along it and a text output of a 4x4 matrix to apply to the cloud I want to move.

**Comment by dgirardeau** [comment]
Well, I'm not against adding such a feature of course. We just need to find someone motivated to do it (or much more users that have this particular need ;)
