### ISSUE TITLE
Test if 3Dpoint  belonging to any diplayed cloud is currently on the current screen

### ISSUE THREAD

**Issue by fotsing365** [CloudCompare/CloudCompare#898]
**Describe the feature you would like**

 
  I would like to know if there is any function in CloudCompare, which can be use to test if a giving 3Dpoint belonging to a display cloud is currently visible on the Viewer.  C++ function, I mean.
 thanks
**Describe alternatives you've considered**

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by dgirardeau** [comment]
It's not a "CloudCompare" method, but an OpenGL one. You can indeed project a 3D point to 2D (with the ccGLCameraParameters structure - see how it is used in various places in the code). Then from the 2D coordinates, you can retrieve the displayed pixel 'depth' and check it against the projected 2D point 'depth' (the third coordinate). There's a shortcut in ccGLWindow (the getGLDepth method) but it's not used anymore in the code I believe.

**Comment by fotsing365** [comment]
Thanks Daniel 
  I tried something like this `ccGLCameraParameters camera;
	m_associatedWin->getGLCameraParameters(camera);
for (int i = 0; i < static_cast<int>(cloudSize); ++i)
        {
			
                const CCVector3* P3D = cloud->getPoint(i);

                CCVector3d Q2D;
                CCVector3d P;

                camera.project(*P3D, Q2D);
                bool test=camera.unproject(Q2D,P);

                visibilityArray[i] = (test ? POINT_HIDDEN : POINT_VISIBLE);
          
        }`
but it doesn't work

**Comment by dgirardeau** [comment]
Not sure what you were expecting when calling 'unproject' here?

Everything prior to this call is good. But then you need to retrieve the pixel depth at the 2D coordinates (= Q2). But you'll have to convert those floating point coordinates to integers (and check that the coordinates origin as well, I can't remember which convention is used by both methods).

Then you'll be able to compare the depth of the projected point (Q2D.z) and the depth of the pixel.

**Comment by fotsing365** [comment]
I don't really understand what you are saying. please can you give me a sample code?
Please thank you.

**Comment by dgirardeau** [comment]
You don't understand? I have some doubts now :D

Can you maybe explain again what you mean by "currently on the current screen"? Do you mean visible (not hidden by other points) or simply "inside the current camera frustum"?

**Comment by fotsing365** [comment]
I means inside the current camera frustum.  Perhaps my english is not good. in french "dans le champs visuel de l'utilisateur. Les points présents en avant plan pas en arrière" Excuse me I m french speaking that's why perhaps my english is not gut understood.
Thank you

**Comment by rjanvier** [comment]
you want to check cheirality? @dgirardeau explains how you could test for positive depth of your 3d point.  I think you can also check the angle between your viewing direction and the "camera-center-to-3d-point" ray. Another solution could be to test this at an octree cell level (if you use the octree-based picking mechanism)

**Comment by dgirardeau** [comment]
Maybe it would be interesting to check the qHPR plugin as well.

**Comment by fotsing365** [comment]
Thanks @dgirardeau  I think you are right. I will try to investigate on this side. 
Thank @rjanvier

**Comment by rjanvier** [comment]
@fotsing365 "les points en avant pas en arrière", c'est-à-dire? 
- "les points à l'avant plan et pas ceux à l'arrière plan/cachés par d'autres points" (point in the foreground not in the background / not potentially hidden) in this case qHPR is the good thing.
- "les points devant la camera et pas derrière la camera" (point in front of the camera, not behind), in this case a simple depth/angle test is enough

**Comment by fotsing365** [comment]
J'ai essaiyé qHPR mais les résultats ne donnent pas vraiment ce dont je m'attendais. @rjanvier   imaginez un dessin en perspective. Moi j'aimerais extraire en faite la vue de face ( dans cas le d'un point cloud l'ensemble des points present au niveau du visualiseur qui sont visible par l'utilisateur à l'instant t).  Merci

**Comment by rjanvier** [comment]
Merci de ce retour. Ce WE, J'ai résolu un "problème" dans le code courrant. Jusqu'à présent, la selection d'un point (picking) dans CloudCompare ne prenait pas en compte le "vrai" champ de vision de la camera et permettait de selectionner des points nons visibles (situés derrière la camera). Est-ce que ça répond à votre question/problématique?

**Comment by fotsing365** [comment]
Je ne ptense pas vraiment. La je vais un peu essayer d'expliquer avec un cloud que mon prof m'a donné. 
 1-- la première est une capture du pointcloud original
 2-- la seconde est une capture d'une orientation du point cloud
 3-- la dernière est une capture approximative du résultat que j'aimerait avoir. Je l'ai réaliser en utilisant la fonctionnalité de segmentation graphique.
![cloud_original](https://user-images.githubusercontent.com/24406778/55734928-b3974780-5a20-11e9-97b7-d7bfe2702bf9.png)
![orientation](https://user-images.githubusercontent.com/24406778/55734939-babe5580-5a20-11e9-9f19-50159deed450.png)
![resultat](https://user-images.githubusercontent.com/24406778/55734955-beea7300-5a20-11e9-80b9-543e1fb4a3ff.png)
Merci et grand merci

**Comment by rjanvier** [comment]
J'ai peur de ne vraiment pas comprendre. Je crois que qHPR correspond à votre besoin ou peut-être l'oultil de" rasterisation" (https://www.cloudcompare.org/doc/wiki/index.php?title=Rasterize) . Dans tous les cas cette question a potentiellement davantage sa place sur le forum...

**Comment by dgirardeau** [comment]
Non pour le coup je crois que m'a première approche répondait au besoin, non ?

Vous voulez uniquement les points effectivement affichés à l'écran et pas ceux qui sont "derrière" ?

Dans ce cas, il faut récupérer la "profondeur" (Z-buffer) OpenGL et la comparer à la profondeur des autres points qui se projette sur le même pixel pour ne garder que le pixel le plus "proche" de la caméra.

qHPR lui ne renverrai pas les points du mur du fond qu'on voit à travers les fenêtres ...

**Comment by fotsing365** [comment]
Merci @dgirardeau  pour votre aide je suis rentré sur votre idée de départ . ci-dessous le bout de code dont j'utilise `for (int i = 0; i < static_cast<int>(cloudSize); ++i)
                {
                
                            const CCVector3* P3D = cloud->getPoint(i);
                
                            CCVector3d Q2D;         
                            
                            //projection 
                            camera.project(*P3D, Q2D);
                            
                            // extraction de la profondeur Opengl
                            GLdouble depth=m_associatedWin->getGLDepth(static_cast<GLint>(Q2D.x),static_cast<GLint>(Q2D.y));

                            //comparaison des deux profondeus
                            visibilityArray[i] = (fabs(depth-static_cast<GLdouble>(Q2D.z))<0.001? POINT_HIDDEN : POINT_VISIBLE);
                      
                    }
` 
Mais le résultat n'est pas vraiment ce dont j'attend. S'il vous plait y a-t'il quelque chose qui manque?

**Comment by dgirardeau** [comment]
Alors il y a peut-être des subtilités ...

Je me rends compte que le plugin PCV fait exactement ça en fait : https://github.com/CloudCompare/CloudCompare/blob/master/plugins/core/Standard/qPCV/PCV/PCVContext.cpp#L317

Il utilise une autre méthode (gluProject) mais ça doit être possible de s'en inspirer.

**Comment by fotsing365** [comment]
Merci @dgirardeau
