### ISSUE TITLE
Camera name displayed at wrong place

### ISSUE THREAD

**Issue by StOriJimmy** [CloudCompare/CloudCompare#902]
**Describe the bug**

Name of the camera (loaded from bundler.out) is shown at the bottom-left corner of the main screen.

**How to reproduce**
Steps to reproduce the behaviour - include images if relevant:
1. Open a bundler file
2. Click on 'Camera #1'
3. Click on show name (in 3D)
4. See error: the name is not at the camera center but at the left-bottom corner, which cannot be seen completely

![bug](https://user-images.githubusercontent.com/9996794/55634201-92501480-57f0-11e9-9674-d99e13ac8adb.png)

**Expected behaviour**

camera name shown at the camera center

**Additional context**

**Your environment**
 - CC Version (or git hash/tag): 2.10.2
 - OS & Version: Win10, 1903
 - Graphics card: NVidia M620
 - Qt Version (if compiling): 5.10.0

**Comment by dgirardeau** [comment]
Indeed. That's fixed: aad307687a8ac0249e41e5c2b57a340c7309fa4b

Thanks for the feedback
