### ISSUE TITLE
qCSF plugin multiprocessor bug

### ISSUE THREAD

**Issue by azzoti** [CloudCompare/CloudCompare#909]
**Describe the bug**

In qCSF Cloth.cpp the uses of openmp parallel for is broken w.r.t. the use of maxDiff which cannot be accessed safely by multiple threads. This gives incorrect results for maxDiff and can cause premature termination of the cloth simulation iterations. 

	double maxDiff = 0;

      #pragma omp parallel for

	for (int i = 0; i < particleCount; i++)
	{
		if (particles[i].isMovable())
		{
			double diff = std::abs(particles[i].old_pos.y - particles[i].pos.y);
			if (diff > maxDiff)                     // can't do this in multiple threads
				maxDiff = diff;                 // can't do this in multiple threads
		}
	}

(Incidentally there is a possible solution described here (search for "max"):  
https://docs.microsoft.com/en-us/cpp/parallel/openmp/reference/openmp-directives?view=vs-2019 but I have not tested it)

**How to reproduce**

**Expected behaviour**

The results should be the same with and without parallelization. (Apart from speed!)

**Additional context**

**Your environment**
 - CC Version (or git hash/tag): Custom build from latest source of qCSF. Can't actually remember! But the bug is still here: plugins/core/Standard/qCSF/src/Cloth.cpp in the master branch. Tagged as https://github.com/CloudCompare/CloudCompare/commit/069c9451fd2af5ca1fca9fde1bfe4fe0b14e139d

 - OS & Version: Windows 10 Pro 64 bit, latest updates. 
 - Graphics card: not relevant.
 - Qt Version (if compiling): not relevant.

**Comment by azzoti** [comment]
To reproduce, you need to use a very flat point cloud and build with and without the pragma parallel for and you will see different results when running the CSF filter.

**Comment by azzoti** [comment]
Environment: I used Microsft Visual Studio 2017 community edition to build and used the "openmp" support compiler option.

**Comment by azzoti** [comment]
I suspect that given the trivial computation inside the loop, there is no point parallelizing the loop

**Comment by asmaloney** [comment]
Thanks @azzoti. Good analysis.

You might be able to fix it by identifying the critical section like this:

```c++
double maxDiff = 0;
#pragma omp parallel for
for (int i = 0; i < particleCount; i++)
{
   if (particles[i].isMovable())
   {
      double diff = std::abs(particles[i].old_pos.y - particles[i].pos.y);
      if (diff > maxDiff)
      {
         #pragma omp critical
         maxDiff = diff;
      }
   }
}
```

I don't have OMP, so I can't try it...

**Comment by azzoti** [comment]
According to the link I mentioned you need to put the pragma omp critical arround the read as well, so

double maxDiff = 0;
#pragma omp parallel for
for (int i = 0; i < particleCount; i++)
{
   if (particles[i].isMovable())
   {
      double diff = std::abs(particles[i].old_pos.y - particles[i].pos.y);
      #pragma omp critical
      {
          if (diff > maxDiff)
          {
             maxDiff = diff;
          }
      }
   }
}

But I don't its worth parallelizing the loop if you do that: too much synchnronization overhead. Just run that loop single threaded without openmp?

**Comment by asmaloney** [comment]
Yep - you're correct.

> Just run that loop single threaded without openmp?

I don't have a problem removing the OpenMP stuff here (especially since I don't compile with OpenMP on macOS :-) ).

I assume that the developer has profiled this code and that's why this is here - but maybe that's a poor assumption.

**Comment by dgirardeau** [comment]
I agree that this parallelization seems pretty useless. I would be in favor or removing it.

**Comment by dgirardeau** [comment]
Okay, I finally chose to fix the bug by removing the omp directive (I really don't think it's worth parallelizing  a max value computation). I'll update the 2.11.alpha version soon (for Windows).

Once again, thanks for the feedback!
