### ISSUE TITLE
Export PLY with FLOAT intensity to LAS, intensity will convert to int

### ISSUE THREAD

**Issue by yeluolei** [CloudCompare/CloudCompare#910]
**Describe the bug**
when export PLY with FLOAT intensity to LAS format, the intensity value will be convert to int value instead of FLOAT. thus only 0 and 1 is remain.

**Expected behaviour**

the intensity should remain to float value.

**Your environment**
 - CC Version (or git hash/tag):
2.10.2

 - OS & Version:
Windows 10 & Ubuntu 16.04

 - Graphics card: 
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
Actually that's due to LAS specifications: the intensity field is a 16 bits integer. Therefore you should multiply your scalar field by 65535 for instance (with the 'SF Arithmetic' tool) first if you want to preserve as much information as possible.

**Comment by yeluolei** [comment]
thanks! I got it!
