### ISSUE TITLE
CC command line LAS export loses info...

### ISSUE THREAD

**Issue by jgrn307** [CloudCompare/CloudCompare#915]
**Describe the bug**
I've been using CC command line to do C2C calculations, and exporting as a LAS file.  I'm noticing some important header fields are not being exported properly, specifically the LAStiling field, which allows us to "reverse" buffered tiles back to their original bounding box in LAStools.  

**How to reproduce**
Run C2C from a LASTools tiled-with-buffer file.  Here's the reference LAS file:
`lasinfo (180330) report for R:\projects\shared_data\rsdata\lidar_airborne\L3\tiled\USCAYF20180722f1a1\USCAYF20180722f1a1_tile_8500_-57500_denoised_ground_norm_classify.laz
reporting all LAS header entries:
  file signature:             'LASF'
  file source ID:             0
  global_encoding:            0
  project ID GUID data 1-4:   00000000-0000-0000-2020-202020202020
  version major.minor:        1.2
  system identifier:          'LAStools (c) by rapidlasso GmbH'
  generating software:        'lasclassify (190307) academic'
  file creation day/year:     234/2018
  header size:                227
  offset to point data:       321
  number var. length records: 1
  point data format:          1
  point data record length:   28
  number of point records:    138551
  number of points by return: 130189 8178 184 0 0
  scale factor x y z:         0.01 0.01 0.01
  offset x y z:               0 0 0
  min x y z:                  8460.00 -57415.96 771.34
  max x y z:                  9039.99 -56960.01 853.52
variable length header record 1 of 1:
  reserved             0
  user ID              'LASF_Projection'
  record ID            34735
  length after header  40
  description          'by LAStools of rapidlasso GmbH'
    GeoKeyDirectoryTag version 1.1.0 number of keys 4
      key 1024 tiff_tag_location 0 count 1 value_offset 1 - GTModelTypeGeoKey: ModelTypeProjected
      key 3072 tiff_tag_location 0 count 1 value_offset 3310 - ProjectedCSTypeGeoKey: NAD83 / California Albers
      key 3076 tiff_tag_location 0 count 1 value_offset 9001 - ProjLinearUnitsGeoKey: Linear_Meter
      key 4099 tiff_tag_location 0 count 1 value_offset 9001 - VerticalUnitsGeoKey: Linear_Meter
LASzip compression (version 3.3r0 c2 50000): POINT10 2 GPSTIME11 2
LAStiling (idx 3638, lvl 7, sub 0, bbox -10500 -84000 53500 -20000, buffer)
reporting minimum and maximum for all LAS point record entries ...
  X              846000     903999
  Y            -5741596   -5696001
  Z               77134      85352
  intensity           1         70
  return_number       1          3
  number_of_returns   1          3
  edge_of_flight_line 0          1
  scan_direction_flag 0          1
  classification      1          6
  scan_angle_rank    11         18
  user_data           0        255
  point_source_ID     0          0
  gps_time 65588.545406 65602.825731
number of first returns:        130189
number of intermediate returns: 180
number of last returns:         130278
number of single returns:       122096
overview over number of returns of given pulse: 122096 15911 544 0 0 0 0
histogram of classification of points:
           27717  unclassified (1)
           66281  ground (2)
           44254  high vegetation (5)
             299  building (6)
`
and here is the output C2C file:

`lasinfo (180330) report for R:\projects\lidarchange\als\ferguson_c2c_dist\tiled\USCAYF_tile_8500_-57500_denoised_ground_norm_classify_C2C_DIST.las
reporting all LAS header entries:
  file signature:             'LASF'
  file source ID:             48393
  global_encoding:            0
  project ID GUID data 1-4:   00000000-0000-0000-0000-000000000000
  version major.minor:        1.2
  system identifier:          'PDAL'
  generating software:        'PDAL 1.6.0 (810417)'
  file creation day/year:     119/2019
  header size:                227
  offset to point data:       473
  number var. length records: 1
  point data format:          3
  point data record length:   42
  number of point records:    138551
  number of points by return: 130189 8178 184 0 0
  scale factor x y z:         0.01 0.01 0.01
  offset x y z:               8460 -57416 771.34000000000003
  min x y z:                  8460.00 -57415.96 771.34
  max x y z:                  9039.99 -56960.01 853.52
WARNING: full resolution of min_y not compatible with y_offset and y_scale_factor: -57415.9609375
WARNING: full resolution of min_z not compatible with z_offset and z_scale_factor: 771.34002685546875
WARNING: full resolution of max_x not compatible with x_offset and x_scale_factor: 9039.990234375
WARNING: full resolution of max_y not compatible with y_offset and y_scale_factor: -56960.01171875
WARNING: full resolution of max_z not compatible with z_offset and z_scale_factor: 771.34002685546875
variable length header record 1 of 1:
  reserved             0
  user ID              'LASF_Spec'
  record ID            4
  length after header  192
  description          'Extra Bytes Record'
    Extra Byte Descriptions
      data type: 10 (double), name "C2C absolute distances", description: "", scale: 1 (not set), offset: 0 (not set)
reporting minimum and maximum for all LAS point record entries ...
  X                   0      57999
  Y                   4      45599
  Z                   0       8218
  intensity           1         70
  return_number       1          3
  number_of_returns   1          3
  edge_of_flight_line 0          1
  scan_direction_flag 0          1
  classification      1          6
  scan_angle_rank    11         18
  user_data           0        255
  point_source_ID     0          0
  gps_time 65588.545406 65602.825731
  Color R 0 0
        G 0 0
        B 0 0
number of first returns:        130189
number of intermediate returns: 180
number of last returns:         130278
number of single returns:       122096
overview over number of returns of given pulse: 122096 15911 544 0 0 0 0
histogram of classification of points:
           27717  unclassified (1)
           66281  ground (2)
           44254  high vegetation (5)
             299  building (6)
`

**Expected behaviour**
For LAS outputs, they should be carrying along all relevant header info into the new file.

**Additional context**

**Your environment**
 - CC Version (or git hash/tag): 2.11 alpha
 - OS & Version: Windows Server
 - Graphics card: Some NVIDIA
 - Qt Version (if compiling):

**Comment by jgrn307** [comment]
(Specifically the "LAStiling (idx 3638, lvl 7, sub 0, bbox -10500 -84000 53500 -20000, buffer)" part)

**Comment by dgirardeau** [comment]
I guess the 'LAStiling' field is not standard and defined as an extended field? I thought that the new LAS filter (based on PDAL) was handling extended fields properly, but I'm not 100% sure. Otherwise, it may also be because the filed is constant (all values are the same) in which case CC might discard the field (it's an optional behavior with the GUI version, but I don't know how it's defaulted in the command line).

Anyway, can you send me a sample file along with the exact command line? (to admin[at]cloudcompare.org?)

**Comment by tmontaigu** [comment]
I took a file and tiled it using LAStools' lastile, i think this is what jgrn307 used,
```
lastile -reversible -i .\some-input-file.laz -olaz -tile_size 1024
```

It seems like it creates tiles for the files where each tiles has a VLR  added by lastile and the `-reversible` makes it also add a `reversible_index_(lastile)` field to each point.

Opening then saving to LAS the tiles using CloudCompare *does*:
- remove the extra added VLR, because we don't keep vlrs, so we can't save them
- remove the extra added point field `reversible_index_(lastile)` which is strange as it is properly loaded in CC and can be viewed

**Comment by tmontaigu** [comment]
Actually, the `reversible_index_(lastile)` extra dimension is just not saved by default, you have to check a box when saving, for it  to be saved.

But i guess the CC commandline doesn't show this dialog, so we may need to change the default / add an option somewhere

**Comment by tmontaigu** [comment]
This should be fixed with the new plugin as it now does not lose vlrs and properly remember and saved extra scalar fields (even in command line)
