### ISSUE TITLE
snap Could not initialize GLX

### ISSUE THREAD

**Issue by christian-rauch** [CloudCompare/CloudCompare#916]
**Describe the bug**
After installing the snap package, CloudCompare crashes at start with:
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Could not initialize GLX
Aborted (core dumped)
```
This is related to https://github.com/CloudCompare/CloudCompare/issues/406 but in this case it is occurring in the snap package.

**How to reproduce**
1. install snap: `sudo snap install cloudcompare`
2. run snap: `cloudcompare.CloudCompare`

**Expected behaviour**
The application should start.

**Your environment**
 - OS & Version: Ubuntu 18.04 LTS
 - Graphics card: Nvidia GeForce GTX 970

**Comment by rjanvier** [comment]
Maybe it's not related but, are you using the NVIDIA driver or Nouveau?
what's the output of  `snap --version` on the command line?
thanks.

**Comment by christian-rauch** [comment]
I am using the proprietary nvidia driver version 418.

```
$ snap version 
snap    2.38.1
snapd   2.38.1
series  16
ubuntu  18.04
kernel  4.18.0-18-generic
```

**Comment by rjanvier** [comment]
I'm clueless here, I do have an NIVIDA card and i'm using 18.04 too. maybe try to update your system since I know I run it with snap 2.39 but i suspect should not do too much difference here.

**Comment by christian-rauch** [comment]
I have the same issue on a second machine with Ubuntu 18.04 + Nvidia.

This seems to be a common issue: https://forum.snapcraft.io/t/nvidia-gl-libs-access-broken-on-ubuntu-18-04.

Stellarium faced the same issue (https://forum.snapcraft.io/t/stellarium-plars-not-working-on-nvidia-cards) and solved it in https://github.com/plars/stellarium-snap/pull/2.
Could the same fix be applied to CloudCompare?

**Comment by rjanvier** [comment]
Please first update your snapd/snap version since it seems to be fixed upstream.

**Comment by christian-rauch** [comment]
The issue was from March 2018. I am sure it's fixed upstream by now. I have version 2.38, which is the latest: https://packages.ubuntu.com/bionic-updates/snapd (2.38+18.04).

**Comment by rjanvier** [comment]
do not know why I have the 2.39 here.
if it's fixed upstream it's another "bug". 
You can try the fix proposed in the other link.

**Comment by christian-rauch** [comment]
Btw, I am using the nvidia driver (418.40.04) from the [CUDA repository](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=debnetwork).
Can you reproduce the issue with this version?

I get this issue with the snap package on two distinct machines (workstation with dedicated GeForce GTX 970, laptop with Quadro K1100M) with the same Ubuntu and nvidia driver version. I can run CloudCompare from my own build and I can run other 3D software via snap (e.g. meshlab).

**Comment by EpicWink** [comment]
I have the same issue on Ubuntu 19.04, with Nvidia driver 430.09 (I've also had this issue on Ubuntu 18.10 with Nvidia driver 418, but I got it to work by down-grading the driver 410).

`snap` v2.38 is shipped with Ubuntu 19.04

**Comment by rjanvier** [comment]
Hi, thank for the feedback.
It's definitely a search path issue that occurs with third party drivers... but for now, I don't think we are doing something wrong on our side so it's maybe something we could report upstream.
anyway, I'm sorry but I won't be able to try to reproduce and try to fix this the coming days/weeks so please use official drivers or try to compile CC by yourself if you really need it, it should be straightforward with the help of the travis.yml file.

**Comment by diegodgs** [comment]
I have the same issue on Ubuntu 18.04, with Nvidia driver 430.09.
```
>$ snap --version 
snap    2.38.1
snapd   2.38.1
series  16
ubuntu  18.04
```
```
>$ nvidia-smi 
Wed May 15 14:47:31 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.09       Driver Version: 430.09       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 00000000:01:00.0  On |                  N/A |
| N/A   46C    P0    23W /  N/A |    658MiB /  6078MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

```

**Comment by christian-rauch** [comment]
If this is a snap issue, couldn't CloudCompare be published with an alternative method? E.g. via plain old deb packages or via [Flatpak](https://flatpak.org) on [Flathub](https://flathub.org/home).
Right now, snap is the only binary distribution method for CloudCompare and it obviously has some issues: https://github.com/CloudCompare/CloudCompare/labels/Linux-snap.

**Comment by rjanvier** [comment]
Compiling cc or using the driver from official repo is easy. It used to exist a Debian package for CC years ago but at the time, trying to be compatible with a lot of different version of Ubuntu was a nightmare. It should be easier now and I know @alexmyczko took my Debian source package and is planning to push it into Debian repo. For any other request (help fixing this issue,flatpack...) any help or funding is welcome because I do not have so much free time right now, i’m sorry.

**Comment by dgirardeau** [comment]
Not sure if this helps, but you may want to test this trick?
https://www.cloudcompare.org/forum/viewtopic.php?f=9&t=3721#p15357

**Comment by EpicWink** [comment]
I can confirm that CloudCompare works again on Ubuntu 19.04 with `snap` v2.39 and NVIDIA driver 430.14

**Comment by NeroBurner** [comment]
For me to make CloudCompare work I had to install the `core` snap first. I don't know why, but without it i got the following error
```
QXcbConnection: Could not connect to display :0
Aborted (core dumped)
```

Install instructions
```
snap install core
snap install cloudcompare
```

And to access removable media also connect the `removable-media` connection
```
snap connect cloudcompare:removable-media
```

maybe it helps :)

OS: Kubuntu 18.04.2 LTS
GPU: GeForce GTX 970
nvidia-version: 390.116-0ubuntu0.18.04.1
snap version: 2.39

**Comment by w4rlock999** [comment]
I had QXcbConnection: Could not connect to display :0

Funny it is resolved after I installed qt5-default on Ubuntu

**Comment by christian-rauch** [comment]
This works now after `snap` has been updated to version 2.39 on Ubuntu 18.04.

**Comment by yuqli** [comment]
I have  `snap` version 2.40 on Ubuntu 18.04 but also face this problem. Installing `qt5-default` using `apt-get` fixed the issue for me. Thanks @w4rlock999 .

**Comment by icolwell-as** [comment]
I have the same problem.
Ubuntu 18.04
Nvidia driver 440.64.00 installed via `sudo ubuntu-drivers install`.
snap version 2.43.3
Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu

> $ cloudcompare.CloudCompare
(process:5700): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Could not initialize GLX
Aborted (core dumped)

Echoing @christian-rauch's desire for a deb file, ppa, or anything other than snap.
I briefly tried compiling the source but it failed.

**Comment by NeroBurner** [comment]
@icolwell-as instructions to compile the base set of CloudCompare

```sh
sudo apt update && sudo apt install -y libqt5opengl5-dev libqt5svg5-dev qttools5-dev qttools5-dev-tools
cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${PWD}/_install"
cmake --build _build --target install -j 8
```

**Comment by alexmyczko** [comment]
it is also not very hard to do your own “simple sid backport”. If i do not forget I can ut one in my ppa and post the url.

**Comment by icolwell-as** [comment]
Thanks @NeroBurner!
I ended up coming across this [flatpack install](https://flathub.org/apps/details/org.cloudcompare.CloudCompare) that works fine for me. I'm new to flatpack but after following the setup and then the following commands, it worked quite well.

> flatpak install flathub org.cloudcompare.CloudCompare
flatpak run org.cloudcompare.CloudCompare

Now that I'm able to use it, CloudCompare is great! Excellent software.

**Comment by christian-rauch** [comment]
@alexmyczko Given the idea of snaps (and other package formats) as a way to simply install and use a program, manually compiling and backporting debs is not an option. If users would compile all the software they use, they wouldn't ask for snap, flatpak or deb packages.

In the meantime, you can try out the [CloudCompare flatpak](https://flathub.org/apps/details/org.cloudcompare.CloudCompare) and check if it solves your GLX issue.
