### ISSUE TITLE
Run CloudCompare from the build path

### ISSUE THREAD

**Issue by christian-rauch** [CloudCompare/CloudCompare#917]
**Describe the bug**
I cannot load STL files with versions above 2.10.2

**How to reproduce**
1. build 2.10.2 from scratch
2. drag&drop a STL file
3. observe that file is opened
4. build master from scratch
5. drag&drop a STL file
6. observe that error is given

**Expected behaviour**
Versions above 2.10.2 should open STL files.

**Your environment**
 - CC Version (or git hash/tag): 50e94e837f7abc44fd221609ec80a0d43a6ef413
 - Qt Version (if compiling): 5.9.5

**Comment by asmaloney** [comment]
Does it open the file if you open it using the menu instead of D&D?

Since it's D&D-related, the OS is important - what OS are you using?

**Comment by christian-rauch** [comment]
I think it's unrelated to the drag&drop functionality itself.

OS: Ubuntu 18.04 LTS

The file menu only offers PLY meshes. When forcing a STL file I get:
`[Load] Can't guess file format: unhandled file extension 'STL'`

**Comment by asmaloney** [comment]
Is the qCoreIO plugin being built and installed properly? That's where STL handling lives now.

`PLUGIN_IO_QCORE` should be on in cmake.

**Comment by christian-rauch** [comment]
Yes, it's active in the `CMakeCache.txt`:
```
//Check to install the CoreIO plugin
PLUGIN_IO_QCORE:BOOL=ON
```

**Comment by asmaloney** [comment]
And is it being built and installed properly?

Does it show up in the list of plugins (_About plugins..._ menu item - not sure where it is on Linux)? If so is it checked?

**Comment by asmaloney** [comment]
You should also see something like this in the console:

```
[13:27:42] [Plugin][Core I/O] New file extensions registered:  GEOREF MA OBJ OFF PDMS PTX SBF STL VTK
```

**Comment by christian-rauch** [comment]
Right, that's the issue. CloudCompare is only searching in these paths: 
```
/usr/local/lib/cloudcompare/plugins
/home/christian/.local/share/CCCorp/CloudCompare/plugins
/home/christian/.local/share/flatpak/exports/share/CCCorp/CloudCompare/plugins
/var/lib/flatpak/exports/share/CCCorp/CloudCompare/plugins
/usr/share/ubuntu/CCCorp/CloudCompare/plugins
/usr/local/share/CCCorp/CloudCompare/plugins
/usr/share/CCCorp/CloudCompare/plugins
/var/lib/snapd/desktop/CCCorp/CloudCompare/plugins
```
but not in the build space, that is created by CMake.

I need to properly install via `sudo checkinstall` to have the plugins placed at these locations.

**Comment by christian-rauch** [comment]
Is there a way to have it search relatively to the executable location so that it can be used without installing it? E.g. by adding `../libs/qCC_io/` to the list of search paths.

**Comment by asmaloney** [comment]
As a general case (i.e. always look there), I would have to leave it to @rjanvier since that's a Linux-specific issue.

To make make "build & run" easier though, one thing we could do is add a cmake option to add the path where the plugins are built. This would mean passing the path from cmake and using it when building the list of paths. Essentially generalizing the `CC_MAC_DEV_PATHS` I have in there for macOS.

**Comment by rjanvier** [comment]
Thanks you very much Christian.
it should work if you run `make && make install` (I agree I will not be ok on non standard prefix ;)). 
As a rule of thumb I avoid as much as possible to get my hand dirty will build systems (CMake) unless something is *really* broken. So feel free to follow the lead that @asmaloney gave you if you want to propose some changes in that direction.

**Comment by christian-rauch** [comment]
It would be useful if you can run CloudCompare straight from where ever it is located. This makes development easier (build & test without install) and also allows to have a to-go version that can be run by a user without administrator privileges.

**Comment by rjanvier** [comment]
My bad, I think the search path is already relative to CC binary, so you can use any prefix you want (even a "local" ones). feel free to improve the build system to be able to launch CC from the build directory but I don't think it really worth it.

**Comment by chunibyo-wly** [comment]
Thanks for contribution, [CC_PLUGIN_PATH](https://github.com/CloudCompare/CloudCompare/blob/master/BUILD.md#debugging-plugins) saves my day.

My solution is make install plugin first and set **CC_PLUGIN_PATH** to installed plugin path, and then I can use CLion to debug this project. And if want to debug plugin, I think the best way is to append build path to **CC_PLUGIN_PATH**.
