### ISSUE TITLE
Is it possible to explicitly call method from CloudSamplingTools.cpp , if possible then please give a code snippet.

### ISSUE THREAD

**Issue by shalinsirwani** [CloudCompare/CloudCompare#918]
I successfully compiled CC_CORE_LIB project of cloud compare. But now i have to use some methods of subsampling directly (like this one "resampleCloudSpatially"). 

If possible then please provide an example , how actually i load the cloud , then provide to this function..

Or

How i call this function from command without any prompt and with desired output file name instead of year_month_date_time.bin.

**Comment by dgirardeau** [comment]
Well yes. And you have the whole project repository as example :D

For the first one, just search for 'resampleCloudSpatially' in the repository (it's used in several places). And for loading a cloud, it's not done by CC_CORE_LIB (but by qCC_db). However once again there are many examples that should how to populate a cloud (actually it's simple, just 'reserve' the right number of points, and then 'add' the points one by one).
