### ISSUE TITLE
Calling resampleCloudSpatially from command line

### ISSUE THREAD

**Issue by shalinsirwani** [CloudCompare/CloudCompare#919]
How i call this function resampleCloudSpatially from command without any prompt and with desired output file name instead of year_month_date_time.bin

I have look into the documentation. But there is no command which stores the output with desired name. 
> https://www.cloudcompare.org/doc/wiki/index.php?title=Command_line_mode

**Comment by shalinsirwani** [comment]
By this way we can call resampleCloudSpatially method "C:\\Program Files\\CloudCompare\\cloudcompare\" -C_EXPORT_FMT ASC -O  area.txt -SS SPATIAL  1.00

BUT THE PROBLEM IS, THERE IS NO COMMAND FOR SAVING OUTPUT FILE WITH DESIRED NAME..

**Comment by dgirardeau** [comment]
I think there is an option: see the 'FILE' sub-option of the '-SAVE_CLOUDS' option (https://www.cloudcompare.org/doc/wiki/index.php?title=Command_line_mode)
