### ISSUE TITLE
How to display an curve from PLY file

### ISSUE THREAD

**Issue by sunstarchan** [CloudCompare/CloudCompare#921]
**Describe the feature you would like**
I have a curve with sample points in PLY file, and I can use cloud compare to disable the sampled points. but how can I render it as a curve line without gap. 

**Describe alternatives you've considered**

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by dgirardeau** [comment]
On "trick" to do this would be to save the points (cloud) as an ASCII file, then change the extension as "poly" and then reload the file in CC. It will then be loaded as a polyline.
