### ISSUE TITLE
RANSACSDlib compilation fails for arm

### ISSUE THREAD

**Issue by christian-rauch** [CloudCompare/CloudCompare#925]
The compilation on the arm architecture on master (0c0fca2704218eb570af13a46aac2f1010796180) fails with:
```
In file included from /run/build/CloudCompare/plugins/core/Standard/qRANSAC_SD/RANSAC_SD_orig/MiscLib/Vector.h:3,
                 from /run/build/CloudCompare/plugins/core/Standard/qRANSAC_SD/RANSAC_SD_orig/Bitmap.h:3,
                 from /run/build/CloudCompare/plugins/core/Standard/qRANSAC_SD/RANSAC_SD_orig/Bitmap.cpp:1:
/run/build/CloudCompare/plugins/core/Standard/qRANSAC_SD/RANSAC_SD_orig/MiscLib/AlignedAllocator.h:9:10: fatal error: xmmintrin.h: No such file or directory
 #include <xmmintrin.h>
          ^~~~~~~~~~~~~
compilation terminated.
```

See https://flathub.org/builds/#/builders/6/builds/341/steps/7/logs/stdio for details.

**Comment by asmaloney** [comment]
Some potentially useful info for a fix:

https://stackoverflow.com/questions/11228855/header-files-for-x86-simd-intrinsics/22291538#22291538

**Comment by dgirardeau** [comment]
I never heard about anyone compiling CC on an arm architecture anyway. But at least one easy option is to avoid compiling this plugin...

**Comment by WargodHernandez** [comment]
> I never heard about anyone compiling CC on an arm architecture anyway. But at least one easy option is to avoid compiling this plugin...

I have been using Cloud Compare on an NVidia Jetson TX2 which is an ARM system, compiled from source on device. I haven't moved onto Zephyrus on it yet but previous releases (2.9 & 2.9.1) were a joy to compile. Also the performance of the compiled app actually seems to outperform my more powerful Windows x86 hardware for some CC tasks.

**Comment by rjanvier** [comment]
btw, qRANSACSD license is not compatible with GPL...

**Comment by christian-rauch** [comment]
> btw, qRANSACSD license is not compatible with GPL...

According to the header:
https://github.com/CloudCompare/CloudCompare/blob/8b94e0cd9da0b8110146ec981833116e09109789/plugins/core/Standard/qRANSAC_SD/qRANSAC_SD.h#L1-L16
It is directly licensed under GPL2.
Is this wrong? What would be the correct license?

Is there an overview which plugins are compatible with the GPL? This is important to know for distributing compiled versions.

**Comment by rjanvier** [comment]
qRANSAC itself is "Research only"

**Comment by dgirardeau** [comment]
Yes, there's the plugin code itself (which is GPL, and has been written by us) and the RansacSD library which is a 3rd party library that is used by the plugin. I know it's silly...

Otherwise most of the plugins are GPL.

**Comment by rjanvier** [comment]
CGAL has a GPL equivalent but without the optional non linear refinement  of fitted shapes (which is used by default in the current qRANSACSD plugin).
