### ISSUE TITLE
Cannot build 2.10.x with E57

### ISSUE THREAD

**Issue by christian-rauch** [CloudCompare/CloudCompare#926]
I am not able to build CloudCompare with E57 support from branch `v2.10.x` (354eea9e210405d19f6afd617b5dad43495d8611).

Compiling with:
```
git clone https://github.com/CloudCompare/CloudCompare.git -b v2.10.x --recursive
cd CloudCompare && mkdir build && cd build
cmake -DOPTION_USE_LIBE57FORMAT=ON ..
```
fails with:
```
CMake Error at contrib/E57Support.cmake:95 (message):
  No libE57Format install dir specified (LIBE57FORMAT_INSTALL_DIR)
Call Stack (most recent call first):
  contrib/AllSupport.cmake:33 (target_link_LIBE57FORMAT)
  ccViewer/CMakeLists.txt:69 (target_link_contrib)
```
but the `contrib/libE57Format` submodule is checked out:
```
$ ls contrib/libE57Format/
CHANGELOG.md  CMakeLists.txt  include     README.md
cmake         contrib         LICENSE.md  src
```

Since the submodule is checked out, I assume that `LIBE57FORMAT_INSTALL_DIR` should be set automatically to the correct path.

**Comment by dgirardeau** [comment]
It could be defaulted to a path indeed. However you have to compile LibE57Format first and then the compiled files + header files will be installed (copied) to the 'installation folder'... which is different depending on the OS (on Windows typically you have to change it manually to something less silly than 'Program Files' which is the default for CMake... so it's hard to predict where it will end). I guess it should be easier to predict on Linux?

So in the end as for most of the 3rd party libraries we let the user choose the installation folder, compile the 3rd party library, and then set the right path when generating CC's solution.

**Comment by rjanvier** [comment]
on linux it can be set to std directories like `install_prefix/lib` and `instrall_prefix/include`

**Comment by christian-rauch** [comment]
I think it's pretty standard to use third party libs in CMake.
Option A: Use git submodules and add the subdirectory to CMake. In this case, all the libraries and include directories of the subproject should be known to cmake. This is how it's done currently, but the main project doesn't know about the subprojects libs and includes. It should not be required to specify the location of the libs and includes.
Option B:  Use [`ExternalProject_Add`](https://cmake.org/cmake/help/latest/module/ExternalProject.html) to fetch, build and install a third party project. This can be used for non-CMake projects.

**Comment by asmaloney** [comment]
E57 has been moved to its own plugin [on master](f0400dd0193e5e81484f5bc7bbceb2c1a8856a4b). There it uses a submodule which does not require any extra steps.

This isn't something that I plan to backport to the 2.10.x branch since plugins have changed a lot.

My suggestion would be to either disable E57 if you don't want to build it separately or use the master branch.
