### ISSUE TITLE
Trace Polyline with Oversample Bug

### ISSUE THREAD

**Issue by mconley928** [CloudCompare/CloudCompare#927]
When tracing a polyline using the "Trace Polyline" tool with the "oversample" functionality on a single point cloud, if the view is rotated or translated during the picking of the polyline vertices, the final result includes a random jump after the oversampling takes place. If you do not rotate the view, the polyline tool and oversample function work as expected giving the intended result.    

To reproduce:
Steps to reproduce the behavior - include images if relevant:
1. Open a point cloud and invoke the Trace Polyline command, (Tools > Trace Poly or hotkey ctr+P) 
2. Increase the "oversampling" to 10
3. Start selecting points/vertices in a strait line (be careful not to click and drag which rotates the view)
4. After selecting 6 or 7 points, rotate the view by clicking and dragging (the bigger the rotation the bigger there error) 
5. Continue to select 6 or 7 points along the intended straight line
6. Finish the Trace poly command by selecting the check mark, wait for the oversample, and notice that the somewhat straight line traced now has a major jump or jog. 
-->

Here are some examples:
White lines are created using CC polyline tool, red arrows show max point of deviation with the tan dashed line showing intended path:
![image](https://user-images.githubusercontent.com/52224395/60144728-66ea1f80-9778-11e9-803f-08ac03e00854.png)

Green line showing during tracing, and white line final output, white arrow shows last point picked before view rotation:
![image](https://user-images.githubusercontent.com/52224395/60144956-4373a480-9779-11e9-9918-8e47a4e775e7.png)
![image](https://user-images.githubusercontent.com/52224395/60144983-5d14ec00-9779-11e9-99d1-40c2f47bdcf8.png)

Any help resolving this bug would be great! This is essential to my workflow.

My environment
 - CC Version (or git hash/tag): v2.10.2 (64bit) also on alpha version as of 6/25/2019 
 - OS & Version: Windows 10 Pro 64-bit (10.0, Build 17134) (17134.rs4_release.180410-1804)
 - Graphics card: NVIDIA GeForce GTX 1050 Ti
 - Qt Version (if compiling): N/A
 - Seems that this bug persists across multiple environments

**Comment by dgirardeau** [comment]
Indeed, the picking process uses the current view orientation when in standard mode. And when applying 'oversampling', CC reuse the view orientation that was used when picking each point (as it can change a lot of things, and we the user is supposed to have chosen the orientation for some reasons).

So the segment that was created just after moving the camera has one vertex acquired with one position of the camera, and one with another (potentially very different). How this particular segment is processed can be tricky. And apparently it doesn't work that well :D.

I updated the algorithm, hoping it will be a little bit smarter (it actually assume the camera orientation of the second vertex is more important in this case, as the user changed the camera orientation before clicking on the second vertex). You can test the newest 2.11.alpha version online.
