### ISSUE TITLE
hello,any guys know the CC use which formula to compute Gauss curvature?

### ISSUE THREAD

**Issue by sherrylongfan** [CloudCompare/CloudCompare#928]
**Describe the bug**

**How to reproduce**

**Expected behaviour**

**Additional context**

**Your environment**
 - CC Version (or git hash/tag):
 - OS & Version:
 - Graphics card: 
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
It is derived from "CURVATURE OF CURVES AND SURFACES – A PARABOLIC APPROACH" by ZVI HAR’EL

See the implementation here: https://github.com/CloudCompare/CloudCompare/blob/002e246936f113a2625dd2fe83d19a73d5fce257/CC/src/Neighbourhood.cpp#L974

**Comment by sherrylongfan** [comment]
Thank you so much!!!!
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Daniel Girardeau-Montaut"<notifications@github.com>;
 发送时间: 2019年6月28日(星期五) 下午5:59
 收件人: "CloudCompare/CloudCompare"<CloudCompare@noreply.github.com>;
 抄送: "Sherry"<1445966987@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [CloudCompare/CloudCompare] hello,any guys know the CC use whichformula to compute Gauss curvature? (#928)

 

 
Closed #928.
