### ISSUE TITLE
roughness

### ISSUE THREAD

**Issue by sherrylongfan** [CloudCompare/CloudCompare#929]
excuse me,could you tell me the paper about computing the roughness in CC?

**Comment by dgirardeau** [comment]
No paper. Just a simple algorithm suggested by Dimitri Lague ([https://geosciences.univ-rennes1.fr/interlocuteurs/dimitri-lague](url)) some time ago.  See [http://www.cloudcompare.org/doc/wiki/index.php?title=Roughness](url)

**Comment by sherrylongfan** [comment]
thank you very much!
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Daniel Girardeau-Montaut"<notifications@github.com>;
 发送时间: 2019年7月2日(星期二) 凌晨4:34
 收件人: "CloudCompare/CloudCompare"<CloudCompare@noreply.github.com>;
 抄送: "Sherry"<1445966987@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [CloudCompare/CloudCompare] roughness (#929)

 

 
No paper. Just a simple algorithm suggested by Dimitri Lague (https://geosciences.univ-rennes1.fr/interlocuteurs/dimitri-lague) some time ago. See http://www.cloudcompare.org/doc/wiki/index.php?title=Roughness
