### ISSUE TITLE
Cant start CC with remote desktop on latest CPU/GPU from 2018

### ISSUE THREAD

**Issue by noreye** [CloudCompare/CloudCompare#930]
Hi,

I see that there are a number of posts already about CloudCompare versions greater than 2. 6.3 not starting with remote desktop are mainly due to the OpenGL version being out of date. 

My remote computer is a i7 8700k, NVIDIA RTX 2070, 32gb ram, NVME ssd win 10 and both CPU/GPU were released in 2018. The OpenGL version is 4.6 if I am not mistaken. I have the latest drivers installed.

I was wondering if there are any suggestions to get this setup to work via remote desktop? I am currently using 2.6.3 and it is very slow/lag over remote desktop while on my local computer (i7-4770s, HD4000 graphics, 16gb ram, Sata SSD, macOS 10.13.6) is way faster and responsive using the exact same dataset. 

When I try to start CC on my remote desktop using the 2.11 beta, I dont  get the CC splash screen but I get an error message saying OpenGL is too old. When I try with the 2.10 version, I dont get any messages at all. I will not be physically located in the same space as this computer for a few weeks so I am not able to check to start up the program. 

I have tried the suggestions in this thread to enable RDP graphics to no avail :(
https://social.technet.microsoft.com/Forums/en-US/e139ec92-90d0-4639-a3b5-5a5a4a5b6a79/hardware-support-gpu-on-rdp-connection-to-windows-10-professional?forum=winRDc

Anyone have suggestions that I may have missed?

**Comment by noreye** [comment]
I finally got it working!

For anyone else having issues using remote desktop with CC >2.6.3. The solution that worked for me was to use a VNC connection instead of an RDP connection. I used TightVNC as the VNC server and it worked like a charm! 

Hope this helps someone other there.

**Comment by dgirardeau** [comment]
Thanks for the feedback!

**Comment by noreye** [comment]
No problems! Thanks for maintaining CC :)

I forgot to mention that I also went into the NVIDIA control panel -> Manage 3D settings -> Program Settings -> Add -> CC and then set the OpenGL rendering GPU to RTX 2070.
