### ISSUE TITLE
"no name" when file filter doesn't set object name

### ISSUE THREAD

**Issue by WargodHernandez** [CloudCompare/CloudCompare#932]
**Describe the bug**

During file loading if the IOFilter does not set a name for the object it loads the FileIOFilter class fails to rename the object as the name is empty when checked. Previously the object would have defaulted to "unnamed" and then replaced with the base file name.

**How to reproduce**
Load a PCD file 

**Expected behaviour**
Cloud should be named with the base file name instead of "no name"

**Additional context**

**Your environment**
 - CC Version (or git hash/tag): Commit add17ce2
 - OS & Version: Windows 10
 - Graphics card: Quadro M2200/PCIe/SSE2
 - Qt Version (if compiling): 5.11.2

From qCC_io/FileIOFilter.cpp ~line 362
``` C++
if (newName.startsWith("unnamed"))
			{
				//we automatically replace occurrences of 'unnamed' in entities names by the base filename (no path, no extension)
				newName.replace(QString("unnamed"), fi.baseName());
				child->setName(newName);
			}

```
 
I suggest adding 
``` C++
if (child->getName().isEmpty())
			{
				child->setName(fi.baseName());
			}

```

**Comment by dgirardeau** [comment]
Good points. I fixed the PCD I/O filter (so that it doesn't output a cloud with an empty name). But I also added your suggestion as a fallback strategy.

**Comment by dgirardeau** [comment]
See 54af686d1d647d753b24a96099c5f0d5d34f2d96
