### ISSUE TITLE
complie CC fail by VS2013 update5 

### ISSUE THREAD

**Issue by Shen001** [CloudCompare/CloudCompare#933]
i try  compiling CC by VS2013 update5 but it seems dont work because of "constexpr",but "BUILD.md" says it supports Visual 2013 and newer,i should use Visual 2015 or newer?

**Comment by WargodHernandez** [comment]
Although msvc 2013 supports c++ 11 it does not support all features of it.
According to https://docs.microsoft.com/en-us/previous-versions/hh567368(v=vs.140)#featurelist constexpr is not supported in msvc 2013, 2015 is the earliest.

**Comment by dgirardeau** [comment]
Yes, I'm afraid Visual 2013 is not an option anymore to compile the latest versions of CC...

**Comment by Shen001** [comment]
thanks~

**Comment by EpicWink** [comment]
The "constexpr" error could also be #848
