### ISSUE TITLE
Bundler import broken

### ISSUE THREAD

**Issue by PaulDebus** [CloudCompare/CloudCompare#934]
**Describe the bug**
When opening a bundler file and a corresponding list.txt file with `Import Images` activated and colored model generation selected, cloudcompare crashes with an assertion error. Opening a file without loading the images works fine.

**How to reproduce**
1. Open a bundler file with the corresponding images available
2. Check the `Import Images` and `Colored model generation` options
3. See error
```
CloudCompare: /home/paul/repos/trunk/plugins/core/IO/qAdditionalIO/src/BundlerFilter.cpp:1047: CC_FILE_ERROR BundlerFilter::loadFileExtended(const QString&, ccHObject&, FileIOFilter::LoadParameters&, const QString&, bool, bool, unsigned int, float): Assertion `mntSamples && mntColors' failed.
```

**Expected behaviour**
The file should be opened and the cameras should be loaded

**Additional context**
On previous versions (I do not remember which though) installed via snap, the import did work fine. I tested several files, created with Agisoft Metashape and Colmap, and they all showed the same behaviour. 

**Your environment**
 - CC Git hash: add17ce2789689131b67f42068a9add358b92f5b
 - OS & Version: Pop OS 19.04
 - Graphics card: NVidia RTX 2080ti
 - Qt Version (if compiling): 5.12
- Built with cmake options `PLUGIN_IO_CORE`, `PLUGNI_IO_QADDITIONAL`, `PLUGIN_IO_PHOTOSCAN`, `

I can provide the models I used while discovering the crash. Also while I have not worked on CC yet, I would like to support in any way I can, as it is a vital tool for me, so if there is anything I can do or test, just let me know.

**Comment by dgirardeau** [comment]
Actually the code still works on my side, but you could indeed trigger this assert if the mesh creation failed. Can you see any warning message in the Console before this assert is triggered? Or can you share the file with me maybe?

Anyway, for now I patched the code so that this case is more properly handled (ffb511cee6a34d1ae566d5b4e1f9039e6066ce04).

**Comment by PaulDebus** [comment]
I rebuilt from ffb511c and now it does not crash anymore but shows `[10:45:20] [Bundler] Failed to generate DTM! (CGAL library not supported)` in the console, which explains the crash and seems to be exactly related to what you mentioned. Sadly, I am not able to build CC with CGAL enabled, due to #848 (the problem with CGAL and floating points). 

While CC does not crash anymore on ffb511, it still does not load the camera positions into the viewer. Is this all related to CGAL or am I still missing something.

Thanks for the support and the awesome tool!

**Comment by dgirardeau** [comment]
There shouldn't be any correlation. Have you checked the "keep images (and sensors) loaded" option? And does it help if you uncheck the "Colored model generation"? (I guess this is the option that requires CGAL)

**Comment by PaulDebus** [comment]
Yes, you are right. Checking "keep images (and sensors) loaded" produces the desired result, while the colored model is the option, that produces the error message - which prior to your recent change would have produced a crash - about not finding CGAL. I still cannot compile CC with CGAL enabled, due to #848 but this is a different issue.

So thanks for your support, I think ffb511c fixed the crash issue for me.
