### ISSUE TITLE
Cross section tool - clipping box moves even if no changes are made in the advanced menu

### ISSUE THREAD

**Issue by seashrimp2** [CloudCompare/CloudCompare#940]
Hi,

I have noticed some strange behavior of the cross section tool. When the clipping box is interactively adjusted and then “advanced” settings are used, the box moves even if there are no manual changes made in the advanced menu.  

Steps to reproduce:
(Tested under Windows 7 in the current CC version 2.10.2, as well as 2.11-alpha.)
1) Load a point cloud, start cross section tool 
2) Interactively adjust the clipping box by dragging the arrows, and rotate it using the torus around any of the arrows
3) Change the size of the box again by dragging any of the arrows
4) Click “advanced” button, but do not make any changes
5) Click “ok”

I would expect the clipping box to remain unchanged (at the same position), since no manual changes are made in the advanced menu. However, position of the box moves after the ok button is clicked.

This only seems to happen when the clipping box is rotated (when no rotation is applied the issue does not seem to emerge). 

I have tried to search for this in documentation (http://www.cloudcompare.org/doc/wiki/index.php?title=Cross_Section) but I could not find anything.

Could it be a bug in the clipping tool? Or is there some explanation for this behavior?

**Comment by dgirardeau** [comment]
Hi,

I haven't been able to reproduce the issue... What is the magnitude of the coordinates of your point cloud?

**Comment by seashrimp2** [comment]
The size of the original point cloud is approximately 17x4x17 and I first noticed the behavior with a clipping box of dimensions around 1x1x1. I have now tried to reproduce the issue with the Stanford bunny model and it still seems to be happening. 
![bunny](https://user-images.githubusercontent.com/54067587/63420439-f1f93600-c406-11e9-9fc2-7b916ca5fbe0.gif)

**Comment by dgirardeau** [comment]
Hum, with the Stanford Bunny, I did manage to reproduce the issue!

Le mer. 21 août 2019 à 11:32, seashrimp2 <notifications@github.com> a
écrit :

**Comment by dgirardeau** [comment]
Ok, normally it's fixed (f5c20965ac6b644ac2c20567c112cab2404ac45f).

Thanks for the feedback.
