### ISSUE TITLE
M3C2 from command line always use sub sampling

### ISSUE THREAD

**Issue by danielfeldman** [CloudCompare/CloudCompare#942]
**Describe the bug**
When running M3C2 from command-line seems like SubsampleEnabled param is ignored - subsampling will occur either way.

**How to reproduce**
- I am running CloudComapre command-line interface like that "/snap/bin/cloudcompare.CloudCompare -O target_cloud.ply -O source_cloud.ply -M3C2 m3c2_params.txt"
- m3c2_params.txt was created using the GUI interface
- I checked both with setting "SubsampleEnabled" param to false and true (directly in m3c2_params.txt), both cases lead to subsampled cloud.
- My solution was to set very low SubsampleRadius, so subsampling not actually occurs.

**Expected behavior**
I expect that when setting "SubsampleEnabled" to false, subsampling will not occur.

**Your environment**
 - CC Version (or git hash/tag): 2.10.1
 - OS & Version: Ubuntu 17.10
 - Qt Version (if compiling): 5.5.1

**Comment by dgirardeau** [comment]
Ok I think I fixed the bug: 057e101e9accf0840a5ef564201317c804f59b97

I'll let you test. And thanks for the feedback ;)
