### ISSUE TITLE
Missing fields of the PCD file in Cloud Compare

### ISSUE THREAD

**Issue by Dinatorehanova** [CloudCompare/CloudCompare#943]
Does cloud compare only shows the x,y,z,intensity values ? When I am opening my pcd file in the cloud compare it just shows the value of my (x,y,z, and intensity) but my original pcd file contains many other fields ( (timestamp,ring,noise, range, reflectivity).

This is my original pcd file opened in text editor containing all the fields.

![image](https://user-images.githubusercontent.com/51459647/63789502-bc47c780-c8b4-11e9-881e-ae9c8c0712eb.png)

My pcd file in the cloud compare.

![image](https://user-images.githubusercontent.com/51459647/63789526-cb2e7a00-c8b4-11e9-8854-6d1ac4af9323.png)

Any help will be greatly appreciated.

Thanks

**Comment by dgirardeau** [comment]
Have you tried to change the active 'scalar field'? (in the cloud properties - when you select it in the DB tree)

**Comment by dgirardeau** [comment]
Well I guess it depends where you click? Looking at the histogram, it seems quite some values are zero:
![image](https://user-images.githubusercontent.com/2735509/63806590-38292a80-c91c-11e9-92d0-9a2c0f75c8f8.png)

And here is what I see on my side (noise SF, with version 2.11 alpha)
![image](https://user-images.githubusercontent.com/2735509/63806374-bf29d300-c91b-11e9-8d8c-c81c905dc4d4.png)
