### ISSUE TITLE
Point cloud fusion algorithm

### ISSUE THREAD

**Issue by wang9964** [CloudCompare/CloudCompare#944]
Hello, Is your  point cloud fusion step on this code?ccPointCloud.cpp line 526 to line 1066
`
const ccPointCloud& ccPointCloud::append(ccPointCloud* addedCloud, unsigned pointCountBefore, bool ignoreChildren/*=false*/)
 {
 assert(addedCloud);
unsigned addedPoints = addedCloud->size();
......
 }
`
And I want to know what is your point cloud fusion algorithm? Can you give me the paper or link?  Thank you very much

**Comment by dgirardeau** [comment]
Well, more than "fusion" it's simply "concatenation" (so nothing fancy here).

If you want to remove duplicate points afterwards (in case of overlap), then you should look at the 'Remove duplicate points' method (https://www.cloudcompare.org/doc/wiki/index.php?title=Remove_duplicate_points). It relies on the octree structure if I remember well.
