### ISSUE TITLE
is any way to load 600millions point cloud？

### ISSUE THREAD

**Issue by windcatcher** [CloudCompare/CloudCompare#945]
is any way to load 600millions point cloud？

i want to load 600millions points in cloudcompare ，but i does not work well

**Comment by dgirardeau** [comment]
Yes, as long as you have enough memory and a good graphic card, no problem. If you don't have a good graphic card, then you have to enable the LOD mechanism (and be patient until it finishes to compute after you load the cloud ;).

But if you don't have enough memory, you are stuck!

**Comment by windcatcher** [comment]
thanks,will you improve the perfermance for loading point clould in the future? has any plan?

**Comment by dgirardeau** [comment]
Do you mean enhance the LOD mechanism? Maybe (but not in a near future). Otherwise most of the job is done by the graphic card...
