### ISSUE TITLE
Conversion between multiple pcd files into csv files

### ISSUE THREAD

**Issue by Dinatorehanova** [CloudCompare/CloudCompare#946]
Hi, Can anyone please help me on this issue

Is it possible to convert multiple pcd files into multiple csv files by a single operation via cloud compare ?

Thanks

**Comment by dgirardeau** [comment]
I believe if you select multiple clouds (after having loaded all your PCD files) and attempt to save them as an ASCII/TEXT file (with the CSV extension and the right delimiter, etc.). In this case CC will create one file for each cloud.
