### ISSUE TITLE
Changing LiDAR Coordinate into WGS 1984

### ISSUE THREAD

**Issue by Dinatorehanova** [CloudCompare/CloudCompare#947]
Hi,

I have some raw LiDAR data collected with mobile LiDAR platform. Now, I would like to define the coordinate system of my point clouds into wgs 1984 so that it overlaps with the corresponding real world place. Is it possible to do it in the cloud compare ? can anyone please advice me on this ?
Any help would be very appreciated.

Thanks.

**Comment by dgirardeau** [comment]
If you want to do that, you will need some "ground control points" (points that are visible in your cloud and for which you know the absolute coordinates. If you have enough of them (theoretically 3, but I would suggest using more, like 6 or 7, and as widespread over the cloud as possible), then you can use the 'Align' tool, were you pick the points in your cloud, and input the equivalent WGS coordinates for each of them (see https://www.cloudcompare.org/doc/wiki/index.php?title=Align).
