### ISSUE TITLE
Snapcraft version lags behind (2.10.1) 

### ISSUE THREAD

**Issue by NeroBurner** [CloudCompare/CloudCompare#949]
The published snap was updated 16 January 2019 with version `2.10.1`

Could you update the stable branch to the latest release `2.10.3`?

And maybe also consider to build the snap with every commit (add it to travis) and publish it to the `edge` branch?

**Comment by dgirardeau** [comment]
I would have assumed the 'edge' branch would do that. We'll need a snap expert to fix that otherwise? (= not me :D )

**Comment by rjanvier** [comment]
Sorry I do not have time to maintain CC snap package as I would love to do. The travis pipeline you mentionned used to be our way to go, but things got broken and changed on Travis and on Cannonical's side. If you want, someone made a flatpack for CC and it's more up to date right now. You could find it here https://flathub.org/apps/details/org.cloudcompare.CloudCompare. Else 2.10.1 is not so bad ;) and you'll have to wait a couple of week for the update.

**Comment by NeroBurner** [comment]
snapcraft offers the build and publish on their side without the need of travis https://snapcraft.io/build
maybe you could use snapcraft.io directly

or we could take some inspiration from the Remmina CI. It uses docker container and therefore should be CI-provider independent
https://gitlab.com/Remmina/Remmina/blob/master/.gitlab-ci.yml#L118

**Comment by rjanvier** [comment]
thanks, feel free to make pull requests if you want. BTW I need to update to snapcraft 3+ and there will be a bit of work.

**Comment by alexmyczko** [comment]
why do the flatpak guys call it version 2.11???

**Comment by rjanvier** [comment]
There is a new version of the snap in the edge channel, @NeroBurner could you help to test it please?
thank you.

**Comment by NeroBurner** [comment]
thanks for the new snap version!

I can download it and open it. When adding self compiled rdbIO plugin and librdb dependency file loading works and the pointcloud is rendered. Zooming with middle mouse button works

anything else you'd like tested?

**Comment by rjanvier** [comment]
Thanks a lot!
Anything you like ;) 
I close this issue for now. I mostly use "self-compiled" version of CC on my side, so do not hesitate to open other issues if you find some.
