### ISSUE TITLE
ccPlane normal vector not updated on setGLTransformation

### ISSUE THREAD

**Issue by NeroBurner** [CloudCompare/CloudCompare#951]
**Describe the bug**
`Primitive` attributes like normal vector are not updated on `setGLTransformation` when creating a `ccPlane`. The view shows the correctly transformed `ccPlane` objects and normal vectors

**How to reproduce**
Working code:
```cpp
        Vector3Tpl<float> X(plane_side);
        Vector3Tpl<float> Y(plane_up);
        Vector3Tpl<float> Z(plane_norm);
        Vector3Tpl<float> t(
                    static_cast<float>(buffer_xyz[i][0]),
                    static_cast<float>(buffer_xyz[i][1]),
                    static_cast<float>(buffer_xyz[i][2]));
        ccGLMatrix mat(X, Y, Z, t);
        // create plane patch
        ccPlane *plane = new ccPlane(
                    static_cast<PointCoordinateType>(buffer_plane_width[i]),
                    static_cast<PointCoordinateType>(buffer_plane_height[i]),
                    &mat);

```

split ccPlane construction to use `setGLTransformation` to get non-working code
```cpp
        ccPlane *plane = new ccPlane(
                    static_cast<PointCoordinateType>(buffer_plane_width[i]),
                    static_cast<PointCoordinateType>(buffer_plane_height[i]));
        plane->setGLTransformation(mat);
```

![Screenshot_20190903_100437](https://user-images.githubusercontent.com/9076163/64154990-3edf0280-ce32-11e9-9548-62df3929b404.png)

**Expected behaviour**
normal vector set correctly like when passing matrix to `ccPlane` constructor
![Screenshot_20190903_095156](https://user-images.githubusercontent.com/9076163/64154834-e445a680-ce31-11e9-9f05-555cefa51e96.png)

**Your environment**
 - CC Version (or git hash/tag): 2.10.1 (snap package)
 - OS & Version: Kubuntu 18.04
 - Graphics card: NVidia Geforce 970
 - Qt Version (if compiling): 5.5.1 snap was compiled with Ubuntu 16.04 (xenial) environment

**Comment by dgirardeau** [comment]
By definition "setGLTransformation" (and it should be explained in the method description) is only used at display time, and it doesn't change the coordinates, etc.

You have to use 'applyGLTransformation' (or similar) to actually change them.

**Comment by NeroBurner** [comment]
thx
