### ISSUE TITLE
Update qPoissonRecon submodule

### ISSUE THREAD

**Issue by Jean-Roc** [CloudCompare/CloudCompare#952]
Hi,

An upgrade of the Poisson Surface Reconstruction library to version 10 or higher (current is 12) would be great, this version added the --width flag which allows the system to compute the depth of the octree given a target depth for the finest resolution nodes.

This flag allows to limit the mesh reconstruction to the adequate octree depth in an easier way (and avoid unnecessary depth processing).

Regards,
JR

**Comment by dgirardeau** [comment]
Ok I gave it a try this week-end, but the API has drastically changed... This will ask for a lot of tinkering and debugging.

**Comment by dgirardeau** [comment]
Ok, it took me some time, but the latest version of PoissonRecon (V12) is now properly wrapped and used by CC: 2e85da4618fd7a241bd3c532dfebee74698600e4
