### ISSUE TITLE
qCSF is non-deterministic when multithreading.

### ISSUE THREAD

**Issue by dbrookes96** [CloudCompare/CloudCompare#953]
**Describe the bug**

The CSF ground filter does not give consistent results when multithreading. i.e. between runs we get slightly different ground and non-ground classifications.

**How to reproduce**

I've attached a CSV point cloud I used for testing that contains 500,000 points ([trimble_500k.zip](https://github.com/CloudCompare/CloudCompare/files/3593140/trimble_500k.zip)). For testing I'm running the CSF filter with the settings:
```
Scene = Relief
Slope processing = True
Cloth Resolution = 1.0
Max Iterations = 500
Classification Threshold = 0.5
Export Cloth Mesh = False
```
Out of 5 runs I got the following number of ground points.
```
1. 71,275
2. 71,276
3. 71,275
4. 71,275
5. 71,276
```
Before testing on CC 2.11 Alpha I tested on CC 2.10.2 Release and that had a much higher variance in the number of results. I assume this is because of the removal of the OpenMP parallel for from this issue https://github.com/CloudCompare/CloudCompare/issues/909?

**Expected behaviour**

Setting the environment variable OMP_NUM_THREADS to 1 and restarting CC 2.11 Alpha results in each run returning 71,274 ground points. I'd assume that this would be the _correct_ result?

**Additional context**

We actually use CSF from https://github.com/jianboqi/CSF in our own product (I plan to log this bug there also, but figured I better log it here as well as you guys have a modified version of that library) and found this issue through our testing. As a workaround we removed all `#pragma omp parallel for` statements from CSF (there is only a few). This resulted in seemingly consistent results between runs. I also didn't observe too much of a drop in performance which was surprising, even for a ~63 million point cloud (although CloudCompare CSF may be different).

**Your environment**
 - CC Version (or git hash/tag): v2.11 Alpha (from website)
 - OS & Version: Windows 10 x64 Enterprise 1903
 - Graphics card: -
 - Qt Version (if compiling): -

**Comment by dbrookes96** [comment]
I've also logged this with CSF (https://github.com/jianboqi/CSF/issues/21).

**Comment by dgirardeau** [comment]
I was going to say that there's no call to the 'random' instruction in this plugin, so it was probably a parallelism issue. But I see that the authors replied already, so I'll let them fix this issue if they think it's necessary (or if you convince them ;).
