### ISSUE TITLE
Error when loading LAS file with no points in it

### ISSUE THREAD

**Issue by Deguerre** [CloudCompare/CloudCompare#956]
**Describe the bug**
When loading a LAS file with zero points in it, the following message appears: "An error occurred while loading '<name of file>': nothing to load."

![image](https://user-images.githubusercontent.com/3769884/64838239-9735b180-d635-11e9-80a2-cfe47b0c4ba9.png)

**How to reproduce**
Load a file such as this.
[empty_las_file.zip](https://github.com/CloudCompare/CloudCompare/files/3608430/empty_las_file.zip)

**Expected behaviour**
Ideally, the LAS file should be loaded as a point cloud with zero points in it (which is still a point cloud). Failing that, it should never be an _error_ to try to load a well-formed LAS file even if it's a corner case.

**Your environment**
 - Version 2.9.1
 - Windows 64-bit

**Comment by dgirardeau** [comment]
I don't know what to say... What do you want to do with an empty point cloud? Because I am not sure that CC will be super happy with an empty cloud once you will have managed to load it ;) (no valid bounding box, etc.)

**Comment by Deguerre** [comment]
Yeah, hence the "failing that" qualification.

As a matter of principle, a point cloud with no points in it is no more an error than a database table with no rows in it, or an array with zero elements. But, honestly, it's more about what I _don't_ want to do. If I drag and drop 30 LAS files into CC, and 8 of them have no points in them, I don't want to have to dismiss 8 dialog boxes claiming that 8 errors occurred.

**Comment by WargodHernandez** [comment]
![image](https://user-images.githubusercontent.com/7495752/67646567-04528d00-f8ec-11e9-87cd-26d3bd990df3.png)

I went ahead and tested creating a point cloud without any points and adding it to the main DB as follows

``` C++
ccHObject* Sensors_surfaces = ccHObject::New(CC_TYPES::HIERARCHY_OBJECT, (QString("Sensors.Surfaces")).toLocal8Bit());
	ccPointCloud* testPC = new ccPointCloud((QString("Sensors.TestPointCloud")).toLocal8Bit());
	Sensors_surfaces->addChild(testPC);
	m_ccRoot->addElement(Sensors_surfaces, false);
	m_ccRoot->addElement(testPC, false);
```

And there were no apparent ill affects, nothing will be displayed obviously. and it is essentially useless, but using the various built in tools all bailed early as expected, without a system crash.
The only time it didn't behave was during save/load where it will report an error if you save the cloud by itself or will just not be in the file after saving its parent into a bin.

I don't have a specific need for no point clouds, but it doesn't seem to be a big issue.

**Comment by dgirardeau** [comment]
Can you fix that then? And track down everywhere this "rule" is enforced?

**Comment by Deguerre** [comment]
Thank you very much!
