### ISSUE TITLE
Geometric features via command line

### ISSUE THREAD

**Issue by GreKro** [CloudCompare/CloudCompare#958]
Hi Daniel !

I would like to use Compute Geometric features tool with "Feature" option  e.g. Planarity or Sum of eigenvalues via command line mode. Is there this posibility avalible ? In Comand line documentation I found comands for curvature, density and roughness options. 
Do you plan to add this functionality in the future?
I also can't find a description of these algorithms, where can I find out how they work?

Best regards,

**Comment by dgirardeau** [comment]
They are not available through the command line mode indeed. And we don't have clear plans (but juste a huge TODO list) and people are welcome to pick any task and make contributions / code updates.

Most of the measures are listed in an article: "Contour detection in unstructured 3D point clouds", Hackel et al, 2016

**Comment by GreKro** [comment]
Can you write which code files are responsible for Compute Geometric features and comand line mode ? Rough and Curvature code could be similar, maybe I can do it by myself.
Thanks for response

**Comment by dgirardeau** [comment]
Yes they are probably not that far.

The command line "commands" are all in the qCC/ccCommandLineCommands(.h/.cpp) class.

Geometric features are computed via the "ccLibAlgorithms::ComputeGeomCharacteristics" method (qCC/ccLibAlgorithms(.h/.cpp)). See how it used in mainwindow.cpp if necessary.
