### ISSUE TITLE
Using Grey field during Ascii import

### ISSUE THREAD

**Issue by ryan-brazeal-ufl** [CloudCompare/CloudCompare#959]
**Describe the bug**

When importing an Ascii file and selecting the 'Grey' attribute type for a data file column, the resulting point cloud appears to be missing the Green values (all zero) and therefore the point cloud is not being coloured with greyscale values but rather pink'ish scale values (according to someone who is colourblind).

**How to reproduce**
Steps to reproduce the behaviour - include images if relevant:
1. Create an Ascii file with only X,Y,Z,Grey data (grey data being 8 bit [0-254 values]).
2. Open/Import the Ascii file and assign the respective field (column) types (coord.X, coord.Y, coord.Z, Grey).
3. Provided your dataset has no other attribute/scalar fields, it will display with it's Colors property set to RGB. You should see your point cloud displayed in a pink'ish scale.
4. With the point cloud selected in the DB Tree, click the Edit Menu -> Colors -> Convert to Scalar field In the SF from RGB dialog that appears, make sure that R, G, and B Channel boxes are checked (Composite doesn't matter) and click OK.
5. The dataset Colors property will automatically change to Scalar field, then scroll down in the properties section so that both, the Scalar Fields section and the SF display params section, are visible.
6. In the Scalar Fields section, change the Active property to R and observe the SF display params histogram and range of values. Also notice the appearance of the point cloud. Repeat this step, selecting the G scalar field and then the B scalar field.
7. When selecting the G scalar field in the previous step, one should have noticed that all the values were zero!

**Expected behaviour**

I would expect that when importing an Ascii dataset and specifying a column as 'Grey', that the resulting RGB colourization of the point cloud would in fact be greyscale. I believe I have narrowed down the error to being caused by the lack of the Green channel for the dataset receiving the values from the data file (just like the Red and Blue channels currently are).

**Additional context**

**Your environment**
 - CC Version (or git hash/tag): 2.10.2
 - OS & Version: Mac OS X (10.14.6) and Windows 7 and Windows 10
 - Graphics card: AMD Radeon R9 (Mac) and NVidia Quadros (Windows)
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
Indeed, it was a silly bug (the green component was left null and the red one was set twice). This is fixed now: b543847c01e0fd3ef535855b3bbb073fbf6d5a0b.

The 2.11.alpha version will be updated online soon.

Thanks for the feedback.
