### ISSUE TITLE
"System error" - CC beta 2.11 alpha 10/6/2019

### ISSUE THREAD

**Issue by onitreb** [CloudCompare/CloudCompare#966]
Installed with FARO sdk option. No errors during installation.

![image](https://user-images.githubusercontent.com/2154479/66335964-fadb9380-e8f0-11e9-947f-411912f67598.png)

**Comment by dgirardeau** [comment]
Yes this error has arisen recently due to the usage of the latest Faro LS SDK... Can you try to uninstall CC, make sure the "Program Files\CloudCompare" folder has been deleted or is empty. Then restart the computer, and re-install everything (with the FARO SDK option).

**Comment by onitreb** [comment]
Following your instructions, CC now loads without the system error. (however the FARO plugin is not working correctly, but I'll open a different bug for that)

**Comment by rjanvier** [comment]
closed: see #967
