### ISSUE TITLE
Plugins are missing

### ISSUE THREAD

**Issue by epixner** [CloudCompare/CloudCompare#973]
Hy there,
I have updated CC to 2.10.2 and all the tools and plugins aren't there anymore.
especially the plugin M3C2 is needed.    

![Bildschirmfoto 2019-10-20 um 15 38 43](https://user-images.githubusercontent.com/37377782/67160299-b53ab400-f34f-11e9-8fa5-32443ed9bf36.png)

**Your environment**
 - CC Version (or git hash/tag): 2.10.2
 - OS & Version: MacOS 10.14.6
 - Graphics card: Intel Iris Graphics 6100 1536 MB

thanks

**Comment by dgirardeau** [comment]
They don't seem to be missing. They are just deactivated because you need to highlight some entities so that it activates.
