### ISSUE TITLE
How could I invert the normals of a mesh?

### ISSUE THREAD

**Issue by zihahage** [CloudCompare/CloudCompare#974]
I want to invert the normals of a mesh, but simply select the mesh and "Edit->Normal->Invert" does not work. 

**Describe alternatives you've considered**

**Is your feature request related to a problem? Please describe.**

I consulted the codes in ccMesh::transformTriNormals(), and tried to do this with a few codes modified, but it also does not work. The mesh turns black and the normal of a pre-selected triangle remains the same.

So how could I invert the normals of a mesh?

**Additional context**

**Comment by dgirardeau** [comment]
Which version are you using?

Anyway, with the latest version (2.11.alpha), you have a new method 'Edit > Mesh > Flip triangles' to actually flip the vertices order. Then you can call the 'Edit > Normals > Compute' method, and you should obtain normals in the right direction...
