### ISSUE TITLE
can't guess file format: unhandled file extension 'jpg' or 'png'

### ISSUE THREAD

**Issue by Seaeven** [CloudCompare/CloudCompare#980]
When I load a jpg or png file, I am prompted ‘can't guess file format: unhandled file extension 'jpg' or 'png'’

**My environment**
 - Get the code:　`git clone --recursive https://github.com/cloudcompare/trunk.git`
 - Qt Version :　5.9.5

Most of the answers on the Internet are for the inability to open pcd files. It is difficult to find out about the failure of opening the picture. Please help me!

**Comment by WargodHernandez** [comment]
![image](https://user-images.githubusercontent.com/7495752/67794587-193d3680-fa3a-11e9-97e9-205ddab2e87f.png)

When on the open screen do you have an Image (*) item with a list of supported formats? 

CloudCompare\libs\qCC_io\ImageFileFilter.cpp
creates the image supported extensions list starting at line 68

if you could modify the following:

```C++
for (auto &format : formats)
		{
			imageExts.append( QStringLiteral("*.%1").arg(format.data()) );
		} 
```

Into:

```C++
ccLog::Print("Image Formats Available");
for (auto &format : formats)
		{
			imageExts.append( QStringLiteral("*.%1").arg(format.data()) );
			ccLog::Print(format.data());
		}
ccLog::Print("End Image Formats");
```

and then report back what shows in the console at startup

**Comment by Seaeven** [comment]
Thank you Mr. Brown.&nbsp;I am very happy to see your reply.&nbsp;I found out that the reason I reported earlier was because the format was chosen to open All(*.*)



I can open the image when I select the Image format.&nbsp;










Wish you a happy working day!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chris Brown"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月30日(星期三) 凌晨2:03
收件人:&nbsp;"CloudCompare/CloudCompare"<CloudCompare@noreply.github.com&gt;;
抄送:&nbsp;"译文"<781853113@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CloudCompare/CloudCompare] can't guess file format: unhandled file extension 'jpg' or 'png' (#980)





 
When on the open screen do you have an Image (*) item with a list of supported formats?
 
CloudCompare\libs\qCC_io\ImageFileFilter.cpp
 creates the image supported extensions list starting at line 68
 
if you could modify the following:
 for (auto &amp;format : formats) 		{ 			imageExts.append( QStringLiteral("*.%1").arg(format.data()) ); 		} 
 
Into:
 ccLog::Print("Image Formats Available"); for (auto &amp;format : formats) 		{ 			imageExts.append( QStringLiteral("*.%1").arg(format.data()) ); 			ccLog::Print(format.data()); 		} ccLog::Print("End Image Formats");
 
and then report back what shows in the console at startup
