### ISSUE TITLE
Can CC project a point cloud in the same coordinate system onto an image?

### ISSUE THREAD

**Issue by Seaeven** [CloudCompare/CloudCompare#981]
Hello everyone! I want to project the point cloud in the same coordinate system on the image and modify the point cloud according to the image. I don't know if cc provides such a function.
Similar to the picture below:
https://github.com/EpsAvlc/cam_lidar_fusion/blob/master/resource/proj.png

**Comment by dgirardeau** [comment]
To do that, you'll need to know the sensor position at least. Either you have a file format that already contains that information (mostly Faro and PTX, but also E57 if you use the latest 2.11.alpha version) or you can create a 'sensor' object (with Edit > Sensors > TLS/BGL > Create) and input at least the sensor 'center'.

This will allow you to activate the 'bubble view' mode (b) which looks like that. You may have also to tinker  with the camera field of view, etc.
