### ISSUE TITLE
Question: Export M3C2-pointcloud with attributes 

### ISSUE THREAD

**Issue by epixner** [CloudCompare/CloudCompare#996]
Hy there, 
i am using M3C2 for the comparison of topographical changes from TLS-pointclouds. 
When exporting (save) the M3C2-pointcloud, i get only a "Default"-value in the scalar field:
 
![Bildschirmfoto 2019-11-09 um 10 53 99](https://user-images.githubusercontent.com/37377782/68526826-16ff9580-02e0-11ea-91cb-d88e92791df0.png)

What i expect, is to choose the scalar field like in the generated PC before the export:  

<img width="804" alt="Bildschirmfoto 2019-11-09 um 10 22 37" src="https://user-images.githubusercontent.com/37377782/68526834-2c74bf80-02e0-11ea-924a-9e5699c651bd.png">

Is there a way to export the M3C2-pc with the attributes like "Distance" or "distance uncertainity"?

Thanks and Regards

**Comment by dgirardeau** [comment]
Yes, simply export it to an ASCII file. You will have X, Y, Z and all the scalar fields values for each point on a single line.

**Comment by epixner** [comment]
> Yes, simply export it to an ASCII file. You will have X, Y, Z and all the scalar fields values for each point on a single line.

thank you for the fast response. I thought it will generate a Grid-File with ASCII, but i tried and this is what i am looking for.
