### ISSUE TITLE
Command Line Save Point Cloud with Normals

### ISSUE THREAD

**Issue by petrasvestartas** [CloudCompare/CloudCompare#997]
I am trying to export pointcloud to .ply with normals, but no normals are saved, just points.

For command line I wrote:
-COMPUTE_NORMALS -O C:\Scans\CloudCompare\Fork.e57 -C_EXPORT_FMT PLY -MERGE_CLOUDS

Am I saving the file in a wrong way or it is not possible to save pointlcloud with normals?

**Comment by dgirardeau** [comment]
Warning, the "COMPUTE_NORMALS" method only works with Faro, DP and PTX files (E57, even structured, are not supported yet - see https://www.cloudcompare.org/doc/wiki/index.php?title=Command_line_mode).

You have to use '-OCTREE_NORMALS' (and optionally -ORIENT_NORMS_MST)

**Comment by petrasvestartas** [comment]
Thanks this worked according to the thread:
C:\Program Files\CloudCompare>CloudCompare 
-O C:\Scans\CloudCompare\Fork.e57  -NO_TIMESTAMP -C_EXPORT_FMT PLY -MERGE_CLOUDS -OCTREE_NORMALS 10 -ORIENT_NORMS_MST 6

However the normals are not the same as with cloudcompare method:
![Com](https://user-images.githubusercontent.com/18013985/68592562-0dbb2800-049c-11ea-9cc2-58c9f45ec752.png)

How I could produce totally the same calculation?

Also Poisson mesh reconstruction is not possible via command-line?

**Comment by dgirardeau** [comment]
Are you using the exact same parameters as in the GUI version? (i.e. a radius of 10?)

And indeed PoissonRecon is not available through the command line. Actually a command line version of PoissonRecon already exists and is maintained by the author: http://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version12.00/
