### ISSUE TITLE
Rasterize, contour plot, missing contour lines

### ISSUE THREAD

**Issue by vosvos** [CloudCompare/CloudCompare#998]
**Describe the bug**
I am using rasterize tool, contour plot to make contour lines for Lidar data (in .las file).
After running "generate" - multiple contour lines are missing.
I can send you .las file using wetransfer.com (1.6 GB)

**How to reproduce**
1. Open .las file;
2. Change "Scalar fields" active to "Classification";
3. Filter by value scalar fields from 0 to 2.5;
4. Run rasterize tool with default settings;
5. Generate contour plot with step 2.5.

**Expected behaviour**
All contour lines must be visible and with 2.5 distance between.

**Additional context**
![cc-contours](https://user-images.githubusercontent.com/1575814/68669885-4d454b00-0554-11ea-8e84-f2ad49f273a6.png)
Hand drawn red line shows - missing contour lines area.

**Your environment**
 - CC Version (or git hash/tag): 2.10.2
 - OS & Version: macOS 64bit (10.14).
 - Graphics card: Intel Iris Graphics 6100

**Comment by dgirardeau** [comment]
Just in case, have you tried lowering the 'min vertex count' parameter to 2?

Otherwise, yes, you can send me the dataset (or a smaller one if you are still able to reproduce the issue with a subsampled version of the Cloud ;) --> admin [at] cloudcompare.org

**Comment by dgirardeau** [comment]
Thanks for the cloud!

But "sadly" it works on my side (with the Windows 2.11.alpha version...). I don't have a Mac myself.

I don't know if the macOS version relies on GDAL do extract contour lines by the way! Maybe this explains the difference? (@asmaloney: can you confirm?)

Or a bug fixed since version 2.10.2? (couldn't find any evidence of that, but who knows...).

**Comment by vosvos** [comment]
Thank you! 

I have installed 2.10.2 version on Windows and there was no problems with contours.
So it looks like macOS version bug.

**Comment by asmaloney** [comment]
@dgirardeau The macOS version does include GDAL.

CloudCompare 2.10.2 uses GDAL v2.4.0 from homebrew.

**Comment by dgirardeau** [comment]
Thanks @asmaloney! That's weird then. But the second explanation is still possible of course (the fixed bug in v2.11 👼 )
